### ISSUE TITLE
Devolo

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/AdapterRequests#10]
https://github.com/kdietrich/node-devolo

Question from Jey Cee:
Basiert doch auf Z Wave und dafür gibt es ja schon einen Adapter.
Brauchen wir dann noch extra einen Speziell für Devolo?

Migrated from Trello with 1 vote

**Comment by justr1** [comment]
Wenn ich die Beschreibung des Zwave-Adapters richtig verstehe, basiert dieser ja auf Zwave-USB-Sticks. Das Devolo-System hat aber einen dedizierten Hub/Host ("Zentrale").

**Comment by justr1** [comment]
??? Bitte noch mal ohne Autokorrektur.  ;-)

**Comment by Apollon77** [comment]
Hehe ... die Frage ist ob man das Gateway/zentrale dann noch braucht

**Comment by justr1** [comment]
Das Gateway ist im Gegensatz zum Stick halt schon da und ich wüsste auch gar nicht, ob der Stick am Mac überhaupt läuft. Abgesehen davon bräuchte er einen der eh viel zu wenigen USB-Ports.

**Comment by Apollon77** [comment]
Homebridge modules exist: homebridge-devolo as example.

Please check if the new ioBroker.ham Adapter can help here: see https://forum.iobroker.net/viewtopic.php?f=36&t=14972

**Comment by justr1** [comment]
Coole Sache! Das Modul "homebridge-devolo" funktioniert mit dem ham-Adapter top. Kleiner Hinweis an Interessierte:
Die beim devolo-pluging beschriebenen Einstellungen
```javascript
"platforms": [
  {
    "platform" : "Devolo",
    "name" : "Devolo",
    "host" : "x.x.x.x",
    "email" : "mail@host.com",
    "password" : "topsecret123"
  }
]
```
reichen nicht aus. Nach der Installation muss man die Log-Stufe der ham-Instanz temporär noch auf "Debug" setzen. Dann liefert das Log nicht nur zusätzlich benötigte Parameter, sondern auch gleich noch die richtigen Werte (hier anonymisiert ;-) ):
```javascript
    "uuid": "04XXXXXX-CXXX-4XXX-8XXX-FDXXXXXXXXXX",
    "gateway": "140XXXXXXXXXXXXX",
    "passkey": "568e5fXXXXXXXXXXXXXXXXXXXXXXXXXX"
```

**Comment by MikeyRZW** [comment]
Hi,
unter Support of new devices steht folgendes:

![grafik](https://user-images.githubusercontent.com/45110596/48662519-5c013b00-ea83-11e8-8579-17ee135242fe.png)

den Config Parameter habe ich in die Configdatei eingetragen..., aber wie führe ich im ioBroker ein Command aus?

Könnt ihr einem Anfänger auf's Pferd helfen? :)

**Comment by derbaum123** [comment]
ich habe den homebridge Adapter 1.1.2 hinzugefügt und den Wrappermodus eingestellt.

als zusätzliches Modul: "homebridge-devolo" eingetragen

Die Konfigurationsdatei wie folgt ergänzt:
[
    {
      "platform": "Devolo",
      "name": "Devolo",
      "host": "192.168.178.74",
      "email": "meinedevolomailadresse@xxx.de",
      "password": "meindevolopassword",
"uuid": "25Fxxx-CxxF-4xxx-9xx2-82xxxEE15xxxx",
"gateway": "1703xxxxxxxxxxxx",
"passkey": "CXxxxxxxxxxxqQ"
    }
  ]
}

Leider komme ich an der Stelle nicht weiter.
Die Log-Datei verrät mir einge Fehler, mit denen ich nichts anfangen kann:


host.raspberrypi	2020-04-15 10:46:24.540	info	instance system.adapter.ham.0 terminated with code 156 (156)
host.raspberrypi	2020-04-15 10:46:24.540	error	Caught by controller[1]: }
host.raspberrypi	2020-04-15 10:46:24.540	error	Caught by controller[1]: code: 'ECONNRESET'
host.raspberrypi	2020-04-15 10:46:24.539	error	Caught by controller[1]: at TCP.<anonymous> (net.js:672:12) {
host.raspberrypi	2020-04-15 10:46:24.539	error	Caught by controller[1]: at Socket.emit (events.js:322:22)
host.raspberrypi	2020-04-15 10:46:24.539	error	Caught by controller[1]: at Socket.socketCloseListener (_http_client.js:400:25)
host.raspberrypi	2020-04-15 10:46:24.539	error	Caught by controller[1]: at connResetException (internal/errors.js:608:14)
host.raspberrypi	2020-04-15 10:46:24.539	error	Caught by controller[1]: Error: socket hang up
host.raspberrypi	2020-04-15 10:46:24.538	error	Caught by controller[0]: [2020-4-15 10:46:12] Plugin /opt/iobroker/node_modules/homebridge-plugin-wrapper package.json does not contain the keyword 'homebridge-plugin'.
ham.0	2020-04-15 10:46:24.047	warn	(31970) Exception: Error: socket hang up
ham.0	2020-04-15 10:46:24.046	error	at TCP.<anonymous> (net.js:672:12)
ham.0	2020-04-15 10:46:24.046	error	at Socket.emit (events.js:322:22)
ham.0	2020-04-15 10:46:24.046	error	at Socket.socketCloseListener (_http_client.js:400:25)
ham.0	2020-04-15 10:46:24.046	error	at connResetException (internal/errors.js:608:14)
ham.0	2020-04-15 10:46:24.046	error	(31970) Error: socket hang up
ham.0	2020-04-15 10:46:24.046	error	(31970) uncaught exception: socket hang up
ham.0	2020-04-15 10:46:24.016	info	(31970) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
ham.0	2020-04-15 10:46:24.014	info	(31970) terminating
ham.0	2020-04-15 10:46:24.002	info	(31970) cleaned everything up...
host.raspberrypi	2020-04-15 10:46:23.995	info	stopInstance system.adapter.ham.0 send kill signal
ham.0	2020-04-15 10:46:24.000	info	(31970) Got terminate signal TERMINATE_YOURSELF
host.raspberrypi	2020-04-15 10:46:23.994	info	stopInstance system.adapter.ham.0 (force=false, process=true)
host.raspberrypi	2020-04-15 10:46:23.993	info	"system.adapter.ham.0" disabled
ham.0	2020-04-15 10:46:13.037	debug	(31970) [2020-4-15 10:46:13] [Devolo] HBDevoloPlatform > Central Unit found.
ham.0	2020-04-15 10:46:13.033	debug	(31970) Websocket open
ham.0	2020-04-15 10:46:12.916	debug	(31970) Trying to connect to socket.
ham.0	2020-04-15 10:46:12.844	debug	(31970) [2020-4-15 10:46:12] Loading 0 accessories...
ham.0	2020-04-15 10:46:12.825	debug	(31970) [2020-4-15 10:46:12] [Devolo] HBDevoloPlatform > Searching for Devolo Central Unit.
ham.0	2020-04-15 10:46:12.819	debug	(31970) [2020-4-15 10:46:12] [Devolo] Initializing Devolo platform...
ham.0	2020-04-15 10:46:12.818	debug	(31970) [2020-4-15 10:46:12] Loading 1 platforms...
ham.0	2020-04-15 10:46:12.810	debug	(31970) [2020-4-15 10:46:12] ---
ham.0	2020-04-15 10:46:12.809	debug	(31970) [2020-4-15 10:46:12] Registering platform 'homebridge-devolo.Devolo'
ham.0	2020-04-15 10:46:12.807	debug	(31970) [2020-4-15 10:46:12] Loaded plugin: homebridge-devolo
ham.0	2020-04-15 10:46:11.648	info	(31970) All Libraries installed/updated
ham.0	2020-04-15 10:46:11.647	info	(31970) Install/Update homebridge-devolo
ham.0	2020-04-15 10:46:11.646	info	(31970) Install/Update the following Libraries: homebridge-devolo
ham.0	2020-04-15 10:46:11.619	info	(31970) starting. Version 1.1.2 in /opt/iobroker/node_modules/iobroker.ham, node: v12.16.2
ham.0	2020-04-15 10:46:11.386	debug	(31970) statesDB connected
ham.0	2020-04-15 10:46:11.385	debug	(31970) States connected to redis: 127.0.0.1:9000
ham.0	2020-04-15 10:46:11.377	debug	(31970) States create System PubSub Client
ham.0	2020-04-15 10:46:11.374	debug	(31970) States create User PubSub Client
ham.0	2020-04-15 10:46:11.369	debug	(31970) Redis States: Use Redis connection: 127.0.0.1:9000
ham.0	2020-04-15 10:46:11.366	debug	(31970) objectDB connected
ham.0	2020-04-15 10:46:11.361	debug	(31970) Objects connected to redis: 127.0.0.1:9001
ham.0	2020-04-15 10:46:11.348	debug	(31970) Objects client initialize lua scripts
ham.0	2020-04-15 10:46:11.347	debug	(31970) Objects create User PubSub Client
ham.0	2020-04-15 10:46:11.346	debug	(31970) Objects create System PubSub Client
ham.0	2020-04-15 10:46:11.342	debug	(31970) Objects client ready ... initialize now
ham.0	2020-04-15 10:46:11.312	debug	(31970) Redis Objects: Use Redis connection: 127.0.0.1:9001
host.raspberrypi	2020-04-15 10:46:10.595	info	instance system.adapter.ham.0 started with pid 31970


Kann mir jemand sagen, was korrigieren muss?

Danke und LG

**Comment by mcm1957** [comment]
Zitat:
Das Modul "homebridge-devolo" funktioniert mit dem ham-Adapter top. 

Falls hier doch noch (immer) ein neuer Adapter benötigt wird, bitte ein neues Issue anlegen.
