### ISSUE TITLE
Support of windy.com as widget for vis and material

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/AdapterRequests#100]
https://api4.windy.com/

**Comment by dwm66** [comment]
Would be cool!

**Comment by GermanBluefox** [comment]
You can make it with html iframe

пт, 31 авг. 2018 г., 10:51 dwm66 <notifications@github.com>:

**Comment by GermanBluefox** [comment]
https://youtu.be/MwkLAvADDe8

пт, 31 авг. 2018 г., 12:14 Smart Home - ioBroker <dogafox@googlemail.com>:

**Comment by Apollon77** [comment]
closing as duplicate of #215 (because this has no votes, the other has some)
