### ISSUE TITLE
Google Home Adapter

### ISSUE THREAD

**Issue by Kev0123** [ioBroker/AdapterRequests#103]
Integration for google home, just like the alexa skill.

https://forum.iobroker.net/viewtopic.php?f=23&t=4902&hilit=google+home

**Comment by emddummi** [comment]
Hardware needed?

**Comment by Apollon77** [comment]
nope ...

**Comment by GermanBluefox** [comment]
Here is the Problem:
https://github.com/actions-on-google/smart-home-nodejs/issues/176

Am Mo., 5. Nov. 2018, 21:07 hat Ingo Fischer <notifications@github.com>
geschrieben:

**Comment by Apollon77** [comment]
Bitte alle die Google Home gescheit haben wollen hier mitmachen um Druck auf Google zu bekommen:

https://forum.iobroker.net/viewtopic.php?f=8&t=18762

**Comment by emddummi** [comment]
Hat die Aktion denn jetzt Erfolg gehabt? Der thread ist ja weg...

**Comment by emddummi** [comment]
Ich meinte er ist nicht mehr angepinnt 😁😉

**Comment by GermanBluefox** [comment]
Action was sent to verification today. Actually only On/Off devices are supported.

**Comment by emddummi** [comment]
Wie lange dauert es dann normalerweise bis man den Dienst in der home App sehen kann?

**Comment by DutchmanNL** [comment]
Das kann ein paar Tage, bis 2 Wochen dauern abwarten auf Google

**Comment by emddummi** [comment]
Ich hasse es Geduld zu haben 😉

Finde ich den Service dann unter dem Namen ioBroker oder musstest du den umbenennen @GermanBluefox?

**Comment by Maranja** [comment]
Wie ist denn eigentlich der aktuelle Stand der Dinge? Hat Google sich mittlerweile gerührt?
Ich warte sehnsüchtig ;-)

**Comment by DutchmanNL** [comment]
> Hat Google sich mittlerweile gerührt?

@GermanBluefox ist noch im Gange mit google, leider nicht so leicht :/

**Comment by zim32** [comment]
Iobroker is great software and I want to contribute, but a lot of conversations and forums are in german. Very sad.

**Comment by Apollon77** [comment]
You saw trhe english subforum?

**Comment by zim32** [comment]
I am using iobroker, but found that many questions i ask in google goes to german pages where I can't understand anything. Of course this is your biz and your choice but i think if more discussions will be in english more people will be involved in it. Good luck to you guys you make great things.

**Comment by Apollon77** [comment]
Hi zim32,

simply ask the questions in the english forum and we will be happy to support and answer in english. ioBroker was mainly growing in the past from germany and other german speaking countries (and russian speaking countries) ... And yes in the meantime we are really proud to have more and more international users, but as you also said they are not that active in forum till now :-(. And here the challenge starts:
It is very hard to convince non-english-native-speakers to start writing their questions in english ;-) And if also the english-native-speakers do not start with writing in forum so that a english-speaking community can "be born" no other english speaking users start ...

So I can only invite anyone to start contributing ion english in the forum - only that way we can start to build an english speaking forum. The Mods and Admins are more then willing also to contribute in english! But users need to start :-)

**Comment by DutchmanNL** [comment]
Yes please @zim32 come to the forum and ask your questions there in the English section, a lot of users are willing to help but if no questions are raised :)

the roots are in Germany but the platforms has  a lot of global users already (even Chinese :))

**Comment by ldittmar81** [comment]
Here you can find us: https://forum.iobroker.net/category/16/english

**Comment by zim32** [comment]
Thanks

**Comment by FiveKnive** [comment]
Gibt es schon was Neues? Laut Bluefox kann man ja schon Geräte mit an und aus hinzufügen. Wie kann ich das in der Google Home App einrichten? Bei Diensten finde ich iobroker leider nicht. Ich habe irgendwo online gesehen, dass manche den Dienst in der App haben.

**Comment by DutchmanNL** [comment]
> Wie kann ich das in der Google Home App einrichten? 

Leider noch garnicht da google ein sehr kompliziertes approval verfahren hat um einen neuen dienst auf zu führen. Im Dev laufen die an/aus befehle aber halt nicht durch google acceptiert und der weg dorthin ist leider nicht leicht

**Comment by FiveKnive** [comment]
OK danke für die Aufklärung. Also ist es nicht möglich das mal eben selbst einzurichten nehme ich an. Kann man etwa abschätzen wie lange das noch dauert oder das Ganze irgendwie unterstützen?

**Comment by Kev0123** [comment]
Nearly one year later....
Are there any news?
I'm a bit worried that this implementation won't ever happen.

**Comment by Apollon77** [comment]
Please stay tuned, with a new contact on Google side things could go better ... we are on it

**Comment by reptil1990** [comment]
Today my LG TV got an update for google assistant so now i am also in need for an adapter :D
Thanks guys

**Comment by Kev0123** [comment]
FINALY its listed under the HomeApp.  How to sign in with wich credentials?

**Comment by Kev0123** [comment]
@Appollon77 where to place issues related to this adapter?

**Comment by Apollon77** [comment]
Discuss in forum first please. If a bug then iot adapter is the correct place.

**Comment by ggraziotti** [comment]
Where to find the Google Home adapter ?

**Comment by DutchmanNL** [comment]
> Where to find the Google Home adapter ?

https://github.com/TA2k/ioBroker.iot
