### ISSUE TITLE
Reptier Adapter

### ISSUE THREAD

**Issue by ludino1505** [ioBroker/AdapterRequests#106]
Hallo,

3D Druck wird immer Populärer, kann man nicht ein adapter dafür entwickeln?

**Comment by foxriver76** [comment]
Es gibt soweit ich weiß einen octoprint Adapter, falls dieser dir hilft. Wird natürlich noch ein Pi benötigt, dafür scheinen die Möglichkeiten nahezu unbegrenzt.

**Comment by ludino1505** [comment]
Hallo,

In diesem Thema läuft es so, man kann am pi octoprint oder repetier
installieren, ich habe mich für repetier entschieden, mal schauen ob man
was machen kann.

Max Hauser <notifications@github.com> schrieb am Mo., 10. Sep. 2018, 17:12:

**Comment by coyote1** [comment]
Habe da mal was gebastelt:
https://github.com/coyote1/iobroker.repetier

siehe hier: https://forum.iobroker.net/viewtopic.php?f=36&t=20724
