### ISSUE TITLE
Brematic Adapter

### ISSUE THREAD

**Issue by FArtBtl112** [ioBroker/AdapterRequests#107]
Ich würde gerne meine Brennenstuhl Funksteckdosen (selbstlernende) über Brematic 433Mhz GWY
mit dem iobroker verbinden

Meine Hardware Pi 3+ mit IoBroker , Brennenstuhl Gateway Brematic 433 GWY , Brennenstuhl Funksteckdosen RCRCE1 1011 (Ohne Dip Schalter).

Ich würde gerne die Funksteckdosen so wie meine AVM Steckdosen über Siri und IOBroker steuern.

**Comment by FArtBtl112** [comment]
Meine Hardware Pi 3+ mit IoBroker , Brennenstuhl Gateway Brematic 433 GWY , Brennenstuhl Funksteckdosen RCRCE1 1011.

Ich würde gerne die Funksteckdosen so wie meine AVM Steckdosen über Siri und IOBroker steuern.

**Comment by helfi9999** [comment]
Hi, habe mir den Sonoff RF Bridge mit Tasmota Firmware besorgt und siehe da kann meine ganzen Funksteckdosen ob Brennenstuhl oder andere mit ioBroker nutzen.

**Comment by mcm1957** [comment]
Bei diesem Issue fehlen derzeit entsorechende Infos / Links zum Hersteller. Außerdem scheint es so, dass das genannte Gateway nicht mehr verfügbar ist, Ich erlaube mir daher hier zu schließen.

**Bitte ein neues Issue mit aktuellen Infos erstellenm, falls hier noch ein Adapter benötigt wird. Danke.**

**Comment by DerrowBond** [comment]
https://ifoedit.com/RaspiBrematicEn.html
