### ISSUE TITLE
Widget zum Editieren von JSON Objekten

### ISSUE THREAD

**Issue by dwm66** [ioBroker/AdapterRequests#108]
Bei Scripts oder Adaptern kommt es oft vor, dass es praktisch wäre, Konfigurationsdaten als JSON Objekt in einem Datenpunkt zu speichern.
Ein Beispiel wäre das Heizungsscript mit den Temperaturprofilen, das einfach als JSON Objekt darstellbar ist.
Ein Widget, mit dem man solche JSON Objekte editieren kann, würde die Integration in VIS sehr einfach gestalten.

Eine Basis dafür könnte free jqgrid sein:
https://github.com/free-jqgrid

**Comment by GermanBluefox** [comment]
Ich glaube nicht dass es vernünftig wäre.

пт, 31 авг. 2018 г., 11:06 dwm66 <notifications@github.com>:

**Comment by Apollon77** [comment]
Wäre vllt die bessere Idee den Weg "Javascript kann messages empfangen" und dann eher ein Widget um messages zu schicken oder so?!

**Comment by dwm66** [comment]
Hm ... 
Vielleicht nochmal kurz zum Problem ...
Ich verwende für die Steuerung der Heizung(en) sowas Ähnliches wie looxers Heizungsscript ... allerdings werden bei mir die Konfigurationen in JSON beschrieben, im Moment "hardcoded" im Javascript selbst.
Ein Beispiel:
`var ProfilBuero = {
    ProfileMap: [ { Mode: 2, Profil: "Normal" },
                  { Mode: 3, Profil: "Homeoffice"},    
                  { Mode: 6, Profil: "Abwesend" },
                  { Mode: 7, Profil: "RampUp" }
        ],
    ProfileSet: {
        Normal: [ 
            { zeit: "08:00", sp: 18.5},
            { zeit: "22:00", sp: 18.5}
        ],
        Homeoffice: [
            { zeit: "08:30", sp: 21},
            { zeit: "19:00", sp: 18.5},
            { zeit: "22:00", sp: 18.5},
        ],
        Abwesend: [
            { zeit: "00:00", sp: 14}
        ],
        RampUp: [
            { zeit: "00:00", sp: 14},
            { zeit: "15:00", sp: 14.5},
            { zeit: "16:00", sp: 15},
            { zeit: "17:00", sp: 15.5},
            { zeit: "18:00", sp: 16},
            { zeit: "19:00", sp: 16.5},
            { zeit: "20:00", sp: 17},
            { zeit: "21:00", sp: 17.5},
            { zeit: "22:00", sp: 18},
            { zeit: "23:00", sp: 18.5}
        ],
    }
};

var ProfilMedienzimmer = {
    ProfileMap: [ { Mode: 2, Profil: "Normal" },
                  { Mode: 6, Profil: "Abwesend" },
                  { Mode: 7, Profil: "RampUp" }
        ],
    ProfileSet: {
        Normal: [ 
            { zeit: "00:00", sp: 17}
        ],
        Abwesend: [
            { zeit: "00:00", sp: 14}
        ],
        RampUp: [
            { zeit: "00:00", sp: 14},
            { zeit: "18:00", sp: 14.5},
            { zeit: "19:00", sp: 15},
            { zeit: "20:00", sp: 15.5},
            { zeit: "21:00", sp: 16},
            { zeit: "22:00", sp: 16.5},
            { zeit: "23:00", sp: 17}
        ],
    }
};
`
Ich möchte das eben nicht auf die vielen Datenpunkte und Widgets aufteilen (hab in meiner Visualisierung jetzt schon einen Wust ...). Also war die Idee, solche (JSON) Konfigurationsdaten über ein Widget komfortabel editieren zu können.
Ich bin nicht sicher, ob "Widget schickt Message" das abdeckt, obwohl ...
Meine Experimente bis jetzt waren mal einen Service zu implementieren, um mit jqgrid die Daten zu editieren, und das dann als IFRAME einzubinden ... liegt etwas auf Eis, bis ich mal Zeit dazu finde :)
