### ISSUE TITLE
Shelly 1 & 2 Products

### ISSUE THREAD

**Issue by ThorstenLM** [ioBroker/AdapterRequests#109]
it would be nice to have these shelly 1 & 2 products in iobroker without flashing them with tasmota.
https://shelly.cloud/

They are small and work perfektly, better too handle like a sonoff basic. They fit perfekt in wall behind a light switch.

**Comment by ThorstenLM** [comment]
http://forum.creationx.de/forum/index.php?thread/980-shelly-1-open-source-wi-fi-switch/

**Comment by Apollon77** [comment]
To really have an adapter without Tasmota an info about the direct "API" would be needed

**Comment by ThorstenLM** [comment]
sowas wie das hier:
http://shelly-api-docs.shelly.cloud/#common-http-api

**Comment by ThorstenLM** [comment]
Okay. Aber das was ich bis jetzt von einem Freund gesehen habe, sind die Dinger super klein und passen auch in fast jede Dose von einem Lichtschalter. Klar mit Tasmota kann man sie Flashen, geht auch einfach mit der aktuellen Version und die Shellys funktionieren einwandfrei. Hab mir welche bestellt, wann die allerdings kommen steht noch in den Sternen da die neue Produktion erst um den 12.09. fertig ist... 

Wenn es dafür dann noch einen Adapter für iobroker gäbe der funktioniert ohne sie zu Flashen wäre natürlich die Krönung schlechthin.

**Comment by Apollon77** [comment]
Naja das einfachste wäre ein kleines eigenes Javscriptchen. ein HTTP Befehl mittels "request" machen und Antwort parsen . Wäre jetzt nicht das Problem :-)

**Comment by ThorstenLM** [comment]
Davon hab ich leider null Ahnung :-)

**Comment by Apollon77** [comment]
Solche use-cases gibt es zuhauf themen im forum.
such mal "request" und sowas

**Comment by Smarti15** [comment]
Wäre auch an den Dingern interessiert. Hab grad nen super Video drüber gesehen. Dann könnte man endlich verhindern, wenn die in die Schalterdose passen, das nen Besucher ausversehen ständig die HUE oder Tradfri dauerhaft ausschalten kann ;)

https://www.youtube.com/watch?v=MBR2HxEqL9w

**Comment by Apollon77** [comment]
cooles Video, aber zur letzten Aussage? Wie verhindert man das Besucher wirklich schalten? Dazu bräuchte es ja ein "schalterbetätigung sendet info aber lässt Last eingeschaltet" Modus den ich nicht gesehen habe.

Anderersits interessant ist der Fakt das die App eine Schalterbetätigung des echten Schalters direkt mitbekommen hat. Da müsste man mal mitschneiden was die App an Nachrichten bekommt, nicht das doch ein "push-Weg "existiert :-)

**Comment by Smarti15** [comment]
Hm na ich Video kann man ja den normalen Lichtschalter betätigen und der Shelly merkt das und kann trotzdem per Software die Lampe einschalten, egal wie der Schalter steht. Hängt der Shelly vielliecht vor dem Schalter?

**Comment by Apollon77** [comment]
Achso, ja klar Du kannst per Schalter UND per Software schalten.

naja mal schauen. Wäre cool zu wissen wie die app so schnell den Statuswechsel vom Schalter mitbekommt. Hat jemand so ein Teil schon da?

**Comment by Apollon77** [comment]
Found:

CoAP
Shelly devices broadcast their state in the local network over UDP messages. If you require real time status updates or have other uses for CoAP-based signaling, please ask for additional details.

... do we may ask? ;-)

**Comment by Apollon77** [comment]
Ich habe die Entwickler mal angeschrieben. Mal schauen was wir rausbekommen

**Comment by Smarti15** [comment]
Super, danke! Bin mal gespannt. Wäre echt super die Shellys in den ioBroker zu integrieren.  :)

**Comment by LJSven** [comment]
Würde mich auch interessieren! #

**Comment by Apollon77** [comment]
@schmupu und ich sind schon dran. Die Dinger scheinen cool zu sein und hat gerade nen eigenen Anwendungsfall für sie :-)

**Comment by Smarti15** [comment]
Na bin gespannt, wäre echt super

**Comment by Apollon77** [comment]
Do someone already have such a device at Home?

**Comment by Fl0ca** [comment]
Die Firmware der Shellys soll in kürze mit MQTT erweitert werden, spätestens dann sollte es funktionieren mit iobroker :)

**Comment by Smarti15** [comment]
Hier wird dein Shelly1 mit Tasmota geflasht, jetzt wäre noch interessant ob das Teil im Sonoff Adapter vom ioBroker erkannt wird :)

https://www.youtube.com/watch?v=sIVjeYZeLNU

**Comment by Apollon77** [comment]
Adapter ist in Arbeit und wird mit Original-Firmware funktionieren sobald die Geräte einmal im "Heim-WLAN" (gleiches Netzwerk wie iobroekr server) sind. Warten noch ne Woche oder so, dann haben wir vllt ne preview

**Comment by Smarti15** [comment]
Oh prima, dann bestell ich mir mal so ein Teil und bin gern bereit als Tester herzuhalten :)

**Comment by LJSven** [comment]
Ich habe einen Shelly 1 / original FW zu Hause liegen. Will ihn eigentlich gern nutzen ohne zu flashen

**Comment by flippo200** [comment]
Werdet Ihr auch einen Iobroker-Adapter für den Shelly4Pro rausbringen?

**Comment by flippo200** [comment]
Danke, das meinte ich. ;)
Du wolltest wissen ob wer was von Shelley hat...
Ich habe zwei Shelly1, zehn Shelly2 (als Rolladenschalter) und zwei Shelly4pro.

**Comment by FrodoBernd** [comment]
Moin zusammen,
habe einen Shelly2 im Einsatz.
Aktuell noch über den Alexa2 Adapter gesteuert über iobroker.

**Comment by Apollon77** [comment]
Ganz kurz zum Stand:
* Kommunikation tut, Geräte werden im Netzwerk automatisch erkannt (UDP, iobroker muss also im gleichen Netz sein wie die Geräte sonst schwierig)
* Live updates wie in der App, (kein Polling, daher aber die UDP Thematik oben)
* Objekte und States werden automatisch passend zum gerätetyp angelegt.
* Die ganzen Relay-Geräte konnte ich testweise auch schon schalten, stromverbrauch wird angezeigt, da ist @schmupu aber noch dran das sauber zu implementieren

Also sind schon recht weit und lehne mich mal aus dem Fenster und sage "gegen Wochenende könnte man vllt was haben zum testen" :-)

**Comment by schmupu** [comment]
Jetzt fühle ich unter Druck gesetzt😏 Wochenendbeschäftigung steht damit fest

**Comment by Apollon77** [comment]
@schmupu hat gerade den Adapter veröffentlicht zum testen ---> https://forum.iobroker.net/viewtopic.php?f=36&t=17059

Da geht es jetzt weiter
