### ISSUE TITLE
Volvo On Call Adapter

### ISSUE THREAD

**Issue by meden01** [ioBroker/AdapterRequests#110]
Hi all,
Volvo has, similar to BMW Connected Drive, his own cloud solution for controlling features of the cars with VOC enabled. Many important information is available on the Android and iOS App, like service demands, fuel, any kind of issues, controls for horn, door locks, head lights etc. Since the amount of hybrid cars is increasing, also the charging status is an important information, which could be used to control push messages (not included in the app) as well as controlling the charging cycle at home via homematic actors. Has anybody a chance to develop such an adapter?
kind regards

**Comment by GermanBluefox** [comment]
Can you provide us a hardware?

чт, 6 сент. 2018 г. в 16:16, meden01 <notifications@github.com>:

**Comment by meden01** [comment]
Hardware = Car will be available end Dec. 2018, but in any case you need access to an existing Volvo ID, so no real hardware required.

**Comment by GermanBluefox** [comment]
> Can you provide us a hardware?

It was a joke. Anyway, where can I get the Volvo ID?

**Comment by meden01** [comment]
Unfortunately not at the moment, any Volvo from 2012 and younger is capable of VOC...

**Comment by einarmiger0815** [comment]
What is the current state?

**Comment by Apollon77** [comment]
As you can see in the labels: status is „requested“. This means that so far no one started the development. You you want to?

**Comment by einarmiger0815** [comment]
Sure, would provide my VOC access to testing.

**Comment by TbsBrggng** [comment]
+1

**Comment by Apollon77** [comment]
Leute ... "+1" ist unsichtbar! Bitte Interessanten nutzt den "Thumbs up" beim ersten Post. Ich würde da 3 Daumen hoch erwarten, aber es sind 0

**Comment by ickest** [comment]
+1

**Comment by misko67** [comment]
+1

**Comment by TA2k** [comment]
Anscheinend gibt es noch interesse. Wenn jemand bereit ist sein App Zugangsdaten mit mir zu teilen kann ich schnell ein Adapter schreiben. Einfach im Forum anschreiben. 
https://forum.iobroker.net/user/tombox
Auf die drei Punkte rechts klicken.

**Comment by einarmiger0815** [comment]
Ich habe das dann mal getan ...

**Comment by einarmiger0815** [comment]
@TA2k, schau mal bitte in dein Email-Postfach, ggf. in deine Spam-Mail.

**Comment by misko67** [comment]
Schön das es weiter geht!

**Comment by TA2k** [comment]
Ist fertig. Bitte testen.
https://forum.iobroker.net/topic/29172/tester-adapter-volvo-on-call-v0-0x

**Comment by einarmiger0815** [comment]
@meden01, please can you change the status of the request?
