### ISSUE TITLE
HomeMatic RPC Adapter - Version 1.76 und Raspberrymatic Firmwareversion: 2.35.16.20180826

### ISSUE THREAD

**Issue by PCSHG** [ioBroker/AdapterRequests#111]
Folgendes Verhalten tritt bei mir auf, wenn ich iobroker gestartet habe:

Alle Programme der Raspberrymatic werden normal ausgeführt, nur die Visualisierung und die Zeitstempel im WebUI werden nicht aktualisiert.

Der Abruf der Statusinfos ist dann auch nicht über die Smartphone App pocketControl HM möglich. Sobald ich die Dienste von iobroker auf dem Raspi gestoppt habe, verhält sich die Raspberrymatic nach ca. 5 Minuten wieder ganz normal.

Als Anlage habe ich Euch meine Konfguration angehängt. Vielleicht findet Ihr den Fehler.

Vielen Dank vorab für Eure Hilfe.

**Comment by Apollon77** [comment]
Sorry, but this is no Adapter-Request
