### ISSUE TITLE
Mobile Alerts Adapter

### ISSUE THREAD

**Issue by Stefven** [ioBroker/AdapterRequests#113]
Hallo,
ich habe großes Interesse an einem Adapter für die Mobile Alerts Sensoren.
Die Sensoren senden ihre Werte an ein Gateway welches die Daten auf einem Server des Herstellers speichtern. Die Daten sind über App, Webseite und die Schnittstelle abrufbar.

Es gibt verschiedene Ansätze/Möglichkeiten die Daten der Sensoren zu bekommen.
- REST API (http://www.mobile-alerts.eu/images/public_server_api_documentation.pdf)
- Webseite (https://measurements.mobile-alerts.eu/)

In Fhem wurde es schon realisiert:
- Über Rest API (http://tips-und-mehr.de/mobile-alerts-sensoren-mit-der-rest-api-in-fhem-einbinden/)
- Über Webseite (http://tips-und-mehr.de/ohne-rest-api-mobile-alerts-temperatur-sensor-in-fhem-einbinden/)
- Nodejs (https://github.com/sarnau/MMMMobileAlerts)
-Fhem Modul (https://github.com/markusfeist/FhemMobileAlerts)

Danke schon mal im Vorraus.

**Comment by Sloop56** [comment]
Hallo,
habe auch schon lange auf einen Mobile Alerts Adapter gewartet, um meine TFA Weatherhub Sensoren in den iobroker zu integrieren. Habe die Werte nun mit dem Parser- Adapter aus Mobile Alerts in iobroker integriert. Funktioniert soweit ganz gut.
Detaillierte Anleitung habe ich hier gepostet:
https://smarthome.schimmer-media.de/forum/index.php?thread/2888-technoline-sensoren-und-mobile-alerts
Gruß Jonny

**Comment by fungus75** [comment]
Scheinbar wurdet ihr erhört: https://github.com/bluerai/ioBroker.mobile-alerts
==> Ich probiere den jetzt gleich mal aus!

**Comment by Stefven** [comment]
Danke für die Info.Am 04.10.2019 9:00 nachm. schrieb DerPilz <notifications@github.com>:Scheinbar wurdet ihr erhört: https://github.com/bluerai/ioBroker.mobile-alerts

==> Ich probiere den jetzt gleich mal aus!

**Comment by DutchmanNL** [comment]
https://github.com/bluerai/ioBroker.mobile-alerts

**Comment by kreativhuhn** [comment]
Könnt ihr über die REST API alle Sensoren abfragen?
Bei mir funktioniert das nur für Wind (MA10660) + Regen (MA10650), aber nicht für alle meine Thermo-/Hygro-Sensoren (MA10200) und auch nicht für den Außen-Sensor (MA10250PRO).
