### ISSUE TITLE
Blockly: URL request is causing errors

### ISSUE THREAD

**Issue by mtk64** [ioBroker/AdapterRequests#116]
**Hi
my Blockly script is requesting a simple URL to get some state of my motioneye server.
Sometimes it is causing errors which will restart the JS engine:**

host.aio	2018-09-30 14:58:18.289	error	instance system.adapter.javascript.0 terminated with code 0 (OK)
host.aio	2018-09-30 14:58:18.288	error	Caught by controller[1]: at Socket.emit (events.js:188:7)
host.aio	2018-09-30 14:58:18.288	error	Caught by controller[1]: at emitOne (events.js:96:13)
host.aio	2018-09-30 14:58:18.288	error	Caught by controller[1]: at Socket.socketErrorListener (_http_client.js:314:9)
host.aio	2018-09-30 14:58:18.288	error	Caught by controller[1]: at ClientRequest.emit (events.js:188:7)
host.aio	2018-09-30 14:58:18.288	error	Caught by controller[1]: at emitOne (events.js:96:13)
host.aio	2018-09-30 14:58:18.288	error	Caught by controller[1]: at Request.onRequestError (/opt/iobroker/node_modules/iobroker.javascript/node_modules/request/request.js:877:8)
host.aio	2018-09-30 14:58:18.288	error	Caught by controller[1]: at Request.emit (events.js:188:7)
host.aio	2018-09-30 14:58:18.288	error	Caught by controller[1]: at emitOne (events.js:101:20)
host.aio	2018-09-30 14:58:18.288	error	Caught by controller[1]: at self.callback (/opt/iobroker/node_modules/iobroker.javascript/node_modules/request/request.js:185:22)
host.aio	2018-09-30 14:58:18.288	error	Caught by controller[1]: at Request._callback (script.js.MTK.MotionServices:129:19)
host.aio	2018-09-30 14:58:18.288	error	Caught by controller[1]: TypeError: Cannot read property 'length' of undefined
host.aio	2018-09-30 14:58:18.288	error	Caught by controller[0]: at Socket.emit (events.js:188:7)
host.aio	2018-09-30 14:58:18.288	error	Caught by controller[0]: at emitOne (events.js:96:13)
host.aio	2018-09-30 14:58:18.288	error	Caught by controller[0]: at Socket.socketErrorListener (_http_client.js:314:9)
host.aio	2018-09-30 14:58:18.288	error	Caught by controller[0]: at ClientRequest.emit (events.js:188:7)
host.aio	2018-09-30 14:58:18.288	error	Caught by controller[0]: at emitOne (events.js:96:13)
host.aio	2018-09-30 14:58:18.287	error	Caught by controller[0]: at Request.onRequestError (/opt/iobroker/node_modules/iobroker.javascript/node_modules/request/request.js:877:8)
host.aio	2018-09-30 14:58:18.287	error	Caught by controller[0]: at Request.emit (events.js:188:7)
host.aio	2018-09-30 14:58:18.287	error	Caught by controller[0]: at emitOne (events.js:101:20)
host.aio	2018-09-30 14:58:18.287	error	Caught by controller[0]: at self.callback (/opt/iobroker/node_modules/iobroker.javascript/node_modules/request/request.js:185:22)
host.aio	2018-09-30 14:58:18.287	error	Caught by controller[0]: at Request._callback (script.js.MTK.MotionServices:96:21)
host.aio	2018-09-30 14:58:18.287	error	Caught by controller[0]: TypeError: Cannot read property 'length' of undefined

**Debug from my script:**

Log
15:01:18.259	[error]	Caught by controller[0]: at Request._callback (script.js.MTK.MotionServices:96:21)
15:01:18.260	[error]	Caught by controller[1]: at Request._callback (script.js.MTK.MotionServices:129:19)
[/quote]

**Showing the lines of code within blockly is showing this code:**

 try {
      require("request")((String('http://pn2.fritz.box:7999') + String('/1/detection/status')), function (error, response, result) {
        if (!!result.length) {
        setState("javascript.0.Services.MotionServer.detectionState.3"/*detectionState.3*/, (result.slice(((result.indexOf('Detection status') + 1) - 1), result.length - 17)), true);
      }
      }).on("error", function (e) {console.error(e);});
    } catch (e) { console.error(e); }

**I was expecting some handling when a server is not responding. Any Idea where the problem resides?
Maybe problems in try/catch in Blockly or JS engine?**

**Comment by Apollon77** [comment]
Bug reports open please in the repository of the respective adapter. ioBroker.javascript in this case
