### ISSUE TITLE
Viessmann Cloud Adapter

### ISSUE THREAD

**Issue by OMCastle** [ioBroker/AdapterRequests#117]
Ich möchte gerne meine Viessman-Heizung über die Cloudlösung auslesen und steuern.
Bewusst ohne vcontrold, da man über die Cloudlösung eine verlängerte Garantie hat und mein Heizungsspezie auch für Wartung usw. darauf zugreifen kann...

http://vitoguide.viessmann.com/login

im ioBroker Forum gibt es dazu einen startenden Threat...
https://forum.iobroker.net/viewtopic.php?f=21&t=17441

**Comment by Ilovegym66** [comment]
@Apollon77 wo ist das Released? Hab nix gefunden.. nur ein Viessmann-Adapter, der mit der Pi-Lösung arbeitet, aber nicht über die Cloud.

**Comment by Apollon77** [comment]
Ok, mein Fehler

**Comment by JueBag** [comment]
Moin, 
ich nutze das PHP-CURL Script von thetrueavatar (ohne Umweg über FHEM) im einer anderen Homeautomation(openhab). 
Ob sich der Aufwand lohnt das Scrpt "komplett" auf eine andere Sprache zu portiren lohnt, muss man sehen. Ich gebe zu bedenken: die ViessmannAPI muss eh als Blackbox genutzt werden und  Grossmann arbeitet noch an der Schnittstelle (Änderungen sind also eher wahrscheinlich).

Link zum Thread in der Community openHAB:
https://community.openhab.org/t/vitoconnect-getting-readings-from-viessmann-heating-system-via-vitoconnect/55974

**Comment by DutchmanNL** [comment]
I looked into this and integration seems to be possible with 2 options , I would like to try the easy route first

1) run the existing source of php script i background as get all values from the exposed JSON format.
That could also work fur switching commands as the php script had this already implemented we only need to call the function.

2) take a complete rebuild, pretty add develop everything in node


So would like to start with option 1 but will need help as I don't have login credentials for viesmann.

So if anyone has it and is willing to work together (test / provide information) we can start

**Comment by Ilovegym66** [comment]
can be closed, Adapter already finished.
https://github.com/thovid/ioBroker.viessmannapi
