### ISSUE TITLE
Skoda connect adapter

### ISSUE THREAD

**Issue by 1tb2** [ioBroker/AdapterRequests#118]

**Comment by Apollon77** [comment]
Any more information about this? Links? Docs? Existing API descriptions? Links to other projects that already interact with this car?

**Comment by Buhu91** [comment]
Hey Apollon77,

**Comment by Buhu91** [comment]
Hey Apollon, ich hätte auch Interesse an so einem Adapter. Soweit ich weiß gibt es keinen "offizellen" Api Zugang gibt. Könnte aber mal mail kontakt herstellen und nachfragen ob und wie man da Zugang bekommt. Außerdem gibt es einen Alexa Skill. 
https://www.amazon.de/%C5%A0KODA-Auto-a-s-Connect/dp/B07B2YDVN2

**Comment by Apollon77** [comment]
Versuch doch mal den Alexa2 Adapter. Mit dem Skill und dem "bespoken" vom Adapter sollte die textuelle Abfrage möglich sein :-)
Besser als nix

**Comment by Buhu91** [comment]
Werde es mal testen, hatte es eben erst beim nachsehen für das Projekt hier gesehen. 
Adapter wäre halt cool, da man über Skoda Connect den aktuellen Tankinhalt bzw. Reichweite sehen kann, die Standheizung einstellen und was mich mit am meisten reizt, die Parkposition anzeigen lassen kann ( ich vergess gerne mal in meiner Frühmorgentlichen verpeiltheit in welcher Straße ich die Karre abgestellt hab :D )

**Comment by Apollon77** [comment]
Na dann wiederhol ich mal den Joke von Bluefox letztens:
Wer stellt die Hardware? *lol* ;-)

**Comment by Buhu91** [comment]
:D Versand wird schwierig, aber ich stelle mich bzw. meinen weißen Tschechenbomber zur verfügung ;) 
Eventuell ist ja das System im VAG Konzern gleich oder zumindest ähnlich. So dass man das auch für Audi, VW und Seat anwenden könnte ❓

**Comment by Buhu91** [comment]
Ich habe schon im Oktober Skoda eine Anfrage geschickt. Dort wird aber nicht sooooo schnell anscheinend gearbeitet. Hatte angefragt ob es für Skoda so etwas wie das VW Smart home auch gibt, was verneint wurde und auf meine frage explizit bekam ich heute ne Mail, dass es noch Dauert -.-
Über Ihr Interesse an unserem Unternehmen freuen wir uns sehr.

>  Ihr Anliegen zur API-Schnittstelle ist uns wichtig und wird von uns sorgfältig und individuell geprüft. Die Durchsicht aller benötigten Unterlagen und die Abstimmung mit unserem Fachbereich nimmt noch einige Zeit in Anspruch.
> 
>  Sobald uns eine abschließende Rückmeldung vorliegt, setzen wir uns umgehend mit Ihnen in Verbindung. Daher bitten wir Sie um etwas Geduld.

**Comment by AlCalzone** [comment]
Für Audi gibts eine Python library, möglicherweise ist das ähnlich?

**Comment by TA2k** [comment]
Besteht noch Interesse?

**Comment by chefrocker** [comment]
Was benötigst du genau?

**Comment by TA2k** [comment]
Nichts mehr getestet kann der  Adapter hier
https://forum.iobroker.net/topic/26438/test-adapter-vw-we-connect-v0-0-x

**Comment by TA2k** [comment]
ist in latest
