### ISSUE TITLE
Kodi Adapter

### ISSUE THREAD

**Issue by helfi9999** [ioBroker/AdapterRequests#119]
Hallo, 
würde mir gerne wünschen das der Kodi Adapter weiter ausgebaut wird und das die Anleitung auch für Anfänger verständlich ist.

Gruß
helfi9999

**Comment by helfi9999** [comment]
Hallo,
mit Kodilexa kann man den Kodi per Alexa steuern wäre aber gut wenn man das per Iobroker einbringen könnte z.B. für die Vis

**Comment by Apollon77** [comment]
Bitte issue beim kodi Adapter öffnen. Und bitte exaktere feature requests nennen. Nur „bitte mehr“ ist für keinen zielführende. 

Issues hier sind für neue Adapter.
