### ISSUE TITLE
Adapter für Gosund und allg Tuya WLAN Steckdosen

### ISSUE THREAD

**Issue by surfer009** [ioBroker/AdapterRequests#120]
Hallo zusammen,

ich weiß nicht, ob meine Anfrage hier richtig ist, aber ich versuche es einfach mal :)
Ich bin bei Amazon auf diese WLAN Steckdosen gestoßen [https://www.amazon.de/Steckdose-Stromverbrauch-Fernsteuerung-Intelligente-kompatibel/dp/B07B911Y6V/](https://www.amazon.de/Steckdose-Stromverbrauch-Fernsteuerung-Intelligente-kompatibel/dp/B07B911Y6V/)
Ich finde sie vom Preis und auch vom Format her interessant. Leider gibt es aktuell noch keinen direkten Adapter mit den Geräten zu kommunizieren (nur IFTTT).
Ich kenne leider den Aufwand nicht so einen Adapter zu programmieren, daher hier erstmal nur eine Anfrage, ob jemand so etwas programmieren kann/will.
Die Steckdosen haben insgesamt gute Bewertungen und auch die Smartphone App bekommt positives Feedback. Ich könnte mir denke, das so ein Adapter vielleicht für mehrere hier interessant sein könnte, alleine da es sich hier um kleine, kompakte Steckdosen handelt.
Vielleicht kann mir ja mal jemand eine Rückmeldung hierzu geben bzw. vielleicht gibt es noch andere User hier im Forum, die an so einem Adapter interessiert wären.

Vielen Dank!

Gruß surfer

**Comment by Apollon77** [comment]
Schau mal ob Port 6668 offen ist bei dem gerät ... Dann wäre https://www.npmjs.com/package/tuyapi ein gedanke ...

**Comment by surfer009** [comment]
Hi Apollon77,
ich habe die Steckdosen noch nicht bei mir im Einsatz. Ich werde mir jetzt aber welche bestellen und dann melde ich mich hier zurück.

Gruß surfer

**Comment by surfer009** [comment]
Bevor ich die Geräte zurücksende habe ich einen normalen Portscan laufen lassen (ich weiß nicht ob das so reicht.) Einen Screenshot habe ich angehangen.
![portscan](https://user-images.githubusercontent.com/43878494/46687303-df18b100-cbfa-11e8-8dca-5ef24778119b.jpg)

**Comment by surfer009** [comment]
Ich habe mir gleichzeitig aber noch die **Gosund SP111** Steckdosen besorgt, vielleicht lassen diese sich genauso ansprechen wie die anderen?! Ich hänge hier ebenfalls den PortScan für diese Steckdosen an.
![sp111_portscan](https://user-images.githubusercontent.com/43878494/46688267-2f910e00-cbfd-11e8-95b5-ab28acd5d479.jpg)

**Comment by Apollon77** [comment]
Jeweils letzte Zeile sieht gut aus.

**Comment by Apollon77** [comment]
Schau dir die Labels an dem Issue hier an und du kannst vllt was absehen ...

Oder: Ich bin gerade dran

**Comment by surfer009** [comment]
Also ich hätte die SP111 Steckdosen da. Die anderen muss ich mir nochmal ordern, weil die erste Lieferung defekt war. Mit den SP111 könnten man ja schonmal testen.

**Comment by surfer009** [comment]
Die neuen SP1 Steckdosen wären jetzt auch da :-)

**Comment by Apollon77** [comment]
Das ganze wird doch etwas blöder weil die Tuya Leute wohl die freien API-Accounts abgeschafft haben und es so um einiges blöder wird an die "secrets" der Geräte zu kommen die man braucht um lokal zu kommunizieren und wäre auch cool gewesen um an das Schema (was kann man schalten/lesen und was ist das) zu kommen.
Das kann man "sniffen" ist aber Aufwändiger und muss jeder selbst machen. Ich denke ich kann was bauen, aber so wirklich "für jedermann" wird das daher leider eher nicht :-(

Ich muss mal überlegen wie ich das genau mache ...

Falls sich jemand mit Decompilen von Android Apps auskenne bitte mal melden :-)

**Comment by PerfectAnswer** [comment]
Ich habe auch 4 von den Steckdosen gekauft. Ich stelle mir die Frage ob es nicht einfacher ist die Dinger mit Tasmota zu flashen?

**Comment by Apollon77** [comment]
Das kommt immer auf die bastelskills und elektroskills und lötskills an. Stark Limitierte nutzergruppe. 

Faktisch geht alles und auch cool. Es ist nur tricky an eine info je device ranzukommen. Das macht man einmalig. Das versuchen wir gerade hinzubekommen ... stay tuned.

**Comment by blackrozes** [comment]
@Apollon77 Ich hatte die APP schon mal decompiled. Ich glaub mit http://www.javadecompilers.com/apk oder einem ähnlichen Online-Tool. Allerdings ist das echt viel Code. 

Man müsste halt irgendwie raus finden aus was sich der localkey generiert. Die Device-ID wird z.B. aus der MAC Adresse generiert https://github.com/codetheweb/tuyapi/issues/2#issuecomment-344284912

**Comment by Apollon77** [comment]
Laut Aussage eines anderen Users steckender key hochverschlüsselt in einem png und mir viel Anti decompile Logik .... und faktisch können Diensten jederzeit ändern. 

Verfolgen gerade nen anderen Ansatz. Mal schauen.

**Comment by surfer009** [comment]
Oh weia.. das hört sich ja kompliziert an... Ich habe da leider nicht viel Ahnung von um euch da helfen zu können. Aber ihr werdet schon einen Weg finden :-)

**Comment by Apollon77** [comment]
Aaaaaalso meine neueste Idee ist die folgende: Man nutzt die offizielle Smart Life App um die Devices zu registrieren. Tut eh am besten. Der Adapter bekommt einen Proxy, den muss man in seinem Handy eintragen um einmalig (oder nach Änderungen) die angemeldeten Geräte zu syncen. Ab dann läuft die Kommunikation direkt und im lokalen netzwerk.

Sagt mal was dazu ...

**Comment by blackrozes** [comment]
@Apollon77 Klingt nach nem echt guten Plan! Und angesichts der Ausgangslage ist das vermutlich die eleganteste und für weniger versierte Nutzer einfachste Lösung.

**Comment by jogiibaer** [comment]
auf das warte ich schon :-) versuch schon die ganze zeit die Tür Fenster Kontakte irgendwie in den ioBroker zu integrieren

**Comment by PerfectAnswer** [comment]
In der SmartLive App finde ich keine Einstellungen für einen Proxy. Oder soll ich das so verstehen, dass während des Registrungsprozesses temporär ein Proxy im Handy eingetragen wird?

**Comment by Apollon77** [comment]
> Oder soll ich das so verstehen, dass während des Registrungsprozesses temporär ein Proxy im Handy eingetragen wird?

Korrekt. Du musst ein SSL-Zertifikat in dein handy laden und trusten (kann man dann wieder ausschalten) und du trägst nen proxy im handy ein. Das SSL-zertifikat ist kein allgemeines sondern wird bei jedem iobroker gesondert erzeugt.
Dann musst DU nachdem alle Geräte in der App angelegt wurden den proxy machen, einmalig die App neu öffnen/neu laden und das sollte reichen um die Device-Infos zu bekommen die grbraucht werden. Dann geht der proxy wieder aus und du brauchst das nur nochmal machen wenn du neue Geräte hinzugefügt hast.

**Comment by PerfectAnswer** [comment]
Ok, der Proxy macht dann das sniffing der Devices. Hast Du das schon in der Praxis ausprobiert? Hast du Hardware zum testen?

**Comment by surfer009** [comment]
Gibts da irgendwo eine Anleitung für? Ich habe das noch nie gemacht.. Wie erzeuge ich das Zertifikat? Wie bekomme ich das dann in mein Telefon (Iphone)?

**Comment by Apollon77** [comment]
Done!
https://forum.iobroker.net/viewtopic.php?f=36&t=18029
