### ISSUE TITLE
Adapter for Meross Wifi devices

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/AdapterRequests#122]

**Comment by Apollon77** [comment]
Hey All,

also die Kommunikation hab ich ... es geht allerdings ausschliesslich über die Meross Cloud. Ein Adapter würde sich also dort einloggen, die Geräte Abfragen und sich mit einem Meross MQTT Server verbinden um Schaltbefehle zu senden und updates zu empfangen ...

Ist der Adapter dann interessant oder sagt Ihr dann "Ne cloud ist blöd" (auch wenn es scheinbar ein EU-Server ist der in Dublin steht)?

Ingo F

**Comment by mateusz1710** [comment]
local wäre schon besser, kann man die Geräte nicht direkt via WiFi anzapfen?

Gruß
Mattes

**Comment by Apollon77** [comment]
Die Geräte haben einen lokalen Port 80 auf dem man mit Ihnen reden kann. Theoretisch geht lesen und schreiben, was aber nicht geht (also zumindestens hab ich es nicht hinbekommen) sind "live statusupdates" und polling ist blöd. 
Am Ende ist es über die Cloud so das man einen Token holt und damit dann eine MQTT Verbindung öffnet ...

Mal schauen ob ich da noch mehr Zeit in Lokal investiere ... wenn jemand mitmachen will sehr gern

**Comment by DEV2DEV-DE** [comment]
Hallo Ingo,
es gibt hier ein funktionierendes Plugin für Homebridge:
https://github.com/bwp91/homebridge-meross#readme
Das funzt auch ohne Cloud.

Ich habe das jetzt über Umwege auch im Broker zum fliegen gebracht:
- Bei mir läuft eine HB im Docker auf Synology (genau wie der Broker).
- Im Broker den HB-Adapter installiert. Im Wrapper-Mode. Ohne zusätzliche Plugins.
- Die Konfig aus der HB kopiert und im Adapter eingetragen.
- Das Plugin aus der HB wieder deinstalliert.
Auf die gleiche Art und Weise habe ich z.B. auch Geräte von Gosund (SP1) und Tapo (P100) in den Broker bekommen.

Das Ganze scheint mir aber ein bisschen "durch die Brust ins Auge" zu sein. Ein nativer Adapter würde irgendwie ein besseres Bauchgefühl hinterlassen.

Vielleicht ein gangbarer Weg: Schauen, wie das bei den HB-Plugins realisiert ist und das in einem Adapter für ioBroker "nachbauen".
Ich bin selbst Entwickler, habe aber weder vom Code noch von der Architektur irgendwelche Berührungspunkte.
Vielleicht kann ich aber trotzdem behilflich sein.

Gruß
Bernd

**Comment by Apollon77** [comment]
Hm .. Ist das noch offen ... komisch. ALso der Meross Adapter ist sieit mehereren Jahren schon im Repo und auch in Stable ... ich mach mal zu hier

**Comment by DEV2DEV-DE** [comment]
Der Adapter im Repo geht aber nur über die Cloud.
Das HB-Plugin macht das iwie ohne Cloud. Mit dem Ham-Adapter kann ich die steuern, obwohl die Geräte in meiner FB für Internet gesperrt sind ;-)

**Comment by Apollon77** [comment]
Der Adpater im Repo geht nicht nur über die Cloud seit 1.12 :-)

**Comment by Apollon77** [comment]
Die Cloud wird nur initial benötigt um meta Daten der Geräte zu laden und zu initialisieren. Danach erfolgt der zugriff Lokal

**Comment by DEV2DEV-DE** [comment]
Der Adapter verbindet sich aber mit schöner Regelmäßigkeit mit der Meross-Cloud :-(
![image](https://user-images.githubusercontent.com/95883579/183413995-db78ccf6-6fa0-42bc-8a4f-c9d31e17b6f8.png)

Ich fände es da schon besser, wenn das nur 1x beim Starten des Adapters passiert, um an die Metadaten zu kommen.
Aus diesem Grund hatte ich mir die SerialNumber über diesen Adapter einmalig geholt und dann im Ham eingetragen.
Anschließend Meross-Adapter gestoppt.

Alternativ kann ich natürlich meine Zugangsdaten nach einer erfolgreichen Verbindung aus dem Adapter löschen ... aber dann bleibt der Adapter gelb und ich kann die Objekte auch nicht mehr steuern.
Also so ganz ohne Cloud geht's offenbar nicht :-(

**Comment by Apollon77** [comment]
Der Adaopter benötigt die Cloud um Push infos von State changes zu bekommen. Die gibt es lokal nicht.

Das ist ein übliches "pest und cholera Thema": Wenn DU aktuelle Werte möchtest die real time sind was den Status der Geräte angeht und ggf Parallelbedienung in der Meross App bzw an Schaltern, dann kommst Du um die Cloud nicht drum herum.
Alles was aktive Abfragen des Adapters sind und Schaltaktionen laufen Lokal.

Da ist der beste komrpomiss in meinen Augen.

Bei Homebridge generell ist es kein Problem ausschliesslich zu pollen weil es nur  abgefragt wird wenn der User auch in der Apple Home App Daten sehen will.
bei ioBroker sind die User-Erwartungen an die Datenaktualität andere und ich glaube nicht das die Geräte ein "sekündliches polling" gern haben
