### ISSUE TITLE
Vallox Lüftungsgeräte

### ISSUE THREAD

**Issue by ODeutsch** [ioBroker/AdapterRequests#123]
Hallo Zusammen!

Vallox ([https://vallox.de](url)) ist der Marktführer für Lüftungsgeräte. Die neue Generation der Geräte können über Websocket gesteuert werden. Die neuen und alten Geräte über Modbus (über ein Interface).
Dokumentation Modbus für die Register: [https://www.vallox.com/files/1092/Manual_Modbus_ENG_20180307_PRINT.pdf](url)
Source in Pyton [https://github.com/yozik04/vallox_websocket_api](url)
Source in Java [https://github.com/bjoernbrings/openhab2-addons/tree/master/addons/binding/org.openhab.binding.valloxmv](url)

Aktuell kann man die Lüftungsanlage über einer Webserver der auf dem Gerät läuft steuern.
Den kompletten JS Code dazu kann man sich anzeigen lassen.
Ich entwickle seit 27 Jahren Software auf Windows (mit c#) bin aber noch nicht wirklich dahinter gestiegen was da passiert, da ich keine JS Kenntnisse habe.
Es wäre schön wenn sich einer der Entwickler dem Adapter annhemen würde evtl reichen auch Grundzüge der Logik zum Abfragen des Websockets, und ich mache den Rest.
Ich bin gerne bereit meinen Rechner per Teamviewer etc. zur verfügung zu stellen.
Visual Studio mit Node läuft darauf.

Olaf

**Comment by Apollon77** [comment]
Was spricht gegen Modbus?

**Comment by ODeutsch** [comment]
> 
> 
> Was spricht gegen Modbus?

Weil man für Modbus wieder ein Stück Hardware benötigt um die Modbus Schnittstelle ans Netz zu bekommen. Warum noch was davor schalten wenn das Gerät es "anders" kann.
Aktuell bin ich mit Vallox im Gespräch ob der vorhandene Source der Weboberfläche teilweise benutzt und veröffentlich werden darf.

**Comment by hacki11** [comment]
Ich habe gerade einen JS Client für Vallox gefunden:
https://github.com/danielbayerlein/vallox-api
Muss man eigentlich nur noch den Adapter in JS für den iobroker schreiben

**Comment by ODeutsch** [comment]
das sieht gut aus. Werde mir das demnächst genauer anschauen.

**Comment by hacki11** [comment]
Ich hab schonmal ein Adapter Projekt generiert und den Client eingehängt. Schaut nicht nach viel Aufwand aus komme aber frühestens in 3 Wochen dazu.

**Comment by ODeutsch** [comment]
ist das Projekt hier zu finden ?

**Comment by hacki11** [comment]
https://github.com/hacki11/ioBroker.valloxmv
Ist bereits aktuell nicht mehr als ein generierter Template Adapter

**Comment by ODeutsch** [comment]
Danke! Ich schau mal wann ich dazu komme mich in JS/TS und Adapter Programmierung einlesen kann.
Meine letzten Versuche sind schon etwas länger her und mit Git hatte ich noch nichts gemacht, wobei ich das demnächst selber einsetzten möchte.
3 Konfigurationseinstellungen (IP, Port, Polling Zeit) und das Polling habe ich mir mal vorgenommen.

**Comment by hacki11** [comment]
Ja gerne, dann übernehme ich die states und die abfragen

**Comment by radierer** [comment]
Sehr schön zu hören, dass es hier weiter geht. :)

**Comment by Apollon77** [comment]
Super! Ich schaue auch hier und da rein falls es Fragen gibt - ansonsten kommt ins Forum unter "Entwicklung", da werdet Ihr auch schnell geholfen.
Ingo

**Comment by hliebscher** [comment]
Hallo,

würde gern mitmachen und Testen habe eine 270MV

Heiko

**Comment by radierer** [comment]
Testen könnte ich auch .. habe ebenfalls eine Valloplus 270 MV.

**Comment by hacki11** [comment]
Sehr gut, habe selbst eine 350 aber noch nicht in Betrieb.

**Comment by hliebscher** [comment]
hallo habe jetzt mit dem vallox-api und javascript unter iobroker das am laufen...
ein Modul wäre klasse

**Comment by williandalton** [comment]
Servus,

ich klinke mich mal mit ein ;-) Ich habe schon vor längerer Zeit meine 350 MV über eigene .NET Implementierung angesprochen und bin durch diesen Thread drauf gestoßen, das in ähnlicher Form auch für den IoBroker einzubinden. Ich habe mal das Template von hacki11 geforkt und einen Adapter angefangen, muss aber zugeben dass ich in Node bzw. JavaScript lange nicht entwickelt habe.

Anyway, es gibt einen funktionalen Prototypen der hier zu finden ist:
https://github.com/williandalton/ioBroker.valloxmv/tree/dev

Aktuell werden Home und Away Profil ausgelesen und geschrieben und die Zuluft und Außentemperaturen gelesen. Das ganze ist so aufgebaut, dass jetzt recht einfach weitere States hinzugefügt werden können, das fällt dann unter Fleißarbeit.

Mein größtest Problem gerade ist, dass die Einstellungsseite (index_m.html) nicht angezeigt wird.
Hat da jemand ne Idee wo es klemmt?

**Comment by Apollon77** [comment]
"iobroker upload valloxmv" gemacht? :-) Bei jeder Änderung an admin-Files, www-Files oder io- package musst Du das im "internen Store" per upload befehl aktualisieren

**Comment by williandalton** [comment]
> "iobroker upload valloxmv" gemacht? :-) Bei jeder Änderung an admin-Files, www-Files oder io- package musst Du das im "internen Store" per upload befehl aktualisieren

Tausend Dank, das hat geholfen :-)

**Comment by hacki11** [comment]
Hi @williandalton, kann es sein, dass du den Code von https://github.com/danielbayerlein/vallox-api kopiert hast, statt die Abhängigkeit als solches einzubinden? Weshalb hast du dich gegen das Einbinden entschieden?

**Comment by williandalton** [comment]
@hacki11 
Danke für den Hinweis, war keine böse Absicht sondern einfach nur Unwissenheit ;-)
Kannst du mir vielleicht noch nen Hinweis geben wie man das macht oder welche Technik ich recherchieren muss? Würde das dann gerne dahingehend umstellen...

**Comment by williandalton** [comment]
Ok, hab was dazu gefunden und es angepasst. Besser jetzt?

**Comment by hacki11** [comment]
Ich denke den kann man schließen :)

**Comment by Apollon77** [comment]
Nichts einfacher als das. Gute ARbeit!!
