### ISSUE TITLE
NEW iOS App for ioBroker

### ISSUE THREAD

**Issue by saepfle** [ioBroker/AdapterRequests#125]
Hello,

there exists the iOS App VIS Viewer for ioBroker which sadly will no longer be updated and only contains the existing views. 
![grafik](https://user-images.githubusercontent.com/42702704/47604556-c2061f80-d9fb-11e8-8acc-29b1b7a416ec.png)
https://itunes.apple.com/de/app/vis-viewer/id1175901818?mt=8
The source code from the developer can be found here:
https://github.com/echt-weg/vis-viewer

Also there exists a new Adpater and Android App for ioBroker "ioGo"
![grafik](https://user-images.githubusercontent.com/42702704/47604548-b4e93080-d9fb-11e8-893d-e48b7d882e40.png)
https://play.google.com/store/apps/details?id=de.nisnagel.iogo

**If somebody could create an NEW simple native iOS App similar to "ioGo" or Homematic "@Home" that would be a great Step for ioBroker.**

Further discussion can be found here:
https://forum.iobroker.net/viewtopic.php?f=30&t=4290&start=120#p126233

**Comment by TA2k** [comment]
I created a own vis viewer but have no apple developer license to publish it in the app store

**Comment by GermanBluefox** [comment]
Done?

**Comment by Apollon77** [comment]
I would wait till official release

**Comment by TA2k** [comment]
It is done and in the appstore
https://itunes.apple.com/de/app/id1449564305
You can now publish on the social media and the ioBroker channels

**Comment by GermanBluefox** [comment]
https://itunes.apple.com/de/app/id1449564305#?platform=iphone
