### ISSUE TITLE
Adapter for Ring Doorbell

### ISSUE THREAD

**Issue by ldittmar81** [ioBroker/AdapterRequests#129]
https://github.com/jimhigson/ring-api

https://forum.iobroker.net/viewtopic.php?f=24&t=11952&p=170111

**Comment by schmupu** [comment]
I would like to program an adapter for the ring video doorbell. Unfortunatly I do not have the hardware.

**Comment by GermanBluefox** [comment]
I can provide it to you. Please write me your address at dogafox@gmail.com

Am Di., 4. Dez. 2018, 13:49 hat schmupu <notifications@github.com>
geschrieben:

**Comment by schmupu** [comment]
Great!! Thanx Bluefox!!

**Comment by DutchmanNL** [comment]
https://github.com/schmupu/ioBroker.ring
