### ISSUE TITLE
Smartthings

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/AdapterRequests#13]
https://www.homeandsmart.de/smartthings-samsung-smart-home-system

http://docs.smartthings.com/en/latest/ref-docs/reference.html

https://github.com/dpjanes/homestar-smartthings
https://github.com/stjohnjohnson/smartthings-mqtt-bridge
https://www.npmjs.com/package/homebridge-smartthings

Migrated from Trello with 0 votes

**Comment by Apollon77** [comment]
Homebridge modules exist: homebridge-smartthings as example.

Please check if the new ioBroker.ham Adapter can help here: see https://forum.iobroker.net/viewtopic.php?f=36&t=14972

**Comment by tigerlampe** [comment]
homeassistant had allready a conection is there a way to copy that ?

**Comment by TA2k** [comment]
https://forum.iobroker.net/topic/48091/test-adapter-samsung-smartthings-v-0-0-x

**Comment by ldittmar81** [comment]
Ist jetzt im latest und kann geschlossen werden.

https://github.com/TA2k/ioBroker.smartthings
