### ISSUE TITLE
Adapter AWTRIX Uhr

### ISSUE THREAD

**Issue by Loi83** [ioBroker/AdapterRequests#132]
Anzeigen lassen von verschiedenen Stats auf der Awtrix uhr.
Hier die API: https://docs.blueforcer.de/#/v2/api

**Comment by Buddinski88** [comment]
Ist es möglich das ich meine AWTRIX zum testen bereitstelle? Bisher befülle ich sie per MQTT, aber ein Adapter wäre sicher auch hilfreich.

**Comment by dhoffmann1979** [comment]
Es gibt diesen Adapter hier: https://github.com/klein0r/ioBroker.awtrix-light

Bei mir läuft der gut!

**Comment by mcm1957** [comment]
@dhoffmann1979 
Bezieht sich deine Info auf die in diesem Request angeführte AWTRIX Uhr sodaa ich hier mit Verweis uach iob roker.awtrix-light schließen kann?

**Comment by mcm1957** [comment]
@klein0r
Ist dein Adapter auch für die in diesem Request angeführte AWTRIX Uhr geeignet sodass ich hier mit Verweis auf ioBroker.awtrix-light schließen kann?

**Comment by klein0r** [comment]
@mcm1957 Wenn die richtige Firmware (awtrix-light) installiert wird, geht das wohl:

https://github.com/Blueforcer/awtrix-light

> AWTRIX Light is an open‑source custom firmware for the Ulanzi Smart Pixel clock TC001 **or as upgrade for the old AWTRIX 2 Mainboard and even self build matrix clock**

**Comment by mcm1957** [comment]
OK, dann kann hier mal geschlossen werden,
