### ISSUE TITLE
AirConWithMe (IntesisHome based) Climatic Control Adapter

### ISSUE THREAD

**Issue by painkillerde** [ioBroker/AdapterRequests#133]
Its an universal ClimaticControl WiFi adapter for many brands. Its based on the IntesisHome but has no connection to there REST API.

Json data and a working bash script for GET and SET can be found here:

[https://forum.iobroker.net/viewtopic.php?f=24&t=18983](url)

**Comment by weggetor** [comment]
I tried to implement an adapter for the airconwithme wlan adapter:
Still in alpha, but works fine with my Mitsubishi heavy:

https://github.com/weggetor/ioBroker.airconwithme
