### ISSUE TITLE
RSS Feed für Visualisierung / for visualization

### ISSUE THREAD

**Issue by mdn-united** [ioBroker/AdapterRequests#135]
Hallo, 
ich baue gerade mein DAK Board ([http://www.dakboard.com](url)) um, bzw. möchte es mit einer ioBrocker Visualisierung ersetzen. Mein Ziel ist es, dass ich sowohl den Zustand einiger Smarthome Aktoren sehe, als auch die aktuellen Spritpreise (Tankerkönig Adaper ist super!) und auch Nachrichten. Die Nachrichten kommen als mehrere RSS Feeds rein. 

Ich würde mich einen Adapter wünschen, der die Überschriften aus RSS Feeds darstellt. Am besten es wäre ein transparenter Hintergrund und man würde noch die ersten x Zeichen des nachfolgenden Textes lesen können. Bei [http://www.dakboard.com](url) kann man sich anschauen, wie das aussehen könnte. Da sind die RSS Feeds direkt in der Mitte. 

--------------------------------
Hi, 
I am currently converting my DAK board ([http://www.dakboard.com](url)), respectively want to replace it with an ioBrocker visualization. My goal is to see the state of some smarthome actors as well as the current fuel prices (the Tankerkönig adaptor is great!) and also news. The news comes in as several RSS feeds. 

I would like an adaptor that displays the headlines from RSS feeds. Best would be a transparent background and you would be able to read the first x characters of the following text. At [http://www.dakboard.com](url) you can see what this could look like. There are the RSS feeds right in the middle. 

Danke! Thank you!

**Comment by oweitman** [comment]
now available in latest repository: iobroker.rssfeed
