### ISSUE TITLE
Miele@Home für WiFi@Connect Geräte 

### ISSUE THREAD

**Issue by Stormbringer11** [ioBroker/AdapterRequests#136]
Ein Miele Adapter für die neuen WiFi Geräte wäre top. Der bestehende Adapter funktioniert nur mit den Gateway bzw. älteren Modellen. 

API glaub ich gibt es bereits seitens Miele. 

https://community.home-assistant.io/t/miele-home-miele-mobile-component/64508

http://developer.miele.com/

**Comment by hash99** [comment]
Hi,
ich hab eine erste Version bei mir am Laufen:
https://github.com/hash99/ioBroker.mieleathome

Genre mal testen

**Comment by markus76** [comment]
Freue mich schon aufs testen...
Warten noch auf die id und den Secret von den devs 👍😊

Danke schon mal

**Comment by tordyrob** [comment]
Hi markus76,

hast Du schon was von den developer@miele.com bekommen?

**Comment by markus76** [comment]
Hi Ja hab auch den Adapter am laufen...
Allerdings geht er seit kurzen auf Fehler. Hätte aber noch keine Zeit zu schauen warum...

**Comment by Stormbringer11** [comment]
Vermutlich wegen dem Token oder? Hatte ich auch und weiß Hash schon. Glaub er arbeitet sogar schon an einem Fix. Ich hab den Fehler mit Neuinstallation beseitigt. Glaub soll aber Logindaten löschen und neu eintragen auch helfen. Steht alles ausführlich im Forum 😉

**Comment by markus76** [comment]
Ok thx für den Tipp...
Muss ich mir mal anschauen 👍

**Comment by Stormbringer11** [comment]
Immer gern 😉

**Comment by tordyrob** [comment]
ok ich habe superschnell aus meiner Sicht die Daten von developer@miele.com bekommen. Adapter geladen wie auf Git beschrieben.  Ich habe iobroker in einer VM mit aktuellem Rasperian Desktop laufen. Alle bsiherverwendeten Adapter laufen, sogar der Simatic S7 oder Gardena. Beide haben echt viele Objekten. Leider erzeugt der Miele@home Adapter folgende Fehlermeldungen mit denen ich aktuell leider nichts anfangen kann.
![iobroker miele@home adapert bug1](https://user-images.githubusercontent.com/556380/56920796-70cb0b80-6ac4-11e9-8b86-7da7295edd0d.PNG)

Könnt Ihr mir dazu etwas sagen? Soll ich andere, weiter Informationen zusammentragen und zur Verfügung stellen?

**Comment by markus76** [comment]
Gibt es hierzu schon was neues ?

**Comment by Apollon77** [comment]
Bitte behandelt Adapter-Fehler beim Adapter-Repo selbst.

**Comment by Grizzelbee** [comment]
Request fullfilled: https://github.com/Grizzelbee/ioBroker.mielecloudservice
