### ISSUE TITLE
Port "Stromprotokollierungs-script" to adapter

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/AdapterRequests#138]
Based on the great script used already by quite a large amount of user this should be an native adapter for ioBroker :

- Keep most logic as currenlty available in script
- Add values / date for final bill
- Make it adjustable of data should be handled komulative
- Ensure propper configuration screen to select states which should be logged

etc

based on : https://github.com/hdering/homematic_verbrauchszaehler

**Comment by Apollon77** [comment]
And if counter are ot enough it could be etended for other aggregation functions, also would more hope to get it into that then creating a very specialized adapter

**Comment by Zefau** [comment]
The current version 0.3.0 of ioBroker.meter-sockets includes a history of the power consumption. 
Did you already created an adapter? Maybe we can align / join our development?

**Comment by DutchmanNL** [comment]
Great yes good idea we also discussed internally how to proceed so let's join forces!

Main idea :
We would like to use the statistics adapter for general statistics data and transformation, logging in time should be handle by history adapters (history, SQL, influx etc)

My idea was to create an additional NON module with functions to be used as power measurement.

This would allow us to:
- have an power monitor adapter to select states to be logged
- include the logic into others

As several adapters need this kind of logging i personally think that's the best way to do it.
Other adapters can call the function in NPM module and implement own logging within their adapter based on this backend.

I am working on the basics now the code will be on GitHub before next weekend

**Comment by OMCastle** [comment]
A lot of people asre using the PulseCounter from Stall.biz.

https://www.stall.biz/produkt/pulsecounter-controller

It deliver the Counter and the calculated Power.
Please support the Counter to calculate the costs

**Comment by foxthefox** [comment]
for the sake of commenting, in my adapter statistics is a function which creates from incoming pulses an analog value and counts it up as consumption, like for gas meters or ferraris electric meters
its called sumCount
[https://github.com/foxthefox/ioBroker.statistics/blob/master/doc/howto_de.md](url)

**Comment by DutchmanNL** [comment]
> for the sake of commenting, in my adapter statistics is a function which creates from incoming pulses an analog value and counts it up as consumption, like for gas meters or ferraris electric meters
> its called sumCount
> [https://github.com/foxthefox/ioBroker.statistics/blob/master/doc/howto_de.md](url)

Powermonitor will not be extended to translate pulses to wh/h, this should be handled with statistics monitor.
https://github.com/foxthefox/ioBroker.statistics

Development is in progress and alpha state, beta release will be available this weekend.
https://github.com/DutchmanNL/ioBroker.powermonitor

**Comment by DutchmanNL** [comment]
beta version released !

https://github.com/DutchmanNL/ioBroker.sourceanalytix
