### ISSUE TITLE
Neato Botvac - Adapter - Erweiterung möglich?

### ISSUE THREAD

**Issue by AndySommer** [ioBroker/AdapterRequests#141]
Gibt es eine Möglichkeit diesen oder einen vorhandenen Botvac-Adapter mit den State der Cleaning Map zu erweitern?

Gibt es noch andere, denen sowas interessiert?

Es wäre doch schön, solche Infos auf dem Dashbord entnehmen zu können. Auf einer anderen Plattform ist dies schon implementiert.

Jetzt die Frage an die Entwickler des Adapters - wäre sowas möglich umzusetzen?

Lieben Gruß

**Comment by Apollon77** [comment]
Feature-Requests für bestehende Adapter bitte beim Adapter im Repo anlegen
