### ISSUE TITLE
Adapter for Withings Products

### ISSUE THREAD

**Issue by jogibear9988** [ioBroker/AdapterRequests#142]
I'd like to see a Adapter for Withings Products (Scale, ...)

http://developer.withings.com/oauth2/

https://gist.github.com/katemonkeys/e17580777b57915f5068

https://github.com/amida-tech/withings-lib

**Comment by jogibear9988** [comment]
I will work on this in a few weeks

**Comment by drtp** [comment]
Well, 

at least [here](https://forum.iobroker.net/topic/960/withings-daten-einlesen?page=1) already is available a respective Javascript.

**Comment by t6a** [comment]
*Push*

**Comment by Apollon77** [comment]
No need to push - GitHub is not a forum where this has any effect. 6 interested users so far according to the "thumbs up" above ...

**Comment by robson80** [comment]
@jogibear9988 Any update on this adapter? I will also start analysing the Withings API within the next one-two weeks.

**Comment by mnl61** [comment]
are there any updates now?
i'm willing to test the adapter, but my knowledge is o small, to write something like that.

**Comment by tardar** [comment]
I'd like to use it, too - are there any updates ? :)

**Comment by Apollon77** [comment]
As soon as an adater developer is interested he will post that here I expect :-)

**Comment by Trrw** [comment]
An adapter would be wonderful!

**Comment by TA2k** [comment]
If someone can provide an login with a device i can create an adapter
https://forum.iobroker.net/user/tombox

**Comment by TA2k** [comment]
https://forum.iobroker.net/topic/51104/test-withings-v0-0-x
