### ISSUE TITLE
Adapter für Zehnder Wohnraumlüftung

### ISSUE THREAD

**Issue by Oreider** [ioBroker/AdapterRequests#144]
Hallo,

würde mir einen Adapter für die aktuellen Modelle (ComfoAir Q350, Q450 und Q600) der Zehnder Wohnraumlüftung wünschen.
Herstellerseite: https://www.zehnder-systems.de/produkte-und-systeme/komfortable-wohnraumlueftung/comfoair-q

Für diese Modelle gibt es ein LAN C Modul welches die Steuerung mit App ermöglicht.
App Store: https://itunes.apple.com/de/app/comfocontrol/id1104291808?mt=8

Leider konnte ich bisher nur folgende Informationen finden:
Python: https://github.com/michaelarnauts/comfoconnect

Es ist wohl schon gelungen die Anlage über openHAB anzusteuern. 

Schönen Gruß
Tom

**Comment by raetsch** [comment]
There is a python script from prtg-developer using the comfoconnect library.
https://github.com/dirkpaessler/sensors_for_prtg/blob/master/Zehnder%20ComfoAir%20Q%20Ventilation%20Systems/sensor_pycomfoconnect.py
i modified it a bit to write the results into ioBroker datapoints and running the script every 5 minutes via a cron. works stable since quite some time now.

with this script it should be easy to create an adapter (just not for me).

regards
raetsch

**Comment by jookeer** [comment]
> There is a python script from prtg-developer using the comfoconnect library.

> i modified it a bit to write the results into ioBroker datapoints and running the script every 5 

hi @raetsch 
Just have seen the python script aswell, sounds promissing for an adapter. i would love to see an adapter. In the meanwhile could you share your modified script? One additional question are you able to switch of the zehnder ventilator completle over the script and the lan c module?

thank you for your help!

**Comment by vain90** [comment]
@raetsch I'm also interessted in your modified script. =)

**Comment by raetsch** [comment]
Hi guys, 

sorry that it took some time.
i uploaded it here:
https://github.com/raetsch/sensors_for_prtg

feel free to test it.

**Comment by annD-annD** [comment]
Hier die Android App für das ComfoConnect LAN C (Ethernet Modul für Zehnder ComfoAir Q350 Q450 und Q600 um ca. 200€): [https://play.google.com/store/apps/details?id=com.zehndergroup.comfocontrol](url)

**Comment by annD-annD** [comment]
Hier eine NodeJS Zehnder ComfoAirQ implementation: [https://developer.aliyun.com/mirror/npm/package/node-comfoairq](url)

**Comment by annD-annD** [comment]
...und hier für ioBroker: [https://github.com/klein0r/ioBroker.comfoairq](url)

**Comment by raetsch** [comment]
> ...und hier für ioBroker: [https://github.com/klein0r/ioBroker.comfoairq](url)

not working yet.

**Comment by Snapergy** [comment]
Wäre auch an solch einem Adapter interessiert. Hat jemand schon etwas am Laufen?

**Comment by vain90** [comment]
Hallo zusammen,
ich hatte die Tage Kontakt zu einem Techniker von Zehnder. (Super nett und extrem kompetent btw.)
Dieser erwähnte in einem Nebensatz das es bald/demnächst (grober Zeitplan ist wohl Anfang kommenden Jahres) ein Alexa Skill geben soll. Das sollte jetzt wohl noch gar nicht bekannt gemacht werden aber es würde fälschlicherweise ein Video auf dem Zehnder YouTube Kanal veröffentlicht welches die Einrichtung des Skills zeigt.
https://www.youtube.com/watch?v=31ifiSP94Ls

Demnach wäre die Steuerung der Lüftungsanlagen von Zehnder, über den Umweg von Alexa, mit IOBroker reletiv einfach möglich. Ob damit dann auch Sensoren ausgelesen werden können muss sich zeigen.

Nun heißt es abwarten.

*Ps: Ich habe auf diesem Wege auch mal nachgefragt ob es nicht möglich wäre eine API zu bekommen oder zumindest eine Dokumentation über die LAN C Schnittstelle welche wir dann in ein Adapter gießen könnten. Aber das ist nicht in Planung.

**Comment by vain90** [comment]
Kleines Update:

der Alexa Skill steht aktuell noch nicht zum downloaden bereit. Allerdings habe ich gerade gesehen das es seit Dezember 20 eine Open Beta Phase gibt in der es wohl unteranderem für ComfoAir Q Geräte eine Cloud Anbindung gibt. So wie ich das lese gibt es dabei wohl auch eine API zur Einbindung in sein SmartHome.

**Comment by klein0r** [comment]
Kurzes Update: Ich habe die Tage mit dem Adapter weiter gemacht und bekomme schon einige Infos. Möchte da auf jeden Fall bald eine lauffähige Version hinstellen. Ohne Cloud und Alexa Skill von hinten durch die Brust Zeug 😄 

<img width="1479" alt="Screenshot 2021-02-07 at 18 54 34" src="https://user-images.githubusercontent.com/1959049/107154963-fd7f4a80-6975-11eb-9ff9-c89143935e38.png">

**Comment by MaverickElTech** [comment]
> 
> 
> Kurzes Update: Ich habe die Tage mit dem Adapter weiter gemacht und bekomme schon einige Infos. Möchte da auf jeden Fall bald eine lauffähige Version hinstellen. Ohne Cloud und Alexa Skill von hinten durch die Brust Zeug 😄
> 
> <img alt="Screenshot 2021-02-07 at 18 54 34" width="1479" src="https://user-images.githubusercontent.com/1959049/107154963-fd7f4a80-6975-11eb-9ff9-c89143935e38.png">

Super! Würde mich als Tester zur Verfügung stellen

**Comment by klein0r** [comment]
@m4dsk8er Nur das, was auf GitHub steht aktuell. Gehe in Arbeit aktuell unter und komme nich dazu weiter zu machen. Pull Requests werden natürlich gerne genommen

**Comment by VincentGeppert** [comment]
Hallo Zusammen, 

Zehnder hat mittlerweile eine Cloud API zur Abfrage und Steuerung des ComfoAir Q, welche bereits von bspw dem Alexa Skill in der Open Beta verwendet wird ([https://www.international.zehnder-systems.com/connected-products](https://www.international.zehnder-systems.com/connected-products)). Aktuell suchen wir jedoch noch einen Entwickler, welcher einen Adapter für den IOBroker programmiert. Falls in dieser Community jemand Interesse daran hat, kann er sich gerne bei Ercan Yapalak (Ercan.Yapalak@zehndergroup.com) melden, nachdem er sich auf der oben angegebenen Seite für die Open Beta registriert hat.

**Comment by TA2k** [comment]
Ich schaue mir mal die Cloud API mal an. Ich würde vorschlagen die https://github.com/klein0r/ioBroker.comfoairq erstmal zu pausieren um nicht Zeit zu verschwenden.

**Comment by vain90** [comment]
Hallo,

gibt es denn hier Neuigkeiten?
Hat sich ein Entwickler für ein IOBroker Adapter gefunden der mit Zehnder zusammen ein Adapter entwickelt?

@TA2k Du hat ja zuletzt geschrieben dass du dir das mal anschauen wolltest.

**Comment by TA2k** [comment]
Warte noch auf die Freigabe der cloud API von zehnder

**Comment by klein0r** [comment]
@TA2k Ich bin nach wie vor Fan davon, die Geräte lokal anzusteuern. Die Lüftungsanlage steht immerhin bei mir im Haus. Warum genau sollte ich mit dieser über einen Server im Internet kommunizieren? Wenn ich Zeit finde, werde ich den Adapter trotzdem weiter entwickeln.

**Comment by Snapergy** [comment]
@klein0r leider kriege ich es bei deinem Adapter nicht hin die uuid auszulesen, obwohl ich alles so gemacht habe, wie von dir beschrieben...

**Comment by TA2k** [comment]
Ich denke das Ticket kann noch nicht geschlossen werden weil ja parallel der nicht cloud adapter noch entwickelt wird

**Comment by ldittmar81** [comment]
Ohh... du hast recht!

Cloud Version released
Home Version in Planung

**Comment by klein0r** [comment]
Der Vollständigkeit halber hier noch der Link zum Cloud-Adapter: https://github.com/TA2k/ioBroker.zehnder-cloud

**Comment by mcm1957** [comment]
as both adapters are available we can close here
