### ISSUE TITLE
Adapter für Mamibot PreVac 650 

### ISSUE THREAD

**Issue by masteryotta** [ioBroker/AdapterRequests#145]
Hallo, 
Ich habe einen Wifi Staubsauger Roboter den ich gerne in meinen Smarthome integrieren möchte. Ich habe leider wenig Ahnung von Programierung und muss mich erst einlesen.. 
Ich hoffe jemand hat auch diesen kleinen Helfer zu Hause!

Hier sind die Infos die ich finden konnte, wenn andere Informationen notwendig sind, suche ich die gerne.

Hersteller link: https://www.mamibot.com/prevac650

Screenshot der App vom Handy:
![screenshot_20181226-144231_mamibot life](https://user-images.githubusercontent.com/45926638/50447856-430b6580-091e-11e9-9805-cbcbddcd3975.jpg)

Vom Roboter:
![20181226_150015 2](https://user-images.githubusercontent.com/45926638/50448200-f6288e80-091f-11e9-8305-9899300418ca.jpg)

Funktion: erste Teil in der App ist für die manuelle Navigation und play Taste um Saugen zu starten.
Auto=mittlere Taste vom Roboter. Spot=Linke Taste vom Roboter. Laden: Roboter geht zur Station=rechte Taste vom Roboter.
30 min und Kanten Funktion ist nur von der App möglich. 
"Alles Reinigen" : Wenn gecheckt wird der Roboter saugen bis der Akku schwach wird. 

Vielen Lieben Dank!

**Comment by masteryotta** [comment]
Ich habe folgendes gefunden, um den Roboter mit Alexa zu steuern, benötigt man eine andere App "Tuya Smart", könnte das weiterhelfen? Ich habe kein Echo und nutze noch nicht Alexa. 
https://www.mamibot.com/how-to-connect-prevac650-with-alexa

**Comment by Apollon77** [comment]
Tuya smart?! Hui ... Versuch mal den tuya Adapter!! Da bin ich gespannt. Gibt im Forum nen Thread zum Adapter.

**Comment by masteryotta** [comment]
Integration mit Tuya war etwas schwierig wegen der Proxy Sache, es hat aber am ende geklappt! 
Somit kann diese Issue bitte geschlossen werden.
Danke!
