### ISSUE TITLE
Adapter für Performance und HealthCheck / Monitor

### ISSUE THREAD

**Issue by OMCastle** [ioBroker/AdapterRequests#146]
Hallo zusammen,

Ich befasse mich gerade mit der Performance meines OrangePi und halte eine Unterstützung in IOBroker für „Linux-Anfänger“ für sinnvoll.

ich fände es super, wenn das Admin Tool um Health und Peformancechecks erweitert wird.

- TOP
- ioWait
- Nodejs Versionen usw. 
- Watchdog für wichtige Prozesse mit aktiver Warnung, wenn die Sterben oder so..
Anzahl Datenpunkte
- Erzeugen eines standardisierten TechReports, um bei fragen im Forum eine einheitliche Basis zu haben. 

alles was ihr noch für sinnvoll und wichtig haltet

**Comment by ldittmar81** [comment]
Node. Js Versionen und Anzeige wenn eine neue Version verfügbar ist, ist im info Adapter bereits eingebaut. Da könnten wir gerne noch mehr anzeigen...

**Comment by OMCastle** [comment]
Gerne. Ihr habt den besseren Überblick ob ein eigener Adapter oder die Erweiterung eines bestehenden Sinn macht.

**Comment by 2bai** [comment]
Finde das Projekt super ... kann aber nur begrenz helfen ... aber kann für eine gewisse Aufmerksamkeit sorgen!

Und da es ja um Health geht - bei med. Fragen bitte einfach melden ... mache gerne mit (bin selber Mediziner und nur Hobby-Entwickler)

Gruß

2bai

**Comment by Apollon77** [comment]
@2bai Ich denke hier geht es eher im die "Health" des Systems auf dem iobroker läuft :-)

Wenn Du aber andere Ideen für Anwendungsfälle hast gern eigene Adapter-Request Issues anlegen

**Comment by DutchmanNL** [comment]
Mit den bestehenden Info Adapter könnte dies geschlossen werden oder gibt es noch Bedarf?

**Comment by mcm1957** [comment]
Sehe ich auch so - dieser request kann wohl geschlossen werden.

Closing this issue as tin the meantime i.e. info adapter exists and admin displays many infoamtions too. If any need for a new adapetr, please create a new issue.
