### ISSUE TITLE
Adapter Samsung Health / Galaxy Phones / Gear Sx / Gear Watch

### ISSUE THREAD

**Issue by Ilovegym66** [ioBroker/AdapterRequests#147]
Die Idee, den Samsung Health Account mit Steps, Kcal, etc. in der Vis darzustellen.
Samsung bietet etwas support hier:
https://developer.samsung.com/health

Müsste dann eher eine App werden, die auf einem Gerät installiert wird, und die Daten an iobroker sendet..

**Comment by Ilovegym66** [comment]
additional info:
https://forums.androidcentral.com/samsung-galaxy-note-5/606733-there-way-export-save-s-health-data-file-2.html

**Comment by 6RomN6** [comment]
They have done allready something similar... perhaps it would help... 
[https://appyhapps.nl/](url)
