### ISSUE TITLE
ID Einfügen Mechanismus im  Script Tab verbessern

### ISSUE THREAD

**Issue by Marty56** [ioBroker/AdapterRequests#149]
Es wäre schön, wenn das User Interface zum Einfügen einer ID verbessert würde.

Ein schöne Implementierung eines gelungenen "ID picker " User Interface sind die Red Node Knoten für Homematic CCU z.B. bei dem  "rpc event" Node.

**Comment by Apollon77** [comment]
Bitte im Admin Repo anlegen mit exakteren Anforderunfen was blöd ist und verbessert werden sollte. Vllt Screenshots dazu?
