### ISSUE TITLE
Bring!

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/AdapterRequests#15]
Inzwischen kann man Bring! auch als Web - https://web.getbring.com - außerdem sind die Entwickler von Bring! sehr hilfsbereit und könnten bei der Umsetzung Hilfestellung geben.

Migrated from Trello with 0 votes

**Comment by BastianSB** [comment]
Hatte kurzen Kontakt mit den Leuten von Bring!
Aktuell gibt es keine API. Das Thema soll aber angegangen werden wenn das Team größer ist.
Ich das ganze neugierig beobachten.

**Comment by larsdecker** [comment]
Theoretisch haben die mit der Web-APP eine API. Es gibt allerdings nirgends eine Dokumentation von der API.

Generell sieht deren API aber recht leicht zu nutzen aus. Man müsste allerdings vorher rausfinden, wie man an einem gültigen  JWT-Token kommt. Das konnte ich auf die schnelle noch nicht rausfinden.

**Comment by foxriver76** [comment]
Ich habe mal einen provisorischen Adapter hierfür geschrieben, allerdings ist keine Garantie gegeben, dass Bring! nicht die ungewünschte Mehrnutzung der API merkt und evtl. dagegen arbeitet. Ich werde das Repo evtl. heute Abend online nehmen, insofern die Zeit es zulässt.

**Comment by foxriver76** [comment]
Alles weitere bitte hier: https://forum.iobroker.net/topic/19840/aufruf-bring-adapter
