### ISSUE TITLE
Adapter Spritpreis Österreich

### ISSUE THREAD

**Issue by Georgius68** [ioBroker/AdapterRequests#150]
Hi

Würde mich über so einen Adapter freuen. Der Link 

https://api.e-control.at/sprit/1.0/search/gas-stations/by-address?latitude=48.092431&longitude=16.287927&fuelType=DIE&includeClosed=false"
method | "get"
upload | false
swaggerDoc | undefined
show less

liefert ein Json zurück. Darin stehen 10 Tankstellen und die 5 (oder mehr wenn Preisgleichheit) haben einen Preis. Es wäre super wenn der Adapter einmal alle Tankstellen in eine Datenstruktur legt (für Verläufe) und dann die mit einem Preis nach Preis sortiert in eine andere Struktur. (Für zB Vis)

Weitere Infos zum Tema: https://api.e-control.at/sprit/1.0/doc/index.html?url=https://api.e-control.at/sprit/1.0/api-docs%3Fgroup%3Dpublic-api

Danke

**Comment by DutchmanNL** [comment]
Hi

Wo liegt der Unterschied zum jetzigen tänkerkönig adapter?

**Comment by Georgius68** [comment]
Nach meinem Wissen ist Tankkönig für Deutschland. Das wäre für Österreich.

**Comment by Apollon77** [comment]
kann man das ggf dort einbauen?

**Comment by Georgius68** [comment]
Von mir aus ;). Allerdings dürfte der Aufbau der Daten sehr anders sein. Was ich auf die Schnelle gesehen habe kann man in D alle Preise abfragen. In Ö geht das nicht da kann man nur die 10 nächsten einer Koordinate abfragen und bekommt nur Preise für die 5 günstigsten.
Ich sehe keinen Vorteil in einer Einbindung. Kann es aber leider auch nicht programmieren. Sollte eigentlich nicht schwer sein.

**Comment by Negalein** [comment]
Hallo
Würde mich auch sehr freuen, wenns was für Österreich gäbe!
Hab es hier auf GIT leider erst entdeckt, nachdem ich im Forum eine Anfrage zur Entwicklung (gerade vor 5 Min.) gestellt habe!

**Comment by MyzerAT** [comment]
häng mich an, da ich auch aus österreich bin

**Comment by Apollon77** [comment]
Setzt mal die Thumbs up bitte oben im ersten beitrag ... sonst sieht man es in der Übersicht nicht

**Comment by Negalein** [comment]
Du meinst beim 1. Beitrag von Georgius68?

**Comment by sigi2345** [comment]
Ich möchte das auch haben, bitte...........

**Comment by NECH2004** [comment]
Nach dem Lesen des Hausautomatisierungs-Blogs von klein0r habe ich mir gedacht, dass ich meine JS Kenntnisse eigentlich wieder einmal auffrischen könnte und eine Spritpreis-Suche auch für Österreich interessant wäre. Beim Studium der API aus dem ersten Blog-Eintrag bin ich dann auf diesen Thread gestoßen.
Da ich den ioBroker aber nur aus den Blog-Beiträgen kenne (hab mich noch nicht für eine Hausautomatisierung entschieden), wird es noch ein wenig dauern, bis ich den Adapter als beta fertig haben werden. Werde euch die ersten verwendbaren Ergebnisse aber zugänglich machen.

**Comment by Apollon77** [comment]
Wenn Du hilfe brauchst, am besten im Entwickler-Bereich im ioBroker Forum!

**Comment by Negalein** [comment]
ein 1. erfolgreiches Script ist im Forum online.
Kein Adapter, aber es funktioniert mit dem Script auch sehr gut.
https://forum.iobroker.net/topic/20314/skripten-des-e-control-spritpreisrechners

**Comment by xXBJXx** [comment]
hab hir mal ein Adapter gemacht wer lust hat kann ihn ja mal testen [ioBroker.e-control-at-fuel](https://github.com/xXBJXx/ioBroker.e-control-at-fuel)

**Comment by ldittmar81** [comment]
https://github.com/HGlab01/ioBroker.fuelpricemonitor
