### ISSUE TITLE
enigma2 adapter in iobroker Database aufnehmem

### ISSUE THREAD

**Issue by Matten-Matten** [ioBroker/AdapterRequests#155]
ich würde gerne den enigma2 Adapter 
`https://github.com/Matten-Matten/ioBroker.enigma2`
in die ioBroker Datenbank übergeben 

ich weiß nur nicht wie ich das GitHub Projekt auf NPM bekomme und 
wollte um Unterstützung/Hilfe bitten.

Gruß
Matten Matten

**Comment by Apollon77** [comment]
Am besten im Forum unter „Entwickler“ fragen da helfen wir alle sehr gern
