### ISSUE TITLE
Alexa skills Multi Language 

### ISSUE THREAD

**Issue by steckenpferd** [ioBroker/AdapterRequests#158]
Today the ioBroker Alexa Skills (normal, Pro, IoT, ..) exists only completely for the local German (DE) Amazon store.
Partially also for the English (UK) Amazon store.

But the skills are missing today completely in the local Amazon language stores (Status January 2019):

Englisch (USA, CA)
French (FR, CA)
Italian (IT)
Japanese (JP)
Spanish (ES, MX)

To make ioBroker more successful outside Germany it would make sense to add Alexa skills also to other local language Amazon stores.

**Comment by Dobis19** [comment]
I can help with the Italian translation

**Comment by steckenpferd** [comment]
Nur zum Vergleich 

![4A9A6523-35C0-4905-BC41-5E90BCCABCA7](https://user-images.githubusercontent.com/39061622/59233336-54a0ab00-8be8-11e9-9ae9-8f0618a24ced.jpeg)

**Comment by Vraanaa** [comment]
> Today the ioBroker Alexa Skills (normal, Pro, IoT, ..) exists only completely for the local German (DE) Amazon store.
> Partially also for the English (UK) Amazon store.
> 
> But the skills are missing today completely in the local Amazon language stores (Status January 2019):
> 
> Englisch (USA, CA)
> French (FR, CA)
> Italian (IT)
> Japanese (JP)
> Spanish (ES, MX)
> 
> To make ioBroker more successful outside Germany it would make sense to add Alexa skills also to other local language Amazon stores.

I would lie to help with Croatian Language...if you provide me neccessary Texts - I can translate from English to Croatian

**Comment by Apollon77** [comment]
Pleas eopen an issue with iot Adapter
