### ISSUE TITLE
Philips TV

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/AdapterRequests#16]
https://github.com/gw-wiscon/homebridge-philipstv
https://github.com/netdata/pcremote
https://github.com/Basster/philips-tv-remote

Migrated from Trello with 1 vote

**Comment by Apollon77** [comment]
@AlCalzone Erledigt? https://github.com/AlCalzone/ioBroker.philips-tv

**Comment by AlCalzone** [comment]
Adapter läuft, aber Pairing mit neueren Geräten über die Admin-UI fehlt noch

**Comment by AlCalzone** [comment]
https://github.com/AlCalzone/ioBroker.philips-tv/pull/5

**Comment by Apollon77** [comment]
Maybe also Homebridge-Adapter can help !?
https://forum.iobroker.net/viewtopic.php?f=36&t=14972

**Comment by AlCalzone** [comment]
I try to get this done soon. Not too relevant for me atm, as my satellite connection has been non-functional for about 5 months...

**Comment by ldittmar81** [comment]
What is the current standing? Still in progress?

**Comment by mcm1957** [comment]
No feedback since jan?
I don't think it's still work in progress.

**Comment by Apollon77** [comment]
I think it is ready ... so I close here. android support is also added since some versions from @foxriver76

**Comment by AlCalzone** [comment]
Yep, I gave @foxriver76 access to the repo and he took over.
