### ISSUE TITLE
Mercedes me Adapter

### ISSUE THREAD

**Issue by HJS72** [ioBroker/AdapterRequests#164]
Adapter mit den Daten und Funktionen der Mercedes me App.
Z.B. Tankfüllstand, Nächster Service und vor allem die Möglichkeit die Standheizung über ioBroker zu programmieren.

**Comment by mangel8** [comment]
API description https://developer.mercedes-benz.com/apis
Only mocked data for free to get acess to live data you have to be a valid company

**Comment by Schello805** [comment]
Jo, wäre cool.

**Comment by TA2k** [comment]
Ich mach mich mal ran

**Comment by TA2k** [comment]
https://github.com/TA2k/iobroker.mercedesme

**Comment by ldittmar81** [comment]
Kann man das dann schließen? Ist doch released!
