### ISSUE TITLE
WLED integration (controlling WS2812b and related RGB stripes)

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/AdapterRequests#165]
Adapter for integration of WLED project to enabled controlling RGB stripes like WS2812b directly from ioBroker without additional setup and configuration of MQTT.

Aspects to consider :

* support multiple stripes in 1 adapter
* controls effects, colors, brightness as implemented in WLED
* control by HTTP API

https://github.com/Aircoookie/WLED/issues/102

**Comment by elzershark** [comment]
esp + tasmota = finished 
control by HTTP API
0 adapter
all over javascript..

**Comment by DutchmanNL** [comment]
Still i will work on the adapter preparation on WLED is almost finished.

Having it in JavaScript is not user friendly and also MQTT is insufficient for the needed commands and speed that's why we implement UDP broadcast instead of HTTP API (to slow)

**Comment by DanielWeeber** [comment]
Via MQTT the change of LEDs as instant as it can be for me. 
Why should the adapter be any easier?

**Comment by DutchmanNL** [comment]
> How should the adapter be any easier?

give me some trust and wait until its done you will see a huge difference in setup and usability

**Comment by Beliar-666** [comment]
Hey @DutchmanNL Nice to see that u work on a adapter for WLED. You also linked my request for more mqtt functionality some posts above.

How its going on with your work? If u need a tester, just ask ;-)

**Comment by Beliar-666** [comment]
gibt es schon was neues?

**Comment by DutchmanNL** [comment]
> gibt es schon was neues?

leider noch nicht ich werde Aircookie mal anschreiben warte auf feedback

**Comment by Beliar-666** [comment]
Moin @DutchmanNL ich nehme an es tut sich nichts mehr?

**Comment by DutchmanNL** [comment]
von meiner Seite her ja muss ja im winter wieder vernünftige Beleuchtung haben :P

ich werde demnaest mal nochmal im issue bei air cookie schreiben, ein push von dir könnte auch helfen ;)

**Comment by Beliar-666** [comment]
na, aircookie antwortet wohl nimmer?

**Comment by Beliar-666** [comment]
Gibt es denn mittlerweile mal neuigkeiten?

**Comment by GermanBluefox** [comment]
So was ? https://github.com/iobroker-community-adapters/ioBroker.wled

**Comment by DutchmanNL** [comment]
Startet on it yesterday give me a day and I will release it and close this request

**Comment by DutchmanNL** [comment]
https://github.com/iobroker-community-adapters/ioBroker.wled

beta ready, happy testing ! 👯‍♂
