### ISSUE TITLE
MyQ Chamberlain Garage Door Controller

### ISSUE THREAD

**Issue by JackWolfskin42** [ioBroker/AdapterRequests#166]
API:
http://docs.unofficialliftmastermyq.apiary.io/#reference/0/toggle-device-state
Python Example:
https://github.com/Einstein42/myq-garage

Existing Openhab: Adapter:
https://www.openhab.org/addons/bindings/myq1/

MyQ doesn't offer the integration into Alexa, Google Home or Homekit in Germany. 
This can be enabled e.g. through iobroker ....

**Comment by Apollon77** [comment]
What about the ham adapter and Homebridge Plugin?

**Comment by JackWolfskin42** [comment]
Ah, just found it:
https://www.npmjs.com/package/homebridge-chamberlain
I'll give it a try, thanks!

**Comment by JackWolfskin42** [comment]
For me this worked sufficient, even if a dedicated adapter might be nicer ;-)
So I suggest to close the Request !

**Comment by Apollon77** [comment]
We can leave open. One idea to build a ham-adapter that makes it "more dedicated" :-) Can you post please how the config looks and which fields in the Homebridge config needs to be edited by the user and what this is and such?

**Comment by JackWolfskin42** [comment]
Like this?


{
  "description": "Add configuration for your accessories or platforms according to the docs of the plugins.",
  "accessories": [
    {
      "accessory": "Chamberlain",
      "name": "Garagentor",
      "username": "Hier den User",
      "password": "Hier das Passwort"
    }
  ],
  "platforms": []
}

**Comment by Apollon77** [comment]
It's just that? :-) cool

**Comment by fraeggle** [comment]
do i need a Homebridge (Hardware) or only take Hombride Adapter and add the configurations above?

**Comment by JackWolfskin42** [comment]
Yes, if you have a Chamberlain Gateway and an account, this Homebridge Adapter and configuration like above is enough - no Homebridge hardware!

**Comment by fraeggle** [comment]
Doesn't work  :-(
Add following (with correct Email and PW whitch i use on https://www.mychamberlain.eu/
What do i have to fill in the adapter?

![ham](https://user-images.githubusercontent.com/40692505/53719392-321b2b00-3e5e-11e9-973b-cde9a86015e6.JPG)
)

Error log:
{
  "description": "Add configuration for your accessories or platforms according to the docs of the plugins.",
  "accessories": [
    {
      "accessory": "Chamberlain",
      "name": "Garagentor",
      "username": "xxxxxx@xxxxx",
      "password": "yyyyyy"
    }
  ],
  "platforms": []
}



host.ioBroker-BPi | 2019-03-04 09:10:16.534 | error | instance system.adapter.ham.0 terminated with code 0 (OK)
-- | -- | -- | --
host.ioBroker-BPi | 2019-03-04 09:10:16.534 | error | Caught by controller[2]:     at Socket.onpacket (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:236:12)
host.ioBroker-BPi | 2019-03-04 09:10:16.533 | error | Caught by controller[2]:     at Socket.onack (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:312:9)
host.ioBroker-BPi | 2019-03-04 09:10:16.533 | error | Caught  by controller[2]:     at Socket.that.objects.getObjectView  (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:2713:25)
host.ioBroker-BPi | 2019-03-04 09:10:16.532 | error | Caught by controller[2]:     at adapter.getDevices (/opt/iobroker/node_modules/iobroker.ham/main.js:175:27)
host.ioBroker-BPi | 2019-03-04 09:10:16.531 | error | Caught by controller[2]:     at loadExistingAccessories (/opt/iobroker/node_modules/iobroker.ham/main.js:232:35)
host.ioBroker-BPi | 2019-03-04 09:10:16.531 | error | Caught by controller[2]:     at Object.start (/opt/iobroker/node_modules/iobroker.ham/lib/wrapper-handler.js:111:23)
host.ioBroker-BPi | 2019-03-04 09:10:16.530 | error | Caught by controller[2]:     at HomebridgeWrapper.init (/opt/iobroker/node_modules/homebridge-plugin-wrapper/index.js:216:17)
host.ioBroker-BPi | 2019-03-04 09:10:16.529 | error | Caught by controller[2]:     at Server.run (/opt/iobroker/node_modules/homebridge-plugin-wrapper/homebridge/server.js:87:38)
host.ioBroker-BPi | 2019-03-04 09:10:16.528 | error | Caught  by controller[2]:     at Server._loadAccessories  (/opt/iobroker/node_modules/homebridge-plugin-wrapper/homebridge/server.js:286:42)
host.ioBroker-BPi | 2019-03-04 09:10:16.527 | error | Caught by controller[2]:     at API.accessory (/opt/iobroker/node_modules/homebridge-plugin-wrapper/homebridge/api.js:64:13)
host.ioBroker-BPi | 2019-03-04 09:10:16.526 | error | Caught by controller[2]: Error: The requested accessory 'Chamberlain' was not registered by any plugin.
host.ioBroker-BPi | 2019-03-04 09:10:16.525 | error | Caught by controller[1]: [3/4/2019, 9:10:16 AM] No plugins found. See the README for information on installing plugins.
host.ioBroker-BPi | 2019-03-04 09:10:16.523 | error | Caught  by controller[0]: [3/4/2019, 9:10:15 AM] Plugin  /opt/iobroker/node_modules/homebridge-plugin-wrapper package.json does  not contain the keyword 'homebridge-plugin'.
ham.0 | 2019-03-04 09:10:16.425 | info | starting. Version 1.0.0 in /opt/iobroker/node_modules/iobroker.ham, node: v6.16.0

**Comment by fraeggle** [comment]
ok think i have to install the plugin in the adapater
shame on me

**Comment by fraeggle** [comment]
What do you use for Polling Interval?

**Comment by JackWolfskin42** [comment]
I mainly use it in IObroker to be able to to control via Amazon Alexa. Polling isn't interesting so I set it to 300 (s).

**Comment by quellenfeuer** [comment]
Hallo zusammen,
leider ist mein Englisch echt schlecht.
Kann mir jemand eventuell auch mit screenshots erklären wie ich mein chamberlain in
den iobroker integrieren kann? Kriege es irgendwie nicht hin.
Habe den ham-0 adapter installiert und wie geht es dann weiter?

Gruß

**Comment by I3imbel** [comment]
Hi,
Wo genau hängt es denn?

**Comment by fraeggle** [comment]
You only have to inset your credentials in the configuration in ham.
ex.:
{
  "description": "Add configuration for your accessories or platforms according to the docs of the plugins.",
  "accessories": [
    {
      "accessory": "Chamberlain",
      "name": "whateveryouwant",
      "username": "yourchamberlainusername",
      "password": "yourchamberlainpassword"
    }
  ],
  "platforms": []
}

after connected you will have yout device under ham.0.name.....

**Comment by flipkill1985** [comment]
Hello,

Is this also possible with the MyQ Starter Kit?
![image](https://user-images.githubusercontent.com/9048651/69485132-778fe600-0e3b-11ea-8839-4abea0146969.png)

**Comment by StrathCole** [comment]
I have the adapter running with myQ starter kit. Maybe you have to set your polling interval to at least some value above 0 (I have it at 10).
Also might try to set "deviceId" in the config as the starter kit offers two ids whereas one of them is only the controller itself that does not give any useful data.

**Comment by StrathCole** [comment]
I have managed to create an adapter for MyQ now. First version on github:
https://github.com/StrathCole/ioBroker.myq

**Comment by JackWolfskin42** [comment]
Works fine for me with MyQ 828EV. switched from Homebridge to your Adapter for now...
Thanks!

**Comment by JackWolfskin42** [comment]
Sorry, didn' want to close this request yet, but leave it open for further feedback :-)

**Comment by TA2k** [comment]
For issues use https://github.com/StrathCole/ioBroker.myq/issues
