### ISSUE TITLE
Adapter für Smarthome Austria

### ISSUE THREAD

**Issue by delfser** [ioBroker/AdapterRequests#172]
Samrthome Austria ist das selbe wie Innogy nur mit anderer Anmeldung

**Comment by Apollon77** [comment]
see https://github.com/PArns/ioBroker.innogy-smarthome/issues/28 too

**Comment by mcm1957** [comment]
Sollte lt https://github.com/PArns/ioBroker.innogy-smarthome/issues/28 mit dem innogy-smarthome adapter funktionieren,

Repo: https://github.com/PArns/ioBroker.innogy-smarthome

Bitte bei Problemen dort ein issue eröffnen.
