### ISSUE TITLE
Homematic IP Wired

### ISSUE THREAD

**Issue by AHg125** [ioBroker/AdapterRequests#176]
Hallo,

die neuen Homematic IP Wired Module erscheinen in der Ansicht Objekte, es werden aber keine Werte/Daten angezeigt.
Es scheinen die Meta-Daten noch zu fehlen. Ist das in nächster Zeit geplant?  
Danke

**Comment by jogibear9988** [comment]
wo werden sie angezeigt? in welchem adapter? denke der issue ist hier falsch!

**Comment by AHg125** [comment]
sie werden im Homematic RPC Adapter angezeigt.
![hmipw](https://user-images.githubusercontent.com/48199855/53747787-56015f80-3ea4-11e9-968d-fd693c40bba0.png)

**Comment by foxriver76** [comment]
@AHg125 ist definitiv geplant, allerdings scheint die XML-RPC API das noch nicht zu unterstützen. Sobald die API die neuen Geräte unterstützt, werden wir dies natürlich auch tun.
Allerdings ist dieser Thread hier für neue Adapter, jedoch wird hierfür der existente hm-rpc Adapter erweitert, daher mache ich hier mal zu.
