### ISSUE TITLE
Weather Wunderground Adapter for new API Key

### ISSUE THREAD

**Issue by gruenerpanzer** [ioBroker/AdapterRequests#177]
Hallo zusammen,

mitte Februar wurde die neue APi in Weatherunderground implementiert wodurch die neuen API Keys nicht mehr mit dem bisherigen Adapter/Commandos funktionieren, daher die Bitte an einen Developer, einen Adapter mit Hilfe der neuen API Dokumentation zu entwickeln.
 
 ----

https://apicommunity.wunderground.com/weatherapi/topics/end-of-feb-wu-api-update

The gateway for the new API keys for PWS uploaders is open.

Cut and paste this URL into your browser:  

https://www.wunderground.com/member/api-keys

Next, once you have your new key, you can use it in the NEW (not old!) API’s commands.  The documentation for those commands is here:  

https://docs.google.com/document/d/1eKCnKXI9xnoMGRRzOL1xPCBihNV2rOet08qpE_gArAY/edit

 ----
Grüße,

Alex

**Comment by Apollon77** [comment]
bitte ein Issue im WU Adapter anlegen. ist ja kein neuer Adapter :-)

Aber ja ich habe auch das Problem.

Wichtig ist aber das das nur für PWS Nutzer geht die Ihre Daten abholen können. Bzw ich will mal schauen was ich noch so finde

**Comment by gruenerpanzer** [comment]
Hallo,

kannst du mir den Link schicken, da ich die Sektion im Forum dafür nciht finden kann!? :(

PS: Stimmt, werde ich dann noch ergänzen.


Grüße,

Alex

**Comment by Apollon77** [comment]
https://github.com/dschaedl/ioBroker.weatherunderground
