### ISSUE TITLE
Adapter für Wasserstände Flüsse / water level rivers 

### ISSUE THREAD

**Issue by Breiti66** [ioBroker/AdapterRequests#179]
Adapter for water level of rivers.
The Data is provided here:
https://www.elwis.de/DE/dynamisch/gewaesserkunde/wasserstaende/index.php?target=2&gw=RHEIN

**Comment by larsdecker** [comment]
Leider gibt es dazu noch keine API (jedenfalls hab ich keine gefunden). Wir könnten also nur die Webseite parsen und dann im ioBroker darstellen. Das sollte machbar sein. 

@Breiti66
Interessant wäre dabei nur zu wissen, welche Daten den benötigt werden? Möchtest du alle Orte haben, oder soll man einzelne auswählen?

**Comment by Breiti66** [comment]
Der Wunsch waere, dass man sich seinen jeweiligen Ort auswählen kann mit dem aktuellen Wert.

**Comment by larsdecker** [comment]
Wenn ich Zeit finde, baue ich mal eine erste Version.

**Comment by larsdecker** [comment]
Okay, es gibt sogar eine API ;-)

@Breiti66 
Bitte schaue mal nach, ob du dort deine Stationen findest die für dich interessant sind.
https://www.pegelonline.wsv.de/webservice/dokuRestapi

**Comment by larsdecker** [comment]
Ich hab mal ein Projekt gestartet. Wird vermutlich aber noch etwas dauern, bevor es fertig ist.

https://github.com/larsdecker/iobroker.pegelonline

**Comment by Breiti66** [comment]
Hallo Lars,
ja für mich wäre die Messstelle 25100100 wichtig.
Diese API hatte ich nicht gefunden, hatte mir einen Wolf gesucht.....

**Comment by DutchmanNL** [comment]
mja die API gibt ja alles in JSON format da ist das Einbinden eigentlich relatief "einfach" zu realisieren.
@larsdecker hat ja nen Anfang gemacht, da die API nur stations daten brauch halt nen admin interface machen fuer diese werte und dan die JSON auslesen ist im gründe keine Hexenarbeit.

**Comment by larsdecker** [comment]
Ja, genau, das wäre nur mein erster Adapter. Da muss man erstmal schauen, wie alles genau funktioniert.

Das auslesen selbst ist wirklich sehr einfach.

**Comment by DutchmanNL** [comment]
> Ja, genau, das wäre nur mein erster Adapter. Da muss man erstmal schauen, wie alles genau funktioniert.
> 
> Das auslesen selbst ist wirklich sehr einfach.

wen du Hilfe brauchst sag Bescheid !
Ich habe mehre adapter entwickelt (oder Gerade in Entwicklung) die auf dem JSON object Prinzip und API beruhen.

Mein Großbaustelle im moment ist SourceAnalytix, Discovery und ein Multicast-API adapter da ist gerade full time programming drin also keine zeit komplett von scratch diesen adapter zu machen aber helfe gerne auf die Sprünge !

Könnten uns dazu z.b. mal im teamspeak treffen.
BTW : Währe cool, wen du lust hast, das innerhalb der iobroker-community Organisation zu machen ?!
wir haben da eine Gruppe gegründet mit leuten die gerne adapter bauen, weiterentwickeln und lernen wollen und machen das in einer GitHub Organisation.
Haben auch eine telegram Gruppen fuer fragen usw, bist herzlich eingeladen !

Cheers,

Dutch

**Comment by larsdecker** [comment]
@DutchmanNL 

Bei einem Call über Teamspeak und Telegram bin ich gern mal dabei. Aktuell ist meine Zeit nur etwas eingeschränkt, da ich selbst gerade ein Haus baue, natürlich auch mit ioBroker. 

Meinen Adapter kann ich wenn er fertig ist, gern an die ioBroker Organisation übertragen, so dass auch andere Entwickler darauf Zugriff haben.

**Comment by DutchmanNL** [comment]
👍 

kannst dich ja mal bei mir melden wen de zeit und lust hast, im telegram erreichbar per @RaffiDuck und zu finden (fast täglich) in der SmartHome TeamSpeak community : 62.104.20.86:10038

**Comment by larsdecker** [comment]
@Breiti66 

Erste Versionen findest du hier: https://github.com/larsdecker/ioBroker.pegelonline

**Comment by Breiti66** [comment]
Hallo Lars,

 

ich bin heute erst dazu gekommen, sorry.

So weit, so gut. Installation ging ohne Probleme.

 

Ich habe es installiert, habe aber bei pegelonline.0.Station.Mainz.timeseries.currentMeasurement nur [object Object] und keine Werte.

Auch bei pegelonline.0.Station.Mainz.km  und Station.Mainz.number steht &nbsp;

 

Als  Verbesserung würde ich vorschlagen bei der Adapterkonfiguration auch die Messstation (z.B. Mainz) zur Auswahl zu stellen da der User ja eigentlich nur seinen Standort benötigt, nicht den ganzen Fluss.

 

Erst mal Dank für die Anstrengung. 

Hätte es gerne selbst gemacht um auch mal ein Adapter gemacht zu haben, aber ich habe ein nicht fertiges Haus gekauft und mache alles alleine fertig.

 

Gruß Ralph

 

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese E-Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser E-Mail sind nicht gestattet.
 
This email contains confidential and/or legally privileged information. If you are not the intended recipient or have received this email in error, please notify the sender immediately and destroy this email. Any unauthorised copying or dissemination of this email is strictly prohibited.

 

Von: Lars Decker [mailto:notifications@github.com] 
Gesendet: Dienstag, 7. Mai 2019 22:34
An: ioBroker/AdapterRequests
Cc: Breiti66; Mention
Betreff: Re: [ioBroker/AdapterRequests] Adapter für Wasserstände Flüsse / water level rivers (#179)

 

@Breiti66 <https://github.com/Breiti66> 

Erste Versionen findest du hier: https://github.com/larsdecker/ioBroker.pegelonline

**Comment by DutchmanNL** [comment]
beta ist online, issue dazu bitte in der repo hinterlegen : https://github.com/larsdecker/ioBroker.pegelonline
