### ISSUE TITLE
NEEO Adapter 

### ISSUE THREAD

**Issue by mikewolf** [ioBroker/AdapterRequests#180]
Ein Adapter für NEEO wäre interressant :?
https://planet.neeo.com/t/x1trmk/api-examples-to-get-https://planet.neeo.com/https://planet.neeo.com/t/631bj1/add-custom-values-to-json-of-the-forward-actions-feature-or-create-a-generic-device-for-api-communication-to-other-systems/18lvvs/introducing-the-neeo-sdk

**Comment by Apollon77** [comment]
The link is wrong ... please check

**Comment by mikewolf** [comment]
https://github.com/NEEOInc/neeo-sdk
https://planet.neeo.com/t/x1trmk/api-examples-to-get-startedhttps://planet.neeo.com/category/sdk-api

**Comment by mikewolf** [comment]
https://planet.neeo.com/category/sdk-api
https://neeoinc.github.io/neeo-sdk/
