### ISSUE TITLE
Schellenberg Rollandenantrieb

### ISSUE THREAD

**Issue by digitalphat** [ioBroker/AdapterRequests#183]
Funkfernbedieung für auf und zu inkl wochentagsabhängige timer Funktion

**Comment by Apollon77** [comment]
Mehr Infos bitte?! links? Gibt es schon libraries die das anbinden? Was sind es für Protokolle?

**Comment by digitalphat** [comment]
Hallo Ingo. 

Hab eben gesehen dass es schon einen Eintrag gibt. Kannst du auf Dublicate setzten. Sorry. 

Smart Friends Box (SCHELLENBERG, ABUS, STEINEL, Paulmann) #78

Mit freundlichen Grüßen,

Ralf Schüngel 

-sent from my mobile device-

Am 17.03.2019 um 09:32 schrieb Ingo Fischer <notifications@github.com>:

Mehr Infos bitte?! links? Gibt es schon libraries die das anbinden? Was sind es für Protokolle?
