### ISSUE TITLE
Dyson Pure Hot + Cool / Link Ventilator

### ISSUE THREAD

**Issue by do1osc** [ioBroker/AdapterRequests#186]
Hallo,
Ich schlage hier mal vor, einen Adapter zu schreiben zur Steuerung des Dyson Pure Hot + Cool bzw. des Vorgängers Dyson Pure Link - Ventilators.

Es gibt dazu schon eine [Javascript-Lib](https://github.com/auchenberg/dyson-purelink).

**Comment by do1osc** [comment]
Hier noch eine passende [Python lib](https://github.com/CharlesBlonde/libpurecoollink)

**Comment by do1osc** [comment]
Hier auch noch eine ausfürliche [Dokumentation](https://libpurecoollink.readthedocs.io/en/stable/) zur Python Lib.

**Comment by MattL0** [comment]
Would also be interested in this

**Comment by totti1171** [comment]
dito

**Comment by Apollon77** [comment]
3 Interessenten aber keiner Klickt auf "Thumbs up" im ersten Beitrag ... damit ist das leider unsichbar :-(

**Comment by do1osc** [comment]
> 3 Interessenten aber keiner Klickt auf "Thumbs up" im ersten Beitrag ... damit ist das leider unsichbar :-(

Wo muss man da drücken ? Ich finde/Sehe da leider nichts ...

**Comment by Apollon77** [comment]
https://github.com/ioBroker/AdapterRequests#how-to-use-this

**Comment by kkickingereder** [comment]
https://user-images.githubusercontent.com/61472717/75275159-5e188480-5804-11ea-86a5-a3802fe64e51.png

https://user-images.githubusercontent.com/61472717/75275205-712b5480-5804-11ea-93f2-741e8e2184d1.png

**Comment by benjaminbalo** [comment]
Adapter for this would be great! I can test, but i'm not into programming :(

**Comment by do1osc** [comment]
Short Information:
The Dyson-Skill creates a Smart-Home-Device, now.
So it is possible to control this device via speech-recognisation of alexa.

**Comment by Apollon77** [comment]
https://github.com/lukasroegner/homebridge-dyson-pure-cool
https://github.com/joe-ng/homebridge-dyson-link

**Comment by Grizzelbee** [comment]
Just developing a dyson adaptor and searching for testers. Anyone is welcome:
https://forum.iobroker.net/topic/37200/dyson-air-purifier-adapter-tester-gesucht
