### ISSUE TITLE
Audi Connect

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/AdapterRequests#188]
Related to #118, #164 

Python API is available at https://github.com/davidgiga1993/AudiAPI

I can test ("hardware" available :laughing: ).

**Comment by gfxdude-dus** [comment]
also interested ✌🏽 hardware available

**Comment by AlCalzone** [comment]
A lot of it seems to be implemented in https://smartcar.com/ which has a free tier. I'm not sure though if I'm willing to route this traffic through a 3rd party service. Maybe worth reverse engineering the npm module.

**Comment by AlCalzone** [comment]
Also seems to be possible with the VW Carnet Adapter: https://github.com/RPerkuhn/ioBroker.vw-carnet/issues/15

**Comment by AlCalzone** [comment]
This will most likely be solved with https://github.com/RPerkuhn/ioBroker.vw-carnet/pull/18

**Comment by TA2k** [comment]
integrated in vw we connect adapter
https://forum.iobroker.net/topic/26438/test-adapter-vw-connect-v0-0-x
