### ISSUE TITLE
Intertechno Adapter

### ISSUE THREAD

**Issue by Pi3BPaul** [ioBroker/AdapterRequests#189]
Anregung
Hallo
Ich benutzte, bzw. habe noch immer einige Intertechno Aktoren am laufen. Gesteuert wird das bei mir mit der Android App "PowerSwitch" von Max Rosin und Markus Ressel.
Die App wird nicht mehr weiter entwickelt und sucht einen Nachfolger. Alles open Source und in Java?
Zitat: DEPRECATED
Dieses Projekt wird nicht mehr aktiv weiterentwickelt. Solltest du Interesse daran haben das Projekt unter Beachtung der Lizenz fortzuführen, melde dich gerne bei mir.

Vielleicht kann ja ein Programmierer einen Adapter daraus basteln. Als Gateways werden imho Intertechno, Brennenstuhl Brematic Home Automation Gateway oder das Simple Solutions ConnAir angesteuert. Eventuell lässt sich auch die Sonoff Bridge mit einbinden
Hier die Adresse: https://github.com/Power-Switch/PowerSwitch_Android

Grüße Paul

**Comment by steckenpferd** [comment]
Doppelt:
https://github.com/ioBroker/AdapterRequests/issues/65
