### ISSUE TITLE
SkyRC MC3000

### ISSUE THREAD

**Issue by nob0dy80** [ioBroker/AdapterRequests#190]
Would be fine to have an adapter for the SkyRC MC3000. Its  a bluetooth battary charger
https://www.akkuteile.de/ladegeraete/nitecoresysmax/skyrc-mc3000-profesionall-universal-analyse-ladegeraet-fuer-alle-rundzellen/a-500301/

This one i controled over bluetooth with an Android/IOS app.
Handling of this Charger is so hard, my wife isnt able to charge anything. My idea is to control it over a script so she can trigger it.

**Comment by Apollon77** [comment]
Is there any info available on API, protocol or such?

**Comment by nob0dy80** [comment]
@Apollon77 
I try to contact the vendor. But its chinese... so i dont think i will get anything.
After that, it seems like i have to sniff it.
Do you have any experience in sniffing bluetooth traffic?

**Comment by nob0dy80** [comment]
Vendor wont give out any api informations.

**Comment by mrMuppet** [comment]
Via USB there is an open source software that reads the data from skyrc chargers: [DataExplorer](http://www.nongnu.org/dataexplorer/). Perhaps this could help.

**Comment by HTRiepe** [comment]
As Base API https://github.com/kolinger/skyrc-mc3000 for ideas?
