### ISSUE TITLE
LG SmartThinQ

### ISSUE THREAD

**Issue by GTV1** [ioBroker/AdapterRequests#191]
Hallo ! 
Ich beantrage ein Adapter für die LG SmartThinQ Technology.
 Ich möchte die Temperaturen meines Side By Side Kühlschranks auslesen können.  Wenn ich das richtig sehe ist das hier eine ( veraltetet ) API. 
http://us.smartthinq.com/images/grid/smartThinQ%203rd%20party%20openAPI.pdf  
und das hier 
https://github.com/sampsyo/wideq   
ein bestehender Phyton code .
Danke!

**Comment by Horgul123** [comment]
Fände ich auch klasse, um meine Klimaanlage zu steuern

**Comment by jlwin** [comment]
Ich würde dies für die Statusanzeige meiner Waschmaschine gerne verwenden wollen!

**Comment by linuxq** [comment]
Ich würde auch gerne den Status meiner LG Waschmaschine integrieren.

**Comment by DenisMtfl** [comment]
ich werde mich demnächst mal um solchen Adapter kümmern. Leider habe ich nur eine LG SmartThinQ Waschmaschine müsste man schauen ob wir es mit Klimaanlagen auch hinbekommen das wideq Projekt sollte das ja können.

**Comment by Apollon77** [comment]
Cool! Adapter development support gibts im Forum jederzeit. Da kist ein "Entwickler" unterforum

**Comment by ELK169** [comment]
> ich werde mich demnächst mal um solchen Adapter kümmern. 
Der Sommer naht! Und "demnächst" ist bestimmt jetzt schon...
Gibt es schon Anfänge/Fortschritte? Die Klimaanlage vollautomatisch zu steuern wäre schon nett... :-)

**Comment by Amnesia1211** [comment]
Mich würde das ganze auch Interessieren :-) habe auch eine Klimaanlage von LG und würde sie gerne über iObroker steuern.

**Comment by CNC-Maniac** [comment]
Mein Energieverbrauch könnte durch die Verbindung von Waschmaschine und der PV, deutlich effizienter werden.

**Comment by einarmiger0815** [comment]
Ich bräuchte den Adapter vorerst nur für die Waschmaschine, die Daten für die Cloud könnte ich @Apollon77 zur Verfügung stellen.

**Comment by DenisMtfl** [comment]
@einarmiger0815 ich auch für die Waschmaschine. Nur bei Waschmaschinen ist das Problem, das sie nicht immer an sind. Wir machen unsere Waschmaschine nach einem, Waschgang aus und dann ist sie offline. wideq hat ein Problem damit, wenn das Gerät aufeinmal wieder offline ist. Kommen nur noch Exceptions muss man prüfen!

**Comment by tonischabloni** [comment]
https://github.com/ssut/wideq-js#readme

hat das schon mal jemand probiert? ich bekomme leider bei der installation fehlermeldungen... also kann ich das nicht testen

**Comment by DenisMtfl** [comment]
Ja bei mir hat es wunderbar geklappt. Welche Fehlermeldung bekommst du?

**Comment by tonischabloni** [comment]
sudo npm install https://github.com/ssut/wideq-js/tarball/698109080a43526dd3f9bd6f1884d7a51d319506 --loglevel error --prefix "/opt/iobroker"
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /opt/iobroker/node_modules/wideq/dist/cli.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/opt/iobroker/node_modules/wideq/dist/cli.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm 6.4.15

**Comment by DenisMtfl** [comment]
> sudo npm install https://github.com/ssut/wideq-js/tarball/698109080a43526dd3f9bd6f1884d7a51d319506 --loglevel error --prefix "/opt/iobroker"
> npm ERR! code ENOENT
> npm ERR! syscall chmod
> npm ERR! path /opt/iobroker/node_modules/wideq/dist/cli.js
> npm ERR! errno -2
> npm ERR! enoent ENOENT: no such file or directory, chmod '/opt/iobroker/node_modules/wideq/dist/cli.js'
> npm ERR! enoent This is related to npm not being able to find a file.
> npm ERR! enoent
> 
> npm 6.4.15

Welches OS ? Welche Maschine ?

**Comment by DenisMtfl** [comment]
> sudo npm install https://github.com/ssut/wideq-js/tarball/698109080a43526dd3f9bd6f1884d7a51d319506 --loglevel error --prefix "/opt/iobroker"
> npm ERR! code ENOENT
> npm ERR! syscall chmod
> npm ERR! path /opt/iobroker/node_modules/wideq/dist/cli.js
> npm ERR! errno -2
> npm ERR! enoent ENOENT: no such file or directory, chmod '/opt/iobroker/node_modules/wideq/dist/cli.js'
> npm ERR! enoent This is related to npm not being able to find a file.
> npm ERR! enoent
> 
> npm 6.4.15

sudo npm install -g wideq

**Comment by tonischabloni** [comment]
> > sudo npm install https://github.com/ssut/wideq-js/tarball/698109080a43526dd3f9bd6f1884d7a51d319506 --loglevel error --prefix "/opt/iobroker"
> > npm ERR! code ENOENT
> > npm ERR! syscall chmod
> > npm ERR! path /opt/iobroker/node_modules/wideq/dist/cli.js
> > npm ERR! errno -2
> > npm ERR! enoent ENOENT: no such file or directory, chmod '/opt/iobroker/node_modules/wideq/dist/cli.js'
> > npm ERR! enoent This is related to npm not being able to find a file.
> > npm ERR! enoent
> > npm 6.4.15
> 
> sudo npm install -g wideq

das hat funktioniert! DANKE.. allerdings noch ne dumme frage, sollte ich dann einen neuen adapter haben?

**Comment by Andy200877** [comment]
Ich habe ebenfalls eine LG SmartQ Waschmaschine. Ich habe mir wideq auch mal installiert. 
`sudo npm install -g wideq
/usr/bin/wideq -> /usr/lib/node_modules/wideq/dist/cli.js
+ wideq@1.1.1
added 12 packages from 17 contributors in 1.77s`

Über wideq -V wird mir auch angezeigt, das die Version 1.1.1 installiert ist.
Aber wie geht es nun weiter und vor allem wie bekomme ich es dann nach iobroker ?

**Comment by vinze30** [comment]
+1

Hey gibt es hier schon etwas Neues? Hab seit gestern einen Lg Waschtrockner und würde diesen auch gerne einbinden :) das mit dem wideq verstehe ich nicht so richtig. Gibt es denn irgendwo eine Anleitung? 
Lg

**Comment by Firedragonweb** [comment]
Ich habe einen LG Waschtrockner und einen Kühlschrank und kann gerne bei der Entwicklung helfen, indem ich remote-Zugang dazu gewähre.

**Comment by DenisMtfl** [comment]
Ich bin leider noch immer nicht dazu gekommen mich mehr um den Adapter zu kümmern. Ich bleibe aber dran.

**Comment by DenisMtfl** [comment]
> 
> 
> Ich habe einen LG Waschtrockner und einen Kühlschrank und kann gerne bei der Entwicklung helfen, indem ich remote-Zugang dazu gewähre.

Was kann der LG Kühlschrank ?

**Comment by Firedragonweb** [comment]
Der ist ziemlich unspektakulär: Temperaturanzeige und -Einstellmöglichkeit, Wasserfilter und Express Freeze.

![photo_2020-07-16_16-08-12](https://user-images.githubusercontent.com/8174332/87681209-b2ee7480-c77e-11ea-9f8c-14d8bd4aee35.jpg)
![photo_2020-07-16_16-08-08](https://user-images.githubusercontent.com/8174332/87681211-b2ee7480-c77e-11ea-9b02-3523c8d64358.jpg)

**Comment by Diggerstyler** [comment]
**Hallo @DenisMtfl** 

ich habe mir eine **SmartTHING** fähige **Waschmaschine** gekauft. Diese ist per Wlan angebunden und in eine App einbindbar.
Jetzt würde ich diese gern in meinen **IOBroker** einbinden, sehe allerdings keine Adapter dafür.
Habe das aktuell so gelöst das ich den Strom messe und dann Quasi die Logic entstehen lasse.
Ist aber bei ner "smarten" Waschmaschine sehr beschränkt meiner Meinung nach.
Bin dann auf den Verlauf hier gestoßen.
Wie wie weit ist den der Stand hier und wie kann ich unterstützen sodass wir etwas hinbekommen.
oder gibt es bereits eine Beta Version.

Würde meine Waschmaschine gern als Versuchsobjekt zur Verfügjung stellen wenn dies benötigt wird.

Danke für einen Austausch.

LG Maik

**Comment by DenisMtfl** [comment]
Leider habe ich noch nie einen Adapter für ioBroker entwickelt, bin zwar Software Entwickler aber im anderen Bereich. 
Ich hoffe das ich bald mal das Thema angehen kann. 
Es gibt von dem Typen: [](https://github.com/sampsyo/wideq) eine sehr gute Library für das LG Thema das musste man in ein ioBroker Adapter integrieren.

**Comment by ulwilgrim** [comment]
Schließe mich hier auch mal an. Würde auch gerne meine Waschmaschine einbinden.

**Comment by doc-snyder** [comment]
Hallo, ich wäre auch an einen solchen Adapter interessiert. Ich würde gern unseren Waschtrockner in iobroker integrieren.

**Comment by ELK169** [comment]
OT: für Waschmaschine und Wäschetrockner hat sich bei mir ein Strommess-Shelly bewährt. Recht einfach im Zählerschrank in die Zuleitung einbaubar, funktioniert zuverlässig.

**Comment by deejay808** [comment]
> Hallo @Diggerstyler
> 
> Leider habe ich noch nie einen Adapter für ioBroker entwickelt, bin zwar Software Entwickler aber im anderen Bereich.
> Ich hoffe das ich bald mal das Thema angehen kann.
> Es gibt von dem Typen: https://github.com/sampsyo/wideq eine sehr gute Library für das LG Thema das musste man in ein ioBroker Adapter integrieren. Diese Libary habe ich schon mal mit meiner Waschmaschine getestet und hat wunderbar funktioniert.

I tested the latest version of this library with AC from LG and it works perfectly. I am also waiting for an IOBroker adapter ...

**Comment by Moskito99** [comment]
Hallo! Ich hänge mich hier auch mal ran. Wär schön, einen Adapter zu haben um eine Waschmaschine über den iobroker zu steuern.

**Comment by DarthPride** [comment]
Hallo zusammen, ich reihe mich hier mal mit ein. Bin seit dem letzten Sommer stolzer Besitzer einer ThinkQ-Klimaanlage und würde diese auch gerne mittels ioBroker ansteuern können.

**Comment by ELK169** [comment]
Und gerade bei der Klimaanlage kommt man mit einem IR-Sender auch nicht weiter, weil die Fernbedienungen immer nur den Powerstatus **um**schalten und wärmer/kälter können. Also keine zuverlässige Möglichkeit, eine bestimmte Temperatur anzusteuern.
Der vorhandene LG-Skill wurde vor ein paar Monaten deutlich verschlimmbessert... zu Anfang ging es noch mit "Alexa, schalte die Klimaanlage an", jetzt braucht es aber "Alexa, sage LG, schalte die Klimaanlage an" und dann dauert es gefühlt eine Minute, bis was passiert...
Mit den bereits verfügbaren Projekten (wideq und hass-smartthinq) kann ich leider nichts anfangen... Python ist nicht meins und mit Javascript komme ich zwar stümperhaft klar und habe auch den Adapter für meine eigene Hardware hinbekommen, aber für diese Umsetzung reicht es wohl lange nicht.
Ich schätze aber, dass ein Python- und Javascript-Kenner den Adapter recht einfach hinbekommen könnte. Die aufwändige Forschungsarbeit, das Protokoll zu untersuchen ist ja schon gemacht.
Also, traut euch! Der gesammelte Dank ist euch sicher!

**Comment by Phalynx** [comment]
Hey, ein Status meiner Waschmaschine in ioBroker wäre klasse

**Comment by Chillkroete1206** [comment]
Hallo zusammen,
an dieser Stelle von mir auch nochmal die starke Interessensbekundung an einem Adapter für LG Thinq.
Mein persönlicher Usecase wäre das Steuern meiner LG Thinq Waschmaschine. Im konkreten Fall geht es um das Starten der vorbereiteten Waschmaschine bei PV-Überschuss.

Wie kann ich die Entwicklung eines Adpaters unterstützen?
Danke und Gruß
Chillkroete

**Comment by DenisMtfl** [comment]
> Mein persönlicher Usecase wäre das Steuern meiner LG Thinq Waschmaschine. Im konkreten Fall geht es um das Starten der vorbereiteten Waschmaschine bei PV-Überschuss.

Ich glaube da gibt es das Problem das man die Waschmaschine nicht über Thnq anschalten kann!? Also meine Waschmaschine mit LG Thinq geht nach einiger Zeit alleine aus und ist über WLAN auch nicht erreichbar erst wenn ich sie wieder per Knopf an der Waschmaschine anschalten? Läuft es bei dir anders? Meiner Meinung nach kann man über wideq nur die Waschmaschine monitoren.

**Comment by Firedragonweb** [comment]
Doch, das geht, aber nur, wenn die WM in einem speziellen Modus ist, den man an der Maschine einschalten muss. Zumindest geht das über die App :)

**Comment by DenisMtfl** [comment]
> Doch, das geht, aber nur, wenn die WM in einem speziellen Modus ist, den man an der Maschine einschalten muss. Zumindest geht das über die App :)

Oh okay das wusste ich noch garnicht. Danke für den Hinweis. Und die bleibt dann immer im StandBy? Ist doch auch nicht gerade Zielführend und Stromsparend?

**Comment by Firedragonweb** [comment]
Ich denke mal, die Leistungsaufnahme der vorbereiteten Maschine im Standby ist im Vergleich zur eigentlichen Waschleistung sehr klein. Es könnte sich also mindestens wirtschaftlich, aber auch im Sinne der Umwelt durchaus lohnen, die Waschleistung in den Bereich zu verschieben, wo der Strom aus lokaler PV Produktion kommt.

**Comment by LuckyStrikeSlv** [comment]
Ich würde das auch mal pushen, habe großes Interesse an einem Adapter ;-) 
Kann man da irgendeinen Anreiz geben?

**Comment by MedizinPumPer** [comment]
Moin. Zu dem Thema hatte ich diese Anleitung gefunden:
https://forum.iobroker.net/topic/41747/lg-smartthinq-waschmaschine-in-iobroker-einbinden/5?_=1621977814859&lang=de

An sich eine super Anleitung, jedoch hapert es bei mir auch an einigen Stellen. Ich muss mir das auch mal genauer anschauen…

**Comment by TA2k** [comment]
Wenn noch interesse besteht kann ich mir das anschauen wenn jemand zugangsdaten bereitstellen kann
einfach via pn im forum 
https://forum.iobroker.net/user/tombox

**Comment by einarmiger0815** [comment]
@TA2k - du hast PN.

**Comment by TA2k** [comment]
Ich habe mal ein Adapter geschrieben
https://forum.iobroker.net/topic/46498/test-adapter-lg-thinq-v0-0-1

**Comment by Firedragonweb** [comment]
Ich kann nächste Woche oder so Zugang für einen Kühlschrank und einen Waschtrockner bereitstellen, die Remote-Befehle unterstützen.

**Comment by Diggerstyler** [comment]
Hallo,

Ich hätte auch eine Waschmaschine.
Gern PN dann geb ich die Zugangsdaten frei....
Gruß

**Comment by einarmiger0815** [comment]
So, habe den Adapter mal installiert und die Instanz hinzugehügt.

Nach dem Eintragen der Daten im Log kommt:


lg-thinq.0 | 2021-07-22 15:03:17.306 | info | (8054) Found: 1 devices
lg-thinq.0 | 2021-07-22 15:03:15.898 | info | (8054) Login successful
lg-thinq.0 | 2021-07-22 15:03:13.782 | info | (8054) starting. Version 0.0.1 in /opt/iobroker/node_modules/iobroker.lg-thinq, node: v14.17.3, js-controller: 3.3.14

Funktioniert soweit. Gut, die Maschine ist gerade aus - aber nicht lange, wenn meine Frau heimkommt ... ;-)

Wahnsinn, was der Adapter für Werte herausquetscht.

Bei der Waschmaschine sind die wichtigen Daten unter "lg-thinq.0.id-der-waschmaschine.snapshot.washerDryer" als Datenpunkte zum Weiterverarbeiten zu finden.


Vielen Dank!!!

**Comment by Chillkroete1206** [comment]
Hallo,

ich habe auch eine LG Thinq Waschmaschine, die ich zum Test zur Verfügung stellen könnte. Was soll ich dafür wem per PN senden? LG Thinq login Daten an TA2k ?

Danke und Gruß!

**Comment by einarmiger0815** [comment]
Zu spät. 

> Ich habe mal ein Adapter geschrieben
> https://forum.iobroker.net/topic/46498/test-adapter-lg-thinq-v0-0-1

Zu spät. Der Adapter ist fertig, klicke auf den Link und teste einfach.

**Comment by GTV1** [comment]
Hallo ! Das ist ja Super das es jetzt einen Adapter für meinen Kühlschrank gibt. Vielen Dank an TA2k ! Ich konnte den Apdapter installieren und mich mit meinem Acount auch Anmelden. Im Adapter sehe ich jetzt sehr viele Werte aber welcher der Werte ist für die Temperatur  ? ( 2 müsten es sein für Küchlteil / Gefrieteil )

**Comment by GTV1** [comment]
![grafik](https://user-images.githubusercontent.com/49487346/127108333-a8f93ad9-e9f0-4dfe-a8be-a8f981fe1d3d.png)

Ich nehme an C01 und C02 sind die Fühler .. aber C01 Kühlteil / C03 Gefrierteil ... Aber die Werte dahinter sind in was für einem Format / wie müste ich die umrechnen ?

**Comment by GTV1** [comment]
Die Aktuellen Temperaturen sind im Display an meinem Kühlschrank sind akutell +5  und -21°C

**Comment by TA2k** [comment]
Ich denke das ist kein Status vom Kühlschrank eher registrierungsDate in UTC formatiert. Alle relevanten Informationen sind unter snapshot

**Comment by GTV1** [comment]
Hmm den Punkt snapshot habe ich gar nicht ?!

**Comment by GTV1** [comment]
> 
> 
> Ich denke das ist kein Status vom Kühlschrank eher registrierungsDate in UTC formatiert. Alle relevanten Informationen sind unter snapshot

Hallo @TA2k  ... ich hab mir alle Reiter noch mal angeschaut. Ich konnte keine "Temperaturen" in den Daten finden ...  was mache ich flasch ?

**Comment by GTV1** [comment]
Habe gerade unter Objekte noch mal alles gelöscht das IOBroker alles neu einlesen muste. Es wird viel erstellt aber auch jetzt sehe ich keine Temperaturen oder das EXpress Kühlung läuft oder der Filter gewechselt werden müste. Ich habe am KS auch mal auf Express Kühlen gestellt aber es ändert sich beim nächsten Update kein Wert...

**Comment by TA2k** [comment]
kontaktier mich mal über iobroker forum https://forum.iobroker.net/user/tombox

**Comment by GTV1** [comment]
> 
> 
> kontaktier mich mal über iobroker forum https://forum.iobroker.net/user/tombox

Du hast PM :-)

**Comment by LuckyStrikeSlv** [comment]
> kontaktier mich mal über iobroker forum

Schreibt aber auch hier rein, wenn es was neues gibt, ich verfolge mit großem Interesse 😁

Bei mir ist's eine LG Klimaanlage mit vielen undefinierbaren Datenpunkten im ioBroker.

**Comment by TA2k** [comment]
Das Problem ist
lg-thinq.0.xxx-id-xxx.platformType = thinq1 wird nicht unterstütz zur zeit nur thinq2
bei thinq2 sollte alles unter snapshot sein

**Comment by ubieberich** [comment]
Könntest Du bitte auch thinq1 umsetzen? Ich kann Dir die Zugangsdaten zu einem Waschtrockner mit Thinq1 geben.

**Comment by GTV1** [comment]
@TA2k  das wäre jetzt natürlich auch meine Bitte.

**Comment by TA2k** [comment]
eine erster thinq1 ist jetzt drin. Einfach neuinstallieren und adapter neustarten

**Comment by GTV1** [comment]
Nach dem TA2k den Adapter angepasst hat funktioniert jetzt auch bei mir ein V1 Gerät. Unser Kühlschrank wirft jetzt folgende Werte aus..  DANKE ! an TA2k für seine Arbeit !!

![grafik](https://user-images.githubusercontent.com/49487346/127498315-a05d134a-aca0-4043-853f-442a0a7a20c5.png)

**Comment by deejay808** [comment]
Hi
I installed the adapter. I have 4 LG AC devices that I can manage using [https://github.com/sampsyo/wideq](url) but waiting for support in iobroker. With the current adapter, I can see all devices with their id under lg-thinq.0 but there is no additional information specific for the AC devices. Can this be added?

Thanks!

**Comment by TA2k** [comment]
@deejay808 please share a screenshot of the snapshot folders

**Comment by LuckyStrikeSlv** [comment]
> @deejay808 please share a screenshot of the snapshot folders

Could you explain, which screenshot exactly would be helpful? I also have an LG AC, but I can't control it with the adapter.

**Comment by TA2k** [comment]
I need an overview what the adapter is creating or access to the account to reproduce this

**Comment by deejay808** [comment]
If I remember well, you added the information already in the adapter and I can see it. I just was not able to control it using iobroker. The minimum I want to do is turn it on/off. I also remember that I communicated this in a PM (which I cannot find anymore). If you have some time to work on this, it will be highly appreciated :-)

**Comment by TA2k** [comment]
Please send me credentials via iobroker forum again

**Comment by LuckyStrikeSlv** [comment]
> I need an overview what the adapter is creating or access to the account to reproduce this

@TA2k The adapter creates really much, I show you some of it and hope it's enough. Especially the entries in the channel «remote» look interesting, but I only can set them to true or false without getting an effect. 

![scr01](https://user-images.githubusercontent.com/83556270/141697744-06db5183-aa10-47cc-8e2b-7b603ed558bb.jpg)
![scr02](https://user-images.githubusercontent.com/83556270/141697745-8508e351-4741-43f1-a1e7-d4ba6006641d.jpg)
![scr03](https://user-images.githubusercontent.com/83556270/141697747-461002a2-3213-4b4b-891a-c5f7e2a71fcb.jpg)

**Comment by TA2k** [comment]
ok no snapshot I need access to an account with such a device please contact me via iobroker forum

**Comment by deejay808** [comment]
> ok no snapshot I need access to an account with such a device please contact me via iobroker forum

what is your username on the iobroker forum?

**Comment by deejay808** [comment]
> ok no snapshot I need access to an account with such a device please contact me via iobroker forum

My credentials are in your personal chat in the iobroker forum. I have just send an update message to you. There you can also find the description of the problem that is indicated by @LuckyStrikeSlv.

**Comment by LuckyStrikeSlv** [comment]
So @deejay808 already shared his credentials (thanks!) and you don't need mine anymore, @TA2k , right? Do you need any other information?

**Comment by TA2k** [comment]
im working on this

**Comment by TA2k** [comment]
@deejay808  @LuckyStrikeSlv Please reinstall the github version and test again

**Comment by LuckyStrikeSlv** [comment]
@TA2k I'm back at home and had time to test it, thank you for your work. Now there is a snapshot channel and the states seem to be correct. 

But at the remote channel I still can't remote the AC. Should the Get- and Set-states be buttons? values? I tried some but nothing happens.

**Comment by TA2k** [comment]
Yes you should have this state
lg-thinq.0.xxxx-xxx-xxx.remote.SetOperation

**Comment by LuckyStrikeSlv** [comment]
> Yes you should have this state lg-thinq.0.xxxx-xxx-xxx.remote.SetOperation

Yeah! That was the needed hint for me. All operations are listet at _lg-thinq.0.xxxx-xxx-xxx-.langPackProductTypeUri_ and can be set as string at _SetOperation_. It seems to work fine, thanks a lot! :-)

**Comment by TA2k** [comment]
Maybe you can a screenshot to show this

**Comment by deejay808** [comment]
> > Yes you should have this state lg-thinq.0.xxxx-xxx-xxx.remote.SetOperation
> 
> Yeah! That was the needed hint for me. All operations are listet at _lg-thinq.0.xxxx-xxx-xxx-.langPackProductTypeUri_ and can be set as string at _SetOperation_. It seems to work fine, thanks a lot! :-)

So far I have no .remote folder and the _lg-thinq.0.xxxx-xxx-xxx-.langPackProductTypeUri_ is empty
<img width="1440" alt="Screenshot 2021-11-22 at 11 57 46" src="https://user-images.githubusercontent.com/56301208/142849686-8437608b-921f-4d30-ac0f-c83e9af97988.png">

**Comment by LuckyStrikeSlv** [comment]
> @TA2k Maybe you can a screenshot to show this. Because setOperation should allow true or false

That's right, but after looking to the file at `lg-thinq.0.xxxx-xxx-xxx-.langPackProductTypeUri` I (maybe) realized how to use the commands:

I changed `lg-thinq.0.xxxx-xxx-xxx.remote.SetOperation` to String and pasted the command `AC_MAIN_OPERATION_ON_W`. The AC turned on. By pasting `AC_MAIN_OPERATION_OFF_W` a few times nothing happened but a "ping" sound from AC. After restarting the adapter, the AC turned off by pasting the command again.
 ⠀ 

> It seems to work fine

Maybe my statement was too hasty. It only worked a few times in that way. Many times pasting the command, the AC did nothing but a ping sound. Rare times the command worked after restarting the adapter. It seems to be randomly. I can't recognize a pattern. I think, we are on the right way but have to find out how to use the commands correctly.
 ⠀ 

> @deejay808  So far I have no .remote folder and the lg-thinq.0.xxxx-xxx-xxx-.langPackProductTypeUri is empty

Here is the [langPackProductTypeUri.txt](https://github.com/ioBroker/AdapterRequests/files/7583415/langPackProductTypeUri.txt). Have you tried to remove and reinstall the adapter because of the missing remote channel?

**Comment by TA2k** [comment]
I don think this is related you can enable debug mode to see what it is send to device.
Please reinstall the latest github version

**Comment by LuckyStrikeSlv** [comment]
@TA2k 

> Please reinstall the latest github version

I already reinstalled the latest version (0.0.2).

> you can enable debug mode to see what it is send to device. 

Unfortunately I do not know how and where to activate the debug mode... could you tell me?

**Comment by LuckyStrikeSlv** [comment]
Ok, it doesn't matter, what I paste to `lg-thinq.0.xxxx-xxx-xxx.remote.SetOperation`. 
At log it says just `(11792) {"ctrlKey":"SetOperation"}`.

That it worked sometimes, was just random. So I have no clue, how to control the AC.

**Comment by deejay808** [comment]
With the latest version, I experience the same behaviour as specified by @LuckyStrikeSlv. Furthermore, I noticed when the AC is turned on using iobroker, I can no longer control it with the LG Thinq app. So to turn the unit off, I have to use the remote of the device.

**Comment by deejay808** [comment]
> > @TA2k Maybe you can a screenshot to show this. Because setOperation should allow true or false
> 
> That's right, but after looking to the file at `lg-thinq.0.xxxx-xxx-xxx-.langPackProductTypeUri` I (maybe) realized how to use the commands:
> 
> I changed `lg-thinq.0.xxxx-xxx-xxx.remote.SetOperation` to String and pasted the command `AC_MAIN_OPERATION_ON_W`. The AC did turned on. By pasting `AC_MAIN_OPERATION_OFF_W` a few times nothing happened but a "ping" sound from AC. After restarting the adapter, the AC turned off by pasting the command again. ⠀
> 
> > It seems to work fine
> 
> Maybe my statement was too hasty. It only worked a few times in that way. Many times pasting the command, the AC did nothing but a ping sound. Rare times the command worked after restarting the adapter. It seems to be randomly. I can't recognize a pattern. I think, we are on the right way but have to find out how to use the commands correctly. ⠀
> 
> > @deejay808  So far I have no .remote folder and the lg-thinq.0.xxxx-xxx-xxx-.langPackProductTypeUri is empty
> 
> Here is the [langPackProductTypeUri.txt](https://github.com/ioBroker/AdapterRequests/files/7583415/langPackProductTypeUri.txt). Have you tried to remove and reinstall the adapter because of the missing remote channel?

How did you get the langPackProductTypeUri.txt file? In my view that object is empty.

**Comment by deejay808** [comment]
I looked at the content of the url that is contained in lg-thinq.0.270e9f10-6a31-11dc-9611-a06faa6f6833.modelJsonUri (content = https://eic.lgthinq.com:46030/api/webContents/modelJSON?modelName=modelJSON_401&countryCode=KR&contentsId=270e9f10-6a31-11dc-9611-a06faa6f6833&authKey=thinq) and I found the following in that file
<img width="435" alt="Screenshot 2021-11-23 at 11 20 28" src="https://user-images.githubusercontent.com/56301208/143007149-d5c726e1-1b27-4a0c-9cf9-de8b9a3aceb9.png">
:

**Comment by LuckyStrikeSlv** [comment]
> How did you get the langPackProductTypeUri.txt file? In my view that object is empty.

It's simple: In my view it was not empty ;-) I saved it as txt.
It looks like the commands are the same and it should be possible to send theese commands to the device or server. I don't know how the LG API works.

> Inoticed when the AC is turned on using iobroker, I can no longer control it with the LG Thinq app.

Exactly the same here...

**Comment by GreatSUN** [comment]
Hey guys...
I have tried using the current adapter, but always getting the following error: 
`lg-thinq.0 | 2022-02-23 13:24:15.910 | error | {"error":{"request":"/emp/v2.0/account/session/scvetter@gmail.com","code":"MS.001.10","message":"Already in use by 3rd-Party Registeration:GGL"}}
lg-thinq.0 | 2022-02-23 13:24:11.757 | info | starting. Version 0.0.4 in /opt/iobroker/node_modules/iobroker.lg-thinq, node: v14.19.0, js-controller: 3.3.22`

Can someone help here?

Thanks,
Stefan

**Comment by GreatSUN** [comment]
Found the solution... You need to have a direct LG Account rather than being registered through Google or Apple or likewise.
You can register with the same E-Mail directly to LG and request invitation to an existing Home, then switch accounts and approve it.
