### ISSUE TITLE
HE Tunnelbroker Endpoint Updater

### ISSUE THREAD

**Issue by PowerPan** [ioBroker/AdapterRequests#192]
Moin

Ich habe diesen Adapter entwickelt und würde mich freuen wenn er mit aufgenommen wird

https://github.com/PowerPan/ioBroker.tunnelproker-endpoint-updater

Im Forum habe ich ihn auch schon vorgestellt

https://forum.iobroker.net/topic/21709/neuer-adapter-he-tunnelbroker-net-endpoint-updater

Der Adapter Checker hat auch nur Grüne Haken
https://adapter-check.iobroker.in/

**Comment by Apollon77** [comment]
Perfekt, dann bist Du aber hier falsch :-)
Bitte unter https://github.com/ioBroker/ioBroker.repositories alles ansehen und checken und dann einen PR erstellen um es ins Latest Repo File einzufügen.

**Comment by Apollon77** [comment]
PS: as b/p ist Absicht? :-)
