### ISSUE TITLE
Hydrawise Bewässerung

### ISSUE THREAD

**Issue by stonehengej** [ioBroker/AdapterRequests#195]
Ein Adapter für Hydrawise wäre klasse.
https://www.hydrawise.com
API bekommt man wohl nur auf Anfrage:
https://support.hydrawise.com/hc/en-us/articles/360008965753-Account-API-Information
Hier hat jemand bereits etwas für Neo und IP-Symcon gebaut: https://mediola.answerbase.com/2301313/Darstellung-der-Informationen-eines-Bewässerungssystems-in-NEO
https://www.symcon.de/forum/threads/37530-Hunter-Hydrawise-einbinden

**Comment by Apollon77** [comment]
Ein paar mehr Informationen zu "Hydrawise" wären ebenso klasse :-)
Links zum Produkt? Links zu Anleitungen? Links zu verfügbaren APIs? Links zu verfügbaren Bibliotheken zu einer Anbindung?

**Comment by marcelk80** [comment]
Hydrawise ist eine Software die zur Bewässerung dient und kommt von Hunter. 
https://www.hydrawise.com/
Es können damit verschiendenste Bewässerungscontroller angesteuert werden:
https://www.hydrawise.com/content/hydrawise-controllers-and-hardware

**Comment by aDabbelju** [comment]
Eine API befindet sich wohl noch in der Entwicklung. Ich habe einmal nachgefragt und hoffe auf eine baldige und gute Antwort seitens Hunter.

**Comment by tomvdw69** [comment]
Einen API-Key könnte ich testweise zur Verfügung stellen...

**Comment by DutchmanNL** [comment]
hab mit die scripte mal angeschaut das sieht nach ner guten JSON aus die kann man eigentlich ganz leicht umsetzen in states.

Mit API documentation und nem key zu testen könnte wir mal schauen

**Comment by Cmax74** [comment]
Würde mich auf freuen, ich habe einen Hydrawise Hunter HC 6 im Einsatz und kann euch gern unterstützen (außer beim Programmieren).

**Comment by micha68** [comment]
Hi!
Leider kann ich keinen Adapter bauen, habe aber ein Skript zusammengewürfelt, dass die Daten aus der Api zieht. Leider gibt API1 nicht viel her - zb nicht die Wassermenge meines Sensors "Wasseruhr". Ich habe Hunter mal angemailt, ob es für API2 eine Doku gibt.

```
schedule('* * * * *', function(){

var url="https://app.hydrawise.com/api/v1/statusschedule.php?api_key=xxxx-xxxx-xxxx-xxxx"
request({url : url}, function (error, response, body) {
                CreateRelays(JSON.parse(body));
});

var url="https://app.hydrawise.com/api/v1/customerdetails.php?api_key=xxxx-xxxx-xxxx-xxxx"
request({url : url}, function (error, response, body) {
                CreateCustomer(JSON.parse(body));
});

})

function CreateCustomer(data){
//log(data.controllers);
if (existsState('javascript.0.hydrawise.user_lastcontact')==false)
    {
    createState('javascript.0.hydrawise.user_lastcontact');
    }
    setState('javascript.0.hydrawise.user_lastcontact', data.controllers[0].last_contact );

if (existsState('javascript.0.hydrawise.user_status')==false)
    {
    createState('javascript.0.hydrawise.user_status');
    }
    setState('javascript.0.hydrawise.user_status', data.controllers[0].status );
}

function CreateRelays(data){
 
if ("undefined" !== typeof  data.relays){    
    //log(data.relays);

var i;
    for (i = 0; i < data.relays.length; i++) 
{

    if (existsState('javascript.0.hydrawise.relay'+i+'_id')==false)
    {
    createState('javascript.0.hydrawise.relay'+i+'_id');
    }
    setState('javascript.0.hydrawise.relay'+i+'_id', data.relays[i].relay_id );

    if (existsState('javascript.0.hydrawise.relay'+i+'_time')==false)
    {
    createState('javascript.0.hydrawise.relay'+i+'_time');
    }
    setState('javascript.0.hydrawise.relay'+i+'_time', data.relays[i].time );

    if (existsState('javascript.0.hydrawise.relay'+i+'_run')==false)
    {
    createState('javascript.0.hydrawise.relay'+i+'_run');
    }
    setState('javascript.0.hydrawise.relay'+i+'_run', data.relays[i].run );

    if (existsState('javascript.0.hydrawise.relay'+i+'_run_min')==false)
    {
    createState('javascript.0.hydrawise.relay'+i+'_run_min');
    }
    setState('javascript.0.hydrawise.relay'+i+'_run_min', Math.round(data.relays[i].run/60) );

    if (existsState('javascript.0.hydrawise.relay'+i+'_name')==false)
    {
    createState('javascript.0.hydrawise.relay'+i+'_name');
    }
    setState('javascript.0.hydrawise.relay'+i+'_name', data.relays[i].name );

    if (existsState('javascript.0.hydrawise.relay'+i+'_period')==false)
    {
    createState('javascript.0.hydrawise.relay'+i+'_period');
    }
    setState('javascript.0.hydrawise.relay'+i+'_period', data.relays[i].period );

    if (existsState('javascript.0.hydrawise.relay'+i+'_timestr')==false)
    {
    createState('javascript.0.hydrawise.relay'+i+'_timestr');
    }
    setState('javascript.0.hydrawise.relay'+i+'_timestr', data.relays[i].timestr );    
}
  
if ("undefined" !== typeof  data.sensors){    
log (data.sensors);
var i;
    for (i = 0; i < data.sensors.length; i++) 
{
    //log(data.sensors);
}
}

}
else{console.warn('Response in JSON nicht gefunden ! ')}
 
}
```

**Comment by micha68** [comment]
Antwort von Hunter zu API2:

`the Graph QL API is designed for commercial application and monitoring more than 1 controller it does not offer any extra functionality than the RestAPI.`

**Comment by MichHan** [comment]
Hallo,

ich habe seit ein paar Tagen einen Hunter Hydrawise HC-Pro am Start und  verwende ioBroker. Habe mit Interesse dieses Request gelesen und würde gerne mit der Hardware unterstützen.

Hydrawise hat auch  eine Seite mit guten Informationen zu den beiden verfügbaren API im Netz:
https://support.hydrawise.com/hc/en-us/articles/360008965753-Account-API-Information


Die pdf Datei mit den Informationen zur REST-API ist auf dieser Seite verlinkt:
[Hydrawise REST API.pdf](https://github.com/ioBroker/AdapterRequests/files/6291513/Hydrawise.REST.API.pdf)


Habe gerade mal etwas mit den Informationen "gespielt" und das Abrufen der Informationen und auch einfache Aktionen, wie starten und stoppen einer Bewässerung per API hat problemlos geklappt.

Es wäre toll, wenn ich mit meinem Gerät und Zugang die Basis für eine Adapterentwicklung für ioBroker unterstützen könnte.

Gruß

Michael

**Comment by LuxBibi** [comment]
Hallo Community,
Hat jemand einen aktuellen Status zur ioBroker integration von Hunter Controlern? 
Gruss,und vielen Dank im Voraus für's update ... 
Luc

**Comment by chris-hoe** [comment]
+1 ... ich würde mich auch sehr über einen funktionierenden ioBroker Adapter für meine Hunter Hydrawise freuen - sowohl zur Auswertung, als auch zur Steuerung. 
Gibt es ev. jemanden, der daran arbeitet? Beim testen kann ich gerne helfen, über eine Spende lässt sich auch reden - für mehr fehlt mir leider die Zeit, tut mir leid.
Viele Grüße,
Christian

**Comment by Magnus8513** [comment]
Gibt es hier inzwischen schon etwas? Falls nicht, würde ich mir das mal ansehen.

**Comment by aDabbelju** [comment]
Mir ist hier noch keine Lösung bekannt. Ich biete mich auch gerne zum Testen an :-)

**Comment by chris-hoe** [comment]
Hallo Magnus,
nicht wirklich viel, außer dem, was hier bei dem Tiket steht. Im deutchen Forum gibt es noch [einen Thread](https://forum.iobroker.net/topic/6564/hydrawise-bew%C3%A4sserungsseuerung/13) zu dem Thema, aber die Überschneidungen zu den Infos hier sind sehr groß. Eine wirkliche Lösung ist mir nicht bekannt.
VG, Christian

**Comment by MichHan** [comment]
Hallo, ist mir aktuell auch nicht bekannt. Ich kann mit Hardware und Testzugang (API) unterstützen. Freue mich auf den Kontakt.

**Comment by JanneW3** [comment]
Hallo zusammen, 

der letzte Eintrag ist zwar schon lange her, aber vlt. ist noch jemand hier aktiv und kann mir den richtigen Input geben. Ich habe das Script installiert und dabei gesehen, dass die Zeitangaben in Unix sind. Meine Java-Fähigkeiten sind allerdings nicht prickelnd und ich habe so meine Probleme aus den Zeitangaben brauchbare Werte zu ermitteln.

Beispiel: 
![grafik](https://user-images.githubusercontent.com/102105100/165862362-859bab0e-43bb-488f-8d4e-fc512ee8f451.png)

Aus diesem Zeitwert erhalte ich die Uhrzeit

`Der Timestamp 1651186939 entspricht dem 29.04.2022 um 01:02:19 Uhr.
(gilt für UTC+2)`

Eine kurze Überprüfung im Hydravise-Konto ergibt, dass dieser Wert korrekt ist.

Der Wert 
`javascript.0.hydrawise.relayx_time`
sollte dann die tägliche Bewässerungsuhrzeit ergeben. Zumindest sehe ich dort eine Veränderung, wenn ich verschiedene Zeitpläne für Zonen anwende und die Zeiten veränder... Bei der Formel du bin ich dann allerdings ratlos.

**Comment by micha68** [comment]
Hallo!

Die Relaytime gibt an, in wie vielen Sekunden beregnet wird.
Willst Du also wissen, wann das nächste mal das Relay angesteuert wird, musst Du diese RelayTime + AktuelleTime rechnen.

Im ioBroker mache ich das so:
`a =  new Date().getTime() ;
    a=a+data.relays[i].time*1000;
    a =  formatDate(a, 'DD.MM. hh:mm');
    }
    setState('javascript.0.hydrawise.relay'+i+'_timeS', a );
`

Gruß
Micha

**Comment by aDabbelju** [comment]
Gibt es mittlerweile schon einen Adapter? Da ich mich mit der API vor kurzem beschäftigt habe, würde ich mich gerne mal daran probieren einen zu schreiben, fall es noch keinen gibt.

**Comment by mcm1957** [comment]
Da dieser Issue noch auf "Requested" steht gehe icch davon aus, dass es keinen Adapter gibt - zumindest keinen "offiziellen".

Ev. frag nochmal im Forum nach, z.B. in dem Thread: https://forum.iobroker.net/topic/6564/hydrawise-bew%C3%A4sserungsseuerung/16

Weiters liefert Google einen Adapter (https://github.com/Andreili1000/ioBroker.hydrawise) der aber auf den ersten Blick nicht finalisiert wirkt bzw. keine eleases aufzuweisen scheint. Ev. kannst du mit dem Entwickler Kontakt aufnehmen.

ICh setz den Adapter mal auf planned und assigne ihn dir.
Bitte lass uns wissen, wenn du mit einer Enticklung ernsthaft beginnst und/oder wenn du das Projekt einstellst.

Falls du Fragen hast, kannst du gerne im Forum und im Telegramm Channel Support bekommen.

Danke im Voraus für deinen Einsatz

**Comment by DutchmanNL** [comment]
> Gibt es mittlerweile schon einen Adapter? Da ich mich mit der API vor kurzem beschäftigt habe, würde ich mich gerne mal daran probieren einen zu schreiben, fall es noch keinen gibt. 

Soweit mir bekannt noch nicht, wen du dich dem annehmen willst sehr gerne bei fragen und bissl Hilfe Stellung stehe ich gerne zur Verfügung und würde das issue dan auch an dich assignen ☺️

**Comment by aDabbelju** [comment]
@DutchmanNL Dann versuche ich mich einmal daran und melde mich bei Fragen einfach :-)

**Comment by DutchmanNL** [comment]
> @DutchmanNL Dann versuche ich mich einmal daran und melde mich bei Fragen einfach :-) 

Cool viel Erfolg! Können uns auch gerne mal im Discord treffen bei Interesse oder fragen ☺️

**Comment by herb2805** [comment]
Würde mich auch gern als Tester anbieten. Grüße

**Comment by SentiQ** [comment]
Ich hatte die letzten Abende etwas Langeweile.
Falls jemand testen möchte: https://github.com/SentiQ/ioBroker.hydrawise
Aktuell nur auf einen Controller ausgelegt, da ich selbst nur einen besitze.

**Comment by reneschuster** [comment]
Die Installation und das Abrufen der Daten hat bisher funktioniert. Werde ich die Tage noch einmal genauer Testen. 
Schon mal vielen Dank.

**Comment by mcm1957** [comment]
@SentiQ 
@aDabbelju 

Hi
Zunächst DANKE für deine / eure Arbeot. ABER könntet ihr mich bitte aufklären ob es da nun 2 Adapter gibt oder einen.

Es gibt die Repos:

https://github.com/aDabbelju/ioBroker.hydrawise
https://github.com/SentiQ/ioBroker.hydrawise

Und es gibt npmjs

https://www.npmjs.com/package/iobroker.hydrawise

Das npmjs Verzeichnis verweist auf das aDabbelju Repository - enthält aber die Releasenotes von SentiQ.

Irgendwie ist das für mich (und wahrscheinlich auch User verwirrend). Welcher Code ist nun auf npm hochgeladen?
@SentiQ hast du das Repo und Npm übernommen? Oder seid ihr eine Person???

Bitte um Info / Klarstellung bzw. was npm betrifft um Bereinigung soweit möglich.

-----------

Bezüglich Test:
Bitte mach doch eien Therad im Forum auf (https://forum.iobroker.net/category/91/tester). Dort erreichst du mehr Testwillige als hier.

Und wenn der Adapter so halbwegs für User brauchbar ist, fordere bitte die Aufnahme in die Repos an. Wenn du dazu irgendweölche HIfle bracuchst, bite heri auder auf Telegramm melden.

McM1957

**Comment by SentiQ** [comment]
@mcm1957 sorry für die Verwirrung.

Ich habe eigentlich nur einen Fork angelegt und bisschen herum probiert und in dem Atemzug auch den npm-Release-Workflow mit getestet, da das neu für mich war.
Habe bisher nichts von @aDabbelju gehört und wollte den Adapter gern für mich am Laufen haben.
Bei npm ist derzeit der von mir angepasste Code.

**Comment by mcm1957** [comment]
Danke mal für die Klarstellung dass ihr 2 Personen seid :-)

Alles klar - hab jetzt nochmal bei npmjs nachgesehen. Das NPM Archiv hast *DU* angelegt. Damit bist du jetzt der rechtmäßige "Eigentümer" des Adapters ioBroker.hydrawise. (npm ist strikt first come - first serve).

Was allerdings falsch sein dürfte sind die links in package.json und io-package.json. Die dürftest du nicht angepasst haben. Der ist der npmjs Link falsch.

Falls du den Forklink in Github weghaben willst kannst du folgendes machen:
-) benenn deinen Fork um (z.B in ioBroker.hydrawise-fork)
-) benutze github (web) um mittels IMPORT ein neues Repo ioBroker.hydrawise anzulegen. Da ist dann alles wie im jetzigen Repo drinnen. Ist einem Fork sehr sehr ähnliuch nur ohne Fork-Link

Verwende den repo checker (auf iobroker.dev z.B.) um allfällige Fehler (links z.B.) bei der Übernahme zu entdecken.

Und aus Höflichkeitsgründen wäre ein Hinweis auf den Originalauthor im README.md ev. angebraucht.

Bitte meld dich hier oder auf Telegramm (https://t.me/+gsX-e8k4mLtmZjZk) wenn du Hilfe bei der Finalisierung brauchst.

McM1957

**Comment by mcm1957** [comment]
Nachtrag:
Wirf bitte node 14 aus workflows/test-and-release.yml raus und trag node 18 und node 20 ein.
Node 14 funktioniert seit Anfang dieser Woche nicht mehr bei Github Tests und wird von js-controller 5 nicht mehr unterstütz.

**Comment by mcm1957** [comment]
> > @aDabbelju willst du daran weiter arbeiten oder ist es für dich okay, wenn ich das weiter übernehme?
> 
> In den kommenden Wochen wollte ich das gerne mal fertig stellen, da ich selbst daran interessiert bin. In zwei Wochen habe ich wieder etwas Zeit und arbeite mich dort rein und melde mich hier nochmal. Wir können notfalls den Adapter in einer Session am Abend fertig stellen. Hoffentlich ist das okay für dich ☺️

DANKE fürs Melden und deine Arbeit.
Ich hab euch jetzt beide hier eingetragen. Gebt einfach Bescheid wenn der Adapter für einen Aufnahme in die Repositories bereit zu sein scheint. auch für dich @aDabbelju golt natürlich, dass du jede Hilfe bekommen kannst die du zur Finalisiserung brauchst. Einfach hier oder noch besser auf Telegramm (Link siehe oben) melden.

Und was NPM betrifft: Es ist definitiv möglich dass mehr als ein User vollen Zugriff auf ein NPM Repo hat. Detto sollte eine Übertragung möglich sein. Nur bitte nicht löschen - das blockiert soweit mir bekannt ist den Namen.

**Comment by MichHan** [comment]
Hi,
habe es mal installiert. Werte werden sofort abgerufen und alles so, wie es sein soll. Die Ansteuerung funktioniert auf. Bei x Sekunden starten funktioniert das. Während dieses Laufes kann man nicht x Sekunden aussetzen. Stoppen geht aber. Die Werte wie timestr werden entsprechend aktualisiert (= "now"). 

Sieht gut aus.

Gruß

Michael

**Comment by reneschuster** [comment]
Bei mir läuft der Adapter leider nicht stabil, hat noch jemand solche Probleme?

![image](https://github.com/ioBroker/AdapterRequests/assets/1628654/19fc6f24-05b3-4252-ae55-dc7b944ad369)

**Comment by pacco81** [comment]
Hi !
Geil, endlich ein Adapter ! **Tausend Dank an die Entwickler**. Mit den Scripten konnte ich nur scher umgehen.

Habe die v009 von SentIQ laufen und es hat auf Anhieb alles vom ProHC12 ausgelesen. Stop und run klappt auch.

Wie auch über das Script bekomme ich jedoch leider keine Sensordaten vom Flussensor sondern nur den Fixwert von "1.8927" bei "rate" der sich nie verändert. Aber das scheint API-seitig so zu sein.
**Hat einer von euch hier echte Durchflusswerte  bei rate gesehen ?**

Besten Dank und Gruß,
Sebastian

P.S. Wenn der Adapter direkt die Unix-Zeit in den time-Datenpunkten umrechnen könnte, wäre das prima. Ich quäle mich da immer mit blockly zum umrechnen um.

<img width="1071" alt="Bildschirmfoto 2023-06-24 um 21 53 30" src="https://github.com/ioBroker/AdapterRequests/assets/29131107/08e4d704-404b-4e95-b595-adfd4ac5e5a4">

**Comment by pacco81** [comment]
P.P.S Ich sehe gerade, dass für die einzelnen Beregnungskreise als Ordner-bezeichnung der Name von Hydrawise gezogen wird. Das gibt dann aber Huddel, wenn man bei Hydrawise die Bezeichnungen mal ändert, oder ?

Wäre eine generische Nummer 1,2,3 nicht besser und die sprechende Bezeichnungen als Datenpunkt eine Etage drunter ?

**Comment by SentiQ** [comment]
@pacco81 danke für deine Rückmeldung. Ich nehme mich der Punkte die Tage an.

**Comment by mbhomie007** [comment]
Wird der Hunter Regensensor auch mit ausgelesen?

**Comment by SentiQ** [comment]
@mbhomie007 keiner der Sensoren übermittelt sinnvoll Werte. Hatte dazu direkt Kontakt mit Hydrawise. Die sind somit leider alle nicht brauchbar.

**Comment by mbhomie007** [comment]
Der Regensensor sagt ja nur "Ausgelöst - Bewässerung wird geblockt" oder "Nicht ausgelöst - Bewässerung wird nicht geblockt".

Also 1 oder 0.

Müsste doch auszulesen sein oder?

Wird jedenfalls unter der API angegeben.
![Screenshot_20230625_124919_Chrome.jpg](https://github.com/ioBroker/AdapterRequests/assets/64688879/4e9950ef-6b8b-4c17-870d-14f0c1435769)

**Comment by Jakoweb** [comment]
> Bei mir läuft der Adapter leider nicht stabil, hat noch jemand solche Probleme?
> 
> ![image](https://user-images.githubusercontent.com/1628654/245760789-19fc6f24-05b3-4252-ae55-dc7b944ad369.png)

Ja, diese Probleme habe ich auch, auch wenn meine Logeinträge anders lauten:

```
09:30:46.952 info hydrawise.0 (621204) starting. Version 0.0.9 (non-npm: SentiQ/ioBroker.hydrawise#95f8352fe43b40f7bb6ecf6912db3d93b9859fd8) in /opt/iobroker/node_modules/iobroker.hydrawise, node: v18.16.0, js-controller: 4.0.24
09:30:47.012 info hydrawise.0 (621024) config apiKey: XXXX-XXXX-XXXX-XXXX
09:30:49.411 warn hydrawise.0 (623261) received 429 response from /api/v1/customerdetails.php with content: "Exceeded maximum number of requests. You cannot make more than 5 requests in any 5 minute period to this endpoint."
09:30:49.430 info hydrawise.0 (623261) terminating
09:30:49.432 warn hydrawise.0 (623261) Terminated (UNCAUGHT_EXCEPTION): Without reason
``` 

Dasselbe Spiel wiederholt sich solange, bis der Neustart wegen häufiger Abstürze unterbunden wird. Vorher ist der Adapter etwa 45 Minuten klaglos gelaufen. Es scheint, als würden im Laufe der Zeit die Abfragen nicht minütlich gestellt, sondern etwas schneller (oder die Serveruhr bei Hydrawise geht langsamer), so dass es zur Fehlermeldung kommt. Durch den Neustart wird eine wiederholte Abfrage gestartet, was natürlich ebenfalls nicht geht.

Ich sehe zwei Möglichkeiten zur Abhilfe:

1. Verlängerung des Abfrageintervalls
2. Abfangung der 429 response im Adapter, so dass dieser nicht terminiert, sondern eine weitere Minute (oder mehr?!) aussetzt.

**Comment by SentiQ** [comment]
@reneschuster @Jakoweb die Abstürze sollten mit 0.0.10 behoben sein

@pacco81 ich habe deinen Vorschlag mit der Ordnerbezeichnung umgesetzt. Unter "timestr" wird nun der Date-String der nächsten Bewässerung angezeigt.
Die Sensoren übernehme ich 1:1 aus der API. Ich habe aktuell nur den Regensensor, den ich aber noch nicht getestet habe. Den Durchflusssensor installieren ich erst in den kommenden Wochen.

**Comment by mbhomie007** [comment]
Wie sieht es mit der Aufnahme in die Repositories aus? 😁

**Comment by reneschuster** [comment]
> @reneschuster @Jakoweb die Abstürze sollten mit 0.0.10 behoben sein
> 
> @pacco81 ich habe deinen Vorschlag mit der Ordnerbezeichnung umgesetzt. Unter "timestr" wird nun der Date-String der nächsten Bewässerung angezeigt. Die Sensoren übernehme ich 1:1 aus der API. Ich habe aktuell nur den Regensensor, den ich aber noch nicht getestet habe. Den Durchflusssensor installieren ich erst in den kommenden Wochen.


@SentiQ Vielen Dank für den fix, läuft aber leider immer noch nicht stabil.


```
2023-06-28 11:32:36.586 - info: hydrawise.0 (4882) starting. Version 0.0.10 (non-npm: SentiQ/ioBroker.hydrawise#9687be3ac4a76100f3b723bf4af40777926b38d6) in /opt/iobroker/node_modules/iobroker.hydrawise, node: v18.16.1, js-controller: 4.0.24
2023-06-28 11:32:36.594 - info: hydrawise.0 (4882) config apiKey: XXXX-XXXX-XXXX-XXXX
2023-06-28 11:32:37.671 - warn: hydrawise.0 (4882) Object hydrawise.0.schedule.1 is invalid: obj.common.name has an invalid type! Expected "string" or "object", received "number"
2023-06-28 11:32:37.672 - warn: hydrawise.0 (4882) This object will not be created in future versions. Please report this to the developer.
2023-06-28 11:32:38.026 - warn: hydrawise.0 (4882) Object hydrawise.0.schedule.2 is invalid: obj.common.name has an invalid type! Expected "string" or "object", received "number"
2023-06-28 11:32:38.026 - warn: hydrawise.0 (4882) This object will not be created in future versions. Please report this to the developer.
2023-06-28 11:32:38.345 - warn: hydrawise.0 (4882) Object hydrawise.0.schedule.3 is invalid: obj.common.name has an invalid type! Expected "string" or "object", received "number"
2023-06-28 11:32:38.345 - warn: hydrawise.0 (4882) This object will not be created in future versions. Please report this to the developer.
2023-06-28 11:32:38.705 - warn: hydrawise.0 (4882) Object hydrawise.0.schedule.4 is invalid: obj.common.name has an invalid type! Expected "string" or "object", received "number"
2023-06-28 11:32:38.705 - warn: hydrawise.0 (4882) This object will not be created in future versions. Please report this to the developer.
2023-06-28 11:32:38.977 - warn: hydrawise.0 (4882) Object hydrawise.0.schedule.99 is invalid: obj.common.name has an invalid type! Expected "string" or "object", received "number"
2023-06-28 11:32:38.978 - warn: hydrawise.0 (4882) This object will not be created in future versions. Please report this to the developer.
2023-06-28 11:32:40.012 - info: hydrawise.0 (4882) State value to set for "hydrawise.0.customer.current_controller" has to be type "number" but received type "string"
2023-06-28 11:32:40.058 - info: hydrawise.0 (4882) State value to set for "hydrawise.0.customer.controllers.PRO-HC 6.last_contact" has to be type "string" but received type "number"
2023-06-28 11:35:39.598 - info: hydrawise.0 (4882) error ECONNABORTED from /api/v1/statusschedule.php: timeout of 3000ms exceeded
2023-06-28 11:35:39.599 - error: hydrawise.0 (4882) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-06-28 11:35:39.599 - error: hydrawise.0 (4882) unhandled promise rejection: Cannot read properties of undefined (reading 'status')
2023-06-28 11:35:39.599 - error: hydrawise.0 (4882) TypeError: Cannot read properties of undefined (reading 'status')
at /opt/iobroker/node_modules/iobroker.hydrawise/build/main.js:273:28
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-06-28 11:35:39.599 - error: hydrawise.0 (4882) Cannot read properties of undefined (reading 'status')
2023-06-28 11:35:39.601 - info: hydrawise.0 (4882) terminating
2023-06-28 11:35:39.601 - warn: hydrawise.0 (4882) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-06-28 11:35:40.219 - error: host.iob instance system.adapter.hydrawise.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
```

**Comment by mcm1957** [comment]
@SentiQ 

Wäre schön wenn du den Adapter in die Repositories aufnehmen lassen würdest.
Derzeit ist er ja - wenn ich das richtig sehe - hier: https://github.com/SentiQ/ioBroker.hydrawise verfügbar.

Ev. würde es Sinn machen, den Adapter vom Fork Origin abzukpoppeln wenn ein backport nicht geplant ist. Das geht in Github via import Funktion. In jedem Fall solltest du im aktiven Repository issues freischalten.

Bezüglich Aufnahme in die Repos findest du Infos hier:

https://github.com/ioBroker/ioBroker.repositories#requirements-for-adapter-to-get-added-to-the-latest-repository

**Comment by pacco81** [comment]
@SentiQ
Vielen Dank für die turboschnelle Umsetzung ! 
Wäre es viel Aufwand auch diese "time" Datenpunkte in ein lesbares Datum zu konvertieren: 

hydrawise.0.customer.controllers.xxx.last_contact
hydrawise.0.schedule.time

Besten Dank !

**Comment by SentiQ** [comment]
@pacco81 "time" sind die Sekunden bis zum nächsten Start - unter "timestr" lesbar berechnet

**Comment by SentiQ** [comment]
Es können jetzt auch Issues erstellt werden.

Bezüglich Aufnahme in Repo bin ich vorab in Klärung mit @aDabbelju wie wir allgemein weiter verfahren und gehe es danach an.

**Comment by MichHan** [comment]
Had one of the first versions installed that crashed continously.
Now installed version 0.0.14 with no problem. All values are there and correct.
Will report on stability here.
Michael

**Comment by aDabbelju** [comment]
> @SentiQ @aDabbelju
> 
> Wäre schön wenn du/ihr den Adapter in die Repositories aufnehmen lassen würdest. (*) Derzeit ist er ja - wenn ich das richtig sehe - hier: https://github.com/SentiQ/ioBroker.hydrawise verfügbar.
> 
> Ev. würde es Sinn machen, den Adapter vom Fork Origin abzukpoppeln wenn ein backport nicht geplant ist. Das geht in Github via import Funktion. Oder durch löschen des nicht mehr aktuellen Repos (welches das immer ist). In jedem Fall sollte im aktiven Repository issues freigeschaltet sein..
> 
> Bezüglich Aufnahme in die Repos findest du Infos hier:
> 
> https://github.com/ioBroker/ioBroker.repositories#requirements-for-adapter-to-get-added-to-the-latest-repository
> 
> McM1957
> 
> (*) auf Grund eines "kleineren" Rückstaus und Kapazitätsproblemen beim Review kann dieser Prozess derzeit einige Wochen dauern. Sorry.

@SentiQ hat damals mein Repo geforked und weiterentwickelt. Sein Repo würden wir gerne in das Repository für die Adapter aufnehmen lassen. Wäre das Löschen meines Repos der einfachste Weg?

**Comment by SentiQ** [comment]
@aDabbelju habe mein Repo bereits per Import neu erzeugt und nehme noch paar Einstellungen vor. Ich gebe dir dann Bescheid und du kannst deins löschen.

**Comment by mcm1957** [comment]
So wie ich das sehe zur Zeit keine Fragen offen. Ihr redet eh miteinadner udn stimmt euch ab.
Wenn doch Info / Hilfe benötigt wird, bitte melden.
McM1957

**Comment by mbhomie007** [comment]
@SentiQ
Sorry, das ich Nachfrage...
Wie ist der Stand um die Aufnahme fürs latest Repo?

**Comment by mcm1957** [comment]
Siehe https://github.com/ioBroker/AdapterRequests/issues/195

**Comment by SentiQ** [comment]
@mbhomie007 bin aktuell noch nicht dazu gekommen die Anpassungen nach dem Review machen

**Comment by mcm1957** [comment]
@SentiQ 
Danke f.d. Info.
Hätte aber (bisher) auch nichts geändert da Apollon77 novh nicht Zeit für Reviews gefunden hat.
Aber wir arbeiten an einer Lösung - mehr möchte ich heute nicht versprechen.

**Comment by SentiQ** [comment]
Test-Thread: https://forum.iobroker.net/topic/67751/test-adapter-hydrawise

**Comment by mcm1957** [comment]
released
