### ISSUE TITLE
Flic Button 

### ISSUE THREAD

**Issue by pockeras** [ioBroker/AdapterRequests#196]
Ein Flic Button Adapter wäre sehr geil 🤪😊

Flic Wireless All-in-one Smart button - Schwarz https://www.amazon.de/dp/B06Y63VZT7/ref=cm_sw_r_cp_api_i_C2aUCb1QDAY06

Mit freundlichen Grüßen

**Comment by DutchmanNL** [comment]
"Verbindet sich mit Ihrem Gerät über Bluetooth Low-Energy"

Kann man den nicht mit Bluetooth Adapter nutzen?

**Comment by pockeras** [comment]
Kein Plan wie das damit funktioniert 🤷‍♂️

**Comment by DutchmanNL** [comment]
> Kein Plan wie das damit funktioniert 🤷‍♂️

mal im forum geschaut :)

**Comment by steckenpferd** [comment]
Doppelt: https://github.com/ioBroker/AdapterRequests/issues/70
