### ISSUE TITLE
DigitalStrom

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/AdapterRequests#2]
https://forum.iobroker.net/viewtopic.php?f=8&t=4423

There may be some libraries available, but all maybe not actively maintained:
https://www.npmjs.com/package/ds-wrapper
https://www.npmjs.com/package/mqtt-dss-bridge
https://www.npmjs.com/package/homebridge-digitalstrom (für Anleihen)

API Specs/Infos:
https://www.digitalstrom.org/allianz/entwickler/developer-resources/system-apis/

Migrated from Trello with 0 votes

**Comment by Apollon77** [comment]
Homebridge modules exist: homebridge-digitalstrom as example.

Please check if the new ioBroker.ham Adapter can help here: see https://forum.iobroker.net/viewtopic.php?f=36&t=14972

**Comment by DutchmanNL** [comment]
i buiding several energy like adapters currently so looking for possible combinations of code.
No update here or big votes is it worth to spend time currently or focus on others ;)

**Comment by Apollon77** [comment]
Ich habe denke ich die Tage etwas testbares. Poste dann hier den Forum Link zum Test Thread. Bitte gebt mir hier mal kurz nen Überblick über Eure Systeme ... also was an Komponenten sind so dran in welchen zahlen?

**Comment by Strobelix80** [comment]
Vielen Dank schon mal.

Ich nutze bis jetzt (wird ständig erweitert):
1x dSS20 mit 3 Filtern DSF20
5x dS Meter dSM12
10x GE-TKM210
1x GE-KM200
2x SW-TKM200
1x GE-UMV200

**Comment by 123Trunks** [comment]
<img width="2088" alt="Bildschirmfoto 2020-01-08 um 12 37 55" src="https://user-images.githubusercontent.com/37037996/71975248-b58e7100-3213-11ea-8ff5-01a94e75649d.png">

**Comment by Farmer-cb** [comment]
ich nutze bis jetzt
1 x dss11
1 x dss IP
3 x dsf20
7 x dsm12
1 x enocean Gateway
1 x HUE Bridge
9 x GE-KL200
3 x SW-ZWS200
15 x GE-TKM210
4 x BL-KM200
4 x dS-iSens200
2 x SW-TKM200
1 x SW-AKM210
2 x Thermokon EnOcean heating valve actuator (A5-20-01)
2 x Thermokon EnOcean Temperature sensor (A5-02-05)
6 x EnOcean window handle (F6-10-00)
3 x EnOcean single contact (D5-00-01)
6 x EnOcean Smoke detector (F6-05-02)
1 x EnOcean Key card switch (F6-04-C0)
1 x GN-TKM210
1 x GN-KM200
9 x GR-KL200
2 x SW-TKM210
2 x SW-UMR200

ca angaben

**Comment by BrunoBauman** [comment]
Moin, 
bin zwar nicht so oft hier, möchte das aber gern ünterstützen:

So in etwa:
1x dss20
1x dss11
1x dsm11
3x dsm12
1x SW UMR200
3x SW-AKM200
2x SDS200-CS
12x GR-KL200
11x GE-KM200
1x SW-ZWS200
1x SW-SSL200-FS
Enocean Helligkeit A5-06-01 @P44
Enocean Temp A5-04-02 @P44
Enodean Schalter F6-02-FF @P44
Enoean Fenstergriff F6-10-00 @P44
Xiaomi Aqara Fenstersensor Magnetkontakt @deconz
Xiaomi Aqara Bewegungsmelder @deconz
Xiaomi Aqara Temperatur/RF/Druck @deconz

**Comment by Apollon77** [comment]
Weiter geht es --> https://forum.iobroker.net/topic/28907/test-adapter-digitalstrom-0-2-x

**Comment by Apollon77** [comment]
0.3.1 on GitHub ... please monitor the forum post!

**Comment by Apollon77** [comment]
Released 0.4.4 in latest repo
