### ISSUE TITLE
KLF-200 zur Ansteuerung des neuen Velux-Interfaces

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/AdapterRequests#20]
http://forum.iobroker.net/viewtopic.php?f=20&t=7922

Der Adapter steuert das KLF-200 Interface an und kann mittels im Adapter hinterlegter Szenen z.B. die Fenster öffnen oder schließen.

Scheinbar teilweise in Arbeit: https://github.com/MiSchroe/ioBroker.klf200/tree/initialdev

Migrated from Trello with 0 votes

**Comment by Apollon77** [comment]
Homebridge modules exist: homebridge-zway-velux as example.

Please check if the new ioBroker.ham Adapter can help here: see https://forum.iobroker.net/viewtopic.php?f=36&t=14972

**Comment by MiSchroe** [comment]
Hi, work on the KLF-200 interface adapter has finished with a first release. You can find it at https://github.com/MiSchroe/ioBroker.klf200/releases/latest.
