### ISSUE TITLE
Dimstal Klimaanlage

### ISSUE THREAD

**Issue by topperharley81** [ioBroker/AdapterRequests#201]
Hallo, ich würde mich über einen Adapter für folgende Klimaanlage freuen:

A++/A++ ECO Smart Inverter WiFi WLAN Golden-Fin 12000 BTU 3,5 kW Split Klimaanlage mit Wärmepumpe INVERTER Klimagerät und Heizung SmartHome https://www.amazon.de/dp/B07CVLLH4W/ref=cm_sw_r_cp_apa_i_GDRWCb35RP1FN

**Comment by Schoppi01** [comment]
Hallo, ich habe auch eine Dimstal Klimaanlage und schließe mich dem Wunsch von  topperharley81 an.
Wir haben aber die etwas kleinere Version. Das WiFi Modul ist aber das gleiche.
Gruß

Schoppi

**Comment by derBonsaii** [comment]
+1
Spiele auch mit dem Gedanken, diese Klimaanlage zu holen ... aber wäre echt froh, wenn es dazu einen Adapter geben würde.

Was würde benötigt werden, um den Adapter zu erstellen?
Reicht das mitschneiden des WLAN-Verkehrs?

**Comment by hieblmedia** [comment]
+1

**Comment by Apollon77** [comment]
Plus 1 posts sind falsch!! Bitte oben das „Daumen hoch“ im ersten Beitrag nutzen sonst sieht es niemand in den Übersichten!!

**Comment by Freerider0815** [comment]
Guten Abend,

bin nun ebenfalls Besitzer einer Dimstal Klimaanlage. Jedoch ist das Gerät ohne einbindung in den ioBroker nur dürftig nutzbar:-( 
Wie kann man bei der Entwicklung eines Adapters denn unterstützend tätig werden?

Grüße Martin

**Comment by jogibear9988** [comment]
Geht da nicht auch die Midea App? Dann sollte das vlt. helfen: https://pypi.org/project/midea/ als Grundlage für eine API

Ich habe auch eine, komme aber z.Z. nicht dazu einen Adapter zu schreiben, helfe aber gerne mit

**Comment by hieblmedia** [comment]
> Geht da nicht auch die Midea App? Dann sollte das vlt. helfen: https://pypi.org/project/midea/ als Grundlage für eine API
> 
> Ich habe auch eine, komme aber z.Z. nicht dazu einen Adapter zu schreiben, helfe aber gerne mit

Ja genau. Midea Air ist sogar die offizielle Android App bei den Geräten. Zumindest ist es bei meiner so.

**Comment by Nopaxa** [comment]
Bei meiner Dimstal sollte ich die APP "NetHome Plus" installieren und darüber die Verbindung herstellen.

**Comment by mcchickents** [comment]
Guten Abend,

würde mich ebenfalls über einen Adapter freuen. Leider kann ich auf IT Basis wenig dazu beitragen. 

Gruß Julian

**Comment by regas123** [comment]
Ich habe mich beholfen das ich die befehle zur Klima übern broadlink rm pro+ sende via IR ist natürlich umständlich und man hat keine rückmeldung zum aktuellen status aber es geht erstmal aber würde mich natürlich auch über ein Adapter freuen für das es über Wlan klappt

**Comment by audiraudi** [comment]
derzeit steuere ich meine noch mit einem MP3 Gong über Homematic dieser Steht in der nähe der Alexa und gibt den Befehl zur Alexa die einen Skill für Nethome hat .... umständlich ... geht aber :-) Vielleicht ist es durch den Skill auch einfacher einen Adapter zu bauen ....

**Comment by TA2k** [comment]
Besteht immer noch interesse? Kann mir jemand Zugangsdaten für die offizielle App bereistellen?
via forum pn
https://forum.iobroker.net/user/tombox

**Comment by Schoppi01** [comment]
Hallo Tombox,

prinzipiell schon, bin zwar auch obenhab mit meiner Visualisierung
umgestiegen, jedoch an der einen oder anderen Stelle nicht so ganz
glücklich. Z.T. ist die Dokumentation nicht besonders. Da gibt es mehr und
für nicht Profis einfachere Beschreibungen and Work arounds.

Auf meinem Handy läuft zur Steuerung der Dimstal Klimaanlage "NetHome Plus"

Welche Daten benötigst Du?.

Habe den Punkt persönliche PN im Forum (Linf oben) nicht gefunden.


Mit freundlichen Grüßen


Lothar Schopmann

Mobile: +49 15205738313
Mail: L.Schopmann@gmail.com


Am So., 26. Jan. 2020 um 23:25 Uhr schrieb TA2k <notifications@github.com>:

**Comment by TA2k** [comment]
Ich denke ich werde ein midea adapter bauen da unter der marke die ganzen geräte zusammenkommen.
ich benötige die zugangsdaten zur app.
https://forum.iobroker.net/user/tombox
hast du rechts drei punkte und dann kann man ein gespräch beginnen.

**Comment by mcchickents** [comment]
Hi hier hat mal wer mit einem Midea adapter angefangen https://forum.iobroker.net/topic/8449/wirds-ein-midea-adapter-geben/5

**Comment by TA2k** [comment]
Ja es gibt schon etwas für hass und openhab. Das sind gut Vorlagen aber es dauert ein wenig länger. Vielleicht am Sonntag.

**Comment by mcchickents** [comment]
Kein Problem bin sehr gespannt.

**Comment by Schoppi01** [comment]
Hallo TA2K,

da ich aktuell eher i openhab unterwegs bin würde mich das "es gibt schon
was für openhab" brennend interessieren

Mit freundlichen Grüßen


Lothar Schopmann

Lönsweg 13
59590 Geseke
Phone: +49 2942 7995586
Mobile: +49 15205738313
Mail: L.Schopmann@gmail.com


Am Mi., 29. Jan. 2020 um 11:45 Uhr schrieb mcchickents <
notifications@github.com>:

**Comment by TA2k** [comment]
https://github.com/bricky/midea-openhab

**Comment by TA2k** [comment]
Ich habe mal angefangen, aber es ist relativ kompliziert da anscheined Infrarot byte codes array versendet werden.
https://github.com/TA2k/ioBroker.midea
Bisher werden nur die allgemeinen Daten der Anlage angezeigt.

Ich bin für Hilfe offen den python code zu transferieren
https://github.com/bricky/midea-openhab/blob/master/midea/packet_builder.py
https://github.com/NeoAcheron/midea-ac-py/blob/master/midea/command.py

**Comment by mcchickents** [comment]
Hi hab ihn gerade mal im Iobroker installiert und mich erfolgreich eingeloggt. Das funktioniert auch einwandfrei:-)

**Comment by TA2k** [comment]
Ist bei dir  bei homeGroupId ein Wert vergeben?

**Comment by mcchickents** [comment]
Hi nein ist leer

**Comment by hieblmedia** [comment]
Hab ihn auch mal installiert. 
Bei mir sieht es so aus, falls das hilft.
https://prnt.sc/qx0z6a

**Comment by TA2k** [comment]
@hieblmedia bittw lösche dein Screenshot und melde dich mal im Forum per pn

**Comment by mcchickents** [comment]
Hi und gibt es schon neue Erkenntnisse?

**Comment by TA2k** [comment]
Ja homegroupid kommt wahrscheinlich bei neu verknüpften Anlagen. Ist aber nicht so wichtig erstmal. Ich versuche nächsten Sonntag den Python Code um Befehle zu senden zu übersetzten.

**Comment by DerChecker** [comment]
Lese hier interessiert mit. Ist sicher auch etwas für nen Comfee Luftentfeuchter mit WLAN Steuerung per nethome plus

**Comment by desprueht** [comment]
Ich installiere den Adapter gleich auch mal, habe meine Dimstal Klimaanlage dieses Wochenende in Betrieb genommen und bin ebenfalls gespannt und würde mich sehr freuen!

**Comment by MBH88** [comment]
Hallo zusammen, ich lese hier auch sehr interessiert mit. Habe den adapter auch gleich installiert und funktioniert soweit auch alles, schonmal vielen Dank an TA2k für das erstellen !! Würde mich wahnsinnig freuen wenn du es schaffst die Anlagen auch steuern zu können. Da ich blutiger Anfänger bin, kann ich leider recht wenig dazu beitragen...

**Comment by MBH88** [comment]
Hi, ich wollte mal vorsichitig nachfragen, ob es hier schon fortschritte gibt ? Ein Ein, btw. Aus-Schalten wäre schon wahnsinnig hilfreich.

**Comment by TA2k** [comment]
Hi, es ist gerade wenig Zeit übrig und ich muss noch was im IoT Adapter fixen dann ist der adapter wieder dran.

**Comment by MBH88** [comment]
Hi, Danke für die schnelle Rückmeldung

**Comment by bennatzen** [comment]
Habe eine Comfee Klima mit NetHome und würde mich über einen Adapter freuen.

**Comment by mcchickents** [comment]
Ein bzw Ausschalten wäre super geil^^

**Comment by huettmasterTB** [comment]
fänd ich auch top.Habe den Adapter schon mal installiert. Würde mich riesig freuen, wenn man demnächst auch was zu steuern gehen würde.

**Comment by jogibear9988** [comment]
@TA2k machst du noch was am Midea Adapter oder soll ich mal schaun? Hab selber ne Anlage und würd probieren da was zu machen falls du da nicht dran bist.

P.S.:

Hättest du nicht Lust deine Adapter in die community adapters zu bringen, siehe : https://github.com/iobroker-community-adapters

**Comment by TA2k** [comment]
Wie gesagt mir fehlt zur zeit die komplexe Entschlüsselung in javascript zu übertragen.
Ich glaube der Aufwand und nutzen steht nicht im Verhältniss du kannst ein PR stellen oder ich kann dir push rechte geben.

Hier ist der python code der transferiert werden muss
https://github.com/bricky/midea-openhab/blob/master/midea/packet_builder.py
https://github.com/NeoAcheron/midea-ac-py/blob/master/midea/command.py

**Comment by jogibear9988** [comment]
@TA2k hab die python api mal konvertiert:
https://github.com/TA2k/ioBroker.midea/pull/5
hab sie aber 1zu1 übernommen...

wo muss ich denn ein command nun hinsenden? habs mir in python noch gar nicht angeschaut. oder kannst du es mir sagen.

push berechtigung brauch ich nicht. dachte nur an die community, da kann der adapter weiter gepflegt werden, falls man mal aus iobroker ausscheidet oder keine zeit mehr dafür hat

**Comment by TA2k** [comment]
Ich habe mal blind das senden eines commandos hinzugefügt. Ich habe es selber nicht getestet aber ich denke mal das ist eine gute basis mit der du weiter entwickeln kannst die order encode und encrypted und dann in hex umgewandelt
encrypted hatte ich schon du musst nur noch das encoding übernehmen und in hex umwandeln
hier ein beispiel  wie es in python aussieht
https://github.com/NeoAcheron/midea-ac-py/blob/master/midea/cloud.py

**Comment by jogibear9988** [comment]
Okay, sieht soweit gut aus....
Einschalten geht bei mir nun...
Das aislesen der Werte muss noch rein, dann ists ja schon fertig

**Comment by jogibear9988** [comment]
Was wir noch brauchen, einen Reconnect bei einer ungültigen sitzung:
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/364896/81466467-36657580-91d2-11ea-8380-764a33c68e7d.png">

dies passiert immer wenn man z.B. mit der App Online war.
Dann schlägt das kommando nämlich fehl.

**Comment by jogibear9988** [comment]
hab den response handler auch noch von python in JS übernommen.
zu mehr komme ich heute nicht.
@TA2k vlt. kannst du den ja einbauen?

**Comment by TA2k** [comment]
habe einen einmaligen relogin eingebaut


habe eingebaut das der response in status states geschrieben wird
es muss aber noch die encode und decode methode geschrieben sonst gibt probleme bei negativen werten oder werte über 128
alles ungetestet da ich keine anlage besitze.

**Comment by jogibear9988** [comment]
@TA2k die stati funktionieren soweit....
aber wir aktualisieren nur beim senden eines commands...

**Comment by jogibear9988** [comment]
ich schließe diesen issue nun mal...

**Comment by TA2k** [comment]
https://forum.iobroker.net/topic/33198/test-adapter-midea-dimstal-klimaanlagen-v0-0-x

**Comment by MBH88** [comment]
Hi, auch wenn die issue geschlossen wurde, wollt ich noch Feedback geben. Ich sehe von allen Anlagen den Status aber kann die Anlagen darüber nicht steuern. Auch unter dem Reiter Control sind zwar die Befehle aufgelistet, aber alle als „State“ wenn ich das richtig verstehe müssten das doch „Button“ sein um es anzusteuern oder? 
Grüße

**Comment by jogibear9988** [comment]
Also bei mir geht es zu steuern, also an und aus.
Aber jede statusabfrage schaltet auch ein.

Das Problem ist aus jeden falls das zur statusabfrage auch ein kommando gesendet wird was schaltet. sehe in der python lib aber auch nicht wie man das anderst machen könnte. wir müssen auf jeden fall immer alle kommand states eintragen, aber dann ist eine gleichzeitige nutzung der app nicht möglich, da deren steuerungen durch die statusabfrage wieder überschrieben werden.

**Comment by jogibear9988** [comment]
P.S. ich würde vorschlagen weiteres in issues im adapter zu pflegen.
