### ISSUE TITLE
Forecast solar radiation

### ISSUE THREAD

**Issue by ggraziotti** [ioBroker/AdapterRequests#203]
I'have a photovoltaic system.

Is existing an adapter for radiation forecast to use for scenes ?

**Comment by Apollon77** [comment]
we should have https://github.com/Pix---/ioBroker.solarwetter ... paid but existing ...

**Comment by ggraziotti** [comment]
But only Germany location ?

**Comment by Apollon77** [comment]
As it seems ... IF you need more/deifferent then please describe more exact in yur first post what you need as a new adapter. For now it is just a question ;-))

**Comment by ggraziotti** [comment]
I found local data for Italy locations, meteo/energy, via FTP.

It's possible modify adapter to get file via FTP ?

**Comment by DutchmanNL** [comment]
> I found local data for Italy locations, meteo/energy, via FTP.
> 
> It's possible modify adapter https://github.com/Pix---/ioBroker.solarwetter, to get meteo forecast on .CSV file, via FTP ?

do you have an example of that file ?

**Comment by ggraziotti** [comment]
I asked an example file, but now I haven't.

But they say me if I want a specific file an format.

So may be better that u give me a possible file that I give to forecast
provider.

They said to me that the data will be available via FTP.

They will be give following FORECAST and HISTORICAL data:


- Radiation levels: GHI, DNI;

- Temperature °C;

- Rain/snow mm;

- Umidity;

- Wind Velocity at 10 mt;





Il lun 24 giu 2019, 23:24 Dutchman <notifications@github.com> ha scritto:

**Comment by DutchmanNL** [comment]
yea but to build an extension in the adapter we need to understand the provide format :)
