### ISSUE TITLE
universelle/ Hersteller unabhängige Rolladen Steuerung/ automatik 

### ISSUE THREAD

**Issue by dos1973** [ioBroker/AdapterRequests#206]
Hallo,
jeder der Heimautomatisierung erreichen will, möchte früher oder später Rolladen steuern.

Eine Suche im Forum ergibt über 500 Einträge mit individuellen Scripten für individuelle Lösungen, welche allerdings nie auf die eigenen Bedürfnisse passen und immer angepasst werden müssen.

Eine eigene Steuerung/ Logik ist ohne Script Erfahrung schwer umzusetzen/ anzupassen. 
Ich suche bereits länger ;-) Die Rolladen manuell steuern hoch/ runter geht recht einfach ;-)

Ich wünsche mir einen Adapter der die gesamte Rolladen Steuerung übernimmt.
- wähbar mittels Automatik
- verschiedene Automatiken für verschiedene Rolladen
- Aussetzen der Automatik
- flexibel nach Atsrozeiten
- Auswahl der Rolladen welche, wann wie fahren sollen
- Darstellung der nächsten geplanten Fahrzeiten (Zeit hoch/runter) im Vis
- manuelle Modifikation der Fahrzeiten (+/-30 min etc)
Erweiterung:
ergänzen von Wind/ Sonne /Regensensoren für individuelle Beschattungen etc. welche aussehalb der Regeln eingreifen.

mir ist klar dass es dafür bereits diverse Scripte/ Schnipsel  und Lösungen gibt, aber eben keinen Adapter der diese sinnvolle Anforderung sauber löst. 

würde mich freuen, wenn sich ein Entwickler dieseser Sache annimmt. 

Danke

**Comment by simatec** [comment]
Schau mal hier ...
https://forum.iobroker.net/topic/22405/aufruf-neuer-adapter-iobroker-shuttercontrol

**Comment by dos1973** [comment]
;-) 
gibts ja nicht... aber freut mich echt. cool & Danke
dann kann das hier geschlossen werden.
