### ISSUE TITLE
[CLOSED] GPS Tracker - Kippy Vita (V-SIM) oder TRACCAR

### ISSUE THREAD

**Issue by JensReitemeyer** [ioBroker/AdapterRequests#208]
Hey!

Es gibt derzeit von Vodafone unterstützte IoT GPS Tracker, die eine integrierte V-SIM haben. Hierunter gibt es unter anderem einen "Kippy Vita" Tracker, mit dem (eigentlich Hunde / Katzen draußen getrackt werden. Es gibt eine App und das Standard Aktualisierungsintervall liegt bei 15min, aber es gibt auch einen LIVE Modus, der sich nach einer gewissen Zeit wieder deaktivert, wenn er nicht genutzt wird...
Es wäre doch auch super, wenn wir dafür einen Adapter hätten! Ich persönlich zweckentfremde den Tracker um meinen Lieben wissen zu lassen wo ich gerade unterwegs bin (SPORT!)
Akkulebensdauer soll bei ca 6 Tagen liegen. 

Infos gibt es hier:
https://eshop.v.vodafone.com/de/v-pet
Preis wird sich, zB wie bei Preisbörse24 bei 20 Euro einpendeln (2,99 Kosten/Monat)
Es gibt aber auch Garmin Tracker wie zB. V-BAG

Alternativ (und auch für andere Mobiltelefone oder Tracker, wie einem TK-905 zB) könnte man drüber nachdenken, einen Traccar-Server-Adapter zu erstellen. Der Server (RPi zB) sammelt alle Daten ein und könnte die an den ioB übergeben!

Infos gibt es hier:
https://www.traccar.org/

https://www.banggood.com/de/TKSTAR-TK905-GPS-Tracker-2G-GSM-GPRS-Locator-Voice-Monitor-5000mAh-with-Powerful-Magnet-Free-Web-APP-p-1111950.html

Viele Grüße,
Dobbs

**Comment by FChristian** [comment]
Side-Info: den Kippy Vita gibt es im Moment zum Preis von 10€ incl. 1 Jahr Service, vielleicht kann das bei der Entwicklung unterstützen? https://www.mydealz.de/deals/kippy-vita-gps-hundetracker-vodafone-v-sim-und-12-monate-datenpaket-inklusive-von-vodafone-tracker-fur-alles-mogliche-mit-appverfolgung-1386412

**Comment by JensReitemeyer** [comment]
Genau da hab ich ihn auch her! Top!

**Comment by NemoN** [comment]
Eine offizielle bzw. dokumentierte API für das Backend (auf das die Kippy App zugreift) scheint es nicht zu geben. Bei Gelegenheit schau ich mir das Protokoll an. Allerdings habe ich keinen Plan von ioBroker Adaptern ;-)

**Comment by nickes** [comment]
Gibt es Informationen bzgl. der GPIOs auf dem Board (JTAG?)? Würde mich interessieren, ob es dadurch möglich ist an weitere Informationen zu kommen. Welche IDE für den NXP-Chip benötigt wird ist mir leider auch unklar. Bin für weitere Informationen dankbar!

**Comment by NemoN** [comment]
Das Datenblatt ist ja frei verfügbar: https://www.nxp.com/docs/en/data-sheet/LPC11U3X.pdf 
Leider habe ich nicht das nötige Equipment (Mini Tastköpfe) um mal durchzumessen welche Pins auf welche Testpunkte führen...

**Comment by hostservice** [comment]
Hallo,

hat hier schon jemand was gemacht?
Also mit dem entsprechenden Json body kann ich mich unter https://prod.kippyapi.eu/login.php einlogen.

**Comment by mcm1957** [comment]
Repo: https://github.com/arteck/ioBroker.traccar

**Comment by JensReitemeyer** [comment]
Thx MCM!
Ich selber nutze seit anbeginn den traccar adapter. Funktioniert super und alles läuft darüber. Danke für die Erinnerung!

**Comment by JensReitemeyer** [comment]
#CLOSED

**Comment by JensReitemeyer** [comment]
Thx MCM!
Ich selber nutze seit anbeginn den traccar adapter. Funktioniert super und alles läuft darüber. Danke für die Erinnerung!
