### ISSUE TITLE
Meteolarm - Weather Alarm for Europe

### ISSUE THREAD

**Issue by jack-blackson** [ioBroker/AdapterRequests#209]
Hello!

I found this website some weeks ago. It provides weather alarms for each region in Europe, for storm, snow, rain and other issues, for free via RSS feeds.

http://meteoalarm.eu/

I created a setup with parser and a script to get the text, type and level and it works great. I think this could be very useful as an adapter, e.g. for people in Europe, as we can't use the DWD adapter.

**Comment by jack-blackson** [comment]
I try to create the adapter myself - can you please assign it to me?

**Comment by Apollon77** [comment]
II invited you, accept and you can assign yourself. If you need support please post in Forum Developer area and we will all support the best we can. There is also a Telegram Group ...

**Comment by jack-blackson** [comment]
Adapter is created and in stable release
