### ISSUE TITLE
Custom Alexa Skill

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/AdapterRequests#21]
Migrated from Trello with 28 votes!

**Comment by ruhr70** [comment]
Zweiter Custom Skill für die Idee notwendig?

Alexa als ASR Engine verwenden um Texte zur weiteren Verarbeitung an ioBroker zu schicken.

"Alexa, xyz kann im Schlafzimmer gelüftet werden"

Analog zu "IFTTT trigger das und das"

Bei IFTTT ist das Wort für Custom Skill "trigger. Welche guten und freien Wörter gibt es dann für ioBroker? Kann es sein, dass da ein Wettlauf im Gange ist, wie bei der Domain Registrierung?

"Alexa, Hausmeister schalte den Fernseher ein".


Die weitere Verarbeitung kann dann per eigener KI erfolgen (Javascript, text2command).

**Comment by Apollon77** [comment]
Es gibt nur einen Smarthome skill. Das ist aktuell kein custom skill. 

Ja die Hauptfarbe ist das triggerwort ;-) die Diskussion gabs schonmal irgendwann im Forum ;-)

**Comment by AlCalzone** [comment]
"Jarvis"? :D

**Comment by Apollon77** [comment]
If not already taken we should „reserve“ it very fast ;-)

**Comment by Apollon77** [comment]
see https://forum.iobroker.net/viewtopic.php?f=36&t=13857

**Comment by GermanBluefox** [comment]
The trigger word must not be unique.

2018-04-30 22:39 GMT+02:00 Ingo Fischer <notifications@github.com>:

**Comment by Apollon77** [comment]
More Tester-Feedback needed!!

**Comment by Apollon77** [comment]
In Amazon Review ...

**Comment by saepfle** [comment]
Kann der Request geschlossen werden?
https://www.amazon.de/ioBroker-Custom/dp/B01MQL6Z1N

**Comment by Apollon77** [comment]
Yes https://forum.iobroker.net/viewtopic.php?f=37&t=17452
