### ISSUE TITLE
Blue Iris Adapter

### ISSUE THREAD

**Issue by epcos71** [ioBroker/AdapterRequests#211]
Integration der Videoüberwachungs-Software BlueIris. Damit könnte man auf Events einer Kamera reagieren.

Software Info: http://blueirissoftware.com/

**Comment by Apollon77** [comment]
SInd APIs o.ä. vorhanden? Andere Libraries for nodejs oder andere Programiersprachen verfürbar?

**Comment by epcos71** [comment]
Aktuell gibt es ein JSON interface. Mehr weiss ich leider auch nicht.

**Comment by Alveran81** [comment]
Habe auch Blue Iris im Einsatz. Geniale Software. Zurzeit lässt sich leider nur das Kamerabild in der VIS anzeigen. Würde gerne die Alarmprofile / Homemode darüber steuern. Es gibt ein JSON Interface. Habe die Vollversion im Einsatz und könnte bei der Entwicklung unterstützen.

**Comment by hawi1981** [comment]
Habe Blue Iris auch im Einsatz und habe mittels MQTT bei Bewegung ein Input bei IoBroker.

**Comment by epcos71** [comment]
> Habe Blue Iris auch im Einsatz und habe mittels MQTT bei Bewegung ein Input bei IoBroker.

Bin jetzt wahrscheinlich offtopic, aber kannst Du mir verraten, wie das konfiguriert ist? Ich bin bei MQTT mächtig planlos und habe es nicht hinbkommen....
