### ISSUE TITLE
windy.com

### ISSUE THREAD

**Issue by sigi2345** [ioBroker/AdapterRequests#215]
Hallo, kann wer daraus einen Adapter machen?
API vorhanden. Sehr gute Wetterdaten und wirklich gute Grafik.

https://www.windy.com

**Comment by Apollon77** [comment]
See: https://www.youtube.com/watch?v=MwkLAvADDe8&feature=youtu.be

**Comment by DutchmanNL** [comment]
ich schaue es mir mal en wen es wirklich ne einfache JSON ist dan kan man da schnell was machen die Seite sah sehr gut aus.
Muss aber sagen wegen prio ... wir haben bereits 2 gut funtionierende wetter adapter (DasWetter und WeatherUnderground)

**Comment by sigi2345** [comment]
>prio ... wir haben bereits 2 gut funtionierende wetter adapter (DasWetter und WeatherUnderground)

Ja das stimmt, mir geht es um Blitze und Regenradar

**Comment by Elektronikwelt** [comment]
Für mich wären auch die Blitze interessant.

**Comment by DutchmanNL** [comment]
hmm hier die API docu fuer mich zu hochgegriffen :/ 

https://leafletjs.com/reference-1.5.0.html#map-methods-for-layers-and-controls

**Comment by dwm66** [comment]
Auf der linken Seite von Windy kann man doch im Menü "Widget einbetten" auswählen, und das geht natürlich nicht nur mit der "Standard" Windkonfiguration, sondern auch mit den Blitzen und Wetterradar. Hab ich bei mir in der Visualisierung so gemacht, klappt einwandfrei. Einfach als iframe einbetten.
