### ISSUE TITLE
Car Connect der Telekom

### ISSUE THREAD

**Issue by yxcon** [ioBroker/AdapterRequests#217]
Hallo,
ich suche ein Adapter für CarConnect von der Telekom. Man hat da zugangsdaten womit man auf dem Account zugreifen kann.  Hat da jemand eine idee?

**Comment by Apollon77** [comment]
mehr Details? Links? API Infos? Irgendwas?

**Comment by rbrunka** [comment]
Mich würde das Thema auch interessieren. Würde ich selbst schreiben, aber leider die Zeit fehlt...

API: https://docs.moj.io/#!/document/view/index

**Comment by Apollon77** [comment]
Schade ... Die Herausforderungen bei der Adapter-Entwicklung ist immer Zeit und "Zugang" und viele Adapter kommen zustande weil der Entwickler es selbst will/braucht. Freie entwickler schauen sich Requests nach den Stimmen "Thumbs up" im ersten post an , was hier noch quasi 0 ist ... 
Naja vllt findest Du ggf vor einem anderen Entwickler ja noch Zeit ;-)

**Comment by Webranger2** [comment]
Würde mich aber auch interessieren.
Der Adapter würde sicherlich einiges an Daten Liefern:

- Tankinhalt
- Batteriestatus
- OBD Fehlermeldung vom Auto
- Fremdeinwirkungen am Auto
- Gefahrene Strecken
- ........

Das ganze Fahrzeug unabhängig, das Fahrzeug muss nur einen OBD II Anschluss haben, was alle KFZ seit 2002 hab.

Den Car Connect Stecker gibt es für 9,99 im Monat von der Telekom und man hat zusätzlich noch wlan im Auto für Amazon, Soundcloud oder sonst was.

Ich würde mich sehr freuen wenn sich jemand der Geschichte annimmt.

Gruss

**Comment by Gandinator** [comment]
Auch wenn das Thema 2 Jahre alt ist... die Magenta Hölle hat den Service meines Wissens eingestellt

**Comment by UncleSamSwiss** [comment]
> Auch wenn das Thema 2 Jahre alt ist... die Magenta Hölle hat den Service meines Wissens eingestellt

Zumindest findet sich auf der Website nicht mehr viel... Die CarConnect-Seite wird auf die IoT Seite weitergeleitet und dort steht nichts mehr zum Produkt CarConnect:
https://www.telekom.de/smarte-produkte/iot?wt_mc=alias_301_unterwegs/carconnect

@Apollon77, was meinst du, schliessen wir diesen Request?
