### ISSUE TITLE
Vis Burger Menü

### ISSUE THREAD

**Issue by dos1973** [ioBroker/AdapterRequests#221]
Hallo,

VIS ist Klasse aber ich wünsche mir ein „Burger“ Menü, o.ä. mit Kaskade... (die 3 kleinen Striche die dann ein Menü darstellen) um darin weiter verschachteln zu können.

Sobald ein Vis komplexer mit vielen Unterseiten entsteht ist eine ordentliche Menüführung nicht mehr möglich.

Ein Menü wie es die iobroker Forums Seite bietet wäre Klasse (von links sliden)

**Comment by Bluelightcrew** [comment]
Ja, das hätte ich auch gerne

**Comment by Apollon77** [comment]
Na dann nutze „Daumen hich“ im ersten post des issues. So zählen wir “ich auch”

**Comment by darkiop** [comment]
Schaut euch mal

https://github.com/Scrounger/ioBroker.vis-materialdesign

an.

**Comment by mrfenyx** [comment]
Oder das hier: https://github.com/Uhula/ioBroker-Material-Design-Style. Funktioniert SUPER!

**Comment by ldittmar81** [comment]
Ist durch [vis-materialdesign](https://github.com/Scrounger/ioBroker.vis-materialdesign) abgedeckt. Ich schließe mal..
