### ISSUE TITLE
TR-064 - nach FritzOS 7.11 Update

### ISSUE THREAD

**Issue by baddy7** [ioBroker/AdapterRequests#222]
Seit dem Update der FritzBox auf FW 7.11 gibt es keine Updates bei den Adapterobjekten:
- tr-064.0.calllists.all.json
- tr-064.0.calllists.missed.json

es gibt sicherlich noch einige Objekte aber evtl ist's mit einem Update des TR-064-Adapter behoben?

Grüße
André

**Comment by sigi2345** [comment]
https://forum.iobroker.net/topic/22782/aufruf-test-community-version-vom-tr-064-adapter

**Comment by Apollon77** [comment]
Please open an issue with the respective adapter. This repo is for new Adapter requests.
