### ISSUE TITLE
Adapter für Mini Connected (BMW)

### ISSUE THREAD

**Issue by muhagl** [ioBroker/AdapterRequests#225]
Hallo, ich suche einen Adapter, womit ich auf meinen MINI per Connected Drive kann. Im BMW Connected Drive Adapter kommen nur die Daten für BMW's - müsste an sich ähnlich oder gleich sein - evtl. nur die Adresse - komme aber nicht weiter....? VG

**Comment by Bernd1984** [comment]
An dem Adapter wäre ich auch sehr interessiert. Da bereits ein Adapter für BMW existiert und Mini ja eine Submarke von BMW ist, muss sicherlich nicht viel angepasst werden.

**Comment by muhagl** [comment]
Ich hab das jetzt mit dem Blockly-Script gelöst:
https://forum.iobroker.net/topic/7457/adapter-bmw-zum-auslesen-von-bmw-s-connecteddrive-daten/213?_=1621003148585
VG
