### ISSUE TITLE
Adapter für den Sonnenverlauf 

### ISSUE THREAD

**Issue by Sharky780** [ioBroker/AdapterRequests#226]
Hallo zusammen,

Es währe nett wenn man einen Adapter bekommen könnte für den Sonnen verlauf in Iobroker zu 
intrigieren, denn dann kann man z.b. die Beschattung der Rollos über den Aktuellen Sonnenstand hoch oder runter fahren lassen.
Ich weiß zwar nicht ob das für die Entwickler weiter helfen würde, es gibt eine Seite die heißt Sonnenverlauf.de.   

Vielen Dank an die Leute, die es uns Ermöglichen ein Smartes zuhause selbst zu bauen.

**Comment by Apollon77** [comment]
Es gibt JavaScripts die die Sonnenposition bereitstellen. Ich denke nicht das es dafür einen Adapter braucht, oder ?!

**Comment by DutchmanNL** [comment]
Westherundergrund hat die meisten dieser Daten.

Es gibt auch einen sonnen Vorhersage Adapter dafür ist eine kleine Gebühr zufällig.

Ich kennen keine anderen "free" api die dergleichen Daten liefern

**Comment by DutchmanNL** [comment]
hat jemand eventuell eine seit oder api um diese Daten zu ermitteln ? sonst würde ich sagen close und WU nemen ?

**Comment by sigi2345** [comment]
> hat jemand eventuell eine seit oder api um diese Daten zu ermitteln ? sonst würde ich sagen close und WU nemen ?

https://www.torsten-hoffmann.de/apis/suncalcmooncalc/link_de.html

**Comment by DutchmanNL** [comment]
> > hat jemand eventuell eine seit oder api um diese Daten zu ermitteln ? sonst würde ich sagen close und WU nemen ?
> 
> https://www.torsten-hoffmann.de/apis/suncalcmooncalc/link_de.html

Mja nicht wirklich ne APi aber interessant

Frage zB was erwartet man, Sonnenverlauf währe fürich als Otto normal die Himmelsrichtung. Den ich weiß wo meine Fenster sind (nord-süd usw) aber mit Grafen usw kann ich wenig anfangen.

Ideen wie man das weiter umsetzen kann/sollte ?

**Comment by sigi2345** [comment]
> Ideen wie man das weiter umsetzen kann/sollte ?

Ich finde die Seite nicht schlecht, kann man ev. mit den Parser Adapter was machen?

**Comment by simatec** [comment]
shuttercontrol gibt die Daten, wie Sonnehöhe usw. als Datenpunkt und Standort bezogen aus.

**Comment by DutchmanNL** [comment]
https://github.com/ioBroker/AdapterRequests/issues/485

**Comment by HGlab01** [comment]
Der Adapter "FollowTheSun" steht nun im Latest Repository zur Verfügung
https://github.com/HGlab01/ioBroker.followthesun

**Comment by Apollon77** [comment]
Thank you!
