### ISSUE TITLE
Wunderlist-Adapter

### ISSUE THREAD

**Issue by AbdulAlBane** [ioBroker/AdapterRequests#227]
Guten Morgen zusammen,

ich fände einen Adapter für die ToDo-Liste [Wunderlist ](https://www.wunderlist.com/de/) sehr hilfreich. Neben Shopping-Listen (Bring!) könnten dann auch andere anfallen Dinge sinnvoll ins Smarthome und die VIS integriert werden.

Die offene API findet sich [hier](https://developer.wunderlist.com/documentation).

Gruß
Alex

**Comment by Coffee-lover** [comment]
Hi,

ich fände den Adapter auch schön!

Vg

**Comment by mobilutz** [comment]
Leider gibt es Wunderlist bald nicht mehr 🙁
![21E045A6-3F59-442E-BDA1-0D7C3FCD1602](https://user-images.githubusercontent.com/491877/71541846-3bcacd80-295f-11ea-9897-9aa4e9470cdb.jpeg)

**Comment by Apollon77** [comment]
Dann würde ich hier zu machen. Schade.

**Comment by mobilutz** [comment]
> Dann würde ich hier zu machen. Schade.

Ja, sehr sehr schade 😦
