### ISSUE TITLE
Adapter stürzt permanent ab

### ISSUE THREAD

**Issue by Moormerlander** [ioBroker/AdapterRequests#228]
Adapter stürzt direkt nach dem Start ab.
ioBroker-Config:

Node.js: v6.11.3
NPM: 3.10.10

`
host.ioBroker | 2019-07-09 10:03:46.240 | info | Do not restart adapter system.adapter.mercedesme.0 because disabled or deleted
-- | -- | -- | --
host.ioBroker | 2019-07-09 10:03:46.240 | error | instance system.adapter.mercedesme.0 terminated with code 1 ()
Caught | 2019-07-09 10:03:46.240 | error | by controller[0]: at startup (bootstrap_node.js:149:9)
Caught | 2019-07-09 10:03:46.240 | error | by controller[0]: at run (bootstrap_node.js:389:7)
Caught | 2019-07-09 10:03:46.240 | error | by controller[0]: at Module.runMain (module.js:604:10)
Caught | 2019-07-09 10:03:46.239 | error | by controller[0]: at Function.Module._load (module.js:438:3)
Caught | 2019-07-09 10:03:46.239 | error | by controller[0]: at tryModuleLoad (module.js:446:12)
Caught | 2019-07-09 10:03:46.239 | error | by controller[0]: at Module.load (module.js:487:32)
Caught | 2019-07-09 10:03:46.239 | error | by controller[0]: at Object.Module._extensions..js (module.js:579:10)
Caught | 2019-07-09 10:03:46.239 | error | by controller[0]: at Module._compile (module.js:542:28)
Caught | 2019-07-09 10:03:46.239 | error | by controller[0]: at Object.runInThisContext (vm.js:97:10)
Caught | 2019-07-09 10:03:46.238 | error | by controller[0]: at createScript (vm.js:56:10)
Caught | 2019-07-09 10:03:46.238 | error | by controller[0]: SyntaxError: Unexpected token ...
Caught | 2019-07-09 10:03:46.238 | error | by controller[0]: ^^^
Caught | 2019-07-09 10:03:46.238 | error | by controller[0]: ...options,
`

**Comment by Apollon77** [comment]
update nodejs to at least 8.x
