### ISSUE TITLE
Statistic/Aggregator

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/AdapterRequests#23]
Adapter to allow the automatic calculation of min, max, sums, averages, differences, also with timeframes and such by simple selection states and the wanted action. Configuration could be done by a custom dialog like mqtt and the history adapters.

Storage of the aggregated values would be in the namespace of the aggregator adapter

Also to replace CuxD a bit, I use CUxD to get "min-24h, max-24h" and such for some temperature sensors, we could also replace that

Migrated from Trello with 2 votes

**Comment by Apollon77** [comment]
What you mean? Mean more "Percentiles"?

One idea is to have a basic featureset and an enhanced featureset when the datapoint is historized using e.g. SQL or InfluxDB because then we can have more aggregation objects because dine by database. Or I need to find a node/Javascript library that supports this (if you have ideas or find some please add here)

**Comment by JackWolfskin42** [comment]
Wahrscheinlich meinen wir doch etwas unterschiedliches. Wenn ich deine Beipiele richtig verstehe möchtest du zusätzlich zu den  Originalwerten noch ab und an ein paar Statistische Größen zu liefern. 

Mein Vorschlag geht mehr in die Richtung die Originalwerte zu filtern, ergo permanent neue/andere Daten zu liefern, was evtl. eher in einem neuen Filter Adapter gehört.

**Comment by Apollon77** [comment]
Ja das wäre ein Filter/Modification-Adapter der Quasi filtern und umrechnen von werten erlaubt und damit virtuelle "andere" repräsentationen erechnen.
Andererseits unter dem Titel "Aggregator" Adapter wäre das ggf durchaus auch drin und vllt sinnvoll. Muss mal überlegen ob das zwei Adapter wären oder doch eher einer :-)

**Comment by AlCalzone** [comment]
Ich würde Filtern durchaus mit zu Statistik zählen.

**Comment by JackWolfskin42** [comment]
Für Node Red gibts ja schon schöne Filter wie den smooth:
[Node Red Smooth](https://flows.nodered.org/node/node-red-node-smooth)

**Comment by Apollon77** [comment]
Ja da kann man coole anleihen nehmen  ;-)

**Comment by Apollon77** [comment]
Ok, also sind wir Ideentechnisch bei folgendem Featureset:

1. Wert-Filterung / State-Wert "Bearbeitung": 
- Min, Max Definitionen inkl. Setting ob der Wert bei Über-/Unterschreitung auf Min/Max gesetzt wird oder ausgelassen wird
- Multiplikation mit einem Definierten Wert und Rundungsangabe des Ergebnisses
- Ablegen des Ergebnisses in einem neuen State

2. Direkte Aggregationen:
- Einfache Berechnungen ala "Node Red Smooth" wie (Floating) Min,Max, Average, Summe, Standardabweichung u.ä. unter Definition der Anzahl an Werten, Ablegen in neuen States (Basisname mit "-Min", "-Max" u.ä.
- Wünsche kamen noch nach Aggregationen nach "Zeit" (Average/Summe auf Stundenebene, Tagesebene, Woche, Monat) wobei man dazu einiges Cachen müsste in States, würde ich ggf durch 3. ersetzen

3. History-Adapter-Abfragen:
- Wenn der State (oder der aus 1.?)  auch in einem der History-Adapter aktiviert ist (History, SQL, InfluxDB) kann man Aggregationsabfragen von der DB erledigen lassen für unterschiedliche Zeiträume. Dann muss der Adapter selbst nichts cachen. Und man könnte auch Percentiles u.ä. "coolere Logiken" anbieten.

Meinungen dazu?

**Comment by JackWolfskin42** [comment]
Ich habe keine Ahnung wie IOBroker aufgebaut ist, und kann mir daher keine Meinugn dazu erlauben, was an Features da wie sinnvoll reinpasst  ;-)
Bei deinem Punkt 3 ist mir aber eine Idee gekommen, da ich kurz vorher noch den Request für einen RRDTool Adapter gesehen hatte und musste dann daran denken wie Domoticz das ziemlich elegant gemeinsam löst (Ja ich nerve vielleicht damit, aber die haben 2-3 geniale Ideen gehabt)
Die eingebaute Datenbank speichert die Werte anscheinend immer in eine RRD und die Statistics werden immer gleich mit abgelegt, das sieht dann z.B. immer so aus für einen Temperatur/Feuchtesensor:
![image](https://user-images.githubusercontent.com/38285253/38733340-d225e294-3f21-11e8-881b-c950d4346478.png)
Beim Übergang von den genauen Werten innerhalb eines Tages auf die Zusammenfassung eines Tages für die Monatsübersicht, wird hier z.b. auch gleich das Tempperatur Min und Max abgespeichert. So was in der Art (am Besten konfigurierbarer) hattest du dir vielleicht für 3. vorgestellt?

**Comment by Apollon77** [comment]
Ja RRDTool Adapter gibt einen Request. Die Herausforderung ist das wir mit "Datentypen" durchaus flexibel sind und bei RRD man alles zu beginn fest definiert und es darf danach nie sich ändern. Und RRD ist gut zum visualisieren, aber mit den Werten wieder zu arbeiten (ergo sie zu lesen) uist, soweit ich weiss, blöd/unpraktisch.

ioBroker hat aktuell 3 History-Adapter: History (JSon Files), SQL (Relationale SQL DB wie MySQL, MSSQL, Postgres) und InfluxDB. Für kleine Anwendungsfälle geht das mit JSON-Files recht gut und braucht nichts extra. Und die Abfrage ist flexibel möglich (https://github.com/ioBroker/ioBroker.history#access-values-from-javascript-adapter) und das geht in der Basis für alle drei Identisch. Bei den echten DBs kann man sogar noch custom-Queries absetzen.

Ich hätte also an der Stelle gesagt:
- Datenpunkt wird in einem der History-Adapter (gern auch automatisch) aktiviert
- Für einen tageswert wird dann einmal am Tag um 0:00 eine Query für den zeitbereich des Vortrages gemacht und das Ergebnis in einen State geschrieben ... Zur Visualisierung kannst du den dann wieder historisieren und darstellen.

Ansonsten muss der Adapter sich die Werte halten. Das geht auch und Skripte tun das aktuell auch so - die haben zig "Schatten-States" wo Sie die aktuellen Werte und sowas abspeichern wie nen Tageszähler der zu Tagesbeginn auf 0 gesetzt wird und dann immer addiert wird und so. Damit geht alles und man  "erinnert" sich an Werte auch wenn der Adapter mal beendet und neu gestartet wird (im vergleich zu alles im Speicher zu halten), hat aber den Aufwand mit den Schatten-States ...

**Comment by foxthefox** [comment]
Ich hab seit längerem schon an einem statistic adapter gearbeitet und grundsätzlich tut er es schon ganz gut. Seit gestern dann auch mit adminv3. Da noch 2 Bugs drin hab ich es aber auch noch nicht im Forum bekannt gemacht.

Ich sehe die Notwendigkeit die Zwischenstates auch als Objekte anzulegen um diese persistent vorrätig zu haben. D.h. ich lege diese Strukturen je nach Bedarf auch an.

Derzeitig realisiert und aus meiner Sicht sinnvoll:
- min /max / mean
- Zählung von Impulsen/Flanken
- Verbrauch aus Zählung
- Zeitenermittlung für Zustand 0 bzw. 1
- Zusammenfassung/gruppierung von Werten (z.B. Energie)

und das alles als Tages/Wochen/Monats/Quartals/Jahreswert

Runden, Smoothing, Standardabweichung sehe ich eher bei der Darstellung als im Adapter.

**Comment by Apollon77** [comment]
Cool, hast Du mal link, dann schaue ich mal an :-)

**Comment by foxthefox** [comment]
der link

https://github.com/foxthefox/ioBroker.statistics

**Comment by foxthefox** [comment]
first version issued today on npm
