### ISSUE TITLE
Volkszaehler frontend zur Energiekostendarstellung

### ISSUE THREAD

**Issue by ingoiot** [ioBroker/AdapterRequests#230]
hi,

das Volkszähler frontend ist wesentlich leistungsfähiger als
die Daten einfach nur mit Flot oder rickshaw darzustellen.

wäre schön wenn sich der Volkzähler einfach als Adapter installieren ließe.

mfg

https://github.com/volkszaehler/volkszaehler.org

**Comment by Apollon77** [comment]
Was genau wäre die Idee hier? Geht es nur darum die Daten darzustellen?

**Comment by ingoiot** [comment]
im Prinzip schon.
Die Datenbank und middleware brauchts denke ich nicht - wäre optimal wenn die Daten von history genommen würden. Wie es am Ende gelöst wird ist aber auch nicht so wichtig.

Das frontend is eben recht flexibel. Mann kann schnell mal ein paar Tage zurückscrollen,
sich einen Zeitbereich markieren und sieht was zb der Lauf ein Spülmaschine verbraucht hat.
Das ist bisher so nicht möglich.

**Comment by Apollon77** [comment]
Do you have seen https://forum.iobroker.net/topic/23033/aufruf-modifikation-simpleapi-adapter-iobroker-als-datenquelle-f%C3%BCr-grafana ... maybe grafana is an alternative for you?

**Comment by ingoiot** [comment]
i tested grafana on a domotiqz insallation,
but while way more beautiful than the available graphs,
the handling is more like flot or rickshaw, not as fancy as Volkszähler.org

**Comment by Apollon77** [comment]
DO you have some links or images of the cool features there?

**Comment by ingoiot** [comment]
on https://www.volkszaehler.org/ is demo page where it can be tested.

 https://demo.volkszaehler.org/?uuid=6836dd20-00d5-11e0-bab1-856ed5f959ae

**Comment by DutchmanNL** [comment]
this can be archived by flot or Grafana and layout adjusted by css to all needs.
i don't see added value for Volkszähler, maybe an feature request for flot ?

suggest to close

**Comment by OMCastle** [comment]
flot or Grafana is to komplex for a lot of people and dos not support the same

**Comment by mcm1957** [comment]
In meatime vis-2 and other vis provide a high flexibility to display infos from history adapters.
As there was no more discussion sinc 4,5years I'll close here
