### ISSUE TITLE
Ford Sync3 / FordPass Adapter

### ISSUE THREAD

**Issue by JBSullivan** [ioBroker/AdapterRequests#231]
I wish a Ford Sync3 /Ford Pass Adapter will become reality before i change my car (in 6 years ;) )

Here are some information for developers

https://developer.ford.com/

https://developer.ford.com/pages/applink/

**Comment by JBSullivan** [comment]
FordPass ist eine Android/iOS App, welche mit den neueren Multimedia Systemen (Sync3) in Ford Fahrzeugen kommunizieren. Über die App können aber auch Fahrzeug Parameter wie Benzin Füllstand, Serviceintervalle, bereits vereinbarte Werkstatttermine, Kilometerstände u.v.m ausgelesen werden.

Die Sync3 Hardware ist in jedem neueren Ford PKW verbaut und verfügt über einen Wlan Zugang. Fahrzeuge die z.B. in der Garage stehen und über einen guten Wlan Zugang verfügen, sind so nach ausschalten der Zündung über das heimische Netzwerk bis zu 4 Minuten sichtbar.

In dieser Zeit könnten die oben genannten Daten ausgelesen und für eine VIS Darstellung verwendet werden. Praxis Beispiel: Der Adapter Tankerkönig zeigt einen günstigen Benzinpreis an. Nun ist die Frage. wie voll ist eigentlich mein Tank, lohnt es sich ggf. zum Nachtanken an die Tankstelle zu fahren?

Über das auslesen der Snyc3 Datenverbindung bei der Anmeldung des Fahrzeugs im Heimischen Netzwerk, hätte man z.B. den letzten Benzin Füllstand zur Verfügung  und müsste nicht erst raus zum Fahrzeug laufen um nachzusehen.

Wenn ich das richtig verstehe kann man sogar mit Zustimmung von Ford und enstprechenden API`s eigene Programm entwickeln die z.B. die bereits genannten Daten parsen und so in einem Adapter zu Verfügung stellen.

Vielleicht sind hier ja auch Ford fahrende User unterwegs die vom programmieren mehr Ahnung haben als ich und diese Idee ganz charmant finden ;)

**Comment by TA2k** [comment]
Werden die Daten die du in der App siehst auf einem Server gespeichert?
Also wenn du Daten abfragst und die App neustartest oder löscht und neuinstallierst siehst du dann daten von dem letzten Sync?
Ich könnte ein Adapter schreiben wenn jemand Zugangsdaten für die App bereitstellt

**Comment by JBSullivan** [comment]
Hallo, ja, nach Neuinstallation der Ford PASS App sind die alten Daten wieder da. Scheint über die Mail Adresse des eingerichteten Buntzerkonto synchronisiert zu werden.

**Comment by TA2k** [comment]
Wenn jemand mir Zugangsdaten im Forum per pn zukommen lässt könnte ich ein Adapter erstellen.  Mein Name ist tombox

**Comment by Xandar31** [comment]
Ich habe im developer.ford.com Forum mal nachgefragt obs ein Rest-Api gibt bei der man die Daten vom Auto abfragen kann. (KM Stand, Tankinhalt, Standort, Reifendruck, ...)

Aktuell gibts da wohl noch nichts.

> Hi Xander,
> Ford has been refining access and usabilty for these types of APIs and we expect to have something for our developer community by late summer-early fall (due to pandemic delays). We will make an announcement as we approach the launch, so stay tuned!
> 
> Thanks,
> FordDev Team

Bin mal gespannt wann da was kommt und ob ich bis dahin immer noch Ford fahre.

**Comment by matare01** [comment]
Ich hätte auch gerne einen Adapter mit dem Ich auf meinen Ford zugreifen könnte denn so währe es vielleicht auch möglich
das im Winter die Heizung bzw im Sommer die Klimaanlage von ioBroker aus gesteuert wird.

es gibt sicher eine Möglichkeit sich zu verbinden ich habe schon verschiedene Ansätze gefunden aber
mangels meiner Programmier kenntnis kann ich leider nichts daraus machen.

https://github.com/Brandawg93/homebridge-fordpass
https://github.com/d4v3y0rk/ffpass

Ich könnte gerne auch meine Fahrzeug Zugangsdaten an jemanden weitergeben der was draus machen kann.

**Comment by Horatio2084** [comment]
Ich habe selbst probiert eine Adapter zu erstellen.

Ich bekomme schon die aktuellen Daten von meinem Ford in IOBroker.
Ist aber gerade noch eine Quick and Dirty Lösung da ich noch nie etwas mit JavaScript gemacht habe.

Werde es in den nächsten Tagen überarbeiten.

https://github.com/Horatio2084/ioBroker.fordpass

**Comment by Apollon77** [comment]
If you need feedback or support we have groups for devs in Discord, Forum and Telegram

**Comment by TA2k** [comment]
@matare01 @JBSullivan wird hier noch was benötigt?

**Comment by JBSullivan** [comment]
Von meiner Seite nicht mehr - Auto ist verkauft.

**Comment by Rugged-ESP** [comment]
Funktioniert der Adapter aktuell noch?

**Comment by TA2k** [comment]
Wie gesagt ich kann schnell ein machen wenn jemand Zugangsdaten bereitstellt

**Comment by Horatio2084** [comment]
@Rugged-ESP kann ich leider nicht sagen. Hab momentan IO-Broker nicht laufen.

Wenn jemand den Adapter pflegen will würde ich die Repo inkl. NPM übertragen.

**Comment by TA2k** [comment]
Ich habe mal schnell einen erstellt. Mit der Login funktioniert aber wie gesgt ich bräuchte zugangsdaten um ihn fertig zu stellen
https://forum.iobroker.net/topic/47548/test-adapter-ford-0-0-1

**Comment by ldittmar81** [comment]
@Apollon77 can be closed. Its latest
