### ISSUE TITLE
GARDENA smart Irrigation Control

### ISSUE THREAD

**Issue by sabixx** [ioBroker/AdapterRequests#234]
Please consider building an adapter for the  GARDENA smart Irrigation Control System.

**Comment by Apollon77** [comment]
Please provide more details like Links, API descriptions or already done libraries or such

**Comment by maodch** [comment]
there is already a solution when you're looking at github.
I'm using it and control my hole watering pipeline with it.
Yes, it's not as smooth as it could be, but it works.

https://github.com/t4qjXH8N/ioBroker.gardena

**Comment by sabixx** [comment]
already exists, closing

**Comment by DutchmanNL** [comment]
adapter is not released yet, raised issue with that question :). https://github.com/t4qjXH8N/ioBroker.gardena/issues/26
