### ISSUE TITLE
Sql erweiterter Export (oder Filterung)

### ISSUE THREAD

**Issue by maodch** [ioBroker/AdapterRequests#235]
Mir fehlt immer wieder die Möglichkeit, direkt aus ioB aus Historydaten (sql.0) einen Export in Excel zu fahren.
Leider werden, wenn man die Daten loggt, bei der Ansichit in ioB nicht alle Datensätze dargestellt, z.B: wenn es ein paar Hundert sind, kommen, sagen wir mal Top100? Top 500? Keine Ahnung, aber manchmal komm ich nicht mal über einen Tag hinweg an Logdaten.

Entweder, es gibt beim sql.0 die Möglichkeit, die Count's einzustellen, oder wenn das aus Performancegründen schlecht sein sollte, zumindest die Exportmöglichkeit, und zwar nicht jene, die nur die aktuelle Ansicht (eben, zu wenig Daten im Set) exportiert, sondern alle anhand Filter.

**Comment by Apollon77** [comment]
Ist alles möglich. Zwar nicht direkt excel aber eigene Skripte können Custom sql queries ausführen https://github.com/ioBroker/ioBroker.sql/blob/master/README.md#custom-queries oder per getHistory Daten ohne sql Anfragen. 

Weiterhin: sql adapter enhancements bitte beim sql Adapter einstellen.
