### ISSUE TITLE
new Sonos Adpater

### ISSUE THREAD

**Issue by Hesse-Bub** [ioBroker/AdapterRequests#239]
As the actual Sonos Adapter is making more and more trouble and the tts is not working for a long time. Maybe it would be good idea to create a new version based on the newer http api from jishy:

https://github.com/jishi/node-sonos-http-api

This would also be an option to include the newer sonos functions for the TV soundbars like night mode and improved speak sound.

Also the TTS functionality is working much better with this API

**Comment by Apollon77** [comment]
Sorry but this is no adapter request. Create issue at sonos Adapter to update it.
