### ISSUE TITLE
Somfy Tahoma Adapter

### ISSUE THREAD

**Issue by DirtyAtze** [ioBroker/AdapterRequests#240]
Ich hätte großes Interesse an einem funktionierenden Adapter für Somfy Tahoma/connexoon, da ich inzwischen fast alles über ioBroker steuern kann, außer meine Rollläden/Jalousien

Da Somfy sich inzwischen nach außen geöffnet hat und ein API bereitstellt, sollte es doch eigentlich ein leichtes sein, das umzusetzen. Ich hab selbst leider keine Ahnung vom Programmieren, aber hier gibt es sicher jede Menge fähige Leute!

Es gibt auch bereits ein Javascript, welches vielleicht als Vorlage genutzt werden kann. Bei mir funktioniert das Script zwar leider nicht, aber von einigen anderen Usern kam ein positives Feedback.

Link zum Forum: https://forum.iobroker.net/topic/8169/anfrage-tahoma-somfy-io-adapter/2

Falls ich die Entwicklung in irgendeiner Art unterstützen kann, würde ich das gerne tun. Könnte uU auch Zugang zu meinem Tahomoa Konto geben.

**Comment by Apollon77** [comment]
Hast Du mal den ham adapter zusammen mit https://www.npmjs.com/package/homebridge-tahoma versucht?

**Comment by DirtyAtze** [comment]
Hi,

die methode kenn ich noch nicht, kann ich das auf dem Raspberry installieren, auf dem ioBroker läuft?

**Comment by Apollon77** [comment]
ham Adapter: https://forum.iobroker.net/topic/13509/aufruf-iobroker-ham-homebridge-accessory-manager-testen

**Comment by DirtyAtze** [comment]
Super Sache, das funktioniert!

Vielen Dank für den Tipp!

**Comment by blackeagle998** [comment]
Hallo Apollon77,

ich habe den ham Adapter mit dem Homebridge Tahoma Plugin getestet. Die Verbindung funktioniert, die Objekte sind da, allerdings ändern sich die States night, wenn ich die Rollläden per Wandtaster bediene.

Wäre es nicht möglich, dass sich einer von euch Entwicklern mal die Somfy API ( SOMFY SO OPEN) anschaut und da vielleicht einen gescheiten Adapter draus baut? 

Nach bisherigem Stand würden sich da einige User im Forum drüber freuen.

Viele Grüße!

**Comment by Apollon77** [comment]
Hey,
erst einmal sehe ich oben im ersten Beitrag 2x ein Thumbs up ... wären also 2 User ;-) Dann stifte die anderen der "einigen" mal an hier auch Ihren Daumen hoch zu hinterlassen.

**Comment by blackeagle998** [comment]
Geht klar, ich tue mein Bestes!
https://forum.iobroker.net/topic/27400/vote-f%C3%BCr-einen-somfy-tahoma-connexoon-adapter
https://forum.iobroker.net/topic/8169/anfrage-tahoma-somfy-io-adapter/64

**Comment by icschorr** [comment]
Ich unterstütze den Post hier 👍

**Comment by blackeagle998** [comment]
> Hey,
> erst einmal sehe ich oben im ersten Beitrag 2x ein Thumbs up ... wären also 2 User ;-) Dann stifte die anderen der "einigen" mal an hier auch Ihren Daumen hoch zu hinterlassen.

@Apollon77 

Kannst du uns bitte eine kurze Rückmeldung geben, ob und wie es hier weiter geht?
Danke!

**Comment by Apollon77** [comment]
Da kann ich nicht wirklich etwas sagen.
Die Adapter-Requests funktionieren so das hier die "Nicht Entwickler User" sich Adapter "wünschen" können und über die "Thumbs up" zeigen können wie wichtig so ein Adapter jeweils wäre. Einer der Entwickler, der ggf ein neues Projekt sucht kann sich diese Adapter-Liste nehmen und schauen ob er etwas findet worauf er Lust hat. Idealerweise berücksichtigt er dabei die Stimmen und so den "Bedarf in der Community".

Ich persönlich werde in absehbarer zeit keine Zeit haben dieses Thema zu starten zumindestens nicht vor 2021 ;-) - ich bin aber bei weitem nicht der einzige Entwickler ;-)

Wenn es schon ein JavaScript gibt und auch der HAM Adapter läuft habt Ihr doch erst einmal zwei Grund-Lösungen, oder sehe ich das falsch? (Nein das soll nicht sagen das der Adapter unwichtig wäre!) ... aber wenn mit Homebridge-Plugin oder Skript Dinge nicht gehen die cool wären sind wir ggf noch an dem Punkt das die Hardware nötig wird um den Rest noch herauszufinden und einzubauen.

**Comment by iqmend** [comment]
Ich habe mich gerade extra bei GitHub registriert nur um den Beitrag zu unterstützen. 

ioBroker ist im kommen und hat schon Systeme verdrängt die länger auf dem Markt sind. 
Warum ? 
Weil ioBroker eine geile Community hat und die Bedienung sehr inuitiv ist. 
Es wird eine Menge unterstützt und es gibt zig verschiedene Videos zu verschiedenen Themen. 

Für mich ist und bleibt ioBroker #1. 

Ein Somfy Adapter darf meiner Meinung nach nicht fehlen. Somfy und Velux sind zwei sehr bekannte Hersteller in ihrem Gebiet, und wir wollen ja noch weiter wachsen, also sollten wir es neuen Usern schmackhaft machen ioBroker zu nutzen.

Dadurch das Somfy die API öffentlich gemacht hat sollte es für den Developer auch eine machbare Sache sein und der Aufwand sich in Grenzen halten.

Wenn ein Developer Zeit und Lust hat, dann soll er sich melden. Im Zweifel starten wir noch eine Spendenaktion und versuchen so für den Developer das maximum an Dankbarkeit für seine Leistung zu erbringen.

**Comment by StrathCole** [comment]
Ich werde mich ggf. mal dran setzen, sobald ich die Zeit finde, und auf Basis des Scripts von "CodeMasteR" und den Anpassungen von "thoemmes86" aus dem Forum (siehe https://forum.iobroker.net/topic/8169/anfrage-tahoma-somfy-io-adapter/) einen Adapter bauen.

**Comment by DirtyAtze** [comment]
Das wäre super! 
Wenn du dafür zugang zu einer TaHomaBox brauchst, könnte ich dir meinen Zugang zur Verfügung stellen.

Zwar läuft die Geschichte mit dem HAM Adapter inzwischen schon eine ganze Weile zuverlässig, aber die Möglichkeiten sind damit doch recht eingeschränkt.
Ich kann z.B meine Jalousien damit hoch/runter fahren, aber die neigung der Lamellen lässt sich nicht steuern.
Außerdem haben meine Motoren (neueste Generation IO) einen Flüstermodus, der bei jedem Fahrbefehl akriv/inaktiv gestetzt werden muss (am Wandsender gibt es dafür einen schalter. Bei steuerung über TaHoma muss der Flüsterbetrieb manuell gesetzt werden.) Dir Option dafür fehlt aber im HAM Adapter.

Vielleicht ist es möglich, diese beiden punkte bei der Adapterentwicklung zu berücksichtigen.

**Comment by icschorr** [comment]
Auch von mir einen Daumen hoch für Dein Vorhaben!

**Comment by StrathCole** [comment]
Ich habe selbst eine Tahoma Box V2 und habe bei mir das JavaScript aus dem Forenthread schon einige Zeit laufen, aber ab und an ein paar Problemchen. Daher könnte ich die in dem Zuge dann ausmerzen.

**Comment by StrathCole** [comment]
> Außerdem haben meine Motoren (neueste Generation IO) einen Flüstermodus, der bei jedem Fahrbefehl akriv/inaktiv gestetzt werden muss (am Wandsender gibt es dafür einen schalter. Bei steuerung über TaHoma muss der Flüsterbetrieb manuell gesetzt werden.) Dir Option dafür fehlt aber im HAM Adapter.
> Vielleicht ist es möglich, diese beiden punkte bei der Adapterentwicklung zu berücksichtigen.

Da könnten wir uns, wenn der Grundadapter steht, ja noch mal im Forum per PN kurzschließen, da ich selbst nur Rollläden habe. Habe im Forum denselben Nickname.

**Comment by StrathCole** [comment]
Hab eine erste Version fertig.
https://github.com/StrathCole/ioBroker.tahoma

**Comment by DirtyAtze** [comment]
Coole Sache!

Werde ich heute Abend gleich mal installieren unt testen.

**Comment by DirtyAtze** [comment]
Moin,

die Installation und Einrichtung des Adapters lief absolut reibungslos. Der Adapter läuft auch einwandfrei.
Was mir aufgefallen ist, dass die Steuerung der Rollläden über buttons (up, down, stop, my) läuft. Bisher war das bei mir (über den HAM Adapter) nicht möglich. Die Steuerung lief über die "Target Position" in %.
Beide varianten haben ihre Vor und Nachteile, daher wäre es schön wenn die Möglichkeit der Steuerung über eine %-Angabe weiterhin möglich wäre.
Die Aktuelle Position des Rollladens wird mir in den States auch in % angezeigt.

Das gleiche gilt natürlich auch für Jalousien, wobei es dort noch schön wäre, wenn die Stellung der Lamellen auch noch gesteuert werden könnte.

Ansonten, sehr gute Arbeit! Vielen Dank nochmal für die Mühe!

**Comment by StrathCole** [comment]
Hi,
das ist möglich. Einfach unter "states" den Core:ClosureState Wert verändern. Dann fährt der Rollladen in die gewünschte Position.

**Comment by StrathCole** [comment]
Und für die Neigung müsste es Core:SlateOrientationState sein.

**Comment by Apollon77** [comment]
Cool! Wenn es soweit stabil ist freue ich mich auf Repo-Anfrage. Die Diskussion am besten im Forum führen?

**Comment by StrathCole** [comment]
@Apollon77 ist ja nun schon die erste Version im latest Repo.

**Comment by Apollon77** [comment]
Danke!

**Comment by Moormerlander** [comment]
Bis letzte Woche lief der Adapter einwandfrei, aber seitdem ich von node.js 10 auf Version 12 hochgezogen habe leider nicht mehr. Ein Adapter  Rebuild und Reinstall brachte auch keinen Erfolg.

**Comment by uwe72** [comment]
Lebt dieser Adapter noch? Habe ihn in ioBroker eingebunden, allerdings gibts nicht mehr alle Datenpunkte um meine RTS Markise hoch- bzw. runterzufahren. Letztes Jahr ging dies noch. An wen und wo kann ich mich hier wenden?

**Comment by Apollon77** [comment]
Bitte im Adapter-Repository nachfragen, nicht hier :-)

**Comment by Moormerlander** [comment]
> Bitte im Adapter-Repository nachfragen, nicht hier :-)

Kannst Du mir sagen wo/wie ich das mache?
Der Adapter läuft nicht mehr ganz sauber und ich würde gerne mal einen Case aufmachen wollen.

**Comment by uwe72** [comment]
> ![Bildschirmfoto 2021-05-18 um 08 22 45](https://user-images.githubusercontent.com/27990424/118602219-b265a680-b7b2-11eb-8de4-ab3c0c10c34c.png)
> 
> > Bitte im Adapter-Repository nachfragen, nicht hier :-)
> 
> Kannst Du mir sagen wo/wie ich das mache?
> Der Adapter läuft nicht mehr ganz sauber und ich würde gerne mal einen Case aufmachen wollen.

https://github.com/StrathCole/ioBroker.tahoma/issues

**Comment by DennjoOyola** [comment]
> Core:ClosureState

Hmm... mein Adapter verbindet sich. Die Datenpunkte sind alle zu sehen. Alle Rolläden geöffnet, also steht der state auf 0%. Setze ich diesen auf z.B. 50%, passiert jedoch nichts. Was mache ich falsch?

**Comment by sansonifabio** [comment]
Ich fände einen Adapter für iobroker auch gut.
Grüße
Fabio

**Comment by Apollon77** [comment]
@sansonifabio DU hast aber gesehen das das hier closed ist und es einen adapter gibt?

**Comment by sansonifabio** [comment]
> @sansonifabio DU hast aber gesehen das das hier closed ist und es einen adapter gibt?

jetzt wo du es sagst @Apollon77 sehe ich auch das es closed ist. 
Ja was will man machen mit 60 Jahren fällt einen doch einiges schwerer.
