### ISSUE TITLE
Adapter für Senec Stromspeicher und Photovoltaik

### ISSUE THREAD

**Issue by B4n4n3** [ioBroker/AdapterRequests#241]
Hallo zusammen,

ein Adapter für die Anbindung der SENEC Strompeicher und die Photovoltaik-Anlagen wäre richtig klasse! Wobei eine Anbindung an die Cloud-Daten und nicht direkt auf den Stromspeicher evtl. auch denkbar wäre!

Grüße B4n4n3

**Comment by Apollon77** [comment]
Gibts mehr Infos? Links? API-Informationen? ANdere Libraries oder Projekte die das schon auslesen können?

**Comment by asrenz1904** [comment]
Hi zusammen, ja das wäre super cool!

**Comment by jkoeber** [comment]
Hi, wurde von mir erstellt die Tage.

https://github.com/jkoeber/ioBroker.senec

**Comment by B4n4n3** [comment]
@jkoeber Ich feier dich gerade so hart ;-)
Hab ihn installiert ... funktioniert! TipTop!

**Comment by tg-71** [comment]
@jkoeber 
Hallo 
Vielen Dank für die tolle Arbeit. Funktioniert super!
2 "Anregungen" hätte ich noch:

- könntest Du vielleicht noch die Einheiten in die Definition der States integrieren

- Auf der Konfigurationsseite ist vielleicht nicht Jedem sofort klar, dass die IP-Adresse eingetragen werden muss. Ein kleiner Hinweis könnte machem helfen.

Viele Grüße

Thomas

**Comment by asrenz1904** [comment]
@jkoeber Mega! Habe es gerade bei mir installiert. Funktioniert ohne Probleme. 
Vielen Dank für deine Arbeit. Würde mich den Anmerkungen von @tg-71 anschließen.

Viele Grüße und Vielen Dank fürs Weihnachtsgeschenk. 

Andreas

**Comment by Apollon77** [comment]
Am besten legt doch für eure Anregungen und feature requests issues I’m eigentlichen adapter repo an ;-)

**Comment by tg-71** [comment]
> 
> 
> Am besten legt doch für eure Anregungen und feature requests issues I’m eigentlichen adapter repo an ;-)

Hab zwei Requests angelegt. Werden hoffentlich als Wünsche aufgefasst. ;o)
