### ISSUE TITLE
Traccar - Iobroker adapter

### ISSUE THREAD

**Issue by Headhunter70** [ioBroker/AdapterRequests#243]
Traccor is an open source project for trackings GPS devices. many GPS protocols and different devices are already supported.  I would love to see an adapter for Iobroker coming .-) Just imagine you arrive at home with your car and iobroker switch on outdoor lights  and open the garage door... or your pet is moving outside the geofence and iobroker informs you via Alexa

https://github.com/traccar/traccar

https://www.traccar.org/traccar-api/

cheers

**Comment by DutchmanNL** [comment]
possible candidate for Project [It's not hard to build an adapter]

https://forum.iobroker.net/topic/32265/das-project-einen-adapter-bauen-ist-nicht-schwer/110

Script available : https://forum.iobroker.net/topic/36373/mit-traccar-eine-geofence-alternative-für-iphone-und-android/2

**Comment by Headhunter70** [comment]
Count me in bro

**Comment by gallaxymv6** [comment]
The adapter is really cool!

Hope that this will soon be officially included in the iobroker!

Since it doesn't really work that way with Traccar and Telegram, it would be nice if you could read out the speed in the iobroker!

**Comment by DutchmanNL** [comment]
@o0shojo0o what is the status of the current community version, can we bring it to latest ?

https://github.com/iobroker-community-adapters/ioBroker.traccar

**Comment by o0shojo0o** [comment]
Yes we could, haven't reported any bugs so far.

**Comment by DutchmanNL** [comment]
> Yes we can, haven't reported any bugs so far.

Great, will you Reise it or should i ?

**Comment by o0shojo0o** [comment]
> Great, will you Reise it or should i ?

I take care of it.

**Comment by DutchmanNL** [comment]
Thanks, per raised let’s close here
