### ISSUE TITLE
DAIKIN Heat Pump / Wärmepumpe

### ISSUE THREAD

**Issue by steph77pro** [ioBroker/AdapterRequests#245]
Hallo zusammen,
Hello everybody,

ein Adapter für die Anbindung von DAIKIN Wärmepumpen über den DAIKIN LAN Adapter BRP069A62 wäre klasse! 
an adapter for connecting DAIKIN heat pumps via the DAIKIN LAN adapter BRP069A62 would be great!

DANKE im Voraus
Thanks in advance

**Comment by Apollon77** [comment]
The daikon adapter from climare contrtol is not working? If not the we need Infos on the needed calls only to add there. Please open an issue there. 

Any library known that supports it?
