### ISSUE TITLE
Mymuell Adapter

### ISSUE THREAD

**Issue by Elektronikwelt** [ioBroker/AdapterRequests#246]
anyone write an adapter that binds the API from https://www.mymuell.de.  There is already an Android app.

> *created by ioBroker.info*

**Comment by Apollon77** [comment]
Do you have a Link to the api it such?

**Comment by Jey-Cee** [comment]
They don't have an API, but they provide an ical file. 
I think it is better to create an adapter with ical support or use the ical adapter its self.

**Comment by DutchmanNL** [comment]
> I think it is better to create an adapter with ical support or use the ical adapter its self.

if they provide an ical file I don't see an need for a dedicated adapter, import the ical into an public calendar (like google) and sync with ical adapter ?

if the APi is not public, it. makes no sense to build an "open source" connector ?

**Comment by Jey-Cee** [comment]
Adavantages of an seperated adapter:
 - Automated/Manual retrieval of the ical file (because i saw more than mymuell is dealing with the same Web interface to get the ical file), or alternative sources but with the same interface
- exact defined objects 
- out-of-the-box usage (the ical adapter solution does not provide this)
- vis widgets can be provided

**Comment by Elektronikwelt** [comment]
I do not want to maintain the collection of garbage manually in an ICAL file.  I would like to query the data of Mymüll (the place should be adjustable in the data points) and represent in the Vis.  I saw that the app did not do anything else.  Maybe someone can analyze the interface of the app and then emulate it as an adapter for Iobroker.

**Comment by Elektronikwelt** [comment]
I wrote to Mymüll if the interface configuration provided me with an answer

**Comment by Elektronikwelt** [comment]
Here is the Link to Download the Adroid App http://android.mymuell.de/

**Comment by bkuerby** [comment]
You may want to try https://www.mein-abfallkalender.de/
Seems to be the same like MyMuell.de, but you can get the data in ical directly.

**Comment by Jey-Cee** [comment]
@Elektronikwelt The ical file is generated by the service, you have to download it once a year, thats it. 

@bkuerby you can not choose the service provider, each Landkreis choose the service provider by its self. So you have to use what you get.

**Comment by volkerrichert** [comment]
I have a script reading data from https://mymuell.jumomind.com. You just need city_id & area_id. Someone interested?

**Comment by Elektronikwelt** [comment]
For me it would be interesting, since MyMüll is maintained by our waste manager.  Could you send me the script?

**Comment by volkerrichert** [comment]
I put it into [github](https://mymuell.jumomind.com/webmodul/wegberg/).

But just the script code. You have to add npm module "request" to your javascript module and find your(!) city and area IDs. I found mine by inspecting the webbased calendar at [https://mymuell.jumomind.com/webmodul/wegberg/](https://mymuell.jumomind.com/webmodul/wegberg/). I never checked other areas.

**Comment by Elektronikwelt** [comment]
Hi volkerrichert

I could not find my place "Eberhardzell".  why does this work in the app but it does not work with your link.  how did you find out your place?

**Comment by patrik-dev** [comment]
Is it possible to get all available cities and streets?

**Comment by volkerrichert** [comment]
Upsss... :-)

https://mymuell.jumomind.com/mmapp/api.php?r=cities

**Comment by Elektronikwelt** [comment]
Stupid question: how and with which adapter can I access the data.  I found the ID for Eberhardzell

**Comment by Elektronikwelt** [comment]
@volkerrichert why did you delete the link.  Appolon77 initially asked if there was an Api Link

**Comment by volkerrichert** [comment]
@Elektronikwelt I don't know if it's allowed (legale) to publish an API link which isn't used on a public site. And because it's so easy to guess, it took me one try to guess it, I want to be on the "right side".

**Comment by volkerrichert** [comment]
@Apollon77 There is no API-Doc, but you can "see" it in real life:

`https://mymuell.jumomind.com/mmapp/api.php?r=streets&city_id=XXX`

"r" seem to be the resource you want to load. street and trash are used here [](https://mymuell.jumomind.com/webmodul/wegberg/)

"cities" is also a valid resource. 

To get all dates and types of your trash pick ups, you must query

`https://mymuell.jumomind.com/webservice.php?idx=termins&city_id=XXX&area_id=XXX&ws=3`

with the area_id given in your street entry. All trash types are listed in the trash resource

**Comment by klein0r** [comment]
Added to [ioBroker.trashschedule](https://github.com/klein0r/ioBroker.trashschedule/) (v3.0.0)

**Comment by mcm1957** [comment]
solved by ioBroker.trashschedule.
