### ISSUE TITLE
Judo i-soft Wasserenthärtung

### ISSUE THREAD

**Issue by ITfromHell** [ioBroker/AdapterRequests#247]
Die Geräte der Serie Judo i-soft (safe, plus) verfügen über ein IP Interface, über das mit einer App Status, Parameter, Statistiken und Fehler ausgetauscht werden. 

Hersteller Webiste: https://judo.eu/enthaertung/

Für FHEM wurde wohl bereits ein Adapter gebaut: https://wiki.fhem.de/wiki/JUDO_iSoft_Plus

**Comment by regalo999** [comment]
Ein Judo-Adapter wäre klasse!

**Comment by ronnythomas** [comment]
Hardware hätte ich da und Anydesk zum Probieren.

**Comment by mpenn0** [comment]
Ich hätte auch Interesse!

**Comment by Apollon77** [comment]
> Ich hätte auch Interesse!

Dann klicke im ersten Post bitte auf den Daumen hoch, sonst sieht es niemand ;-)

**Comment by mpenn0** [comment]
Danke für den Hinweis, schon erledigt :-)

**Comment by Nussert** [comment]
Hallo Zusammen,
gibt es dazu schon Neuigkeiten, wäre sehr interessant ein Adapter.
@Apollon77 du hast angemarkt, dass Du Hardware benötigst.
Wenn ich irgendwas an meiner Anlage testen kann/soll - kein Problem ;-)

**Comment by joker17177** [comment]
Hallo Leute!

Bin neu bei Euch und begeistert von Eurem Engagement und Fachwissen. Ich habe durch mein Interesse am IOBroker zu Euch gefunden und bin auf der Suche nach einem Judo I-Soft Plus Adapter auf diesen Beitrag gestoßen. 
Ich besitze zwei dieser Anlagen und wäre auch erfreut über eine Möglichkeit diese in mein Smart Home einbinden zu können.
Ich weiß nicht in wie weit Euch das weiterhilft, aber wenn ich auf meiner Anlage den Port 8000 im Webbrowser öffne, dann erscheint folgendes.

![I-Soft-Plus-Port-8000](https://user-images.githubusercontent.com/59476103/71725396-04af5d00-2e34-11ea-91e8-c7e7369e198b.jpg)

**Comment by joker17177** [comment]
Ich habe auch den PIN um in die Einstellungsebene des Servicemechanikers zu kommen. Ist laut seiner Aussage bei jeder I-Soft Plus gleich...-;)

**Comment by Brandy-f1** [comment]
Hallo Leute,

Ich wäre auch sehr an einem Andapter für eine Judo i-soft safe interessiert! Eine Anlage zum Testen wäre vorhanden, was sonst noch benötigt wird, bitte einfach schreiben.
Ich bin hier noch Anfänger.

**Comment by tommedIO** [comment]
> Hallo Leute,
> 
> Ich wäre auch sehr an einem Andapter für eine Judo i-soft safe interessiert! Eine Anlage zum Testen wäre vorhanden, was sonst noch benötigt wird, bitte einfach schreiben.
> Ich bin hier noch Anfänger.

Dem schließe ich mich auch an. Habe ebenfalls oben meinen Daumen gesetzt, in der Hoffnung, dass es bald losgeht :)

**Comment by eviw** [comment]
Ich stehe auch kurz vor der Anschaffung der Jodo i-soft. Iobroker läuft und ich stehe gern als Tester bereit. Daumen ist gesetzt.

**Comment by mirage-111** [comment]
Hallo @joker17177,
Kannst mir mal die Zugangsdaten per Mail zukommen lassen, will mir das mal anschauen.
Mail: mirage-1 at gmx.de

Danke

**Comment by eviw** [comment]
> 
> 
> Ich stehe auch kurz vor der Anschaffung der Judo i-soft. Iobroker läuft und ich stehe gern als Tester bereit. Daumen ist gesetzt.

i-soft plus Anlage ist installiert und im Netz. Ich stehe nun gern als Tester bereit.

**Comment by eviw** [comment]
Einen hilfreichen Blog zur i-soft pro API hab ich noch gefunden. Zwar schon älter, aber funktioniert wohl noch: [https://blog.muwave.de/2017/06/monitoring-and-controlling-a-judo-i-soft-plus-water-softening-device-via-lan/](https://blog.muwave.de/2017/06/monitoring-and-controlling-a-judo-i-soft-plus-water-softening-device-via-lan/)

**Comment by tommy-rk** [comment]
Gibt es denn jemanden, der das Projekt angenommen hat und umsetzen will?

**Comment by tommedIO** [comment]
Ich glaube, dass sich leider noch niemand an die Programmierung gemacht hat.

**Comment by CG28** [comment]
Steht bei mir auch ganz oben auf der Liste. Ist mir einfach zu umständlich jedesmal in der App die Wasserhärte anzupassen und entsprechende Sensorik habe ich noch keine installiert. Daumen ist gesetzt.

**Comment by jreichl** [comment]
da schliesse ich mich an, dieser Adapter wäre super

**Comment by Andr3asB** [comment]
Bedarf für den Adapter +1

**Comment by Apollon77** [comment]
Dann hoffe ich ihr habt alle oben Thumbs up geklickt

**Comment by arteck** [comment]
fettisch
https://github.com/arteck/iobroker.judoisoft

**Comment by eviw** [comment]
> 
> 
> fettisch
> https://github.com/arteck/iobroker.judoisoft

Klasse, vielen Dank!
Installation ohne Probleme und alle Datenpunkte sind gefüllt. Werde die Tage genauer testen.

**Comment by joker17177** [comment]
Hallo Leute!

Erstmal vielen Dank für den Adapter. Konnte ihn problemlos installieren. Leider verbindet er sich nicht mit meiner Anlage. Bekomme im Log die Fehlermeldung "(19704) No one IP configured" und die Datenpunkte füllen sich auch nicht. Kann mir Jemand einen Tipp geben? Benutzername und Passwort sind ja sicherlich die von der Online Registrierung, oder?
Ich habe in der Anleitung von Judosoft zur APP gelesen, das man bei einer lokalen Verbindung bei der Registrierung die Datenschutzerklärung ablehnen muß. 
Bin irgendwie verwirrt und bitte um Hilfe. Vielen Dank im Voraus!

**Comment by mirage-111** [comment]
Gutes Neues, und vielen Dank für den Adapter.
Ich hab gleiches Thema wie Joker17177 bekomme auch „ (1242) No one IP configured“ im Log.
Geht weiter mit:
„Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().“
(1227) unhandled promise rejection: tokenObject is not defined
(1227) ReferenceError: tokenObject is not defined at judoisoftControll.getTokenFirst (/opt/iobroker/node_modules/iobroker.judoisoft/main.js:277:57) at process._tickCallback (internal/process/n

Ne Idee was wir falsch machen ? Die ip stimmt.

viele Grüße

**Comment by Apollon77** [comment]
Bitte am besten GitHub issues im Adapter Repo für Fehler anlegen und nicht hier kommentieren

**Comment by bambi-arch** [comment]
Super das es einen Adapter für Judo gibt! Gibt es schon einen Termin wann dieser nach npm zum installieren für den iobroker kommt? Danke im Voraus!

**Comment by Apollon77** [comment]
Please create an issue with the adapter to add them to stable repository ... in beta it is in when I remember

**Comment by MK222222** [comment]
> Ich habe auch den PIN um in die Einstellungsebene des Servicemechanikers zu kommen. Ist laut seiner Aussage bei jeder I-Soft Plus gleich...-;)

Hallo,

Kannst du mir den PIN zukommen lassen?
Danke im Voraus.

**Comment by joker17177** [comment]
Hallo!Der PIN sollte 5289 lauten.MfG: SvenAm 22.02.2023 um 01:49 schrieb MK222222 ***@***.***>:﻿

Ich habe auch den PIN um in die Einstellungsebene des Servicemechanikers zu kommen. Ist laut seiner Aussage bei jeder I-Soft Plus gleich...-;)

Hallo,
Kannst du mir den PIN zukommen lassen?
Danke im Voraus.

**Comment by MK222222** [comment]
Danke,Hat funktioniert 👌🏻Mit freundlichen Grüßen Michael Am 22.02.2023 um 17:22 schrieb joker17177 ***@***.***>:﻿
Hallo!Der PIN sollte 5289 lauten.MfG: SvenAm 22.02.2023 um 01:49 schrieb MK222222 ***@***.***>:﻿

Ich habe auch den PIN um in die Einstellungsebene des Servicemechanikers zu kommen. Ist laut seiner Aussage bei jeder I-Soft Plus gleich...-;)

Hallo,
Kannst du mir den PIN zukommen lassen?
Danke im Voraus.
