### ISSUE TITLE
Bahn

### ISSUE THREAD

**Issue by siggi85** [ioBroker/AdapterRequests#257]
An adapter for "deutsche Bahn" should be able to configure specific connections and stations and get informations about their state like delays etc.
You could alarm you when you have an delay, you can configure your alarm clock when the train has delay, you can show the actual state of your connection in vis, etc.

API from "deutsche Bahn" is available on https://developer.deutschebahn.com/store/ or https://data.deutschebahn.com/dataset/api-fahrplan. There are also some third party APIs and sites on the market (http://bahnreise-wiki.de/wiki/Fahrplanauskunft, https://dbf.finalrewind.org, etc).

**Comment by TA2k** [comment]
gibt es eine konkrekte API die Verspätungen anzeigt?

**Comment by siggi85** [comment]
Ich weiß leider nicht über welche API man am besten gehen sollte. Ich habe vor einiger Zeit dazu auch mal ein Thema in der FB ioBroker Gruppe geschrieben, und da haben einige auch kommentiert, dass die Bahn die Daten wohl bereitstellt.
Timetables unter https://developer.deutschebahn.com/store/ möglicherweise?!?

**Comment by TA2k** [comment]
Mit https://developer.deutschebahn.com/store/apis/info?name=Timetables&version=v1&provider=DBOpenData#!/default/get_fchg_evaNo  könnte man vielleicht verspätungen sehen. Aber das XML parsen macht keinen Spaß
`<timetable station="Berlin Hbf" eva="8011160">
  
  <s id="3754935158696263041-1909261335-10" eva="8011160">
        <ar ct="1909261449" l="1">
              <m id="r55280749" t="f" c="0" ts="1909260121"/>
        </ar>
  </s>
  
  
  <s id="4327365759713543038-1909261304-12" eva="8011160">
        <ar ct="1909261414" l="7"/>
  </s>
  
  
  <m id="i699394" t="i" from="1909060320" to="1911290920" ts="1909260912"/>
  
  
  <m id="i704517" t="i" from="1909161350" to="1909162300" ts="1909161352"/>
  
</timetable>`

**Comment by TA2k** [comment]
<timetable station="Berlin Hbf" eva="8011160">
  
  <s id="3754935158696263041-1909261335-10" eva="8011160">
        <ar ct="1909261449" l="1">
              <m id="r55280749" t="f" c="0" ts="1909260121"/>
        </ar>
  </s>
  
  
  <s id="4327365759713543038-1909261304-12" eva="8011160">
        <ar ct="1909261414" l="7"/>
  </s>
  
  
  <m id="i699394" t="i" from="1909060320" to="1911290920" ts="1909260912"/>
  
  
  <m id="i704517" t="i" from="1909161350" to="1909162300" ts="1909161352"/>
  
</timetable>

**Comment by ikkerus** [comment]
Hm. Ich habe gerade per Zufall diese API auf GitHub gefunden: https://github.com/highsource/delays-api

Scheint genau das zu sein, was wir brauchen. Nur weiß ich nicht genau, was die Datenquelle ist, die API scheint recht einfach via Amazon AWS anzusprechen zu sein?!

**Comment by flat1984** [comment]
Ich benutze den hafas-client: https://github.com/public-transport/hafas-client 
Dort sind auch die spezifischen Wrapper für verschiedene Dienste, ich nutze z.B. INSA für den Nahverkehr in Mitteldeutschland, dort werden auch die Verspätungen angezeigt. https://github.com/derhuerst/insa-hafas

**Comment by TA2k** [comment]
https://www.youtube.com/watch?v=r0bNIQWgvUE

**Comment by gaudes** [comment]
https://github.com/gaudes/ioBroker.fahrplan

**Comment by gaudes** [comment]
@siggi85 : Hi,

could this Request be closed with this adapter:

https://github.com/gaudes/ioBroker.fahrplan

Regards, Ralf

**Comment by siggi85** [comment]
@gaudes Yes I use this adapter already. This request can be closed.
