### ISSUE TITLE
Ical Calender, Series appointments

### ISSUE THREAD

**Issue by Henny4184** [ioBroker/AdapterRequests#258]
If you create an appointment in the Google Calendar as a serial date and then insert it into the Ical, everything is great. However, if you change one of the series appointments in a day because you don't have to work in the morning but in the afternoon, the appointment is changed in google but not in the Ical Calendar. There you sometimes have the appointment for the morning and that of the afternoon indoors. What can be done about it? There seem to be several of the problems. Is there a solution to this?

**Comment by Apollon77** [comment]
Please file this as bug in the ical adapter, it is no adapter request

**Comment by Henny4184** [comment]
How and where exactly do I have to do that?

**Comment by Apollon77** [comment]
Go to the GitHub page for the Adapter ioBroker/ioBroker.ical and create an issue there if nich already existing.
