### ISSUE TITLE
Bosch Home Connect

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/AdapterRequests#26]
https://forum.iobroker.net/viewtopic.php?f=24&t=3402

API Specs https://developer.home-connect.com/?q=docs/api/authorization/flow und Simulator!

Migrated from Trello with 2 votes

**Comment by arteck** [comment]
ich habe angefangen Informationen zu sammeln um einen Adapter zu entwickeln.. leider sieht es schlecht aus da die API zwar verfügbar ist aber leider nicht für alle... 
die Anbindung an iobroker somit zur Zeit ungewiss

**Comment by Apollon77** [comment]
Reine Developer bekommen Keys, aber die Frage ist wie es danach in die "breite Masse" (sprich zu den Usern) geht. Wenn das nicht geht, sage ich ehrlich das Entwicklungszeit in diesem Thema unsinn ist und wir andere Baustellen bedienen sollten. Sprich: Vorher klären unter welchen Bedingungen man es den Usern anbieten kann, sonst gar nicht erst anfangen.

FHEM ist seit knapp einem Jahr mit denen am Reden und Klären ... Letzter offizieller Stand: https://forum.fhem.de/index.php/topic,29353.msg509294.html#msg509294 ... Thread aber seit Ende 2017 geschlossen.

@arteck will mal versuchen bei den FHEM Leuten einen Status rauszubekommen.

Dann sehen wir weiter.

Ich bin mit @arteck in Kontakt dazu und dann sehen wir weiter. Wir halten hier aktuell.

@Interessenten: Jemand nen draht zu denen direkt als Firma? :-)

**Comment by Apollon77** [comment]
Das heisst: Jeder User muss sich nen eigenen API Key holen, dann für seine Geräte die Freischaltung anfordern ... und wir machen den Adapter ...

?!

**Comment by arteck** [comment]
zur Zeit sehe ich den Nutzen zu Programmieraufwand nicht .. man kann die Geräte auch per ifttt einbinden.

**Comment by xxNikoxx** [comment]
also ich hätte da Neuigkeiten. Ich habe einen Api key als Betatester über das Fhem forum bekommen und visualisiere damit schon  länger status, restlaufzeit etc. 
Nun ist es so das es im Fhem forum eine mitteilung gab. das die Api wohl zum 1.8 für alle geöffnet wird.

> ab 1.8.2018 geht das neue Developer Portal und somit auch das bereits angekündigte neue Zugangskonzept live, d.h. ab dieses Datum kann jeder registrierte Nutzer, der seinen eigenen HC Benutzernamen in seinem Developer User Account hinterlegt, mit seinen im HC-Account angebundenen Hausgeräten über eine „eigene“ HC API-Lösung kommunizieren. Die explizite Freischaltung der einzelnen FHEM-Developer ist somit ab diesem Zeitpunkt nicht mehr erforderlich. (Eine Freischaltung der Applikation ohne eine limitierte HC Benutzeranzahl ist nur dann für durch Home Connect geprüfte Applikationen möglich. Die Beantragung werden über einen s.g. Publication Request im Developer Account möglich sein und sind in erster Linie für geprüfte HC Partner vorgesehen). Zum 1.8. stellen wir damit auch das FHEM Beta-Programm ein.
> 
> Damit den Übergang reibungslos funktioniert, bitten wir Sie ab sofort die HC Benutzernamen mit den neuen Anmeldungen der Beta-Tester zukommen zu lassen. Zudem würden wir Sie bitten für die bereits freigeschaltenen  Developer Accounts die HC Benutzernamen bis spätestens 10.7 (gerne auch früher) nachzureichen. Dann würden wir die Daten bereits hinterlegen, damit am Stichtag 1.8 die Applikationen der FHEM-Nutzer ohne Unterbrechung funktionieren werden. 
> 
> Vielen Dank  
> 
> Freundliche Grüße,
> 
> Your Home Connect Developer Team

Gruß Niko

**Comment by Apollon77** [comment]
@arteck was denkst du, neuer Anlauf?

**Comment by arteck** [comment]
ne leider nein... bei mir haben sich paar Projekte dazwischen gedrängt..sry

**Comment by dna909** [comment]
Ich werde mich mal mit meinen spärlichen JS-Kenntnissen dran machen. Probleme werde ich aber bestimmt haben, bei den Server-Events. Das sieht mir etwas knifflig aus. Ich versuche erstmal ein Grundgerüst zu schustern und denn schaun wir mal. Wird aber sicherlich lange Zeit dauern.....

**Comment by foxriver76** [comment]
@dna909 done? ;-)
