### ISSUE TITLE
Solar Log Integration for Energy Management

### ISSUE THREAD

**Issue by ikkerus** [ioBroker/AdapterRequests#260]
**Solar Log Adapter**

Solar log is a company that integrates a lot of energy devices for a complete energy management for the users or companies home. They integrate solar panels, thermal heat pumps, batteries, inverters and many other devices into a Energy-Management-System. Every Devices Data are aggregated into Solar Log, so that with Solar Log ioBroker would be able to integrate a lot of vendors with just one adapter.

https://www.solar-log.com/en/

There is a JSON-Interface available for the Solar-Log Devices that can be found in the manual starting from page 300: https://www.solar-log.com/manuals/manuals/en_GB/SolarLog_Manual_4x_EN.pdf

An adapter for this would fil a gap, so e.g. heat pumps can also be integrated into ioBroker.

Thanks and in case of questions please file a comment.

**Comment by philoxio** [comment]
Do I understand you correctly that you would like to have the adapter below but with added functionalities?

https://github.com/forelleblau/ioBroker.solarlog

**Comment by forelleblau** [comment]
The gap should be filled allready: the 'open JSON-interface' is a part of the existing solarlog - adapter (it's the basic functionality). You will find the values described in the manual in the 'status' - channel:

![image](https://user-images.githubusercontent.com/44144152/67258526-6ac15080-f491-11e9-9cf0-e42b6a6cfd0f.png)

in case of needs of additional functionalities please open an issue on 
[https://github.com/forelleblau/ioBroker.solarlog](https://github.com/forelleblau/ioBroker.solarlog)

or post it on 

[https://forum.iobroker.net/topic/17036/projekt-iobroker-solarlog-adapter/](https://forum.iobroker.net/topic/17036/projekt-iobroker-solarlog-adapter/)  
(what you might found allready).

**Comment by Apollon77** [comment]
Cool, then I close here
