### ISSUE TITLE
JUDO iSoft Plus Adapter

### ISSUE THREAD

**Issue by ronnythomas** [ioBroker/AdapterRequests#265]
Hallo zusammen,

ich und sicher auch ein paar andere brauchen einen Adapter für den JUDO iSoft Plus. 
Er hat Lan Anschluss und es wurde schon einiges im Fhem gemacht. 
Kann das jemand bauen?

https://wiki.fhem.de/wiki/JUDO_iSoft_Plus
https://judo.eu/produkt/judo-i-soft-plus-vollautomatische-enthaertungsanlage/

VG Ronny

**Comment by DutchmanNL** [comment]
duplicate :)
https://github.com/ioBroker/AdapterRequests/issues/247
