### ISSUE TITLE
History Adapter mit mehr Informationen

### ISSUE THREAD

**Issue by Stormbringer11** [ioBroker/AdapterRequests#266]
Falls es möglich ist fände ich es sehr praktisch (vor allem bei größeren Systemen), wenn der History Adapter anstelle von „geändert von Javaskript Instanz“ die entsprechende Regel anzeigen würde.

**Comment by Apollon77** [comment]
Sorry. Das ist kein Adapter request. Es ist eine Feature Erweiterung für JavaScript im ersten Schritt und History im zweiten. Bitte feature request issues bei den Adaptern anlegen. Danke
