### ISSUE TITLE
Problem Zigbee adapter

### ISSUE THREAD

**Issue by Petest1** [ioBroker/AdapterRequests#267]
Hi,

i try to install a zigbee adapter, after install ioBroker i havec this error message

host.raspberrypi | 2019-10-27 11:52:36.547 | error | instance system.adapter.zigbee.0 terminated with code 1 ()
-- | -- | -- | --
Caught | 2019-10-27 11:52:36.547 | error | by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Caught | 2019-10-27 11:52:36.547 | error | by controller[0]: at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
Caught | 2019-10-27 11:52:36.547 | error | by controller[0]: at Module.load (internal/modules/cjs/loader.js:653:32)
Caught | 2019-10-27 11:52:36.547 | error | by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
Caught | 2019-10-27 11:52:36.547 | error | by controller[0]: at Module._compile (internal/modules/cjs/loader.js:778:30)
Caught | 2019-10-27 11:52:36.547 | error | by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/cc-znp/lib/ccznp.js:7:18)
Caught | 2019-10-27 11:52:36.547 | error | by controller[0]: at require (internal/modules/cjs/helpers.js:25:18)
Caught | 2019-10-27 11:52:36.546 | error | by controller[0]: at Module.require (internal/modules/cjs/loader.js:692:17)
Caught | 2019-10-27 11:52:36.546 | error | by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:562:25)
Caught | 2019-10-27 11:52:36.546 | error | by controller[0]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
Caught | 2019-10-27 11:52:36.546 | error | by controller[0]: Error: Cannot find module 'serialport'
Caught | 2019-10-27 11:52:36.546 | error | by controller[0]: ^
Caught | 2019-10-27 11:52:36.546 | error | by controller[0]: throw err;
Caught | 2019-10-27 11:52:36.546 | error | by controller[0]: internal/modules/cjs/loader.js:638

i do  lot of forum but i find no solution ....

**Comment by Apollon77** [comment]
Please open adapter related bugs or issues issues directly in the repo of the adapter

**Comment by Apollon77** [comment]
And when you do so please provide log from the adapter installation too (should be helpful in this case.)
