### ISSUE TITLE
Haus-Bus-Push-Button humidity sensor not viewable

### ISSUE THREAD

**Issue by Alletklar** [ioBroker/AdapterRequests#273]
The new haus-bus-multibutton http://haus-bus.de/ with a 2 way temp/humidty-sensor is working fine in ioBroker, except the option to read the data from the humidty-sensor. the temperature-sensor ist working and readable. I guess its because of the 2-way / one package sensor @ the same channel.

**Comment by Apollon77** [comment]
If there is already an adapter please open issue there. Here is for completely new adapters.
