### ISSUE TITLE
MQTT Problem Änderungen setzen

### ISSUE THREAD

**Issue by Sascha1983** [ioBroker/AdapterRequests#275]
Hi,
mein Problem ist, daß ich per MQTT den aktuellen Status übertragen bekomme. 
Sobald ich einen Schaltbefehl an den entsprechenden Topic sende, wird angezeigt, daß er angekommen ist, jedoch wird der Befehl nicht ausgeführt. Ich habe konkret versuche Zigbee Steckdosen Ein/Aus zu schalten per MQTT. Letztes Jahr ging das einwandfrei, jetzt leider nicht mehr... 
Hat jemand einen Tipp für mich??

**Comment by foxriver76** [comment]
Du solltest das Issue hier: https://github.com/ioBroker/ioBroker.mqtt/issues anlegen oder besser im Forum nachfragen. Hier geht es um Vorschläge für neue Adapter.

**Comment by foxriver76** [comment]
Ah und btw. ich schätze es liegt daran, dass du eingestellt hast, dass die States mit ack=true gesetzt werden. Die meisten Adapter reagieren hierauf nicht.
