### ISSUE TITLE
PV Anlage Solax Power

### ISSUE THREAD

**Issue by Schello805** [ioBroker/AdapterRequests#276]
Adapter für Photovoltaikanlage "Solax Power" https://www.solaxpower.com/de/.

**Comment by Apollon77** [comment]
Gibt es eine API? Irendwas um an Daten ranzukommen? Librares für nodejs oder python? Mehr Details bitte und Links

**Comment by Schello805** [comment]
Es gibt leider keine API, aber bisher schon mehrere Ansätze über andere Wege. 
https://community.home-assistant.io/t/solax-solar-inverter-setup-guide/48008
https://github.com/GitHobi/solax/issues/1

und hier noch den Link ins ioBroker Forum mit einer Lösung für symcon, die offenbar bei jemandem funktioniert. 
https://forum.iobroker.net/topic/13152/solax-photovoltaik-portal-in-iobroker

**Comment by Schello805** [comment]
Gibt immer noch keine Möglichkeit die Daten irgendwie in iobroker zu bekommen?

**Comment by DutchmanNL** [comment]
> Gibt immer noch keine Möglichkeit die Daten irgendwie in iobroker zu bekommen?

Hat dieses geraet kein ModBus wie die meisten derartigen Geräte ?

**Comment by chrkraus** [comment]
Gibt es eine eventuell eine Möglichkeit über die Solax Cloud zu gehen? Eventuell dort mal eine Anfrage stellen.

**Comment by Schello805** [comment]
> Gibt es eine eventuell eine Möglichkeit über die Solax Cloud zu gehen? Eventuell dort mal eine Anfrage stellen.

Wie oben schon verlinkt greift das Script auf die mobile cloudanwendung zu. Lokal hatte für einige Monate der Parser von iobroker funktioniert. Inzwischen nicht mehr.

**Comment by simatec** [comment]
Ich würde mich dabei machen und einen Adapter bauen. 
Es gibt eine API, die man für die Auswertung im iobroker nutzen kann.
[Solax_API_for_End-user_V1.0.pdf](https://github.com/ioBroker/AdapterRequests/files/6564985/Solax_API_for_End-user_V1.0.pdf)

Aktuell plane ich bei mir auch in diese Richtung eine PV Anlage auf das Garagendach zu bauen.

Im Moment habe ich allerdings noch keine Hardware.
Wenn also Interesse an einem Adapter besteht, könnt ihr mich gerne direkt anschreiben.

Es müsste mir dann für die Entwicklung jemand sein Token und SN zur Verfügung stellen.

VG simatec

**Comment by Schello805** [comment]
Also bei mir läuft die Anbindung mit dem Parser seit ca. 1 Jahr "relativ" stabil. Aber einfach war das nicht. Ein Adapter wäre da  echt toll!!!

**Comment by simatec** [comment]
Wie gesagt, im Moment mangelt es bei mir noch an Hardware. 
Mein Projekt ist aber gerade in Planung und wird sich demnächst bestellt. 

Ich würde mit dem Adapter schon anfangen, wenn wer bereit ist sein Token und seine Seriennummer zur Verfügung zu stellen. 

Das ganze ist natürlich nur bei mir lokal zum testen und wird vertraulich behandelt. 

Also bitte hier nicht einfach die Daten posten, sondern wenn bitte mich privat anschreiben.

**Comment by simatec** [comment]
Ich habe mich mal dran gesetzt und einen Adapter geschrieben.
Wer ihn testen möchte, kann das gerne über eine Github Installation tun und sein Feedback geben.

https://github.com/simatec/ioBroker.solax.git

**Comment by Wolfi311** [comment]
Werde testen baue Geräte die Anlage auf.
GIBT ES schon ein Thema im iobroker Forum von Dir?

**Comment by simatec** [comment]
Bisher gibt es dazu noch kein Thema.
Meine Anlage ist auch bestellt und wenn es gut läuft, dann kann ich am WE aufbauen.

**Comment by simatec** [comment]
Hier der Link ins Forum  ...
https://forum.iobroker.net/topic/45494/test-adapter-solax-0-1-x

**Comment by Wolfi311** [comment]
Seit heute ist meine Anlage komplett geliefert.
Bei erster Lieferung wahren beide PV Module zerstören.!

Hoffe auch das die Module diese oder Anfang nächster Woche auf Dach montiert bekomme.
Ein Zimmerman Kollege hilft Mir. 
Wechselrichter X1 600w  ist schon montiert und fix am Netz angeschlossen!

**Comment by ldittmar81** [comment]
@Apollon77 can be closed. Its stable

**Comment by MagicSven81** [comment]
Ich hatte selbiges Problem und bin dann auf folgendes Modul gestoßen welche mir alle Daten des Wechselrichters per MQTT in meinen ioBroker liefert. Und das auf Wunsch jede Sekunde

[Solax X1 X3 Mic Hybrid Modbus Adapter OpenWB MQTT RS485 TTL ESP32](Solax X1 X3 Mic Hybrid Modbus Adapter OpenWB MQTT RS485 TTL ESP32)

**Comment by simatec** [comment]
https://github.com/simatec/ioBroker.solax
