### ISSUE TITLE
Velux Active with Netatmo Request

### ISSUE THREAD

**Issue by fisch55** [ioBroker/AdapterRequests#278]
Es wäre schön wenn es für den Netatmo/Velux Active einen Adapter für IoBroker gäbe.

Hier gibt es bereits was auf GitHub

https://github.com/nougad/velux-cli/blob/master/velux-protocol.md

**Comment by TA2k** [comment]
Duplicate ? 
https://github.com/ioBroker/AdapterRequests/issues/244
