### ISSUE TITLE
Windows Server Essentials 2012 oder 2016 Adapter

### ISSUE THREAD

**Issue by Elektroniker0486** [ioBroker/AdapterRequests#279]
Wäre Coll wenn man ein Windows Server in ioBroker einbinden könnte.
Z.B.: Status der Festplatten, Freier Speicherplatz, Dienste die nicht gestartet sind, Benutzer, Onlinestatus, Updates? usw.

Könnte man da was machen?
Ich selbst habe ein Server 2016 laufen und würde mich zum testen zur Verfügung stellen.

> *created by ioBroker.info*

**Comment by Apollon77** [comment]
Gibts hier Details? APIs? Infos? Libraries?

**Comment by Alveran81** [comment]
Über die WMI Schnittstelle lassen sich alle Informationen eines Windows Server auslesen.
Diese ist standardisiert.

**Comment by peterbaumert** [comment]
Ich würde hier ganz einfach den SNMP Adapter nehmen und im Server den SNMP Dienst verwenden.

**Comment by mcm1957** [comment]
Ev. hilft hier auch der relativ neue nsclient adapter weiter. (-> latest repo)
-) cpu Ausalstung
-) Memory Auslastung
-) Diskauslastung
sollten bereits verfügbar sein.

Wünsche für andere Infos ev. asl issues im nsclient repo.

**Comment by mcm1957** [comment]
Da die angeführten Windows Versionen inzwischen outdated sind schließe ich hier mal.
Bitte bei Bedarf ein neues Issue eröffnen,
