### ISSUE TITLE
Tessan WLAN Steckdose / Smart Life

### ISSUE THREAD

**Issue by itstartedwithac64** [ioBroker/AdapterRequests#283]
ich suche einen Adapter, um eine WLAN Steckdose:
https://www.amazon.de/gp/product/B07VKK2W6L
in ioBroker einzubinden.
Die vom Hersteller gelieferte iPhone App zum schalten und verwalten lautet "Smart Life".

Wahrscheinliche ählich zum Meross-Adapter.

Danke

**Comment by sigi2345** [comment]
Tuya Adapter!
