### ISSUE TITLE
go-Echarger (Wallbox)

### ISSUE THREAD

**Issue by pmocdh** [ioBroker/AdapterRequests#284]
Hallo,
die Einbindung einer go-Echarger Wallbox wäre super, um die
Ladevorgänge zu steuern und die geladene Energie zu Protokollieren.

Infos und API gibt es hier: 
https://go-e.co/go-echarger-home/#jet-tabs-control-1273

Ich hoffe es gibt Interessierte, die das umsetzen können.
Danke

**Comment by MK-2001** [comment]
Habe ich mit dem https://github.com/MK-2001/ioBroker.go-e
