### ISSUE TITLE
Icloud Kalender anbindung

### ISSUE THREAD

**Issue by bug84** [ioBroker/AdapterRequests#285]
Ich würde mir einen Adapter wünschen, mit dem man den Icloud Kalender einbinden kann im normalen Tabellenlayout, so wie ich ihn auch offiziell dargestellt bekomme.
Leider funktioniert das einbinden per Iframe nicht (CSP) und über den Umweg Google möchte ich nicht gehen.
Ical auch keine Alternative, da dort nur Listen erstellt werden, keine Monatsübersicht.

Es wäre schön, wenn einer sowas erstellen würde...

Grüße
BUG84

**Comment by DutchmanNL** [comment]
> Ical auch keine Alternative, da dort nur Listen erstellt werden, keine Monatsübersicht.

der Ical adapter macht. das doch ? Also iCloud ==> Ical ==> ical adapter ==>. HTML Tabelle

**Comment by Apollon77** [comment]
Ich würde es wenn auch eher als ical erweiterung sehen ein "anderes html" zu nutzen - oder eigebtlich weil recht speziell kann man ein eigenes javascript nutzen um mit den Daten vom ical so ein html zu erstellen

**Comment by Apollon77** [comment]
Daher bitte in ical anlegen als feature request

**Comment by bug84** [comment]
Ok dann schreib ich’s da nochmal rein, danke
