### ISSUE TITLE
SIKU RV 30 DW PRO DUO WIFI Lüftersteuerung

### ISSUE THREAD

**Issue by Starcon79** [ioBroker/AdapterRequests#286]
Hallo,
ich benötige mal eure Hilfe. Letzten Monat habe ich bei mir einen Lüfter installiert und würde ihn jetzt gerne über Iobroker steuern. Leider gibt es noch keinen Adapter.
Es handelt sich um folgenden Lüfter: SIKU RV 30 DW PRO DUO WIFI:
[https://www.siku.at/produkte/dezentrale-wohnraumlueftung/siku-rv-30-dw-pro-duo-wifi](url) 
Dieser ist baugleich mit diesem Lüfter : Blauberg VENTO Expert DUO A30-1 W
[https://blaubergventilatoren.de/series/vento-expert-duo-a30-1-w#downloads](url)
Die Lüfter kommunizieren via UDP:
[ventoexpertduowsmarthousev11en2.pdf](https://github.com/ioBroker/AdapterRequests/files/3875992/ventoexpertduowsmarthousev11en2.pdf)

Ausserdem hab ich noch ein Python-Script auf Github gefunden welches den Lüfter in Homeassistant einbindet:
[https://github.com/aglehmann/pyEcovent](url)

Und hier noch der Link zum Forum:
[https://forum.iobroker.net/topic/26036/hilfe-l%C3%BCftersteuerung-%C3%BCber-iobroker/4](url)

Wäre toll wenn jemand daraus einen Adapter machen könnte.

**Comment by dma7** [comment]
Servus!

Schon eine Lösung dafür gefunden? 

Ich habe auch den SIKU Lüfter und musste feststellen, dass die Software Schnittstelle anders ist als die oben verlinkte von Blauberg. Ich habe von https://raumluft-shop.de ein Dokument mit der Beschreibung der API erhalten und sehe, dass die wesentlich anders ist. Deckt sich auch mit den Mitschnitten der Kommunikation zwischen der App und dem Gerät, die ich mit Wireshark gemacht habe.

**Comment by Starcon79** [comment]
Hallo,
Ich habe leider noch keine Lösung da ich selber nicht programmieren kann. Habe echt gedacht das beide gleich sind da ich meinen Lüfter auch mit der Blauberg App bedienen kann. 
Aber da du ja jetzt die originale API hast könntest du sie ja hier einstellen vielleicht  findet sich ja doch noch jemand. Oder wir fragen nochmal im iobroker-forum nach Unterstützung.  Wäre echt super wenn wir das noch in Iobroker bringen könnten.

**Comment by dma7** [comment]
Ok, kein Problem. 

Als schnelle Lösung habe ich erstmal ein Python-Skript entwickelt, mit dem man die Basics steuern kann: An/aus, Lüftungsmodus (Luft rein/raus/alternierender Betrieb) und die Geschwindigkeit. Das Skript rufe ich momentan aus einem JavaScript Code auf und es funzt perfekt. 
Ich habe es mir vorgenommen, mich die nächsten Tage und Wochen mit der Adapter-Entwicklung etwas zu befassen, weil ich das eigentlich auch als Adapter einbinden will.

Gruß,
Daniel

**Comment by madjack84** [comment]
Guten Morgen @dma7 : Bist du weiter gekommen? ich hab ein Node Script geschrieben und so ziemlich das Gleiche implementiert. Ich spiele mit dem Gedanken nun einen Adapter zu bauen... möchte aber ungern Doppelarbeit machen.

Dabei ist Blauberg, Vento, Oxxify und RL das gleiche Produkt. Ich hab den Oxxify

**Comment by dma7** [comment]
Hi madjack84

leider habe ich noch nichts Vorzeigbares, weil ich in den letzten Monaten sehr wenig Zeit hatte.

Der Adapter steht aber ganz oben auf der Wunschliste, weil ich gerne den Zustand der Lüfter als Datenpunkt in iobroker hätte. Mein Skript funktioniert zwar sehr gut, aber es liefert nicht den Schaltzustand der Lüfter... ich könnte zwar das Python Skript dahingehend erweitern und dann dessen Result in einem JS Skript in beliebige Datenpunkte schreiben, aber schick ist anders in meinen Augen. 

Ich bin allerdings noch etwas im Lernmodus bzgl. iobroker, insbesondere was die Adapter-Entwicklung angeht. Hatte zuvor jahrelang FHEM laufen. Deswegen gibt's noch nichts.

Grüße
dma

**Comment by madjack84** [comment]
Hallo @dma7
Soll ich dir meinen Service schicken? Der bildet alles auf mqtt ab. Mit dem mqtt Client Adapter hast du dann alles in iobroker als Datenpunkte
Hab heute mal ein guthub repo eröffnet und taste mich vor :/

**Comment by Starcon79** [comment]
Hallo @madjack84 ,
wirklich klasse das du einen Adapter  bauen möchtest.  Zur Unterstützung zwecks testen usw. stehe ich gerne zur Verfügung.

**Comment by dma7** [comment]
> Hallo @dma7 Soll ich dir meinen Service schicken? Der bildet alles auf mqtt ab. Mit dem mqtt Client Adapter hast du dann alles in iobroker als Datenpunkte Hab heute mal ein guthub repo eröffnet und taste mich vor :/

Schick mal rüber, danke schon mal dafür. Vllt komme ich damit schneller weiter. 

Auf das Testangebot komme ich sicher noch zurück :-)

**Comment by madjack84** [comment]
[rl_UDP2MQTT.zip](https://github.com/ioBroker/AdapterRequests/files/7842381/rl_UDP2MQTT.zip)

hier schonmal das node file und die Service description zur Kopie in /lib/systemd/system/rl_UDP2MQTT.service
das file kannst du mit `node rl.js` ausführen. Im js oder service File solltest du die IP Adresse für MQTT und die IP Adresse für deinen Lüfter austauschen.

**Comment by toralt** [comment]
Hier gibt es jetzt ein funktionierendes Plugin für die homebridge:
https://github.com/PaulMT/homebridge-blauberg-vento

Vllt kann man damit ja auch direkt für den ioBroker was basteln?

**Comment by mcm1957** [comment]
Please note that https://github.com/madjack84/ioBroker.ventilation is despite the repository name *NOT* an ioBroker adapter.

**Comment by andispammonyer** [comment]
Is someone able to takeover the existing HomeAssistant Adapter to build an iobroker one or write a new one from scratch by using the UDP description?

**Comment by mcm1957** [comment]
Maybe THI adapter could work:

Repo https://github.com/intellicasa/ioBroker.blauberg-ventilation
Lastet https://github.com/ioBroker/ioBroker.repositories/pull/3060

**Comment by intellicasa** [comment]
Hi together,

@mcm1957 is right. I've developed an ioBroker adapter for Blauberg Vents, using the manufactorers UDP protocoll. If there are other vents from Siku using the same protocoll they probably might work as well.

**Comment by mcm1957** [comment]
Adapter has been released

Repo https://github.com/intellicasa/ioBroker.blauberg-ventilation

Please create a issue at adapter repository in case of problems or improvementrequests.
