### ISSUE TITLE
Twinkly (Wifi RGB Lights) Adapter (Christmas is coming)

### ISSUE THREAD

**Issue by W0RSCHD** [ioBroker/AdapterRequests#288]
Hi,
would be great if anyone is able to add an Adapter for Twinkly Wifi Lights. (www.twinkly.com)
I found on Homeassistant Forum that someone managed to use it via python script,
perhaps that helps a bit for development.

https://community.home-assistant.io/t/twinkly-christmas-lights/31354

Thank you very much

**Comment by mrMuppet** [comment]
Home Assistant is working on it... perhaps someone can port their adapter to iobroker.

**Comment by Zefau** [comment]
https://xled-docs.readthedocs.io/en/latest/rest_api.html

**Comment by siggi85** [comment]
It is not an adapter, but I can control basic functions of my twinkly with this script in iobroker. Maybe it is helpful until a developer make a real adapter.
https://forum.iobroker.net/topic/38713/twinkly-basisfunktionen-mit-iobroker-steuern

**Comment by patrickbs96** [comment]
I've created a functioning script which works like an adapter
https://github.com/patrickbs96/ioBroker.twinkly

**Comment by Apollon77** [comment]
@patrickbs96 cool, but maybe do not name the repo "Like the other adapter repos" ... else Users will try to install it like an adapter :-))

**Comment by Apollon77** [comment]
If you want support in how to transform that into an adapter (if you have it that way it is just "a bit different"), just tell and we will support

**Comment by patrickbs96** [comment]
@Apollon77 oh sorry, didn't think about that... I've changed the repo name :-)
That would be great, I'll try and make sense of the documentation for creating adapters first

@siggi85 Könntest du den Link in deinem Forumbeitrag ändern, danke :-) (https://github.com/patrickbs96/script.twinkly)

**Comment by Apollon77** [comment]
Best use the adapter-creator to create abschwören. Then it should be relatively clear ;-)

**Comment by patrickbs96** [comment]
thanks, I found that last night already :-) implemented my code and correcting it according to WebStorms error messages at the moment. Main challenge will be creating the Admin page I guess. I'll have a look at other adapters for examples.

By the way, is it possible to implement another adapter into the code? I'd like to check if the Wifi-Lights are actually available or not. At the moment I'm giving the user the option to add a boolean state (e.g. from ping or tr-064) to the configuration to do the checks. But it would be nicer if I could do the checks directly in the adapter.

**Comment by patrickbs96** [comment]
@Apollon77 the adapter is finalized and all the warnings from the adapter-check have been corrected. I guess the testing phase can start now :-)

**Comment by RkcCorian** [comment]
Hello together, I found this adapter and I like it. Is there some docu how to write e.g. ```color_config```. I write on it but it does not have an effect for me.

Greetings!

**Comment by patrickbs96** [comment]
@RkcCorian Hey there, in the [README](https://github.com/patrickbs96/ioBroker.twinkly/blob/master/README.md) file you can see which settings currently can be set. I only detected `color_config` as a new option through Sentry. It's currently not picking up that information on my Twinkly's. Just added it as an [issue](https://github.com/patrickbs96/ioBroker.twinkly/issues/91), I'll look into it.

**Comment by patrickbs96** [comment]
@Apollon77 Das Issue kann eigentlich geschlossen werden :-)

**Comment by ldittmar81** [comment]
@Apollon77 can be closed. Its stable
