### ISSUE TITLE
Alias-Verwaltungsadapter

### ISSUE THREAD

**Issue by DocGame69** [ioBroker/AdapterRequests#293]
Wie ich im Forum gelesen habe kommt der "Normalanwender" (mich eingeschlossen) nicht optimal mit den Konfigurieren der Alias-ID's klar. Der Grundgedanke ist genial, die Konfigurierung der einzelnen ID's für mich aber zu hoch.
Wäre es nicht möglich einen adapter mit folgenden Einstellmöglichkeiten zu programmieren:
1: Anlegen eines neuen Alias mit entsprechender Verzeichnissstrucktur.
2: Anwählbarkeit der zu dieser Alias-ID gewünschten ID, States usw,
3: Etitierfunktion um schon vorhandene Alias-ID's neue States unw. zuzuordnen.

Habe mich vielleicht etwas Laienhaft ausgedrückt, ich hoffe, man versteht trotzdem was ich meine.
Das ganze könnte natürlich noch um weitere Punkte ausgebaut werden.

**Comment by Apollon77** [comment]
Iobroker.devices existiert auf GitHub als Alpha. Rest kommt ggf in Admin mit rein.
