### ISSUE TITLE
Roth EnergyLogic Touchline

### ISSUE THREAD

**Issue by misery** [ioBroker/AdapterRequests#296]
I like to request support for EnergyLogic of Roth.
The API is private but is really simple as some people reverse-engineered it. Data can be fetch in local network without cloud.

I will create a python script later to fetch all data. But I don't know how to add it to an adapter.

https://www.roth-werke.de/de/software.htm

Someone added a script for openhab.
https://community.openhab.org/t/suggestion-for-controlling-my-underfloor-heating-roth-touchline/31565

Some reverse-engineered the API and added an app:
https://play.google.com/store/apps/details?id=dk.schmack.hometemps

**Comment by DutchmanNL** [comment]
> I will create a python script later to fetch all data. But I don't know how to add it to an adapter.

if you know the logic of the API, I can assist porting the information to an adapter !
What we need is understand how the API is called, what data is in it etc.

This must be translated then to ioBroker objects and states based on the adapter template.
Happy to corporate here if you like !

**Comment by misery** [comment]
Yeah, that would be great. Can you use a python script or would you re-implement it in some other script?

**Comment by DutchmanNL** [comment]
> Yeah, that would be great. Can you use a python script or would you re-implement it in some other script?

I would reimplement it in Javascript based on NodeJS framework depending on wha we need (to make it full compatible, so basically port the python part).

But I am not a python pro :/, so I need to understand what we do in the API.
Are you German en from foreign country ? We could join a teamspeek session or discuss by telegram if you like

**Comment by Apollon77** [comment]
It is normally not that hard to convert ... python is "just another programming language" :-)

And if it is really mainly HTTP requests and parsing it should be not that problematic ;-)

**Comment by misery** [comment]
> Are you German en from foreign country ? We could join a teamspeek session or discuss by telegram if you like

You got mail. ;-)

**Comment by misery** [comment]
Hier mal meine Zusammenfassung vom reverse-engineering....

**Comment by misery** [comment]
```
curl -s -k  -X 'POST' -H 'Content-Type: text/xml' --data-binary $'<body><item_list_size>7</item_list_size><item_list><i><n>isMaster</n></i><i><n>totalNumberOfDevices</n></i><i><n>hw.HostName</n></i><i><n>R0.SystemStatus</n></i><i><n>R0.DateTime</n></i><i><n>R0.kurzID</n></i><i><n>R0.Safety</n></i></item_list></body>' "http://192.168.x.y/cgi-bin/ILRReadValues.cgi"
```

Der obige Befehl bedeutet folgendes.

Ein HTTP-POST-Request um Daten zu LESEN. Dabei muss der HTTP-Header 'Content-Type: text/xml' gesetzt sein.
Der Request geht an folgende URL: http://192.168.x.y/cgi-bin/ILRReadValues.cgi

```
<body>
    <item_list_size>7</item_list_size>
    <item_list>
        <i><n>isMaster</n></i>
        <i><n>totalNumberOfDevices</n></i>
        <i><n>hw.HostName</n></i>
        <i><n>R0.SystemStatus</n></i>
        <i><n>R0.DateTime</n></i>
        <i><n>R0.kurzID</n></i>
        <i><n>R0.Safety</n></i>
   </item_list>
</body>
```

* <item_list_size> ist hier die Anzahl an folgenden Einträgen unter <item_list>.
* Die Einträge müssen immer mit <i><n> anfangen und mit </i></n> aufhören. Ansonsten meldet die EnergyLogic einen Parserfehler.
* Die Einträge sind die "Parameter", die man abfragen möchte.



**Dies wäre eine Antwort auf den Request oben:**
```
<?xml version="1.0"?>
<body>
  <item_list_size>7</item_list_size>
  <item_list>
    <i>
      <n>isMaster</n>
      <v>1</v>
    </i>
    <i>
      <n>totalNumberOfDevices</n>
      <v>10</v>
    </i>
    <i>
      <n>hw.HostName</n>
      <v>ROTH-0111F6</v>
    </i>
    <i>
      <n>R0.SystemStatus</n>
      <v>0</v>
    </i>
    <i>
      <n>R0.DateTime</n>
      <v>1576104926</v>
    </i>
    <i>
      <n>R0.kurzID</n>
      <v>81</v>
    </i>
    <i>
      <n>R0.Safety</n>
      <v>0</v>
    </i>
  </item_list>
</body>
```
* Wieder ist <item_list_size> die Anzahl die folgenden Einträge in <item_list>
* Zu den angefragten Parametern vom Request sind nun <v> </v> Einträge dazugekommen. Dies sind die Values dazu.


* isMaster: 1 bedeutet die EnergyLogic ist als Master registiert, ansonsten 0.
            Dies ist eine Einstellung wenn man mehrere EnergyLogic hat und diese miteinander über Funk verbunden hat. Master/Slave stellt man anhand von Tasten an den Geräten ein.

* totalNumberOfDevices: Anzahl der Räume bzw. Thermostaten
* hw.HostName: Der Hostname, der im LAN verwendet wird.
* R0.SystemStatus: Keine Ahnung
* R0.DateTime: Keine Ahnung
* R0.kurzID: Eine eindeutige ID der EnergyLogic im LAN. Die ID wird auch bei den Thermostat-Abfragen zurückgegeben. Daran kann man erkennen, an welcher EnergyLogic das Thermostat über Funk angeschlossen ist. Dies kommt dann vor wenn mehrere hat und einen Master/Slave-Verbund hat. Dann fragt man z.B. an ID 81 mittels dieser Requests ab. Die Daten der Thermostate enthaltet aber z.B. ID 161. Daran sieht man, dass an ID 81 eine zweite EnergyLogic verbunden ist und dieser die Daten nur weiterleitet.
* R0.Safety: Keine Ahnung

**Comment by misery** [comment]
```
curl -s -k  -X 'POST' -H 'Content-Type: text/xml' --data-binary $'<body><item_list_size>12</item_list_size><item_list><i><n>G0.OPMode</n></i><i><n>G0.RaumTemp</n></i><i><n>G0.SollTemp</n></i><i><n>G0.WeekProg</n></i><i><n>G0.name</n></i><i><n>G0.TempSIUnit</n></i><i><n>G0.SollTempStepVal</n></i><i><n>G0.SollTempMinVal</n></i><i><n>G0.SollTempMaxVal</n></i><i><n>G0.OPModeEna</n></i><i><n>G0.kurzID</n></i><i><n>G0.ownerKurzID</n></i></item_list></body>' "http://192.168.x.y/cgi-bin/ILRReadValues.cgi"
```

Der obige Befehl bedeutet folgendes.

Ein HTTP-POST-Request um Daten für ein Thermostat zu LESEN. Dabei muss der HTTP-Header 'Content-Type: text/xml' gesetzt sein.
Der Request geht an folgende URL: http://192.168.x.y/cgi-bin/ILRReadValues.cgi
```
<body>
    <item_list_size>12</item_list_size>
    <item_list>
        <i><n>G0.OPMode</n></i>
        <i><n>G0.RaumTemp</n></i>
        <i><n>G0.SollTemp</n></i>
        <i><n>G0.WeekProg</n></i>
        <i><n>G0.name</n></i>
        <i><n>G0.TempSIUnit</n></i>
        <i><n>G0.SollTempStepVal</n></i>
        <i><n>G0.SollTempMinVal</n></i>
        <i><n>G0.SollTempMaxVal</n></i>
        <i><n>G0.OPModeEna</n></i>
        <i><n>G0.kurzID</n></i>
        <i><n>G0.ownerKurzID</n></i>
    </item_list>
</body>
```

* <item_list_size> ist hier die Anzahl an folgenden Einträgen unter <item_list>.
* Die Einträge müssen immer mit <i><n> anfangen und mit </i></n> aufhören. Ansonsten meldet die EnergyLogic einen Parserfehler.
* Die Einträge sind die "Parameter", die man abfragen möchte.
  Beachten muss man hier, dass alle Thermostate einfach mit G und einer Zahl definiert werden.
  Der erste Thermostat ist G0, der zweite G1 usw.
  Die Anzahl der Thermostate konnte man mit dem vorherigen Request mittels <totalNumberOfDevices>
  auslesen. Man kann also dann leicht bei 10 <totalNumberOfDevices> mit 10 Requests
  die Thermostate G0 bis G9 abfragen.


**Dies wäre eine Antwort auf den Request oben:**
```
<?xml version="1.0"?>
<body>
  <item_list_size>12</item_list_size>
  <item_list>
    <i>
      <n>G0.OPMode</n>
      <v>0</v>
    </i>
    <i>
      <n>G0.RaumTemp</n>
      <v>2058</v>
    </i>
    <i>
      <n>G0.SollTemp</n>
      <v>2100</v>
    </i>
    <i>
      <n>G0.WeekProg</n>
      <v>0</v>
    </i>
    <i>
      <n>G0.name</n>
      <v>Wohnzimmer</v>
    </i>
    <i>
      <n>G0.TempSIUnit</n>
      <v>0</v>
    </i>
    <i>
      <n>G0.SollTempStepVal</n>
      <v>0</v>
    </i>
    <i>
      <n>G0.SollTempMinVal</n>
      <v>500</v>
    </i>
    <i>
      <n>G0.SollTempMaxVal</n>
      <v>3000</v>
    </i>
    <i>
      <n>G0.OPModeEna</n>
      <v>1</v>
    </i>
    <i>
      <n>G0.kurzID</n>
      <v>1</v>
    </i>
    <i>
      <n>G0.ownerKurzID</n>
      <v>81</v>
    </i>
  </item_list>
</body>
```

* Wieder ist <item_list_size> die Anzahl die folgenden Einträge in <item_list>
* Zu den angefragten Parametern vom Request sind nun ```<v> </v>``` Einträge dazugekommen. Dies sind die Values dazu.

* G0.OPMode: 0 bedeutet "Heizung im Raum an" und 2 bedeutet "Heizung im Raum aus".
             Dies bedeutet KOMPLETT aus. Auch wenn Soll-Temperatur nicht erreicht.

* G0.RaumTemp: Aktuelle Raumtemperatur
               Angabe ist vierstellig. Beispiel: 2058 bedeutet 20,58 Grad.
    
* G0.SollTemp: Soll-Temperatur
               Angabe ist vierstellig. Beispiel: 2100 bedeutet 21,00 Grad.

* G0.WeekProg: Angabe welches Wochen-Programm aktiv ist. Man kann verschiedene
               Programme direkt konfigurieren. Bisher aber nicht benutzt.

* G0.name: Name vom Raum

* G0.TempSIUnit: Einheit der Temperaturen vom RaumTemp und SollTemp.
                 0 bedeutet Celcius und 1 Fahrenheit.

* G0.SollTempStepVal: Keine Ahnung
* G0.SollTempMinVal: Keine Ahnung
* G0.SollTempMaxVal: Keine Ahnung
* G0.OPModeEna: Keine Ahnung
   
* G0.kurzID: Eindeutige ID des Thermostats an einer EnergyLogic.
* G0.ownerKurzID: Die ID der EnergyLogic, an dem das Thermostat angeschlossen ist.
                  Dies ist die ID vom Http-Request für R0.kurzID.

**Comment by misery** [comment]
Schreibende Zugriffe laufen über Http-Get-Requests.

Hierbei müssen die Parameter URL-Kodiert werden, da dann auch Umlaute und Leerzeichen für Raumnamen verwendet werden können.

Der Parameter beginnt wieder mit G und der 0 wie bei den lesenden Zugriffen. Also G0 für den ersten Raum, G1 für den zweiten....

Namen setzen:
```curl "http://192.168.x.y/cgi-bin/writeVal.cgi?G0.name=Mein+Name"```

Soll-Temperator setzen:
```curl "http://192.168.x.y/cgi-bin/writeVal.cgi?G1.SollTemp=2150"```

Heizung in dem Raum komplett anschalten/abschalten:
```curl "http://192.168.x.y/cgi-bin/writeVal.cgi?G0.OPMode=2"```
```curl "http://192.168.x.y/cgi-bin/writeVal.cgi?G0.OPMode=0"```

**Comment by DutchmanNL** [comment]
Hast du Telegramm?

**Comment by misery** [comment]
I wrote my own EnergyLogic 2 MQTT bridge: https://github.com/misery/HeatingMqttBridge
So this can be used by all smart home systems...
