### ISSUE TITLE
Rain Bird Irrigation System

### ISSUE THREAD

**Issue by adandl** [ioBroker/AdapterRequests#298]
Hello!
I saw that an integration to Home-Assistent for Rain Bird already exists.
Not sure, but can this integration be migrated to ioBroker by someone?

I'm basically looking for an option to set a "rain delay" by ioBroker and have  the status of the sprinklers available for visualisation.

Here is the link to the home-assistant integration I would like to have in IO Broker :)

https://www.home-assistant.io/integrations/rainbird

Hope this is a valid request - If needed I can offer testing and translation to German as well

Kind regards

Albert

**Comment by StrathCole** [comment]
Hello,
just added a new adapter for Rain Bird (LNK Wifi) for testing.
https://github.com/StrathCole/ioBroker.rainbird

**Comment by StrathCole** [comment]
@Apollon77 Hier auch eine Version im latest repo

**Comment by Apollon77** [comment]
super, dann mache ich hier zu., Danke!!
