### ISSUE TITLE
求美的中央空调适配器

### ISSUE THREAD

**Issue by lighu36** [ioBroker/AdapterRequests#299]
美的中央空调适配器网关：ccm15

https://cac.midea.com/product/Control-Device/Network-Control/CCM15

**Comment by Apollon77** [comment]
Could you please update the Adapter Request in english?
Is there any API available? what exactly you would like to control using ipbroker?

**Comment by lighu36** [comment]
> 您能用英语更新适配器请求吗？
> 有没有可用的API？您到底想使用ipbroker控制什么？

我不会更新适配器，能否根据Haier的api改编一下，想用iobroker控制空调的开关，制热，制冷，等功能
Haier的api（https://github.com/instalator/ioBroker.haier）

**Comment by SchumyHao** [comment]
@lighu36  CCM15有协议么？ 是否有介入其他智能家居平台的例子？

@Apollon77  CCM15 is a central AC controller. @lighu36 want to add this device support into ioBroker.
But no API doc for now. I'll update if it avaliable.

**Comment by lighu36** [comment]
> @ lighu36 CCM15有协议么？是否有介入其他智能家居平台的例子？
> 
> @ Apollon77 CCM15是中央交流控制器。@ lighu36希望将此设备支持添加到ioBroker中。
> 但是暂时没有API文档。如果有的话，我会更新。

https://bbs.hassbian.com/thread-1275-1-1.html
有一个大佬接入了ha，上面是地址，有没有可能把海尔的适配器修改一下支持美的

**Comment by SchumyHao** [comment]
@Apollon77 
This device is intergrated in Hass

https://github.com/houselabs/home-assistant-mideaccm/blob/master/custom_components/ccm15/climate.py

**Comment by lighu36** [comment]
> @Apollon77 
> 
> This device is intergrated in Hass
> 
> 
> 
> https://github.com/houselabs/home-assistant-mideaccm/blob/master/custom_components/ccm15/climate.py
> 
> 

看github发现了这个项目，妖哥看看美的中央空调ccm15设备能不能通过tasmota接入
https://github.com/arendst/Tasmota/pull/8859

**Comment by lighu36** [comment]
> @Apollon77 
> 
> This device is intergrated in Hass
> 
> 
> 
> https://github.com/houselabs/home-assistant-mideaccm/blob/master/custom_components/ccm15/climate.py
> 
> 

看github发现了这个项目，妖哥看看美的中央空调ccm15设备能不能通过tasmota接入
https://github.com/arendst/Tasmota/pull/8859

**Comment by lighu36** [comment]
看github发现了这个项目，妖哥看看美的中央空调ccm15设备能不能通过tasmota接入
arendst/Tasmota#8859

**Comment by lighu36** [comment]
> @ Apollon77
> 此设备集成在Hass中
> 
> https://github.com/houselabs/home-assistant-mideaccm/blob/master/custom_components/ccm15/climate.py

看github发现了这个项目，妖哥看看美的中央空调ccm15设备能不能通过tasmota接入
arendst/Tasmota#8859

**Comment by mcm1957** [comment]
If still relevant please open a new request in ENGLISH using english character set - especially for the title.
Currently the infoamtion is hard or not at all readable.
