### ISSUE TITLE
DoorBird

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/AdapterRequests#3]
http://forum.iobroker.net/viewtopic.php?f=23&t=3881

Link zur API: https://www.doorbird.com/de/api

Migrated from Trello with 5 votes.

**Comment by Apollon77** [comment]
LDittmar posted in Trello: https://github.com/ldittmar81/ioBroker.doorbird

**Comment by BuZZy1337** [comment]
@ldittmar81 whats going on? :grinning:

**Comment by Apollon77** [comment]
@BuZZy1337 kann das eigentlich zu?

**Comment by BuZZy1337** [comment]
Yes, adapter ist mittlerweile in latest repo.
