### ISSUE TITLE
Adapter für EMS-ESP - Heizungsansteuerung Buderus etc.

### ISSUE THREAD

**Issue by OXERY** [ioBroker/AdapterRequests#302]
Als kostengünstige Alternative zur Buderus KM200 gibt es die EMS-ESP, mit der man über den Service-Jack die Heizung steuern kann. (Bosch, Buderus, Nefit, Junkers und Sieger)
Ich habe es bisher in MQTT am laufen, das haut auch soweit hin - allerdings werden viele Werte als JSON geliefert, sodass man sie nicht sehr komfortabel verändern kann..
Für Domoticz und Home Assistant gibt es bereits Plugins.

https://github.com/proddy/EMS-ESP

**Comment by icxcube** [comment]
Hallo,
hätte auch großes Intresse an dem Adapter.
Habe mir  das getway von [bbqkees ](https://bbqkees-electronics.nl/) bestellt werde es versuchen in den nächsten Tagen über iobroker und MQTT zum laufen zu bringen. Das wird schon eine große Herausforderung für mich, da iobroker für mich ziemlich Neuland ist.
Also wäre das echt nicht schlecht wenn einer den Adapter erstellen könnte.
Würde auch die Hardware ggf. zur Verfügung stellen.

**Comment by bbqkees** [comment]
@tp1de created an adapter with support for EMS-ESP: https://github.com/tp1de/ioBroker.ems-esp

**Comment by tp1de** [comment]
Bitte daran denken, dass der Adapter den ESP32 und API V3 braucht.
Wenn der km200 parallel ausgelesen werden soll, dann dringend tx delay in den ems-esp Settings setzten (60 Sekunden).
Der Adapter ist noch nicht im ioBroker repository und muss über Github installiert werden.

**Comment by tp1de** [comment]
Ich habe einen Forum-Beitrag erstellt, falls jemand Intersse hat den Adapter zu testen.
[EMS-ESP Adapter](https://forum.iobroker.net/topic/45862/neuer-adapter-ems-esp-f%C3%BCr-bosch-heizungen)

**Comment by ldittmar81** [comment]
https://github.com/tp1de/ioBroker.ems-esp
