### ISSUE TITLE
360 S5 Saugroboter

### ISSUE THREAD

**Issue by tobiasw83** [ioBroker/AdapterRequests#306]
Hi,

ein Adapter für die 360 Saugroboter wäre toll. Vielleicht lässt sich der Xiaomi abwandeln??

Danke
Tobias

**Comment by tobiasw83** [comment]
360 S5 Saugroboter 
Verbindung: 2,4 Ghz Wlan 
Anbieter : 360 AI
Link : https://smart.360.cn/cleanrobot/en/s5/index.html

**Comment by ginvibe** [comment]
ich hab den S6 in benutzung, ein Adapter wäre echt super. 

Daten: 

**360 S6 Saubroboter**
Verbindung: 2,4 Ghz Wlan
Anbieter: 360 AI
Link: [360](https://smart.360.cn/cleanrobot/en/s6/index.html)

**Comment by markus2701** [comment]
ich habe auch den 360 S5

**Comment by HypoChonder1971** [comment]
ich würde mich auch sehr über einen Adapter für den 360 S6 freuen

**Comment by king-cake** [comment]
Ich hab auch den 360 s6 und würde den gern per adapter steuern.

**Comment by markus2701** [comment]
> Ich hab auch den 360 s6 und würde den gern per adapter steuern.
> 
> Wahrscheinlich kann man hier aufsetzen:
> https://github.com/bmachuletz/amcv360RequestRecorder

bekomme das nicht hin. In der App wird dann immer Netztwerk Fehler angezeigt.

**Comment by ginvibe** [comment]
> > Ich hab auch den 360 s6 und würde den gern per adapter steuern.
> > Wahrscheinlich kann man hier aufsetzen:
> > https://github.com/bmachuletz/amcv360RequestRecorder
> 
> bekomme das nicht hin. In der App wird dann immer Netztwerk Fehler angezeigt.

bei mir selbiges

**Comment by Babola123** [comment]
Ein Adapter für den 360 wäre Super. Hab den S7

**Comment by 20silencer04** [comment]
Ich habe eine 360 S6 würde ihn auch gerne per Adapter Steuern.

**Comment by tobiasw83** [comment]
Some News?

**Comment by lars-dev** [comment]
anything?

**Comment by lil-pete** [comment]
Habe einen 360 S5. Wäre über einen Adapter auch sehr dankbar. Könnte für Testzwecke behilflich sein. 👍

**Comment by fabiomaticus** [comment]
I have robot vacuum cleaner 360 S5. News for this?

**Comment by Futtel24** [comment]
Hallo, ich habe aud den 360 S6 und wäre super dankbar für einen Adapter !

**Comment by mtm87** [comment]
Hallo, auch ich habe Interesse an einem Adapter für den 360 Staubsauger

**Comment by mtm87** [comment]
> Ich hab auch den 360 s6 und würde den gern per adapter steuern.
> 
> Wahrscheinlich kann man hier aufsetzen:
> https://github.com/bmachuletz/amcv360RequestRecorder

Ich habe das Auslesen hin bekommen mit dem iPhone, leider weis ich nun nichts damit anzufangen...
Bei Interesse kann ich gerne die Daten bereitstellen.

**Comment by ginvibe** [comment]
Der Sauger erstellt bei der Erst Konfiguration ein WLAN, die App auf dem Smartphone wählt sich in dieses WLAN rein. Nach dem Eintragen von den WLAN Daten des eigenen Routers baut der Sauger seine Verbindung zu den China Servern auf und die Steuerung ist über die App möglich. 

Ich weiß nicht ob das hilft, aber schaden tut es bestimmt nicht :-)

**Comment by mtm87** [comment]
Hallo zusammen,

Es gibt auch eine Webseite mit weiteren Informationen
http://open.app.360.cn/dev/docapi

**Comment by tobiasw83** [comment]
Gibt es neue Informationen ob solch ein Adapter entstehen kann???

**Comment by canim60** [comment]
wäre auch definitiv interessiert und ne kleine spende

**Comment by nolimitek** [comment]
Bitte das wäre klasse hab auch den S6 . Spende wäre auch dabei :-)

**Comment by Mc261** [comment]
Ich habe auch den 360 S6 und würde mich über einen Adapter freuen!

**Comment by steefan85** [comment]
Ein Adapter für den 360 S6 wäre toll. Würde unterstützen so weit ich kann.

**Comment by lueschi** [comment]
Ich habe ebenfalls einen360 S9 (S6 Pro) und würde mich über einen Adapter freuen. Bei Spenden bin ich nat. dabei.

**Comment by ldittmar81** [comment]
Ich hoffe ihr habt alle oben gevotet, denn nur die Votes zählen und nicht die Anzahl der Kommentare. Hier nochmal die Erklärung https://github.com/ioBroker/AdapterRequests#how-to-use-this

**Comment by nowi967** [comment]
Hab gevotet. :-)

**Comment by BastiX456** [comment]
Ich wäre auch sehr dankbar. Bei Spenden bin ich dabei.

**Comment by TA2k** [comment]
Mit welcher App wird der gesteuert

**Comment by BastiX456** [comment]
360Robot

**Comment by farshis** [comment]
https://apps.apple.com/us/app/botslab/id1527541684
Botslab

**Comment by TA2k** [comment]
Ich benötige noch schnell ein account mit Roboter drin
tombox2020@gmail.com

**Comment by ckoeber83** [comment]
Ich habe meine 360 S5 nun mit Alexa Sprachassistenten verbunden:
![FB_IMG_1668412666680.jpg](https://user-images.githubusercontent.com/52466072/201612250-63965208-caab-492f-b4e2-59da5fadef2c.jpg)

Dann im iobroker über den [alexa2](https://github.com/Apollon77/ioBroker.alexa2/blob/master/README.md) Adapter taucht dieser dann unter den Smart Home Devices mit seiner Device ID auf.

![IMG_20221114_090618.jpg](https://user-images.githubusercontent.com/52466072/201611013-16541047-12dd-4183-8156-f6374f974538.jpg)

Über den powerState kann man diesen nun wenigstens aus dem ioBroker via true=Starten und false=Stop und zurück zur Ladestation.
Mehr geht da aber leider nicht, da entweder die CN360 API nicht mehr Daten liefert oder Alexa nicht mehr zur Verfügung stellt.

VG

**Comment by TA2k** [comment]
Login geht soweit ich bräuchte nur noch Geräte
https://github.com/TA2k/ioBroker.botslab360

**Comment by TA2k** [comment]
Nur ein Login ist ausreichend

**Comment by nolimitek** [comment]
> Nur ein Login ist ausreichend

Hast ein Mail.

Lg

**Comment by TA2k** [comment]
https://forum.iobroker.net/topic/60046/test-adapter-360-staubsauger-botslab

**Comment by TA2k** [comment]
Status Abruf geht jetzt und man kann sich die Karte holen aber umwandeln in ein Bild ist noch unbekannt.

**Comment by nolimitek** [comment]
Hi

Besten Dank.

Habs auch schon in das iobroker  Forum geschrieben .
Bekomme einen Json Fehler aktuell

botslab360.0
2022-11-18 09:00:04.903 warn State
"botslab360.0.360TY030103023203.remote.setLevel-wind" has no existing
object, this might lead to an error in future versions

botslab360.0
2022-11-18 08:51:46.917 error SyntaxError: Unexpected end of JSON input at
JSON.parse (<anonymous>) at Socket.<anonymous>
(/opt/iobroker/node_modules/iobroker.botslab360/main.js:280:35) at
Socket.emit (node:events:513:28) at addChunk
(node:internal/streams/readable:315:12) at readableAddChunk
(node:internal/streams/readable:289:9) at Socket.Readable.push
(node:internal/streams/readable:228:10) at TCP.onStreamRead
(node:internal/stream_base_commons:190:23)

botslab360.0
2022-11-18 08:51:46.916 error SyntaxError: Unexpected end of JSON input

Am Do., 17. Nov. 2022 um 22:40 Uhr schrieb TA2k ***@***.***>:

**Comment by mcm1957** [comment]
@nolimitek 

Es gibt nun das github repo

**https://github.com/TA2k/ioBroker.botslab360**

Bitte Probleme / Wünsche zu diese Adapter als issue dort eintragen.

Dieses issue sollte nur mehr solange offen bleiben bis der neue Adapter released wurde (oder - was ich nicht hoffe -) die Entwicklung eingestellt wird.

**Comment by mcm1957** [comment]
request to add to lastest seems to be pending:
https://github.com/ioBroker/ioBroker.repositories/pull/2038

**Comment by mcm1957** [comment]
Adapter has been released to repository (latest).

Please report and issue or feature request at the adapters repository (https://github.com/TA2k/ioBroker.botslab360)

@TA2k  Thanks for your work

**Comment by BastiX456** [comment]
Der Adapter ist super. Vielen Dank für die gute Arbeit!
