### ISSUE TITLE
Senec Home Battery V2.1 Adapter

### ISSUE THREAD

**Issue by jkoeber** [ioBroker/AdapterRequests#307]
Hi, neuer Adapter für Senec Home Batterie:
https://github.com/jkoeber/ioBroker.senec

vg
Jo.

**Comment by Apollon77** [comment]
Ok cool. Aber warum dann bei den requests eingestellt? ;-)) ab damit ins Forum das noch User testen j d er bald ins Repo kommt ;-))

**Comment by mcm1957** [comment]
Repo: https://github.com/nobl/ioBroker.senec
