### ISSUE TITLE
Selve Commeo Rollladen

### ISSUE THREAD

**Issue by mrfenyx** [ioBroker/AdapterRequests#308]
Hi,
wäre es möglich einen Adapter für die Selve Commeo Rollladen zu erstellen? Diese werden durch einen [USB-RF Gateway (Stick)](https://www.selve.de/de/service/software-updates/service-entwicklungstool-commeo-usb-rf-gateway/) betrieben. Eine API/Specifications dafür gibt es auch: 
[SELVE XML Spezifikation - Rev. 2.0.2 - GER.pdf](https://github.com/ioBroker/AdapterRequests/files/4008329/SELVE.XML.Spezifikation.-.Rev.2.0.2.-.GER.pdf)
Der Stick selbst ist ziemlich teuer (~€100) aber ich kann gerne beim Testen helfen.
Danke!

**Comment by Apollon77** [comment]
Versuch mal den ham Adapter mit https://github.com/tfohlmeister/homebridge-selve

**Comment by mrfenyx** [comment]
Ich habe es damit versucht aber der homebridge-selve Adapter ist sehr limitiert und viele Optionen fehlen, das wichtigste davon wäre "State". Ich betreibe die Rollläden jetzt durch FHEM und den fhem-Adapter aber es wäre schön diese direkt in iobroker zu haben.

**Comment by andi-willi** [comment]
Hallo zusammen - ich wäre auch sehr an einem Adapter interessiert. Ich habe mein smarthome komplett über ioBroker integriert, nur die Selve Rolläden fehlen noch.

**Comment by Fortune95** [comment]
Hallo zusammen, wäre auch sehr an einem Adapter interessiert...

**Comment by mbecker-selve** [comment]
Würde für die Entwicklung kostenfrei SELVE RF-USB Gateway, Antriebe, Aktore, Sensoren und Fernbedienung zur Verfügung stellen.

**Comment by Rintrium** [comment]
Hallo,
unter https://forum.iobroker.net/topic/47779/neuer-adapter-selverf/1 könnt ihr meinen Adapter finden. 

Viele Grüße
Rintrium

**Comment by ldittmar81** [comment]
@Rintrium Please request repo addition ... details see https://github.com/ioBroker/ioBroker.repositories

**Comment by Rintrium** [comment]
Submitted pull request [https://github.com/ioBroker/ioBroker.repositories/pull/1585](url)

**Comment by ldittmar81** [comment]
https://github.com/Rintrium/ioBroker.selverf
