### ISSUE TITLE
Frontier Silicon Undok (Lidl Silvercrest Multiroom Speaker and others)

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/AdapterRequests#31]
Ähnliche Implementierungen für andere Sprachen/Plattformen siehe unter
https://github.com/openhab/openhab1-addons/tree/master/bundles/binding/org.openhab.binding.frontiersiliconradio
https://github.com/flammy/fsapi
https://github.com/z1c0/FsApi

Migrated from Trello with 0 votes

**Comment by santa81** [comment]
Wird das eventuell weiter verfolgt?

**Comment by Apollon77** [comment]
Bisher hat sich noch kein Entwickler gemeldet der Zeit und die Hardware hat ... Das kann sich ändern. Interessenten bitte Thumbs up nutzen

**Comment by Pantoffelknilch** [comment]
Im Moment gibt es den Urbanears Baggen, der mal für eine UVP von 450€ verkauft werden sollte, für 82,99 € im Abverkauf (siehe [hier](https://www.mydealz.de/deals/urbanears-baggen-multiroom-lautsprecher-60w-wlan-bluetooth-aux-in-airplay-chromecast-spotify-connect-7-sender-speicherplatze-1586178)).

Der hat wohl auch einen Chip von Frontier Silicon und lässt mittels der fsapi bedienen, was die Integration in ioBroker theoretisch relativ einfach machen sollte (siehe [hier](https://old.reddit.com/user/dertypvonmydealz/comments/gogf89/urbanears_baggen_api/))

Ich habe gerade mehrere davon als Multiroom-System für verschiedene Räume gekauft und würde beim Rumprobieren mithelfen. Meine Entwickler-Fähigkeiten in ioBroker hören aber leider bei relativ simplen Blockly-Projekten auf. Aber vielleicht wäre das hier ja für den ein oder anderen ein Anreiz, sich so ein Ding zuzulegen, was preislich auf Silvercrest-Niveau liegt, aber klanglich eher Richtung Sonos?

**Comment by SF1980** [comment]
Schau mal hier, das läuft bei mir seit über einem Jahr 

https://forum.iobroker.net/topic/6688/adapter-für-internetradios-silvercrest-grundig-sono-aldi-lidl-etc/13

**Comment by halloamt** [comment]
Oder der hier, den ich vor ein paar Tagen angefangen habe https://github.com/halloamt/ioBroker.frontier_silicon
Noch kann er nicht viel, aber das Grundgerüst steht schon. Umschalten auf andere Sender klappt.

**Comment by xdaamg** [comment]
Habe den Adapter von @halloamt im Zusammenspiel mit einem Dual IR6 im Einsatz. Die wesentlichen Funktionen (Ein-/Aus-/Umschalten, Lautstärke, Modi wechseln etc.) lassen sich damit steuern.

**Comment by Diginix** [comment]
Läuft bei mir auch perfekt mit einem Medion MD 87090 Radio.
Hatte bisher ein Skript um rudimentär ON/OFF, Vol, Mute steuern zu können. Nun kann ich Modus wechseln, gespeicherte Sender wählen. Alles auch per Alexa wenn man die Buttons zB über den iot Adapter an Amazon weitergibt.

**Comment by Menne01** [comment]
Hi, ich habe da ein Problem mit den Presets. Wenn ich in der VIS ein Preset ausgewählte habe. ist alle soweit I.O. Der Preset geht von Orange zu Grün über. Wähle ich ein nächstes aus, bleibt das vorige Grün. Weil das Recall einfach auch True bleibt, anstatt auf false zu gehen. Wäre es im Code möglich, das dies geändert wird?

![Screenshot 2024-10-12 at 11-06-05 vis](https://github.com/user-attachments/assets/9f7c8c7a-4e6c-4c77-9986-b471e4fd8ba3)

![Screenshot 2024-10-12 at 11-16-48 objects - iobroker](https://github.com/user-attachments/assets/671a99cc-9fee-4bda-a95a-74b9dac5bc9b)

**Comment by pdbjjens** [comment]
Dieser Adapter (ioBroker.frontier_silicon) wurde mit Einverständnis des Autors ( [@hallo-amt](https://forum.iobroker.net/uid/17290) ) im März 2023 zur Wartung an iobroker-community-adapters übertragen.

Neues GitHub Repo: https://github.com/iobroker-community-adapters/ioBroker.frontier_silicon

Bitte das bisherige [repo](https://github.com/halloamt/ioBroker.frontier_silicon) nicht mehr für GitHub-Installation, Issues oder PRs benutzen. Es wurde mittlerweile archiviert (read-only).

Ich habe die Betreuung übernommen. 

@Menne01 
Im Forum gibt es einen neuen Thread [https://forum.iobroker.net/topic/66890/test-adapter-frontier_silicon-v0-3-x-latest](https://forum.iobroker.net/topic/66890/test-adapter-frontier_silicon-v0-3-x-latest) bei dem solche Fragen gestellt werden können/sollten.

@Apollon77 
Bitte diesen Adapter Request schließen, da ein entsprechender Adapter (ioBroker.frontier_silicon) bereits seit Oktober 2020 existiert.
