### ISSUE TITLE
OPC UA

### ISSUE THREAD

**Issue by dotti-ba** [ioBroker/AdapterRequests#310]
Hi,

da ich keinen AdapterRequest dazu gefunden hab, mach ich doch mal zur Übung einen auf :-)

Hier hat schon mal jemand agefangen.
https://github.com/ioBroker/ioBroker.opcua

Installation manuell:
iobroker url "https://github.com/ioBroker/ioBroker.opcua" --debug

LG

Klaus

**Comment by Apollon77** [comment]
Kannst du bestimmt gern übernehmen. Schreib mal bluefox an

**Comment by GermanBluefox** [comment]
Server or client functionality?

**Comment by ldittmar81** [comment]
Can be closed... Its on latest
