### ISSUE TITLE
WIZ Connected lights

### ISSUE THREAD

**Issue by OE5PON** [ioBroker/AdapterRequests#311]
Please integrate Adapter for "WIZ Connected" Lights
https://www.wizconnected.com/en/oem/
More information request by E-Mail to europe@wizconnected.com

**Comment by TomSC1984** [comment]
It would be great !! Pls integrate an Adapter

**Comment by CoHoAppel** [comment]
WiZ is the entry-level line of Signify (Philips) Hue. Signigy is not offering integration, so it would be great if this can be done by using ioBroker. With brands like Osram LIGHTIFY being discontinued this would be a great addition.

**Comment by crazycusti** [comment]
i have interest too

**Comment by Rushmed** [comment]
I am interested too.

**Comment by DutchmanNL** [comment]
No documentation for API available at all, will try to contact the vendor we will if they are coorperative fir integration

**Comment by arminf82** [comment]
Would be awesome!

**Comment by biker1602** [comment]
Ich habe auch großes Interesse und sage schon mal Danke für eure Mühe

**Comment by KrX3D** [comment]
Hi i would be interested too.

i found this for openhab: https://community.openhab.org/t/overhaul-and-rebmission-of-wiz-lighting-binding/89828/127

and this: https://www.npmjs.com/package/@suisse00/wiz-local-control

**Comment by einarmiger0815** [comment]
I'm interested too!

**Comment by arminf82** [comment]
Would be cool! How can I help? Have to lamps for testing and can do python.

**Comment by stoegge** [comment]
Wäre ganz genial. Zumal diese Leuchtmittel einiges günstiger sind als Hue. etc

**Comment by disaster123** [comment]
Here is my Adapter - have fun: https://github.com/disaster123/ioBroker.wizconnect

**Comment by mcm1957** [comment]
@disaster123 
Thanks for your work.

Please request your adapter to be added at iob repositories if  no problems exist after initial tests.

**Comment by disaster123** [comment]
@mcm1957 Thanks - but i might need some help. 

First of all the initial and main work was done by @basti85goe here https://github.com/basti85goe/iobroker.wizconnect 9 month ago. So also the copyright of this code is with him.

I found his code back in november or december and squashed some bugs, added more devices and made it work for me under docker.

No i idea if i'm in the position of requesting to add the adapter to the iob repo. Not sure about copyright or problems as well... who can help?

**Comment by mcm1957** [comment]
The original code was published under MIT license.. So any further use firther use should be legal. But of course the first step would be to contact the original maintainer a.nd tio ask wether he will finish the adapter etc..

You can get gelp for sure at iobroker forum or telegram channels iobroker entwicklung or iobroker adapter development starters.

I m on holliday this week so supporting by me is limited.i suggest to ask for help and links at forum or telegram at the moment.

**Comment by disaster123** [comment]
I asked him here: https://github.com/basti85goe/ioBroker.wizconnect/issues/2 but i also got no further response here https://github.com/basti85goe/ioBroker.wizconnect/issues/1 - weeks ago...

**Comment by DutchmanNL** [comment]
> I asked him here: [basti85goe/ioBroker.wizconnect#2](https://github.com/basti85goe/ioBroker.wizconnect/issues/2) but i also got no further response here [basti85goe/ioBroker.wizconnect#1](https://github.com/basti85goe/ioBroker.wizconnect/issues/1) - weeks ago...
> 
> So i've no idea how to proceed.

I would suggest to publish your working version & mention the original repo/developer in your readme.

**Comment by disaster123** [comment]
I've no idea why you react in such an aggresive and offensive way. If you read my comment i refer to https://github.com/basti85goe/ioBroker.wizconnect/issues/1 which was Dec 02 2022 and yes this is weeks ago.

I just wanted to help the community and no i won't start any request now - would be great if you could do this so everyone can benefit from your great work.

But please keep in mind there is no need to ask you - it's only an act of being nice, respectful and kindness. The MIT license allows todo this as long as the original author is mentioned in the README, ...

Have fun and be nice. Just my 2 cents and THX.

**Comment by mcm1957** [comment]
@basti85goe 
Thanks for the work you spent to implement wizconnect devices.

Currently the adapter https://github.com/basti85goe/ioBroker.wizconnect is still in an alpha state (at least in regard to the infrastructure / integration to ioBroker in general). According to github there was no development within the last 9 months - at least not visible for the public.

As there is general interest in this adapter **please let us know if you are still working on this adapter and you plan to finish / publish it within a reasonable timeframe and to request an addition to the official repositories.** Before adding the adapter to the repositories a formal review will be done. Please let us know if you are willing to do changes suggested there and to maintian the adapter in future (at least as seen at this time - time an interest can change in future of course :-) ) too. **If yes, please let us know the timeframe you think this can be done.**

Currently i.e. the readme has not been written to provide a general description of the adapter. In addition the adapter checker (https://www.iobroker.dev/adapter-check) lists several actions to be done, i.e.

  | [E518] "@alcalzone/release-script" is used, but ".releaseconfig.json" not found
  | [E300] Not found on travis. Please setup travis or use github actions (preferred)
  | [E606] Current adapter version 0.0.2 not found in README.md
  | [W171] "common.title" is deprecated in io-package.json
  | [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
  | [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
  | [W170] "common.keywords" should not contain "iobroker, adapter, smart home" io-package.json
  | [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
  | [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
  | [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)

If you need any help to adapt the code / environment for Integration into the official repositories I and others will try to help you. Please feel free to ask here or better in the ioBroker forum or on telegram (https://t.me/+gsX-e8k4mLtmZjZk or / and https://t.me/ioBroker_development).

McM

**Comment by mcm1957** [comment]
Just for Info:
Development is work in progress again.
Further updates will follow depending on status of work.

**Comment by mcm1957** [comment]
New adapter location: https://github.com/disaster123/ioBroker.signifylights

**Comment by mcm1957** [comment]
reqeust for latest: https://github.com/ioBroker/ioBroker.repositories/pull/2268

**Comment by mcm1957** [comment]
adapter listed at latest
