### ISSUE TITLE
Garmin API für Iobroker geeignet ?

### ISSUE THREAD

**Issue by poweruser0815** [ioBroker/AdapterRequests#312]
Hallo, ich habe heute eine Info bekomme, dass es eine Gamin API gibt https://developer.garmin.com/health-api/overview/. Ich bin mir nicht sicher, ob die kostenlos nutzbar ist. Wäre es damit ggf, möglich einen Adapter für iobroker zu entwickeln ?

[](url)

**Comment by foxriver76** [comment]
> Are there any further maintenance fees or services charges?
> 
> No, the Garmin Health API is completely free for enterprise partners.

Könnte man als ioBroker GmbH anfragen, als Privatperson schwierig, hatte ich früher schon mal geschaut.

**Comment by drtp** [comment]
Fände einen Adapter spannend, mit dem ich über meinen Garmin Edge 830 den Zustand meiner Garmin Varia UT800 und meines Varia RTL 511 auslesen kann, wenn das Fahrrad in der Garage steht. Hatte es schon ein paar Mal, dass das Licht an war und dadurch die Akkus leergesogen wurden.

**Comment by karlheinz0502** [comment]
Ich fände so einen Adapter ebenfalls toll

**Comment by DickenSerm** [comment]
Wäre auch an einem Adapter interessiert.

**Comment by Timee79** [comment]
Also ich hätte hier auch starkes Interesse.

**Comment by Apollon77** [comment]
@DickenSerm @Timee79 Tja ... warum posted Ijr dann hier und klickt nicht oben auf "Thumbs up"? Der Post ist unsichtbar wenn man sich nur die "Thimbs up" anschaut

**Comment by TA2k** [comment]
Kann ich mir anschauen. Brauch aber ein account mit gerät bitte via forum melden
https://forum.iobroker.net/user/tombox

**Comment by n3roGit** [comment]
> Kann ich mir anschauen. Brauch aber ein account mit gerät bitte via forum melden https://forum.iobroker.net/user/tombox

Ich könnte auch einen bereitstellen

**Comment by TA2k** [comment]
Die offizielle api bekommt man nur nach einem Zulassungsprozess die api via app ist relativ kompliziert

**Comment by TA2k** [comment]
Ich habe mal was gebaut was ein paar Daten abruft aber ich benötige accounts mit echten geraten um die Daten zu erweitern

https://forum.iobroker.net/topic/59413/test-adapter-garmin

Es wird node v18 benötigt zum installieren

**Comment by mcm1957** [comment]
Request to add to latest repo seems to be pending:
https://github.com/ioBroker/ioBroker.repositories/pull/2034

**Comment by mcm1957** [comment]
Adapter nun im repository verfügbar (latest)

Bitte alle Issues und Feature Requests im Adapterverzeichnis eintragen (https://github.com/TA2k/ioBroker.garmin)

@TA2k Danke für deine Arbeit
