### ISSUE TITLE
Amazon dash button

### ISSUE THREAD

**Issue by MathiasJZ** [ioBroker/AdapterRequests#315]
ich würde mich über einen neuen Amazon dash button freuen, bzw den alten mal aus der Repro nehmen.
1. Dash buttons wurden von Amazon aus dem Programm genommen.
2. Die Instanz läßt sich nicht mehr installieren.

**Comment by Apollon77** [comment]
Bitte das issue mit Details zu Fehlern wegen Installation beim existierenden Adapter öffnen.
