### ISSUE TITLE
Keine Verbindung Ozmo 900

### ISSUE THREAD

**Issue by Leprechaun91** [ioBroker/AdapterRequests#316]
Hey,

Also ich komme nicht über das gelbe Lämpchen hinaus. Ich habe einen Ozmo 900.

**Comment by Apollon77** [comment]
Um was genau geht es hier? Ist es ein bestehender Adapter? Wenn ja bitte Issue dort öffnen!

Klingt gerade nicht nach einem Adapter Request für einen neuen Adapter.
