### ISSUE TITLE
Aqara HomeKit Hub

### ISSUE THREAD

**Issue by RoberTo1111** [ioBroker/AdapterRequests#318]
Hallo zusammen,

fuer die auslaufenden Mija Hubs gibt es bereits einen Adapter. Fuer die bereits und in Zukunft nur noch verfuegbaren Aqara Homekit leider noch nicht. Mit der neuen APP ist das auslesen des Dev Keys leider nicht moeglich. Es waere schoen wenn der jetzige Adaapter um die Moeglichkeit des Keyauslesens erweitert werden koennte wie beim Tuya Adapter z.B.

**Comment by Apollon77** [comment]
Dann bitte ein issue beim Bestands_Adapter öffnen ... ?!

**Comment by ldittmar81** [comment]
@RoberTo1111 ist das hier was du brauchst? https://github.com/lasthead0/ioBroker.xiaomi-gateway3
