### ISSUE TITLE
Panasonic Aquarea H-Serie Adapter (Heisha)

### ISSUE THREAD

**Issue by gregor-samosir** [ioBroker/AdapterRequests#319]
Es gibt hier bei GitHub ein sich schnell entwickelndes Projekt
https://github.com/Egyras/HeishaMon

HeishaMon bietet über 90 Status-, Temperaturmeldungen und Modi und bisher 15 Kommandos über MQTT zum Monitoring und zur Steuerung der Aquarea H-Serie Wärmepumpen an. HeishaMon ist ein auf Wemos basierende Hardware mit serieller Anbindung an die Wärmepumpe und kann den Cloud Adapter TAW-1 vollständig ersetzen. Es findet keinerlei Eingriff in Hard- oder Software der Wärmepumpe statt.

IOBroker erfahrene könnten da sicher helfen bei der Entwicklung eines Adapters für IOBroker.
Der Adapter in IOBroker soll auch dem nicht so techniknahen Anwender von IOBroker das Überwachen und Steuern seiner H-Serien Wärmepumpe erleichtern. 

Anregungen können gerne noch in das Projekt einfließen.

Über den Slack ist die Gruppe um das Projekt gut zu erreichen. Wir sind international in Projekt.
Ein Link zum Chat findet sich auf der Readme Seite.

**Comment by Apollon77** [comment]
Warum nicht den MQTT Adapter nutzen ?!

**Comment by gregor-samosir** [comment]
> Warum nicht den MQTT Adapter nutzen ?!

im MQTT sind bereits alle Daten, kein Problem. Vielleicht gibt es Interesse da etwas drüber zu setzen, damit der nicht so versierte Anwender den Überblick behalten kann.
Habe da an sowas in der Art wie den SonOff Adapter gedacht, der auch MQTT nutzt und die Menge an Informationen strukturiert aufbereitet.

**Comment by DutchmanNL** [comment]
> IOBroker erfahrene könnten da sicher helfen bei der Entwicklung eines Adapters. Anregungen können gerne noch in das Projekt einfließen.

Nicht wirklich du verwechselst da 2 Sachen.
Diese project macht reverse engineering, das hat nix mit iobroker oder Erfahrung zu tun dafuer brauch man leute die messages decrypten koennen und Verstehen was da hin und her geschickt wird.

Die andere Sache ist iobroker, wie du bereits sagst können 15 Sachen ueber MQT gemacht werden und damit 55 nicht.
Diese 15 Sachen können per MQTT nach iobroker (entweder das oder halt adapter aller sonoff).

Also 2 Möglichkeiten, man übernimmt die MQTT Geschichte von dem Project. Oder die logic dahinter fuer nen nicht MQTT dedicated ioBroker connector/adapter

**Comment by gregor-samosir** [comment]
> Die andere Sache ist iobroker, wie du bereits sagst können 15 Sachen ueber MQT gemacht werden und damit 55 nicht.
Diese 15 Sachen können per MQTT nach iobroker (entweder das oder halt adapter aller sonoff).

Den Satz verstehe ich jetzt nicht. Es gibt 70 bereits dekodierte Statusmeldungen und 15 implementierte Kommandos. Ich suche auch niemanden der bei HeishaMon im Team mitmacht, sondern jemanden, der das aus IOBroker Sicht "netter" als nur im MQTT weiterverwendet.

Sorry, wenn ich mich dar nicht klar ausgedrückt habe. Ich würde jedenfalls nicht in einem anderen Projekt versuchen Entwickler für das eigene zu rekrutieren.

**Comment by Apollon77** [comment]
Ah ok :-) Macht Sinn

**Comment by gregor-samosir** [comment]
Wer sich mit dem Adapter beschäftigen möchte meldet sich bitte über den Slack chat im Projekt. Wir stellen den Wemos D1 inklusive der Anbindung an die Wärmepumpe selbstverständlich zur Verfügung.
Von Vorteil wäre selbst eine Auarea Serie H Wärmepumpe zu haben. Unter Insidern gerne auch Heisha genannt.

**Comment by DutchmanNL** [comment]
Ich kann nicht versprechen alles end to end zu implementieren aber helfe gerne mit

Wo soll ich mich melden ?

**Comment by gregor-samosir** [comment]
Über die Projektseite oben auf den Link zum Slack Chat gehen.
Kurz vorstellen damit wir wissen um was es geht, und dann sehen wir, wie es weiter geht.
[https://github.com/Egyras/HeishaMon](url)

**Comment by DutchmanNL** [comment]
Ich habe mich in die Slack Gruppe eingeklinkt und werde mich diesem anehmen.
Basis ist das Modul, welche man im project entwikkerld auf ESP basis, native mittels MQT einbinden zu koennen.

Dazugehoerig structuren usw muessen durch den adapter realisiert werden

**Comment by gregor-samosir** [comment]
Aus meiner Sicht kann die Adapter Anfrage geschlossen werden.
Nachdem ich mich weiter damit beschäftigt habe bin ich der Meinung, das der Kreis der Interessenten doch der klein ist. Und die Anforderungen so unterschiedlich, das es mit einem Adapter nicht getan ist.

Für meinen Teil habe ich inzwischen eine Kaskadensteuerung in Node-Red realisiert. Wenn jemand daran Interesse hat gebe ich da gerne meine Erfahrungen weiter.
