### ISSUE TITLE
Hoover washing maschine

### ISSUE THREAD

**Issue by MrMadracer** [ioBroker/AdapterRequests#321]
Looking for an adapter to bring the Hoover Wasching and dryer machine into iobroker. They have OneFi and using an ESP for connection to the Wizard App. Not sure if an API is available.

**Comment by Apollon77** [comment]
Are there more details? Links? published APIs? other libraries that allow to control it?

**Comment by MrMadracer** [comment]
unfortunately I cant find anything about the API. 
Here is a Link to the APP it self.
https://play.google.com/store/apps/details?id=it.hoover.wizard&hl=de
and details about the Wizard
http://wizardservice.candy-hoover.com/

I hope that will help.

**Comment by Solilord** [comment]
Ich werde mir auch demnächst eine Hoover Waschmaschine mit WLAN kaufen.

Ich habe mal eine Art WIP API für das Candy Simply-Fi gefunden.
Hoover ist ja gemeinsamer Konzern mit Candy.

https://www.postman.com/explore/template/7373/candy-simply-fi

Inwiefern das klappt kann ich aktuell nicht sagen.

**Comment by MrMadracer** [comment]
> Are there more details? Links? published APIs? other libraries that allow to control it?

I got these details via email.

Ich werde mir auch demnächst eine Hoover Waschmaschine mit WLAN kaufen.

Ich habe mal eine Art WIP API für das Candy Simply-Fi gefunden.
Hoover ist ja gemeinsamer Konzern mit Candy.

https://www.postman.com/explore/template/7373/candy-simply-fi

Inwiefern das klappt kann ich aktuell nicht sagen.

**Comment by Solilord** [comment]
Problem: Die neuen Hoover haben nicht mehr one touch oder Simpli fi sonder sind alle in der neuen hOn App integriert. Und das scheint ein komplett anderes system zu sein.
Ich habe auch eine neue Hoover mit der hOn App. Aber das funktioniert alles nicht :/

**Comment by MrMadracer** [comment]
> Problem: Die neuen Hoover haben nicht mehr one touch oder Simpli fi sonder sind alle in der neuen hOn App integriert. Und das scheint ein komplett anderes system zu sein.
> Ich habe auch eine neue Hoover mit der hOn App. Aber das funktioniert alles nicht :/

Na das ist ja spitze, Diese App ist mit keinem deiner Geräte kompatibel. Trotz das alle Smartphones aktuell sind. Danke für den Tipp, dann besorg ich mir doch noch schnell eine von den älteren, da die alte Maschine demnächst ausfallen wird.

**Comment by Solilord** [comment]
Also an sich klappt das mit der hON App sehr gut. Ich kann meine WM einbinden, Starten, einstellen und die Assistenten zum waschen laufen auch super. Die Weiterentwicklung und Fehlerbehebung seitens der Entwickler läuft auch super.

Nur leider gibts eben keine API :/

**Comment by TA2k** [comment]
Was ist der Unterschied zwischen hON und Hoover Wizard.
Funktionieren beide Apps ohne WLAN oder nur im lokalen Netz?

**Comment by TA2k** [comment]
https://forum.iobroker.net/topic/55667/test-adapter-hoover-hon

**Comment by hotwin** [comment]
Leider ist es nur noch möglich die Hoover Wizard zu steuern als ich meine in die Hon App einfugen wollte ging es nicht falsches gerät jetzt suche ich eine Lösung auf Hoover Wizard. adapter

**Comment by mcm1957** [comment]
Adapter für Hoover (hon) existiert: https://github.com/TA2k/ioBroker.hoover
Request für Hoover Wizzard existiert getrennt: https://github.com/ioBroker/AdapterRequests/issues/806

Damit kann hier geschlossen werden.

**Comment by Paddel0815** [comment]
Gibt es für Simpli fi eine Anbindung? Konnte dazu nichts finden.

**Comment by mcm1957** [comment]
Ähmm ...

Dieser Issue ist geschlossen. Bitte Probleme oder Featurereqeusts im Adapter Repository als Issue ablegen.

Für Hoover Wizzard gibts einen extra Issue - siehe oben.

Allgemeine Suchanfragen sind wahrscheinlich im Forum besser aufgehoben. Falls nichts zu Simpli Fi gefunden wird bitte 
-) ein Issue bei https://github.com/TA2k/ioBroker.hoover anlegen falls es wahrscheinlich erscheint dass in diesen Adapter zu integrieren.

-) ein neues Issue anlgen wenn anzunhmen ist dass ein neuer Adaoter benötigt wird
