### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by SimonFischer04** [ioBroker/AdapterRequests#322]
Hi, Ich würde mich über einen Discord-Adapter sehr freuen mit dem man: 
1) Nachrichten senden/empfangen
2) Informationen über "alle" Server auf denen der Bot ist. (Benutze online mit Rollen,... / Channels am Server)

**Comment by Apollon77** [comment]
Are there APIs available? Links? Libraries?

**Comment by SimonFischer04** [comment]
ich denke das könnte helfen: https://discord.js.org/#/

**Comment by SimonFischer04** [comment]
do your need more information?

**Comment by Noe12372** [comment]
Ich würde es auch ziemlich praktisch finden. Vllt könnte man dann auch Mic Mute und so Sachen einfügen, wäre ziemlich cool :)

**Comment by Noe12372** [comment]
Hier gibt es auch noch etwas zur API:
https://support.discordapp.com/hc/de/articles/212889058-Discord-s-Offizielle-API

**Comment by dfrozen** [comment]
https://discordjs.guide/#before-you-begin Easy solution to implement.

**Comment by Sacred-Shadow** [comment]
Würde mich an den Wunsch mal anhängen. 
Wär schon cool, wenn man über nen Adapter Nachrichten senden & empfangen kann.

**Comment by Sacred-Shadow** [comment]
Fänd ich auch gut, wenn hier was kommt :)

**Comment by duczz** [comment]
Fänd ich auch super, hoffe es kommt bald

**Comment by ldittmar81** [comment]
https://github.com/discordjs/discord.js Discord API

**Comment by crycode-de** [comment]
Ich würde mir "ioBroker.discord" demnächst mal als neuen Adapter vornehmen wollen. 🙂 
Ein paar Ideen/Wünsche sind hier ja schon gesammelt. Weitere gerne hier oder direkt an mich.

**Comment by Sacred-Shadow** [comment]
Naja erstmal die Basics ... schreiben an eine bestimmte Person oder einen bestimmten Channel. 
Damit kann man erstmal normale Benachrichtigungen machen. 

Interessant wäre noch, wenn der Adapter reagieren kann. 
Also sprich, dass man den Bot anschreiben kann und der Adapter darauf reagiert - damit man halt Befehle im ioBroker auslösen kann. 

Klar könnte man überlegen ob man den Adapter benutzen möchte, um Channels zu überwachen. 
Hier würde ich aber eher sagen es gibt auf dem Markt schon nen ganzen Haufen Bots die das können.

**Comment by SimonFischer04** [comment]
> Interessant wäre noch, wenn der Adapter reagieren kann.

jo, ne text2command integration wär schon nice

**Comment by Fontheweg** [comment]
@crycode-de wenn Du Tester brauchst, wäre am Start. Würde das auch gerne nutzen.
Bei mir ist der Gedanke einen Log-Discord aufzubauen und den Status dort zu posten.
Mache das derzeit mit nem XMLHTTP und Webhooks, ist aber umständlich.

So generell, kann man die Discord.js nicht einfach im ioBroker im JS laden und in Skripten nutzen?

**Comment by crycode-de** [comment]
Das Repository mit einer noch recht frühen alpha-Version ist nun unter https://github.com/crycode-de/ioBroker.discord verfügbar.

Eine Auflistung der bereits integrierten Funktionen ist in der [Readme](https://github.com/crycode-de/ioBroker.discord#features) zu finden. Noch geplante Features habe ich in einem [Issue](https://github.com/crycode-de/ioBroker.discord/issues/1) festgehalten.

Wichtig: Der Adapter benötigt **Node.js 16.6** oder höher, da dies für das aktuelle discord.js benötigt wird.

Wer mag darf schon jetzt gerne testen und Feedback geben.

---

> So generell, kann man die Discord.js nicht einfach im ioBroker im JS laden und in Skripten nutzen?

Ja, könnte man sicherlich auch. Der Adapter macht die Nutzung aber sicherlich komfortabler. ;-)

@ldittmar81 Kannst du bitte das Label "Planned" in "InProgess" ändern? Danke!

**Comment by Fontheweg** [comment]
Leider nicht ... 
Unsupported engine for discord.js@13.6.0: wanted: {"node":">=16.6.0","npm":">=7.0.0"} (current: {"node":"14.19.1","npm":"6.14.16"})

**Comment by Apollon77** [comment]
Na dann braucht du wohl mindestens nodejs 16

**Comment by Fontheweg** [comment]
Ja, aber das ist dich für den Broker nicht freigegeben wenn ich das richtig sehe.... oder bin ich da auf dem Holzweg?

**Comment by Apollon77** [comment]
E ist nicht das empfohlene, das ist korrekt, Mit js-controller 4.0 ist bisher nichts bekannt, aber auch unklar welche Adapter ggf noch nicht gehen und angepasst werden müssen.

**Comment by Fontheweg** [comment]
Jau, das möchte ich da nicht testen. Habe aktuell nur ein Prod-System laufen.
Zum testen könnte man das allerdings mal schnell clonen - das wäre ne Idee.

**Comment by crycode-de** [comment]
Node.js >= 16.6 wird von der aktuellen discord.js Library (13.x) benötigt.
In der package.json vom Adapter ist deshalb auch [`"node": ">=16.6.0"`](https://github.com/crycode-de/ioBroker.discord/blob/a45e5b607df15bc09ca33b3fe1a4e85854654ae4/package.json#L24) und in der io-package.json [`"js-controller": ">=4.0.0"`](https://github.com/crycode-de/ioBroker.discord/blob/a45e5b607df15bc09ca33b3fe1a4e85854654ae4/io-package.json#L81) definiert.

Für eine Unterstützung von Node.js 14 müsste man die veraltete Version 12.x von discord.js benutzen, was aus meiner Sicht für einen neu entwickelten Adapter keinen Sinn macht.

**Comment by crycode-de** [comment]
Auf dem ioBroker Discord Server gibt es jetzt unter "Beta Testing & Feedback" einen eigenen Kanal [`#discord`](https://discord.gg/ZdkzZvKwmD) für den Adapter.
Feedback, Ideen, Diskussionen etc. bitte gerne dort schreiben.

**Comment by duczz** [comment]
https://forum.iobroker.net/topic/48886/test-adapter-discord-bot-v0-0-x

**Comment by crycode-de** [comment]
> https://forum.iobroker.net/topic/48886/test-adapter-discord-bot-v0-0-x

Das ist aber ein anderer Adapter und nicht der von mir. Ich würde auch behaupten, dass meiner deutlich mehr kann. ;-)

**Comment by duczz** [comment]
Okay, aber für jemanden der nicht die aktuelle node etc nutzen will wäre es was :)
Kann man eig vorab testen ob alle Instanzen die neue node Version unterstützen? Bzw woran erkennt man das wenn nicht?

**Comment by crycode-de** [comment]
Zusammen mit js-controller 4.x wird Node.js 16.x unterstützt und soweit mir bekannt ist (nach Aussage von Ingo) sind aktuell keine Adapter bekannt, die damit nicht laufen würden.
Testen kann man das am besten in einer Testinstallation eben mit Node.js 16. Wenn etwas nicht funktioniert, dann würde der entsprechende Adapter crashen.

**Comment by Fontheweg** [comment]
Dann installiere ich heute Abend in meinem Dev-System mal ein paar Adapter nach. Aber der Discord-Adapter läuft ja nich nicht... falls Du Zeit hast, können wir heute gucken ^^

**Comment by crycode-de** [comment]
Ab sofort ist **ioBroker.discord** in Version 1.0.0 auf [GitHub](https://github.com/crycode-de/ioBroker.discord/releases/tag/v1.0.0) und [NPM](https://www.npmjs.com/package/iobroker.discord) verfügbar. 🎉 
Ein [PR](https://github.com/ioBroker/ioBroker.repositories/pull/1809) zur Aufnahme in das Latest-Repo existiert nun auch.

Danke an alle bisherigen Tester!

**Comment by crycode-de** [comment]
Forumthread zum Adapter-Test: https://forum.iobroker.net/topic/54928/test-adapter-discord-v1-0-x

**Comment by crycode-de** [comment]
Der Adapter ist ab sofort über das Latest-Repository verfügbar.

@Apollon77 Ich denke der Issue hier kann dann geschlossen werden. ;-)
