### ISSUE TITLE
Google Location

### ISSUE THREAD

**Issue by maxpd1** [ioBroker/AdapterRequests#328]
I want to use my steadily shared location from my smartphone via Google Maps.

There was an adapter named googlesharedlocations (https://github.com/t4qjXH8N/ioBroker.google-sharedlocations) which isn't getting updated since Google changed the way you can log into your account via 3rd party apps.

But perhaps there is a developer who knows another way to read the google location and transmit it into iobroker?

**Comment by n3roGit** [comment]
Diese issue kann zu. Der Adapter geht wieder!

**Comment by maxpd1** [comment]
yes, thank you.
