### ISSUE TITLE
Nanoleaf Aurora

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/AdapterRequests#33]
https://github.com/darrent/nanoleaf-aurora-api/blob/master/README.md

**Comment by daniel-2k** [comment]
I've written an adapter für Nanoleaf Light Panels (formerly Aurora).
Currently not on GitHub/npm (not yet).
I've posted a first version on ioBroker Forum:
[https://forum.iobroker.net/viewtopic.php?f=20&t=13692](url)
It needs to be tested, then I will upload it.

**Comment by daniel-2k** [comment]
Ok, I've uploaded it to GitHub:
https://github.com/daniel-2k/ioBroker.nanoleaf-lightpanels

**Comment by daniel-2k** [comment]
You can close the issue.
Adapter exists for some time.

**Comment by DutchmanNL** [comment]
> You can close the issue.
> Adapter exists for some time.

thank you :)

**Comment by sochin67** [comment]
Hi,
I'd like to switch Nanoleaf Light Panels with an Aqara Zigbee switch (single click => on, double click => off). Script works perfectly with a Hue light bulb. 
However, when I monitor the "Power State" data point in ioBroker whilst clicking the switch it switches from "False" to "True" - but unfortunately it automatically switches back to "False" after some seconds.
Any ideas?
Utilize the CC2531 Zigbee stick on a Raspi 4.
Here's my blockly script:

![grafik](https://user-images.githubusercontent.com/44208289/68716814-5dd1e180-05a5-11ea-8db7-e1b36c87a1b1.png)

Many thanks!
Tom

**Comment by Apollon77** [comment]
The Adapter is released. Please open an issue there or write in forum. Commenting on a closed issue no one will see
