### ISSUE TITLE
Go E Charger

### ISSUE THREAD

**Issue by 123Trunks** [ioBroker/AdapterRequests#330]
Hallo,
ein Go E Charger Adapter wäre nicht schlecht damit man die Ladebox vernünftig in das Smarthome einbinden kann.Zur Zeit geht es nur umständlich über Mqtt. Da kann man auch nur Befehle loswerden.Ich wäre dankbar wenn sich da ein Programmierer finden würde.Wäre auch gerne hilfsbereit in welcher Form auch immer.

+ 9 votes von #284

**Comment by DutchmanNL** [comment]
Kommen den per mqtt die Daten rein und müssen nur strukturiert werden?

**Comment by 123Trunks** [comment]
so kommen die Daten rein.
Hier noch ein Link zur Api:https://go-e.co/app/api.pdf




{"version":"B","tme":"0102201053","rbc":"53","rbt":"1022598823","car":"1","amp":"16","err":"0","ast":"0","alw":"0","stp":"0","cbl":"32","pha":"8","tmp":"27","dws":"0","dwo":"0","adi":"0","uby":"0","eto":"7990","wst":"3","txi":"2","nrg":[225,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0],"fwv":"033","sse":"005366","wss":"","wke":"*************","wen":"1","cdi":"0","tof":"101","tds":"1","lbr":"38","aho":"3","afi":"7","azo":"0","ama":"32","al1":"8","al2":"16","al3":"20","al4":"24","al5":"32","cid":"255","cch":"65535","cfi":"65280","lse":"1","ust":"0","wak":"","r1x":"3","dto":"0","nmo":"0","sch":"AAAAAAAAAAAAAAAA","sdp":"0","eca":"0","ecr":"0","ecd":"0","ec4":"0","ec5":"0","ec6":"0","ec7":"0","ec8":"0","ec9":"0","ec1":"0","rca":"","rcr":"","rcd":"","rc4":"","rc5":"","rc6":"","rc7":"","rc8":"","rc9":"","rc1":"","rna":"","rnm":"","rne":"","rn4":"","rn5":"","rn6":"","rn7":"","rn8":"","rn9":"","rn1":"","loe":0,"lot":8000,"lom":6,"lop":1,"log":"BRCLWBHW","lon":0,"lof":0,"loa":0,"lch":71418}

**Comment by DutchmanNL** [comment]
Sieht gut dokumentiert aus sowohl MQTT als rest-api Möglichkeiten die Komplexität hällt sich also in Grenzen.

Hab's selber nicht also keine Anreiz da jetzt selber Ran zu gehen im Moment ☺️

**Comment by 123Trunks** [comment]
Schade aber vielleicht findet sich ja noch einer.

**Comment by DutchmanNL** [comment]
> Schade aber vielleicht findet sich ja noch einer.

Weis nicht wie weit es benutzt ist / vetreten auf m markt vielleicht bekommste ja n par zusammen fuer ne croudfunding / spemdem aktion ☺️

**Comment by 123Trunks** [comment]
Hab schon des öfteren gelesen das welche den GO E Charger gerne in Iobroker nutzen würden bzw integrieren.

**Comment by TA2k** [comment]
Wenn wirklich ein paar Leute so ein Adapter benötigen, dann sollen sie mal hier voten oder kommentieren

**Comment by 123Trunks** [comment]
Wäre schön.

**Comment by Jautze82** [comment]
Hallo,
ich wäre auch dankbar für die Entwicklung.
...finde leider den Button zum voten nicht.
Danke und viele Grüße

**Comment by OttoLeirer** [comment]
Ich wäre auch dafür. lg

**Comment by DutchmanNL** [comment]
das assign bedeutet nicht ich mache es ist aber potentieller Kandidat fuer Seminare zum adapterbau

**Comment by Fuz100** [comment]
Hallo zusammen, bin neu hier und sehr dafür, da ich mir vor Kurzem diese Ladebox besorgt habe. LG

**Comment by Trunks1982** [comment]
Ich habe hier ein JavaScript bekommen was den Go E Charger ausliest.Vielleicht kann das einer in einen Adapter umwandeln.

[go e charger javascript.txt](https://github.com/ioBroker/AdapterRequests/files/4508823/go.e.charger.javascript.txt)

**Comment by Fiiti** [comment]
Das geht mit dem Systeminfo Adapter sorgenfrei und schnell.
![2020-04-21 16_04_41-instances - ioBroker und 1 weitere Seite - Persönlich – Microsoft​ Edge](https://user-images.githubusercontent.com/25975978/79875835-7cf15c80-83ea-11ea-86e8-f16cc2556186.png)

**Comment by ChrisBGL** [comment]
Die gleiche Anfrage gibt es noch mal hier: https://github.com/ioBroker/AdapterRequests/issues/284

**Comment by hombach** [comment]
Also ich habe das per Javascript adapter am laufen.... funktioniert bisher prima. 
Es werden dabei die Werte der PV-Anlage verwertet und der Ladestrom entsprechend mit einem kleinen Regelkreis angepasst. So lade ich meinen BEV im Sommer nur mit "PV-Reststrom".
Ist das das was ihr euch vorgestellt habt?

**Comment by hombach** [comment]
So schaut das dann bei mir in der Visualisierung aus:

![image](https://user-images.githubusercontent.com/63002482/85931116-2c9eeb00-b8c2-11ea-95ec-7261d41d851f.png)

Alles noch etwas sehr "denglish" aber das stört die Funktion nicht:
- Soll SoC Batterie ist der Zielwert der Hausbatterie auf den der Regler (Charge-Manager) hinarbeitet.
- Ladestrom zeigt im Automatik-Modus den aktuellen Strom an 
- mit "Charge NOW" wird sofort und bedingungslos geladen
- der Ladestromschieber dient dann der händischen Vorgabe des Ladestroms
- aktuelle Ladeleistung unten rechts (mein BEV und daher auch der go-e sind auf 11kW beschränkt)

**Comment by MK-2001** [comment]
Hallo, 

ich habe mal eine erste Version erstellt, mit der der go-eCharger in ioBroker aufgenommen werden kann. 

https://github.com/MK-2001/ioBroker.go-echarger 
https://www.npmjs.com/package/@mk2001/iobroker.go-echarger

**Comment by Trunks1982** [comment]
Sehr cool, habs mir gerade angeguckt.Sogar Rfid haste mit drin.Da wäre ja sogar bestimmt möglich mit dem Leser die Tür zu öffnen:-)?

**Comment by Trunks1982** [comment]
> Hallo,
> 
> ich habe mal eine erste Version erstellt, mit der der go-eCharger in ioBroker aufgenommen werden kann.
> 
> https://github.com/MK-2001/ioBroker.go-echarger
> https://www.npmjs.com/package/@mk2001/iobroker.go-echarger

Was mir bis jetzt schonmal aufgefallen ist, kann es sein das man nur Ampere for PWM ändern kann und das andere nur state abfragen sind?

**Comment by Apollon77** [comment]
Sollten wir hier dann zu machen und es im Forum weiter diskutieren? Oder warten bis erstes Latest Release da ist?

**Comment by Trunks1982** [comment]
Ich würde sagen warten bis latest release da ist.

**Comment by MK-2001** [comment]
> Was mir bis jetzt schonmal aufgefallen ist, kann es sein das man nur Ampere for PWM ändern kann und das andere nur state abfragen sind?

Ja, weitere Schreibfunktionen folgenden dann heute Abend :-) 
Das war mein erster Schuss ins Repo. Danach hatte ich gesehen, wieviele Anforderungen seitens ioBroker für einen Adapter vorhanden sind und wollte mich erstmal darum kümmern.
Möchtest du eine priorisieren? :-)

**Comment by Trunks1982** [comment]
> > Was mir bis jetzt schonmal aufgefallen ist, kann es sein das man nur Ampere for PWM ändern kann und das andere nur state abfragen sind?
> 
> Ja, weitere Schreibfunktionen folgenden dann heute Abend :-)
> Das war mein erster Schuss ins Repo. Danach hatte ich gesehen, wieviele Anforderungen seitens ioBroker für einen Adapter vorhanden sind und wollte mich erstmal darum kümmern.
> Möchtest du eine priorisieren? :-)

Ich würde sagen der Datenpunkt Car (PWM Signalisieren wäre wichtig.Damit gibt du ja das laden frei.

**Comment by Trunks1982** [comment]
> > Was mir bis jetzt schonmal aufgefallen ist, kann es sein das man nur Ampere for PWM ändern kann und das andere nur state abfragen sind?
> 
> Ja, weitere Schreibfunktionen folgenden dann heute Abend :-)
> Das war mein erster Schuss ins Repo. Danach hatte ich gesehen, wieviele Anforderungen seitens ioBroker für einen Adapter vorhanden sind und wollte mich erstmal darum kümmern.
> Möchtest du eine priorisieren? :-)

Habe jetzt mal mit meiner automatischen Ladeanpassung den Adapter am laufen und bis jetzt top.Aber konnte bis jetzt das neue Release noch nicht installieren.

**Comment by Trunks1982** [comment]
> > Was mir bis jetzt schonmal aufgefallen ist, kann es sein das man nur Ampere for PWM ändern kann und das andere nur state abfragen sind?
> 
> Ja, weitere Schreibfunktionen folgenden dann heute Abend :-)
> Das war mein erster Schuss ins Repo. Danach hatte ich gesehen, wieviele Anforderungen seitens ioBroker für einen Adapter vorhanden sind und wollte mich erstmal darum kümmern.
> Möchtest du eine priorisieren? :-)

Hast schon was neues vorliegen zum testen?

**Comment by MK-2001** [comment]
🤣 Ja, aber derzeit schlage ich mich noch mit den Anforderungen von ioBroker. 

Es gab jeden Tag commits aber leider nur administrative und keine funktionalen.

Aber ich habe mir dein Script schon angesehen. Ich denke da wird es einen Weg geben, die Funktion zu integrieren.

**Comment by Trunks1982** [comment]
> 🤣 Ja, aber derzeit schlage ich mich noch mit den Anforderungen von ioBroker.
> 
> Es gab jeden Tag commits aber leider nur administrative und keine funktionalen.
> 
> Aber ich habe mir dein Script schon angesehen. Ich denke da wird es einen Weg geben, die Funktion zu integrieren.

@DutchmanNL frag ihn mal der weiss genau wie das geht mit den Anforderungen von IOBroker

**Comment by MK-2001** [comment]
Ich bin mir nicht sicher, warum der PR nicht weiter geht.
https://github.com/ioBroker/ioBroker.repositories/pull/855

E801 E802 habe ich m.E. erfüllt. Hier scheint aber das Script noch nicht mit dem neuen Design vom GitHub synchronisiert zu sein.

Könnt ihr mir verraten was noch falsch ist?

**Comment by MK-2001** [comment]
> > > Was mir bis jetzt schonmal aufgefallen ist, kann es sein das man nur Ampere for PWM ändern kann und das andere nur state abfragen sind?
> > 
> > 
> > Ja, weitere Schreibfunktionen folgenden dann heute Abend :-)
> > Das war mein erster Schuss ins Repo. Danach hatte ich gesehen, wieviele Anforderungen seitens ioBroker für einen Adapter vorhanden sind und wollte mich erstmal darum kümmern.
> > Möchtest du eine priorisieren? :-)
> 
> Ich würde sagen der Datenpunkt Car (PWM Signalisieren wäre wichtig.Damit gibt du ja das laden frei.

CAR selbst kann nicht via API geschrieben werden. 

M. E. sind folgende Endpunkte zunächst wichtig:
- ast | uint8_t | access_state​: Zugangskontrolle.
- alw | uint8_t | allow_charging: ​PWM Signal darf anliegen
- stp | uint8_t | stop_state: ​Automatische Abschaltung
- dwo | uint16_t | Abschaltwert ​in 0.1kWh wenn ​stp==2​, für dws Parameter

Habe ich welche vergessen?

**Comment by Trunks1982** [comment]
> > > > Was mir bis jetzt schonmal aufgefallen ist, kann es sein das man nur Ampere for PWM ändern kann und das andere nur state abfragen sind?
> > > 
> > > 
> > > Ja, weitere Schreibfunktionen folgenden dann heute Abend :-)
> > > Das war mein erster Schuss ins Repo. Danach hatte ich gesehen, wieviele Anforderungen seitens ioBroker für einen Adapter vorhanden sind und wollte mich erstmal darum kümmern.
> > > Möchtest du eine priorisieren? :-)
> > 
> > 
> > Ich würde sagen der Datenpunkt Car (PWM Signalisieren wäre wichtig.Damit gibt du ja das laden frei.
> 
> CAR selbst kann nicht via API geschrieben werden.
> 
> M. E. sind folgende Endpunkte zunächst wichtig:
> 
> * ast | uint8_t | access_state​: Zugangskontrolle.
> * alw | uint8_t | allow_charging: ​PWM Signal darf anliegen
> * stp | uint8_t | stop_state: ​Automatische Abschaltung
> * dwo | uint16_t | Abschaltwert ​in 0.1kWh wenn ​stp==2​, für dws Parameter
> 
> Habe ich welche vergessen?

Ne das wäre erstmal gut wenn die laufen.

**Comment by Trunks1982** [comment]
Können uns auch per pn kurzschliessen dann kann och das auch immer sofort für dich mittesten 😉

**Comment by Apollon77** [comment]
> Ich bin mir nicht sicher, warum der PR nicht weiter geht.

Weil der Ingo noch keine Zeit für den Review hatte. Sorry

**Comment by MK-2001** [comment]
So der Adapter ist nun im latest vorhanden. Schließen? Wir können diese Issues gerne im Repo hier weiterführen. Bzw. tun dies auch gerade. https://github.com/MK-2001/ioBroker.go-e/issues/

**Comment by Trunks1982** [comment]
Ja kannste schliessen.Werde es dann heute mal testen wenn genug sonne da ist🤣

**Comment by Apollon77** [comment]
Super!
