### ISSUE TITLE
SolarEdge adapter from local network.

### ISSUE THREAD

**Issue by YRRK** [ioBroker/AdapterRequests#334]
One missing adapter is the one that can read the SolarEdge from in the local network. Maybe some startup work for such an Adapter is fork-able from the HomeAssistant SolarEdge integration on Github. ;-)

**Comment by Apollon77** [comment]
Links? Infos? APIs? ;-)

**Comment by YRRK** [comment]
Inspiration:
https://github.com/home-assistant/home-assistant/tree/dev/homeassistant/components/solaredge_local
(Link from https://www.home-assistant.io/integrations/solaredge_local/ )

https://pypi.org/project/solaredge-local/

Api (this is about their remote api, not the local api (is wat you want) but maybe it has some general info: https://www.solaredge.com/sites/default/files/se_monitoring_api.pdf

**Comment by jookeer** [comment]
I would be interested very much in an adapter. Not only local one, but using the api.

**Comment by YRRK** [comment]
> Op 7 feb. 2020 om 22:25 heeft jookeer <notifications@github.com> het volgende geschreven:
> 

﻿
I would be interested very much in an adapter. Not only local one, but using the api.

**Comment by YRRK** [comment]
Oké, but it makes you dependent on an external party, who also sells your data. Keep that in mind.

> Op 7 feb. 2020 om 22:25 heeft jookeer <notifications@github.com> het volgende geschreven:
> 

﻿
I would be interested very much in an adapter. Not only local one, but using the api.

**Comment by Apollon77** [comment]
Why closed?

**Comment by YRRK** [comment]
Can’t provide you with such expensive hardware.
Discovered/start using HomeAssistant instead of iobroker.
Can open it again if you want.

> Op 25 feb. 2020 om 22:45 heeft Ingo Fischer <notifications@github.com> het volgende geschreven:
> 

﻿
Why closed?

**Comment by Apollon77** [comment]
lets open again .. then we see how much other users might be interested

**Comment by Apollon77** [comment]
PS: "HW needed" do not mean that you have to provide it ... but it means that a dev most likely need to have access to such a HW for development.

**Comment by 92lleo** [comment]
https://github.com/92lleo/ioBroker.solaredge
I've a small adapter for getting the current power and day/month/year/lifetime readings. From local network you could use modbus as detailed multiple times in the forum

**Comment by YRRK** [comment]
SolarEdge recently closed their local API with a software update. They made the internal IP inaccesable. Thus rendering this request at the moment useless. Maybe close the case...?
