### ISSUE TITLE
Controme

### ISSUE THREAD

**Issue by Chesterw83** [ioBroker/AdapterRequests#335]
Für die Heizungssteuerung Controme wäre ein IObroker Adapter sehr sinnvoll. Wird immer öfter eingesetzt. Haben eine sehr gute API Doku.

https://support.controme.com/api/

**Comment by MadErstam** [comment]
Darüber würde ich mich auch sehr freuen!

**Comment by ronschd** [comment]
Oh ja, das wäre toll.

**Comment by DutchmanNL** [comment]
Interessantes Produkt und gute API das weckt mein Interesse! Habe da einige libs vorbereitet womit man json api leicht integrieren kan.

werde mich mal mit dem Hersteller in Verbindung setzen, habe einmal sowas blind programmiert ohne Geräte (tado) und das ist wirklich schwierig vor allem im Support

**Comment by MadErstam** [comment]
Hallo zusammen,

Ich habe mittlerweile einen Adapter entwickelt. Ist noch rudimentär, aber liest alle von mir benötigten Werte aus und schreibt auch die Zieltemperatur zurück. Werde ich nachher Mal releasen.

Viele Grüße!

Marc

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________

**Comment by MadErstam** [comment]
Der Adapter liegt auf Github: https://github.com/MadErstam/iobroker.controme. Ich wäre euch dankbar, wenn ihr den Adapter testweise installieren könntet und mir Feedback gebt. Habt bitte Nachsicht, es ist mein erster Adapter und meine aktive Zeit der Softwareentwicklung liegt schon 20 Jahre zurück.

Die Readme beschreibt, was aktuell schon geht. 

Ihr könnt den Adapter installieren, wenn ihr lokal auf eurem iobroker den folgenden Befehl aufruft:

`npm install https://github.com/MadErstam/iobroker.controme/tarball/main/`

Bugs, Feature Requests und allgemeines Feedback bitte direkt im Repository.

**Comment by Chesterw83** [comment]
Dann werde ich mir mal die Controme API freischalten lassen. Da bin ich ja schon gespannt.
Vielen Dank schonmal für die Arbeit :-)

**Comment by DutchmanNL** [comment]
> Der Adapter liegt auf Github: https://github.com/MadErstam/iobroker.controme. Ich wäre euch dankbar, wenn ihr den Adapter testweise installieren könntet und mir Feedback gebt. Habt bitte Nachsicht, es ist mein erster Adapter und meine aktive Zeit der Softwareentwicklung liegt schon 20 Jahre zurück.
> 
> Die Readme beschreibt, was aktuell schon geht.
> 
> Ihr könnt den Adapter installieren, wenn ihr lokal auf eurem iobroker den folgenden Befehl aufruft:
> 
> `npm install https://github.com/MadErstam/iobroker.controme/tarball/main/`
> 
> Bugs, Feature Requests und allgemeines Feedback bitte direkt im Repository.

Cool thanks! Na Dan mach ich mal hier zu und issue bitte in der Adapter repo oder über Forum 

Bei Fragen immer her damit oder auch in Discord
