### ISSUE TITLE
Check von ausgewählten Datenpunkten über Min und Max Werte über einen definierbaren Zeitraum.

### ISSUE THREAD

**Issue by Easyrunner** [ioBroker/AdapterRequests#336]
Hallo allerseits,

Vielleicht kann ich bei jemanden das Interesse wecken einen Adapter oder Script zu schreiben bei dem man Datenpunkte auswählen kann und über einen frei definierbaren Zeitraum Minimum, Maximum und Mittelwerte zu berechnen.

Beispiel 
Was wären in den letzten 12 Monaten die min. und Max. Temperaturen außen. 

Viele Grüße

**Comment by Apollon77** [comment]
sourceanalytix kann das nichgt? Wenn nein wäre es ggf eher ein Feature Request dort oder ?

**Comment by Ilovegym66** [comment]
Oder der minmax Adapter?

**Comment by DutchmanNL** [comment]
Nein beides nicht, dafür habe wir statistics;)

Sourceanalytix = Verbrauch Messung über Zeiträume 

Statistics = von wert x Durchschnitt, Max use ermitteln
