### ISSUE TITLE
Legrand Measurement Concentrator EMDX³ 412000 (Ecocompteur)

### ISSUE THREAD

**Issue by raintonr** [ioBroker/AdapterRequests#337]
This is a electrical power measurement device (with optional pulse inputs for water/gas measurement) with IP interface. The Legrand product code is 412000:

https://www.legrand.com/ecatalogue/412000-measurement-concentrator-emdx-6-modules.html

It is known as the Legrand Ecocompteur in France:

https://www.legrand.fr/pro/catalogue/31736-ecocompteurs-ip/ecocompteur-modulaire-ip-pour-mesure-consommation-sur-6-postes-110v-a-230v-6-modules

I have one of these devices and easily interfaced it to a Loxone Miniserver. Will write an ioBroker adapter if there is demand.

**Comment by raintonr** [comment]
Have made a start here... https://github.com/raintonr/ioBroker.legrand-ecocompteur

**Comment by raintonr** [comment]
... and it's pretty much working. Will tidy up and make a release.

**Comment by raintonr** [comment]
Waiting for this pull request: https://github.com/ioBroker/ioBroker.repositories/pull/757

**Comment by Apollon77** [comment]
Thank you! I hope I find review time soon

**Comment by raintonr** [comment]
Adapter now stable so closing this.

**Comment by TimotheeDP** [comment]
How do you integrate this into Loxone Config?

**Comment by mcm1957** [comment]
Please ask question related to an (existing) Adapter at the forum (forum.iobroker.net).
For problems and feature requests please create an issue at the adapter repository.

Fragen zur Verwendung eines Adapters bitte im Forum stellen.
Probleme u Featurerequests bitte als Issue im Repository des Adapters eintragen.
