### ISSUE TITLE
Eufy Security Cam / HomeBase / Object for "a person was recognized"

### ISSUE THREAD

**Issue by knutbrecht** [ioBroker/AdapterRequests#338]
The Eufy Security Cam is able to decide, if there is a person or just something else moving. Actually the Homebase does this.

I found some first little codings for Home Assistant:

https://community.home-assistant.io/t/eufy-camera-integration/121758
http://community.anker.com/t/open-api/70397/5

And some more here on GitHub:

https://github.com/FuzzyMistborn/python-eufy-securityhttps://github.com/FuzzyMistborn/python-eufy-security/issues/3

Sorry, thats all. It would be great, if there was an  object like "Person recognized".
... Dreaming of a button on my iobroker VIS which activates the rtsm stream from one cam... ;)

Best. Knut

**Comment by TA2k** [comment]
Duplicate ?
https://github.com/ioBroker/AdapterRequests/issues/455

**Comment by mcm1957** [comment]
Seems to be a duplicate. Please see #455.

Link to adapter repository: https://github.com/bropat/ioBroker.eusec

Adapter has been release. Please report any issues at adapter repository.

Will close here too.
