### ISSUE TITLE
Internet Speed Test

### ISSUE THREAD

**Issue by ldittmar81** [ioBroker/AdapterRequests#341]
I want to record exactly how my internet provider is kidding me and visualize it nicely so that I can show it to everyone.

https://github.com/ddsol/speedtest.net

**Comment by DutchmanNL** [comment]
Thats an easy one will do the basic this week

**Comment by DutchmanNL** [comment]
very first small alpha done, can scan for closest servers and execute test by pressing a button.

todo : mja, a lot so maybe at least someone can help matching all the state names

lets go further here : https://github.com/iobroker-community-adapters/ioBroker.web-speedy
