### ISSUE TITLE
LOXONE Miniserver V2

### ISSUE THREAD

**Issue by manuelmaudrich** [ioBroker/AdapterRequests#347]
Leider funktioniert der Loxone Adapter im ioBroker für den Loxone Miniserver V2 nicht mehr. Möglicherweise liegt es am HTTPS Request welches bis lang im V1 nur unter HTTP lief. Ist es möglich den aktuellen Adapter dahingehend anzupassen bzw. einen neuen Adapter zu entablieren?

Grüße  im Namen der Loxone- und Allroundbastler- Community

**Comment by Apollon77** [comment]
Bitte beim Adapter ein Issue anlegen das das dort gefixt wird. EIn neuer Adapter macht wenig sinn

**Comment by manuelmaudrich** [comment]
Hallo, danke für die Info? Nur wo finde ich den Adapter um ein Issue anzulegen? Im IOBroker hab ich nicht die Möglichkeit zum Adapter Anfragen anzulegen. Dieser Button ist nicht verfügbar. 

Mit freundlichen Grüßen 
Manuel Maudrich

**Comment by Apollon77** [comment]
https://github.com/UncleSamSwiss/ioBroker.loxone/issues
