### ISSUE TITLE
example for connection

### ISSUE THREAD

**Issue by SVallant** [ioBroker/AdapterRequests#350]
some time ago i have made an example for testing with the bticino gateway, here is my code:

include https://www.npmjs.com/package/myhome

`log("Start BtiCino");

var myhome = require('myhome');
var mhengine = new myhome.engine({
	host:'192.168.178.111',
	pass:'12345'
});
var old_data ="";

var dimmervalue = "2";
mhengine.on ('monitoring', function () {
	//log ('successfully connected, started monitoring');
});
mhengine.on ('packet', function ( data ) {
	bticino_analyze_data ( data );
});

schedule("5,15,25,35,45,55 * * * * *", function () {

  mhengine.sendCommand({
    command:'*1*0*12##', 
    stopon: ['*#*1##', '*#*0##'],
    done: function(pkt,i) {
      //log("SendCommand *1*0*12##");
    }
  });
});

schedule("0,10,20,30,40,50 * * * * *", function () {

  mhengine.sendCommand({
    command:'*1*1*12##', 
    stopon: ['*#*1##', '*#*0##'],
    done: function(pkt,i) {
      //log("SendCommand *1*1*12##");
    }
  });
  // if (dimmervalue == "10") {
    // mhengine.sendCommand({
      // command:'*1*6*31##', 
      // stopon: ['*#*1##', '*#*0##'],
      // done: function(pkt,i) {
        // //log("SendCommand *1*6*31##");
      // }
    // });
    // dimmervalue = "2";
  // } else {
    // mhengine.sendCommand({
      // command:'*1*2*31##', 
      // stopon: ['*#*1##', '*#*0##'],
      // done: function(pkt,i) {
        // //log("SendCommand *1*2*31##");
      // }
    // }); 
    // dimmervalue = "10";
  // }
});  

function bticino_analyze_data ( data ) {
  // log ('Data received: ' + data);
  // log ('ALTE Data    : ' + old_data);
  // if ( data === old_data ) { return }
  // old_data = data; // old_data nachführen
  var data_parts = data.split("##");
  if ( data_parts.length > 1 ) {
    // for (let data_part of data_parts) {
     // log("Teil 1: " + data_parts[0]); 
    // }
    var tel_data = data_parts[0];
    if (tel_data.indexOf("*#13**22*") === 0) {
      log("Uhrzeit von bticino: " + tel_data.substring(9));
    }
    else if (tel_data.indexOf("*1*1000") === 0) {
      log("Diagnose von bticino: " + tel_data);
    }
    else if (tel_data.indexOf("*1*") === 0 || tel_data.indexOf("*2*") === 0) {
      log("Status von bticino: " + tel_data);
      tel_data_parts = tel_data.split("*");
      if ( tel_data_parts.length != 4 ) {
        log("FEHLER: mehr als 3 Telegrammteile: " + tel_data + " : " + tel_data_parts.length);
      } else {
        log("WHO: " + tel_data_parts[1]);
        log("WHAT: " + tel_data_parts[2]);
        log("WHERE: " + tel_data_parts[3]);

        var system  = tel_data_parts[1];
        var wert    = parseInt(tel_data_parts[2]);       
        var adress  = tel_data_parts[3];
        
        var bticino_states = $('state[state.id=bticino*]');
        //log(JSON.stringify(obj_selected_adress));
        var state_found = false;
        bticino_states.each(function (id, i) {
          var obj = getObject(id);
          if ( obj.native.adress == adress ) {
            state_found = true;
            log("Geraet Nr. " + i + ": " + obj._id + ": "+ obj.native.adress + ": "+ obj.common.type);
            if ( obj.common.type == "boolean" ) {
              if ( wert > 0 ) {
                setState(id, true, true);
              } else {
                setState(id, false, true);
              }
            } 
            else if ( obj.common.type == "number" ) {
              if ( obj.native.type == "blind" ) {
                setState(id, wert , true);
              } else if ( obj.native.type == "dimmer" ) {
                setState(id, wert*10 , true);
              } else {
                log("FEHLER: nativer Typ ungueltig: " + obj.common.type);
              }
            } else {
              log("FEHLER: Typ ungueltig: " + obj.common.type);
            }
          }
        });
        // keine dazugehörige Adresse gefunden
        if ( state_found === false ) {
          log("ACHTUNG: Variable mit Adresse: " + adress + " nicht in ioBroker vorhanden !"); 
        }
      }
    }
    else {
      log("UNBEKANNT von bticino: " + tel_data);
    }
    
  }
}

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////  
  
var bticino_states = $('state[state.id=bticino*]');

bticino_states.on(function (obj) {
  // visu_kommandos haben ack = false
  if ( obj.state.ack !== false ) { return; } 
  log('BtiCino Neuer Visu-Befehl ' + obj.id + ' = ' + obj.state.val + " ack: " + obj.state.ack);
  var bitcino_command = "";
  if ( obj.common.type == "boolean" ) {
    if ( obj.state.val === true ) {
      try {
        bitcino_command = obj.native.command_on;
      }
      catch(err) {
        log = err.message;
        return;
      }
    } else {
      try {
        bitcino_command = obj.native.command_off;
      }
      catch(err) {
        log = err.message;
        return;
      }
    }
  } 
  else if ( obj.common.type == "number" && obj.native.type == "dimmer" ) {
    try {
      bitcino_command = obj.native.command_dim;
    }
    catch(err) {
      log = err.message;
      return;
    }
    var wert = parseInt(parseInt(obj.state.val)/10);
    bitcino_command = bitcino_command.replace("%", wert.toString());
  }
  else if ( obj.common.type == "number" && obj.native.type == "blind" ) {
    try {
      bitcino_command = obj.native.command;
    }
    catch(err) {
      log = err.message;
      return;
    }
    var wert = parseInt(obj.state.val);
    bitcino_command = bitcino_command.replace("%", wert.toString());
  }
  if (bitcino_command.length > 2) {
  
    mhengine.sendCommand({
      command: bitcino_command, 
      stopon: ['*#*1##', '*#*0##'],
      done: function(pkt,i) {
        log("SendCommand " + bitcino_command);
      }
    });
  
  
  }
  
  
});  `

**Comment by Apollon77** [comment]
Ok, what you like to say with this issue? Would you be interested in having an Adapter for the "bticino gateway" (whatever this is ;-) )?

**Comment by Apollon77** [comment]
Is this a topic that would make sense as comment in #198 ?!

**Comment by mcm1957** [comment]
That's no cleaf request for a concrete adapter. So lets close for now.

If any concrete adapter is requested, please add a nwe issue and fill out details.
