### ISSUE TITLE
"Alpha-ESS" ioBroker Adapter

### ISSUE THREAD

**Issue by MBH88** [ioBroker/AdapterRequests#351]
Hallo zusammen,

ich habe eine PV-Anlage / Wechselrichter der Firma Alpha ESS. Ich befürchte zwar, dass es nicht viele Leute gibt die auch so ein Anlage haben, aber vlt finden sich ja genug, dass es sich lohnt einen Adapter zu programmieren. Ich bin leider blutiger Anfänger und kann so gut wie nichts dazu beisteuern. 
Der Wechselrichter ist mit dem Internet verbunden und kann nach registrierung  via WEB und APP ausgelesen werden. Schön wäre es, wenn ich die Daten in ioBroker auslesen und dementsprechend weiter verarbeiten könnte.

**Comment by hobili** [comment]
Hallo, 

ich bekomme demnächst einen Speicher von Alpha ESS, den Smile B3. 

Auf Nachfrage bei Alpha hieß es es gäbe keine API die man dem Kunden zu Verfügung stellen könne. Ich wäre aber ebenfalls sehr interessiert an einem Adapter - leider bin ich auch eine absolute Null was das programmieren angeht...

**Comment by hobili** [comment]
Die Monitoring Webseite findet man übrigens unter 

alphaess.com 

und mit 

Benutzer: demo 
Passwort: demo 

kann man sich dort schon mal ein wenig umsehen ;-)

**Comment by MBH88** [comment]
Hallo hobili, könntest du bitte dem ersten Beitrag ein Daumen hoch geben. Danke. 
@Apollon77 gibt es noch weitere Informationen die interessant wären? 
Wie hobili schon oben geschrieben hat rückt AlphaESS leider die api nicht raus.
Ansonsten fällt mir nur noch die normale Homepage ein
alpha-ess.de

**Comment by MBH88** [comment]
Bin mir nicht sicher ob das was hilfreiches ist, aber bin über folgende Seite gestolpert als ich nach AlphaESS API gegoogelt habe.

http://52.63.238.58/docs/goodwe/goodwe-1bgoaocid6uq8

**Comment by Gaspode69** [comment]
Ich habe auch seit einigen Tagen so ein Teil (Smile 5) und wäre sehr an einem passenden Adapter interessiert. Wenn ich was beitragen kann, sehr gerne im Rahmen meiner bescheidenen Möglichkeiten...

**Comment by allesistmoeglichoderauchnicht** [comment]
Hi,
ja hab auch eine und wär am Adapter interessiert!

**Comment by MBH88** [comment]
Hi allesistmoeglich...
Gibst du bitte dem ersten Beitrag ein Daumen hoch, danke

**Comment by Freeride1986** [comment]
Hi,
ich hab auch den Smile B3. 
Bin super zufrieden, die Chinesen rücken die API nicht raus. 
Die hatten sich das mal überlegt, aber ist für die zu viel Aufwand es zu pflegen war die Begründung.
Aber es kann sein, dass sie trotzdem kommt. Der Chef war letztens in Deutschland, daher weiß ich das. Bin auch an so einem Adapter interessiert, da meine Wechselrichter kein Modbus haben.

Alternativ kann man auch per FHEM die Seite abgreifen und dann selber darstellen, ist aber auch n bisschen Aufwand wenn es auch einfacher gehen würde.

Daher bin ich auch an einem Adapter interessiert.

**Comment by hobili** [comment]
Hi Freeride1986,

leider habe ich meine PV Anlage immer noch nicht auf dem Dach und daher auch keinen Smile im Keller...

Ich habe schon versucht auf der Demo-Seite von Alpha Ess die Daten ab zu greifen aber die URL ist immer "https://www.alphaess.com/Monitoring/VtSystem/VtSystemIndexForCustomer#" egal was man auf der Seite auswählt. Daher ist das mMn schwierig per Parser oder Ähnlichem die Daten zu bekommen. Wie geschrieben - ich bin ein noob was das Programmieren angeht.

Gibt es da eine andere Lösung?

LG
Holger

**Comment by Micheagle** [comment]
Hallo zusammen,
ich habe eine Alpha Ess Storion ECO S5 Anlage mit einem 5,4kWH Akku im Haus installiert.
Auch ich bin sehr an einem Adapter interessiert.
Letzte Aussage war, dass bei meinem System für eine lokale Abfrage maximal was über die RS-485 Schnittstelle gehen könnte.

Ich habe seinerzeit von deinen ein PDF mit einer API bekommen, angeblich passte die aber nicht zum System.

Kann ich sonst etwas zur Adapter Entwicklung beitragen?

Viele Grüße
Michael

**Comment by Gaspode69** [comment]
Beim Smile 5 gibt es eine RS485 Modbus RTU Schnittstelle. Die ließe sich komfortabel mit dem ioBroker Modbus Adapter nutzen. Allerdings muss Alpha dafür Software auf den Smile 5 aufspielen. Bei mir haben sie das auf Anfrage sogar gemacht (die RS485 2 Draht Schnittstelle leigt dann auf der CAN Buchse, 4-B, 5-A). Leider habe ich es aber noch nicht ans Laufen bekommen und stehe noch im Kontakt mit dem Alpha Service.
Bei Interesse evtl. mal bei Service@alpha-ess.de anfragen, ob sie bereit sind, die Software aufzuspielen (können die Remote).

**Comment by hamerheat** [comment]
Hallo,

ich habe einen Smile 5 mit 11kW Akku.  In iobroker sind auch schon einige Werte zusehen, manche passen, manche nicht.

@Gaspod69, welche Firmware ist bei dir installiert?  

Gruß
 Christian

**Comment by Freeride1986** [comment]
Hallo hamerheat, wie hast du Daten in ioBroker bekommen? ioBroker nutzte ich auch. 
Was muss man machen dass man zumindestens mal ein paar Werte bekommt.

Gruß Nils

**Comment by hamerheat** [comment]
Hallo Nils,

ich befürchte das ich dir nicht weiter helfen kann. Soweit mir bekannt hat der Smile B3 keine Modbus Schnittstelle, zumindest wird diese nicht unterstüzt.

Ich bin an der RS485 Schnittstelle mit einem RS485 zu TCP Umsetzer dran. 
Beim iobroker läuft der Modbusadapter und zeigt die Werte an.

Kennst Du bestimmt,  "https://www.storion4you.de/" war Modbus am B3 mal Thema.

Gruß
 Christian

**Comment by Lothar67** [comment]
Hallo Chrsitian,

ich habe ebenfalls einen Smile5 und ioBroker. Den Modbus Adaoter habe ich bereits installiert, aber ich bin mir nicht sicher, wo ich den RS485 Adapter am Smile5 anschließen kann. Der RS485 ist bereits durch die Backup Box belegt.
Kannst du mir da weiter helfen?
Vielen Dank im Voraus
Gruß
Lothar

**Comment by hamerheat** [comment]
Hallo Lothar,
gerne versuche ich dir zu helfen, soweit ich es kann.

Ich habe deinen Beitrag im Storion4you Forum gelesen. Ich vermute dein Adapter wir so nicht funktionieren. Hast du Informationen wie der RJ45 Stecker vom Adapter belegt ist?  

Ansonsten muss der Stecker im Umrichter ganz rechts in die mit "CAN" gekennzeichnete Buchse gesteckt werden.   
Der Modbus befindet sich auf den Adern bl(A+) + bl/ws(B-)

Bevor du mit den iobroker weiter machts, schaue mit einen Modbus Analyser ob deine Verbindung läuft.

Ich nehme ua. qModbus.  

Ich benutze zZ. folgende Hardware Adapter:
USR-TCP232-410S (RS485 nach LAN)   dieser geht Grundsätzlich, ich habe aber ständige Verbindungsabbrüche, die Verbindung wird automatisch sofort wieder aufgebaut.  Im Storion Forum habe ich etwas von einer fehlerhaften Implementation des Modbus-Protokolls gelesen, möglicherweise besteht da ein Zusammenhang, die Anfrage nach einem Update läuft.  

weiter habe ich noch 2 weitere RS485 Adapter:
Amxxxxn:  1. USB RS485 Adapter mit Gehäuse
                  2. RS485 USB zu RS 485 Konverter CH340 Chip
einfach mal nach der Bezeichnung suchen, eine Typenbezeichnung gibt es nicht

Diese Funktionieren grundsätzlich auch, mit qModMaster konnte ich Daten vom Umrichter auslesen.

Ich hoffe dir hilft das etwas weiter. Ansonsten weiter Fragen.... -)

Gruß
 Christian

**Comment by Lothar67** [comment]
Hallo Christian,

erst einmal vielen Dank für deine ausführliche Info.

Ich werde mir den USR-TCP232-410S bestellen.

Habe ich das richtig verstanden, dass ich ein Patchkabel halbiere, den RJ45 in den CAN Port stecke und die
Leitungen BL und BL/WS an den A+ und B- Anschluß des USR´s schließe?

Muss G (Ground) an die Schirmung des Patchkabels?

Ist eine Spannungsversorgung für den USR notwendig (was ich vermute)?

Den Netzwerkteil des USR stecke ich dann in meine Switch, richtig?

Das qModbus Tool habe ich mir herunter geladen und installiert.

Gruß
Lothar

**Comment by Lothar67** [comment]
Hallo Christian,
der Adapter ist da und die Verkabelung erledigt.
Wenn ich den RJ45 in den CAN Port stecke, leuchtet die RS485 LED am Adapter.
Der Adapter ist im Netzwerk zu erreichen.
Im Smile5 ist Modbus aktiviert.
Leider wird (noch) nichts übertragen. 

Wahrscheinlich ist das jetzt eine Einstellungssache.

Wird der Smile5 als Master oder als Slave eingestellt? (im Moment ist er Master)
Gibt es bei dem USR bestimmte Einstellungen (z.B. im RS485 Menü) auf die man achten muss?
Das gilt auch für das qModbus Tool?

Ich hoffe du kannst mir hier weiter helfen

Gruß
Lothar

**Comment by CraigN** [comment]
Hello. Sorry if I post in English as my German is still very basic.

I have been asking Alpha ESS for an API to integrate with and noticed your thread about it here. They sent me a document titled "Web Monitoring API Specification Document v2.1" which is fantastic however when I asked for access credentials for my application to access the API I was denied access as its only supported for business system integration partners.

I will keep you guys updated.

**Comment by Gaspode69** [comment]
@hamerheat
Oh, sorry. Hatte das hier total aus den Augen verloren.

> @Gaspod69, welche Firmware ist bei dir installiert?
V1.02.25A

> In iobroker sind auch schon einige Werte zusehen, manche passen, manche nicht.
Die meisten Werte konnte ich zuordnen bzw. berechnen. Leider fehlen mir noch drei der Energiewerte, darunter der interessanteste, nämlich die Erzeugung.

Ich habe im Storion4you mal einen Beitrag dazu aufgemacht.

**Comment by Nithoma** [comment]
> Hi, ich hab auch den Smile B3. Bin super zufrieden, die Chinesen rücken die API nicht raus. Die hatten sich das mal überlegt, aber ist für die zu viel Aufwand es zu pflegen war die Begründung. Aber es kann sein, dass sie trotzdem kommt. Der Chef war letztens in Deutschland, daher weiß ich das. Bin auch an so einem Adapter interessiert, da meine Wechselrichter kein Modbus haben.
> 
> Alternativ kann man auch per FHEM die Seite abgreifen und dann selber darstellen, ist aber auch n bisschen Aufwand wenn es auch einfacher gehen würde.
> 
> Daher bin ich auch an einem Adapter interessiert.

Für FHEM gibt es auch ein iobroker Adapter mit dem man alle FHEM Werte bekommt und dann im IOBroker weiterverarbeiten kann.
Solange es kein Alpha ESS Adapter für IOBroker gibt muß man wohl schauen ob man FHEM dazwischen hängt.

**Comment by Honk815** [comment]
> Hallo,
> 
> ich habe einen Smile 5 mit 11kW Akku. In iobroker sind auch schon einige Werte zusehen, manche passen, manche nicht.
> 
> @Gaspod69, welche Firmware ist bei dir installiert?
> 
> Gruß Christian

Hallo Christian,

ich habe seit kurzem ebenfalls einen Smile 5 mit 9,8kW Akku. Ich möchte es ebenfalls in iobroker integrieren. Kannst du mir schreiben, wie du das genau hinbekommen hast? :) bin hier echt am Verzweifeln. :(

VG Nico

**Comment by Gaspode69** [comment]
Hallo,
ich habe mich mal an einem Adapter versucht, ganz mutige können diese frühe Version mal ausprobieren:

https://github.com/Gaspode69/ioBroker.alpha-ess

Im Moment nur direkt aus GIT installierbar, d.h. noch nicht per NPM. 
Ich bitte um Nachsicht. Das ist mein erster Versuch und Javascript ist nicht wirklich meine Sprache. Es ist nur ein erster, früher Entwurf, d.h. es könnten sich in naher Zukunft auch noch grundlegende Dinge ändern.

Ich persönlich rate dazu, wenn immer möglich eher auf Modbus zu setzen, da die verwendete API eine undokumentierte, interne API ist und von heute auf morgen nicht mehr funktionieren könnte.

**Comment by Gaspode69** [comment]
Wenn jemand testet, die Ergebnisse bitte hier posten:
https://forum.iobroker.net/topic/60009/test-adapter-alpha-ess-v0-0-x-github

**Comment by lutzleonhardt** [comment]
Hallo @Gaspode69,
habe eben den Adapter installiert für eine SMILE-T10-HV-INV mit Speicher. Hat auf Anhieb funktioniert! Vielen lieben Dank für deine Mühe. VG

**Comment by Freeride1986** [comment]
Ganz große Klasse, danke für den Adapter. Ich habe einen Smile B3 also den kleinsten Speicher und es funktioniert auf Anhieb. Habe mir noch eine Erweiterung gekauft, da fehlt aber noch ein Verlängerungskabel. Wenn das angeschlossen ist, schau ich, ob das noch sauber klappt (aber warum auch nicht). Vielen Dank, auf das hatte ich die ganze Zeit gewartet.

**Comment by Gaspode69** [comment]
Freut mich, dass der Adapter bei euch tut, was er soll. Neuigkeiten poste ich immer im Forum:
https://forum.iobroker.net/topic/60009/test-adapter-alpha-ess-v0-0-x-github

@Freeride1986 
Was sollte den das "supertolle Blockly" machen? Evtl. etwas, das man sinnvoll in den Adapter integrieren könnte?

**Comment by mcm1957** [comment]
@Gaspode69 
Da der Adapter nun doch schon bei einigen Usern in Betrieb ist - und soweit ich das hier und im Forum lese - einwandfrei funktioniert, bitte überleg dih ihn in das offizielle Repo aufnehmen zu lassen:

https://github.com/ioBroker/ioBroker.repositories#add-a-new-adapter-to-the-latest-repository

**Comment by Gaspode69** [comment]
PR ist bereits erstellt:
https://github.com/ioBroker/ioBroker.repositories/pull/2087

**Comment by mcm1957** [comment]
> @mcm1957 PR ist bereits erstellt: [ioBroker/ioBroker.repositories#2087](https://github.com/ioBroker/ioBroker.repositories/pull/2087)

Ja danke - habs zu spät gesehen. Mea Culpa.
DANKE

**Comment by Gaspode69** [comment]
OK; das sollte man dann tatsächlich per Script außerhalb des Adapters lösen. Da gibt es viele Möglichkeiten.
Ggfs. kannst du ja mal einen entsprechenden Thread im Forum eröffnen. Da findet sich bestimmt jemand, der dir helfen kann. Ich selbst bin bei Blockly raus, nutze nur JavaScript.

**Comment by Gaspode69** [comment]
Hi, ich denke, die Diskussion könnte man hier schließen.[
Für weitere Diskussionen gibt es ja diesen Thread: https://forum.iobroker.net/topic/60009

**Comment by Gaspode69** [comment]
@mcm1957 
Könntest du dieses issue bitte schließen? Oder gibt es aus deiner Sicht einen Grund, es offen zu lassen?
Danke.

**Comment by DutchmanNL** [comment]
> @mcm1957 
> 
> Könntest du dieses issue bitte schließen? Oder gibt es aus deiner Sicht einen Grund, es offen zu lassen?
> 
> Danke.

Danke für die Erinnerung

**Comment by mcm1957** [comment]
Zum Repo: https://github.com/Gaspode69/ioBroker.alpha-ess
