### ISSUE TITLE
IoBroker Adapter für vis / sip / tr064 über asterisk

### ISSUE THREAD

**Issue by Knallochse** [ioBroker/AdapterRequests#353]
Wäre es möglich, das man diesen Adapter [https://github.com/iobroker-community-adapters/ioBroker.vis-sip-asterisk](url) so umzugestalten, dass man mit seinem VIS-Tablett über die Fritzbox telefonieren kann?
Vielleicht könnte man diesen Adapter direkt in den TR064 Adapter integrieren?

**Comment by Apollon77** [comment]
Bitte bei den Adaptern entsprechende Issues anlegen. Ich sehe aber keine sinnvolle Logik  vis-sip-asterisk  in tr-064 einzubauen
