### ISSUE TITLE
Envertech Solar

### ISSUE THREAD

**Issue by timomatrixer** [ioBroker/AdapterRequests#355]
The company Envertech Corporation Limited sells inverter for solar systems. There is a enverbridge available to interact with the inverter over powerline. The Bridge is connected via ethernet to the homenetzwerk and delivers his data to the envertech portal:
http://www.envertecportal.com/
Maybe it is possible to make a subserver-adapter to read the sent data. Or read the data from the portal directly.

**Comment by Balze2** [comment]
Both mentioned ways are possible. A proxy capturing the data and (do or don't) forward it to the envertec-portal (cloud free is possible) or reading the data from the envertec-portal. (cloud only)
Both has been done for fhem.

Details can be found here: https://forum.fhem.de/index.php?topic=61867.0 (German only)
There is an example perl script how to capture data from the cloud (envertec-portal).

An envertech proxy has been realized by MEitelwein, here:
https://gitlab.eitelwein.net/MEitelwein/Enverbridge-Proxy
There are sniffing-snippets included in his documentation.

A python lib for API access of the envertec-portal has been done by tkanerva, here:
https://github.com/tkanerva/enver-cloud-access

I'm waiting for my hardware. I may be able to give more infomation when it has arrived.

**Comment by timomatrixer** [comment]
Hey, nice. I didn't know about that. I already have this hardware and will test it.

**Comment by Balze2** [comment]
Hey Timomatrixer,

any news?

**Comment by adcrafter27** [comment]
I am currently building an adapter to load data from the web portal. 
But I am only at the beginning and only teach how to program everything, but the first steps already work

**Comment by mcm1957** [comment]
Adpter repository exists.
Adapter not yet released into any iobroker repository, request to do so posted (https://github.com/adcrafter27/ioBroker.envertech-pv/issues/12)

**Comment by mcm1957** [comment]
Adapter will be moved to iobroker-community-adapters. Work In Progress...

**Comment by mcm1957** [comment]
Release 1.0.0 is available for testing:
https://forum.iobroker.net/topic/64102/test-adapter-envertech-pv-v1-0-x-github
https://github.com/iobroker-community-adapters/ioBroker.envertech-pv

Request to add to latest queued: 
https://github.com/ioBroker/ioBroker.repositories/pull/2189

**Comment by mcm1957** [comment]
request for latest: https://github.com/ioBroker/ioBroker.repositories/pull/2273

**Comment by mcm1957** [comment]
Published at latest
