### ISSUE TITLE
Vorwerk Kobold VR200 - VR300

### ISSUE THREAD

**Issue by timomatrixer** [ioBroker/AdapterRequests#356]
Es gibt bereits den Adapter für den Saugroboter Kobold VR200 der Firma Vorwerk. Der ist allerdings nur zum Teil mit dem VR300 kompatible und deckt nicht die neuen Features ab, wie Raum-Auswahl. Vielleicht mag @Eisbaeeer / eisbaeeer@gmail.com den Adapter erweitern. Das wäre super klasse. Ich kann gerne unterstützen.

**Comment by Apollon77** [comment]
... Dann wäre es aber besser ggf erstmal einen Issue bei dem exiostierenden Adapter zu öffnen :-)

**Comment by timomatrixer** [comment]
Ja das stimmt, wenn es kein neuer Adapter VR300 werden soll. Was meint ihr?

**Comment by iansenkowalski** [comment]
wäre auch an dem Vr300 interessiert

**Comment by Eisbaeeer** [comment]
Es macht in meinen Augen keinen Sinn, einen neuen Adapter zu erstellen.  Begründung: Die Li rary ist die Selbe. Der Adapter muss lediglich um die Funktionen erweitert werden.

**Comment by Apollon77** [comment]
Dann schliessen wir hier. @timomatrixer @iansenkowalski Bitte isue beim Adapter öffnen
