### ISSUE TITLE
HP ILO Adapter installed v1.0.5 but installs 0.0.1 

### ISSUE THREAD

**Issue by niceguy0815** [ioBroker/AdapterRequests#358]
Hi,
i have installed the HP ILO Adapter installed v1.0.5 but it installs in v 0.0.1 now i see a Adapter Update to 1.0.5 it runns but after Update version is still 0.0.1 and wants to update the Adapter.

The Installation shows no error.
Is the version number in 1.0.5 wrong (0.0.1)
So iobroker wants to update it over and over again?
Ore do i need somthing special to install 1.0.5?

`$ ./iobroker upgrade hp-ilo
Update hp-ilo from @0.0.1 to @1.0.5
NPM version: 6.13.4
npm install iobroker.hp-ilo@1.0.5 --loglevel error --prefix "/opt/iobroker" (System call)
upload [3] hp-ilo.admin /opt/iobroker/node_modules/iobroker.hp-ilo/admin/words.js words.js application/javascript
upload [2] hp-ilo.admin /opt/iobroker/node_modules/iobroker.hp-ilo/admin/index_m.html index_m.html text/html
upload [1] hp-ilo.admin /opt/iobroker/node_modules/iobroker.hp-ilo/admin/index.html index.html text/html
upload [0] hp-ilo.admin /opt/iobroker/node_modules/iobroker.hp-ilo/admin/hp-ilo.png hp-ilo.png image/png
Adapter "hp-ilo" updated
process exited with code 0
`

<img width="1112" alt="iobrokerhpilo" src="https://user-images.githubusercontent.com/43955022/75769337-49794680-5d46-11ea-8d3e-a458db694006.png">

**Comment by Apollon77** [comment]
Please create this issue in the repo of the Adapter itself!
