### ISSUE TITLE
Adapter für Gartenbewässerung

### ISSUE THREAD

**Issue by Kuddel071089** [ioBroker/AdapterRequests#361]
Hallo zusammen,

ich habe gerade die Steuerung für meine Gartenbewässerung komplett in Blockly realisiert.

Vllt. wäre es möglich dafür einen Adapter so zu erstellen, wie der Heat- oder Shutter-Control Adapter.

Als Einstellunsmöglichkeiten dachte ich an folgende:

- Anzahl Ventile
- Name Ventil (z.B: Ventil 1 = Rasen, Ventil 2 = Beet etc.)
- Einzelne Ventile aktivieren / deaktivieren
  -Kanal pro Ventil zum Schalten
  -Schaltdauer
  -PulsTime (Sonoff) / ON_TIME (Homematic) (Ja + Dauer / Nein)
- Ventile nacheinander aktiveiren (Ja / Nein)
- Ventile X und Y parallel

Als DPs wäre es klassen, wenn folgendes generiert werden würde:

- Endzeit gesamt (z.B. 18:52:01 Uhr)
- Restlaufzeitzeit gesamt (z.B. 15:06 Minuten)
- Endzeit pro Ventil 
- Restlaufzeit pro Ventil

Ich hoffe ich konnte meine Ideen einigermaßen rüberbringen :-)

So sieht das Ganze aktuell in meiner ioBroker VIS aus

![bewaesserung](https://user-images.githubusercontent.com/34958991/75922592-99016480-5e63-11ea-8c0c-a136be2df39f.PNG)

**Comment by darkiop** [comment]
Gute Idee - aktuell hab ich das auch über ein Blockly gelöst - bzw. Steuer das mit einer Art Halbautomatik nach Gefühl. Interessant wäre auch ein oder mehre DPs mit der Bodenfeuchte.

**Comment by darkiop** [comment]
Passend hierzu auch https://forum.iobroker.net/topic/29559/iobroker-mit-feuchtesensor-zur-rasenbew%C3%A4sserung

**Comment by Bono5** [comment]
habe meine Bewässerungssteuerung über Blockly gelöst. Bei weitem nicht so umfangreich wie Kuddel.
Ganz tolle Arbeit!! Umsetzung als Adapter wäre super!!

**Comment by TA2k** [comment]
https://forum.iobroker.net/topic/44493/test-adapter-sprinkle-control-0-1-4-latest

**Comment by h07d0q** [comment]
.

TA2k ***@***.***> schrieb am Mo., 26. Juli 2021, 08:17:

**Comment by TA2k** [comment]
Please assign to 
Dirk-Peter-md

**Comment by Apollon77** [comment]
I can as soon as he accepts invitation

**Comment by ldittmar81** [comment]
@Apollon77 can be closed. Its stable
