### ISSUE TITLE
Stromzähler Enera 

### ISSUE THREAD

**Issue by j3sk0** [ioBroker/AdapterRequests#362]
Hallo, 

ein Adapter für Projekt Enera wäre wünschenswert. API aktuell noch nicht vorhanden. 
https://projekt-enera.de/

**Comment by DutchmanNL** [comment]
Schwierig ohne API, irgendwie müssen wir ja an die Daten ran kommen

**Comment by oliverrahner** [comment]
Ich habe gerade den ersten Wurf eines Addons für OpenHAB gebaut, vielleicht könnt ihr euch da was abschauen: https://github.com/oliverrahner/openhab-addons/tree/enera-binding/bundles/org.openhab.binding.enera

Ich habe im Zuge der Implementierung auch eine Mini-Experimentierversion gebaut, in C# und Java, wenn ihr Interesse habt.

Kurzüberblick:
- Login läuft über Amazon Cognito
- man verbindet sich zu einem MQTT-Server und published dort in ein bestimmtes Topic eine Registration Message, die u.a. den oben erhaltenen Id-Token erhält
- dann bekommt man ~1 mal pro Sekunde (genau so oft, wie in der App) die aktuellen Werte als JSON in ein Topic gepusht

**Comment by j3sk0** [comment]
Hi, ich komme nochmal auf das Thema zurück, ich habe leider nicht das technische Wissen für die Übersetzung deines Projektes in iobroker bzw. Integration in Grafana. Kannst du das evtl. noch weiter erläutern? Oder könnten wir uns anderes absprechen?

**Comment by oliverrahner** [comment]
Ohne Entwicklungs-Knowhow wird das leider nichts... Ich habe aber leider keine Erfahrung in ioBroker, daher kann ich selbst da nicht helfen.
Der Hinweis oben galt einem potenziellen Entwickler eines Adapters für ioBroker als Hilfestellung, um die Konzepte zu verstehen.

**Comment by j3sk0** [comment]
Ich nutze seit längerem jetzt die Grund fw von dem eigentlichen Hersteller smart-me. Hierzu gibt es auch eine Adapter anfrage. https://github.com/ioBroker/AdapterRequests/issues/291
