### ISSUE TITLE
Mini Countryman SE

### ISSUE THREAD

**Issue by wendfrsg** [ioBroker/AdapterRequests#372]
Hello Guys, 
I´m a privat user without any programming knowledges. 
I´d like to show some Datas of the mini Countryman SE on my screen. Such as charging Level etc. 
Is there any adapter available already? ;)
THX for your assistance. 
best regards
Frank

**Comment by Apollon77** [comment]
Is there any way to get such daat? App? An API? Other projects that read out the data? Please provide more details!

**Comment by wendfrsg** [comment]
Well there is just the official Mini Connected app available in Playstore ... 
and of course the Website.... https://www.mini-connected.com/germany/de

**Comment by Coffee-lover** [comment]
I would assume it's quite similar to the BMW app. @wendfrsg Due to missing hardware I cannot check, but you could try to log in into BMW App with you Mini Login information.

**Comment by wendfrsg** [comment]
HI Guys out there ;) 
any news how to display the status informations for the mini countryman SE without offering my log in informations ?! ;) 
THX

**Comment by TA2k** [comment]
@wendfrsg please check if this is working for you
https://forum.iobroker.net/topic/46720/test-adapter-bmw-v2-0-0?_=1628010315225

**Comment by TA2k** [comment]
@ldittmar81
