### ISSUE TITLE
1und1 TV

### ISSUE THREAD

**Issue by BassT23** [ioBroker/AdapterRequests#380]
gibt es hier vielleicht jemanden, der einen Adapter für 1und1 TV basteln kann?

ich möchte zb gerne den https://www.1und1.tv/guide in meine Vis einbinden. Leider schlägt aber der Login fehl (im iframe Widget).
Wenn man dann noch daraus die App, mit gewähltem Programm im Vollbild starten könnte, ... *freu*

Vielen Dank

**Comment by Apollon77** [comment]
Gibt es mehr Details? Eine API? Haben es andere Smart Home Systeme bereits angebunden? Gibt es Libraries?

**Comment by Prosti95** [comment]
Ich würde die Programmzeitschrift aus einer anderen Quelle nutzen, also evtl. die TV-Spielfilm API.
Für das Abrufen der Streams gibt es bereits das Projekt [Telerising](https://github.com/sunsettrack4/telerising/blob/master/README.md#the-following-providers-domain-names-are-supported). Grundsätzlich zapft das anscheinend Zattoo an unterstützt aber auch 1und1.TV. Das Abspielgerät muss jedoch mit m3u Playlists klarkommen. Ich glaube da könnte man sich schon etwas basteln. Telerising könnte man sich auch unabhängig vom ioBroker aufsetzen und mit Kodi abrufen. Kommt ein bisschen auf Deinen Einsatzzweck an.

**Comment by BassT23** [comment]
die Telerising gedschichte habe ich hier gefunden: https://www.kodinerds.net/index.php/Thread/68738-1-1-TV-schauen-mittels-Kodi-Addon-geht-das/

Werde es mir mal genauer anschauen. Kodi ist grundsätzlich möglich, entweder mit fireTV oder ich setz es zusätzlich auf meinem Video Server auf, ...

Einsatz war ursprünglich geplant als; Vis Seite -> Guide (läuft auf Android Tab mit fullybrowser) und von dort aus per klick den stream (über vlc oder direkt 1und1 TV App). Wobei bei 1und1 App die nächste schwierigkeit der direkte Vollbild wird, ...

Grüße
Bleibt gesund!

**Comment by oweitman** [comment]
https://www.iobroker.net/#de/adapters/adapterref/iobroker.tvprogram/README.md
und
https://github.com/oweitman/ioBroker.tvprogram

mittlerweile auch auf latest verfügbar.

**Comment by BassT23** [comment]
> https://www.iobroker.net/#de/adapters/adapterref/iobroker.tvprogram/README.md
> und
> https://github.com/oweitman/ioBroker.tvprogram
> 
> mittlerweile auch auf latest verfügbar.

Gleich mal ausprobiert. Ist zwar kein 1und1 Adapter, aber ein super zu verwendendes EPG.

Grüße

**Comment by oweitman** [comment]
wenn es irgendeine Möglichkeit gibt dein 1und1TV anzusteuern, dann habe ich Schnittstellen eingebaut, mit dem du bspw den Kanal umschalten kannst.
Im supportthread gibt es diverse diskussionen dazu
https://forum.iobroker.net/topic/40168/test-adapter-tvprogram?_=1616014970136

**Comment by ldittmar81** [comment]
@Apollon77 Can be closed. Its stable
