### ISSUE TITLE
SolarMax Wechselrichter data request

### ISSUE THREAD

**Issue by godlich** [ioBroker/AdapterRequests#381]
There is already a pearl, a python and a simple C code to request the data, but no JavaScript Code. 

- [Here is the C Code](https://www.photovoltaikforum.com/thread/52179-solarmax-datenlogger/?pageNo=1)

- [Here the python Code](https://github.com/bwurst/python-solarmax/blob/master/lib/solarmax.py) 

- [Here the Pearl code ](https://2007.blog.dest-unreach.be/2009/04/15/solarmax-maxtalk-protocol-reverse-engineered/)

The Adapter should simply request data via TCP from the solar inverter. Many thanks for any help to develop the adapter.

**Comment by SimonBard** [comment]
hat sich erledigt, hab selbst was geschrieben, werde es im Forum veröffentlichen nachdem ich es selbst genug getestet habe.

**Comment by Farmer-cb** [comment]
gibts schon was neues, hätte auch interesse daran

**Comment by SimonBard** [comment]
Ist entwickelt und getestet, muss es nur noch auf github pushen.

**Comment by DutchmanNL** [comment]
@SimonBard teilst du bitte noch den repo link ?

**Comment by Scotty-89** [comment]
hey wollte mal fragen ob es den Adapter noch gibt und ob er aktuell auch tut ?
