### ISSUE TITLE
Rotex HPSU Wärmepumpe über ELM327 CAN-Bus

### ISSUE THREAD

**Issue by Easyrunner** [ioBroker/AdapterRequests#386]
Hallo zusammen,

das Partnerforum FHEM hat es schon vorgemacht:
[https://forum.fhem.de/index.php/topic,106503.0.html](url)
Hier klappt die Anbindung einer Rotex HPSU Wärmepumpe durch den CAN-Bus und einem ELM327 OBD Interface.
Das Interface wird per USB an den Host angeschlossen oder, noch besser, über Bluetooth.

**Comment by shortcircuit0815** [comment]
Durchaus eine schöne Alternative wäre auch eine Anbindung via Ethernet, bspw. mit einem RasperryPi und RS485 CAN HAT.

**Comment by shortcircuit0815** [comment]
Habe es mit dem [Projekt von Spanni26](https://github.com/Spanni26/pyHPSU) gelöst.
Ein "Pican 2" Board auf einem RaspbeeryPi montiert liefert die Daten via ssh-Anfrage (durch Node-Red) an den ioBroker.
Vielleicht hilft das dem ein oder anderen als Workaround.

**Comment by Trunks1982** [comment]
Hi, mit dem Can Modul ist es möglich ohne fhem in Io die Rotex zu steuern.Es gibt auch schon eine Config Datei zum Download wo man direkt mit loslegen kann.

**Comment by Bonda85** [comment]
> ![3FC9FFA1-4F8B-4C70-88CD-41A9A5C76F6C](https://user-images.githubusercontent.com/62701386/145683877-bec5ea4f-4492-490b-a775-08d4d975cc30.jpeg)
> 
> Hi, mit dem Can Modul ist es möglich ohne fhem in Io die Rotex zu steuern.Es gibt auch schon eine Config Datei zum Download wo man direkt mit loslegen kann.

Guten Abend, könnten Sie es mir bitte verraten, wie ich das ganze ohne FHEM machen kann? Gibt es irgendwo ein tutorial dafür? Welches Can Modul ist dafür notwendig? Gruß, Alex

**Comment by crycode-de** [comment]
An einem Raspberry Pi ist das Einfachste ein fertiges CAN HAT (z.B. von [Waveshare](https://www.waveshare.com/rs485-can-hat.htm)) mit MCP2515 CAN-Controller zu verwenden.
Eine Anleitung zum CAN-Bus am Raspi habe ich hier geschrieben: https://crycode.de/can-bus-am-raspberry-pi

Die HPSU arbeitet mit einer Bitrate von 20 kbit/s auf dem CAN-Bus.

Die Integration in ioBroker ist dann mit meinem Adapter [ioBroker.canbus](https://github.com/crycode-de/ioBroker.canbus) möglich. Dazu einfach den Adapter installieren und in der Adapterconfig die vordefinierte Config von GitHub für die Rotex HPSU laden. Da sind dann jede Menge Daten enthalten, die ausgelesen, abgefragt und gesetzt werden können.

**Comment by Elektroniker0486** [comment]
Moin,

wo finde ich denn "die vordefinierte Config von GitHub für die Rotex HPSU"

**Comment by crycode-de** [comment]
> wo finde ich denn "die vordefinierte Config von GitHub für die Rotex HPSU"

In der Instanzkonfiguration des Adapters gibt es unter "Import / Export" einen Button "Konfigurationen von GitHub abrufen". 

![grafik](https://user-images.githubusercontent.com/24603271/156993550-71b5cb38-5e78-43bd-9fa7-d47602122b31.png)

Nachdem du den angeklickt hast, kannst du die HPSU Konfiguration direkt in den Adapter laden.

![grafik](https://user-images.githubusercontent.com/24603271/156996942-272a4e66-4253-4909-b5ec-5cb943396d1c.png)

Auf GitHub findest du die Konfiguration in den verschiedenen Versionen [hier](https://github.com/crycode-de/ioBroker.canbus/tree/master/well-known-messages/configs).

**Comment by Elektroniker0486** [comment]
Ist ja geil. Ok das hab ich nun geschnallt. Ich hätte aber doch noch ein paar Fragen.
Ich bekomme diese Woche eine Daikin Altherma 3 H HT mit dem ECH2O (ETSX16P50D) diese würde ich sehr gerne in mein ioBroker integrieren und finde deine Lösung mit dem Pi und dem HAT sehr sinnvoll. Soll ich vielleicht lieber in ioBroker ein neues Thema eröffnen damit andere auch was davon haben ich bin vermutlich ja nicht der einzige mit dieser Anlage.

**Comment by crycode-de** [comment]
Siehe https://forum.iobroker.net/topic/52171/rotex-hpsu-daikin-altherma-w%C3%A4rmepumpe-%C3%BCber-iobroker-canbus 
Da passen deine Fragen bestimmt gut mit rein oder sind vlt. sogar schon beantwortet. 😉
