### ISSUE TITLE
HP iLO Server

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/AdapterRequests#39]
Lösung per JavaScript bereits vorhanden, Konfiguration per Adapter end-user tauglicher: http://forum.iobroker.net/viewtopic.php?t=6501

Migrated from Trello with 0 votes

**Comment by SebastianSchultz** [comment]
Ich hätte einen HP Microserver Gen8 mit ILO.
Ich könnte theoretisch daraus auch einen Adapter bauen.

Soll ich???

**Comment by SebastianSchultz** [comment]
@Apollon77 Was muss ich tun damit dieses Issue mir zugewiesen wird?

**Comment by SebastianSchultz** [comment]
https://github.com/SebastianSchultz/ioBroker.hp-ilo

**Comment by Apollon77** [comment]
cool

**Comment by SebastianSchultz** [comment]
Brauche nur nochmal Hilfe wie ich das dann irgendwann ins offizielle Repository bekomme, wenn ich Readme etc. fertig habe.

**Comment by Apollon77** [comment]
https://github.com/ioBroker/ioBroker.repositories#requirements-for-adapter-to-get-added-to-the-repository :-)
