### ISSUE TITLE
Adapter for Sindoh 3D printers

### ISSUE THREAD

**Issue by drtp** [ioBroker/AdapterRequests#395]
I would like to see an ioBroker adapter for the Sindoh 3D printers that is at least capable in showing the information of the respective Sindoh App or the IP address.

![2020-04-29_13h41_03](https://user-images.githubusercontent.com/17758445/80592569-f78c2e80-8a1f-11ea-9d78-36ac43480918.png)

**Comment by DutchmanNL** [comment]
is there any information available like kind fo device, api interface or else ?
I don't know the devices in basic, mostly I use octoprint to connect 3d printers to ioBroker.

**Comment by drtp** [comment]
Well, I'm afraid there is no API available. The only thing, I currently have, is the source code of the above webpage, if this helps.

`<!doctype html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=Edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="cache-control" content="no-cache, must-revalidate">
	<meta http-equiv="pragma" content="no-cache">
	<link rel="icon" type="image/x-icon">
	<title>Webmonitor</title>
	<link rel="stylesheet" type="text/css" charset="utf-8" href="/css/jquery-ui.css" />
	<link rel="stylesheet" type="text/css" charset="utf-8" href="/css/custom.css?0084" />
	<link rel="stylesheet" type="text/css" charset="utf-8" href="/css/bootstrap.css" />
	<link rel="stylesheet" type="text/css" charset="utf-8" href="/css/bootstrap-dialog.css" />
	<link rel="stylesheet" type="text/css" charset="utf-8" href="/css/fonts.css" />

<script src="/js/jquery.min.js" charset="utf-8"></script>
<script src="/js/jquery.cookie.js" charset="utf-8"></script>
<script src="/js/jquery-ui.js" charset="utf-8"></script>

<script src="/js/common.js?0084" charset="utf-8"></script>
<script src="/js/jquery.keyboard.js" charset="utf-8"></script>
<script src="/js/bootstrap.js" charset="utf-8"></script>
<script src="/js/bootstrap-dialog.js" charset="utf-8"></script>

<style>
	#pwd_window_for_security>.modal-backdrop.in {
	opacity: 1.0;
}
</style>
<script type="text/javascript" charset="utf-8">

	C_or_F_flag = 0;
	var statrt_streaming = true;
	saved_filename = null;
	marquee_flag = false;
	f = $(".marquee").text();
	var screen_width = screen.availWidth;
	var scrren_height = screen.availHeight;
	var alert_msg_Correct;
	var alert_msg_Incorrect;
	var label_please_enter_pw;
	var btn_ok;
	var btn_cancel;
	$("document").ready(function () {
	
		// $('.bs-example-modal-sm').on('shown.bs.modal', function () {
		// 	$('#pwd').focus();
		// });

		$('.modal').on('shown.bs.modal', function() {
			$(this).find('[autofocus]').focus();
		});

		var filter = "win16|win32|win64|mac|macintel|linux i686|linux x86_64";
		if (navigator.platform) {
			if (filter.indexOf(navigator.platform.toLowerCase()) < 0) {
				$(".title").css("font-size", "170%").css("height", "50%");
				$(".nozzle").css("font-size", "100%");
				$(".bed").css("font-size", "100%");
				$(".nozzle_label").css("font-size", "90%");
				$("#Nozzle_value").css("font-size", "100%");
				$(".bed_label").css("font-size", "90%");
				$("#Bed_value").css("font-size", "100%");
				if (get_cookie("language_choice") == 0) { //english
					if (screen_width < 330) {
						$(".control_print").css("font-size", "80%");
					} else {
						$(".control_print").css("font-size", "100%");
					}
				} else { //kor, chn
					$(".control_print").css("font-size", "100%");
				}
				$("#filament_material").css("font-size", "80%");
			} else {
				$('.container').width('480px');
			}
		}
		$('#imagee').height($('.preview').width());
		$('#imagee').width($('.preview').height());
		$(window).resize(function () {
			if (navigator.platform) {
				if (filter.indexOf(navigator.platform.toLowerCase()) < 0) {
					$('#imagee').height($('.preview').width());
					$('#imagee').width($('.preview').height());
				} else {
					$('.container').width('480px');
				}
			}
		});
		if (f.length > 17) {
			$('.marquee').html("<marquee>" + f + "</marquee>");
			$('.marquee').addClass("marquee_on");
			$('.marquee').removeClass("marquee_off");
		} else {
			$('.marquee').html(f);
			$('.marquee').addClass("marquee_off");
			$('.marquee').removeClass("marquee_on");
		}
		$('.saved').bind("DOMSubtreeModified", function () {
			// console.log('A');
			f = $('.marquee').text();
			if (f.length > 17) {
				// console.log('name is longer');
				$('.marquee').html("<marquee>" + f + "</marquee>");
				$('.marquee').addClass("marquee_on");
				$('.marquee').removeClass("marquee_off");
			} else {
				// console.log('name is short');
				$('.marquee').html(f);
				$('.marquee').addClass("marquee_off");
				$('.marquee').removeClass("marquee_on");
			}
		});
	});

	function security_access(){

		var pw_security = $("#pwd_for_security").val();
		$.ajax({
			url: "/cgi-bin/cancel_job.cgi",
			type: "post",
			dataType: "text",
			data: "&type=security.access&pwd=" + pw_security,
			async: false,
			success: function (result) {
				// console.log(result);
				if (result != 0) {//security pw fail

					$("#pwd_window_for_security_modal_header").text(alert_msg_Incorrect).css("color", "red", "text-align", "center").effect('shake', {times:1, direction: "up", distance: 6}, 500);
					$('#pwd_for_security').val("");

				} else {//security pw ok
				
					$("#pwd_window_for_security").modal().hide();
					var date = new Date();
					var minutes = 30;
					date.setTime(date.getTime() + (minutes * 60 * 1000));
					$.cookie("secured", "On", { expires: date });

					location.reload();

					// console.log("asdfasdf");
				}
			}
		});
	}

	function click_cancel() {
		$('#please_pw_id').text(label_please_enter_pw);
		$('#btn_ok_id').text(btn_ok);
		$('#btn_cancel_id').text(btn_cancel);
	}
	function new_cancel() {
		var pwdd = $('#pwd_window');
		pwd_value = pwdd.find('input').val();
		cancel(pwd_value);
	}
	function cancel(enter_pw) {
		$.ajax({
			url: "/cgi-bin/cancel_job.cgi",
			type: "post",
			dataType: "text",
			async: false,
			data: "&type=cancel.data&pwd=" + enter_pw,
			success: function (result) {
				if (result != 0) {
					if (get_cookie("language_choice") == 1) {}
					BootstrapDialog.show({
						title: " ",
						size: "size-large",
						type: "type-danger",
						message: alert_msg_Incorrect,
						buttons: [{
							label: btn_ok,
							cssClass: 'btn-danger',
							autospin: false,
							action: function (dialogRef) {
								dialogRef.close();
							}
						    }]
					});
					$('#pwd').val("");
				} else {
					BootstrapDialog.show({
						title: " ",
						size: "size-large",
						type: "type-primary",
						message: alert_msg_Correct,
						buttons: [{
							label: btn_ok,
							cssClass: 'btn-primary',
							autospin: false,
							action: function (dialogRef) {
								dialogRef.close();
							}
						    }]
					});
					$('#pwd').val("");
				}
			}
		});
	}
	function update_data() {
		// console.log("update_data called");
		$.ajax({
			url: "/cgi-bin/config_periodic_data.cgi",
			type: "post",
			async: false,
			dataType: "text",
			data: "&type=inform.data",
			success: function (s) {
				// console.log("msq wakeup");
				eval(s);
			}
		});
	}

	function getUTCNow()
	{
		var now = new Date();
		var time = now.getTime();
		var offset = now.getTimezoneOffset();
		offset = offset * 60000;
		return time - offset;
	}

	function getUTCNowAfter30()
	{
		var now = new Date();
		var time = now.getTime();
		var offset = now.getTimezoneOffset();
		offset = offset * 60000;
		return time - offset + 18000000;
	}

	function update_ui() {

		// console.log("update_data called and false");

		if (statrt_streaming == true) {
			var dt = new Date();
			var img = document.getElementById('imagee');
			var src_url = "/?action=snapshot&n=" + dt.getTime();
			img.src = src_url;		

		}			
				
	}

	function init(){
		// remove_cookie("");
	}



	function body_onload() {

		clear_cookie_just_use();		
		// console.log(get_cookie("secured"));

		get_tli(); //just set cookie value 'machien_tli' as TLI(3DP200, ST3DP1 ...etc) : remove cookie, and set_cookie
		getSpoolMode(); // get spool mode value in DB and set cookie value

		update_data();
		
		set_language(); //: remove cookie, and set_cookie
		get_secured();
		setTimeout(function() {
			language_type();

			if(parseInt(get_cookie("secured_setting"))==1)
			{
				if(get_cookie("secured")==""){
				
					$("#pwd_window_for_security").modal(
						{
							keyboard: false,
							backdrop: 'static'
						}
					);
					$("#pwd_window_for_security_modal_header").text(label_please_enter_pw);
					$("#security_ok_button").text(btn_ok);			
				}
			}

			// debugger;
			// setTimeout(function(){
			// 	//do what you need here
			// }, 2000);

			setInterval(update_ui, 1000);
			setInterval(update_data, 10000);
			// update_ui();
		}, 100);
	}
	
	// m_setImg = document.getElementById('imagee');

	function time_calculating(Estimatetime, PrintJobprocessing){

		//Estimatetime is seconds
		//mins = Estimatetime/60
		//hours = (Estimatetime/60)/60

		// var percent = PrintJobprocessing;
		// var remain_time = Estimatetime*(1- percent*0.01);

		// remain_time_min = parseInt(remain_time/60); // mins

		// var calc_hours = parseInt(remain_time_min/60); //hours
		// var calc_mins = parseInt(remain_time_min%60); //mins

		// if(calc_hours==0 && calc_mins==0) calc_mins=1;

		// // console.log(calc_hours, calc_mins);
		
		// // if(remain_time==0 || percent ==100){
		// if(remain_time==0){
		// 	$(".ctime").hide();

		// }else{
		// 	$(".ctime").show();

		// 	// console.log(remain_time);
		// 	$("#estimation_time_hour").text(calc_hours);
		// 	$("#estimation_time_min").text(calc_mins);
		// }

		// new code
		
		progressRatioPercent = PrintJobprocessing;
		// remainTimeSecond = this.estimationTime*(1 - progressRatioPercent*0.01);	// 초 단위
		// remainTotalTimeMinute = parseInt(remainTimeSecond/60);
		// remainTimeHour = parseInt(remainTotalTimeMinute/60);
		// remainTimeMinute = parseInt(remainTotalTimeMinute%60);

		remainTotalTimeMinute = parseInt(Estimatetime/60);
		remainTimeHour = parseInt(remainTotalTimeMinute/60);
		remainTimeMinute = parseInt(remainTotalTimeMinute%60);
		remainTimeMinuteFinal = (remainTimeHour*60 + remainTimeMinute)*(1 - progressRatioPercent*0.01);	// 초 단위

		remainTimeHour = parseInt(remainTimeMinuteFinal/60);
		remainTimeMinute = parseInt(remainTimeMinuteFinal%60);
		
		if (remainTimeHour == 0 && remainTimeMinute ==0) {
			remainTimeMinute = 1;
		}
		
		if(remainTimeMinuteFinal==0){
			$(".ctime").hide();
		}
		else {
			$(".ctime").show();			
			$("#estimation_time_hour").text(remainTimeHour);
			$("#estimation_time_min").text(remainTimeMinute);
		}		

	}

	function set_status(Estimatetime, PrintJobStatus, PrintJobprocessing, filamentRemain, filamentSub, R, G, B, Material, bedTemp, NozzleTemp, FileName) {

		// console.log("C_or_F: "+C_or_F_flag );
		// console.log("set_status: "+Estimatetime, PrintJobStatus, PrintJobprocessing, filamentRemain, filamentSub, R, G, B, Material, bedTemp, NozzleTemp, FileName);


		time_calculating(Estimatetime, PrintJobprocessing);

		// if(FileName=="gcodefile.gcode"){
		// 	FileName="Cloud Printing...";
		// }

		// console.log("PrintJobStatus: "+PrintJobStatus);

		if (NozzleTemp <= 50) {
			$("#Nozzle_value").css('color', '#0082D4');
			$(".orange").css('color', '#0082D4');
			// 51~150 orange	
		} else if (50 < NozzleTemp && NozzleTemp <= 150) {
			$("#Nozzle_value").css('color', 'orange');
			$(".orange").css('color', 'orange');
			// 150~ red
		} else {
			$("#Nozzle_value").css('color', '#C9302C');
			$(".orange").css('color', '#C9302C');
		}
		if (bedTemp <= 50) {
			$("#Bed_value").css('color', '#0082D4');
			$(".blue").css('color', '#0082D4');
			// 51~150 orange	
		} else if (50 < bedTemp && bedTemp <= 150) {
			$("#Bed_value").css('color', 'orange');
			$(".blue").css('color', 'orange');
			// 150~ red
		} else {
			$("#Bed_value").css('color', '#C9302C');
			$(".blue").css('color', '#C9302C');
		}
		if (C_or_F_flag == 1) {
			bedTemp = Celsius_to_Fahrenheit(bedTemp);
			NozzleTemp = Celsius_to_Fahrenheit(NozzleTemp);
			$(".orange").text("°F");
			$(".blue").text("°F");
		} else {
			$(".orange").text("˚C");
			$(".blue").text("˚C");
		}
		if (FileName.length == 0) {
			$('.marquee').empty();
		}


		var visi = true;

		loading_visible(0);


		if (PrintJobStatus == 9999 && PrintJobprocessing == 9999 && filamentRemain == 9999 && filamentSub == 9999 && Material == 9999 && bedTemp == 9999 && NozzleTemp == 9999) {

			// alert("machine  is not ready");
		
			if (visi == true) loading_visible(1);
			$("#Nozzle_value").text(""); // 노즐온도
			$("#Bed_value").text(""); // 베드 온도
		} else if (PrintJobStatus == 9999 && PrintJobprocessing == 9999) {
			if (visi == true) loading_visible(0);
			$("#Nozzle_value").text(NozzleTemp); // 노즐온도
			$("#Bed_value").text(bedTemp); // 베드 온도
		} else {
			if (visi == true) loading_visible(0);
			$("#Nozzle_value").text(NozzleTemp); // 노즐온도
			$("#Bed_value").text(bedTemp); // 베드 온도
		}
		var jobprocessing = PrintJobprocessing;
		if (PrintJobStatus == 10006) {
			printing_percentageFunc(0);
		} else {
			if (jobprocessing == 9999) { //undefined system loading..
				jobprocessing = 0;
			}
		}
		printing_percentageFunc(jobprocessing);
		if (PrintJobStatus == 9999 || PrintJobStatus == 10001 || PrintJobStatus == 10006) {
			$(".control_print").attr('disabled', true);
		} else if (PrintJobStatus == 10002 || PrintJobStatus == 10003 || PrintJobStatus == 10023 || PrintJobStatus == 10021 || PrintJobStatus == 10018) {
			$(".control_print").attr('disabled', false);
		} else {
			$(".control_print").attr('disabled', true);
		}
		
		if (f != FileName) {
			$('.marquee').text(FileName);
			$(".saved").text("ch");
			f = FileName;
		}
		
		// f = FileName;
		var Colorinfo = "#" + R + G + B;

		
		if ( (PrintJobStatus == 10007) || (PrintJobStatus==10004) || (PrintJobStatus==10006	) ||  (PrintJobStatus==10028)){
			$('.marquee').empty();
			f="";
			FileName="";
			$(".ctime").hide();
		}
		// console.log(Colorinfo);
		// Colorinfo ="#000000";
		// console.log(Colorinfo);	
		if(Colorinfo=="#000000"){
			$(".bg_white").css({"border-width": "thin", "border-style": "solid", "border-color": "white"});
		}
		
		$(".bg_white").css("background-color", Colorinfo);

		// console.log("Maerial is " + Material);
		if (Material == 1) { // PLA
			$("#filament_material").text("PLA").css("color", "white");
		}else if (Material == 2){ // ABS
			$("#filament_material").text("ABS").css("color", "white");
		}else if (Material == 3){ // ABS
			$("#filament_material").text("WOOD").css("color", "white");
		}else if (Material == 4){ // ABS
			$("#filament_material").text("HIPS").css("color", "white");
		}else if (Material == 5){ // ABS
			$("#filament_material").text("PETG").css("color", "white");
		}else if (Material == 13){ // ASA
			$("#filament_material").text("ASA").css("color", "white");
		}else if (Material == 255){ // no cartridge
			$("#filament_material").text(" ").css("color", "white");
		}else {
			$("#filament_material").text("ETC").css("color", "white");
		}

		if ($(".control_print").attr("disabled") == "disabled") {
			$(".control_print").attr("opacity", "0.1");
		} else {
			$(".control_print").attr("opacity", "1.0");
		}


		if(parseInt(get_cookie("spoolMode"))==1) {	// if spoolMode is on
			// cartridge reamin is 0, cartridge battery border is 0
			$('div.col-xs-3.color').css('border', '0px');
			$("#cartridge_20").addClass('display_none');
			$("#cartridge_40").addClass('display_none');
			$("#cartridge_60").addClass('display_none');
			$("#cartridge_80").addClass('display_none');
			$("#cartridge_100").addClass('display_none');
			// $('div.col-xs-3.color').text("Open Material").css('font-size', '130%').css('color', 'white').css('text-align', 'center').css('font-weight', 'bold').css("padding-top", "0.3em").css("padding-left", "0em").css("padding-right", "0em");
		}

		else {	// if spoolMode is off or (maybe) there is no cookie spoolMode
			if (Material == 255) {	// 재질정보가 255 라는건 필라멘트가 장착되지 않았다는 의미
				// 참고로 쉐어드 메모리에서 잔량은 이전에 있던 정보가 그대로 올라온다...
				$('div.col-xs-3.color').css('border', '0px');
				$("#cartridge_20").addClass('display_none');
				$("#cartridge_40").addClass('display_none');
				$("#cartridge_60").addClass('display_none');
				$("#cartridge_80").addClass('display_none');
				$("#cartridge_100").addClass('display_none');
			}
			else {
				$('div.col-xs-3.color').css('border', '2px solid white');
				if (filamentRemain <= 10) {
					$("#cartridge_20").addClass('display_none');
					$("#cartridge_40").addClass('display_none');
					$("#cartridge_60").addClass('display_none');
					$("#cartridge_80").addClass('display_none');
					$("#cartridge_100").addClass('display_none');
				} 
				else if (filamentRemain <= 20) {
					$("#cartridge_20").removeClass('display_none');
					$("#cartridge_40").addClass('display_none');
					$("#cartridge_60").addClass('display_none');
					$("#cartridge_80").addClass('display_none');
					$("#cartridge_100").addClass('display_none');
				}
				else if (filamentRemain <= 40) {
					$("#cartridge_20").removeClass('display_none');
					$("#cartridge_40").removeClass('display_none');
					$("#cartridge_60").addClass('display_none');
					$("#cartridge_80").addClass('display_none');
					$("#cartridge_100").addClass('display_none');
				}
				else if (filamentRemain <= 60) {
					$("#cartridge_20").removeClass('display_none');
					$("#cartridge_40").removeClass('display_none');
					$("#cartridge_60").removeClass('display_none');
					$("#cartridge_80").addClass('display_none');
					$("#cartridge_100").addClass('display_none');
				}
				else if (filamentRemain <= 80) {
					$("#cartridge_20").removeClass('display_none');
					$("#cartridge_40").removeClass('display_none');
					$("#cartridge_60").removeClass('display_none');
					$("#cartridge_80").removeClass('display_none');
					$("#cartridge_100").addClass('display_none');
				}
				else if (filamentRemain <= 100) {
					$("#cartridge_20").removeClass('display_none');
					$("#cartridge_40").removeClass('display_none');
					$("#cartridge_60").removeClass('display_none');
					$("#cartridge_80").removeClass('display_none');
					$("#cartridge_100").removeClass('display_none');
				}
			}
			
		}

		

		
		// return FileName;
	}
	
	function securityEnterKey(event) {
		if (event.keyCode == 13) {
			security_access();
		}		
	}

	function cancelEnterKey(event) {
		if (event.keyCode == 13) {
			new_cancel();
			$("#pwd_window").modal().hide();
		}		
	}
</script>
</head>
<body onload="body_onload();">
	<div class="container">
		<div class="row">
		</div>
		<div class="row ">
			<div class="header printing">
				<h2 class="title">MONITORING</h2>
			</div>
			<div class="ctime" style="text-align: center;    font-size: larger;    color: white;">
				<span class="glyphicon glyphicon-time" aria-hidden="true"></span>
				<span id="estimation_time_hour"></span>
				<span id="lb_hour"></span>	
				<span id="estimation_time_min"></span>
				<span id="lb_min"></span>	
				
			</div>
		</div>
		<canvas id="myCanvas" width="400" height="150" style="display:none"></canvas>
		<div class="row printing_box">
			<div class="col-xs-12">
				<div class="preview"><img src="" id="imagee" /></div>
			</div>
		</div>
		<div class="row progressbar">
			<div class="col-xs-12" style="height: 40px;">
				<div class="per_label">
					<p id="per_label_id"> </p>
				</div>
				<div class="progress" style="height: 30px;">
					<div class="progress-bar progress-bar-striped active" id="value_per" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100"> </div>
				</div>
			</div>
		</div>
		<div class="row control_box">
			<div class="col-xs-8">
				<div class="marquee">					
				</div>
			</div>
			<div class="col-xs-4">
				<div>
					<button type="button" class="btn btn-danger btn-lg btn-block control_print" disabled="false" data-toggle="modal" data-target=".bs-example-modal-sm" style="font-weight: bold; height:70px" onclick="javascript:click_cancel()"> </button>
				</div>
				<div class="modal fade bs-example-modal-sm" id="pwd_window" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
					<div class="modal-dialog">
						<div class="modal-content">
							<div class="modal-header">
								<h4 class="modal-title" id="please_pw_id"></h4>
							</div>
							<div class="modal-body">
								<input type="password" class="form-control" id="pwd" onkeydown="cancelEnterKey(event)" autofocus>
							</div>
							<div class="modal-footer">
								<button type="button" class="btn btn-primary" id="btn_ok_id" data-dismiss="modal" onclick="javascript:new_cancel()"></button>
								<button type="button" class="btn btn-default" id="btn_cancel_id" data-dismiss="modal"></button>
							</div>
						</div>
					</div>
				</div>

				
			</div>
		</div>

		<div class="modal fade" tabindex="-1" role="dialog" id="pwd_window_for_security">
			<div class="modal-dialog" role="document">
				<div class="modal-content">
				<div class="modal-header">					
					<h4 class="modal-title" id="pwd_window_for_security_modal_header">Security - Please input password.</h4>
				</div>
				<div class="modal-body">
					<input type="password" class="form-control" id="pwd_for_security" onkeydown="securityEnterKey(event)" autofocus>
				</div>
				<div class="modal-footer">					
					<button type="button" class="btn btn-primary" onclick="javascript:security_access()" id="security_ok_button">OK</button>
				</div>
				</div>
			</div>
		</div>

		<div class="row status">
			<div class="col-xs-6 ">
				<div class="nozzle">
					<span class="label nozzle_label" style="padding-left: 5px;"> </span>
					<span class="temp" id="Nozzle_value"></span>
					<span class="orange">˚C</span>
				</div>
			</div>
			<div class="col-xs-6" style="float: right; padding-left: 0px;">
				<div class="bed">
					<span class="label bed_label"> </span>
					<span class="temp" id="Bed_value"> </span>
					<span class="blue">˚C</span>
				</div>
			</div>
		</div>
		<div class="bottom">
			<div class="row cartridge">
				<div class="col-xs-3 desc">
					<label id="filament_material"> </label>
				</div>
				<div class="col-xs-3 color" style="padding-left: 0.2em; padding-right: 0.2em;">
					<div class="battery">
						<div class="bg_white" id="cartridge_20"></div>
						<div class="bg_white" id="cartridge_40"></div>
						<div class="bg_white" id="cartridge_60"></div>
						<div class="bg_white" id="cartridge_80"></div>
						<div class="bg_white" id="cartridge_100"></div>
					</div>
					<span id ="lb_openSpool"></span>
				</div>
			</div>
		</div>
	</div>
	
	<div id="div_loading" style="background-color:rgb(0,0,0); width:100%; height:100%; position:absolute; left:0%; top:0%; z-index:999; visibility:hidden;">
		<table width="100%" height="100%" border="0">
			<tr>
				<td align="center">
					<img src="/img/loading.gif" />
				</td>
			</tr>
		</table>
	</div>
	<div class="saved" style="visibility:hidden;"></div>
	<div id="dialog-alert">
		<p> </p>
	</div>
</body>
</html>`

**Comment by drtp** [comment]
Well, I think, an adapter is not necessary anymore. I have just included into my visualisation be using a simple html widget with the following code:

`
<div style>
<iframe style="transform-origin: 0px 0px 0px; transform: scale(0.78); width: 510px; height: 860px;" src="http://192.168.0.56/" name="iFrame" scrolling="no"></iframe>
</div>
`

By e.g. using a dialog widget, it can then be displayed like this:

![2020-05-03_11h56_16](https://user-images.githubusercontent.com/17758445/80913373-6b8e4580-8d44-11ea-8243-e0f7009fae40.png)
