### ISSUE TITLE
Wallpanel Adapter

### ISSUE THREAD

**Issue by duczz** [ioBroker/AdapterRequests#399]
Fully Browser Kiosk alternative - Komplett Freeware
https://github.com/thanksmister/wallpanel-android

Ein Adapter um alle Stats zu empfangen und via Rest setzten zu lassen würde mir schon reichen - Mega wäre ein Adapter ähnlich zum Fully-Tablet-Control
API: https://github.com/WallPanel-Project/wallpanel-api

**Comment by xXBJXx** [comment]
Schreib mal bitte eine liste was du so steuern willst hier mal eine Liste die man über die API steuern kann:
Liste zum steuern 

* **clearCache** = Clears the browser cache

* **audio URL** = Play the audio specified by the URL immediately => funktioniert 

* **relaunch** = Relaunches the dashboard from configured launchUrl => funktioniert 

* **reload** = Reloads the current page immediately => funktioniert 

* **url** = Browse to a new URL immediately => funktioniert 

* **wake**  =  Wakes the screen if it is asleep. Option wakeTime (in seconds) is optional, default is 30 sec. (Note: 
 wakeTime cannot be shorter than Androids Display Timeout setting) => funktioniert 

* **wake** = Release screen wake (Note: screen will not turn off before Androids Display Timeout finished) => funktioniert (Hinweis: Der Bildschirm wird nicht ausgeschaltet, bevor das Androids Display Timeout abgelaufen ist )

* **speak** = Uses the devices TTS to speak the message => funktioniert 
* **brightness** = Changes the screens brightness, value 1-255 => funktioniert 

* **camera** = Turns on/off camera streaming, requires camera to be enabled. => der Kamera Stream bleibt immer an keine Ahnung was es bewirken soll 

* **volume** = Changes the audio volume, value 0-100 (in %. Does not effect TTS volume) => funktioniert bei mir nicht


beim abfragen ist es viel kleiner den die api gibt nur 3 Datenpunkte aus:

* currentUrl = Current URL the Dashboard is displaying
* screenOn = If the screen is currently on.
* brightness = Current brightness value of the screen.

**Comment by duczz** [comment]
Danke für deine Rückmeldung.
Da ich Wallpanel derzeit parallele zum Fully nutze, da mir die Face detection mehr liegt, ist die Liste gar nicht so groß :)
Wenn mir jemand ein Rest Beispiel gibt kann ichs auch über ein Script immer abfragen bzw steuern lassen, hab die Rest Abfrage aber iwie nicht hinbekommen.

**Wunschliste:**
- Camera on/off (Für Alarmanlage mit Bild oder Video)
- speak
- audio URL
- volume

**Comment by xXBJXx** [comment]
@duczz  hier erst mal ein blockly Funktion mit der du die Commands senden kannst.
Mal schauen wenn ich paar freie tage finde bastle ich mal ein Adapter dazu **kann aber für nichts garantieren**  
[WallPanel Send Command.txt](https://github.com/ioBroker/AdapterRequests/files/5138275/WallPanel.Send.Command.txt)
![Screenshot_223](https://user-images.githubusercontent.com/32600934/91484164-18b73b80-e8a9-11ea-83b8-516e7df6a1c2.png)

**Comment by xXBJXx** [comment]
Erste Beta vom Wallpanel Adapter ist [hir zufinden](https://github.com/xXBJXx/ioBroker.wallpanel) die Dokumentation ist noch nicht gemacht ist aber relativ leicht zu verstehen.

**Comment by canim60** [comment]
Vielen Dank fürs den Adapter!,läuft bei mir, wenn du mir noch den Akkustatus einbauen kannst, bist du mein Held ;),mehr als ne Kaffeetasse wäre drin:P

**Comment by xXBJXx** [comment]
@canim60 
> Vielen Dank fürs den Adapter!,läuft bei mir, wenn du mir noch den Akkustatus einbauen kannst, bist du mein Held ;),mehr als ne Kaffeetasse wäre drin:P

tut mir leid aber die battery werte kann ich nicht rein machen da sie nicht angeboten werden von der api die kann man nur per MQTT abfragen

**Comment by DutchmanNL** [comment]
Alle weiteren Anregungen und wünsche bitte in der Adapter-Repo, wir behalten dieses issue offen bis https://github.com/xXBJXx/ioBroker.wallpanel offiziell released ist

**Comment by canim60** [comment]
> 
> 
> @canim60
> 
> > Vielen Dank fürs den Adapter!,läuft bei mir, wenn du mir noch den Akkustatus einbauen kannst, bist du mein Held ;),mehr als ne Kaffeetasse wäre drin:P
> 
> tut mir leid aber die battery werte kann ich nicht rein machen da sie nicht angeboten werden von der api die kann man nur per MQTT abfragen

kannst mir evt sagen wie?Blockly script?

**Comment by xXBJXx** [comment]
> > @canim60
> > > Vielen Dank fürs den Adapter!,läuft bei mir, wenn du mir noch den Akkustatus einbauen kannst, bist du mein Held ;),mehr als ne Kaffeetasse wäre drin:P
> > 
> > 
> > tut mir leid aber die battery werte kann ich nicht rein machen da sie nicht angeboten werden von der api die kann man nur per MQTT abfragen
> 
> kannst mir evt sagen wie?Blockly script?

bitte nicht mehr hier fragen sondern im Forum wir werde ich keine fragen mehr beantworten wir der Forum post zu dem Adapter https://forum.iobroker.net/topic/36438/test-adapter-wallpanel/7
