### ISSUE TITLE
LinkTap Garten Bewässerung

### ISSUE THREAD

**Issue by steckenpferd** [ioBroker/AdapterRequests#400]
API:
https://www.link-tap.com/#!/api-for-developers

**Comment by Xfiles-de** [comment]
An adapter to the LinkTap products would be great!

**Comment by Smart-Gang** [comment]
I have implemented an adapter for [LinkTap ](https://github.com/Smart-Gang/ioBroker.linktap) and would like to start the test phase. I own the G2 myself. 
But the predecessor model should also work. The API of the manufacturer is identical. There are only less states.

It would be great if you test the adapter. 

Einfach melden, wenn was ist.

**Comment by Xfiles-de** [comment]
Perfect .  I will test it.  Thank you very muchDanke schön .--Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 11.10.20, 21:33 schrieb Smart-Gang <notifications@github.com>:

   
  I have implemented an adapter for LinkTap  and would like to start the test phase. I own the G2 myself. But the predecessor model should also work. The API of the manufacturer is identical. There are only less states. 
  It would be great if you test the adapter. 
  Einfach melden, wenn was ist.

**Comment by Smart-Gang** [comment]
Bitte diesen Thread für die Testergebnisse verwenden: [https://forum.iobroker.net/topic/37467/test-adapter-linktap-v-0-0-x](https://forum.iobroker.net/topic/37467/test-adapter-linktap-v-0-0-x)

Danke

**Comment by ldittmar81** [comment]
@Apollon77 can be closed. Its stable
