### ISSUE TITLE
KIA UVO Adapter

### ISSUE THREAD

**Issue by gidhap** [ioBroker/AdapterRequests#403]
Hallo, 
Ich würde gerne die Daten meines e-Autos im ioBroker sehen.
Es gibt bereits einen API wrapper für KIA UVO, für eine home assist integration, allerdings in Python.
[https://github.com/wcomartin/kiauvo]
Ist das eine Grundlage auf der man einen Adapter zum Auslesen der Werte bauen könnte oder müsste ich dazu weitere Infos beschaffen. 
Natürlich vorausgesetzt, dass sich jemand dafür interessiert und seine Zeit opfert, das ist schon klar ;)
Gruss Karl-Heinz

**Comment by culpinnis** [comment]
Ich als Hyundaifahrer unterstütze das mal. Ich vermute Hyundai/KIA nutzen dasselbe Backend.
Karl-Heinz, das von dir verlinkte Projekt reimplementiert eine JavaScript-lib names bluelinkly (der Hyundai-Service heißt Bluelink). 
Ich vermute mal, wenn es bereits eine Lib in npm gibt dürfte die Integration in iobroker nicht allzu schlimm werden?
Die Lib ist ja bereits sehr gut dokumentiert. 
Beste Grüße
Chris

**Comment by mclane** [comment]
Hallo,
das fände ich auch gut, insbesondere in Hinblick auf eine Ladesteuerung zum Abschöpfen des Überschusses einer PV Anlage. Ich plane dann auch eine Prioritätssteuerung für die Ladung des E Autos vs. Ladung einer PV Speicherbetterie. Über KIA UVO könnte man den aktuellen Ladezustand des Fahrzeugs ermitteln und dies für die Prioritätssteuerung verwenden.
Ich wäre bereit, eine etwaige Lösung zu testen - ggf. bitte Kontaktaufnahme.
Gruß mclane

**Comment by Dennis1987m** [comment]
Ich habe einen Hyundai IONIQ Facelift mit Bluelink und hätte ebenfalls sehr Interesse an einem ioBroker-Adapter. Wenn ich helfen kann (leider absolut keine Programmierkenntnisse - aber vielleicht irgendwie anders) - gern bei mir melden.

**Comment by SvenP99** [comment]
Ich habe eine e-Niro und würde mich auch über einen Adapter freuen. 
Das Projekt habe ich bei OpenWB gefunden:
https://openwb.de/forum/viewtopic.php?f=5&t=1215&start=10
Da wird alles abgehandelt. Irgendwie scheitere ich schon beim Login, wenn ich das mal auf Testseiten probiere. Bekomme mit meinen Login-Daten immer "401 Unauthorized"

**Comment by gidhap** [comment]
Die Jungs haben im WB jetzt genau was wir im ioBroker wollen, zu blöd dass ich nicht programmieren kann.
Ich hoffe es findet sich noch ein motivierter Coder ;o)

**Comment by culpinnis** [comment]
Ich denke für Hyundai wäre https://github.com/Hacksore/bluelinky ein guter Startpunkt. Leider bin ich kein JS/TS Programmierer, allerdings ist die Einbindung sicherlich machbar. Das Backend steht ja schon, man müsste nur die Arbeiten für den ioBroker machen. Vielleicht werfe ich mal einen Blick drauf, falls mal Zeit über sein sollte. 
Laut dieser Diskussion https://github.com/Hacksore/bluelinky/issues/41 sollte es ja möglich sein einen KIA-kompatiblen Fork zu erstellen, sodass man so ein Projekt dann auch integrieren könnte.

**Comment by MarkusKress** [comment]
Leider scheint Hyundai (wahrscheinlich auch Kia) ein Problem damit zu haben, deren API zu verwenden. Ich habe aus dem Goingelektric Forum (sollte jedem eAuto Fahrer bekannt sein) erfahren, dass es bereits zu Sperrungen des Bluelinks-Account gekommen ist. Erst nach Kommunikation mit Hyundais Rechtsabteilung wurde der Zugang wieder freigegeschaltet. 

Ich habe mit bluelinky selbst auch Versuche unternommen und mittels einem kleinem Shell und JS-Script, sowie einem Exec des Shell-Scriptes eine einfache Umsetzung gebaut, ohne dazu einen Adapter zu erstellen (das kann ich leider nicht). Das ganze habe ich auch mit einem selbst gebautem Alexa-Skill verbinden können, wo ich den Zustand, Ladezustand und weitere Infos abrufen kann oder die Klima aktivert werden kann (abhängig von der Außentemperatur mit oder ohne Lenkradheizung). Allerdings ist der Teil mit der Alexa-Anbindung recht komplex (neben dem Alex-Skill wird eine Lamba-Funktion und ein IoT-Core-Device in der AWS benötigt. Zusätzlich wird ein MQTT-Broker (nicht der vom IOBroker), benötigt, da dieser mit dem IoT-Core gespiegelt wird. Dazu ist auch ein AWS-SDK lokal notwendig. Leider liegt jetzt alles brach und traue mich nicht mehr die API über Bluelinky zu verwenden. 

Gruß
Markus

**Comment by Dennis1987m** [comment]
Das ist schade. Aber herzlichen Dank für die ausführliche Antwort und die Zeit, die du dir dafür genommen hast. 

Am 05.01.2021 um 16:30 schrieb MarkusKress <notifications@github.com>:

﻿
Leider scheint Hyundai (wahrscheinlich auch Kia) ein Problem damit zu haben, deren API zu verwenden. Ich habe aus dem Goingelektric Forum (sollte jedem eAuto Fahrer bekannt sein) erfahren, dass es bereits zu Sperrungen des Bluelinks-Account gekommen ist. Erst nach Kommunikation mit Hyundais Rechtsabteilung wurde der Zugang wieder freigegeschaltet.

Ich habe mit bluelinky selbst auch Versuche unternommen und mittels einem kleinem Shell und JS-Script, sowie einem Exec des Shell-Scriptes eine einfache Umsetzung gebaut, ohne dazu einen Adapter zu erstellen (das kann ich leider nicht). Das ganze habe ich auch mit einem selbst gebautem Alexa-Skill verbinden können, wo ich den Zustand, Ladezustand und weitere Infos abrufen kann oder die Klima aktivert werden kann (abhängig von der Außentemperatur mit oder ohne Lenkradheizung). Allerdings ist der Teil mit der Alexa-Anbindung recht komplex (neben dem Alex-Skill wird eine Lamba-Funktion und ein IoT-Core-Device in der AWS benötigt. Zusätzlich wird ein MQTT-Broker (nicht der vom IOBroker), benötigt, da dieser mit dem IoT-Core gespiegelt wird. Dazu ist auch ein AWS-SDK lokal notwendig. Leider liegt jetzt alles brach und traue mich nicht mehr die API über Bluelinky zu verwenden.

Gruß
Markus

**Comment by Newan** [comment]
Projekte wie Vecchio und openwb haben das ja implementiert, glaube kaum das jeder gesperrt wird der das nutzt. Wenn mir einer Daten gibt und ich mal Zeit finde würde ich mir das ansehen aber verspreche nix

**Comment by MarkusKress** [comment]
Die Info mit dem gesperrtem Bluelink Account habe ich als private Nachricht im genannten Forum bekommen. Hat sich aber schon sehr wahrheitsmäß angehört. Ich habe keine Zweifel, dass hier nichts dran ist. Ggf. wurden es mit der Anzahl der Abfragen auch etwas übertrieben. Im Bluelinky wird eine Device-ID verwendet, die dort fest eingestellt ist. Ggf. sollte nicht jeder die gleiche verwenden. Die API ist wahrscheinlich erweitert worden oder hat eine neue Version bekommen. Es sind jetzt Profile in der neusten Firmware von Hyundai/Kia möglich, was sich auch in der APP widerspiegelt.

**Comment by Newan** [comment]
> Die Info mit dem gesperrtem Bluelink Account habe ich als private Nachricht im genannten Forum bekommen. Hat sich aber schon sehr wahrheitsmäß angehört. Ich habe keine Zweifel, dass hier nichts dran ist. Ggf. wurden es mit der Anzahl der Abfragen auch etwas übertrieben. Im Bluelinky wird eine Device-ID verwendet, die dort fest eingestellt ist. Ggf. sollte nicht jeder die gleiche verwenden. Die API ist wahrscheinlich erweitert worden oder hat eine neue Version bekommen. Es sind jetzt Profile in der neusten Firmware von Hyundai/Kia möglich, was sich auch in der APP widerspiegelt.

War auch nicht mein Ziel das in abrede zu stellen das sowas vorgefallen ist, sorry wenn das so rüberkam. Denke aber das die API nutzbar ist sonst würden die anderen Projekte dies ja auch nicht tun können ;-)

**Comment by gidhap** [comment]
@Newan wenn Du mir eine mail an sz@manzell-city.de schickst, mit den Daten die Du brauchst, gebe ich Dir gerne die von meinem e-Soul. (Ich hab den Request ja auch "verbrochen" ;o)

**Comment by MarkusKress** [comment]
@gidhap
Hast Du das Update mit den Profilen auf dein e-Soul schon installiert/installieren lassen?

**Comment by gidhap** [comment]
Wenn Du das meinst, das jetzt den Lila touch bringt und den schönen dreigeteilten Startbildschirm eliminiert hat :o( , dann JA.

**Comment by Newan** [comment]
> Die Info mit dem gesperrtem Bluelink Account habe ich als private Nachricht im genannten Forum bekommen. Hat sich aber schon sehr wahrheitsmäß angehört. Ich habe keine Zweifel, dass hier nichts dran ist. Ggf. wurden es mit der Anzahl der Abfragen auch etwas übertrieben. Im Bluelinky wird eine Device-ID verwendet, die dort fest eingestellt ist. Ggf. sollte nicht jeder die gleiche verwenden. Die API ist wahrscheinlich erweitert worden oder hat eine neue Version bekommen. Es sind jetzt Profile in der neusten Firmware von Hyundai/Kia möglich, was sich auch in der APP widerspiegelt.

Kurzes Update dazu. Die Aufrufe in Deutschland sind auf 200 Api-Calls begrenzt. Danach wirst du wohl gesperrt. Somit muss man da aufpassen wenn man einen Adapter benutzt UND die App. Möglicherweise noch mit mehreren Benutzer?
https://github.com/Hacksore/bluelinky/wiki/API-Rate-Limits

**Comment by DutchmanNL** [comment]
> > Die Info mit dem gesperrtem Bluelink Account habe ich als private Nachricht im genannten Forum bekommen. Hat sich aber schon sehr wahrheitsmäß angehört. Ich habe keine Zweifel, dass hier nichts dran ist. Ggf. wurden es mit der Anzahl der Abfragen auch etwas übertrieben. Im Bluelinky wird eine Device-ID verwendet, die dort fest eingestellt ist. Ggf. sollte nicht jeder die gleiche verwenden. Die API ist wahrscheinlich erweitert worden oder hat eine neue Version bekommen. Es sind jetzt Profile in der neusten Firmware von Hyundai/Kia möglich, was sich auch in der APP widerspiegelt.
> 
> Kurzes Update dazu. Die Aufrufe in Deutschland sind auf 200 Api-Calls begrenzt. Danach wirst du wohl gesperrt. Somit muss man da aufpassen wenn man einen Adapter benutzt UND die App. Möglicherweise noch mit mehreren Benutzer?
> https://github.com/Hacksore/bluelinky/wiki/API-Rate-Limits

im adapter kan man das begrenzen mit Intervallen, beachte aber das der adapter (bzw ioBroker) nicht wissen kan ob anderen connections stattfinden

**Comment by Newan** [comment]
Pre-Alpha Version könnt ihr hier teste: https://github.com/Newan/ioBroker.bluelink

Ausgelesen: Tacho
Steuerung: lock/unlock

**Comment by gidhap** [comment]
Läuft bei mir 👍

**Comment by Newan** [comment]
https://forum.iobroker.net/topic/43592/adapter-hyundai-bluelink-oder-kia-uvo

**Comment by DutchmanNL** [comment]
> https://forum.iobroker.net/topic/43592/adapter-hyundai-bluelink-oder-kia-uvo

Danke 🙏 viel Erfolg beim Testen/Releasen
