### ISSUE TITLE
NISSAN CARWINGS Adapter

### ISSUE THREAD

**Issue by gidhap** [ioBroker/AdapterRequests#405]
Hallo, nachdem ich hier schon einen Adapter für KIA UVO angefragt habe möchte ich gleich einen nachschieben, damit die Daten unseres zweiten E-Autos auch im ioBroker dargestellt werden können.
Im Nissan Carwings Portal lassen sich wesentliche Daten des Nissan Leaf abfragen und auch ein paar Funktionen steuern. (Z.B. Standheizung). Auf dem Androiden gipt es eine App dazu..

Bei meiner Suche habe ich Node Red Nodes zu Carwings gefunden [https://flows.nodered.org/node/node-red-contrib-carwings](url). Ich kann leider nicht programmieren, aber das mit RedNode liest sich so, als ob sich das irgendwie für einen ioBroker Adapter verwenden liesse - hoffe ich.
Bin gespannt

**Comment by tobintax** [comment]
I'm interested in this, too. There are a bunch of scripts on github to achieve that (pulling data from the leaf cloud or from the vehicle without any additional hardware).

**Comment by Apollon77** [comment]
@tobintax can you post links to them? COuld make it easier if a dev has time and do not require him to search for himself :-)

**Comment by gidhap** [comment]
As a workaround - I had a guy enhancing his [Android app](https://play.google.com/store/apps/details?id=com.chk.lcc) by MQTT. 
All I needed was an old smartphone which is now sitting unattended in my office and connecting to Nissan via App on one side and to ioBroker on the other side, using the MQTT adapter. At least a workaround.
![image](https://user-images.githubusercontent.com/28500973/113825362-29a22680-9781-11eb-8c73-4cf1c3899aa5.png)

**Comment by tobintax** [comment]
> @tobintax can you post links to them? COuld make it easier if a dev has time and do not require him to search for himself :-)

Yes, sorry for that. Here are the links: 

https://github.com/philliphoff/carwings2
https://github.com/joshperry/carwings

**Comment by TA2k** [comment]
Besteht noch interesse an einem Nissan Adapter? Hätte jemand Zugangsdaten?

**Comment by tobintax** [comment]
> Besteht noch interesse an einem Nissan Adapter? Hätte jemand Zugangsdaten?

Ja, ich habe natürlich noch Interesse

**Comment by TA2k** [comment]
Dann melde dich im Forum dann schreib ich schnell einen

**Comment by TA2k** [comment]
https://forum.iobroker.net/user/tombox

**Comment by TA2k** [comment]
Der Adapter ist fertig Details hier
https://forum.iobroker.net/topic/46700/test-adapter-nissan-v-0-0-x

**Comment by TA2k** [comment]
@ldittmar81
