### ISSUE TITLE
Adapter für alle Helios KWL Lüftungsanlagen mit easyControls Steuerung

### ISSUE THREAD

**Issue by strackm** [ioBroker/AdapterRequests#407]
Hallo, ich vermisse einen Adapter für Helios Lüftungsgeräte mit easyControls.
Der Hersteller hat die Modbus TCP/IP Schnittstelle entsprechend dokumentiert, dürfte also kein riesiges Problem darstellen.

https://www.easycontrols.net/de/service/downloads/send/4-software/16-modbus-dokumentation-f%C3%BCr-kwl-easycontrols-ger%C3%A4te

**Comment by strackm** [comment]
Es gibt bereits eine funktionierende Einbindung in openhab:
https://community.openhab.org/t/helios-binding-for-modbus-tcp/5578/61

Anscheinend gibt es auch eine Einbindung in FHEM
https://www.loxforum.com/forum/german/software-konfiguration-programm-und-visualisierung/1080-helios-kwl-easycontrols-%C3%BCber-modbus-tcp-einbinden

**Comment by Ritschy2000** [comment]
Bin auch an einem Adapter interessiert.

über Modbus TCP/IP ist es wohl nicht ganz so einfach, zumindest laut dem Forum.
Moehre hat es wohl über ein Script hinbekommen:

[https://forum.iobroker.net/topic/24769/gel%C3%B6st-helios-kwl-zugriff-auf-xml](url)

eventl. kann daraus ein kleiner Adapter gebaut werden?

**Comment by chrisss83** [comment]
Hätte auch großes Interesse an einem Adapter. So ein Gerät kostet aber 2000€ und mehr und wiegt 50 kg.
Wäre es auch möglich einen Adapter zu entwickeln, wenn ein Besitzer eines Gerätes einen Fernzugriff einrichtet?

**Comment by chrisss83** [comment]
Mit dem was hier 

https://forum.iobroker.net/topic/24769/gel%C3%B6st-helios-kwl-zugriff-auf-xml/3

Kann ich alle Variablen mittels JavaScript auslesen. Ich schaffe es aber nicht die Variablen zuverlässig zu schreiben....

Die Hälfte des Adapters wäre quasi schon fertig. Wenn mir jemand etwas hilft der mehr Ahnung von JavaScript und PHP hat, teste ich gerne alles mögliche durch.

**Comment by strackm** [comment]
Es lohnt sich hier mal vorbei zu schauen:

https://github.com/KLVN/ioBroker_Helios-KWL

**Comment by TA2k** [comment]
Hier ein Adapter zum testen

**Comment by DutchmanNL** [comment]
> Hier ein Adapter zum testen
> https://forum.iobroker.net/topic/47762/test-helios-kwl-v0-0-x

Cool thanks! Alles weitere (issue / frage etc) am besten Dan weiter dort 👍
