### ISSUE TITLE
OPC UA

### ISSUE THREAD

**Issue by jopebe** [ioBroker/AdapterRequests#415]
Many old  systems have OPC UA. (e.g. moeller Easy) Now You cannnot  combine them with IOBROKER.
Long time ago, OPC -adapter was announced, but nothing happend. 
For Siemens s7 there is an adapter.
For easy Relais I know a DLL > EASY_COM.dll that works with windows.
Last dicussion in EasyForum look: http://easy-forum.net/index.php?topic=6455.0

**Comment by GermanBluefox** [comment]
There is a ioBroker.opcua adapter. Actually only for client functionality.
And only 10 Datapoints are available for free.
![image](https://user-images.githubusercontent.com/4582016/82829289-37292780-9eb3-11ea-80ff-28c576187463.png)

**Comment by Apollon77** [comment]
So Request done ?!

**Comment by GermanBluefox** [comment]
Yes. I will not do anything else.
