### ISSUE TITLE
lieferungen.app

### ISSUE THREAD

**Issue by n3roGit** [ioBroker/AdapterRequests#419]
Es wäre sehr geil wenn man seine ausstehenden Paketlieferungen in IoBroker bekommen könnte.
Damit ließe sich z.B. ein Event auslösen, wenn das Paket innerhalb der nächsten Minuten kommt.

https://www.lieferungen.app/

**Comment by Apollon77** [comment]
How an API could work?

**Comment by n3roGit** [comment]
Leider bietet der Ersteller keine api an. Vielleicht lässt es sich ja direkt über die Status Seite abfragen

**Comment by Elektrickser** [comment]
Von DHL gibts ne API zum Sendungsstatus. Glaube gibts auch noch von anderen Dienstleistern.

Eventuell, dass man versucht nen Adapter zu schreiben, der auf die verschiedenen API's zugreift.

**Comment by n3roGit** [comment]
https://www.google.com/amp/s/www.parcelmonitor.com/track-parcel-express-tracking-api/

Diese Seite kann anscheinend tracking von so ziemlich allem automatisch zuordnen. Und ne api gibt's auch

**Comment by psydie** [comment]
Ich werde mir mal die API anschauen biss jetzt ist die sehr offen gehalten und könnte mit einem Acces-Token funktionieren.

**Comment by FlexerJR** [comment]
Hallo @psydie hattes du die Zeit mal zu schauen was mit der Api möglich ist. Wäre auch sehr interessiert an dem Projekt

**Comment by FlexerJR** [comment]
@Apollon77 Meiner Meinung nach hat der mögliche Adapter riesiges Potential!

Stelle mich gerne als Tester zur Verfügung

**Comment by DutchmanNL** [comment]
> https://www.google.com/amp/s/www.parcelmonitor.com/track-parcel-express-tracking-api/
> 
> Diese Seite kann anscheinend tracking von so ziemlich allem automatisch zuordnen. Und ne api gibt's auch

leider nicht kostenlos https://www.parcelperform.com/pricing

**Comment by n3roGit** [comment]
> > https://www.google.com/amp/s/www.parcelmonitor.com/track-parcel-express-tracking-api/
> > Diese Seite kann anscheinend tracking von so ziemlich allem automatisch zuordnen. Und ne api gibt's auch
> 
> leider nicht kostenlos https://www.parcelperform.com/pricing

Schade, das hab ich nicht gesehen.
Kann man nicht die Webseite von lieferungen.app irgendwie parsen und so auslesen?
Man muss doch wahrscheinlich nur die Anmeldung hinbekommen und dann die Spalten von der Webseite grabben?

Ich hab schon ein bisschen mit Curl rumprobiert, bin allerdings an der Authentifizierung gescheitert.

**Comment by ldittmar81** [comment]
Bitte weiter auf bei #216 abstimmen

**Comment by TA2k** [comment]
Ich habe was für dhl und 17track soweit gebaut
https://forum.iobroker.net/topic/51795/test-adapter-parcel-paketverfolgung-dhl-v0-0-1
