### ISSUE TITLE
Adapter für Luxtronik 2 Wärmepumpensteuerung

### ISSUE THREAD

**Issue by TechSaiyajin** [ioBroker/AdapterRequests#426]
Die Luxtronik 2.0 ist eine Heizungssteuerung der Firma Alpha Innotec,
die in Wärmepumpen von folgenden Herstellern verbaut ist:
- Alpha Innotec
- Siemens Novelan
- Roth
- Elco
- Buderus
- Nibe
- Wolf Heiztechnik
- CTA

Sie besitzt einen Ethernet Anschluss, so dass sie direkt in lokale Netzwerke integriert werden kann.

Die große Verbreitung der Steuerung, würde einen Adapter sehr interessant machen.
Anfragen existieren bereits im iobroker Forum.

Sehr nützliche Informationen über die Steuerung und dessen Ansteuerung  gibt es auf:
https://www.loxwiki.eu/display/LOX/Luxtronik+2

Ein Adapter existiert bereits, dieser wird seit Jahren nicht weiterentwickelt und funktioniert nicht mehr zuverlässig.
(Vermutlich weil der Hersteller mit neuer Firmware auf ein Websockets basierendes Protokoll setzt.)
Links zu diesem Projekt:
https://github.com/jachik/ioBroker.hpcontrol
https://forum.iobroker.net/topic/6477/neuer-adapter-w%C3%A4rmepumpensteuerung-f%C3%BCr-w%C3%A4rmepumpen-luxtronik2-buderus-alpha-innotec-usw

**Comment by Apollon77** [comment]
Gibt es andere Integrationen die mit dem neuen Websocket System tun?

**Comment by TechSaiyajin** [comment]
Anscheinend basieren alle Lösungen auf das Java Applet, welches auch weiterhin vom Hersteller unterstützt wird!
Ich habe eine Integration in Home Assistant gefunden:
https://github.com/Bouni/Home-Assistant-Luxtronik
Weitere Quelle:
https://www.loxwiki.eu/plugins/servlet/mobile?contentId=18219334#content/view/18219334

**Comment by DomKue** [comment]
Hallo,
habe meine inzwischen 10 Jahre alten Luxtronic, die auf Version 1.81 läuft (geht auch ab 2.81 oder 3.81), grade erfolgreich an ioBroker angebunden.
Es gibt für node-red bereits ein passendes Modul - https://flows.nodered.org/node/node-red-contrib-luxtronik2-ws
Die Verbindung wird dort via websocket hergestellt, funktioniert ganz gut (ohne Langzeiterfahrung).
Hier auch gute Hinweise, wie man mit den Daten weiterkommt:
https://www.loxforum.com/forum/faqs-tutorials-howto-s/30078-luxtronik-wp-steuerung-auslesen-alpha-innotec-novelan-evtl-auch-buderus/page4

Falls an dieser Stelle ein direkter Adapter angestrebt wird und node-red hier keine Option ist, entschuldigt bitte den Post.

**Comment by Timmes123** [comment]
Hallo,
ich bin gerade ebenfalls auf der suche nach einem Adapter.
Ich habe laut webinterface version 1.81 und bin gerade am testen mit node red.
Bei nodered kann ich sowohl mit node-red-contrib-luxtronik2 als auch mit node-red-contrib-luxtronik2-ws (websocket) daten auslesen. schreiben hab ich bisher nicht versucht.
Schön wäre es natürlich schon, da dieses system sehr weit verbreitet ist, eine direkte iobroker einbindung zu realisieren.

**Comment by TbsJah** [comment]
Ich habe mir einen Adapter geschrieben
Der liest die Werte aus. Per request 

![Screenshot_20201104_131440_com android chrome-01](https://user-images.githubusercontent.com/34193151/98110722-ca717a80-1e9f-11eb-980d-6d7242df8ef7.jpeg)

Sieht dann so aus
Ist nur auslesen. Habe ihn jedoch noch nicht auf github. Wollte ihn erst aktualisieren

**Comment by Timmes123** [comment]
@TbsJah Der Adapter sieht super aus :-) würd mich freuen wenn du den publizieren würdest :-)

**Comment by Oreider** [comment]
@TbsJah würde mich auch sehr darüber freuen :)

**Comment by TbsJah** [comment]
[iobroker.ait_lwd50.zip](https://github.com/ioBroker/AdapterRequests/files/5501261/iobroker.ait_lwd50.zip)


Wie geschrieben - nur lesen

**Comment by Oreider** [comment]
@TbsJah: Schade...

host.ioBroker-Rock64 | 2020-11-07 12:03:07.257 | error | instance system.adapter.ait_lwd50.0 terminated with code 10 (CANNOT_FIND_ADAPTER_DIR)
-- | -- | -- | --

**Comment by TechSaiyajin** [comment]
Aktuell nutze ich noch den alten Adapter. Funktioniert er bei euch auch noch?

https://github.com/jachik/ioBroker.hpcontrol

Der von TbsJah sieht aber äußerst vielversprechend aus.

**Comment by TbsJah** [comment]
![image](https://user-images.githubusercontent.com/34193151/98462498-13357600-21b5-11eb-8797-e7b81c75f75a.png)

Das Verzeichnis muss nach /opt/iobroker/node_modules kopiert werden
Dann erscheint er auch unter Adapter und es kann eine Instanz generiert werden

**Comment by Apollon77** [comment]
@TbsJah  Warum kein Repo im Github und dann per GitHub installieren lasse wie üblich? Zip files manuell in ein node_modules einfügen kann am ende zu mehr Problemen führen als einem lieb ist ...

**Comment by TbsJah** [comment]
Gebe ich dir recht.
Aber, ich muss mich erst in das Thema github / repo / iobroker einarbeiten
dazu fehlte mir bisher die zeit

**Comment by Apollon77** [comment]
Es gibt im Forum bzw in Telegram auch Dev Gruppen , da helfen wir gern :-)

**Comment by UncleSamSwiss** [comment]
Habe heute unsere CTA Aeroheat 16iL endlich ans LAN angeschlossen und bin darauf gekommen, dass sie eine Luxtronik 2 Steuerung hat (zum Glück nennt sich die JS Datei "Lux.js" ;-).

@TechSaiyajin Der hpcontrol Adapter funktioniert mit meiner WP, allerdings nehme ich an, dass man nur Werte auslesen kann und keine verändern (sonst wäre es etwas bedenklich, da ich kein Passwort eingeben musste).

@TbsJah So wie ich das im Code sehe, liest dein Adapter noch über die alte Schnittstelle (die gleich ist wie bei Luxtronik 1). Was ist der Unterschied zum hpcontrol Adapter?

Falls niemand anderes bereits begonnen hat, würde ich einen Adapter auf WebSocket-Basis schreiben, der dann auch Werte schreiben kann. Ich würde mich dabei an [node-red-contrib-luxtronik2-ws](https://github.com/bouni/node-red-contrib-luxtronik2-ws) anlehnen, aber natürlich saubere ioBroker States machen.

**Comment by TbsJah** [comment]
Der einzige Unterschied zu dem hpcontrol Adapter ist die Aufgliederung in Bereiche und die Formatierung
Sonst gibt es keine wesentlichen Unterschiede

Falls du einen Tester benötigst - sehr gerne!

**Comment by UncleSamSwiss** [comment]
@TbsJah Ich habe die Firmware V3.83C (r3915)

**Comment by UncleSamSwiss** [comment]
So, jetzt habt ihr mal was zum testen:
https://github.com/UncleSamSwiss/ioBroker.luxtronik2
Bitte seid vorsichtig mit Werten ändern: ich übernehme keine Verantwortung, wenn eure WP abraucht!
Fehler bitte als Issue in GitHub.

**Comment by tbit-c** [comment]
Hallo zusammen, wann wird's das Ding denn mal im "offiziellen Store" des IObroker geben?
