### ISSUE TITLE
Adapter für PegelAlarm

### ISSUE THREAD

**Issue by sigi2345** [ioBroker/AdapterRequests#431]
Hallo, ich würde einen Adapter für PegelAlarm benötigen.

Sigi

https://github.com/SOBOS-GmbH/pegelalarm_public_pas_doc/wiki

APP:

https://play.google.com/store/apps/details?id=at.pegelalarm.app&hl=de

**Comment by Apollon77** [comment]
https://github.com/larsdecker/ioBroker.pegelonline auch eine Option?

**Comment by sigi2345** [comment]
> https://github.com/larsdecker/ioBroker.pegelonline auch eine Option?

Leider nein, nicht für Ösis.

**Comment by bazidibavaria** [comment]
https://github.com/bazidibavaria/ioBroker.pegelalarm
