### ISSUE TITLE
I-soft zugangsdaten

### ISSUE THREAD

**Issue by mirage-111** [ioBroker/AdapterRequests#433]
>Ich habe auch den PIN um in die Einstellungsebene des Servicemechanikers zu kommen. Ist laut seiner Aussage bei jeder I-Soft Plus gleich...-;)
_Originally posted by @joker17177 in https://github.com/ioBroker/AdapterRequests/issues/247#issuecomment-570894601_

Hallo @joker17177,
Kannst mir mal die Zugangsdaten per Mail zukommen lassen, will mir das mal anschauen.
Mail: mirage-1 at gmx.de 

Danke

**Comment by joker17177** [comment]
Hallo!

Der PIN sollte 5289 sein...

mirage-111 <notifications@github.com> schrieb am Fr. 19. Juni 2020 um 17:10:
