### ISSUE TITLE
Telegram Menü

### ISSUE THREAD

**Issue by EuloTV** [ioBroker/AdapterRequests#434]
Hallo, ich hätte großes Interesse an einem Telegram Menü Adapter.

Ich habe zwar viele Codes und Videos für ein Telegram Menü gefunden, aber leider keinen Adapter.

Wäre geil, wenn sich ein Entwickler finden würde.

**Comment by Apollon77** [comment]
Hm ... also der Telegram Adapter kann das - da aber jeder sein eigenes Menü und dinge haben will ist die Umsetzung des Menüs spezifisch per JavaScript  umgesetzt ... Was genau sollte der Adapter denn wie tun?

**Comment by Ilovegym66** [comment]
Es gibt n Adapter der heißt blockly Extension und hat das schon eingebaut, Telegram Menü mit klicki-bunti 😉

Erweitert die blocklys auch um noch n paar Funktionen, und ist mit dem aktuellen Javascript und auch js-controller 3.x kompatibel.

**Comment by Apollon77** [comment]
Ist der schon im Repo? :-)

**Comment by Ilovegym66** [comment]
nee, Version 0.0.1 :-)
nicht von mir, aber hab n mal getestet. [Blockly Plus](https://github.com/excal-foley/ioBroker.blockly-plus)

**Comment by duczz** [comment]
Ich nutze wie @Ilovegym66 auch Blockly Plus, es hat aber scheinbar einen Bug bei zu vielen "Sonst falls" Abfragen, weswegen ich nun angefragt habe es direkt im Blockly zu integrieren (Es wären ja eigentlich nur 2 Punkte)

https://github.com/ioBroker/ioBroker.javascript/issues/630

**Comment by MiRo1310** [comment]
Ich bin dabei sowas zu bauen.

**Comment by duczz** [comment]
@MiRo1310 Sehr cool, gibts dazu schon einen Post im Forum?

**Comment by MiRo1310** [comment]
@duczz nein gibt es noch nicht. Bin da auch erst gerade mit gestartet. Vielleicht kannst du mal stichpunkt artig schreiben was er können sollte.

**Comment by duczz** [comment]
@mcm1957 Gerne.
Bei mir ist es eig relativ simple, ich möchte eine Übersicht Pro Raum (Wohnzimmer, Küche) als Einstig's Menü mit darunterliegenden Primär Aktionen (Licht, Temperatur, PC, Pool) und darunter STATE abfragen/setzten.
STATES sollten aber in jeder Ebene setzbar sein. - Hoffe ich hab's gut erklärt :)

Z.B.
Wohnzimmer
-Licht
-- ON/OF
-PC
-- ON/OFF
-Temperatur
-- Temperatur via STATE anzeigen
-- Temperatur via STATE setzen

**Comment by MiRo1310** [comment]
@duczz ja das wird alles drin sein. Es wird in jeder Ebene schaltbar sein. 
die Struktur legt man selbst an.das wird aber relativ simpel

**Comment by MiRo1310** [comment]
@duczz Die erste Version habe ich heute mal erstellt. Ist aber absolut noch in der probephase. Aber gerne mal probieren. 
https://github.com/MiRo1310/ioBroker.telegram-menu

**Comment by mcm1957** [comment]
@MiRo1310 

DANKE für deinen Einsatz und Zeitaufwand!

Mach bitte mal einen Thread im Forum / tester Bereich auf. - falls noch nicht geschehen.
https://forum.iobroker.net/category/91/tester

Erhöht die Sichtbarkeit und das Forum ist der richtige Platz allfällige Probleme / Anregungen zu diskutieren.

**Comment by mcm1957** [comment]
Request for latest: https://github.com/ioBroker/ioBroker.repositories/pull/2297

**Comment by mcm1957** [comment]
Published at latest
