### ISSUE TITLE
Balboa Adapter

### ISSUE THREAD

**Issue by michihorni** [ioBroker/AdapterRequests#435]
Ich suche einen Adapter für eine Balboa Whirl-Poolsteuerung. Die Steuerung ist über WiFi zu Erreichen, eine API habe ich leider nicht.
Hat jemand eine Idee wie zu einen solchen Adapter kommen kann?

Anbei ein Link zur App.
https://www.balboawatergroup.com/bwa
Gruß Michael

Funktionen:
- [ ] Pooltemperatur ändern / Anzeigen
- [ ] Umwälzpumpe Status bzw. schalten
- [ ] Jetdüsen Status bzw. schalten
- [ ] LED Leuchten Status bzw. schalten
- [ ] Timer soll die Temperatur Nachts absenken

**Comment by mike47de** [comment]
Hallo michihorni,

Für die Homebridge gibt es ein Plugin für diese Whirlpoolsteuerung. Vielleicht hilft die Info - wenngleich es schon klasse wäre diese auch über iobroker steuern zu können

**Comment by Apollon77** [comment]
Dann vllt via HAM adapter?

**Comment by michihorni** [comment]
Hallo Ingo 

ich weiß leider nicht wie die Konfigurationsdatei im HAM auszusehen hat.
 

Mit freundlichen Grüßen
Michael Horn

 
 

Gesendet: Dienstag, 14. Juli 2020 um 10:56 Uhr
Von: "Ingo Fischer" <notifications@github.com>
An: "ioBroker/AdapterRequests" <AdapterRequests@noreply.github.com>
Cc: "michihorni" <michaelhorn@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [ioBroker/AdapterRequests] Balboa Adapter (#435)


 

Dann vllt via HAM adapter?

**Comment by michihorni** [comment]
Hallo Ingo Fischer (Apollon) hat den HAM Adapter entwickelt, mit dem Homebridge Komponenten laufen. Allderdings ist eine Konfig Datei Notwendig. Ich habe keine Ahnung was da drin stehen muß
 

Mit freundlichen Grüßen
Michael Horn

 
 

Gesendet: Dienstag, 14. Juli 2020 um 08:33 Uhr
Von: "Mike" <notifications@github.com>
An: "ioBroker/AdapterRequests" <AdapterRequests@noreply.github.com>
Cc: "michihorni" <michaelhorn@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [ioBroker/AdapterRequests] Balboa Adapter (#435)


 

Hallo michihorni,

Für die Homebridge gibt es ein Plugin für diese Whirlpoolsteuerung. Vielleicht hilft die Info - wenngleich es schon klasse wäre diese auch über iobroker steuern zu können

**Comment by Apollon77** [comment]
--> https://www.npmjs.com/package/homebridge-balboa-spa !?

**Comment by mike47de** [comment]
@Apollon77 ja genau. Ich versuche es auch grad mit dem HAM Adapter und habe dafür auf meinem Raspi 4 mit ioBroker zusätzlich noch eine Homebridge nach der Anleitung von smartapfel installiert. Diese läuft nun und auch das Plugin habe ich dort installiert. Nun bekomme ich die Geräte des Spa jedoch nicht in ioBroker angezeigt. Ich muss hier nur ein wenig suchen um die Details herauszufinden bin allerdings ein Linux Anfänger.

**Comment by michihorni** [comment]
Hallöchen, den Artikel hatte ich schon gefunden und auch versucht die Konfigdatei anzupassen.

er HAM Adapter ist grun aber es werden keine objekte angelegt.
 

Mit freundlichen Grüßen
Michael Horn

 
 

Gesendet: Mittwoch, 15. Juli 2020 um 09:35 Uhr
Von: "Ingo Fischer" <notifications@github.com>
An: "ioBroker/AdapterRequests" <AdapterRequests@noreply.github.com>
Cc: "michihorni" <michaelhorn@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [ioBroker/AdapterRequests] Balboa Adapter (#435)


 

--> https://www.npmjs.com/package/homebridge-balboa-spa !?

**Comment by michihorni** [comment]
@mike47de Hast du echt die Werte des Spa in der Homebridge Installation? Wie sieht deine Config aus?
Michael

**Comment by michihorni** [comment]
@Apollon77 Ich habe nun den Pool im Homebridge sichtbar. Ich habe die selbe Konfig nun in den HAM Adapter eingebaut. Im Wrapper Modus und im Lokalen Modus wird der Adapter grün, aber es werden keine Objekte angelegt. Polling Interval ist auf 30. habe einmal "verwenden Sie den unsicheren HB Modus" ausprobiert und einmal ohne. Leider werden keine Objekte angelegt.
Anbei die Konfig:
`{
  "description": "Add configuration for your accessories or platforms according to the docs of the plugins.",
  "accessories": [],
  "platforms": [
    {
      "name": "Spa",
      "autoCreateAccessories": false,
      "host": "192.168.178.xxx",
      "devices": [
        {
          "name": "Zirkulationspumpe",
          "deviceType": "Pump 1"
        },
        {
          "name": "Pumpe1",
          "deviceType": "Pump 2"
        },
        {
          "name": "Sprudler",
          "deviceType": "Blower"
        },
        {
          "name": "Temperatur",
          "deviceType": "Temperature Sensor"
        },
        {
          "name": "Wasserdurchlauf",
          "deviceType": "Water Flow Problem Sensor"
        },
        {
          "name": "Temperatur Einstellung",
          "deviceType": "Thermostat"
        },
        {
          "name": "LED",
          "deviceType": "Lights 1"
        }
      ],
      "platform": "Balboa-Spa"
    }
  ]
}`
Kannst du helfen?
Gruß
Michael

**Comment by Apollon77** [comment]
Ham adapter bitte Debug log und log zeigen

**Comment by michihorni** [comment]
Hallöchen anbei der gewünschte LOG
[iobroker.2020-07-24.log](https://github.com/ioBroker/AdapterRequests/files/4973565/iobroker.2020-07-24.log)

**Comment by michihorni** [comment]
Hallo Ingo, ich habe gesehen das Du den HAM Adapter upgedatet hast. Ich habe sofort in den Objekten die Datenstruktur der Balboa Steuerung erhalten, allerdings bislang keine Werte für Temperatur oder für Pumpen. Ich glaube aber das liegt nicht an dem Adapter sondern an der Hardware, aktuell komme ich auch nicht über die  APP auf die Steuerung. Wo kann ich eine Spende für deine Arbeit hin senden? Mit Dankbaren Gruß Michael (Bitte Info an Michaelhorn@web.de)

**Comment by michihorni** [comment]
Hallöchen
ich kann also jetzt bestätigen, dass ich nun auch die Werte des Whirlpools in den Objekten sehe. Super arbeit, Danke
Michael

**Comment by mike47de** [comment]
Hallo @michihorni welche Einstellungen hast du denn im iobroker ham Adapter vorgenommen? Bei mir startet der Adapter nur kurz und wird dann wieder rot :-(. Jetzt habe ich viel probiert und musste den iobroker schließlich neu installieren. Ich würde mich auf eine Antwort freuen

**Comment by michihorni** [comment]
Hallöchen

anbei zwei Screenshoots


 

Mit freundlichen Grüßen
Michael Horn

 
 

Gesendet: Dienstag, 11. August 2020 um 12:21 Uhr
Von: "Mike" <notifications@github.com>
An: "ioBroker/AdapterRequests" <AdapterRequests@noreply.github.com>
Cc: "michihorni" <michaelhorn@web.de>, "Mention" <mention@noreply.github.com>
Betreff: Re: [ioBroker/AdapterRequests] Balboa Adapter (#435)


 

Hallo @michihorni welche Einstellungen hast du denn im iobroker ham Adapter vorgenommen? Bei mir startet der Adapter nur kurz und wird dann wieder rot :-(. Jetzt habe ich viel probiert und musste den iobroker schließlich neu installieren. Ich würde mich auf eine Antwort freuen

**Comment by mike47de** [comment]
Herzlichen Dank @michihorni , leider werden die Screenshots bei mir nicht angezeigt. Liegt hier ein Fehler vor? Herzliche Grüße

**Comment by michihorni** [comment]
Die Screenshots sollten als Anhang im jpg Format gesendet sein. Mit freundlichen GrüßenMichael HornAm 11.08.20, 18:00 schrieb Mike <notifications@github.com>:

   
  Herzlichen Dank @michihorni , leider werden die Screenshots bei mir nicht angezeigt. Liegt hier ein Fehler vor? Herzliche Grüße

**Comment by michihorni** [comment]
Du kannst mir auch gerne deine private Email Adresse zukommen lassen, dann sende ich die Anhänge gern nochmal Mit freundlichen GrüßenMichael HornAm 11.08.20, 18:00 schrieb Mike <notifications@github.com>:

   
  Herzlichen Dank @michihorni , leider werden die Screenshots bei mir nicht angezeigt. Liegt hier ein Fehler vor? Herzliche Grüße

**Comment by mike47de** [comment]
Sehr gerne. Das ist ja toll, danke schön. Meine Emailadresse lautet michaelwirges@web.de.

Herzliche Grüße Michael

**Comment by hofmachr** [comment]
Frage, hab ihr s geschafft die Poolsteuerung in den IOBROKER zu integrieren, würde gerne die Heizung mit PV Überschuss steuern.

**Comment by michihorni** [comment]
Moin, ja die Poolsteuerung mittels HAM läuft im Iobroker.

Aber bei PV kann ich sicher nicht helfen
 

Mit freundlichen Grüßen
Michael Horn

 
 

Gesendet: Montag, 09. November 2020 um 20:41 Uhr
Von: "hofmachr" <notifications@github.com>
An: "ioBroker/AdapterRequests" <AdapterRequests@noreply.github.com>
Cc: "michihorni" <michaelhorn@web.de>, "Mention" <mention@noreply.github.com>
Betreff: Re: [ioBroker/AdapterRequests] Balboa Adapter (#435)


 

Frage, hab ihr s geschafft die Poolsteuerung in den IOBROKER zu integrieren, würde gerne die Heizung mit PV Überschuss steuern.

**Comment by hofmachr** [comment]
Danke für die rasche Antort (schneller als ich wieder online bin :-) 
Nachfrage:
seht ihr eine chance für einen Nativ IOBROKER Adapter, ich hätte mir gerne die Zusätzliche HOMEBRIDGE Installation erspart.


@PV Überschuss aus meiner ursprünglichen Anfrage: 
die PV Steuerung hab ich schon für meinen WarmwasserBoiler mittels Shelly realisiert - lass es aber noch ein paar wochen Laufen, und teile dann mein Script mit der community.

**Comment by michihorni** [comment]
Ich denke, die Nachfrage nach einem Baloa Adapter ist relativ gering, somit ist der Aufwand einen Adapter zu entwickeln zu hoch, die Alternative das ganze mit dem HAM Adapter zu realisieren ist ja schließlich gegeben und funktioniert einwandfrei.
 

Mit freundlichen Grüßen
Michael Horn

 
 

Gesendet: Freitag, 13. November 2020 um 12:03 Uhr
Von: "hofmachr" <notifications@github.com>
An: "ioBroker/AdapterRequests" <AdapterRequests@noreply.github.com>
Cc: "michihorni" <michaelhorn@web.de>, "Mention" <mention@noreply.github.com>
Betreff: Re: [ioBroker/AdapterRequests] Balboa Adapter (#435)


 

Danke für die rasche Antort (schneller als ich wieder online bin :-)
Nachfrage:
seht ihr eine chance für einen Nativ IOBROKER Adapter, ich hätte mir gerne die Zusätzliche HOMEBRIDGE Installation erspart.

@pv Überschuss aus meiner ursprünglichen Anfrage:
die PV Steuerung hab ich schon für meinen WarmwasserBoiler mittels Shelly realisiert - lass es aber noch ein paar wochen Laufen, und teile dann mein Script mit der community.

**Comment by hofmachr** [comment]
alles klar. ich werd mein Glück view HomeBridge probieren.

**Comment by michihorni** [comment]
Wenn Du Hilfe bei der Konfig brauchst, einfach melden

Viel Erfolg
 

Mit freundlichen Grüßen
Michael Horn

 
 

Gesendet: Freitag, 13. November 2020 um 17:18 Uhr
Von: "hofmachr" <notifications@github.com>
An: "ioBroker/AdapterRequests" <AdapterRequests@noreply.github.com>
Cc: "michihorni" <michaelhorn@web.de>, "Mention" <mention@noreply.github.com>
Betreff: Re: [ioBroker/AdapterRequests] Balboa Adapter (#435)


 

alles klar. ich werd mein Glück view HomeBridge probieren.

**Comment by Apollon77** [comment]
dann biete im Forum melden ioder issue mit allen details im ham adapter anlegen

**Comment by michihorni** [comment]
Bitte schön...

{
  "description": "Add configuration for your accessories or platforms according to the docs of the plugins.",
  "accessories": [],
  "platforms": [
    {
      "name": "Spa",
      "autoCreateAccessories": false,
      "host": "192.168.178.xxxxx",
      "devices": [
        {
          "name": "Jet",
          "deviceType": "Pump 1"
        },
        {
          "name": "Pumpe1",
          "deviceType": "Pump 2"
        },
        {
          "name": "P1",
          "deviceType": "Pump 1"
        },
        {
          "name": "P2",
          "deviceType": "Pump 2"
        },
        {
          "name": "P3",
          "deviceType": "Pump 3"
        },
        {
          "name": "P4",
          "deviceType": "Pump 4"
        },
        {
          "name": "P5",
          "deviceType": "Pump 5"
        },
        {
          "name": "P6",
          "deviceType": "Pump 6"
        },
        {
          "name": "Sprudler",
          "deviceType": "Blower"
        },
        {
          "name": "Temperatur",
          "deviceType": "Temperature Sensor"
        },
        {
          "name": "Wasserdurchlauf",
          "deviceType": "Water Flow Problem Sensor"
        },
        {
          "name": "Temperatur Einstellung",
          "deviceType": "Thermostat"
        },
        {
          "name": "LED",
          "deviceType": "Lights 1"
        }
      ],
      "platform": "Balboa-Spa"
    }
  ]
}

Mit freundlichen Grüßen
Michael Horn

 
 

Gesendet: Freitag, 09. September 2022 um 08:43 Uhr
Von: "ges7881" ***@***.***>
An: "ioBroker/AdapterRequests" ***@***.***>
Cc: "michihorni" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [ioBroker/AdapterRequests] Balboa Adapter (#435)


 

Hallo an alle,

hab leider das Problem, dass ich im ioBroker keine Datenpunkte hab. Hätte wer eine funktionierende Konfig für mich bitte?

Danke im Voraus!

**Comment by 83beni** [comment]
Hallo Zusammen 

Gibt es zum Adapter schon Erfahrungen?
Ich möchte die Umwälzpumpe und die Heizung so steuern können das sie auch dann laufen wenn die Solaranlage auch Strom produziert. 

Hat dies schon jemand von Euch so umgesetzt?

Gruss Beni

**Comment by mcm1957** [comment]
Fragen dieser Art besser im Forum stellen.
Probleme u Featurerequests bitte als Issue im  Adapter Repository eintragen.
