### ISSUE TITLE
Lichtsteuerung

### ISSUE THREAD

**Issue by n3roGit** [ioBroker/AdapterRequests#439]
Es gibt mittlerweile sehr viele Adapter die einem sehr viel Arbeit für die Steuerung des Smarthomes abnehmen, idem man keine Blockly oder Scripte mehr schreiben muss.

Wie z.B. shuttercontrol oder heatcontrol

Was es allerdings noch nicht gibt ist ein Adapter der die Lichtsteuerung übernimmt.

Ich stelle mir eine einfache GUI vor in der man den Räumen die Sensoren und Aktoren zuordnet. Dazu ein paar globale Einstellungen für Schaltzeit, Helligkeit, Anwesenheit usw. gepaart mit individuellen Raumeinstellungen.

Ich denke das würde vielen den Einstieg in das IOT Thema stark vereinfachen.

**Comment by MMeinhardt1** [comment]
Hi,

das ist eine sehr gute Sache. Wenn sich jemand bereit erklärt einen solchen Adapter zu schreiben, hätte ich direkt ein paar Wünsche.
Schön wäre wenn sich das ganze dann auch auf die Außenbeleuchtung erweitern lassen könnte indem man auswählen kann welche der Lampen wann an bzw. aus gehen sollen, mit oder ohne Bewegungsmeldersteuerung oder nach Astro.
Das ganze ähnlich dem shuttercontrol.

Vielen Dank

**Comment by vain90** [comment]
Hallo zusammen,
ich würde einen solchen Adapter auch toll finden.
Ich würde mich noch viel mehr freuen, wenn man dann noch eine HCL Steuerung umsetzen könnte.
Ich habe dazu heute morgen mal meine Skripte im ioBroker Forum gepostet. Dort ist auch kurz beschrieben was HCL ist.

Evtl. kann davon etwas mit einfließen.

https://forum.iobroker.net/topic/34982/vorlage-hcl-script-human-centric-lighting

**Comment by n3roGit** [comment]
https://forum.iobroker.net/topic/33691/planung-neuer-adapter-smart-control/

**Comment by MMeinhardt1** [comment]
@n3roGit danke für den Hinweis. Ich habs mir mal durchgelesen und werd den Adapter die Tage mal testen, klingt und liest sich sehr gut und vielversprechend! Danke

**Comment by Mic-M** [comment]
Siehe hier: https://forum.iobroker.net/topic/33691/planung-neuer-adapter-smart-control/66

Github (Entwickler-Version, noch nicht zum offiziellen testen, und vor allem nicht produktiv einsetzen!): https://github.com/Mic-M/ioBroker.smartcontrol

**Comment by Pittini** [comment]
Es ist zwar kein Adapter, aber evtl. ja doch für den einen oder anderen hilfreich: https://github.com/Pittini/iobroker-LightControl

**Comment by ldittmar81** [comment]
Der Smartcontrol Adapter ist stable
