### ISSUE TITLE
Tedee Smartlock

### ISSUE THREAD

**Issue by siob** [ioBroker/AdapterRequests#445]
Ein Nuki like Adapter wäre fantastisch.
Es existiert eine API
https://api.tedee.com/swagger/index.html

A Nuki lile adapter would be great.
There‘s also an official API
https://api.tedee.com/swagger/index.html

**Comment by mrMuppet** [comment]
Vielleicht funktioniert erstmal der Betrieb über den homebridge Adapter https://github.com/ioBroker/ioBroker.ham
Mit dem homebridge-tedee-plugin https://github.com/lukasroegner/homebridge-tedee

**Comment by Proper0912** [comment]
Ist jemand daran ein Adapter zu machen?
Oder wie kann ich das Smartlock in den IoBroker intigrieren ohne homebridge?

**Comment by mrMuppet** [comment]
Du brauchst ja keine Homebridge-Installation zu betreiben. Es reicht den Homebridge-Adapter zu benutzen. Der kann (auch) ohne einen Homebridge-Server die entsprechenden Plugins in Iobroker integrieren.

**Comment by ldittmar81** [comment]
Funktioniert es mit dem Homebridge Adapter? Hat es schon jemand getestet?

**Comment by mrMuppet** [comment]
Ja, Tedee funktioniert sehr gut mit dem Homebridge In Iobroker.

**Comment by Holger76** [comment]
Kann ich bestätigen, das läuft soweit. Wobei ich aber denke, ein schlanker
Adapter speziell wäre besser und standesgemäß. Etwas bessere Reaktionszeit
würde ich mir auch erhoffen.

**Comment by ldittmar81** [comment]
Natürlich... Ohne Frage. Inzwischen haben ja schon 6 Personen dafür gevotet und vielleicht findet sich ein Entwickler der ein Adapter schreibt.

**Comment by kBrausew** [comment]
habe die hardware und würde auch den Adapter machen wenn es einen lokale rest api geben würde. leider ist im augenblick nur über die Cloud oder per Bluetooth möglich. beides habe ich mir angesehen und werde dies nicht umsetzen... da ja bereits mit dem HAM-Adapter ein provisorischer zugriff möglich ist.

Vorab wäre es wichtig die Support-Seite zu spammen um den versprochenen lokale rest-api zu bekommen ...
es sind jetzt immerhin schon **bald** drei jahre die sie von jahr zu jahr versprechen "nächstes jahr..." :-(

zwei beispiele ;-)
[hier](https://tedee.freshdesk.com/en/support/discussions/topics/77000263533)
[und hier](https://tedee.freshdesk.com/en/support/discussions/topics/77000270118)

**Comment by Holger76** [comment]
Ich konnte gestern erfreulicherweise lesen, dass an einer local API gearbeitet wird. Einer Adapter Erstellung steht nun also nichts mehr im Wege ;)
https://tedee.freshdesk.com/en/support/discussions/topics/77000270118/page/2?url_locale=en

**Comment by kBrausew** [comment]
... na dann warten wir mal bis sie released wird

**Comment by MrDrache333** [comment]
Gibt es hier schon etwas neues diesbezüglich?

**Comment by kBrausew** [comment]
API ist im Test beim Hersteller

**Comment by Holger76** [comment]
API ist jetzt verfügbar bei neuester APP & Bridge Firmware.  Bei einem ersten Test hat alles gut funktioniert, leider nur per nicht gesichertem token, das andere bekomme ich nicht hin. Ein Adapter wäre diesbezüglich wirklich hilfreich. Die Api ist gut dokumentiert

**Comment by mrMuppet** [comment]
Vielleicht verschickt der Hersteller ja sogar ein Muster, wenn sich jemand mit Interesse und belegbaren Fähigkeiten in der Richtung bei ihm melden.

**Comment by DutchmanNL** [comment]
> Vielleicht verschickt der Hersteller ja sogar ein Muster, wenn sich jemand mit Interesse und belegbaren Fähigkeiten in der Richtung bei ihm melden.

wen sich die Möglichkeit bietet waehre ich bereit mir die Umsetzung an zu nehmen.
Es betrifft eine Rest-API hofier ich momentan ein Module entwickle und bereits einige adapter relativ ohne hohen aufwand integrieren konnte.
Ziel ist es diese library grosser ein zu setzen und zu verallgemeinern damit wir es fuer derartige Integrationen nutzen können ohne spezifisch seperat viel code generieren zu muessen

**Comment by DutchmanNL** [comment]
habe es mir gerade mal näher angeschaut, schon ein schickes gerät muss ich sagen!
Nur um jetzt fuer die Entwicklung 150-(mit bridge) fast 300 zu investieren fehlen mir leider die Möglichkeiten

**Comment by TA2k** [comment]
Adapter ist fertig. Bitte testen
https://forum.iobroker.net/topic/71052/test-tedee-adapter
https://github.com/TA2k/ioBroker.tedee

**Comment by mcm1957** [comment]
Not yet released

**Comment by mcm1957** [comment]
Latest Request: https://github.com/ioBroker/ioBroker.repositories/pull/3071

**Comment by mcm1957** [comment]
has been released to latest
