### ISSUE TITLE
Adapter Smart-EQ Control

### ISSUE THREAD

**Issue by Uwe1984** [ioBroker/AdapterRequests#446]
Es wäre super,  wenn jemand einen Adapter zur Steuerung des neuen Smart EQ programmieren könnte. 
Ich fahre selbst einen und könnte als Tester zur Verfügung stehen. 
Die API müsste hier zu finden sein: 

https://developer.mercedes-benz.com/products

**Comment by MK-2001** [comment]
Leider ist das nicht die API. Diese ist nur für Mercedes excl. SMART.

**Comment by TA2k** [comment]
Kann ich gerne machen vielleicht kann es ja in den mercedes adapter registrieren. ich bräuchte nur zugangsdaten 
einfach via forum melden
https://forum.iobroker.net/user/tombox

**Comment by TA2k** [comment]
https://forum.iobroker.net/topic/49548/test-adapter-smart-eq-v0-0-x
