### ISSUE TITLE
Ondilo ICO Poolsensor

### ISSUE THREAD

**Issue by ldittmar81** [ioBroker/AdapterRequests#447]
We need a adapter for poolsensors. ioBroker dont have something like this. Here is a good sensor: https://ondilo.com/en/

They have an API for it

https://interop.ondilo.com/docs/api/customer/v1/

IPSymcon has an adapter for it

https://github.com/Wolbolar/IPSymconOndilo

> *created by ioBroker.info*

**Comment by ldittmar81** [comment]
We can get help from Ondilo.

```
Dear Sir,

here is the link to our API documentation: https://interop.ondilo.com/docs/api/customer/v1/
Please let me know may you have any question.
Best regards,

Amandine DESHORS

Marketing & Communication
adeshors@ondilo.com

www.ondilo.com
```

**Comment by chris-hoe** [comment]
I have such a sensor and an iobroker installation on a Raspberry Pi 4 - I could assist in testing such an adapter. I would love to make one myself but unfortunately I don't have enough time to do that.

**Comment by ldittmar81** [comment]
It should be easy to create an adapter with the description on https://interop.ondilo.com/docs/api/customer/v1/ and here is an example how to do it: https://github.com/edwinvdpol/com.ondilo.ico/tree/main/lib

**Comment by Sev7eNup** [comment]
Would also love to see an adapter for the sensor :)

**Comment by Garfonso** [comment]
I now have the hardware and will look into it.

**Comment by Garfonso** [comment]
I implemented an adapter to connect to the cloud and pull measurements, it can be found here: 
https://github.com/iobroker-community-adapters/ioBroker.ico

There also is a [forum thread (german part of the forum)](https://forum.iobroker.net/topic/46468/ico-pool-sensor-von-ondilo) and I started the process to get the adapter into the latest repository.

Also, feel free to add issues with suggestions, the adapter is pretty basic currently. Do you want / need the recommendations in ioBroker?

**Comment by Manuel35i** [comment]
Hallo
Erst Mal Danke für den Adapter und die damit verbundene Arbeit.

Denn Adapter habe ich installiere und er läuft soweit auch.

Nur leider Aktualisiert der Adapter seine Daten nicht Automatisch.

Ich bekomme nur eine Aktualisierung wenn ich den Adapter neu Lade.

**Comment by chris-hoe** [comment]
Hello Manuel35i, that's interesting - I also installed the adapter but cannot configure it: the admin screen is just empty. How did you do the setup?

**Comment by chris-hoe** [comment]
> Also, feel free to add issues with suggestions, the adapter is pretty basic currently. Do you want / need the recommendations in ioBroker?

The recommendations are not needed in iobroker in my opinion - if we will be able to record the data over a longer term and with better graphing possibilities plus the possibility to base actions on measured values, that would be great.

**Comment by Manuel35i** [comment]
Auf Adapter gehen und in den Expertenmodus wechseln.
Dann auf die GitHub Katze klicken.
Anschließend über URL Installieren.
IO Broker Server Neustarten.
Wieder auf Adapter gehen dann auf denn Adapter ICO Cloud klicken und auf das + Symbol.
Dann sollte in Instanzen die Instanz ICO Cloud aufgeführt sein diese dann Konfigurieren.
![IMG_20210721_230205.jpg](https://user-images.githubusercontent.com/79336301/126560257-5567e649-c945-4808-ba97-74000eae5a28.jpg)
![IMG_20210721_230148.jpg](https://user-images.githubusercontent.com/79336301/126560311-a77de24d-9abe-4050-8d7f-1e32d56f222f.jpg)
![IMG_20210721_230131.jpg](https://user-images.githubusercontent.com/79336301/126560333-3e648ea7-4442-4192-8dcb-c9d251f40109.jpg)
![IMG_20210721_230113.jpg](https://user-images.githubusercontent.com/79336301/126560347-0b4d5091-a519-45a1-be33-da93d7480627.jpg)

**Comment by Garfonso** [comment]
> Hallo
> Erst Mal Danke für den Adapter und die damit verbundene Arbeit.
> 
> Denn Adapter habe ich installiere und er läuft soweit auch.
> 
> Nur leider Aktualisiert der Adapter seine Daten nicht Automatisch.
> 
> Ich bekomme nur eine Aktualisierung wenn ich den Adapter neu Lade.

Ja, da war nochwas kaputt. Versuch mal bitte 0.0.4.

**Comment by Manuel35i** [comment]
Hallo zur Info Version 0.0.4 funktioniert bei mir einwandfrei 👍 nun wird alles Aktualisiert.

**Comment by Manuel35i** [comment]
Adapter läuft bei mir seit 1 Woche ohne Probleme.
Es wäre noch toll wenn man einen Datenpunkte in Objekte hätte der einen sagt von welcher Uhrzeit und Datum die gemessenen Werte sind damit man im VIS erkennen kann ob diese Aktuelle sind oder nicht, so wie in der Originalen App![IMG_20210729_110430.jpg](https://user-images.githubusercontent.com/79336301/127464247-599c82c6-f680-40ac-90bb-0beefd7bb4ee.jpg)

**Comment by Apollon77** [comment]
EWs gibt doch vis widgets die den "ts" von einem Datenounkt anzeigen? Das ist doch nochmal viel besser oder

**Comment by Garfonso** [comment]
Der Adapter setzt den Timestamp der Datenpunkte auf den Timestamp, den ich von der API bekomme. Kannst du den nicht in der Vis anzeigen? Also state.ts statt state.val. Müsste mit Markdown gehen, z.B. so:
`Daten von {ico-cloud.0.ICOID.temperature.ts;date(hh:mm DD.MM.YYYY)}`

**Comment by Manuel35i** [comment]
> EWs gibt doch vis widgets die den "ts" von einem Datenounkt anzeigen? Das ist doch nochmal viel besser oder

Hat funktioniert Dankeschön 👍

**Comment by chris-hoe** [comment]
Hallo zusammen, 
ich hab immer noch das Problem, dass ich den Adapter nicht konfigurieren kann. Außerdem fehlt meiner "Kachel" für den ICO die große Überschrift "ICO Poolsensor", die bei Manuel35i zu sehen ist. Details habe ich beim entsprechenden [github issue](https://github.com/iobroker-community-adapters/ioBroker.ico-cloud/issues/6) hochgeladen. Auch die altuelle 0.0.5er Version zeigt das Verhalten. Deinstallation und Neuinstallation mit oder ohne Restart des iobroker Daemons bringen nichts. Jemand noch eine Idee? Ich würde den Adapter wirklich gerne nutzen....!!!
Viele Grüße, Christian

**Comment by Garfonso** [comment]
Ja, admin 4 bzw der zu neue Krempel, den ich benutzt habe ist das Problem. . . 🙁 
Admin 5 soll aber jetzt ins stable kommen, dann sollte es auch für dich gehen.

**Comment by markusk1407** [comment]
Hallo! Hatte von euch jemand auch folgendes Problem? Ich habe mich in der App bei ondilo registriert. Die App (Android) macht auch was sie soll, es wird alles angezeigt, ich bekomme Benachrichtigungen etc,. Wenn ich mich jetzt aber über die Website anmelden will um einen Token zu bekommen, kommt immer die Meldung, dass meine Emailadresse nicht bekannt wäre. Weiss jemand wo der Fehler liegt?

LG
Markus

**Comment by chris-hoe** [comment]
> 
> 
> Ja, admin 4 bzw der zu neue Krempel, den ich benutzt habe ist das Problem. . . 🙁
> Admin 5 soll aber jetzt ins stable kommen, dann sollte es auch für dich gehen.

Hallo Garfonso,
Danke für den Hinweis. Ich habe jetzt auf Admin 5 umgestellt und siehe da: es geht! :-D
Vielen Dank für diesen Adapter - funzt prima!

**Comment by Apollon77** [comment]
Then we close this request?
