### ISSUE TITLE
Adapter für Powerfox/Poweropti: Energiedaten verfügbar – kostengünstig und in Echtzeit

### ISSUE THREAD

**Issue by Hupenberger** [ioBroker/AdapterRequests#449]
Poweropti stelle alle Daten (in/output) eines digitalen Stromzählers zu Verfügung. I Kosten: 69 Eur. Die App funktioniert tadellos. Ich würde gerne die Daten von Poweropti in Iobroker/Vis einbinden. Bin leider kein Entwickler.
Hier die Homepage: https://www.powerfox.energy/
Hie das techn. Datenblatt:  https://www.powerfox.energy/wp-content/uploads/2020/05/20190905-Datenblatt-poweropti-v1MB.pdf
Eine Kunden Rest API ist vorhanden:  https://www.powerfox.energy/wp-content/uploads/2020/05/powerfox-Kunden-API.pdf
Hier noch eine Doku für openHAB:  https://www.powerfox.energy/wp-content/uploads/2020/05/openHAB-und-powerfox.pdf

**Comment by Hupenberger** [comment]
Raspi Pi 4

**Comment by bazidibavaria** [comment]
I'm in contact with powerfox and started to create an adapter
https://github.com/bazidibavaria/ioBroker.powerfox

**Comment by FabianHM** [comment]
Hallo, 
freut mich sehr das jemand das Thema Poeropti in Angriff nimmt.

Ich habe schon einige Zeit versucht basierend auf der o.g. Doku des Herstellers über HTTP Requests die Daten von der API zu holen und sinnvoll strukturiert in den ioBroker zu bekommen.

Ich stehe gerne zur Verfügung wenn es um Testing geht.

Grüße
Fabian

**Comment by bazidibavaria** [comment]
Hi @FabianHM,

würdest du mich per IoBroker Forum kontaktieren?
Wäre klasse, dann könnten wir uns einfacher austauschen.

PS: Ich nutze den Demo-API Account von PowerFox.
Leider hat der Demo-Acc Fehler in API Auslieferung, was mich aktuell etwas einschränkt.

LG

**Comment by DutchmanNL** [comment]
Danke @bazidibavaria das du dich diesem annimmst, ich lasse das issue offen bis die release soweit ist.
PS : zum Austausch heisse ich euch auch herzlichen willkommen auf unserem discord, erstelle gerne einen channel fuer diesen adapter um die diskussionen/fragen zu zentralisieren

https://discord.gg/HwUCwsH

Info dazu : 

https://forum.iobroker.net/topic/36313/willkommen-beim-iobroker-discord-channel

**Comment by ldittmar81** [comment]
New Adapter https://github.com/Ax-LED/ioBroker.powerfox2
