### ISSUE TITLE
AWIN - Affiliate Status

### ISSUE THREAD

**Issue by sky-it** [ioBroker/AdapterRequests#453]
Awin bietet eine API Schnittstelle an, die es Publishern ermöglicht, Statistiken zu den Partnerprogrammen abzurufen.
Interessant wäre es hier die Provisionen automatisiert abzurufen.

Doku: https://wiki.awin.com/index.php/Publisher_API

**Comment by manoloxxl** [comment]
Das sollte doch bei so einer einfachen Abfrage über den Parser möglich sein, oder?

**Comment by sky-it** [comment]
Die API ist wirklich simpel, nur wie bekommt man in die URL den abzufragenden Zeitraum beim Parser-Adapter?

**Comment by Apollon77** [comment]
Warum closed?

**Comment by sky-it** [comment]
Weil ich die Daten mit dem Parser holen kann. Das mit dem Datum ist noch offen, aber denk da kann ich für mich zumindest mit einer dazuwischengeschalteten Seite arbeiten.
Mir fehlt in der Api eh noch ein Punkt, welche Provisionen bereits angefallen sind, seit der letzten Auszahlung, das hab ich mal angefragt und dafür braucht man normalerweise kein Datum
