### ISSUE TITLE
Eufy Security Cam und Doorbell

### ISSUE THREAD

**Issue by Trunks1982** [ioBroker/AdapterRequests#455]
Ich würde mich freuen wenn es irgendwie eine Möglichkeit für Eufy cam gäbe Sie in Iobroker zu integrieren.
Die werden immer bekannter und die Produkte sind echt gut.
Vielleicht kann man einen Adapter erstellen.

MFG

**Comment by Apollon77** [comment]
Dann füge bitte mal Links zu den Produkten hinzu. Gibt es APIs? oder wie sind die angebunden? Gibt es andere Systeme die das schon nutzen können?

**Comment by Trunks1982** [comment]
Dieses habe ich gefunden: 
https://community.home-assistant.io/t/eufy-camera-integration/121758
http://community.anker.com/t/open-api/70397/5

Pyton Script: https://github.com/FuzzyMistborn/python-eufy-security/issues/3

Produkte zb: 
https://www.eufylife.com/de/products/variant/videoturklingel-mit-akku/E82101W4
https://www.eufylife.com/de/products/variant/eufycam-2c-2kameraset/T88313D2

**Comment by OXERY** [comment]
https://github.com/JanLoebel/eufy-node-client

**Comment by DutchmanNL** [comment]
> https://github.com/JanLoebel/eufy-node-client

das Modul ist leider noch nicht reif fuer eine Integration hat aber Potential : 

```
Experiment to send/receive/control messages from eufy security. Currently I only have the doorbell with a station. My basic target is to be able to control the guard mode of the station and receive doorbell events if somebody is on the door.
```

**Comment by Trunks1982** [comment]
Für mich wäre das hervorragend wenn ich eufy als adapter nützen könnte

**Comment by DutchmanNL** [comment]
API refference : http://community.anker.com/t/open-api/70397/6

**Comment by robbsen-iobroker** [comment]
Ein Adapter wäre hier wirklich wunderbar :). Die Kameras haben Potential für ioB

**Comment by bropat** [comment]
Ich arbeite gerade daran. In den nächsten Tagen werde ich eine erste release posten.

**Comment by Trunks1982** [comment]
> Ich arbeite gerade daran. In den nächsten Tagen werde ich eine erste release posten.

Super.Würde es dann gerne testen.

**Comment by robbsen-iobroker** [comment]
Super, danke im Voraus für die Arbeit. Würde es natürlich auch gerne testen.

**Comment by bropat** [comment]
Habe eine erste Version des Adapters hier veröffentlicht: https://github.com/bropat/ioBroker.eufy-security
Diese Version kann noch nicht vieles, aber mehr wird kommen... ;-)

**Comment by Trunks1982** [comment]
Gerade mal den Adapter installiert und erkennt schonmal meine zwei Eufy 2c cam und meine Doorbell.Eine frage gibt es einen Status wenn es klingelt?

**Comment by bropat** [comment]
> Gerade mal den Adapter installiert und erkennt schonmal meine zwei Eufy 2c cam und meine Doorbell.Eine frage gibt es einen Status wenn es klingelt?

Super. Nein gibt es nicht. JanLoebel hat bereits  erfolgreich die push notifications der Eufy Cloud getestet. Ich denke damit könnte man es integrieren.

**Comment by Trunks1982** [comment]
Schade.Dann muss ich mal gucken wie ich das integriere

**Comment by bropat** [comment]
> Schade.Dann muss ich mal gucken wie ich das integriere.Wo finde ich diese Push notifications?
> 

https://www.github.com/JanLoebel/eufy-node-client/tree/master/src%2Fpush

**Comment by Trunks1982** [comment]
Da kapier ich gar nichts von🤣

**Comment by ubieberich** [comment]
Hallo bropat,

finde super, dass Du Dich der Aufgabe angenommen hast. Habe den Adapter auch schon installiert. Leider komme ich wegen der aktiven 2-Faktor-Authentifizierung nicht all zu weit. Ich habe ein Ticket mit Logfile bei Github angelegt.

Gruß

**Comment by bropat** [comment]
> Hallo bropat,
> 
> finde super, dass Du Dich der Aufgabe angenommen hast. Habe den Adapter auch schon installiert. Leider komme ich wegen der aktiven 2-Faktor-Authentifizierung nicht all zu weit. Ich habe ein Ticket mit Logfile bei Github angelegt.
> 
> Gruß

Hallo ubieberich,

leider kann ich die 2FA nicht verwenden und somit integrieren, da sie zur Zeit nur für Deutschland und Kanada von Eufy freigeschalten wurde.

**Comment by Sedrah87** [comment]
Hallo ubieberich,

ich konnte es noch nicht testen aber der 2FA ist ja noch recht neu und hat noch die eine oder andere Schwäche - eine davon ist zur Zeit, dass alle bereits angemeldeten Gerät nicht mehr nach dem 2. Faktor gefragt werden. Ich bin zur Zeit nicht Zuhause und kann es nicht testen aber vielleicht funktioniert das temporäre deaktivieren, iobroker einrichten, anschließend wieder aktivieren. In meiner Theorie bleibt der ioBroker dann ein valides Gerät aus der Sicht von Anker/eufy.

Gruß

**Comment by Trunks1982** [comment]
Was mir aufgefallen ist wenn man einmal den Benutzernamen und Passwort eingegeben hat kann man das nicht mehr ändern.
Es wird im Adapter nichts mehr angezeigt.

**Comment by bhueck** [comment]
Adapter per Gitlab URL im ioBroker installiert; diverse Objekte für weiter unten aufgeführte Hardware wurden angelegt.
Stehe gerne für weiteres Testing bereit.
Weiter so! 👍 

Hardware
* HomeBase2 T8010 2.1.2.0h
* eufy Security Indoor Cam 2K T8410 2.0.8.9
* Akku Video-Türklingel T8210 2.2.1.3

**Comment by ubieberich** [comment]
> 
> 
> Hallo ubieberich,
> 
> ich konnte es noch nicht testen aber der 2FA ist ja noch recht neu und hat noch die eine oder andere Schwäche - eine davon ist zur Zeit, dass alle bereits angemeldeten Gerät nicht mehr nach dem 2. Faktor gefragt werden. Ich bin zur Zeit nicht Zuhause und kann es nicht testen aber vielleicht funktioniert das temporäre deaktivieren, iobroker einrichten, anschließend wieder aktivieren. In meiner Theorie bleibt der ioBroker dann ein valides Gerät aus der Sicht von Anker/eufy.
> 
> Gruß

Hallo Sedrah87,

ich hab's ausprobiert. Funktioniert leider nicht. Ohne 2FA kann ich den Adapter mit dem Konto verbinden. Sobald ich 2FA dann wieder aktiviere kann sich der Adapter nicht mehr verbinden.

Gruß

**Comment by lk911lk** [comment]
Ich habe das klingeln der Doorbell über "Bell-Base-Alexa-Iobroker-hue" gelöst. 
Einen neuen Datenpunkt der über eine Alexa Routine auf true gesetzt wird wenn die Klingel betätigt wird. Dieser wirderrum lässt meine Lichter mit einem Blockly aufleuchten. Also Klingeln nun Lichter,Echo´s, Base, Echo Show sowie alle Fernseher die Aktiv sind. VIS fehlt noch, sollte aber mit dem ioBroker.eufy-security aus Git kein Problem darstellen.

**Comment by Trunks1982** [comment]
> Ich habe das klingeln der Doorbell über "Bell-Base-Alexa-Iobroker-hue" gelöst.
> Einen neuen Datenpunkt der über eine Alexa Routine auf true gesetzt wird wenn die Klingel betätigt wird. Dieser wirderrum lässt meine Lichter mit einem Blockly aufleuchten. Also Klingeln nun Lichter,Echo´s, Base, Echo Show sowie alle Fernseher die Aktiv sind. VIS fehlt noch, sollte aber mit dem ioBroker.eufy-security aus Git kein Problem darstellen.

Das habe ich gerade auch mal probiert über routine.🙈klingel dauert ja fast 15min bis er meine routine ausführt.So nicht verwendbar

**Comment by maysn10** [comment]
Hallo

Wird bei den Adapter auch ein Türsensor unterstützt?
Ich würde mir gerne diesen Sensor umbauen, sobald das Schloss aufgesperrt ist soll über Iobroker die Base den Modus wechseln und umgekehrt.
@bropat Danke für deinen Mühe der Adapter funktioniert perfekt.

**Comment by bropat** [comment]
> Hallo
> 
> Wird bei den Adapter auch ein Türsensor unterstützt?
> Ich würde mir gerne diesen Sensor umbauen, sobald das Schloss aufgesperrt ist soll über Iobroker die Base den Modus wechseln und umgekehrt.
> @bropat Danke für deinen Mühe der Adapter funktioniert perfekt.

Hallo @maysn10,

im Moment nicht. Zur Zeit arbeite ich an der Integration der Push-Benachrichtigungen, die für die 2FA und für die Eventbenachrichtigung (Bewegung entdeckt usw.) benötigt werden.

**Comment by CreaTeXGER** [comment]
Hallo,

@ bropat

Vielen Dank für deine bisherige Arbeit 👍 

Einer Erweiterung des Adapters um 2FA und die weiteren Module, wie zB. der Türsensor, wären toll. Dies ist hinsichtlich der Automatisierung notwendig.

Gruß

**Comment by rotzaff** [comment]
Zum Thema Eufy würde ich mich auch freuen, wenn die Staubsaugerroboter über den Adapter gesteuert werden könnten :)
Viele Grüße
Rotzaff

**Comment by bropat** [comment]
> Zum Thema Eufy würde ich mich auch freuen, wenn die Staubsaugerroboter über den Adapter gesteuert werden könnten :)
> Viele Grüße
> Rotzaff

Dieser Adapter wird nur die Eufy Produkte der Familie "Security" unterstützen.

**Comment by bropat** [comment]
Eine neue Version (0.0.2) wurde veröffentlicht:

* Added push notification support for event notification (raw notifications!)
* Added 2FA (token renewal needs manual intervention)
* Added P2P communication with station (event: Alarm mode change)
* Added more device classes (sensors, locks, keypads) with no actions (at the moment! WIP!)
* Added all eufy camera devices release to date
* Added battery state to eufy cameras

**Comment by 3RROR-TINO** [comment]
Hi kommt auch die Indoor Cam Pan & Tilt mit in den Adapter das wäre Hammer!?

Lg Tino

**Comment by bropat** [comment]
> Indoor Cam Pan & Tilt

Hi,

sollte eigentlich mit der letzten Version schon "aufscheinen". Es wurden aber noch keine spezifischen Funktionalitäten integriert.

Grüße
Patrick

**Comment by tofrie** [comment]
Ich habe versucht den Status bei Skript zu wechseln. Leider komme ich nicht zum Erfolg.

**Comment by MaxWinterstein** [comment]
@bropat Ich habe dich mal bei https://github.com/FuzzyMistborn/python-eufy-security/issues/3 erwähnt. Das scheint aktuell die beste bassis für eine HomeAssistant implementierung zu werden. 

Soweit ich das sehe stecken die dort aber fest beim versuch die P2P Kommunikation aufzubröseln, wo du wohl mehr erfolg hast.

Danke!

**Comment by iHorstD** [comment]
Hi, there is now a Homebridge Plugin available.
Features notification on bell and detection and also video for HomeKit.
I would love to see notifications as state in ioBroker....
[https://github.com/birkir/homebridge-plugin-eufy-security]
(https://github.com/birkir/homebridge-plugin-eufy-security)

Regards,

**Comment by knutbrecht** [comment]
Hallo.

ich stell mich glaub ich zu blöd an... bekomme den Adapter nicht installiert. Ich bekomme folgende Fehlermeldung:

`$ ./iobroker url "/opt/iobroker/node_modules/iobroker.eufy-security"
install /opt/iobroker/node_modules/iobroker.eufy-security
NPM version: 6.14.9
npm install /opt/iobroker/node_modules/iobroker.eufy-security --loglevel error --prefix "/opt/iobroker" (System call)
npm 
ERR! code ELOOPnpm ERR! syscall opennpm ERR! path /opt/iobroker/node_modules/iobroker.eufy-security/node_modules/@types/iobroker/package.json.3018281288npm ERR! errno -40
npm ERR! ELOOP: too many symbolic links encountered, open '/opt/iobroker/node_modules/iobroker.eufy-security/node_modules/@types/iobroker/package.json.3018281288'
npm ERR! A complete log of this run can be found in:npm ERR!     /home/iobroker/.npm/_logs/2020-12-02T14_51_25_056Z-debug.log
ERROR: host.phoscon Cannot install /opt/iobroker/node_modules/iobroker.eufy-security: 216
ERROR: process exited with code 25`


Wäre toll wenn mir jemand einen Tip geben könnte... Grüße.

**Comment by bropat** [comment]
Ich bitte euch alle Fragen und Wünsche zum Adapter hier im Forum zu posten:

[https://forum.iobroker.net/topic/39276/neuer-adapter-eufy-security](https://forum.iobroker.net/topic/39276/neuer-adapter-eufy-security)

**Comment by bropat** [comment]
> Hallo.
> 
> ich stell mich glaub ich zu blöd an... bekomme den Adapter nicht installiert. Ich bekomme folgende Fehlermeldung:
> 
> `$ ./iobroker url "/opt/iobroker/node_modules/iobroker.eufy-security"
> install /opt/iobroker/node_modules/iobroker.eufy-security
> NPM version: 6.14.9
> npm install /opt/iobroker/node_modules/iobroker.eufy-security --loglevel error --prefix "/opt/iobroker" (System call)
> npm 
> ERR! code ELOOPnpm ERR! syscall opennpm ERR! path /opt/iobroker/node_modules/iobroker.eufy-security/node_modules/@types/iobroker/package.json.3018281288npm ERR! errno -40
> npm ERR! ELOOP: too many symbolic links encountered, open '/opt/iobroker/node_modules/iobroker.eufy-security/node_modules/@types/iobroker/package.json.3018281288'
> npm ERR! A complete log of this run can be found in:npm ERR!     /home/iobroker/.npm/_logs/2020-12-02T14_51_25_056Z-debug.log
> ERROR: host.phoscon Cannot install /opt/iobroker/node_modules/iobroker.eufy-security: 216
> ERROR: process exited with code 25`
> 
> 
> Wäre toll wenn mir jemand einen Tip geben könnte... Grüße.

[https://www.iobroker.net/#de/documentation/admin/adapter.md](https://www.iobroker.net/#de/documentation/admin/adapter.md)

siehe Punkt Nr. 5

**Comment by knutbrecht** [comment]
> > Wäre toll wenn mir jemand einen Tip geben könnte... Grüße.
> 
> https://www.iobroker.net/#de/documentation/admin/adapter.md
> 
> siehe Punkt Nr. 5

Hallo.

Hatte es schon so gemacht...

Hab heute die 0.0.4 installiert. Das ging problemlos und es werden nun auch diverse Objekte erkannt.
VIELEN DANK für die Arbeit bisher!!

Grüße, Knut

**Comment by cyber3211** [comment]
Hallo, erst mal danke für deine Arbeit bisher.

Ich besitze die Eufy Türklingel T8200 und habe mit dem Adapter folgendes Problem:
0.0.1 konnte ich installieren und funktionierte auch ohne Probleme, Türklingel wurde erkannt und es wurden auch die entsprechende Objekte angezeigt.

0.0.3 konnte ich nicht installieren, gleiche Probleme wie beim Vorgäner.

0.0.4 kann ich problemlos installieren, er erscheinen im Log allerdings folgende Meldungen und es werden keine Objekte angezeigt. Der Adapter wird nicht grün.

Beim starten: 
eufy-security.0 | 2020-12-05 12:44:09.464 | info | (1287) Terminated (NO_ERROR): Without reason
-- | -- | -- | --
eufy-security.0 | 2020-12-05 12:44:09.463 | info | (1287) terminating
eufy-security.0 | 2020-12-05 12:44:09.406 | error | at fulfilled (/opt/iobroker/node_modules/iobroker.eufy-security/build/main.js:27:58)
eufy-security.0 | 2020-12-05 12:44:09.406 | error | at Generator.next (<anonymous>)
eufy-security.0 | 2020-12-05 12:44:09.406 | error | at EufySecurity.<anonymous> (/opt/iobroker/node_modules/iobroker.eufy-security/build/main.js:282:56)
eufy-security.0 | 2020-12-05 12:44:09.406 | error | at Object.generateUDID (/opt/iobroker/node_modules/iobroker.eufy-security/build/lib/eufy-security/utils.js:42:34)
eufy-security.0 | 2020-12-05 12:44:09.406 | error | (1287) TypeError: crypto.randomBytes(...).readBigUInt64BE is not a function
eufy-security.0 | 2020-12-05 12:44:09.405 | error | (1287) unhandled promise rejection: crypto.randomBytes(...).readBigUInt64BE is not a function
Unhandled | 2020-12-05 12:44:09.404 | error | promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
eufy-security.0 | 2020-12-05 12:44:09.301 | info | (1287) starting. Version 0.0.4 in /opt/iobroker/node_modules/iobroker.eufy-security, node: v10.19.0, js-controller: 3.1.6

und dann kontinuirlich alle paar Sekunden:
eufy-security.0 | 2020-12-05 12:45:14.401 | info | (1363) Terminated (NO_ERROR): Without reason
-- | -- | -- | --
eufy-security.0 | 2020-12-05 12:45:14.400 | info | (1363) terminating
eufy-security.0 | 2020-12-05 12:45:14.345 | error | (1363) TypeError: crypto.randomBytes(...).readBigUInt64BE is not a function at Object.generateUDID (/opt/iobroker/node_modules/iobroker.eufy-security/build/lib/eufy-security/utils.js:42:34) at
eufy-security.0 | 2020-12-05 12:45:14.344 | error | (1363) unhandled promise rejection: crypto.randomBytes(...).readBigUInt64BE is not a function
eufy-security.0 | 2020-12-05 12:45:14.343 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
eufy-security.0 | 2020-12-05 12:45:14.241 | info | (1363) starting. Version 0.0.4 in /opt/iobroker/node_modules/iobroker.eufy-security, node: v10.19.0, js-controller: 3.1.6

Gibt dafür eine Lösung?

Schöne Grüße
Ingo

**Comment by bropat** [comment]
@cyber3211 Ja du musst mindestens auf NodeJs v.10.20.0 updaten. Vorher gabs die Funktion "readBigUInt64BE" nicht.

**Comment by Apollon77** [comment]
@bropat Dann gib am besten in der Adapter package.json die minimale nodejs version an!!

**Comment by bropat** [comment]
@Apollon77 Habe ich nun gemacht.

**Comment by bropat** [comment]
Version 0.0.5 wurde gerade veröffentlicht:

(bropat) Added event states for camera (motion detected, person detected)
(bropat) Added event states for entry sensor (open/closed)
(bropat) Added event states for motion sensor (motion detected)
(bropat) Added event states for doorbell (motion detected, person detected, ringing)
(bropat) Added event states for indoor camera (motion detected, person detected, crying detected, sound detected, pet detected)
(bropat) Added entry sensor state (online, offline, etc.)
(bropat) Added entry sensor low battery
(bropat) Added motion sensor state (online, offline, etc.)
(bropat) Added motion sensor low battery
(bropat) Added keypad state (online, offline, etc.)
(bropat) Added keypad low battery

@maysn10 Mit dieser Version sollte nun Türsensor funktionieren. Bitte Testen und Feedback geben (kann es leider nicht selbst testen).

@CreaTeXGER Die neue Version Unterstützt weitere Module. :)

@3RROR-TINO Diese Version unterstützt einige Events der Indoor Kameras. Bitte Testen und Feedback geben (kann es leider nicht selbst testen).

@cyber3211 Mit dieser Version sollte es bei dir auch wieder laufen. :)
@iHorstD This version supports now motion detection, person detection and ringing as states for doorbell. Please test it and let me know ().

**Comment by eyichbins** [comment]
Nabend, also bei mir läuft der Adapter . Sehe die Bilder zB vom letzten Snapshot. kann auch ein Livevideo starten für Zb 2min und in Windows über den VLC Player abspielen. Soweit also Prima :-)
ABER wie schaffe ich es, das Live Bild im Iobroker VIS anzeigen zu lassen? Hab jetzt alles mögliche getestet, bekomme aber nur das mit dem Snapshot Bild hin.

Jemand eine Idee?

Vielen Dank

**Comment by Rockclimber87** [comment]
Hallo Zusammen,

ich habe nun auch den Adapter am laufen und meine Cameras werden angezeigt.
Wie bekomme ich nun ein Livebild in der VIS des ioBroker??
Da stehe ich irgendwie aufm Schlauch.
Danke.

**Comment by ldittmar81** [comment]
@bropat Please request repo addition ... details see https://github.com/ioBroker/ioBroker.repositories

**Comment by bropat** [comment]
@ldittmar81 As soon as I consider the adapter stable, I will ask to add it to the stable branch. It already exists in the Beta branch.

**Comment by ldittmar81** [comment]
https://github.com/bropat/ioBroker.eufy-security

@bropat there are 2 ioBroker branches latest/beta and stable and I can't find your adapter on the beta branch. Your adapter should be here https://github.com/ioBroker/ioBroker.repositories/blob/6af0718ac995416326423c695d3e057124ef57e1/sources-dist.json#L427 but it isn't there.

**Comment by bropat** [comment]
@ldittmar81 Check [this](https://github.com/ioBroker/ioBroker.repositories/pull/1177) out.

**Comment by bropat** [comment]
It was removed as requested by anker :(

https://github.com/ioBroker/ioBroker.repositories/commit/868b53f73e43b52cb024157848e1abbd26d8f1d3

**Comment by ldittmar81** [comment]
Its back :-) https://github.com/bropat/ioBroker.eusec

**Comment by denjo82** [comment]
Läuft der Adapter auch mir der eufy Security Video Doorbell??

**Comment by tofrie** [comment]
> Läuft der Adapter auch mir der eufy Security Video Doorbell??

Ja bei mir läuft auch die Doorbell perfekt. Eine genaue Übersicht der unterstützten Modelle findest du in der Adapter Beschreibung.

**Comment by denjo82** [comment]
Also hat man dort wenn ich richtig gesehen habe ein datenpunkt wenn es klingelt???

**Comment by tofrie** [comment]
> Also hat man dort wenn ich richtig gesehen habe ein datenpunkt wenn es klingelt???

Genau, der nennt sich Ringing. Ich selbst nutze ihn um unsere Telefone klingeln zu lassen. So bekomme ich das Klingeln auch im Garten mit.

**Comment by denjo82** [comment]
Okay cool, letzte Frage wäre "hat nix mit iobroker zu tun" kann man eine interne Glocke digital daran anschließen?

**Comment by mcm1957** [comment]
Link to adapter repository: https://github.com/bropat/ioBroker.eusec

Adapter has been release. Please report any issues at adapter repository.
