### ISSUE TITLE
Adapter für Heizölpreise

### ISSUE THREAD

**Issue by atifan** [ioBroker/AdapterRequests#457]
Wäre super wenn mal ein Adapter erstellt würde, der die aktuellen Heizölpreise als Datenpunkt im IoBroker zur Verfügung stellt. Es gibt im IoBroker Forum zwar ein paar Scripte die das machen sollen, aber irgendwie funktionieren die nicht so richtig. Ein Adapter wäre auch einfacher zu finden und zu installieren. Ich denke, dass aktuellen Ölpreis viele Leute interessieren würde.

**Comment by bazidibavaria** [comment]
just as information
https://forum.iobroker.net/topic/23885/vorlage-heiz%C3%B6lpreisabfrage-%C3%BCber-esyoil-com/22

**Comment by james3332** [comment]
heute möchte ich Ihnen etwas über die Esyoil Heizölpreise erzählen. Esyoil ist eine bekannte Plattform, die Informationen und Dienstleistungen rund um den Heizölmarkt bietet, einschließlich aktueller Heizölpreise.

Die Esyoil Heizölpreise sind ein nützliches Werkzeug für Verbraucherinnen und Verbraucher, um die aktuellen Preise für Heizöl zu überprüfen. Die Plattform bietet eine transparente Darstellung der Preise verschiedener Anbieter und ermöglicht es den Nutzern, die besten Angebote zu finden.
klicken Sie hier
https://nachrichtenmorgen.de/esyoil-heizoelpreise/

**Comment by Ilovegym66** [comment]
already exists
https://github.com/TA2k/ioBroker.heizoel

**Comment by mcm1957** [comment]
@TA2k
Ist your adapter working so that we can close here?

**Comment by mcm1957** [comment]
> @TA2k Ist your adapter working so that we can close here?

Please provide some statusupdate.
Is this adapter still under development?
Please add it to repositories once useable for users.

**Comment by Jamestabey** [comment]
Adapter für Heizölpreise sind nützliche Werkzeuge, die es den Verbrauchern ermöglichen, die aktuellen Preise für Heizöl zu überwachen und informierte Entscheidungen zu treffen. Diese Adapter können in Verbindung mit speziellen Softwareanwendungen oder Online-Plattformen verwendet werden, um Echtzeitinformationen über die Preise von Heizöl zu erhalten. Sie werden in der Regel mit verschiedenen Sensoren und Verbindungsmöglichkeiten geliefert, um eine genaue Messung und Übertragung der Daten zu ermöglichen. Mit einem Heizölpreisadapter können Verbraucher die Preisentwicklungen verfolgen, um den besten Zeitpunkt für den Kauf von Heizöl zu ermitteln und potenzielle Einsparungen zu erzielen. Diese Adapter tragen zur Transparenz auf dem Heizölmarkt bei und ermöglichen den Verbrauchern eine fundierte Entscheidung in Bezug auf ihren Heizölbedarf. Weitere Informationen finden Sie unter [Secret German Jodel](https://nachrichtenmorgen.de/secret-german-jodel-verborgene-wahrheiten/).
