### ISSUE TITLE
LON für Biobroker 

### ISSUE THREAD

**Issue by herby571128** [ioBroker/AdapterRequests#461]
LON Network is a automation standard for buildings, issued by an idea of several people like Bill Gates, Steve Jobs etc.
The interoperability between the products of several companies is promised by the use of standard variables so called snvt´s. Every LON unit has it's own, not changeable ID, placed in the LON Chip. This Chip regulates the communication between the units.
There are different possibilities to do the conversation for example on twisted pair up to 1 km, on power line or via radio transmissions.
The laws of LON are watched by the LON MARK organization.
There exists no Lon based visualization, so I think the io broker would be an instrument to do this.

**Comment by herby571128** [comment]
is there any adapter awaiable for a Lon based device to integrate in Biobroker

**Comment by Apollon77** [comment]
@herby571128 can you please edit the first post and create the adapter request with as much infos as possible from the asked things?

**Comment by herby571128** [comment]
LON Network is a automation standard for buildings, issued by an idea of several people like Bill Gates, Steve Jobs etc.
The interoperability between the products of several companies is promised by the use of standard variables so called snvt´s. Every LON unit has it's own, not changeable ID, placed in the LON Chip. This Chip regulates the communication between the units. 
There are different possibilities to do the conversation for example on twisted pair up to 1 km, on power line or via radio transmissions. 
The laws of LON are watched by the LON MARK organization.
There exists no Lon based visualization, so I think the io broker would be an instrument to do this.

**Comment by mcm1957** [comment]
duplicated by https://github.com/ioBroker/AdapterRequests/issues/615
