### ISSUE TITLE
Fehlende States beim Start

### ISSUE THREAD

**Issue by SoerenKaiser99** [ioBroker/AdapterRequests#469]
tado.0.ID.Rooms.x.setting.temperature &

tado.0.ID.Rooms.x.setting.power 

sind notwendige States für die Automatisierung/Weiterverarbeitung 
Sie bedienen an/aus und die overlay Temp. Beide sollten direkt beim Start angelegt werden

**Comment by Apollon77** [comment]
Please open Issue with the tado Adapter
