### ISSUE TITLE
Mediola Gateway

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/AdapterRequests#47]
http://forum.iobroker.net/viewtopic.php?f=34&t=5559

Migrated from Trello with 3 votes

**Comment by steckenpferd** [comment]
https://www.mediola.com/api 

Call to offer the hardware:
https://forum.iobroker.net/viewtopic.php?f=8&t=6807

**Comment by AcidSubway** [comment]
is the Adapter on the to do List?

**Comment by ldittmar81** [comment]
https://github.com/bergos/mediola-aio-gateway
https://github.com/andyboeh/mediola2mqtt
https://github.com/tobias-d-oe/fheMcontrol

**Comment by oelison** [comment]
I will try to make this adapter. But only for old HW Version 3.4.7. This is my own HW and I send IR messages into a room with that.

**Comment by AcidSubway** [comment]
which SW do you mean exactly, I have a Mediola V5 Plus

**Comment by oelison** [comment]
```
HWV:F9
VER:3.4.7
RFV:0209
RFF:0347
RFM:0d
EID:01
FF:11
TZ:21
NAME:AIO GATEWAY
VID:FFFF
```
I think it is a Gateway V4.

**Comment by AcidSubway** [comment]
I have a V5 but I think it will also work. THANKS TO YOU that you are BEGINNING. If you need help to test I'm there :D

**Comment by AcidSubway** [comment]
I have a V5 but I think it will also work. THANKS TO YOU that you are BEGINNING. If you need help to test I'm there :D

**Comment by mcm1957** [comment]
Link to adapter (development state !!!) for reference https://github.com/oelison/ioBroker.mediola-gateway

**Comment by oelison** [comment]
[german forum on ioBroker](https://forum.iobroker.net/topic/63560/neuer-adapter-mediola-gateway)

**Comment by mcm1957** [comment]
Request for Latest: https://github.com/ioBroker/ioBroker.repositories/pull/2313

**Comment by mcm1957** [comment]
@oelison 

Kannst du bitte checken ob https://github.com/ioBroker/AdapterRequests/issues/848 ein Duplikat zu diesem issue ist? Geht zwar um andere HW aber Gateway scheint v mediola zu sein. Ev kann man das mit abdecken wenn nicht eh der Fall ist.

**Comment by oelison** [comment]
Der Adapter sollte erweiterbar sein. Leider habe ich kein Gateway v6.

**Comment by mcm1957** [comment]
Published at latest
