### ISSUE TITLE
Tibber Stromzulieferer

### ISSUE THREAD

**Issue by Michaelnorge** [ioBroker/AdapterRequests#475]
Ich würde mich über eine Schnittstelle zu Tibber freuen.

Tibber ist ein automatischer Stromzulieferer, der aus Norwegen kommt und jetzt auch in Deutschland tätig ist.

Ich habe diese Infos schon gefunden: https://github.com/bisand/tibber-api

Außerdem gibt es für Tibber eine API-Schnittstelle: https://developer.tibber.com/

Grüße
Michael

**Comment by flinke-flasche** [comment]
So ein Adapter würde mich auch freuen

**Comment by pandar0** [comment]
Hätte auch Interesse an einen solchen Adapter. :)
Würde auch gerne unterstützen, falls Ich unterstützen kann ;)

**Comment by Apollon77** [comment]
@pandar0 Dann "Daumen hoch" im ersten Post sonst sieht es keiner

**Comment by Leviathan09** [comment]
Würde mich auch sehr interessieren
Daumen ist gesetzt

**Comment by andispammonyer** [comment]
Bin auch interessiert.
Wallbox Easee Home ist auch Tibber kompatibel

**Comment by torsten3009** [comment]
Ist es nicht möglich das ganze über ein Skript und eigene Objekte direkt schon einzubinden?
https://developer.tibber.com/explorer gibt es Beispiele.
sowohl zum melden des aktuellen Verbrauches, als auch zum Abfragen, z.b. aktueller Preis.

Hat das ggf. schon einer Probiert?

**Comment by Malz1902** [comment]
gibt es hier schon etwas neues?

**Comment by Magnus8513** [comment]
Hat hier schon jemand weiter gemacht? Würde mich nun sonst auch einmal versuchen die Infos aus der API in mein iobroker system zu holen.

**Comment by Magnus8513** [comment]
Kurzes Update: bin dran. Aus Script Basis läuft das bei mir schon in see Grundfunktionalität - bin gerade dabei auf der Basis meinen ersten iobroker Adapter daraus zu bauen. Melde mich, sobald ich etwas zum Testen haben.

**Comment by flinke-flasche** [comment]
@Magnus8513 
das wäre richtig klasse wenn das funktioniert.

**Comment by Malz1902** [comment]
@Magnus8513 vielen Dank schonmal für deine Mühe. Das klingt echt super, ich bin gespannt und freu mich

**Comment by Michaelnorge** [comment]
Super!!!!!

**Comment by Magnus8513** [comment]
ganz grobe erste Alpha steht bereit für die mutigen unter Euch: [https://github.com/Magnus8513/ioBroker.tibber.git](https://github.com/Magnus8513/ioBroker.tibber.git) 

Disclaimer: aktuell noch kein schedule hinterlegt, Daten werden also nur einmal bzw. beim neustart des adapters refreshed - gilt es noch zu ergänzen.

Finde gerade heraus, wie ich einen passenden Thread dazu im Forum eröffne. Link werde ich dann auch hier posten.

Viele Grüße,
Magnus

**Comment by Michaelnorge** [comment]
Super @Magnus8513 ,  Deine Alpha funktioniert, die Daten kommen hier rein - Preise von heute und morgen.
Die Daten sind stündlich in Folders verteilt, das macht die Sache bei der Visualisierung und der Steuerung etwas schwerer.
Das Gleiche habe neuerdings auch beim YR-Wetter Adapter so, denke mal die Daten kommen einfach so an....

Tolle Arbeit, weiter so!!!

![image](https://user-images.githubusercontent.com/42386692/128243736-135dba1d-d6ab-4d50-ac14-ba97486cba64.png)

**Comment by Magnus8513** [comment]
Danke für die Rückmeldung. Das mit den Ordnern habe ich so gemacht um möglichst nahe an der API Struktur dran zu bleiben. Bin noch ganz frisch bei ioBroker, daher wenig Erfahrung mit der Visualisierung. In welcher Struktur wäre es denn dafür am dienlichsten? Noch ist da nix in Stein gemeißelt.

**Comment by andispammonyer** [comment]
Beim Adapter vom Konkurrenten aWattar gibt es die Möglichkeit den Arbeitspreis (Netznutzung + Umlage EEG + Abgaben + Gebühren) in cent pro kwh einzustellen. Dadurch kann durch Addition des Börsenpreis der tatsächlich zu zahlende Strompreis pro Stunde direkt benutzt werden.
Könntest du das bitte noch hinzufügen?

**Comment by Magnus8513** [comment]
Auf die Gefahr Dich missverstanden zu haben: Ist das nicht genau der weit in „total“ den Du hier suchst?

**Comment by andispammonyer** [comment]
Genau davon bin ich eben auch ausgegangen aber was bedeutet denn 0,783? Euro? Cent? Pro kwh? 
Wenn es sich um den zu zahlenden Strompreis handeln würde, sollte eher sowas wie 31ct pro kwh rauskommen. Zudem sind die Netzentgelte pro PLZ unterschiedlich weshalb die TibberAPI das gar für meinen Standort abbilden kann.

**Comment by Magnus8513** [comment]
Das sind Euro und der Gebührenteil ist Lokationsabhängig. Hast Du sicher Deinen eigenen persönlichen Token hinterlegt? Die 0,783 klingen sehr nach den Wucherpreisen im Winterfell Castel die über den Demo Token geliefert werden ;).

**Comment by andispammonyer** [comment]
Ups ich hab die Preise dem Screenshot von Michaelnorge entnommen. Wusste nicht, dass er einen DemoToken verwendet hatte. Sorry

**Comment by Michaelnorge** [comment]
> Ups ich hab die Preise dem Screenshot von Michaelnorge entnommen. Wusste nicht, dass er einen DemoToken verwendet hatte. Sorry

@andispammonyer Benutze keinen Demo-Token - meine Preise sind in NOK (norwegische Krone) :-)

**Comment by Malz1902** [comment]
Ich bekomme beim installieren folgende Warnings angezeigt:
`npm WARN typedoc@0.20.28 requires a peer of typescript@3.9.x || 4.0.x || 4.1.x but none is installed. You must install peer dependencies yourself.

npm WARN typedoc@0.20.28 requires a peer of typescript@3.9.x || 4.0.x || 4.1.x but none is installed. You must install peer dependencies yourself.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: osx-temperature-sensor@1.0.7 (node_modules/osx-temperature-sensor):

npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for osx-temperature-sensor@1.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/zigbee-herdsman-converters/node_modules/fsevents):

npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/zigbee-herdsman-converters/node_modules/zigbee-herdsman/node_modules/fsevents):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/zigbee-herdsman/node_modules/fsevents):

npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})`

Auch finde ich nachdem installieren den Adapter nicht unter meinen Instanzen, was mach ich falsch?

Gibt es eigentlich schon nen ioBroker Forum Thread?

**Comment by Malz1902** [comment]
In der Tibber Api bei Current Energy Price finde ich noch zu today und tommorow den punkt  
current {
            total
            energy
            tax
            startsAt
          }

könntest du den auch noch hinzufügen?

**Comment by Malz1902** [comment]
graphql_query = "{viewer
 {name}
{homes 
	{
	address {address1 postalCode city country latitude longitude}
	}
{currentSubscription 
{priceInfo 
	{
	today {total energy tax startsAt} 
	tomorrow {total energy tax startsAt} 
	current {total energy tax startsAt}
	}
}
}
}
}"

Sollte dann ja alles an Infos erstmal liefern was nötig ist

**Comment by Magnus8513** [comment]
> In der Tibber Api bei Current Energy Price finde ich noch zu today und tommorow den punkt  
> 
> current {
> 
>             total
> 
>             energy
> 
>             tax
> 
>             startsAt
> 
>           }
> 
> 
> 
> könntest du den auch noch hinzufügen?

Habe mit ein issue dazu aufgemacht und werde das einbauen. Macht allerdings erst dann wirklich Sinn, wenn ich rausgefunden habe wie ich ein regelmäßiges polling rein bekommen - dass muss ich aber eh rausfinden ;).

**Comment by Magnus8513** [comment]
> energy  ist der Strompreis
> 
> tax denk ich mal die ganzen Steuern und Umlagen
> 
> total dann der Preis den ich pro kwh zahle oder?
Korrekt.

**Comment by Magnus8513** [comment]
> Vielen Dank, werde den Adapter mal installieren und testen :-)
> 
> 
> 
> Was später richtig geil wäre, wenn man den Adapter Smartmeter der nden aktuellen Stromverbrauch misst mit einbauen könnte :-)
> 
> Gibt es eigentlich schon nen ioBroker Forum Thread?

Thread kommt noch. 

Smart Meter integration schaue ich mir an. Wenn ich sie api richtig lese, liefert diese die live Daten aber nur bei Verwendung des Tibber eigenen Smart Meter add on Moduls (Puls heißt das glaube ich) und das gibt es bisher wohl nur in Norwegen. 

Uber den Discovergy Adapter bekommst du aber heute schon Daten aus deinem Smart Meter falls es ein Discovergy Meter ist - was auf die meisten in Deutschland zutreffen sollte - oder nicht?

**Comment by Malz1902** [comment]
@Magnus8513 vielen Dank für Deine Mühe :-)

Wäre ein Thread im ioBroker Forum nicht evtl. besser, vielleicht nutzen da noch mehr tibber und könnten bei der Entwicklung helfen oder so :-)

Evtl. könnte man später auch mit dem sourceanalytix den aktuellen Strompreis dort immer einfügen bzgl der Kostenberechnung vom Strom asber das ist noch zukunftsmusik.

Kann man dann eigentlich später an tibber den korrekten Verbrauch melden, momentan wird bei mir z.b. Pauschal mit einem Durchschnittspreis vom Monat gerechnet

**Comment by Malz1902** [comment]
> > Vielen Dank, werde den Adapter mal installieren und testen :-)
> > Was später richtig geil wäre, wenn man den Adapter Smartmeter der nden aktuellen Stromverbrauch misst mit einbauen könnte :-)
> > Gibt es eigentlich schon nen ioBroker Forum Thread?
> 
> Thread kommt noch.
> 
> Smart Meter integration schaue ich mir an. Wenn ich sie api richtig lese, liefert diese die live Daten aber nur bei Verwendung des Tibber eigenen Smart Meter add on Moduls (Puls heißt das glaube ich) und das gibt es bisher wohl nur in Norwegen.
> 
> Uber den Discovergy Adapter bekommst du aber heute schon Daten aus deinem Smart Meter falls es ein Discovergy Meter ist - was auf die meisten in Deutschland zutreffen sollte - oder nicht?

Ich nutze den smartmeter Adapter im ioBroker um meinen Stromzähler auszulesen, aktueller Verbrauch und gesamt

**Comment by Michaelnorge** [comment]
> > > Vielen Dank, werde den Adapter mal installieren und testen :-)
> > > Was später richtig geil wäre, wenn man den Adapter Smartmeter der nden aktuellen Stromverbrauch misst mit einbauen könnte :-)
> > > Gibt es eigentlich schon nen ioBroker Forum Thread?
> > 
> > 
> > Thread kommt noch.
> > Smart Meter integration schaue ich mir an. Wenn ich sie api richtig lese, liefert diese die live Daten aber nur bei Verwendung des Tibber eigenen Smart Meter add on Moduls (Puls heißt das glaube ich) und das gibt es bisher wohl nur in Norwegen.
> > Uber den Discovergy Adapter bekommst du aber heute schon Daten aus deinem Smart Meter falls es ein Discovergy Meter ist - was auf die meisten in Deutschland zutreffen sollte - oder nicht?
> 
> Ich nutze den smartmeter Adapter im ioBroker um meinen Stromzähler auszulesen, aktueller Verbrauch und gesamt

Mein Stromzähler liefert die Daten via SIM-Karte direkt zu Tibber, sehe daher Gesamtverbrauch in der App.

**Comment by Malz1902** [comment]
> > > > Vielen Dank, werde den Adapter mal installieren und testen :-)
> > > > Was später richtig geil wäre, wenn man den Adapter Smartmeter der nden aktuellen Stromverbrauch misst mit einbauen könnte :-)
> > > > Gibt es eigentlich schon nen ioBroker Forum Thread?
> > > 
> > > 
> > > Thread kommt noch.
> > > Smart Meter integration schaue ich mir an. Wenn ich sie api richtig lese, liefert diese die live Daten aber nur bei Verwendung des Tibber eigenen Smart Meter add on Moduls (Puls heißt das glaube ich) und das gibt es bisher wohl nur in Norwegen.
> > > Uber den Discovergy Adapter bekommst du aber heute schon Daten aus deinem Smart Meter falls es ein Discovergy Meter ist - was auf die meisten in Deutschland zutreffen sollte - oder nicht?
> > 
> > 
> > Ich nutze den smartmeter Adapter im ioBroker um meinen Stromzähler auszulesen, aktueller Verbrauch und gesamt
> 
> Mein Stromzähler liefert die Daten via SIM-Karte direkt zu Tibber, sehe daher Gesamtverbrauch in der App.

Sowas kann mein Stromzähler nicht :-D
Ich lese den über die IR Schnittstelle aus und bekomme die Daten so über den ioBroker

**Comment by Michaelnorge** [comment]
> Danke für die Rückmeldung. Das mit den Ordnern habe ich so gemacht um möglichst nahe an der API Struktur dran zu bleiben. Bin noch ganz frisch bei ioBroker, daher wenig Erfahrung mit der Visualisierung. In welcher Struktur wäre es denn dafür am dienlichsten? Noch ist da nix in Stein gemeißelt.

Hallo :-)
Ich bekomme es wegen der Ordnerstruktur irgendwie nicht hin, mir ein Diagramm in VIS zu bauen, das vergleichbar ist mit dem Diagramm in der Tibber-App (Vlt kann mich da jemand auf eine gute Idee bringen?)

Bekommt man über die API eigentlich generell die Daten raus, die man in der APP sehen kann?
So wie hier in dem Screenshot?

![Screenshot_20210810_182538_com tibber android](https://user-images.githubusercontent.com/42386692/128897183-d44cfcae-31b8-400f-9ace-716cc3abdca7.jpg)

Das wäre sehr interessant für mich, das in VIS einzubinden.

Grüße
Michael

**Comment by Magnus8513** [comment]
@Malz1902 
> Ich lese den über die IR Schnittstelle aus und bekomme die Daten so über den ioBroker

ok. mach mir doch auf github ein issue dazu auf, dann schaue ich mir das bei Gelegenheit an.

**Comment by Magnus8513** [comment]
@Michaelnorge 
> Hallo :-)
> Ich bekomme es wegen der Ordnerstruktur irgendwie nicht hin, mir ein Diagramm in VIS zu bauen, das vergleichbar ist mit dem Diagramm in der Tibber-App (Vlt kann mich da jemand auf eine gute Idee bringen?)
> 
> Bekommt man über die API eigentlich generell die Daten raus, die man in der APP sehen kann?
> So wie hier in dem Screenshot?
> 
> ![Screenshot_20210810_182538_com tibber android](https://user-images.githubusercontent.com/42386692/128897513-f6c70367-9637-40d3-95d0-56b28928661c.jpg)
> 
> Das wäre sehr interessant für mich, das in VIS einzubinden.
> 
> Grüße
> Michael

mit VIS kann ich leider (noch) mangels Erfahrung nicht helfen. Wie gewünscht sind die "current" Daten nun aber auch eingebunden und werden regelmäßig aktualisiert.  

Geht es damit nun besser?

Wo verfügbar kann ich gerne auch den Verbrauch den tibber liefert mit ausgeben - muss mir aber mal anschauen wie ich das sauber unterscheide, fall ein home keine Daten hat.

**Comment by Magnus8513** [comment]
> In der Tibber Api bei Current Energy Price finde ich noch zu today und tommorow den punkt
> current {
> total
> energy
> tax
> startsAt
> }
> 
> könntest du den auch noch hinzufügen?

ist nun da.

**Comment by Magnus8513** [comment]
Nun auch ein [Link zum Test Thema im iobroker Forum](https://forum.iobroker.net/topic/46954/test-adapter-tibber-v0-1-x)

@Michaelnorge : kannst Du mir hier die Rechte geben das issue hier in Bearbeitug zu nehmen und es als "in arbeit" zu taggen?

**Comment by sphings79** [comment]
Da der Adapter anscheinend nicht weiterentwickelt wird, hier mal der Link zu einem andern:
https://github.com/Codibris/ioBroker.tibberconnect
https://forum.iobroker.net/topic/52486/test-adapter-tibberconnect-0-0-x-inkl-tibber-pulse
