### ISSUE TITLE
Intesis WiFi Adapter for Airconditioning (Mitsubishi Heavy and others)

### ISSUE THREAD

**Issue by RandGH** [ioBroker/AdapterRequests#476]
The Intesis WiFi gateway is intended to control various Air Conditioning brands via App or local Web interface.

complete list of gateways https://www.intesis.com/products/ac-interfaces/wifi-gateways

The one for Mitsubishi Heavy's is here
https://www.intesis.com/products/ac-interfaces/wifi-gateways/mitsubishi-heavy-ascii-wifi-ac-mh-ac-wmp-1?ordercode=INWMPMHI001I000

There are various 'drivers' available for commercial smart home systems, but also an API documentation:
https://cdn.hms-networks.com/docs/librariesprovider11/manuals-design-guides/wmp-protocol-specifications.pdf

Theoretically (unverified) all gateways should use the same API (potentially functionality not being available for specific models not working)

There are previous integrations available for these on Github (https://github.com/search?q=intesis), some are for integration via WeMos D1)
OpenHAB
https://community.openhab.org/t/anyone-using-intesishome-wifi-control-of-mini-split-ac/11031/100
Homebridge
https://github.com/sj26/homebridge-intesisbox
HASS
https://github.com/jnimmo/hass-intesisbox

Also there is an ongoing discussion on the forum for this (which drifted to the WeMos solution)
https://forum.iobroker.net/topic/17041/anfrage-airconwithme-intesishome-klimasteuerung-adapter/12
but also contains a Shell script to control the Intesis Wifi adapter

There also seems to be an IOBroker adapter for intesishome (https://github.com/maxtox/ioBroker.intesishome) 
it never made it to stable, looks like it has been abandoned. 
It is also not clear if this is connecting to the same devices or potentially MELcloud (which is the solution for Mitsubishi Electric AC's (opposed to Mitsubishi *Heavy* ACs))

**Is this device already integrated in homebridge? Might the ham adapter together with the homebridge plugin be sufficient?**
I can't t verify it as this point as I don't have the adapters/AC Units yet. I will post accordingly in the above mentioned thread

**Comment by RandGH** [comment]
Might actually be a duplicate of 
https://github.com/ioBroker/AdapterRequests/issues/133

**Comment by weggetor** [comment]
I tired to implement an adapter for the airconwithme wlan adapter:
Still in alpha, but works fine with my Mitsubishi heavy:

https://github.com/weggetor/ioBroker.airconwithme

**Comment by ldittmar81** [comment]
@Apollon77 can be closed. Its stable
