### ISSUE TITLE
Cross-Platform Systeminformation

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/AdapterRequests#48]
Ein Plugin um Systeminformationen aus dem entsprechenden System zu holen.

hier eine Basis: https://github.com/sebhildebrandt/systeminformation

Migrated from Trello with 0 votes

**Comment by AWhiteKnight** [comment]
Könnte hier mit abgedeckt werden: https://github.com/AWhiteKnight/ioBroker.moma

**Comment by GermanBluefox** [comment]
May be... But now it is not too much documentation about it.
What the protocol it uses for monitoring? How to configure devices?

вт, 25 сент. 2018 г. в 14:08, AWhiteKnight <notifications@github.com>:

**Comment by AWhiteKnight** [comment]
Right now it is just the first try of writing an adapter doing not more then the findings of apollon77. 
The intention is to have a possibility to monitor and manage my home it infrastructure.
That is 25 ECU, SBC, PC & NAS connected to 3 Router running Ubuntu, Debian, Raspbian, openSUSE, QTS, Fritz!OS, other custom Linux-Derivates and of course there is also Windows 10.
So the capability of cross platform system information will be preliminary for that purpose.

**Comment by AWhiteKnight** [comment]
The concept is to have a separation between data gathering and ui. 
Data gathering has to be installed on every machine, the ui only on the master within a multihost installation.

**Comment by AWhiteKnight** [comment]
Some Screenshots
![moma-config](https://user-images.githubusercontent.com/42740052/46040529-d14e3080-
c110-11e8-9c9a-35e34473634f.png)
![moma-instanzes](https://user-images.githubusercontent.com/42740052/46040531-d3b08a80-c110-11e8-8b84-4c9e998cbe2f.png)
![moma-multihost](https://user-images.githubusercontent.com/42740052/46040536-d7441180-c110-11e8-9b7d-a286684ae660.png)
![moma-objects](https://user-images.githubusercontent.com/42740052/46040537-d7441180-c110-11e8-9256-63d92c994792.png)

**Comment by ldittmar81** [comment]
https://github.com/frankjoke/ioBroker.systeminfo
https://github.com/iobroker-community-adapters/ioBroker.info
https://github.com/AWhiteKnight/ioBroker.moma

@Apollon77 maybe this can be closed :-)
