### ISSUE TITLE
Hyperion.ng

### ISSUE THREAD

**Issue by dannyv1101** [ioBroker/AdapterRequests#483]
Hi, is it possible to make an adapter for hyperion ng, or work on the "normal" hyperion adapter to work with hyperion ng???
That would be great!!!

**Comment by Apollon77** [comment]
For an Adapter request it is a bad idea to ignore the template ... so everything is missing, Links, Details, and such ...

Additionally: Did you created an issue with the Hyperion Adapter to ask for an enhancement there?

**Comment by emddummi** [comment]
We have already one Adapter.

https://github.com/felixganzer/ioBroker.hyperion_ng

**Comment by mcm1957** [comment]
Ok, adapter is a available at latest repo.
Lets lose here
