### ISSUE TITLE
Philips Fernseher Adapter

### ISSUE THREAD

**Issue by michihorni** [ioBroker/AdapterRequests#486]
Ich suche einen Adapter für Philips Fernseher mit Ambilight, leider habe ich so einen Adapter hier noch nicht gefunden.

Gruß
Michael

**Comment by Apollon77** [comment]
https://github.com/AlCalzone/ioBroker.philips-tv ?! (sogar im repo)

**Comment by michihorni** [comment]
Hallo Ingo

vielen Dank, hab ich wohl übersehen ;-)
 

Mit freundlichen Grüßen
Michael Horn

 
 

Gesendet: Sonntag, 11. Oktober 2020 um 17:28 Uhr
Von: "Ingo Fischer" <notifications@github.com>
An: "ioBroker/AdapterRequests" <AdapterRequests@noreply.github.com>
Cc: "michihorni" <michaelhorn@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [ioBroker/AdapterRequests] Philips Fernseher Adapter (#486)


 

https://github.com/AlCalzone/ioBroker.philips-tv ?! (sogar im repo)
