### ISSUE TITLE
Nuki Smartlock

### ISSUE THREAD

**Issue by eXTreMe-1337** [ioBroker/AdapterRequests#49]
Nuki Smartlock
API Documentation: https://nuki.io/de/api/

**Comment by GermanBluefox** [comment]
https://github.com/smaragdschlange/ioBroker.nuki

**Comment by Apollon77** [comment]
Homebridge modules exist: homebridge-nukiio as example.

Please check if the new ioBroker.ham Adapter can help here: see https://forum.iobroker.net/viewtopic.php?f=36&t=14972

**Comment by Apollon77** [comment]
https://forum.iobroker.net/viewtopic.php?f=20&t=17465
