### ISSUE TITLE
Mediola Adapter oder wie 868MHz ansteuern?

### ISSUE THREAD

**Issue by bencobi** [ioBroker/AdapterRequests#492]
Hallo zusammen,
Ich habe bidirektionale Elero Rolladenmotoren. Diese laufen über die Grequenz 868MHz.

Von Elero gibt es ein Gateway, welches diese anspricht und man somit über die Herstellerapp die Rolladen steuern kann. Leider ist das Centero Home Gateway nicht erreichbar außer über die App. 

Jetzt habe ich mir ein Mediola V6 Gateway genommen, in der Hoffnung dieses mit dem IoBroker ansteuern zu können. Ich habe da was über HTTP Requestd gehört, dazu gibt es auch eine Dokumentation. Jedoch weiß ich nicht wie ich einen Rolladenmotor anspreche, also mit welchem HTTP-Request. 

Mediola ist ja relatov umfangreich. Vielleicht wäre es eine Idee dafür ein Adapter zu erstellen. Oder hat sonst jemand ein Tipp wie ich meine Elero Rolladen in den ioBroker bekomme? 

Vielen Dank schonmal im Voraus!

Natürlich bin ich bei einer Hilfe oder auch Erstellung eines Adapters für jegliche Spenden offen.(Hatdware etc..)

Viele Grüße

**Comment by steckenpferd** [comment]
s. hier:
https://github.com/ioBroker/AdapterRequests/issues/60

https://github.com/marc2016/ioBroker.elero-usb-transmitter

und hier:
https://github.com/ioBroker/AdapterRequests/issues/47

https://forum.iobroker.net/search?term=mediola&in=titles&matchWords=all&sortBy=timestamp&sortDirection=desc&showAs=posts

**Comment by mcm1957** [comment]
potential duplicate.
Leave it open until #47 or #60 is done and it can be determined whether this reqeust is fullfilled.

**Comment by mcm1957** [comment]
see #47 and #60 for further details.
If request is not fulfilled, please open a issue at those adapters if a solution with those adapters seems possible.
Otherwise please open a new request issue.
