### ISSUE TITLE
zwave2mqtt 

### ISSUE THREAD

**Issue by DieterKoblenz** [ioBroker/AdapterRequests#496]
**What kind of device or service you would like to see an adapter for?**
It's an opensource implementation of the zwave protocol (requires a zwave USB controller). It transmits all information to a MQTT broker, hence this is where ioBroker can pick it up.

**Is an official API including documentation is available?**
https://github.com/OpenZWave/Zwave2Mqtt

**Are other libraries for an integration available?**
Ideally in JavaScript/npm, but also other programming languages are interesting, add Links please

**Is this device already integrated in other Smart Home systems?**
Home Assistant

**Is this device already integrated in homebridge? Might the ham adapter together with the homebridge plugin be sufficient?**
Don't use homebridge, can't use homebridge.

**Additional context**
Perhaps the mqtt client is already enough, but I think from a plug & play perspective an auto detection would be beneficial. See also implementation for Tahoma device via mqtt.

After you created the issue vote for yourself in the first post of the issue using the "+1"/"Thumbs up" button

**Comment by Apollon77** [comment]
What exactly is the purpose that ioBroker should have that? We have two zwave adapters (one with openzwave and one with a pure js zwave implementation) to really have the values in iobroker and can control it directly. iobroker have amqtt client adapter to sccess mqtt servers like that ... So what exactly is the benefit?

**Comment by DieterKoblenz** [comment]
That's why I left additional context. Wasn't sure if there is a benefit, I agree there's already a way to set this up currently. Perhaps the question is broader and should be asked with regard to the mqtt client adapter, an automatic device recognition system could be beneficial in making ioBroker more accessible. Especially for those coming from other systems. 

I think this issue may be closed.
