### ISSUE TITLE
Speedport Pro Hybrid

### ISSUE THREAD

**Issue by DerAndy77** [ioBroker/AdapterRequests#497]
Ist es möglich einen Adapter für den Speedport Pro Hybrid bereitzustellen? 
Idealer Weise wie der Adapter für die Fritzbox, hilfreiche Funktionen wären z.B.:

 - Auslesen Stati DSL / LTE / Telefonie / WLAN
 - Restart Router
 - verbundene Geräte

Auf GitHub konnte ich ein Projekt finden, welches aber leider nicht für ioBroker ist:
https://github.com/florianprobst/ips-speedport/blob/master/README.md

Anscheinend gab es mal einen Ansatz für ioBroker, aber anscheinend nicht weiter vefolgt:
https://github.com/Sh1nto/ioBroker.speedport_hybrid

Wäre auch gern bereit zu testen, habe einen Speedport Hybrid Pro Router hier stehen...

Beste Grüße
Andy

**Comment by Solilord** [comment]
Hier ist noch ne php api. Die ist auch vorraussetzung für das o.a. Projekt bei Github
https://github.com/Stricted/speedport-hybrid-php-api/

**Comment by Backe03** [comment]
Ich stelle mich ebenfalls gerne für versuche etc. zur Verfügung.

**Comment by hacki11** [comment]
Ich hab für meinen Speedport w925v einen Adapter geschrieben und würde den um beliebige Modelle erweitern.
https://forum.iobroker.net/topic/43356/test-adapter-speedport-v0-0-x

Da ich keine anderen Router habe benötige ich eure Mithilfe, damit ich eine Erweiterung machen kann.
Ich benötige einen Wireshark Trace während ihr euch anmeldet und die "geheimen" Menüs durchsurft.

So geht das:
0) Router Passwort ändern, es könnte im Trace sichtbar sein oder evtl. wird es auch für die Entwicklung benötigt
1) Wireshark (https://www.wireshark.org/) starten und Aufzeichnung auf richtigem Interface beginnen
2) Cookies löschen oder Inkognito Modus verwenden
3) Speedport im Browser aufrufen und einloggen
4) Die geheimen Menüs aus https://telekomhilft.telekom.de/t5/Geraete-Zubehoer/Speedport-Router-Hidden-Menues/ta-p/3101743 oder https://www.onlinekosten.de/forum/showthread.php?t=145605 aufrufen und am besten alle Einträge anklicken und laden lassen.
5) Trace speichern und mit Passwort zippen
6) Mir zukommen lassen

**Comment by ldittmar81** [comment]
@Apollon77 can be closed. Its on latest

**Comment by CH1989** [comment]
Hallo @hacki11 
Ich wäre auch sehr an einem Adapter für den Speedport Pro Hybrid interessiert. 

Ich würde mich auch zum Testen anbieten 😉

**Comment by Apollon77** [comment]
@CH1989 Then you missed the most important thing ... "thumbs up on first post" ... else noone sees your interest

**Comment by ldittmar81** [comment]
> Hallo @hacki11 Ich wäre auch sehr an einem Adapter für den Speedport Pro Hybrid interessiert.
> 
> Ich würde mich auch zum Testen anbieten 😉

Ähh... der Adapter ist schon da. Das Issue hier wurde bereits geschlossen, weil es schon ein Adapter dafür gibt.

**Comment by CH1989** [comment]
> > Hallo @hacki11 Ich wäre auch sehr an einem Adapter für den Speedport Pro Hybrid interessiert.
> > Ich würde mich auch zum Testen anbieten 😉
> 
> Ähh... der Adapter ist schon da. Das Issue hier wurde bereits geschlossen, weil es schon ein Adapter dafür gibt.

Wo ist denn der Adapter?
Bzw. auf was verweist du?

**Comment by ldittmar81** [comment]
> > > Hallo @hacki11 Ich wäre auch sehr an einem Adapter für den Speedport Pro Hybrid interessiert.
> > > Ich würde mich auch zum Testen anbieten 😉
> > 
> > 
> > Ähh... der Adapter ist schon da. Das Issue hier wurde bereits geschlossen, weil es schon ein Adapter dafür gibt.
> 
> Wo ist denn der Adapter? Bzw. auf was verweist du?

Es ist noch nicht auf stable, aber bestimmt bald - https://github.com/hacki11/ioBroker.speedport

**Comment by CH1989** [comment]
> > > > Hallo @hacki11 Ich wäre auch sehr an einem Adapter für den Speedport Pro Hybrid interessiert.
> > > > Ich würde mich auch zum Testen anbieten 😉
> > > 
> > > 
> > > Ähh... der Adapter ist schon da. Das Issue hier wurde bereits geschlossen, weil es schon ein Adapter dafür gibt.
> > 
> > 
> > Wo ist denn der Adapter? Bzw. auf was verweist du?
> 
> Es ist noch nicht auf stable, aber bestimmt bald - https://github.com/hacki11/ioBroker.speedport

Da hast du recht. Allerdings ist der Adapter aktuell nur für den Speedport W 925V sowie den Speedport Smart 3.

NICHT für den Speedport Hybrid Pro…

**Comment by ldittmar81** [comment]
Ohh... ok. Maybe @hacki11 can add support for Hybrid Pro - https://github.com/hacki11/ioBroker.speedport/issues/65
