### ISSUE TITLE
SMSTools für SMS-Versand und Anrufe

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/AdapterRequests#5]
- SMSTools3 or direct USB stick communication?
- Adapter to send SMS or also maybe do calls
- ideally enhancement of other Networkbased Adapters to allow Fallbacks on errors (using messages)

Migrated from Trello with 2 votes

**Comment by BuZZy1337** [comment]
You assigned this to yourself. Are you actually working on this @Apollon77?
I planned to buy a Sim Card USB stick in the near future for similar purposes. Maybe we can develop this adapter together.. :smile:

**Comment by Apollon77** [comment]
I already have "smstools3" on Linux (a normal system deamon that works with files) and a USB stick. So one fast idea is to build Adapter on top of that. Good here is that we do not need to care about different sticks and such. Bad is this external dependency and only works on linux
http://smstools3.kekekasvi.com/

I also had a check on nodejs libraries to communicate with such USB sticks but most of them are not actively maintained :-( So this would mean a lot of basic library work as soon as it comes to different usb sticks.

What do you think?

**Comment by Apollon77** [comment]
@BuZZy1337 do not forget to vote :-)

**Comment by BuZZy1337** [comment]
Whoops.. Done.. :smiley:

**Comment by Apollon77** [comment]
@BuZZy1337 what you think about starting with an dapter based on "smstools3" because it would be "just" writing and reading files and monitoring a directory ... a good "easy" start in "writing" an adapter. We should prepare it modular so that we later on allow to also use a library for direct communication with the usb sticks.

In general for the "fallback idea" I had a talm with Bluefox and we would implement a generic "failback" option in "sendTo" in adapter.js and so be able to use this for all kinds of "sendTo" commands. But first we need the adapter itself

**Comment by Apollon77** [comment]
Maybe: https://github.com/zabsalahid/serialport-gsm ?!

**Comment by Apollon77** [comment]
I'm currently working together with the serialport-gsm guys to optimize their library a bit and bring the functionality (communicate with USB GSM models/Sticks) into an adapter soon. So prepare your Hardware and stay tuned :-)

**Comment by ukaeufeler** [comment]
Hi,
I would be very interested in an adapter for sms and calls. I should recognize when a call comes in or an SMS. I should also see which number. Is this adapter still planned?

**Comment by Apollon77** [comment]
yes still planned

**Comment by Azathoth88** [comment]
Maybe you can use the sms gateway from traccar. See: [](https://play.google.com/store/apps/details?id=org.traccar.gateway)
The gateway can be installed on an Android phone. An SMS can then be sent via POST / WGET.

**Comment by Apollon77** [comment]
My plan is to have something without other cloud dependencyies that also works when interget is gone :-) so an USB stick is the only choice :-)

**Comment by Azathoth88** [comment]
I tried to install a gatewayserver on usb stick on a vm. I left it due to driver issues.. Now i get it worked in iobroker with traccar app. The traccar gateway app isnt a cloud solution. The app makes your smartphone to a local sms gateway server.
And: its pretty easy to install. Everbody has an old smartphome in his closet and could use it for sending sms. I am happy about a working usb solution that also works under synology / docker.  Until then, I'll be using my old Galaxy s8.

**Comment by ldittmar81** [comment]
What is the current standing? Still in progress?

**Comment by Apollon77** [comment]
yes still on the list ... sooner then later planned

**Comment by Azathoth88** [comment]
@ldittmar81
In the meantime you can try the solution I used. 

1.) Install traccar sms gateway on android.
https://www.traccar.org/sms-gateway/

2.) exec('wget -N http://IP-of-Smartphone:8082 --post-data=\'{"to":"+4901......", "message": "Your Message"}\' --header "Authorization: code from traccar app"');

I use this API on my Synology NAS, ioBroker and to send sms from a wordpress-contact-formular.
It works great!

**Comment by Apollon77** [comment]
The goal of this adapter is to direxctly send out SMS using GSM USB sticks to allow communication if internet connection is broken!

**Comment by forelleblau** [comment]
Ok, unfortunately I haven't been here the last few days, so I had seen that something is planned  sooner than later. 
Because I was not happy with the tools I used until now, a created an adapter, based on serialport-gsm. So if anybody ist interested: [https://github.com/forelleblau/ioBroker.gsmsms](https://github.com/forelleblau/ioBroker.gsmsms)
It works fine with mit GSM-Stick.

sorry Apollon77 for passing on the right side.

**Comment by Apollon77** [comment]
All good, wanted to basically use the same library :-)) WIll have a look

**Comment by vaaarg** [comment]
i am very interested in calls, cause asterisk adapter is not maintained anymore

**Comment by Apollon77** [comment]
In fact adapter in general is available https://github.com/forelleblau/ioBroker.gsmsms and checked for repo currently. Calls are planned to be added there https://github.com/forelleblau/ioBroker.gsmsms

**Comment by mcm1957** [comment]
Adapter gsmsms is available at repository (latest).

Please report any problems or feature requests at the adapetr repository (https://github.com/klein0r/ioBroker.gira-iot)

@forelleblau Thanks for your work
