### ISSUE TITLE
evcc (controlling wallboxes by information of pv-inverter and power meter)

### ISSUE THREAD

**Issue by astrakid** [ioBroker/AdapterRequests#503]
**What kind of device or service you would like to see an adapter for?**
evcc (https://github.com/andig/evcc) is collecting information of inverters and power meters and controls your wallbox to load your car's battery with pv-energy only or not.

**Is an official API including documentation is available?**
https://github.com/andig/evcc#api

**Are other libraries for an integration available?**
see github

**Is this device already integrated in other Smart Home systems?**
no

**Is this device already integrated in homebridge? Might the ham adapter together with the homebridge plugin be sufficient?**
no

**Additional context**
the github-page is a good place to start

**Comment by astrakid** [comment]
I hopefully get a wallbe eco 2.0s within the next 6 weeks. would it help if i test things for you? or which kind of hardware is missing?

**Comment by EdExley** [comment]
Wouldn’t it make more sense to provide this function (PV production regulates EV charging) as script? All required data should be available already from existing adapters in IO Broker?

**Comment by astrakid** [comment]
could be done as well, but because evcc contains lots of logic inside it would make sense to simply use that.

**Comment by Newan** [comment]
I think the better idea is to implement this logic in an iobroker Charge / PV logic adapter?
What logic do you mean, can you explain it to me. For evcc is recommended a new vm or container, so I could save this .

**Comment by astrakid** [comment]
> What logic do you mean, can you explain it to me. For evcc is recommended a new vm or container, so I could save this .

evcc is only an executable and a config file. you don't need a vm or another container for this, just use it in your existing environment.

**Comment by Newan** [comment]
Evcc works with the mqtt Adapter. Make it sense to create a Single Adapter over Restful?

**Comment by Newan** [comment]
Under process: https://github.com/Newan/ioBroker.evcc

**Comment by mcm1957** [comment]
Adapter has been released
