### ISSUE TITLE
Rademacher Brigde

### ISSUE THREAD

**Issue by Homeworker11** [ioBroker/AdapterRequests#505]
Request for an Rademacher Start2Smart Bridge Adapter

Company Rademacher
Type Brigde
Artikel-Nr. / Item no.: 3400 00 19
Typ / Type: 9492
https://www.rademacher.de/shop/rollladen-sonnenschutz/fernbedienung/bridge

Regards

**Comment by Newan** [comment]
Ist es nicht das gleiche: https://www.iobroker.net/docu/index-259.htm?page_id=4933&lang=de ??

**Comment by Homeworker11** [comment]
Hallo

 

>>Ist es nicht das gleiche: https://www.iobroker.net/docu/index-259.htm?page_id=4933 <https://www.iobroker.net/docu/index-259.htm?page_id=4933&lang=de> &lang=de ??

Nein, dieser Adapter funktioniert nicht mit der Rademacher Bridge.

 

Aber dieser hier funktioniert.

 

 <https://github.com/homecineplexx/ioBroker.homepilot20/blob/master/README.md> ioBroker.homepilot20/README.md at master · homecineplexx/ioBroker.homepilot20 · GitHub

 

Der Adapter Request hat sich somit erledigt.

 

Mit freundlichen Grüßen

Klaus Kummer

 

 

 

 

Von: Newan ***@***.***> 
Gesendet: Sonntag, 21. März 2021 11:37
An: ioBroker/AdapterRequests ***@***.***>
Cc: Homeworker11 ***@***.***>; Author ***@***.***>
Betreff: Re: [ioBroker/AdapterRequests] Rademacher Brigde (#505)

 

Ist es nicht das gleiche: https://www.iobroker.net/docu/index-259.htm?page_id=4933 <https://www.iobroker.net/docu/index-259.htm?page_id=4933&lang=de> &lang=de ??

**Comment by DutchmanNL** [comment]
https://github.com/homecineplexx/ioBroker.homepilot20/blob/master/README.md
