### ISSUE TITLE
Microsoft ToDo crud

### ISSUE THREAD

**Issue by rotzaff** [ioBroker/AdapterRequests#509]
Ich nutze gerne die MS ToDo-Liste und weise da auch gerne mal meiner Frau die Aufgaben zu XD (umgedreht natürlich auch).

Jetzt wäre es natürlich ziemlich cool, könnte man die Aufgaben oder bestimmte ToDo-Listen in der Vis einbinden. 

Genial wäre, wenn man ähnlich der Alexa-Einkaufsliste / Todo-Liste Einträge hinzufügen oder löschen könnte.

**Comment by Apollon77** [comment]
Und auch Genial wäre wenn die Fragen aus dem Issue Template beachtet worden wären. Links? Libraries? ... :-(

**Comment by rotzaff** [comment]
> Und auch Genial wäre wenn die Fragen aus dem Issue Template beachtet worden wären. Links? Libraries? ... :-(

Ich habe leider nur diese Info hier vorliegen gehabt: (https://forum.iobroker.net/topic/12804/adapter-anfragen-mehr-aktivit%C3%A4t-erforderlich

Link zu Microsoft Todo: https://todo.microsoft.com/tasks/de-de/ 
API MS Todo: https://docs.microsoft.com/de-de/graph/todo-concept-overview 
https://docs.microsoft.com/de-de/previous-versions/office/office-365-api/api/version-2.0/task-rest-operations

Libraries?: Keine gefunden. 

Ich vermute stark, dass es nur über den kommerziellen weg bei MS geht.

**Comment by rotzaff** [comment]
Dublikat: https://github.com/ioBroker/AdapterRequests/issues/340
