### ISSUE TITLE
Solarlog Adapter

### ISSUE THREAD

**Issue by JackWolfskin42** [ioBroker/AdapterRequests#51]
Es wäre schön, wenn neben den bereits unterstützten PV Systemen, das in Deutschland besonders verbreitete Solarlog nativ per Adapter unterstützt würde :-)
Daten können z.b per JSON abgefragt werden - siehe Seite 313ff
[https://www.solar-log.com/manuals/manuals/en_GB/SolarLog_Manual_EN.pdf](https://www.solar-log.com/manuals/manuals/en_GB/SolarLog_Manual_EN.pdf)

**Comment by g3orgs** [comment]
Ja das wäre ne tolle Sache.

**Comment by forelleblau** [comment]
Ich habe die Datenabfrage für meinen Solarlog ab Homematic mit verschiedenen .sh Files realisiert. Kann noch einige Daten mehr abfragen als in der Anleitung angegeben. Diese Informationen könnte ich zur Verfügung stellen, wie man IO-Broker Adapter erstellt weiss ich aber nicht.

**Comment by forelleblau** [comment]
Habs trotzdem versucht. Ist copy&past und trial und error. Bei mir kommen die Werte an.

[https://github.com/forelleblau/ioBroker.solarlog](https://github.com/forelleblau/ioBroker.solarlog)

Tipps, Kommentare und Verbesserungsvorschläge sind willkommen

**Comment by JackWolfskin42** [comment]
Aktuell liefert der Adapter bei mir (trotz eingetragener IP) folgenden Fehler: 
[START] No IP-address set

**Comment by forelleblau** [comment]
Hallo 

 

Danke fürs Testen und für die Rückmeldung

 

Kannst du mir sagen, ob die IP im «native» Reiter bei den Eigenschaften des Instance-Objekts eingetragen ist?

 

 

 

 



 

 

Beste Grüsse

 

Marcel Adam

Von: JackWolfskin42 <notifications@github.com> 
Gesendet: Mittwoch, 7. November 2018 16:40
An: ioBroker/AdapterRequests <AdapterRequests@noreply.github.com>
Cc: forelleblau <marceladam@gmx.ch>; Manual <manual@noreply.github.com>
Betreff: Re: [ioBroker/AdapterRequests] Solarlog Adapter (#51)

 

Aktuell liefert der Adapter bei mir (trotz eingetragener IP) folgenden Fehler:
[START] No IP-address set

**Comment by JackWolfskin42** [comment]
Leider sagt mir das als Nicht-Entwickler gar nix?
"«native» Reiter bei den Eigenschaften des Instance-Objekts"

**Comment by forelleblau** [comment]
Hallo JackW

 

Habe eben eine möglich Fehlerquelle eliminiert. Vielleicht klappt es jetzt wenn du den Adapter neu installierst.

 

Herzlichen Dank im Voraus für den Test.

 

Herzliche Grüsse

 

 

Von: JackWolfskin42 <notifications@github.com> 
Gesendet: Mittwoch, 7. November 2018 21:46
An: ioBroker/AdapterRequests <AdapterRequests@noreply.github.com>
Cc: forelleblau <marceladam@gmx.ch>; Manual <manual@noreply.github.com>
Betreff: Re: [ioBroker/AdapterRequests] Solarlog Adapter (#51)

 

Leider sagt mir das als Nicht-Entwickler gar nix?
"«native» Reiter bei den Eigenschaften des Instance-Objekts"

**Comment by JackWolfskin42** [comment]
Danke! Er verbindet sich jetzt und liefert Daten :-)
Werde dann mal ein bisschen testen....

**Comment by JackWolfskin42** [comment]
Das sind bisher aber hauptsächlich die "offiziellen"  Werte (801:170:100..116) . Es gibt da ja noch deutlich mehr als diese Werte z.b. aktueller Status sowie weitere WR und Unterverbraucher etc.  
[https://www.photovoltaikforum.com/sds-allgemein-ueber-solar-log-f38/tagesdaten-von-soalrlog-aufrufen-aber-wie--t59417-s20.html
Könntest du evtl. auch diese weiteren Daten abrufen?

**Comment by Apollon77** [comment]
Bissl Code-Review-Kommentare:
* https://github.com/Apollon77/ioBroker.solarlog/blob/master/main.js#L99 sollte unnötig sein
* Bei dem HTTP kram und JSON parse fehlt Fehlerhandling ... Da könnte einiges schieff gehen was ggf direkt den adapter crasht. WIll man vllt nicht
* besser setTimeout nutzen und nach dem Ende der Kommunikation neu setzen als setintervall. Wenn mal eine Anfrage länger dauert fängt es sonst an parellel immer mehr requersts zu machen
* wenn du on objectChange/statechange/message nicht brauchst dann wirf es raus

**Comment by forelleblau** [comment]
Danke für die Feedbacks.
Die weiteren Werte sind bekannt und bereits in Planung.
Danke für den Code-Review. Werde gerne versuchen, das zu berücksichtigen.

**Comment by forelleblau** [comment]
Version 0.0.2 aufgeschaltet: Berücksichtigung der Code-Review Kommentare von Appollon.

**Comment by forelleblau** [comment]
Version 0.0.3 aufgeschaltet! Neu mit Abruf der Werte aller WR und Unterverbraucher wie von @JackWolfskin42 gewünscht. Auf Hinweis von @Apollon77 auch Travis-CI tested.

[https://github.com/forelleblau/ioBroker.solarlog](url)

**Comment by Apollon77** [comment]
Ist es auf schon NPM bzw im Repo? Wenn nein wäre es cool

**Comment by forelleblau** [comment]
Nein, wär mir zumindest nicht bewusst... ich werd mich mal schlaumachen.

**Comment by mhoerche** [comment]
Bei mir geht der Adapter nur auf "gelb" und aktualisiert sich nicht. Wenn ich "neu lade" kommen die aktuellen Werte aber danach kommt nichts aktuelles mehr :-(. 
Hat da jemand eine Idee?

**Comment by Apollon77** [comment]
Gelb ist es wenn es einen info.connection state gibt der aber auf false steht. Also entweder auf true setzen oder nicht nutzen :-)

**Comment by forelleblau** [comment]
Vielen Dank. Mein Plan wär „nicht nutzen“, hatte einfach noch nicht rausgefunden wie. 
Jetzt hab ich den Ansatz, danke.
