### ISSUE TITLE
Govee Home Adapter

### ISSUE THREAD

**Issue by Haenk93** [ioBroker/AdapterRequests#510]
Hallo,

ich suche einen Adapter für meine Govee LEDs

Es gibt dazu bereits einen Homebridge Adapter aber ich bekomme diesen einfach nicht zum laufen.
Link: https://github.com/bwp91/homebridge-govee

API wird von Govee über die APP bereit gestellt

**Comment by Grothesk242** [comment]
https://github.com/nbuenger/ioBroker.govee
mal angeschaut?

**Comment by DEV2DEV-DE** [comment]
> https://github.com/nbuenger/ioBroker.govee mal angeschaut?

Der Adapter funktioniert, auch wenn er sich bei der Installation lange geweigert hat.
Nachteil: Bei Govee läuft alles ausschließlich über die Cloud und das Abfrageintervall ist deutlich eingeschränkt (10 Aufrufe pro Minute).
https://govee-public.s3.amazonaws.com/developer-docs/GoveeDeveloperAPIReference.pdf

**Comment by mcm1957** [comment]
Could be solved by

https://github.com/TA2k/ioBroker.govee-app

https://github.com/ioBroker/ioBroker.repositories/pull/2243

**Comment by mcm1957** [comment]
@Haenk93
@DEV2DEV-DE 

As repository addition of goovee-app has been canceled, could you please check whether adapter

**https://github.com/boergegrunicke/ioBroker.govee-local**

satisfies your needs?
