### ISSUE TITLE
Schwimmbadtechnik

### ISSUE THREAD

**Issue by joachimknape** [ioBroker/AdapterRequests#513]
Hat sich schon jemand mit Schwimmbadtechnik bzw automatischen Dosieranlagen für Chlor und pHWert beschäftigt? Wenn man schon so einen Raspberry Rechenknecht im Haus hat, kann man den doch auch sicher mit ioBroker zum messen und dosieren im hauseigenen Pool verwenden..

**Comment by Apollon77** [comment]
hast Du konkrete Ideen bzw Produkte im Sinn  und Details dazu?

**Comment by joachimknape** [comment]
klar.. ggg
das komplette projekt würde so aussehen - ein internetanbieter einer komplettlösung:
https://www.poolsana.de/automatische-poolsana-mess-und-dosieranlage?
https://pooldoktor.at/dosieranlage-pool.html

gclid=CjwKCAiAnvj9BRA4EiwAuUMDf_w4Oq_4k1p1B2c4I2xvF7-YCFFsMROaR6Lncaz151i_L21f237hKBoCwRAQAvD_BwE

das angebot greift aber mächtig in den geldbeutel.
ich dachte daran, die pumpen und messensoren einzeln zu nehmen, und den rest durch meinen raspi machen zu lassen:
https://gastrotiger.de/shop/dosiergeraet-microdos-frequenzregelung-4l/h-230vac-361803?campaignid=1410154787&adgroupid=53982763325&targetid=pla-297631419503&network=u&gclid=CjwKCAiAnvj9BRA4EiwAuUMDf1bProDATdWDv86pWsn9FxR96iKgm-GX7M53yYCOB28Qw3d0RaXCDRoCm38QAvD_BwE

http://www.pooldoktor.net/shop/ph-sonde-/-elektrode-0-14-ph
Sonden gibbet jeweils für chlor und pHWert.

und das alles will ich irgendwie zusammenknüppern...

**Comment by flapman** [comment]
Ich beschreib mal, wie ich es gelöst habe. Als Hardware einen seperaten Rasp mit dem Atlas scientific board als HAT. Dazu die drei circuits Chlor, Ph und Temperatur aufgesteckt. Das ganze mit der Software von 100prznt versehen (EZOGateway). Über den Simple REST Adapter kommen die Werte rein. Theoretisch geht es auch mit der original Software von Atlas und MQTT, hab ich aber nicht zum laufen bekommen mangels MQTT Erfahrungen. Einmal im Broker drin, wird die Salzanlage von Intex eingeschaltet über den Shelly 1 da nur ein Relais gebraucht wird, um die Anlage aus dem Schlaf zu holen. Warum Shelly? weil ich so auch zwei Temperaturfühler für das Wasser günstig einbinden konnte.
Für PH oder auch flüssiges Chlor kann man ja simple Dosierpumpe besorgen und einen Schaltaktor über Deconz oder WIFI einbinden. Dazu halt noch die ganzen Regeln erstellen mit den entsprechenden Datenpunkte.
Kosten:
- Rasp 3B 35€
- Shelly 1 ca.15€
- [Atlas Board](https://www.whiteboxes.ch/) mit allem drum und dran (Carrier Board Tentacle T3, Circuits und Kalibrierlösungen) 295€
- [Intex Salzanlage](https://www.idealo.de/preisvergleich/OffersOfProduct/6035777_-krystal-clear-salzwassersystem-26670-intex-pools.html) 150€
- Rohrzubehör für die Sonden ( noch nicht gekauft, schätze aber auch so um die 100€)

Auch nicht günstig, aber günstiger als die Fertiglösungen, eigene Kontrolle und smart.
[Passender Thread im Forum](https://forum.iobroker.net/topic/33990/ezogateway-watermonitoring)

**Comment by SoerenKaiser99** [comment]
ich hatte eine Ph Messung mit Wemos und mqtt als Grundlage beizusteuern. Müsste man nur auf i2C ändern und ein Erweiterungsboard für Analoge eingänge verwenden.. Hätte ich auch da zum testen... Aufbau und Grundlagen hier:

http://tryit.familiekaiser.nrw/2021/05/11/phsonde/

**Comment by Apollon77** [comment]
@SoerenKaiser99 Cool, kannst Du noch Links zur Sonde einfügen? Ich überlege gerade auch sowas :-)

**Comment by Apollon77** [comment]
BTW: Für den PH803W (PH und Redox) gibts jetzt einen Adapter

**Comment by Apollon77** [comment]
Und warum PH803W und nicht selbst bauen (weil ich diese Entscheidung auch hatte - und ja meine persönliche Meinung): Zwei Sonden die nacheinander im gleichen Wasser so anbinden das Sie Galvanisch getrennt sind und dich ggf so die Messergebnisse nicht gegenseitig verfälschen und der Zeitaufwand steht den 90 EUR für das PH803W Gerät nicht im Verhältnis :-)

**Comment by Apollon77** [comment]
Frage wäre ob man damit den AdapterRequest schliessen kann?  @joachimknape ??

**Comment by sezme2022** [comment]
Ich habe das mit der ProconIP Steuerung und dem zugehörigen Adapter realisiert. Läuft hervorragend. https://www.pooldigital.de/shop/poolsteuerungen/procon.ip/35/procon.ip-webbasierte-poolsteuerung-/-dosieranlage

**Comment by mcm1957** [comment]
https://github.com/ioBroker/ioBroker.repositories/pull/2536
https://github.com/ylabonte/ioBroker.procon-ip

Adapter released

Bei Bedarf an einer Anbindung anderer Anlagen bitte ein neues Issue erstellen.
