### ISSUE TITLE
Easee Adapter for Easee Home / Easee Charge Wallbox

### ISSUE THREAD

**Issue by lastoks** [ioBroker/AdapterRequests#514]
**What kind of device or service you would like to see an adapter for?**
Easee Home / Easee Charge Wallbox
https://easee-international.com

**Is an official API including documentation is available?**
Yes
https://api.easee.cloud/index.html

**Are other libraries for an integration available?**
https://pypi.org/project/easee/
https://github.com/fondberg/pyeasee

**Is this device already integrated in other Smart Home systems?**
There is an integration in solar manager.
https://www.solarmanager.ch/

**Is this device already integrated in homebridge? Might the ham adapter together with the homebridge plugin be sufficient?**
no

**Additional context**
https://forum.iobroker.net/topic/38437/easee-wallbox-mit-iobroker
https://community.openhab.org/t/easee-ev-charger-integration/107095
https://community.home-assistant.io/t/easee-ev-charging-station/186474

**Comment by andispammonyer** [comment]
No progress? Alteratives available?

**Comment by andispammonyer** [comment]
Who need the HW for the implementation? I live near Heilbronn/Stuttgart

**Comment by andispammonyer** [comment]
I requested support from easee directly.

Please vote for this idea to integrate easee home in ioBroker

https://easee.upvoty.com/b/ideas/smart-home-iobroker-integration

**Comment by Newan** [comment]
Please test: https://github.com/Newan/ioBroker.easee

**Comment by wupdich** [comment]
> Please test: https://github.com/Newan/ioBroker.easee

Thank you very much @Newan.❤️ I will be definitely trying it out in the next weeks.

**Comment by Newan** [comment]
Please close, adapter is done

**Comment by DutchmanNL** [comment]
> Please close, adapter is done

great. thank you !
https://github.com/ioBroker/ioBroker.repositories/pull/1136
