### ISSUE TITLE
new Hoover Washing machine series(new hOn; Candy and Haier devices compatible)

### ISSUE THREAD

**Issue by Solilord** [ioBroker/AdapterRequests#515]
It's an Wi-Fi + Bluetooth enabled Washing Machine from the brand new H-WASH 500 Series.

You can start various washing cycles, check the filling status of the detergent and softener container, See remaining time, energy consumption and such things.

I don't know yet about an API. It uses the (also new) hOn App from Haier (Haier group owns Candy and Hoover now) 

The Machine gets connected as a client in your home 2.4GHz Wi-Fi.
The WiFi setup is made with the app and a QR code or alt. a alphanumeric String printed on a sticker.

Due to the new series (and the new System (hOn App)) there is no other integrations yet I know from.

Especially, my WashingMachine is the HWPDQ410AMBCR/-S.

I can provide you with more information. 
Due to the meantime I try to catch some traffic from an to the machine.

Yours Florian! :)

Meinetwegen auch auf Deutsch ^^

**Comment by cholawo** [comment]
I've got a Hover H-Wash 500 too.   I had a little look into where the hOn app is getting data from and it looks pretty complex to me.    I see that the login page is going to salesforce at https://he-accounts.force.com/SmartHome/s/login/ and worse still there are some authorization redirects going on eg this kind of page request
`
https://he-accounts.force.com/SmartHome/setup/secur/RemoteAccessAuthorizationPage.apexp?source=CAAAAX.... really really long token name ...EeRoGf4YBMpTuYFlXOtMmgvsjEDYQyJ0LBQp4nE3Qqr5M8FgXsiyer5Kzxw5zHiVErRV3_qCmCy--cpxx_w%3D&display=touch
`

I couldn't successfully login when I was trying to sniff packets using an android device with a man-in-the-middle attack.   It seemed to spit me back at the login page, and I saw an error about it not liking a certificate (sorry can't remember the specific error message).   I think it would need someone much cleverer than I having one of these models!

**Comment by Miloune** [comment]
It's seem to use Amazon MQTT with a certificate stored in the washing machine

**Comment by TA2k** [comment]
I can have look but is this brand present in germany?

**Comment by fishbone222** [comment]
Absolutely. We have a Hoover HDPD696AMBC our own.
The brand belongs to Candy Hoover Group Srl./Haier.
I was also considering already to replace the ESP to make the Machine comunicate with my servers but had no time for that yet.
If someone wants information about the machine or access to the esp to reverse engeneer the connection feel free to ask me.

**Comment by TA2k** [comment]
please contact me via iobroker forum to provide app credentials
https://forum.iobroker.net/user/tombox

**Comment by maury77** [comment]
Any idea for this Integration?

**Comment by TA2k** [comment]
Still needing credentials for integration

**Comment by TA2k** [comment]
https://forum.iobroker.net/topic/55667/test-adapter-hoover-hon

**Comment by mcm1957** [comment]
Adapter : https://github.com/TA2k/ioBroker.hoover

Adapter has been released (https://github.com/ioBroker/ioBroker.repositories/pull/2125).
Please report any issues at adapter repository.
