### ISSUE TITLE
Trivum Multiroom system

### ISSUE THREAD

**Issue by Chrisham** [ioBroker/AdapterRequests#518]
I am intending to install a multiroom system, favorite is Trivum:
https://www.trivum.de/produkte/soundsysteme/reg-line/58/rp341?c=413
But the pre-requisite is that I can integrate this into IOBroker server and to control it via HAPPanel Visu.

**Is an official API including documentation is available?**
Not yet known, inquiry to supplier is raised.

**Are other libraries for an integration available?**
Not yet known.

**Is this device already integrated in other Smart Home systems?**
Yes, into KNX.

**Is this device already integrated in homebridge? Might the ham adapter together with the homebridge plugin be sufficient?**
Not known.

**Additional context**
Should also be operatable by the HABPanel Visu also integrated into IOBroker.

**Comment by TheBam1990** [comment]
I have this system in mind to install myself.  So far there has been the possibility of integrating the system via node-red and thus also in iobroker.  An API can be viewed on the manufacturer's page.

https://www.trivum-shop.de/support/docs/de/mcenter-api.html

**Comment by Chrisham** [comment]
> I have this system in mind to install myself. So far there has been the possibility of integrating the system via node-red and thus also in iobroker. An API can be viewed on the manufacturer's page.
> 
> https://www.trivum-shop.de/support/docs/de/mcenter-api.html

thanks for this info. do you know if someone is already working on an IOBroker-Adapter for this system?

**Comment by TheBam1990** [comment]
As far as I know not yet. Do you want to go to it?

**Comment by TheBam1990** [comment]
in progress

**Comment by TheBam1990** [comment]
First Version is available here:
https://github.com/TheBam1990/ioBroker.trivum

https://forum.iobroker.net/topic/44235/trivum-multiroom-system-adapter-v-0-0-1

**Comment by ldittmar81** [comment]
@Apollon77 can be closed.. its stable
