### ISSUE TITLE
Wemo (Insight) Switch Wlan Steckdosen

### ISSUE THREAD

**Issue by JackWolfskin42** [ioBroker/AdapterRequests#52]
SInd wohl per UPNP ansprechbar:
https://github.com/ericblue/Perl-Belkin-WeMo-API

**Comment by JackWolfskin42** [comment]
Wenn es nur um fehlende HW für die Entwicklung geht, die spende ich gerne  -
also einen Raspi + Belkin Steckdose ;)

**Comment by Apollon77** [comment]
Homebridge modules exist: homebridge-platform-wemo as example.

Please check if the new ioBroker.ham Adapter can help here: see https://forum.iobroker.net/viewtopic.php?f=36&t=14972

**Comment by Apollon77** [comment]
Closed because of  Homebridge?

**Comment by JackWolfskin42** [comment]
Ok, how about a Homebridge-Plugins HAM-Plugin-Adapter for WeMo ;-)

**Comment by GermanBluefox** [comment]
https://github.com/ioBroker/ioBroker.ham-wemo

ср, 20 июн. 2018 г., 22:17 JackWolfskin42 <notifications@github.com>:

**Comment by Apollon77** [comment]
@JackWolfskin42 Please try the ioBroker.ham-wemo ... is it enoigh or are there pitfalls, missing features or strange things that would better need an own Adapter?

**Comment by Apollon77** [comment]
Can you open UI glitch as issue with adapter please ? Then I close here and we release the ham-adapter :-)

**Comment by Apollon77** [comment]
iobroker.ham-wemo ist jetzt (also dann ab morgen früh) mit v0.2.1 auf npm und im latest Repo
