### ISSUE TITLE
Wenn - Dann Logik

### ISSUE THREAD

**Issue by AxelHoss** [ioBroker/AdapterRequests#521]
Guten Tag,

 

wäre es möglich, einen Adapter zu erstellen, welcher auf dem Wenn - Dann - Prinzip basiert?

 

Ein paar einfache Beispiele:

Wenn Lux größer als Wert X - dann Jalousie A auf 100% für X Minuten.

Wenn Lux kleiner als Wert X - dann Licht auf true bis Lux größer als Wert X

Wenn Temperatur unter Wert X - dann Heizungsaktor auf true

 

Die Angabe der Zeit sollte optional sein.

 

Etwas aufwendiger wird es wenn wir mehrere Vorraussetzungen haben:

Wenn Alarmanlage ein und Bewegung erkannt (Bewegungsmelder geht auf true) - dann setze Sirene auf true für x Sekunden

Wenn Garagentor offen und X Sekunden gehen vorbei - dann Whatsapp mit Nachricht raus.

 

Das könnte man dann auch mit dem Email -und Telegram/Whatsapp Adapter koppeln:

Wenn Terrassentür auf und X Sekunden vergehen - dann Nachricht per Telegram

Wenn Fenster A offen und Temperatur unter Wert X - dann Nachricht per Telegram

 

Mit einem Adapter könnte man das auch einfach in die VIS integrieren. Z. B. Regel für Garagentorbenachrichtigung ein/aus

 

Mir ist bewusst, dass dies alles auch mit Scripte oder Blockly funktioniert.

Allerdings wäre es sicherlich eine große Zeitersparnis, wenn man von beiden wenig/keine Ahnung hat.

Bei vielen Smarthome-Herstellern kann man solche Logiken schon in der App erstellen.

Ich denke das hier sehr viel Potential liegt.

Oft lese ich in den Foren, dass genau diese Funktion leider bei den freien Smarthomes fehlt. Das schreckt viele Leute ab, sich mit sowas zu beschäftigen.

 

 

Vielen Dank für eure Hilfe.

Grüße

**Comment by Apollon77** [comment]
Das steht schon af der Planungliste für den JavaScript Adapter ... ist nur ein grösseres Zeitliches Themen und bedarf einer ausgeklügelten Oberfläche.

**Comment by patrickbs96** [comment]
Ich habe es meinerseits mit einem Skript umgesetzt, das parametrierbar ist. Dabei wird auf States reagiert und wenn hinterlegte Bedingungen erfüllt sind, wird eine Aktion/State gesetzt. 
Zusätzlich verarbeite ich so auch meine Alexa-Routinen. Das wiederum bedeutet, dass die Alexa-Routinen selbst entweder vollständig leer sind oder nur eine Bestätigung rückmelden und die eigentlichen Verarbeitungen alle im Skript ablaufen. So besteht auch die Möglichkeit, bestimmte Routinen nur mit bestimmten Echos zu verknüpfen oder Bedingungen an die Ausführung zu hängen.

Die Prüfungen sind mit AND, OR, XOR möglich und Verschachtelungen können ebenfalls eingebaut werden.

Da ich das Skript immer nur soweit erweitere wie gerade meine Anforderungen sind, sind folgende Aktionen aktuell möglich:
- setState
- setState Echo
- sendMessage Telegram
- Adapter starten/stoppen
- Skript starten/stoppen
- Log-Ausgaben
- Timeouts
- Hue Lampen steuern

Ein Beispiel für die Routine "Gute Nacht":
```javascript
'Gute_Nacht' : {check: {1: checkModeActive}, checkSerials: ECHOS_SLEEPING_AREA, echo: ECHO_SLEEPINGROOM, tasks: [
	{debug: 'Gute Nacht...'},
	{echo: '.Player.volume', value: 1},
	{id: STATE_AUTOMATION, value: MODE_NIGHT},
	{wait: 10 * MS_PER_SECOND},
	{lightsHue: {name: 'Schlafzimmer_Decke', command: '{"on": false, "transitiontime":1500}'}},
	{wait: 20 * MS_PER_MINUTE},
	{echo: '.Player.controlPause', value: true}
]}
```
Oder für die Einschaltung von Weihnachtsbeleuchtung, wenn die Sonne untergegangen ist: 
```javascript
'javascript.0.MyDevices.System.Sonnenstand.Elevation' : {name: 'Sonnenstand', change: 'ne', tasks: [
	// Twinkly-Balkon
	{id: 'twinkly.0.Balkon.on', value: true, check: {
		1: {le: -2},
		2: {id: STATE_AUTOMATION, ne: MODE_NIGHT},
		3: {timeRange: [{start:'16:00', end:'23:59'},
					 {start:'00:00', end:'01:59', days: '6,7'}], eq: true}, 
		4: {id: 'twinkly.0.Balkon.on', eq: false}}},
	{id: 'twinkly.0.Balkon.on', value: false,   check: {
		1: {id: 'twinkly.0.Balkon.on', eq: true},
		OR: {
			1: {gt: -2}, 
			2: {id: STATE_AUTOMATION, eq: MODE_NIGHT},
			3: {timeRange: [{start:'16:00', end:'23:59'},
						 {start:'00:00', end:'01:59', days: '5-6'}], eq: false}}}}
]}
```

**Comment by MMeinhardt1** [comment]
@AxelHoss 
Viele von Dir beschriebene Dinge sollten sich mit dem SmartControl Adapter realisieren lassen, schau Dir den einfach mal an. Gibt im Forum auch nen großen Thread dazu.

**Comment by AxelHoss** [comment]
> @AxelHoss
> Viele von Dir beschriebene Dinge sollten sich mit dem SmartControl Adapter realisieren lassen, schau Dir den einfach mal an. Gibt im Forum auch nen großen Thread dazu.

Hallo MMeinhardt1, habe ich bereits. Finde den Adapter völlig unübersichtlich.

**Comment by MMeinhardt1** [comment]
@AxelHoss das ist sehr schade für Dich.

**Comment by TheBam1990** [comment]
Gibt jetzt eine Erweiterung für den JavaScript Adapter in der neuen Version ist der drin. Es heißt Rules probier das mal aus ob es das ist was du brauchst dann könnte man den Beitrag schließen

**Comment by AxelHoss** [comment]
Vielen Dank. Schau ich mir gleich an
