### ISSUE TITLE
Stihl / Viking iMow Mähroboter Adapter

### ISSUE THREAD

**Issue by meistermolli** [ioBroker/AdapterRequests#528]
ein Stihl (früher Viking) iMow Mähroboter hat eine API und APP und kann über ein Innogy Smart Home angelernt werden.
evtl ist es auch möglich ihn in io Broker zu bekommen?

Das wäre sehr fein.

Danke und Gruß

**Comment by Apollon77** [comment]
Links zur API? Links zum Geröt? SChade das du das Template rausgelöscht hast da waren alle Fragen drin

**Comment by meistermolli** [comment]
Hallo,
leider kann ich keinen link zu einer API finden. 
Bisher war nur die Integration in Innogy Möglich und als Alexa Skill.

[https://support.stihl.com/de-de/knowledgeArticlesDetails/?knowledgeArticleId=KA-01183](url)

Skill:
[https://www.amazon.de/STIHL-Tirol-GmbH-iMow/dp/B07Y895L69](url)

Ich weiß nicht ob und wie man das als eigenen Adapter anlegen kann, daher frage ich ja hier nach.

Wenn das nicht als eigener Adapter geht werde ich es über den Alexa Skill versuchen. Obwohl wir nichts mit Alexa oder generell Amazon machen. 

Danke und Gruß

**Comment by ninja-warrior** [comment]
Push. 😉

**Comment by Apollon77** [comment]
Warum pushst Du etwas was Du nicht im ersten Post mit einem Thumbs-up versiehst?

**Comment by ninja-warrior** [comment]
Der Daumen wurde ergänzt. Würde mich sehr schön über eine Integration in IOBroker freuen.

**Comment by tschuberth** [comment]
Wäre sehr cool wenn da jemand was bauen könnte....die Original-App ist grauenvoll.....

**Comment by Maxim-7777** [comment]
Wünsche mir auch Gene ein Adapter ☺️

**Comment by martinkuck** [comment]
Hallo!
Ich hab das hier gefunden für Home Assistant, kann da jemand was mit anfangen?
https://github.com/ChrisHaPunkt/ha-stihl-imow

**Comment by ninja-warrior** [comment]
Interessanter ist wohl die WebAPI des selben Entwicklers:

https://github.com/ChrisHaPunkt/stihl-imow-webapi

**Comment by meistermolli** [comment]
bin zu alternativer Plattform umgestiegen.

**Comment by Maxim-7777** [comment]
Welche?? Wenn ich fragen darf??

**Comment by Apollon77** [comment]
Naja, es sind inzweischen 9 User die sich das wünschen also würde ich den Request gern offen lassen.

**Comment by meistermolli** [comment]
> 

homeassistant deckt sich eher mit meinem Anwendungsfall und meinem Verständnis. Zudem bessere Übereinstimmung mit den von mir genutzten geraten.

**Comment by TA2k** [comment]
Wenn jemand zugangsdaten hat dann kann ich mir das schnell anschauen
Einfach im Forum anschreiben
https://forum.iobroker.net/user/tombox

**Comment by meistermolli** [comment]
@TA2k das hilft vielleicht auch. Bei mir funktioniert es im Homeassistant. Vielleicht kannst du dir was abgucken.

https://github.com/ChrisHaPunkt/ha-stihl-imow

**Comment by Wxjacker** [comment]
Es wäre schon einen Adapter für ioBroker zu haben. Der IMOW sendet viele Signale die man gut weiter verarbeiten könnte.

**Comment by TA2k** [comment]
Wenn jemand zugangsdaten hat kann ich es machen

**Comment by Wxjacker** [comment]
Hallo,

 

ich freue mich dass du dich dem Problem mit einem Adapter annehmen willst. Teile dir meine Anmelde-Daten mit.

Anbei habe ich noch Links hinzugefügt, die ich im Netz gefunden habe. Leier komme ich mit den Python Anweisungen nicht weiter.

 

 

 

https://app.imow.stihl.com/#/imows/46421/device      IMOW                User:                  ***@***.*** ***@***.***> 

                                                                                                                            Passwort:          ***@***.*** ***@***.***> 

https://home.livisi.de                                                          Innogy / Livisi

                                                                                                                            User:                  Wolfi

                                                                                                                            Passwort:          ***@***.*** ***@***.***> 

                            Unter Livisi gibt es nur unter Auswertungen brachbare Informationen, die man für das Öffnen und Schließen einer Garage verwenden könnte. 

Man bräuchte das Start-Signal, wenn er aus der Docking-Station fahren will.                                  

 

https://chrishapunkt.github.io/stihl-imow-webapi/imow/api/index.html#imow.api.IMowApi.fetch_messages              API Dokumentation

 

https://libraries.io/pypi/imow-webapi                                           pip install imow-webapi

https://chrishapunkt.github.io/stihl-imow-webapi/imow/

https://github.com/chrishapunkt/ha-stihl-imow

https://pypi.org/project/imow-webapi/                                         imow WebApi

https://packagegalaxy.com/python/imow-webapi

 

Vielen Dank im Voraus für deine Bemühungen.

 

 

Viele Grüße

Wolfgang Jackermayer

 

Mobil:   0152 22665965

 

 

 

Von: TA2k ***@***.***> 
Gesendet: Donnerstag, 16. Juni 2022 10:28
An: ioBroker/AdapterRequests ***@***.***>
Cc: Wxjacker ***@***.***>; Comment ***@***.***>
Betreff: Re: [ioBroker/AdapterRequests] Stihl / Viking iMow Mähroboter Adapter (#528)

 

Wenn jemand zugangsdaten hat kann ich es machen

**Comment by TA2k** [comment]
Ich habe mal schnell was gebaut bitte testen ob es geht
https://forum.iobroker.net/topic/55747/test-adapter-stihl-viking-imow
