### ISSUE TITLE
Tasmota update

### ISSUE THREAD

**Issue by Dragon0501** [ioBroker/AdapterRequests#529]
I want to update my tasmota devices with the newest tasmota. At the moment I have to make it by opening every device. There are so many ways to do that for example Tasmota device Manager, TasmoAdmin, or the update script. TDm just works if you don't use the sonoff adapter, TasmoAdmin is impossible for me to install next to the Broker to the Pi and the script isn't working, tells just failures.

Hope that can be solved easily by an adapter. Just install, use the devices and the infos of the Sonoff adapter and a big Button with Update all... That would be a dream.....

**Comment by Apollon77** [comment]
An Adapter that only cares about updating devices? Makes that really sense? ESpecially when there are "standard tools" for that available ...

**Comment by Dragon0501** [comment]
If possible you can add it to the Sonoff Adapter... It doesn't matter but the standard tools aren't working well... I think you must be a rocket Scientist for installing TasmoAdmin next to the Broker to the same pi. Update Script doesn't work and is very complicated to configure. The Board tells that TDM needs an full MQTT Broker, not the Sonoff Adapter. I hope we will find a solution...

**Comment by Ilovegym66** [comment]
Install TasmoAdmin on a Windows PC, that works fine and it's easy to install...
( sorry, I'm a rocket Scientist or not? )

**Comment by Dragon0501** [comment]
I don't want to have a second computer. It would be a dream if it can be hosted on the pi... 
I see there is no future for this idea...

**Comment by Ajimaru** [comment]
@Dragon0501 I have installed TasmoAdmin on a RPi3 together with IoBroker without any issues.
The link to a guide how to install Apache and php7 is linked in the installation guide at TasmoAdmin's website [](https://tasmota.github.io/docs/TasmoAdmin/#installation )

**Comment by psydie** [comment]
Hey I have a Javascript to Update alls Tasmota Devices to the newest update
