### ISSUE TITLE
Adapter für Wifi Wandthermostat für heizkreissteuerung / temperaturregelung von FLOUREON

### ISSUE THREAD

**Issue by smartboart** [ioBroker/AdapterRequests#53]
Hallo, ich habe ein optisch sehr ansprechendes und gut funktionierendes Wandthermostat zur Steuerung bzw. Raumtemperaturregelung installiert. Der Preis und die Optik sowie die Verarbeitung machen das Teil sehr attraktiv für Smarthomeanwendungen. Es funktioniert mit der installierten Firmware  sowohl im wlan also auch über eine Cloudanwendung ...benötigt wird allerdings eine App. 
Bedient werden kann das Teil also über App und direkt am Gerät....leider gibt es keine html Anwendung...Ein Adapter für den iobrokerfür für dieses Gerät ist vlt. auch für andere interessant. Deshalb hier meine Anfrage...und ein zwei Fotos von dem Teil...
![screenshot_2018-04-15-01-59-12](https://user-images.githubusercontent.com/38385805/38777710-d63fd48e-40ac-11e8-9530-844e84d115e0.png)
![20180415_125538](https://user-images.githubusercontent.com/38385805/38777715-f7f17696-40ac-11e8-8577-ae89c01f3b87.jpg)

![unbenannt](https://user-images.githubusercontent.com/38385805/38938594-2cd44a8e-4326-11e8-9a96-488c56333078.png)

**Comment by Apollon77** [comment]
Ein paar mehr Details bitte ... Exakte Typenbezeichnung? Hersteller-Link? Doku?

**Comment by smartboart** [comment]
Hier noch ein paar Details:

Name des Produktes: 
TGT70WIFI-EP (BEOK Controls)
 HY03WE-4-Wifi (FLOUREON)
Hersteller: BEOK Controls, gleiche Bauteile auch durch FLOUREON in D vertrieben
Technologie: WIFI

Hersteller link:

http://www.beok-controls.com/pro_view.asp?id=61

Features:
- Wi-Fi remote control function, control your house temperature from anywhere.
- Large LCD touch screen with backlight display
- Double temperature display mode
- 5/5+1/5+2 time modes
- 6 period daily programmable controlling temperature setting
- An-freezing function
- Internal and external temperature sensor for choice
- Keypad locking function to prevent the children from misusing
- Frame resistance material, safe and reliable
- Room temperature display precision is ±0.5℃
- Memory function when power failure,protect your setting from power failure
- Room temperature automatically calibration function
- Come with 3m external sensor



Technical Data: 
- Power Supply: AC200-240V, 50/60HZ
- Load Current: 12A/16A(Electric Heating) 
- Set-point Temperature Range: 5ºC - 35ºC
- Limit Temperature Range: 5-99℃ 
- Internal sensor measuring range: -10-60℃
- External sensor measuring range: -10-60℃
- Accuracy: ±0.5ºC 
- Setting unit: 0.5℃
- Consumption:<0.3W 
- Internal Sensor: NTC
- External Sensor: 10K resistance, Length=3 meters (optional)
- Material: flame resistant PC ABS
- Dimension: 86*86*14mm (H*W*D) 
- Display size: 63mm*48mm
- Weight: 176g

**Comment by JackWolfskin42** [comment]
Sieht cool aus - fehlt nur noch eine weisse Version :-)
Leider scheint das Protocol nicht offengelegt und noch nicht reverse engineered zu sein.
Aber da scheinen ja schon ein paar Leute dran zu arbeiten z.B. hier:
[Beok protocol](https://community.openhab.org/t/electronic-heating-thermostat-reverse-engineering-beok-floureon-decdeal/39251/11)
Mal sehen ob da was draus wird ...

**Comment by Apollon77** [comment]
Naja dann muss man also ggf ran und den netzwerkverkehr der App mitschneiden und analysieren ... und schon braucht man dringend die Hardware um zu starten.

**Comment by JackWolfskin42** [comment]
Wenn du den Datenverkehr entschlüsseln magst kauf ich dir gerne ein Thermostat ;-)

**Comment by smartboart** [comment]
Hallo, das Teil bekommt man günstig in der Bucht...Habe es jetzt seit 6 Monaten im Einsatz und läuft tadellos und sehr stabil...kurz macht was es soll und Einstellungen sind über die App sehr komfortabel... 
Wenn sich jemand daran macht einen adapter für IOBroker zu bauen, spende ich die Hardware...Ein Thermostat ist ohnehin automatisch mit dabei. internes und externes... Mir ist halt daran gelegen mein Netzwerk so sicher wie möglich zu halten, und deshalb möchte ich solche Geräet für das Internet sperren. Mit Vis hätte man dann trotzdem Kontrolle über das Teil... Wie gesagt, wenn sich jemand daran machen möchte, ich bestelle gerne so ein Teil. Brauche nur die Lieferadresse...

**Comment by Apollon77** [comment]
Dann sammle mal noch ein paar Votes, dann schauen wir mal :-)

**Comment by JackWolfskin42** [comment]
Manchmal dauert es im Alter etwas :-)
Dieses Wlan Thermostat basiert ja auf einem Broadlink Chipsatz und für den gibt es ja sogar schon einen IOBroker Adapter, d.h. jemand im Besitz eines Thermostats sollte mal ausprobieren ob der schon erkannt wird und sonst ggf. als Enhancement beim Broadlink Adapter eintragen:
[https://github.com/frankjoke/iobroker.broadlink2](https://github.com/frankjoke/iobroker.broadlink2
)

**Comment by Apollon77** [comment]
Ja sann ja noch einfacher ;-)

**Comment by smartboart** [comment]
coole Sache, werde das gleich heute noch austesten....gebe bescheid....danke für die Info...

**Comment by smartboart** [comment]
Hallo, danke für den Tipp...du hattest Recht...Der Adapter erkennt das Raumthermostat. Im Log steht folgendes, siehe Foto ganz oben...
Allerdings werden keine Instanzen hinzugefügt...

**Comment by JackWolfskin42** [comment]
Sowas ;-)
Ok, hab eben auch mein Muster bekommen und das gleiche Resultat. Dann mal ein Issue beim Broadlink Adpter dafür aufgemacht ... und nun daumendrücken und ggf. Hardware spenden !

**Comment by frankjoke** [comment]
Habe auf https://github.com/frankjoke/ioBroker.broadlink2/issues/22 geantwortet, wie gesagt, wenn mir wer ein Teil leihen kann kann ich versuchen die Kommandos & Werte in Broadlink2 einzubauen, kann allerdings ohne Device nichts versprechen.

**Comment by Apollon77** [comment]
Ich mache hier mal zu, geht bei broadlink2 weiter :-) Super!!
