### ISSUE TITLE
MIELE Scout RX2 HomeVision Saugroboter Adapter für iOBroker gesucht

### ISSUE THREAD

**Issue by SigiMOE** [ioBroker/AdapterRequests#54]
Hi,
immer mehr Haushaltsroboter von MIELE werden verkauft/gekauft und diese Geräte können mit der Scout RX2 App gesteuert werden.
https://itunes.apple.com/de/app/scout-rx2/id1347269040?mt=8
Ein Adapter für den Saugroboter wäre also eine super Sache! 
Leider kann ich nicht selbst programmieren, deshalb teile ich nur meine Idee mit euch. 
Vielleicht besteht auch bei anderen Interesse?!
https://forum.iobroker.net/viewtopic.php?f=30&t=13626&e=1&view=unread#unread

**Comment by blar** [comment]
Aktuell ist über die [öffentliche API](https://www.miele.com/developer/) nur die Statusabfrage des Scout RX2 möglich. Auf eine Anfrage zum **Miele 3rd party API Team** wurde mir mitgeteilt, dass die Steuerung bald möglich sein wird.

**Comment by DutchmanNL** [comment]
> Aktuell ist über die [öffentliche API](https://www.miele.com/developer/) nur die Statusabfrage des Scout RX2 möglich. Auf eine Anfrage zum **Miele 3rd party API Team** wurde mir mitgeteilt, dass die Steuerung bald möglich sein wird.

das währe interessant zu verfolgen und würde mit adapter Entwicklung warten bis die Daten auch in der API verfügbar sind (sonst eventuell doppelte Arbeit weil der layout sich ändert).

**Comment by Grizzelbee** [comment]
Besagte öffentliche API implementiere ich gerade im Rahmrn des MielecloudService Adapters, der gerade in latest eingezogen und auf dem Weg in Stable ist.
Das Auslesen aller States sollte bereits für alle Miele Geräte funktionieren. Die Steuerung werde ich in Kürze implementieren.

Supportthread: https://forum.iobroker.net/topic/29836/mielecloudservice-adapter/2
Repo: https://github.com/Grizzelbee/ioBroker.mielecloudservice

Über Rückmeldungen freue ich mich.

**Comment by Grizzelbee** [comment]
Request fullfilled: https://github.com/Grizzelbee/ioBroker.mielecloudservice

**Comment by Apollon77** [comment]
great! Thank you!
