### ISSUE TITLE
Blitzer Adapter

### ISSUE THREAD

**Issue by Bernd1984** [ioBroker/AdapterRequests#541]
Hallo,
ich beschäftige mich erst seit wenigen Tagen mit dem Thema RPI und auch ioBroker.
Ich habe gesehen, dass man Adpaterwünsche über Github stellen kann.
In verschiedenen Foren habe ich auch gesehen, dass bereits über Blitzerabfragen diskutiert wird. Jedoch scheint es, als wären das immer recht individuelle Lösungen für Einzelpersonen.
Daher dachte ich, ich stelle einmal eine Anfrage nach einem offiziellem Adapter.
Ich freue mich über Feedback

**Comment by Apollon77** [comment]
Hm ... was sollte der Adapter denn genau tun? Welche Datenquellen gäbe es? ...

**Comment by Bernd1984** [comment]
Hi Apollon,
danke für deine Antwort und Interesse.

Was sollte der Adapter tun:
Ich könnte mir vorstellen, dass es für viele Leute interessant wäre, ob in ihrem Umfeld oder auf dem Weg zur Arbeit ein (mobiler) Blitzer aufgestellt ist. Die festen Blitzer kennt man ja in der Regel. Wäre dies der Fall, kann man sich natürlich auf verschiedensten Wegen hierzu warnen lassen.

a) Umkreissuche um fest definierte GPS Koordinaten mit Radius
b) Umkreissuche um eine fest definierte Route mit Start und Ende. Etwas ähnliches habe ich einmal in VBA für Verkehrsmeldungen auf einer Route programmiert. 

Quellen: 
https://www.blitzer.de/
https://www.scdb.info/ (ist aber kostenpflichtig)
http://www.radarfalle.de/

Bereits andiskutiert:
https://forum.iobroker.net/topic/13617/blitzer-auslesen-von-https-osthessen-blitzer-de

Was denkst du hierzu?
Viele Grüße

**Comment by ldittmar81** [comment]
Es gibt ein Skript der sowas macht: https://forum.iobroker.net/topic/37979/geschlossen-blitzer-%C3%BCber-api-abfragen/16

Daraus könnte man ein Adapter schreiben, der mehrere Routen auswertet und immer  die aktuellen Blitzer anzeigt. Zum Beispiel beim Weg zur Arbeit.

**Comment by sigi2345** [comment]
Hallo, oder dieser Adapter:

https://github.com/Steiger04/ioBroker.radar-trap

**Comment by ldittmar81** [comment]
@sigi2345 danke für die Info :-) 
@Steiger04 Danke fürs Adapter

**Comment by mcm1957** [comment]
request for latest: https://github.com/ioBroker/ioBroker.repositories/pull/2292

**Comment by mcm1957** [comment]
Published at latest
