### ISSUE TITLE
mqtt.0 error (5821) Client [btscanner1] Cannot parse

### ISSUE THREAD

**Issue by BurmisGit** [ioBroker/AdapterRequests#547]
Hallo,
angeregt durch einen Artikel in der ct 26/2020 (ESP32 als Smart-Home-Bluetooth-Scanner) sende die Results vom ESP32 an eine ioBroker-MQTT-Instanz.
Die Daten landen in den entsprechenden Objekten und ich kann sie auch auswerten.
Im Log kommt aber bei jedem Scan folgende Fehlermeldung:
**mqtt.0 error (5821) Client [btscanner1] Cannot parse {"Results":{"5c ....usw**
Wenn ich die gleichen Daten mit dem MQTT.fx Client Publishe kommt die Fehlermeldung nicht.
Kann hir jemand helfen?

**Comment by Apollon77** [comment]
Bitte Adapter-spzifische Issues im entsprechenden Adapter Repo anlegen ... und bitte vollständige Lofs posten! Die Meldung meint an sich das das JSON ungültog ist
