### ISSUE TITLE
SILVER CREST MISTER CUISINE CONNECT

### ISSUE THREAD

**Issue by Sevsev972** [ioBroker/AdapterRequests#550]
Please I need your help 
I bouge à Mister cuisine connect last December in France and then live to Martinique.
I just realized that it is not working and i think that is because the versionnof my firmware is 0.
I don t think it s normal.
Does anybody has this same trouble ?
Hotline dose not reply 
Please van you help me to upload a firmware for exemple.
![20210107_084921](https://user-images.githubusercontent.com/77133497/103965667-9ed76e80-5134-11eb-83ae-d3d0ce1ebb46.jpg)
![Uploading 20210107_084925.jpg…]()

**Comment by Apollon77** [comment]
sorry but this is no adapter request
