### ISSUE TITLE
Moes Zigbee Radiator Thermostat aka Tuya

### ISSUE THREAD

**Issue by Dilldappe-io** [ioBroker/AdapterRequests#561]
New adapter for the thermostat. I bought it through Aliexpress 
https://moes.de.aliexpress.com/store/4988128?spm=a2g0o.detail.1000002.2.2e3f555fECTxvt 
Direct store is here:
https://www.moeshouse.com/products/zigbee-smart-thermostatic-radiator-valve-controller-trv-thermostat-tuya-temperature-voice-control-works-with-alexa-google-home?variant=31931364212817

I guess it is a Tuya device. It pairs with my ioBroker but as an unidentified device. 
Nevertheless I can read out the following from the info page:
model: **TS0601**
type:EndDevice
nwk:60899
**manuf id:4098**
manufacturer:_TZE200_zion52ef
power:Battery
app version:255
hard version:1
zcl version:3
stack version:0
date code:
interviewed:true
configured:false
endpoint:1
profile:260
input clusters:genBasic (0)
genTime (10)
genGroups (4)
genScenes (5)
manuSpecificTuyaDimmer (61184)
output clusters:genOta (25)

The manufacturer ID is the same for the Tuya **TS0201** Temperature and Humidity Sensor which integrates fine in ioBroker.
Same manufacturer ID is true for the LIDL smart socket, which is a Tuya **TS011F** 
**Additional context**
On the Moes Homepage 2MQTT  is mentioned. Until now I dont have MQTT running but if the device would work through that I would try that instead of an adapter

**Comment by Apollon77** [comment]
SO is it zigbee? Then please create the issue for support in the zigbnee adapter ...

**Comment by arteck** [comment]
close here.. its a zigbee device

**Comment by ldittmar81** [comment]
@Apollon77 can be closed... @Dilldappe-io you can use the zigbee adapter
