### ISSUE TITLE
Netatmo Smarte Videotürklingel

### ISSUE THREAD

**Issue by mrs14** [ioBroker/AdapterRequests#562]
**What kind of device or service you would like to see an adapter for?**
Add name and company of the device, including links to the device and any additional informations[...]

**Is an official API including documentation is available?**
If yes please add links and informations[...]

**Are other libraries for an integration available?**
Ideally in JavaScript/npm, but also other programming languages are interesting, add Links please

**Is this device already integrated in other Smart Home systems?**
Add Links please

**Is this device already integrated in homebridge? Might the ham adapter together with the homebridge plugin be sufficient?**
Please try it and add infos

**Additional context**
Add any other context or screenshots about the feature request here. If the topic was discussed in ioBroker forum please include the link too.

After you created the issue vote for yourself in the first post of the issue using the "+1"/"Thumbs up" button

**Comment by mrs14** [comment]
Gibt es die Möglichkeit die Netatmo Smarte Videotürklingel in den Iobroker einzubinden?

Vielen Dank im Vorraus...

**Comment by einarmiger0815** [comment]
Ich stand lange erst mit dem Netatmo und später mit dem Legrand-Kundendienst in Verbindung:

Angeblich aus gründen der Sicherheit wollen die Franzosen keine API bereitstellen. Selbst den Zugriff auf den RTSP-Stream geben sie nicht frei. Ich vermute, dass die ganze Sache bei denen in Richtung Abo laufen wird.

Mach einen Haken dran und kaufe dir eine Türkamera, die RTSP und API anbietet - da gibt es mittlerweile gute Modelle mit wesentlich höherer Auflösung, besserer Nachtsicht und zum Drittel des Preises. Habe ich auch gemacht.

Netatmo ist in meinen Augen eine Totgeburt. Braucht keiner, genau wie Biergläser ... ;-)

**Comment by Apollon77** [comment]
Der Netatmo Adapter kann das nicht schon??

**Comment by mrs14** [comment]
Danke für die Anwort :-) 
Kannst du mir eine empfehlen? 

⁣Mit freundlichen Grüßen 

Michael Reis ​

**Comment by einarmiger0815** [comment]
> Der Netatmo Adapter kann das nicht schon??

Seit dem Update vor einem halben Jahr nach der Übernahme von Legrand wurden keine Daten mehr aktualisiert; die Netatmo Doorbell wurde im Gegensatz zu den Netatmo smarten Aussenkameras gar nicht erst unterstützt. Deswegen ja der (ja, man kann schon sagen) Disput mit dem Support.

**Comment by Apollon77** [comment]
> Netatmo Doorbell wurde im Gegensatz zu den Netatmo smarten Aussenkameras gar nicht erst unterstützt

Und was hab ich dann in https://github.com/PArns/ioBroker.netatmo/issues/45 getan?

**Comment by einarmiger0815** [comment]
Bei mir hat das nie hingehauen ... ohne Scherz.

**Comment by Apollon77** [comment]
naja ... dann ist ein Issue mit vollem Debug Log bei dem Adapter wo es tun sollte der ideale erste Schritt :-)

**Comment by einarmiger0815** [comment]
Eigentlich schon ... aber irgendwann gibt man einfach auf. 

... und wenn dann das neue Spielzeug einfach tut, was es soll, ist der Rest vergessen. 

Kennst du das nicht? ;-)

**Comment by Apollon77** [comment]
naja, Aufgeben heisst sich mit der Situation abfinden ... dann ist es ja auch kein Problem mehr ... eine Lösung bekommt man so hat nicht ;-)
