### ISSUE TITLE
Adguard Home

### ISSUE THREAD

**Issue by Loi83** [ioBroker/AdapterRequests#568]
Adguard Home ist ein DNS Werbeblocker ähnlich PiHole. Meiner Meinung nach allerdings einfacher zu konfigurieren.

**Is an official API including documentation is available?**
https://github.com/AdguardTeam/AdGuardHome/tree/master/openapi

**Are other libraries for an integration available?**
https://pypi.org/project/adguardhome/

**Is this device already integrated in other Smart Home systems?**
https://www.home-assistant.io/integrations/adguard/

**Comment by o0shojo0o** [comment]
Hi @Loi83
ich werde mich der Sache annehmen, da ich mittlerweile auch den AdGuard Home einsetzte.
Hier das Repo dazu https://github.com/o0shojo0o/ioBroker.adguard

**Comment by Loi83** [comment]
Hi @o0shojo0o danke für den Adapter. Gerade installiert, läuft ohne Probleme. Die Stats passen und die Switches schalten :)
