### ISSUE TITLE
Tesla Powerwall Adapter

### ISSUE THREAD

**Issue by funcarv3r** [ioBroker/AdapterRequests#569]
Tesla Powerwall 2 - Stromspeicher

Es gibt bereits in github eine Doku zur API
https://github.com/vloschiavo/powerwall2

Im Zeitalter der Elektromobilität sollte auch der Mercedes unter den Stromspeichern nicht im IOBroker fehlen. In Kombination mit einer Wallbox wie der Go-e Charger kann so eine effiziente Ladesteuerung für Überschiussladung erstellt werden. Klassw wäre wenn die Berechnung des Überschusses direkt im Adapter erfolgen würde. Klasse wäre wenn man alle Daten der Powerwall auslesen könnte, also den Verbrauch vom Haus, wieviel Strom wird produziert, wie viel verbraucht, wieviel eingespeist oder wie viel bezogen. Gleichzeitig ein Wert wie voll die Batterie geladen ist, der Wert den ich auslesen konnte stimmt leider nicht, bei tatsächlichen 2% zeigt die API 6% an, bei tatsächlichen 35% sind es über di API 44%.

**Comment by funcarv3r** [comment]
Sollte jemand Zugang zu einer Powerwall benötigen, wir haben natürlich eine im Haus und ich könnte den Zugang zur Hardware z.B. per VPN zur Verfügung stellen. Es gäbe noch andere Alternativen , aber hier wird z.B. eine Feste IP vorausgesetzt.

**Comment by Newan** [comment]
Schau mal ob bei den folgenden links Daten kommen. Dann wäre es ein einfaches:

`http://<ip-Powerwall>/api/system_status/soe 
http://<ip-Powerwall>/api/meters/aggregates
http://<ip-Powerwall>/api/site_info
http://<ip-Powerwall>/api/sitemaster
http://<ip-Powerwall>/api/powerwalls
http://<ip-Powerwall>/api/networks
http://<ip-Powerwall>/api/system/networks
http://<ip-Powerwall>/api/operation
http://<ip-Powerwall>/api/status
http://<ip-Powerwall>/api/customer/registration`

**Comment by pnewman68** [comment]
Hallo Newan,

bis Firmwareversion 20.49.0 konnte man die Werte so auslesen.
Seit Firmwareversion 20.49.0 kommt die Meldung:
code":403,"error":"Unable to GET to resource","message":"User does not have adequate access rights"

Ich habe gelesen, dass die Powerwall seit  Firmwareversion 20.49.0 Oauth v3 Autorisation verwendet.

Gruß
Ralf

**Comment by Newan** [comment]
🤔, https://oauth.net/3/

denke wir warten: https://github.com/vloschiavo/powerwall2/issues/41
ab ob da was für die lib kommt und dann müssten wir zusammen testen da ich keinen Speicher besitze.

**Comment by Newan** [comment]
> Sollte jemand Zugang zu einer Powerwall benötigen, wir haben natürlich eine im Haus und ich könnte den Zugang zur Hardware z.B. per VPN zur Verfügung stellen. Es gäbe noch andere Alternativen , aber hier wird z.B. eine Feste IP vorausgesetzt.

Bitte Zugang dann würde ich mir das mal ansehen. Muss zu https://<tesla-powerwall-ip>/api/ gelangen und brauche User / Password der Powerwall. info@newan.de

**Comment by hausschwein** [comment]
Ich hätte auch Interesse an dem Adapter für den ioBroker, um unsere Tesla PowerWall einzubinden.

**Comment by Newan** [comment]
Hab keine Zugänge erhalten.

**Comment by DraycD** [comment]
Hey, nach dem Update auf 21.20.2 geht das Javascript leider auch nicht mehr:
Das Skript stammt von MeSwissX (ganz unten die Zip datei):
https://tff-forum.de/t/powerwall-2-daten-auslesen-per-api/34214/27

Error ist: 

javascript.0 | 2021-07-06 20:27:36.153 | info | (1244) Stop script script.js.common.ioBroker-powerWall
javascript.0 | 2021-07-06 20:27:32.156 | error | (1244) Request error: Error: Client network socket disconnected before secure TLS connection was established
javascript.0 | 2021-07-06 20:27:32.156 | error | (1244) script.js.common.ioBroker-powerWall: Request PowerWall meldet Fehler: Error: Client network socket disconnected before secure TLS connection was established

kann leider kein java ;(

**Comment by DraycD** [comment]
hier der code:
const ipPowerwall = '192.168.1.142';
const userEmail = "thierry@girard.li";
const password = "thgiPowerwall";
var logOn = false;

createState("photovoltaik.PowerWall", 0.0); // Ladezustand PowerWall in %
createState("photovoltaik.PowerWallErrorReported", false);
createState("photovoltaik.PowerWallDown", false);

createState("photovoltaik.powerWall.error", false);
createState("photovoltaik.powerWall.down", false);
createState("photovoltaik.powerWall.battery", 0.0); // Ladezustand PowerWall in %
createState("photovoltaik.powerWall.power_netz", 0.0); // Energie Netz
createState("photovoltaik.powerWall.power_battery", 0.0); // Energie Batterie
createState("photovoltaik.powerWall.power_haus", 0.0); // Energie Haus
createState("photovoltaik.powerWall.power_solar", 0.0); // Energie Photovoltaik

var powerWallErrorReported = 'javascript.0.photovoltaik.PowerWallErrorReported';
var PowerWallDown = 'javascript.0.photovoltaik.PowerWallDown';

getPWCookie();

function getPWCookie() {

    const https = require("https");
    const cookieUrl = 'https://'+ipPowerwall+'/api/login/Basic';
    
    var request = require("request");
    var agentOptions;
    var agent;

    agentOptions = {
        host: ipPowerwall
        , port: '443'
        , path: '/api/login/Basic'
        , rejectUnauthorized: false
    };

    agent = new https.Agent(agentOptions);

    var headers = { 'Content-Type': 'application/json' };
    var dataString = '{"username": "customer","email": "'+userEmail+'","password":"'+password+'"}';

    var options = {
        url: cookieUrl,
        method: 'POST',
        headers: headers,
        body: dataString,
        agent: agent
    };

    request(options, function (error, response, body) {
            // if (err) log(JSON.stringify(err));
            // if (resp) log(JSON.stringify(resp));
        if (!error && response.statusCode == 200) {
 //           if(logon) { log('powerWall_Cookie_login_success') };
            try {
                var json = JSON.parse(body);
                var token = json.token;
                getPWDataNew(token);
                
            } catch (e) {
                if (e instanceof SyntaxError) {
                    log("json parse error: " + e);
                } else {
                    log("json parse error - other: " + e);
                }
            } 
        } else {
            log('Request PowerWall meldet Fehler: ' + error, 'error');
            if (getState(powerWallErrorReported).val === false) {
                setState(powerWallErrorReported,true);
                //pushover
                sendTo('pushover.0', {
                    message: 'PowerWall Error',
                    title: 'POWERWALL',
                    priority: 1,
                    sound: 'magic'
                });
            }
        }
    });
}

function getPWDataNew(token) {
    
    const https = require("https");
    const urlBatterySoe = 'https://'+ipPowerwall+'/api/system_status/soe';
    const urlAggregates = 'https://'+ipPowerwall+'/api/meters/aggregates';
    
    var request = require("request");

    var agentOptions;
    var agent;
    
    agentOptions = {
        host: ipPowerwall
        , port: '443'
        , path: '/'
        , rejectUnauthorized: false
    };
        
    agent = new https.Agent(agentOptions);

    var headers = {
        'Content-Type': 'application/json',
        'Cookie' : 'AuthCookie='+token
    };

    var optionsBatterySoe = {
        url: urlBatterySoe,
        method: 'GET',
        headers: headers,
        agent: agent
    };

    var optionsAggregates = {
        url: urlAggregates,
        method: 'GET',
        headers: headers,
        agent: agent
    };

    request(optionsBatterySoe, function (error, response, body) {
//            if (error) log(JSON.stringify(error));
//            if (response) log(JSON.stringify(response));
        if (!error && response.statusCode == 200) {
//            if (logon) {log('powerWall readout success!!')};
            setState(powerWallErrorReported,false);
            setState(PowerWallDown,false);
            if (body) {
                batteryPercentage(body);
          } 
        } else {
            log('powerWall battery readout Fehler: ' + error, 'error');
        }
    });

    request(optionsAggregates, function (error, response, body) {
//            if (error) log(JSON.stringify(error));
//            if (response) log(JSON.stringify(response));
        if (!error && response.statusCode == 200) {
//            if (logon) {log('powerWall readout success!!')};
            if (body) {
                aggregatesVerarbeiten(body);
          } 
        } else {
            log('powerWall aggregates readout Fehler: ' + error, 'error');
        }
    });

    
}

// analyse PowerWall Battery Percentage
function batteryPercentage(result) {
    try {
        var json = JSON.parse(result);

        var ladungPowerWall = Number(json.percentage);
        
        if (logOn) log("PowerWall Ladezustand: " + ladungPowerWall + " %");
        
        setState("javascript.0.photovoltaik.PowerWall"/*PowerWall Ladezustand in %*/,ladungPowerWall);
        
    } catch (e) {
        if (e instanceof SyntaxError) {
            log("json parse error: " + e);
        } else {
            log("json parse error - other: " + e);
        }
    }
}

// analyse PowerWall aggregates
function aggregatesVerarbeiten(result) {
    try {
        var json = JSON.parse(result);

        var sitePower = Number(json.site.instant_power);
        var batteryPower = Number(json.battery.instant_power);
        var loadPower = Number(json.load.instant_power);
        var solarPower = Number(json.solar.instant_power);

        setState('photovoltaik.powerWall.power_netz',sitePower);
        setState('photovoltaik.powerWall.power_battery',batteryPower);
        setState('photovoltaik.powerWall.power_haus',loadPower);
        setState('photovoltaik.powerWall.power_solar',solarPower);
        
        if (logOn) log("PowerWall site: " + sitePower + ' battery: ' + batteryPower + ' load: ' + loadPower + ' solar: ' + solarPower);
                
    } catch (e) {
        if (e instanceof SyntaxError) {
            log("json aggregates parse error: " + e);
        } else {
            log("json aggregates parse error - other: " + e);
        }
    }
}

// Startet das Skript alle 1 minuten neu
schedule("* * * * *", function() {
    getPWCookie();
});

**Comment by TA2k** [comment]
Werden über den IP zugang mehr daten angezeigt als über die Tesla app.
Die Tesla app daten könnte man auch in tesla motors adapter integrieren.

**Comment by quadjojo** [comment]
Meineswissens nicht. Wäre wahrscheinlich der einfachere Weg weil dieses Modul bereits existiert.

**Comment by TA2k** [comment]
Dann kann ja jemand den Adapter hier testen und schauen ob bei ihm was angezeigt wird
https://forum.iobroker.net/topic/47203/test-tesla-motors-v1-0-0

**Comment by quadjojo** [comment]
Ja, habe ich bereits. Der zeigt nur die Fahrzeug Daten/Werte an

**Comment by TA2k** [comment]
Hab erst vor 40min die power walls hinzufgefügt hast du seit dem neu installiert und getestet?

**Comment by quadjojo** [comment]
Ah sorry.. ich stand auf dem Schlauch :)
Jetzt läuft es.. MEGA!

**Comment by TA2k** [comment]
Werden alle Daten angezeigt und aktualisiert? Fehlen noch Werte?

**Comment by quadjojo** [comment]
Ja, das hier sind ja alle Werte und die aktualisieren sich auch korrekt.
![Screenshot 2021-08-22 123322](https://user-images.githubusercontent.com/3460344/130351968-83370e9b-58ab-41ec-acc3-23d0e87561f5.png)

In der App gibt es noch Weiteres zu sehen wie z.B. Hausverbrauch, was zurückgespeist wird, usw.
![IMG_2924](https://user-images.githubusercontent.com/3460344/130351925-3c2f3de2-d913-46ff-82b9-cc82dd7d7421.jpg)
Könnte man das noch einbinden?
Falls ja würde hier wahrscheinlich eine andere (höhere) Aktualisierungsfrequenz Sinn machen.
Grüße
Toby

**Comment by hausschwein** [comment]
Kann mir jemand kurz erklären, wie ich den Adapter im ioBroker installiere. Bei mir wird immernoch die Version 0.5.2 angezeigt und kein Update verfügbar.

Danke!!

**Comment by quadjojo** [comment]
Hier steht alles:
https://forum.iobroker.net/topic/47203/test-tesla-motors-v1-0-0

Du musst allerdings vorher dieses Kopf Icon (Expertenmodus) in der Titelzeile aktivieren, sonst wird dir das GitHub Icon nicht angezeigt:
![Screenshot 2021-08-22 133710](https://user-images.githubusercontent.com/3460344/130353652-c0069025-5f9f-4f27-8cf3-75dcbc0fa58e.png)

**Comment by TA2k** [comment]
@quadjojo  Kann dazu keine öffentlich dokumentation zum powerflow finden. Bräuchte also echte Zugangsdaten um zu sehen wo die App die Daten herbekommt

**Comment by hausschwein** [comment]
Vielen Dank, die Installation hat geklappt, die Batterie liefert Daten. Nur die Daten unter charge state bleiben leer. Sollte diese auch ordner auch befüllt werden oder gehört das dann zu der Kategorie Auto also nicht zur Powerwall?

**Comment by TA2k** [comment]
@ldittmar81 In tesla adapter integriert
