### ISSUE TITLE
Xiaomi Sensoren ohne "China-Gateway und Cloud"

### ISSUE THREAD

**Issue by none007** [ioBroker/AdapterRequests#57]
Hallo Zusammen,

ich habe gestern diese Seite gefunden "https://haus-automatisierung.com/projekt/2018/04/28/projekt-xiaomi-ohne-cloud.html" und frage mich, ob das nicht auch direkt in einem Adapter in IObroker integiert werden könnte. Wenn ich mir die Github Page von oskarn97 anschaue "https://github.com/oskarn97/xiaomi-zb2mqtt" scheint das ja bis auf die Firmware für den Stick Javascript zu sein. Da soweit ich es verstanden habe IObroker auch darauf basiert, sollte es doch eigentlich keine "großes" Problem sein, oder?

**Comment by GermanBluefox** [comment]
Es ist schon gemacht.
https://github.com/kirovilya/ioBroker.zigbee

пн, 30 апр. 2018 г., 8:48 none007 <notifications@github.com>:

**Comment by Apollon77** [comment]
@none007 please test it out. install directly from GithUb using URL given above and report back in forum/ as issues in the respective github project

**Comment by steckenpferd** [comment]
Mega cool welche Zigbee Gateways/USB Stick kann ich damit ansprechen bzw brauche ich für den Adapter?

**Comment by none007** [comment]
Auf dieser Seite ist die Hardware beschrieben. Leider auf Russisch aber Google Übersetzer liefert brauchbar Ergebnisse.
https://github.com/kirovilya/ioBroker.zigbee/wiki/%D0%9F%D1%80%D0%BE%D1%88%D0%B8%D0%B2%D0%BA%D0%B0

**Comment by steckenpferd** [comment]
Super - wäre an einer kleinen Schritt für Schritt Anleitung stark intressiert !!

**Comment by GermanBluefox** [comment]
https://translate.google.com/translate?hl=en&sl=auto&tl=de&u=https%3A%2F%2Fgithub.com%2Fkirovilya%2FioBroker.zigbee%2Fwiki

2018-05-09 19:05 GMT+02:00 steckenpferd <notifications@github.com>:
