### ISSUE TITLE
Warema WMS Webcontrol Adapter

### ISSUE THREAD

**Issue by Rapptor33** [ioBroker/AdapterRequests#572]
Warema WMS [https://www.warema.com/en/control-systems/radio-systems/wms-webcontrol-pro.php](https://www.warema.com/en/control-systems/radio-systems/wms-webcontrol-pro.php)
Adapter for WebControl or Webcontrol pro (newer Version)

There are some versions for the WMS-Stick, maybe this helps:
[https://www.npmjs.com/package/warema-wms-venetian-blinds](https://www.npmjs.com/package/warema-wms-venetian-blinds)

Python Web Control libary:
[https://github.com/cornim/wms_webcontrol](https://github.com/cornim/wms_webcontrol)
Others with WMS Stick:
[https://github.com/zeezee300/openwms](https://github.com/zeezee300/openwms)

Warema now is also implemented into  Homee 
[https://www.warema.at/steuerungssysteme/funksysteme/homee.php](https://www.warema.at/steuerungssysteme/funksysteme/homee.php)

iobroker Forum Topic:
[https://forum.iobroker.net/topic/7336/iobroker-mit-warema-wms-web-control](https://forum.iobroker.net/topic/7336/iobroker-mit-warema-wms-web-control)

**Comment by TA2k** [comment]
https://forum.iobroker.net/topic/45197/test-warema-wms-webcontroller-v0-0-1
