### ISSUE TITLE
Solax Cloud Adapter für Solar Wechselrichter

### ISSUE THREAD

**Issue by huettmasterTB** [ioBroker/AdapterRequests#579]
Hallo,

Ein Adapter zum Auslesen des Wechselrichters von Solax wäre super! Die API-Dokumentation und einen Zugang könnte ich für die Entwicklung bereit stellen.

**Comment by KristianHeider** [comment]
Nimm doch einfach ein Script:
```
var request = require('request');

var acpower = 'javascript.0.Solar.ACPower';
createState(acpower, 0, { read: true, write: true, desc: acpower, type: 'number' });
var yieldtoday = 'javascript.0.Solar.YieldToday';
createState(yieldtoday, 0, { read: true, write: true, desc: yieldtoday, type: 'number' });

function getInfo(answer) {
    var options = {
        url: 'https://www.eu.solaxcloud.com:9443/proxy/api/getRealtimeInfo.do?tokenId=111&sn=222',
        method: 'GET', headers: { 'User-Agent': 'request' }
    };

    request(options, callback);

    function callback(error, response, body) {
        if (!error && response.statusCode == 200) {
            answer(JSON.parse(body));
        }
    }
}

schedule('*/2 * * * *', function () {  // each 2 min
    getInfo(function (read) {
        setState(acpower, read.result.acpower);
    });
});

schedule('50 23 * * *', function () {  //
    getInfo(function (read) {
        setState(yieldtoday, read.result.yieldtoday);
    });
});
```
ersetzen
**111** dein API Token
**222** dein Wechselrichter SN
Am Besten den String 1x im Browser ausprobieren (https://www.eu.solaxcloud.com:9443/proxy/api/getRealtimeInfo.do?tokenId=111&sn=222).

**Comment by lmk1366** [comment]
Danke Kristian, 
habe Deinen Code gerade bei mir im ioBroker implementier. Alles läuft direkt.

**Comment by simatec** [comment]
Ich würde mich dabei machen und einen Adapter bauen. 
Aktuell plane ich bei mir auch in diese Richtung eine PV Anlage auf das Garagendach zu bauen. 

Im Moment habe ich allerdings noch keine Hardware. 
Wenn also Interesse an einem Adapter besteht, könnt ihr mich gerne direkt anschreiben. 

Es müsste mir dann für die Entwicklung jemand sein Token und SN zur Verfügung stellen. 

VG simatec

**Comment by simatec** [comment]
Ich habe mich mal dran gesetzt und einen Adapter geschrieben.
Wer ihn testen möchte, kann das gerne über eine Github Installation tun und sein Feedback geben.

https://github.com/simatec/ioBroker.solax.git

**Comment by ldittmar81** [comment]
@Apollon77 please close it... its already stable :-)

**Comment by OKTP** [comment]
Hallo, @simatec ist es möglich das der Adapter bei der 4. Generation des x3 Wechselrichters nicht funktioniert?
Ich bekomme der WR über die Cloud ausgelesen, aber nicht local.

**Comment by simatec** [comment]
Was heißt lokal? Wifi? Welche Firmwareversion ist auf dem Wifi Stick? Hast du die Doku gelesen?

**Comment by OKTP** [comment]
Ich habe die Firmware aus der Doku auf den WiFi Stick gezogen. Über die solax cloud funktioniert die Abfrage auch. Wenn ich im Adapter die Experteneinstellungen aktiviere und alles einstelle kann ich nicht auf den WR zugreifen. Es werden mir zwar die Datenpunkte angezeigt, aber der WR bleibt offline.

**Comment by simatec** [comment]
Zeige mal ein Screenshot des Webinterfaces vom Wifi Stick

**Comment by OKTP** [comment]
Mache ich heute Abend fertig wenn ich zu Hause bin.

**Comment by ldittmar81** [comment]
@OKTP Der Richtige Weg ist hier https://github.com/simatec/ioBroker.solax/issues ein issue anzulegen und nicht die geschlossenen Wünsche weiter zu führen.

**Comment by OKTP** [comment]
Ich hoffe das das mit den Bildern funktioniert. Ich kenne mich hier leider nicht wirklich aus. Mir ist auch aufgefallen das ich das Webinterface auch nicht über die Lokale IP aufrufen kann. Ich habe den Wlan Stick mit der Externen Antenne, gibt es da eventuell Unterschiede?

![Solax1](https://user-images.githubusercontent.com/100536655/156029398-1dca864c-4092-4b0d-8f63-8313cdc9e5d2.jpg)
![Solax2](https://user-images.githubusercontent.com/100536655/156029401-09115e86-95cd-4995-a967-35a84f07f7ca.jpg)
![Solax3](https://user-images.githubusercontent.com/100536655/156029403-09f475cf-dd4e-4076-b448-6956854f806f.jpg)

**Comment by OKTP** [comment]
@ldittmar81 Sorry, das wusste ich nicht. Kann man das eventuell irgendwie verschieben?

**Comment by simatec** [comment]
Bitte erstelle hier mal das Issue. 
https://github.com/simatec/ioBroker.solax
