### ISSUE TITLE
android wandtablet / tablet wallmount Adapter für interne kamera als ip cam und bewegungsmelder 

### ISSUE THREAD

**Issue by smartboart** [ioBroker/AdapterRequests#58]
Hallo, ich würde gerne mein androit tablet / wallmount welches als vis im einsatz für iobroker ist, auch als ip cam und bewegungsmelder für die alarmanlage benutzen..zur zeit mache ich das mit der fritzcam app welche das auch prima macht...alarm per mail mit bild und speichern des bildes auf einem nass...sogar life gespräche sind möglich...
Leider lässt sich das nicht ohne grossen aufwand in vis einbinden geschweige denn als datenpunkt für die alarmanlage nutzen...mit so einem adapter könnten alle alten android telefone oder tablet als bewegugsmelder und ip cam laufen....
Als vorlage würde ich da die fritzcam app vorschlagen, welche echt gut läuft...

**Comment by BassT23** [comment]
Meine Lösung:

App "IP Webcam" - https://play.google.com/store/apps/details?id=com.pas.webcam.pro

Funktioniert prima!

Verwende es bei mir mit einem SGS3 (Wohnzimmer Kamera)
und einem SGTab3 10" (Küchentablet)

Zusätzlich läuft bei mir alles über einen Motioneye Server. Damit lässt sich dann auch der Bewegungsmelder umsetzen.

PS: diese Kameras laufen bei mir deutlich besser als die China WLan Cams.
Einziges manko; keine Nachtsicht.

Grüße

**Comment by ldittmar81** [comment]
Ist das gleiche wie https://github.com/ioBroker/AdapterRequests/issues/8
