### ISSUE TITLE
OCPP Wallbox Adapter

### ISSUE THREAD

**Issue by jaschkopf** [ioBroker/AdapterRequests#582]
**What kind of device or service you would like to see an adapter for?**
Many wallboxes use OCPP, like VW ID Charger Connect/Pro. 

**Is an official API including documentation is available?**
OCPP is open source 

**Are other libraries for an integration available?**
https://github.com/NewMotion/ocpp 

**Is this device already integrated in other Smart Home systems?**
For iobroker the "VW Connect" adapter integrates the charger over cloud. But OCPP would be a nice local network solution.
https://github.com/TA2k/ioBroker.vw-connect 

**Is this device already integrated in homebridge? Might the ham adapter together with the homebridge plugin be sufficient?**
I don't know

**Additional context**
Maybe this project could help, too: https://github.com/RWTH-i5-IDSG/steve

**Comment by Schimi1983** [comment]
Die cfos Wallbox würde mit OCPP auch funktionieren:

https://github.com/ioBroker/AdapterRequests/issues/525

**Comment by hostservice** [comment]
Meine keba hat auch ocpp. Integraton wäre toll, wenn man abfragen könnte, wann ist das Auto voll. etc.

**Comment by Micha0203** [comment]
My evBox Elvi does support OCPP 1.5 S und 1.6 J. I would love to see an integration so i can see the stats about ongoing charges in IOBroker.

**Comment by kantega-ea** [comment]
Ein Adapter für OCPP im Biobroker wäre traumhaft.

**Comment by foxriver76** [comment]
This might be useful https://github.com/elifTech/cpd-ocpp

**Comment by kleineismann** [comment]
It does not work for me. This is not a ocpp adapter. I installed this module and I see nothing more.

**Comment by foxriver76** [comment]
It’s obviously not an adapter, it can be used by an adapter dev.
