### ISSUE TITLE
RCT-Power

### ISSUE THREAD

**Issue by deckerstim** [ioBroker/AdapterRequests#583]
HEy,

i installed a new photovoltaics system from RCT-Power. the inverter does have a networking function, but it is only working with a stupid iOs app.
I would like to have the data in iobroker in order to control ma smart home devices, such as dishwasher etc.
It would make sense to start energy hungry devices when energy is available.

**Is an official API including documentation is available?**
afaik: no

**Are other libraries for an integration available?**
there i a website, wher the system can be monitored.

**Is this device already integrated in other Smart Home systems?**
no

**Is this device already integrated in homebridge? Might the ham adapter together with the homebridge plugin be sufficient?**
No

**Additional context**
Add any other context or screenshots about the feature request here. If the topic was discussed in ioBroker forum please include the link too.

After you created the issue vote for yourself in the first post of the issue using the "+1"/"Thumbs up" button

**Comment by Tobi-BPi** [comment]
Hey, 

i think i have some informations for this adapter. 
(i also have RCT POWER Hardware (PV and Battery) 
in git is a version vor IPSymcon
[IPSCoyote/RCT-Power](https://github.com/IPSCoyote/RCT-Power)

There is also a pyton script version
[python-rctclient](https://github.com/svalouch/python-rctclient)

I hope i could help. 
for testing the hardware, contact me again. 

Tobi

**Comment by Tobi-BPi** [comment]
Hey, 
i got many Documens from RCT Support. 

Is ther somebody who can need/use this Docs for adapter creating?

Wherre can i put this documens? 

regards 
tobi

**Comment by Apollon77** [comment]
I think for now good to know you have them available. As soon as a developer can start he might request it

**Comment by Dirk-I** [comment]
Hallo, es gibt schon einen Anfang.
https://github.com/lauff/ioBroker.rct 

vielleicht hat jemand Lust zu helfen? 

VG
Dirk

**Comment by ldittmar81** [comment]
Close after https://github.com/ioBroker/ioBroker.repositories/pull/1621 review

**Comment by mcm1957** [comment]
Adapter available at https://github.com/lauff/ioBroker.rct
