### ISSUE TITLE
Samsung TV -- H and J Series -- JS lib is available

### ISSUE THREAD

**Issue by mwp007** [ioBroker/AdapterRequests#587]
The Samsung TV community adapter would be very happy if someone could extend it with this library :

https://github.com/tdudek/samsung-remote-models-2014-and-newer

I created an issue already in the adapter github itself:
https://github.com/iobroker-community-adapters/ioBroker.samsung-community/issues/45

**Comment by Apollon77** [comment]
If you created the issue with the adapter this should be sufficient
