### ISSUE TITLE
wireless MBUS Adapter

### ISSUE THREAD

**Issue by sky-it** [ioBroker/AdapterRequests#590]
aktuell scheint es keinen lauffähigen wireless MBUS Adapter zu geben, der mit einer Node-Version >= 12.x klar kommt.

Beispiele an Adaptern (nicht lauffähig):
https://github.com/ISFH/ioBroker.wmbus
https://github.com/soef/ioBroker.wm-bus
https://github.com/iobroker-community-adapters/ioBroker.wm-bus-community

**Comment by ldittmar81** [comment]
https://forum.iobroker.net/topic/21208/test-adapter-wireless-mbus-v0-7-x

@Apollon77 - its latest and can be closed
