### ISSUE TITLE
Skydance Push-Dimmer über Wi-Fi to RF Converter

### ISSUE THREAD

**Issue by throstenk** [ioBroker/AdapterRequests#591]
Hallo ich habe bei mir 10 von den „Push-Dimmer V1“ verbaut 
http://www.iskydance.com/index.php?c=product_show&a=index&id=599

ich kann sie über den „Wi-Fi to RF Converter WiFi-Relay“ mit dem Handy steuern 
http://www.iskydance.com/index.php?c=product_show&a=index&id=810

das geht über die app „SkySmart“
https://play.google.com/store/apps/details?id=com.lxit.wifirelay&hl=de&gl=US

aber leider gibt es noch keinen IObroker Adapter kann mir hier jemand weiterhelfen
Danke Für eure Hilfe 
Lg. Thorsten

**Comment by DutchmanNL** [comment]
Ein Adapter specifisch hierfür ist nicht möglich da es algemein RF ist.

Eventueel per Sonos rf bridge oder broadcom.
Ein Adapter könnte das Protokoll implementieren für den Sender, dies ist für broadcom und sonoff bereits anwesend

**Comment by throstenk** [comment]
die sonoff rf Bridge arbeitet mit 433 Mhz meine Dimmer aber mit 2,4 Ghz das passt nicht ganz zusammen ;-(

**Comment by DutchmanNL** [comment]
> die sonoff rf Bridge arbeitet mit 433 Mhz meine Dimmer aber mit 2,4 Ghz das passt nicht ganz zusammen ;-(

ueber welche Schnittstelle soll es laufen ?

**Comment by throstenk** [comment]
Ich dachte mir über "Wi-Fi to RF Converter WiFi-Relay".
http://www.iskydance.com/index.php?c=product_show&a=index&id=810
ich bin leider noch ein Anfänger ;-)
aber vielleicht gibt es ja eine Möglichkeit
