### ISSUE TITLE
Elgris SmartMeter

### ISSUE THREAD

**Issue by JHA-2021** [ioBroker/AdapterRequests#592]
**What kind of device or service you would like to see an adapter for?**
Add name and company of the device, including links to the device and any additional informations[...]

Elgris SmartMeter LAN/Wifi
https://www.elgris.de/smart-meter/

**Is an official API including documentation is available?**
If yes please add links and informations[...]

It works with Modbus TCP. Values according SunSpec Table 203 (see page 25 ff in the documentation)
https://www.elgris.de/downloads/Smartmeter/SMART%20METER%20Bedienungsanleitung.pdf

**Are other libraries for an integration available?**
Ideally in JavaScript/npm, but also other programming languages are interesting, add Links please

not that I know of, only a general Adapter for ModBus TCP

**Is this device already integrated in other Smart Home systems?**
Add Links please

unknown

**Is this device already integrated in homebridge? Might the ham adapter together with the homebridge plugin be sufficient?**
Please try it and add infos

unknown

**Additional context**
Add any other context or screenshots about the feature request here. If the topic was discussed in ioBroker forum please include the link too.

n/a

After you created the issue vote for yourself in the first post of the issue using the "+1"/"Thumbs up" button

**Comment by Apollon77** [comment]
Why not use the modbus adapter?

**Comment by JHA-2021** [comment]
You are right. There seems to be a bug in the ModBus adapter for IOBroker which gave me a hard time. I figured it out now and can poll the data.

**Comment by Apollon77** [comment]
Ok, can youcreate a bug inmbus or also propose a fix or such?

**Comment by JHA-2021** [comment]
Done.

 

Von: Ingo Fischer ***@***.***> 
Gesendet: Dienstag, 16. März 2021 09:32
An: ioBroker/AdapterRequests ***@***.***>
Cc: JHA-2021 ***@***.***>; Author ***@***.***>
Betreff: Re: [ioBroker/AdapterRequests] Elgris SmartMeter (#592)

 

Ok, can youcreate a bug inmbus or also propose a fix or such?

**Comment by DutchmanNL** [comment]
> You are right. There seems to be a bug in the ModBus adapter for IOBroker which gave me a hard time. I figured it out now and can poll the data.

so I assume we can close this one and work on the bug at modbus ?
