### ISSUE TITLE
BleBox SaunaBox

### ISSUE THREAD

**Issue by Peter213213** [ioBroker/AdapterRequests#593]
**What kind of device or service you would like to see an adapter for?**
Blebox saunabox
https://blebox.eu/product/saunabox/?lang=en

**Is an official API including documentation is available?**
https://technical.blebox.eu/archives/saunaBoxAPI/

**Are other libraries for an integration available?**

**Is this device already integrated in other Smart Home systems?**

**Is this device already integrated in homebridge? Might the ham adapter together with the homebridge plugin be sufficient?**
Please try it and add infos
https://www.npmjs.com/package/homebridge-blebox
Its working fine

**Additional context**

**Comment by ka-vaNu** [comment]
Please have a look at my adapter: https://github.com/ka-vaNu/ioBroker.blebox 

Currently only shutterboxes, switchboxes and tempSensors are supported. I can extend the adapter if needed.

**Comment by ka-vaNu** [comment]
saunabox added. Please have a look at https://github.com/ka-vaNu/ioBroker.blebox

**Comment by ldittmar81** [comment]
@ka-vaNu please plublish it on npmjs :-)

**Comment by ka-vaNu** [comment]
Can be closed as soon as adapter is reviewed. [Pull 1604](https://github.com/ioBroker/ioBroker.repositories/pull/1604)

**Comment by ka-vaNu** [comment]
Version  0.1.2 published on npmjs

**Comment by ldittmar81** [comment]
Its on latest
