### ISSUE TITLE
tv

### ISSUE THREAD

**Issue by michakoblenz** [ioBroker/AdapterRequests#594]
**What kind of device or service you would like to see an adapter for?**
Add name and company of the device, including links to the device and any additional informations[...]

**Is an official API including documentation is available?**
If yes please add links and informations[...]

**Are other libraries for an integration available?**
Ideally in JavaScript/npm, but also other programming languages are interesting, add Links please

**Is this device already integrated in other Smart Home systems?**
Add Links please

**Is this device already integrated in homebridge? Might the ham adapter together with the homebridge plugin be sufficient?**
Please try it and add infos

**Additional context**
Add any other context or screenshots about the feature request here. If the topic was discussed in ioBroker forum please include the link too.

After you created the issue vote for yourself in the first post of the issue using the "+1"/"Thumbs up" button

**Comment by Apollon77** [comment]
This issue has mo content. Please open with more details agai
