### ISSUE TITLE
E3DC

### ISSUE THREAD

**Issue by jhalscheidt** [ioBroker/AdapterRequests#598]
**What kind of device or service you would like to see an adapter for?**
Adapter um Daten aus dem E3DC Hauskraftwerk und der Wallbox auszulesen wäre super. Leider kann ich das nicht selbst machen.
**Is an official API including documentation is available?**
Leider weiß ich das nicht. Es gibt aber ein aktuelles Dokument welches ich als PDF zur Verfügung hab wo die Modbus Schnittstelle erklärt wird. 

**Are other libraries for an integration available?**
Leider weiß ich das nicht. 

**Is this device already integrated in other Smart Home systems?**
Modbus und KNX Integration möglich. Modbus klappt wohl bei FHEM. Ich habe aber keine Ahnung wie man das bedient. 
Laut Gerald5524 auch in openHAB: (https://www.openhab.org/addons/bindings/modbus.e3dc/)

**Is this device already integrated in homebridge? Might the ham adapter together with the homebridge plugin be sufficient?**
Nein. Kein Homebridge meines Wissens nach. 

**Additional context**

**Comment by Apollon77** [comment]
Naja dann: Links und alle Infos die an sich im Issue Template gefragt werden wie Libraries, andere Smarthomesysteme und soweiter wäre schön :-)

**Comment by jhalscheidt** [comment]
Sorry, das Template war bei mir leer nach dem einloggen! Habe es erst später beim zweiten Versuch gesehen dass es da was gab. leider bin ich kein Entwickler und habe überhaupt keine Ahnung wo ich sowas finden soll. Wenn das ohne die Daten nicht geht, dann bitte löschen. Ich bin damit überfordert. 

https://www.e3dc.com/#Intro

**Comment by Apollon77** [comment]
Na der Linkt ist doch schonmal ein Anfang :-)

**Comment by Gerald5524** [comment]
Is this device already integrated in other Smart Home systems?
Ja, in openHAB über Modbus/Ethernet. Das funktioniet dort auch einwandfrei. Ist dort auch gut dokumentiert.
(https://www.openhab.org/addons/bindings/modbus.e3dc/)

Is an official API including documentation is available?
https://docplayer.org/130115062-Modbus-tcp-schnittstelle-der-e3-dc-gmbh.html

Habe leider keine Erfahrung mit Adapterschreiben, würde aber gerne diesen Request unterstützen.
Zurzeit bin ich mich erstmal mit ioBroker am Einarbeiten.

**Comment by DutchmanNL** [comment]
> https://docplayer.org/130115062-Modbus-tcp-schnittstelle-der-e3-dc-gmbh.html

fuer modbus integration haben wir doch den Modus Adapter ?

**Comment by Gerald5524** [comment]
Danke, werde ich mir ansehen. Leider erst nach dem 26.3. Dann aber werde ich meine Erfahrungen teilen.

**Comment by jhalscheidt** [comment]
> > https://docplayer.org/130115062-Modbus-tcp-schnittstelle-der-e3-dc-gmbh.html
> 
> fuer modbus integration haben wir doch den Modus Adapter ?

Ja. Den habe ich mal ausprobiert. Geht in Teilen, manche Datentypen werden aber scheinbar nicht unterstützt. Probiere noch weiter und werde berichten.

**Comment by Gerald5524** [comment]
So, hier nun meine Erkenntnisse.
Habe aus den Dokumentationen mir meine Register konfiguriert und die Datentypen per Ausprobieren gefunden.
Bis auf die Wallbox und die externe Quelle habe ich die gelisteten Werte mit meinem Hauskraftwerk überprüfen können und die Werte stimmen.

```
deviceId	address	name	description	unit	type	len	factor	offset	formula	role	room	poll	wp	isScale
1	40001	modbus-id	Magicbyte –S10 ModBus ID (Immer 0xE3DC)		uint16be	1	1	0		value		true	false	false	
1	40002	modbus-firmware	S10 ModBus-Firmware-Version		uint16be	1	1	0		value		true	false	false	
1	40003	supported-registers	Anzahl unterstützter Register		uint16le	1	1	0		value		true	false	false	
1	40004	manufacturer-name	Hersteller: „E3/DC GmbH"		string	16	1	0		value		true	false	false	
1	40020	model-name	Modell		string	16	1	0		value		true	false	false	
1	40036	serial-number	Seriennummer		string	16	1	0		value		true	false	false	
1	40052	firmware-release	S10 Firmware Release		string	16	1	0		value		true	false	false	
1	40068	pv-power-supply	Photovoltaik-Leistung in Watt		int32sw	2	1	0		value		true	false	false	
1	40070	battery-power	Batterie-Leistung in Watt(negative Werte = Entladung)		int32sw	2	1	0		value		true	false	false	
1	40072	household-power-consumption	Hausverbrauchs-Leistung in Watt		uint32sw	2	1	0		value		true	false	false	
1	40074	grid-power-consumption	Leistung am Netzübergabepunkt in Watt (negative Werte = Einspeisung)		int32sw	2	1	0		value		true	false	false	
1	40076	external-power-supply	Leistung aller zusätzlichen Einspeiser in Watt		int32sw	2	1	0		value		true	false	false	
1	40078	wallbox-power-consumption	Leistung der Wallbox in Watt		int32sw	2	1	0		value		true	false	false	
1	40082	autarky	Autarkie und Eigenverbrauch in Prozent		uint8be	1	1	0		value		true	false	false	
1	40083	battery-soc	Batterie-SOC in Prozent		uint16be	1	1	0		value		true	false	false	

```
Sollte man so per copy&paste übernehmen können.

Offene Frage wäre: Gibt es einen Platz für solche Konfigurationen? Das muss ja nicht jeder für sich selbst herausfinden müssen. 

Zu den Datentypen: Das Zauberwort heißt "...Swap" - die wurden wohl eigens wegen E3DC in Modbus eingebaut.

**Comment by DutchmanNL** [comment]
> Offene Frage wäre: Gibt es einen Platz für solche Konfigurationen? Das muss ja nicht jeder für sich selbst herausfinden müssen.

hm, docu vom modbus adapter ?
Ich mache den request dan mal zu, danke fürs teilen der config :)

**Comment by jhalscheidt** [comment]
Danke Gerald. 
Ich würde den Fall trotzdem nicht als geschlossen sehen. Es gibt zwar die Möglichkeit über Modbus, denke aber dass die E3DC Community groß ist und größer wird. Daher wäre ein eigener Adapter wünschenswert. Aus diesem Grund habe ich den request ja gestellt.

**Comment by jhalscheidt** [comment]
@DutchmanNL : Die Community wächst und wächst. Wie schon gesagt es gibt einen Modbus Adapter, den nicht jeder gut bedienen kann. Trotzdem wäre ein eigener E3DC Adapter schön. Würde den Fall daher bitte wieder öffnen. 
Für SMA gibt es auch einen eigenen Adapter obwohl SMA auch über Modbus ginge.

**Comment by UncleSamSwiss** [comment]
> Modbus Adapter, den nicht jeder gut bedienen kann.

@jhalscheidt im Modbus Adapter ist geplant, komplette "Gerätekonfigurationen" zu haben (siehe Link unten). Damit ist aus meiner Sicht dieser Request abgedeckt.

@Gerald5524 Kannst du bitte deine Erkenntnisse im folgenden Forumsthema teilen: https://forum.iobroker.net/topic/44510/aufruf-sammlung-an-modbus-anbindungen

**Comment by jhalscheidt** [comment]
@UncleSamSwiss 
ModBus kann aus dem E3DC leider nicht alles rausholen was geht. Wie zum Beispiel die Temperaturen, die für eine eventuelle Klimatisierung/Heizung hilfreich wären. Das geht aber per RSCP. Daher bin ich trotzdem der Meinung, dass der Adapter notwendig ist. Ich würde ihn selbst machen wenn ich das könnte. Leider kann ich nur SPS Steuerungen programmieren...
