### ISSUE TITLE
Elero USB Transmitter zur Rolladensteuerung (Elero/Weinor) Adapter

### ISSUE THREAD

**Issue by steckenpferd** [ioBroker/AdapterRequests#60]
Hallo,

mit dem Elero USB Transmitter lassen sich bis zu 15 Rolläden steuern.
Ich stelle gerne meinen Stick zu Testzwecken bereit

![grafik](https://user-images.githubusercontent.com/39061622/39712225-8ba3d858-5222-11e8-903a-2251e9e2355b.png)

Es gibt schon Lösungen für Homematic, Home Assitant, FHEM und Openhab - vielleicht könnte ein fähiger Entwickler daraus einen Adapter für ioBroker basteln.

Mehr Infos s.
https://forum.iobroker.net/viewtopic.php?f=35&t=9663

**Comment by steckenpferd** [comment]
Ich habe 2 Interessante Lötlösungen gefunden um die unidirektionalen Geräte zu steuern:

Elero Fernbedienung an HM-MOD-Re-8:
https://forum.fhem.de/index.php/topic,3 ... #msg298170

Elero Fernbedienung an ESP32 WROOM Dev Board:
https://forum.fhem.de/index.php/topic,90169.0.html

**Comment by TobiasBST** [comment]
@steckenpferd binding is available in latest snapshot release

**Comment by steckenpferd** [comment]
@TobiasBST - I guess with binding you mean Openhab? 
https://www.openhab.org/addons/bindings/elerotransmitterstick/

There is also Home Assistant solution already available:
https://github.com/W00D00/home-assistant-elero

ioBroker not yet I guess.

**Comment by Negalein** [comment]
gibt es schon News zum Stick in ioBroker?

**Comment by GeneralTweety** [comment]
Mich würde das Thema auch interessieren. Ich habe eine Notlösung erstellt und greife mit dem Openhab Adapter von Iobroker auf einen extra Opbenhab Server zu. Der Openhab Server steuert ausschließlich die Elero Rollläden und ich würde mir diesen extra Server gerne sparen. 

Ich wäre jedem sehr dankbar, der uns hier Unterstützen könnte. Ich stelle mich auch gerne bereit zum Testen.

Danke Euch

**Comment by steckenpferd** [comment]
GeneralTweety - nette von hinten durch die Brust Lösung :-) Leider bisher kein Entwickler gefunden der hier helfen möchte

**Comment by Negalein** [comment]
Ich schmeiss jetzt diese doofen extrem überteuerten Elero-Motoren raus und kauf mir ganz normale Rohrmotoren.
Dann geht HM, HMIP, Shelly, usw.!

**Comment by seb2010** [comment]
Hallo zusammen,
ich bin leider ein paar Wochen zu spät auf den ioBroker-Zug aufgesprungen, so dass ich mich erst jetzt für den Funkmotoren-Typ meiner neuen Raffstoreanlage interessiere. Es sind Eloro-Motoren, so dass ich nun Leidensgenosse bin. Gibt es hier schon ein Update?
Wenn nein, ist das so ein großer Aufwand die Home-Assistant etc. -Projekte hierzu auf ioBroker zu portieren? Die Codes, Typen und Kommunikationsprozesse kann man sich dort schön abschauen. Ich bin kurz davor es selbst mal zu versuchen...

**Comment by kentbrock** [comment]
Hi, ich hätte auch sehr starkes Interesse an einem Elero Rolladen Adapter. Ich betreibe FHEM und ioBroker auf einem Pi. FHEM brauche ich eigentlich nur noch für die Elero Rollos. Ich kann leider auch nicht programmieren... ich biete mich aber gern zum testen an :-)

**Comment by seb2010** [comment]
Hallo zusammen,
mangels USB-Stick habe ich nun eine, wie ich finde, bessere Lösung gefunden:
Elero bietet selbst eine Centero-Zentralsteuerung an. Wie ich erfahren habe, ist das jedoch nur ein auf Elero gebrandeter Mediola Gateway. Diese Mediola Gateways können mit seeeeehr vielen Protokollen umgehen und haben unter anderem eben auch 433MHz und 868MHz Funkoptionen. Ein nackter V5 Gateway kostet neu 79,-€, gebraucht gibt es sie auch manchmal. Das einlernen war dann so einfach wie bei einer Fernbedienung für die Elero-Motoren und man kann sie ganz einfach per Web-API (http://api.mediola.com/v5/login, anmelden kann sich dafür jeder) mit ganz einfachen Befehlen für hoch/runter/stop etc ansprechen.
So habe ich jetzt die Raffstore-Motoren eingebunden und konnte gleichzeitig noch die restlichen Somfy-RTS Motoren integrieren, für die ich sonst auch noch einen 433MHz Gateway benötigt hätte.
Viele Grüße

**Comment by steckenpferd** [comment]
@seb2010 Frage zu Mediola V5, brauchst du nicht erst das Mediola Plugin für Elero kaufen? Leider gehen laut deren Webseite keine unidirektionalen Geräte - verstehe nicht warum.

**Comment by seb2010** [comment]
Hallo @steckenpferd, ich dachte auch, dass man das ioBroker-Plugin braucht. Ist aber nicht der Fall, die Web-API ist offen und kann (zumindest für meine Zwecke) benutzt werden. Du kannst damit Stati von Sensoren auslesen und Befehle an Geräte senden. unidirektional (also in eine Richtung) tut es schonmal mit Elero und Somfy RTS. Ich sehe als Stati auch verschiedene Zustände der Motoren (obere Endlage, fährt runter etc.), wenn per API geschaltet wurde. Wenn ich zwischendurch mit der Fernbedienung schalte tut es das aber nicht. Bin mir nicht sicher ob die Zustände echt gelesen oder nur berechnet werden.
So wie ich das sehe ist das Mediola ioBroker-Plugin nicht für das Einbinden des Mediola Gateway in ioBroker, sondern andersherum für das Einbinden von ioBroker in den iQontrol NEO Apps. Damit zieht sich Mediola ja das Geld rein.

**Comment by michihorni** [comment]
Moin
ich habe das mit dem Elero-Stick über meine Raspberrymatic  [realisiert.](https://homematic-forum.de/forum/viewtopic.php?f=37&t=26066&hilit=elero&start=20) Die Steuerung erfolgt dann über den Iobroker.

**Comment by steckenpferd** [comment]
@seb2010 also ich hatte den Elero USB Stick aber der konnte keine Elero unidirektionalen (Elero Revio 868 mit der Version 28400.0001) verbinden. 

Bist du Sicher 1. das die alten Unidirektionalen Geräte gehen und 2. das auf dem Mediola V5 Gateway kein Elero Plugin gebraucht wird.

**Comment by seb2010** [comment]
achso, also ob der Stick kein unidirektional kann weiß ich nicht. Solange der sendet, müsste man den doch auch irgendwie das Richtige senden lassen können. Vor allem wenn man low-level Befehle sendet.
Und den Gateway habe ich wie gesagt seit einer Woche im Einsatz und der kann meine JA-Comfort 868 steuern. Das war wirklich alles sehr einfach zu realisieren.

**Comment by sc83ge** [comment]
Hat jemand Erfahrungen mit elero centero in Kombination mit HomematicIP? Ich bekomme keine Verbindung hergestellt

**Comment by marc2016** [comment]
Hallo zusammen,

die Anfrage ist zwar schon etwas älter, aber ich habe auch Bedarf an so einem Adapter und würde ihn entwickeln oder dabei unterstützen. Scheinbar wurde hier https://github.com/seb2010/iobroker.elero schonmal damit angefangen. @seb2010 Ist das Projekt noch aktiv und hat es funktioniert?
Welche Hardware ist dafür zu empfehlen, der Elero Stick, Mediola Gateway oder vielleicht mit einem nanoCUL?

**Comment by seb2010** [comment]
Hi @marc2016,
das Projekt habe ich nicht weiterverfolgt, nachdem ich Mangels Hardware nicht weiter machen konnte. Da der Mediola Gateway v5 (den ich nun zur Steuerung benutze) sogar günstiger war als der Stick, habe ich es liegen lassen. 
Vielleicht nochmal zur Klarstellung:
- mit dem Elero Stick KÖNNTE man über den hier übersetzeten Adapter evtl. die Steuerung realisieren. Die Übersetzung des Elero-Adapters müsste einigermaßen vollständig sein, es steht aber vermutlich noch Feinarbeit an.
- mit dem Mediola Gateway hättest du eine Lösung ohne diesen Adapter hier, bei der du erstens eine gute Bandbreite an Funkfrequenzen und den zugehörigen Protokollen der Hersteller (wie hier eben RTS, https://www.mediola.com/checkliste) ansteuern kannst. Den Gateway selbst steuerst du dann mit API-Befehlen über eine HTTP-Schnittstelle. Das könnte man dann noch in einen Adapter verpacken, aber da die theoretisch ansprechbaren Geräte viel zu viele sind, wird man es hier mit einer Vereinheitlichung schwer haben. Ablauf ist: Anlernen der Geräte per App und dann steuern der Geräte per ioBroker-Skript über die lokale Web-API des Gateways.

Ich bin letztendlich bei dem Adapter gelandet, weil ich dachte, ich binde mir noch 433Mhz oder 868Mhz Schalter und Sensoren ein. Dazu kam es aber bisher nicht 😆

**Comment by kentbrock** [comment]
Ich selber hab den Elero Stick in Verbindung mit FHEM seit 4 Jahren im Einsatz. Ich bin sehr interessiert an einem Adapter für den IoBroker - biete mich gern als Tester an. :-)

**Comment by sc83ge** [comment]
Ich habe auf den v5+ gesetzt. Dort klappt die Einbindung der Elero Motoren gut. Nur ist mein Haus zu groß und es können nicht alle Motoren eingebunden werden. Jetzt stehe ich vor der Frage, ob ich einen zweiten v5+ einbinde, aber nur um die Elero Beschränkung zu umgehen, ist das ärgerlich und überteuert. Hat jemand eine Idee oder es anders gelöst?

**Comment by kentbrock** [comment]
Also mit dem Stick komme ich bei mir aus dem Keller durch zwei Stahlbetondecken bis ins 1.OG. Ich glaub ich hab mal gelesen, dass die Rollos ein Mesh aufmachen. Damit hatte ich mir die Reichweite immer erklärt.

**Comment by seb2010** [comment]
> Ich habe auf den v5+ gesetzt. Dort klappt die Einbindung der Elero Motoren gut. Nur ist mein Haus zu groß und es können nicht alle Motoren eingebunden werden. Jetzt stehe ich vor der Frage, ob ich einen zweiten v5+ einbinde, aber nur um die Elero Beschränkung zu umgehen, ist das ärgerlich und überteuert. Hat jemand eine Idee oder es anders gelöst?

Wenn du es dich traust, kannst du dem v5+ eine größere Antenne verpassen

**Comment by sc83ge** [comment]
> > Ich habe auf den v5+ gesetzt. Dort klappt die Einbindung der Elero Motoren gut. Nur ist mein Haus zu groß und es können nicht alle Motoren eingebunden werden. Jetzt stehe ich vor der Frage, ob ich einen zweiten v5+ einbinde, aber nur um die Elero Beschränkung zu umgehen, ist das ärgerlich und überteuert. Hat jemand eine Idee oder es anders gelöst?
> 
> Wenn du es dich traust, kannst du dem v5+ eine größere Antenne verpassen

Die Reichweite ist im ganzen Haus überhaupt kein Problem. Eher das Problem, dass die Mediola-Box bei 15 Elero Motoren dicht macht und ich keine Möglichkeit habe, mehrere Motoren auf einen Kanal zu belegen...

**Comment by marc2016** [comment]
> Hi @marc2016,
> das Projekt habe ich nicht weiterverfolgt, nachdem ich Mangels Hardware nicht weiter machen konnte. Da der Mediola Gateway v5 (den ich nun zur Steuerung benutze) sogar günstiger war als der Stick, habe ich es liegen lassen.
> Vielleicht nochmal zur Klarstellung:
> 
> * mit dem Elero Stick KÖNNTE man über den hier übersetzeten Adapter evtl. die Steuerung realisieren. Die Übersetzung des Elero-Adapters müsste einigermaßen vollständig sein, es steht aber vermutlich noch Feinarbeit an.
> * mit dem Mediola Gateway hättest du eine Lösung ohne diesen Adapter hier, bei der du erstens eine gute Bandbreite an Funkfrequenzen und den zugehörigen Protokollen der Hersteller (wie hier eben RTS, https://www.mediola.com/checkliste) ansteuern kannst. Den Gateway selbst steuerst du dann mit API-Befehlen über eine HTTP-Schnittstelle. Das könnte man dann noch in einen Adapter verpacken, aber da die theoretisch ansprechbaren Geräte viel zu viele sind, wird man es hier mit einer Vereinheitlichung schwer haben. Ablauf ist: Anlernen der Geräte per App und dann steuern der Geräte per ioBroker-Skript über die lokale Web-API des Gateways.
> 
> Ich bin letztendlich bei dem Adapter gelandet, weil ich dachte, ich binde mir noch 433Mhz oder 868Mhz Schalter und Sensoren ein. Dazu kam es aber bisher nicht 😆

Danke für die ausführliche Antwort :-) Die Box scheint universell einsatzbar zu sein. Sind dort noch irgendwelche versteckten Kosten zu brachten durch einen Service des Herstellers?
Leider finde ich auch nur noch das Modell V6. Die Box V6 Mini ist für unter 100€ zu haben. Die Box V6 kostet schon fast 200€. Welche Version ist zu empfehlen?

**Comment by marc2016** [comment]
Den Stick scheint man nicht mehr überall kaufen zu können. Zumindest habe ich nur einen Anbieter gefunden: https://www.der-sonnenschutz-shop.de/elero-221250001-centero-transmitter-stick.html
Bekommt man den noch woanders her?

**Comment by sc83ge** [comment]
Man muss wissen, was man will. Wenn man sowohl 433 als auch 868 mhz nutzen will, kommt wohl nur die v5+ Box in Frage...

**Comment by seb2010** [comment]
Die v5 ohne plus kann auch beide Funkfrequenzen. Die Version ist jedoch leider nur noch gebracht zu erwerben. Ob das die neueren Modelle noch mit Kosten daherkommen kann ich nicht sagen. Das Geschäftsmodell für die App von Mediola basiert jedenfalls auf dem Zukauf von "Plugins" um Funktionen freizuschalten. Die v5 konnte man noch mit einer hässlichen aber freien IQntrol-App anlernen und dann per API anzapfen.
Auf erstere Pferd sind aber ja jetzt auch jetzt viele Hersteller aufgesprungen und verabschieden sich vom RTS Funk. Die kommen ja jetzt alle mit geschlossenen Protokollen und ihrem eignen Gateway daher um dich auf deren "Cloud"-System zu locken.

**Comment by marc2016** [comment]
Ich habe mir gerade den elero Stick bestellt und werde dann auf die Implementierung von @seb2010 aufsetzen. Ich werde mich nochmal melden, wenn es was neues gibt. Vielen Dank an alle für die Infos :-)

**Comment by marc2016** [comment]
Mittlerweile habe ich hier https://github.com/marc2016/elero-usb-transmitter-client einen node.js Client geschrieben, über dem man mit dem USB Stick kommunizieren kann. 
Und hier ist der aktuelle Stand des Adapters zu finden https://github.com/marc2016/ioBroker.elero-usb-transmitter .
Der ist aber noch nicht fertig.

**Comment by marc2016** [comment]
Hallo zusammen,

der Adapter hat jetzt einen funktionsfähigen Stand. Es gibt allerdings noch ein paar Probleme:

- die Kommunikation funktioniert nicht immer zuverlässig. Ich habe versucht dies an den entsprechenden Stellen abzufangen, aber manchmal stürzt der Adapter ab.
- Bei mir funktionieren die Commands ventilationPosTilting und intermediatePos nicht. Die Rolladen gehen entweder komplett auf oder komplett zu. Vielleicht kann jemand dies bei sich testen.
- Ich wollte gerne einen Level State implementieren. Meine Idee ist, dies anhand der Laufzeit zu machen. Das heißt, der Adapter misst die Laufzeit (siehe Einstellungen) und dann wird dies für das Level der Rolllade verwendet (bei 50% nur die Hälfte der Laufzeit). Leider ist das nicht sehr genau. Evtl. hat jemand eine bessere Idee.

**Comment by michihorni** [comment]
Hallöchen

gerne möchte ich Deinen Adapter testen. Bislang mache ich die Steuerung über den Umweg mittels CuXD. 

In meiner Umsetzung im Iobroker arbeite ich auch über Laufzeit. Ist nur individuell von Behang Größe zum Behang Größe.

Wie soll der Stick im Adapter eingetragen werden. bei mir im CuxD steht er wie folgt: 
/dev/ttyUSB0


Mit freundlichen Grüßen
Michael Horn

 
 

Gesendet: Freitag, 04. Dezember 2020 um 20:33 Uhr
Von: "marc2016" <notifications@github.com>
An: "ioBroker/AdapterRequests" <AdapterRequests@noreply.github.com>
Cc: "michihorni" <michaelhorn@web.de>, "Comment" <comment@noreply.github.com>
Betreff: Re: [ioBroker/AdapterRequests] Elero USB Transmitter zur Rolladensteuerung (Elero/Weinor) Adapter (#60)


 

Hallo zusammen,

der Adapter hat jetzt einen funktionsfähigen Stand. Es gibt allerdings noch ein paar Probleme:


	die Kommunikation funktioniert nicht immer zuverlässig. Ich habe versucht dies an den entsprechenden Stellen abzufangen, aber manchmal stürzt der Adapter ab.
	Bei mir funktionieren die Commands ventilationPosTilting und intermediatePos nicht. Die Rolladen gehen entweder komplett auf oder komplett zu. Vielleicht kann jemand dies bei sich testen.
	Ich wollte gerne einen Level State implementieren. Meine Idee ist, dies anhand der Laufzeit zu machen. Das heißt, der Adapter misst die Laufzeit (siehe Einstellungen) und dann wird dies für das Level der Rolllade verwendet (bei 50% nur die Hälfte der Laufzeit). Leider ist das nicht sehr genau. Evtl. hat jemand eine bessere Idee.

**Comment by marc2016** [comment]
HI Michael,

sehr schön :-) In dem Textfeld muss der Pfad zu dem Gerät eingetragen werden. Bei mir ist das auch /dev/ttyUSB0, sollte also richtig sein. Vielen Dank für das Testen! Ich habe mir jetzt auch das erste Typescript angelegt und schaue mal, wie es läuft.

Viele Grüße
Marc

**Comment by michihorni** [comment]
Ich nutze allerdings Iobroker auf einer Windows Umgebung, das würde bedeuten, das der Elero-Stick an einem COM-Port angeschlossen werden muss. Wie würde dann der Geräte Pfad aussehen?
 

Mit freundlichen Grüßen
Michael Horn

 
 

Gesendet: Freitag, 04. Dezember 2020 um 21:14 Uhr
Von: "marc2016" <notifications@github.com>
An: "ioBroker/AdapterRequests" <AdapterRequests@noreply.github.com>
Cc: "michihorni" <michaelhorn@web.de>, "Comment" <comment@noreply.github.com>
Betreff: Re: [ioBroker/AdapterRequests] Elero USB Transmitter zur Rolladensteuerung (Elero/Weinor) Adapter (#60)


 

HI Michael,

sehr schön :-) In dem Textfeld muss der Pfad zu dem Gerät eingetragen werden. Bei mir ist das auch /dev/ttyUSB0, sollte also richtig sein. Vielen Dank für das Testen! Ich habe mir jetzt auch das erste Typescript angelegt und schaue mal, wie es läuft.

Viele Grüße
Marc

**Comment by marc2016** [comment]
Intern wird https://serialport.io/ genutzt. Dort habe ich gerade ein Beispiel gesehen, bei dem "COM5" eingetragen wurde.
https://gist.github.com/maximilian-lindsey/b5a981d3657627bfbb89
`var serialPort = new SerialPort("COM5", {
	baudrate: 9600
}, false);`

Du könntest einmal testen, ob die Serialport Commandline Tools funktionieren und ob der Stick dort aufgelistet wird. Gib dazu folgendes in die Kommandozeile von Windows ein: npx @serialport/list
Hier die Erläuterung dazu: https://serialport.io/docs/guide-cli

**Comment by Gukerl** [comment]
Vielen DANK für Deine Mühe! Anfang nächsten Jahres werden bei mir auch Elero Rollläden installiert, samt Handsendern, die bekomme ich dazu.
Ich will nur "in der Früh rauf und am Abend runter". Die Lösung mit dem Stick oder das Mediola Gateway V5? Ich verwende eine CCU2 und einen ioBroker auf einem Raspi 4. 
Über das Gateway klingt das ziemlich einfach, umgesetzt in JS. Die Funktion der Handsender muss aber weiterhin gegeben sein, das ist für den WAF wichtig (woman acceptance factor) ;)

**Comment by marc2016** [comment]
Ich muss sagen, dass ich den Stick nicht als optimale Lösung empfinde. Es werden manchmal Befehle verschluckt und es gibt keine Prozenteinstellung. Leider kenne ich die Alternativen nicht.

Für mich ist der Stick trotzdem in Ordnung, weil ich bereits zwei Elero Rollladen habe, der Stick nicht so teuer ist und ich etwas basteln wollte ;-) Für "Rauf und Runter" reicht es auf jeden Fall und funktioniert bei mir seit ein paar Tagen zuverlässig.

**Comment by appi1** [comment]
Ich habe den Elerostick und habe 19 Rolladen, ich muss mehrere Rollladen grupieren auf einzelnen Kanälen, etwas schwierig die dass nur 15 Kanäle möglich sind.
Zudem will ich wine Lan Lösung, Server ist im Keller.
Der Ansatz von QuadCore85 gefällt mir deshalb sehr gut.
Bin gespannt ob ich damit weiter komme.

**Comment by QuadCorei8085** [comment]
theoretisch wäre möglich. du brauchst ein esp32 oder arduino dazu mit CC1100/cc1101 radio vom TexasInstruments.
oder ähnliches radio damit du die geforderte modulation erstellen könntest.

ich habe nur den protocol "encryption" herausgefunden.
Ich habe mein fernsteuer (variotel 2) "MAC addresse" aufegenommen und mit 1-2 botschaften du könntent die rolladen steuern.
Also für jede gekoppelte variotel2<->rolladen du brauchst die MAC addresse vom die variotel2.

Danach ein 
"auf" kommando is "HOCH_TASTEN_DRUCK + 200ms pause + HOCH_TASTEN_WEGLASSEN"
Stop is einfach 1 botschaft.
"unten" ist auch "UNTEN_TASTEN_DRUCK + 200ms pause + UNTEN_TASTEN_WEGLASSEN"

Für MAC addresse du könntest den radio traffic "sniffen" (keine ahnung wie sagt man das auf deutsch) die siehst dass ein variotel immer schickt die gleiche botschafte 3x nach einander.

**Comment by appi1** [comment]
thank you for your answer. i ordered the CC1101 today and after my hollydays i will make some tests and give you a feedback on your project on github.

**Comment by ldittmar81** [comment]
@marc2016  Please request repo addition ... details see https://github.com/ioBroker/ioBroker.repositories

**Comment by marc2016** [comment]
@ldittmar81 the adapter is still unstable. I'll try to fix that in the next few days. then I make a request.

**Comment by PackElend** [comment]
> i ordered the CC1101 today and after my hollydays i will make some tests and give you a feedback on your project on github.

have you been successful?

**Comment by michihorni** [comment]
It works fine
 

Mit freundlichen Grüßen
Michael Horn

 
 

Gesendet: Donnerstag, 03. Februar 2022 um 12:03 Uhr
Von: "PackElend" ***@***.***>
An: "ioBroker/AdapterRequests" ***@***.***>
Cc: "michihorni" ***@***.***>, "Comment" ***@***.***>
Betreff: Re: [ioBroker/AdapterRequests] Elero USB Transmitter zur Rolladensteuerung (Elero/Weinor) Adapter (#60)


 


i ordered the CC1101 today and after my hollydays i will make some tests and give you a feedback on your project on github.


have you been successful?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by PackElend** [comment]
> It works fine

can we see your built somewhere?

**Comment by christianjungwirth** [comment]
Hallo,
does anybody know, where i can get those elero transmitter stick from?
in all shops, which i found this stick, they said "not in stock, no longer produced".

Is there any alternative? 

Elero sells his centero gateway, but this is a little to expensive for me, and ther is also no binding for openhab.

**Comment by seb2010** [comment]
I just can point you into the direction of an "Mediola Gateway" as stated above. It does the job here for some time now

**Comment by QuadCorei8085** [comment]
Or you build your own using esp32 and a cc1101 following the code on my repo.

**Comment by christianjungwirth** [comment]
@seb2010 but the problem is, that i could no binding for open hab, so i had to host 2 smarthome systems. Or did I just overlook that there is one?

@QuadCorei8085 but when i want to use my MultiTel2 too, does the 2 systems get the actual positions of the raffstores?

**Comment by QuadCorei8085** [comment]
No the code only shows how to send messages, The protocol isnt reverse engineered, no data with the multitel2 and raffstores. But my guess is it is in the messages we just need data to analyse.

**Comment by seb2010** [comment]
> @seb2010 but the problem is, that i could no binding for open hab, so i had to host 2 smarthome systems. Or did I just overlook that there is one?

The gateway does have an Webservic API where you can
- get current States with: http://?.?.?.?/cmd?XC_FNC=getStates
- send status (like "up" and "down" or "doubledown" with: http://?.?.?.?/cmd?XC_FNC=SendSC&type=ER&data='+channel+cmdcode
For the latter "ER" is "Elero", "channel" is the channel of the motor it receives on and "cmdcode" the Command-Code like "01" for "up".

I can paste my code here if you want for ioBroker though (javascript to write and react on Object-States).

The Gateway can also send UDP broadcasts for other appliance states it receives. For instance some 433 MHz communication)

**Comment by DutchmanNL** [comment]
> > @seb2010 but the problem is, that i could no binding for open hab, so i had to host 2 smarthome systems. Or did I just overlook that there is one?
> 
> 
> 
> The gateway does have an Webservic API where you can
> 
> - get current States with: `http://?.?.?.?/cmd?XC_FNC=getStates`
> 
> - send status (like "up" and "down" or "doubledown" with: `http://?.?.?.?/cmd?XC_FNC=SendSC&type=ER&data='+channel+cmdcode`
> 
> For the latter "ER" is "Elero", "channel" is the channel of the motor it receives on and "cmdcode" the Command-Code like "01" for "up".
> 
> 
> 
> I can paste my code here if you want for ioBroker though (javascript to write and react on Object-States).
> 
> 
> 
> The Gateway can also send UDP broadcasts for other appliance states it receives. For instance some 433 MHz communication)

Is there Amy documentation available about this api?

**Comment by motorcross3973** [comment]
Hi @marc2016,

I found your repository for the iobroker elero adapter. Is it as this point possible to use your implemented adapter.
And if yes, how can I configure it?

**Comment by mcm1957** [comment]
Adapter available at latest repository.

Please create issues or feture requests at adpter directory (https://github.com/ioBroker/ioBroker.repositories)

**Comment by stanleypa** [comment]
I took the great work done by [QuadCorei8085](https://github.com/QuadCorei8085) and made a python based remote control emulator that can run on and esp32 or a Raspberry Pi and uses mqtt as to accept commands and report statuses. It also uses the cc1101 module but should be modular enough to replace that with a different module if someone wants to.

**Comment by mcm1957** [comment]
Adapter available at latest repository.

Please create issues or feture requests at adapter directory (https://github.com/marc2016/ioBroker.elero-usb-transmitter)

**Comment by lomion0815** [comment]
> I took the great work done by [QuadCorei8085](https://github.com/QuadCorei8085) and made a python based remote control emulator that can run on and esp32 or a Raspberry Pi and uses mqtt as an interface to accept commands and report statuses. Thus it should be usable to interface with most opensourced home automation systems. It also uses the cc1101 module but should be modular enough to replace that with a different module if someone wants to.
> 
> https://github.com/stanleypa/eleropy

I adapted stanleypas code to support ESP8266 SoC chips used in NodeMCU and other boards. Thanks for your great work!

This fork can be found [here](https://codeberg.org/lomion/eleropy) on Codeberg.

Additionally I wrote a german [description](https://www.sarkasti.eu/articles/de/post/elero/) about how to program such a transceiver.

**Comment by mlinko6** [comment]
Does someone need the Elero Centero USB Stick? Have one to sell from Austria.

KR
Rok

**Comment by zupdaz** [comment]
Hi, Thanks to marvelous work of @QuadCorei8085 and @stanleypa I have managed to control my Elero blinds with RasPi and E07-M1101D. 

In addition, I would like to control my pergola which also operates at 868 MhZ and uses Teleco Automation remote TVNOON868xxx v1.2. I was naive enough to think I can just use cc1101.py from stanlepa's repo to sniff Teleco's commands but I get no commands printed.

Can you offer me some tips how do I need to change cc1101 code to be able to sniff Pergola's traffic. I am getting my RTL-SDR in a week so I will now more about operation of Teleco after that.

**Comment by Darklirah** [comment]
Hi ther,

does anyone know wher to get this stick solo?
And is this MEDIOLA AIO Gateway V5 also useful for controlling the shutters?
cheers Franky

**Comment by DjGreg7Home** [comment]
> Does someone need the Elero Centero USB Stick? Have one to sell from Austria.
> 
> KR Rok

Hi, yes I am looking and am also Germany Please contact me.
