### ISSUE TITLE
Heidelberg Wallbox Energy Control via Modbus

### ISSUE THREAD

**Issue by josefholdschick** [ioBroker/AdapterRequests#601]
Hallo Zusammen!!!
	
Ich bin seit kurzem begeisterter ioBroker-Nutzer.
Ich würde gerne meien neue Heidelberg Wallbox Energy Control via Modbus einbinden. Leider klappt das mit dem Modbus-Adapter nicht wirklich.
Unter euch gibt es sicher sehr sehr gute Programmierer, die einen Adapter für die Wallbox schreiben können. Wäre jemand dazu bereit oder hätte Interesse?

Vielen Dank!

Hello everyone!!!
	
I have recently become an enthusiastic ioBroker user.
I would like to integrate my new Heidelberg Wallbox Energy Control via Modbus. Unfortunately, this doesn't really work with the Modbus adapter.
I'm sure there are very good programmers among you who can write an adapter for the wallbox. Would anyone be willing or interested?

Thank you very much!

> *created by ioBroker.info*

**Comment by Apollon77** [comment]
> Leider klappt das mit dem Modbus-Adapter nicht wirklich.

Warum?

**Comment by Apollon77** [comment]
Please add links to docs and all such stuff

**Comment by kahuwi14** [comment]
Hey there.

> Warum?
that depends on the [Issue #77](https://github.com/ioBroker/ioBroker.modbus/issues/77#issuecomment-792638061).
The wallbox requires "write only"-registers to be controlled.

> die einen Adapter für die Wallbox schreiben können. Wäre jemand dazu bereit oder hätte Interesse?
If that Issue would be fixed, I would be able to test some stuff and could help to improve the evcc-project.

**Comment by josefholdschick** [comment]
Ich kapier das Vorgehen mit den Registern einfach nicht. Ich beschäftige mich auch erst zu kurz damit. Vielleicht liegt es auch an meinem USB-Modbus-Adapter der am Raspi angesteckt ist.
Es wäre einfach toll, wenn es einen "fertigen" Adapter gäbe. Ich muss es jetzt leider so Leihenhaft sagen.

Danke!

**Comment by DutchmanNL** [comment]
> Ich kapier das Vorgehen mit den Registern einfach nicht. Ich beschäftige mich auch erst zu kurz damit. Vielleicht liegt es auch an meinem USB-Modbus-Adapter der am Raspi angesteckt ist.
> Es wäre einfach toll, wenn es einen "fertigen" Adapter gäbe. Ich muss es jetzt leider so Leihenhaft sagen.
> 
> Danke!

ein fertiger adapter wuerde die koplixitaet nicht wirklich verbessern und bei aenderungen ist man angewiesen auf den Entwickler.
Modbus ist ein Allgemeines Protokoll, wen wir fuer jeden modbus adapter so etwas machen wuerde waren das alleine ueber 200

Im forum gibt es sehr gute infos wie man mit den Adressen umgehen sollte

**Comment by josefholdschick** [comment]
Der Fehler lag in der Eingabe der Register, denn im iobroker muss die Zahl für das Register immer um 1 höher sein als in der Hardwaredoku!
