### ISSUE TITLE
Audi Adapter

### ISSUE THREAD

**Issue by rande83** [ioBroker/AdapterRequests#606]
Is there any way to make an adapter for myaudi service so that we can integrate all relevant data in iobroker? Or is someone still involved in it?

Maybe this could help: https://github.com/davidgiga1993/AudiAPI

Best regards,

Randy

**Comment by sky-it** [comment]
Look here: https://github.com/ta2k/ioBroker.vw-connect

**Comment by rande83** [comment]
Oh, I'm very sorry. I really doesn't recognized that it is inbuilt  in VW Adapter.

Works great.

Maybe it would better to rename this adapter, so it's easier to find it if you don't drive an VW.

**Comment by ldittmar81** [comment]
Works with VM Adapter
