### ISSUE TITLE
Homee Adapter

### ISSUE THREAD

**Issue by steckenpferd** [ioBroker/AdapterRequests#61]
Nur als Idee - da ja FHEM, Openhab usw es Adapter gibt - wie wäre es mit einem Adapter für Homee
https://community.hom.ee/t/oeffentliche-schnittstelle-api/79/62

![grafik](https://user-images.githubusercontent.com/39061622/39712407-3ade28dc-5223-11e8-9470-32643219cbd8.png)

**Comment by hblaschka** [comment]
@Apollon77 
Ingo, wo muss der homee hin? CodeAtelier (Chris Bertko) würde einen zur Verfügung stellen... Und ich bin mir sicher, dass Stefan (s.o.) bei der Entwicklung des Adapters unterstützen würde.

**Comment by Coffee-lover** [comment]
Super Idee. Würde ich sofort einsetzen.

**Comment by odig** [comment]
Mit den oben erwähnten Beispielen sollte es relativ einfach zu implementieren sein.

**Comment by steckenpferd** [comment]
Letzter Stand: https://forum.iobroker.net/viewtopic.php?f=24&t=14006&p=148422#p148422

**Comment by Apollon77** [comment]
Für die Wartezeit bis zum eigenen Adapter (kommt als nächstes) vllt mal mit ioBroker.ham versuchen? :-))

https://forum.iobroker.net/viewtopic.php?f=36&t=14972

**Comment by Apollon77** [comment]
test-Thread: https://forum.iobroker.net/viewtopic.php?f=36&t=15247

**Comment by GermanBluefox** [comment]
Cool

ср, 4 июл. 2018 г., 17:02 Ingo Fischer <notifications@github.com>:
