### ISSUE TITLE
Remote GPIO / Control the GPIOs of network connected Raspberrypis remotely from iobroker host. (without making these pi to a multihost slave)

### ISSUE THREAD

**Issue by smartboart** [ioBroker/AdapterRequests#611]
I would like to control the GPIOs from several Raspberry pis which are connected to my network. This should be done remotely from the iobroker host / master .
I know that this is possible by installing iobroker to them and make them to an iobroker multihost slave with rpi adapter installed on this slaves. 
But because of limited Resources i just would like to use the remote GPIO function from these Raspberry pis.

I think it could be a usefull Adapter even for others...

So far i did not startet to get it working on another way, but as soon as i have found out , how i can do this i will update this Adapterrequest...

Thanks a lot...

Best regards..

**What kind of device or service you would like to see an adapter for?**
Raspberrypi 3 3B+ 4

**Is an official API including documentation is available?**
https://gist.github.com/bennuttall/572789b0aa5fc2e7c05c7ada1bdc813e

**Are other libraries for an integration available?**
Ideally in JavaScript/npm, but also other programming languages are interesting, add Links please

**Is this device already integrated in other Smart Home systems?**
no

**Is this device already integrated in homebridge? Might the ham adapter together with the homebridge plugin be sufficient?**
Please try it and add infos
no
**Additional context**
Add any other context or screenshots about the feature request here. If the topic was discussed in ioBroker forum please include the link too.

After you created the issue vote for yourself in the first post of the issue using the "+1"/"Thumbs up" button

**Comment by DutchmanNL** [comment]
@Apollon77 I would say "we. already have" ?

option 1: Multihost and RPI adapter
native option wit adapter and gpis control
option2: Linux controle 
sending command line commands to another. linux host


booth make it possible to archive the goal?

**Comment by DutchmanNL** [comment]
checked the related GitHub page, the python part I. a local solution no relation to ioBroker, best practice is to use remote ssh to run the commands which can bye accomplished with linux control

"Yes you could SSH in and control it with python directly - that would be a better approach."
