### ISSUE TITLE
Peugeot (App, API)

### ISSUE THREAD

**Issue by Starter4711** [ioBroker/AdapterRequests#613]
**What kind of device or service you would like to see an adapter for?**
Peugeot App. GPS and other vehicle infos.

**Is an official API including documentation is available?**
**Are other libraries for an integration available?**
**Is this device already integrated in other Smart Home systems?**
**Is this device already integrated in homebridge? Might the ham adapter together with the homebridge plugin be sufficient?**
Sry, I don't know.

**Additional context**
like the Adapter Zoe would be great ;) (or other vehicle adapter)

**Comment by Starter4711** [comment]
Hi, got this info for the API
https://developer.groupe-psa.io/webapi/b2c/api-reference/specification/
Regards

**Comment by jhalscheidt** [comment]
Please rename this Issue to "PSA Adapter needed." I want the same for my new Opel Corsa Electric.

**Comment by jhalscheidt** [comment]
Example: https://github.com/flobz/psa_car_controller

**Comment by TA2k** [comment]
If you can provide me a login I can create an adpater
https://forum.iobroker.net/user/tombox

**Comment by TA2k** [comment]
Da die Sache gut dokumentiert ist habe ich mal was gebaut. Aber da ich kein Fahrzeug habe ist es ungetestet
https://github.com/TA2k/ioBroker.psa
Adapter via Benutzerdefiniert installiert und dann unter Adapter eine Instanz mit dem + erzeugen.

**Comment by TA2k** [comment]
Ich habe mal ein Thread erzeugt
https://forum.iobroker.net/topic/45951/test-adapter-psa-v0-0-x-peugot-opel-citroen

**Comment by ldittmar81** [comment]
Its on latest... can be closed

**Comment by Quaddriver** [comment]
Leider funktioniert  der Adapter seit längerer Zeit nicht mehr. Bei Homeassistant gibt es eine Möglichkeit die PSA Fahrzeuge einzubinden. Schade, dass es bei ioBroker nicht mehr geht.

**Comment by mcm1957** [comment]
> Leider funktioniert der Adapter seit längerer Zeit nicht mehr. Bei Homeassistant gibt es eine Möglichkeit die PSA Fahrzeuge einzubinden. Schade, dass es bei ioBroker nicht mehr geht.

Please report problems or feature requests at adapter repository
https://github.com/TA2k/ioBroker.psa
