### ISSUE TITLE
Roborock Adapter Vacuum Cleaner

### ISSUE THREAD

**Issue by SevenNines** [ioBroker/AdapterRequests#614]
Hi, I would prefer a native adapter for the Roborock app so you don't have to switch to the Mi Smart Home app.

**Comment by KLVN** [comment]
https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum

**Comment by mcm1957** [comment]
Look like the adapter mihome.vacuum (already available at repo) satifies this request.
(https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum)

Please report any problems or feature requests at the adapater repository.

If this radapter does not solve this request, please respond and state why an extra adapter should be implemented an what difference to mihome.vacuum ist expected. The request could be opened again if there is a special reason to do so.
