### ISSUE TITLE
HomematicIP Cloud Access Point Adapter 

### ISSUE THREAD

**Issue by steckenpferd** [ioBroker/AdapterRequests#62]
s. https://github.com/coreGreenberet/homematicip-rest-api
https://github.com/coreGreenberet/homematicip-samples

https://homematic-forum.de/forum/viewtopic.php?f=59&t=35574

https://www.home-assistant.io/components/homematicip_cloud/

Create an Adapter for Homematic IP Cloud s . solution HomematicIP REST API (Access Point Based)
Ich stelle gerne Hardware HmIP Access Point und passende Geräte bereit falls sich ein Fähiger Entwickler meldet

![grafik](https://user-images.githubusercontent.com/39061622/39712744-72c9ccb4-5224-11e8-8e8a-22874c6f3ac3.png)

**Comment by Apollon77** [comment]
Im ersten Schritt heisst es das ein Entwickler idealerweise diese Hardware und idealerweise auch HMIP Geräte braucht um bei der Entwicklung nicht blind zu arbeiten. heisst also nicht zwangsläufig das die HW gesucht wird, sondern eher das man es idealerweise braucht.

**Comment by steckenpferd** [comment]
Wie oben geschrieben ich stelle gern HMIP Access Point und Geräte bereit. Oh du geheimnisvoller Entwickler falls es dich gibt melde dich einfach ;-)

**Comment by steckenpferd** [comment]
Rest-API Version 0.9.7 ist veröffentlicht worden:
Neben Stabilitätsverbesserungen wird jetzt auch der Wassersensor (HMIP-SWD) und der Bewegungsmelder mit 2-Kanal-Funksender (HMIP-SMI55) unterstützt.

**Comment by hdxbrain** [comment]
Das wäre ja klasse wenn das gehen würde.
Gibt es dazu schon was neues??

**Comment by Apollon77** [comment]
Der Request ist nicht assigned, also nichts.

**Comment by anrada73** [comment]
Bitte!)

**Comment by steckenpferd** [comment]
Nicht vergessen mit Daumen hoch abzustimmen sonst bringt es nix

**Comment by anrada73** [comment]
steckenpferd : https://www.facebook.com/groups/HomematicIP/  )

**Comment by steckenpferd** [comment]
Hallo,

hier noch der von Andrey bei Facebook gepostete Workaroung mit dem Alexa2 Adapter.
[Anleitung-HmIP-ioBroker.pdf](https://github.com/ioBroker/AdapterRequests/files/2388076/Anleitung-HmIP-ioBroker.pdf)

Sowie dem Workaround für das Problem mit dem aktuellen Status erkennen:
![homematic_ip_alexa_status](https://user-images.githubusercontent.com/39061622/45616735-a14bc100-ba70-11e8-9441-7fd163cacf34.jpg)

**Comment by Apollon77** [comment]
nicht zu empfehlen ... bitte mindestens auf 10 Minuten hochsetzen!!

**Comment by steckenpferd** [comment]
Noch als Link Homematic IP Technische Geräte Dokumentation:
https://www.eq-3.de/Downloads/eq3/download%20bereich/hm_web_ui_doku/HmIP_Device_Documentation.pdf

**Comment by saepfle** [comment]
Da in der HmIP Facebook Gruppe von der "Home Assistant" Lösung für den Access Point geschwärmt wird hoffe Ich weiterhin das es einen ioBroker Adapter Entwickler gibt der die Rest-API Doku umsetzten könnte - dann wäre alles wichtige in ioBroker integriert.

**Comment by anrada73** [comment]
bitte,bitte, mach einen HMip Adapter.

**Comment by Levaeri** [comment]
Da kann man nur sagen "Daumen Hoch!"

**Comment by anrada73** [comment]
Das funktioniert leider nur in einer Richtung, nimm lieber Home Assistant, da ist schon alles möglich) https://www.facebook.com/groups/HomematicIP/

**Comment by TobiasF1986** [comment]
So wie es aussieht aktualisiert die vis den Statur doch,dies dauert aber locker gefühlt eine viertel Stunde. 

Das andere Projekt schaue ich mir gerne mal an.

**Comment by anrada73** [comment]
dann mach via Blockly  einen Querry All Request (in Alexa Adapter)

**Comment by TobiasF1986** [comment]
Den habe ich nach dem Bild oben mit 5 Minuten erstellt. Auch wie später angegeben mit 10 Minuten ohne Änderung. Sogar mit wenigen Sekunden keine Änderung. Wahrscheinlich verstehe ich es einfach nur nicht.

**Comment by tomasj83** [comment]
Ich gebe die Hoffnung auf das in unmittelbarer Nähe bald ein ioBroker Adapter für den HmIP AP erscheint. Bestärkt duch die Homematic IP User Facebook Gruppe und die zahlreichen positiven Rückmeldungen habe ich mich getraut Home Assistant auszuprobieren. Eins Vorweg das war die richtige Entscheidung und bevor ihr alle zu lange darauf wartet hier meine Erfahrung.
 
Auf meinem ioBroker habe ich bisher Dashboards für Wetterdaten, Philips Hue, Logitech Harmony, Amazon Alexa, Netamo, Mi Staubsauger, Yamaha Muisccast Receiver sowie Homekit. Da ich günstig einen Homematic IP AP mit 5x Thermostaten erstanden hatte, war vor 6 Monaten meine Hoffnung groß das dank diesen Request es bald auch den HmIP AP in ioBroker geben wird. Leider war das nicht der Fall, auch wollte ich keine CCU kaufen und alles von der HmIP AP Zentrale migrieren, vor allem da in der Zwischenzeit weitere HmIP Komponenten dazu kamen wie Wandthermostate, Aktoren und Bewegungsmelder.
Als dann vor kurzem Conrad Connect für den HmIP AP erschien dachte ich endlich der Lösung nahe zu sein - aber das Ganze war sehr eingeschränkt zu benutzen und lief auch nicht stabil. Dann sah ich den letzten Aufruf in der ioBroker Facebook Gruppe diesen Request zu unterstützen und wie einige alteingesessene ioBroker User/Community reagiert haben, das und die positiven Rückmeldungen zu Home Assistant haben mich bewogen diesen auf einem extra Raspi zu installieren und auszuprobieren.

Die Einrichtung ging aufgrund der guten Anleitungen auf youtube kinderleicht, der große Aha Effekt kam als ich Anfing die ersten Sachen mit Home Assistant zu verbinden - viel unkomplizierter als ioBroker, alles gleich einfach dargestellt und aufgearbeitet und nicht wie nach Excel Listen aussehenden Datenpunkte wie in ioBroker. Dann wurder der HmIP AP angebunden und mein Smart Home Herz wurde beglückt alles lies sich problemlos in Home Assistant integrieren und steuern – endlich !!! Mittlerweile habe ich alles in Home Assistant migriert.

Daher liebe HmIP AP Freunde, trauert nicht zu lange den vergebenen Liebesmühen nach, ich hätte mich gefreut aufgrund der großen Deutschen ioBroker Community weiter Teil diesem zu sein. Aber auch ich wie viele andere möchten nicht nur 75% steuern können, sondern auch den größten Deutschen Smart Home Hersteller integriert haben. Home Assistant hat mich bisher nicht enttäuscht.

**Comment by Apollon77** [comment]
Reisende soll mal ziehen lassen ... alles gut. Schade das Du "die Hoffnung aufgibst" und viel Erfolg mit Home Assistant.

**Comment by tomasj83** [comment]
Du meinst die Hoffnung das es “zeitnah” doch einen Adapter geben wird. 
Falls ich in weiter Zukunft Sonoff oder Tasmota nutzen möchte und doch ein HmIP AP oder Alternativ ein Home Assistant Adapter erschienen ist schau ich gern wieder mal vorbei ;-)

**Comment by jogibear9988** [comment]
arbeitet da schon jemand dran, sonst würds ich mir mal anschauen.

kann denn jm. hardware ausleihen?

**Comment by jogibear9988** [comment]
@steckenpferd ich melde mich hiermit

**Comment by steckenpferd** [comment]
Mail geht gleich raus

**Comment by steckenpferd** [comment]
jogibear9988 hast du die Mail erhalten?

**Comment by steckenpferd** [comment]
FYI - jogibear9988 braucht meine Geräte nicht mehr die ich zur Verfügung stellen wollte - hoffentlich klappt es aber mit der Adapter Entwicklung - Daumen drücken

**Comment by jogibear9988** [comment]
Also hab die HW nun erhalten. Hab schon mal ne node-js api angefangen, token abgleich etc. funzt soweit mal schon, auslesen der config auch.
Bis ich da was vorstellen kann, vergehen aber bestimmt noch 1-2 Wochen

**Comment by jogibear9988** [comment]
steckdose steuern geht schon

**Comment by jogibear9988** [comment]
state changes muss ich noch schauen, aber wird...

**Comment by saepfle** [comment]
Sind ja super Neuigkeiten!!! Falls du etwas brauchst bzw. es Fragen zu HmIP gibt einfach schreiben.
Kurz Frage setzt du gleich alle Geräte aus der Rest-API um? Werden auch die eigenen internen Automatisierungsregeln aufrufen möglich sein?

**Comment by steckenpferd** [comment]
Ich habe schon mal eine Übersicht erstellt welche Homematic IP Geräte es gibt bzw. angekündigt wurden, in der REST-API bereits dokumentiert sind und sobald per HmIP AP Cloud Adapter verfügbar werde ich die "x" setzen.
url=https://dl.dropboxusercontent.com/s/nma2rtpafgngy2e/REST-API.vs.ioBroker.HmIP.xlsx

**Comment by jogibear9988** [comment]
hier mal ne demo: https://github.com/iobroker-community-adapters/ioBroker.hm-ip-cloud-accesspoint

in 0.1 landen wohl nur energy steckdose und temperaturmesser aber das ist dann leicht erweitert

**Comment by jogibear9988** [comment]
token muss noch über test_getAuthToken.js erzeugt werden

**Comment by steckenpferd** [comment]
Folgende Geräte könnte ich momentan entbehren und zusenden wenn es hilft:
[X] HMIP-ASIR-B1 (Alarm Siren)
[X] HMIP-eTRV2, HMIP-eTRV-B1 (Heating-thermostat)
[X] HMIP-PCBS (Printed Curcuit Board Switch)
[X] HMIP-PS (Plugable Switch)
[X] HMIP-PSM (Plugable Switch Measuring)
[X] HMIP-SWDO (Shutter Contact)
[X] HMIP-SWDM-B2 (Door / Window Contact - magnetic )
[X] HMIP-WTH-2 (Wall Mounted Thermostat Pro)

**Comment by ApolloSK** [comment]
Guten Abend,

bei der Nutzung der test_getAuthToken.js erhalte ich folgende Fehlermeldung:

/opt/iobroker/node_modules/iobroker.hm-ip-cloud-accesspoint/api/test_getAuthToke                   n.js:6
const api = new apiClass(process.arg[0]);
                                    ^

TypeError: Cannot read property '0' of undefined
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.hm-ip-cloud-acces                   spoint/api/test_getAuthToken.js:6:37)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

**Comment by jogibear9988** [comment]
@steckenpferd 
brauche die im moment nicht, das kann später ganz leicht erweitert werden. da kannst du den code dann per pull req. um nicht vorhandene devices erweitern (oder um parameter die fehlen)

ich muss jetzt erstmal den token abgleich in den config screen einbauen, und ein bisschen aufräumen.
dann den api wrapper vervollständigen, also bischen dauerts noch.

**Comment by jogibear9988** [comment]
man braucht eigentlich für jedes device auch erstmal nur das json was ich hier ausplotte: 
"device - not implemented device ....."

**Comment by jogibear9988** [comment]
Im Moment sind 

PLUGABLE_SWITCH_MEASURING und
TEMPERATURE_HUMIDITY_SENSOR_DISPLAY

enthalten

**Comment by jogibear9988** [comment]
@Apollon77 kannst den status auf in progress ändern?

**Comment by jogibear9988** [comment]
@steckenpferd poste mir mal die JSONS welche mein adapter für deine devices ausgibt

**Comment by ApolloSK** [comment]
Guten Morgen jogibear9988,

leider erhalte ich erneut eine Fehlermeldung -siehe Anlage.

Zum Vorgehen:
Ich habe den Adapter neu von Github geladen. Eine neue Instanz in iobroker angelegt.
In der Instanz, in der Konfiguration, an den entsprechenden Stellen meine AcessPoint SGTIN und die AcessPoint PIN eingetragen. Anschließend habe ich über die Komandozeile die Datei get_AuthToken.js gestartet.

[Fehler_HMIP.txt](https://github.com/ioBroker/AdapterRequests/files/2767737/Fehler_HMIP.txt)

**Comment by jogibear9988** [comment]
Das Tool test_getAuthToken.js verwendet keine Daten von IOBroker, du musst deine AccessPointIP und dein Pin als Parameter übergeben.

In die Config UI von IOBroker muss ich das noch einbauen!

**Comment by ApolloSK** [comment]
Ah, ok ... ich hab meine Abfrage entsprechend angepasst. Sehe aber kein Ergebnis:

root@debian-iobroker:/opt/iobroker/node_modules/iobroker.hmip/api# ./test_getAuthToken.js 3014XXXXXXXXXXXXXXXXXXXXXXXXXXX [26XXXXXXXXXXXXXXXXXXXXXX]                 ./test_getAuthToken.js: Zeile 1: //: Ist ein Verzeichnis
./test_getAuthToken.js: Zeile 2: $'\r': Kommando nicht gefunden.
./test_getAuthToken.js: Zeile 3: Syntaxfehler beim unerwarteten Wort `$'\r''
'/test_getAuthToken.js: Zeile 3: `if (!process.argv || !process.argv[0])
root@debian-iobroker:/opt/iobroker/node_modules/iobroker.hmip/api#

**Comment by jogibear9988** [comment]
try again... (new version)

**Comment by ApolloSK** [comment]
neu getestet :-)

root@debian-iobroker:/opt/iobroker/node_modules/iobroker.hmip/api# ./test_getAuthToken.js 3014XXXXXXXXXXXXXXXXXXXXXX [26XXXXXXXXXXXXXXXXXXXXX]
./test_getAuthToken.js: Zeile 1: //: Ist ein Verzeichnis
./test_getAuthToken.js: Zeile 2: $'\r': Kommando nicht gefunden.
./test_getAuthToken.js: Zeile 3: Syntaxfehler beim unerwarteten Wort `$'\r''
'/test_getAuthToken.js: Zeile 3: `if (!process.argv || !process.argv[2])
root@debian-iobroker:/opt/iobroker/node_modules/iobroker.hmip/api#

**Comment by jogibear9988** [comment]
dann füg deine 2 werte einfch hart in das script ein

**Comment by jogibear9988** [comment]
oder probiers mit 

       node test_get...

**Comment by steckenpferd** [comment]
@ApolloSK kannst du schon deine JSONS für die Devices an jogibear senden - ich komme frühstens am WE dazu da verreist.

**Comment by jogibear9988** [comment]
noch besser wären gleich pull requests mit den device states

**Comment by TobiasF1986** [comment]
Hallo,
das sieht wirklich nach einer wunderbaren Arbeit hier aus. Ich freue mich schon riesig darauf dass der iobroker mit dem AP ohne Alexa Umweg funktioniert.

Habe die Testversion nun installiert und die SGTIN im Adapter eingetragen. Wäre evtl. jemand so nett und würde mir erklären, wie ich an die Token komme?

**Comment by TobiasF1986** [comment]
Habe mich nun zur richtigen Datei vorgearbeitet, aber scheinbar übergebe ich falsche Parameter? In den eckigen Klammern der vierstellige AP Code?

`
pi@All-In-One_RasPi:/opt/iobroker/node_modules/iobroker.hm-ip-cloud-accesspoint/api $ node test_getAuthToken.js 3015-0377-DC00-03D9-XXXX-XXXX [XXXX]
/opt/iobroker/node_modules/iobroker.hm-ip-cloud-accesspoint/api/test_getAuthToken.js:6
const api = new apiClass(process.arg[0]);
                                    ^

TypeError: Cannot read property '0' of undefined
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.hm-ip-cloud-accesspoint/api/test_getAuthToken.js:6:37)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
`

**Comment by jogibear9988** [comment]
du musst das consolen programm starten und sgtin und pin übergeben

**Comment by TobiasF1986** [comment]
Okay, danke, dann war ich an sich ja richtig unterwegs. Leider bleibt es dabei (habe zur Vereinfachung den Pin im AP deaktiviert)

`
pi@All-In-One_RasPi:/opt/iobroker/node_modules/iobroker.hm-ip-cloud-accesspoint/api $ node test_getAuthToken.js 3015-0377-DC00-03D9-XXXX-XXXX
/opt/iobroker/node_modules/iobroker.hm-ip-cloud-accesspoint/api/test_getAuthToken.js:6
const api = new apiClass(process.arg[0]);
                                    ^

TypeError: Cannot read property '0' of undefined
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.hm-ip-cloud-accesspoint/api/test_getAuthToken.js:6:37)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
`

**Comment by jogibear9988** [comment]
npm i
im adapter verzeichnis

**Comment by TobiasF1986** [comment]
Ich komme wohl nicht ganz mit:
- Ich habe den Adapter über die Github Adresse in ioBroker installiert
- in der Adapterkonfig im ioBroker habe ich meine SGTIN eingetragen
- danach den Befehl "pi@All-In-One_RasPi:/opt/iobroker/node_modules/iobroker.hm-ip-cloud-accesspoint/api $ node test_getAuthToken.js 3015-0377-DC00-03D9-XXXX-XXXX" eingegeben mit der obrigen Fehlermeldung. Habe ich etwas vergessen zu installieren? Entschuldige meine Unwissenheit, aber was meinst du mit "npm i
im adapter verzeichnis"? Gruß

**Comment by ApolloSK** [comment]
Probiere mal:
Die SGTIN ohne die "-", anschließend ein Leerzeichen und danach den KEY, wieder ohne "-".
Also:
"pi@All-In-One_RasPi:/opt/iobroker/node_modules/iobroker.hm-ip-cloud-accesspoint/api $ node test_getAuthToken.js 30150377DC0003D9XXXXXXXX KEYXXXXX..."

**Comment by steckenpferd** [comment]
Ich habe im Forum einen Thread aufgemacht falls ihr da weiter posten wollt: https://forum.iobroker.net/viewtopic.php?f=36&t=21000

**Comment by jogibear9988** [comment]
token sollte man nun über die settings erzeugen können!!!

**Comment by jogibear9988** [comment]
repo nun unter: https://github.com/iobroker-community-adapters/ioBroker.hmip
bitte ab nun fehler dort melden!

**Comment by jogibear9988** [comment]
@TobiasF1986 jetzt sollte auch das token erstellen von der Config Seite aus gehen

**Comment by TobiasF1986** [comment]
So ist es. Danke schonmal für die tolle Arbeit und schnelle Hilfe hier!!

**Comment by jhuebner1** [comment]
Hallo,

kann noch das Merkmal "Boost" eingebunden werden?
In den VIS ist das drin, aber ich habs im Adapter nicht....

**Comment by Apollon77** [comment]
Bitte ein issue als feature request beim Adapter selbst eröffnen!
