### ISSUE TITLE
Adapter for Gira HomeServer and X1 (Gira IoT REST API)

### ISSUE THREAD

**Issue by nowi967** [ioBroker/AdapterRequests#625]
**What kind of device or service you would like to see an adapter for?**
Gira X1
[https://www.gira.de/produkte/lichtsteuerung/lichtsteuerung-per-app/gira-x1](url)
Gira HomeServer / FacilityServer
[https://www.gira.de/produkte/lichtsteuerung/lichtsteuerung-per-app/gira-homeserver-die-zentrale-fuer-das-intelligente-haus](url)

**Is an official API including documentation is available?**
[https://download.gira.de/data3/Gira_IoT_REST_API_v2_DE.pdf](url)

**Are other libraries for an integration available?**
[https://github.com/metaneutrons/node-red-contrib-gira-rest](url)

**Is this device already integrated in other Smart Home systems?**
Node Red

**Is this device already integrated in homebridge? Might the ham adapter together with the homebridge plugin be sufficient?**
Nein, für die Gira Server gibt es keine Homebridge integration.

**Comment by klein0r** [comment]
Ich habe mal angefangen: https://github.com/klein0r/ioBroker.gira-iot

Aber: Das ist nur das absolute Grundgerüst. Bald mehr.

*Der Adapter ist im Rahmen eines Videos zur Apapter-Entwicklung entstanden. Daher gibt es zwar schon 2 Versionen auf npm, aber der Adapter kann noch nicht besonders viel.*

**Comment by klein0r** [comment]
See also: https://forum.iobroker.net/topic/58514/test-adapter-gira-iot

**Comment by mcm1957** [comment]
Repo: https://github.com/klein0r/ioBroker.gira-iot

request to add to repo seems to be pending
https://github.com/ioBroker/ioBroker.repositories/pull/2052

**Comment by klein0r** [comment]
@mcm1957 Merged

**Comment by mcm1957** [comment]
Adapter available at latest repository.
In case of problems, please opne a issue at the adapter repository (https://github.com/klein0r/ioBroker.gira-iot)
