### ISSUE TITLE
Corona Impftermine

### ISSUE THREAD

**Issue by Elektronikwelt** [ioBroker/AdapterRequests#627]
Da es sehr schwierig ist gerade in Baden-Württemberg ein Impftermin unter 60 zu bekommen, hab ich eine Homepage entdeckt wo die Daten von den Impfterminen abruft. 
Gibt es eine Möglichkeit die Daten für IOBroker aufzubereiten. 
Die Seite ist https://www.impfterminübersicht.de/
Am besten wäre es eine Favoritenauswahl möglich zu machen.

> *created by ioBroker.info*

**Comment by Elektronikwelt** [comment]
Ich habe einen Code entdeckt im Github. Wäre dieser als Adapter integrierbar in Iobroker?
https://github.com/marcoklein/impftermin

**Comment by Newan** [comment]
Dienst wurde eingestellt
