### ISSUE TITLE
Anwesenheitssimulation

### ISSUE THREAD

**Issue by Castlehub** [ioBroker/AdapterRequests#631]
Hallo,
meine Suche nach einer gut zu bedienenden Anwesenheitssimulation, ergab bis heute für mich keine händelbare und übersichtliche Lösung.
Daraufhin habe ich einmal grafisch versucht meine Idee zu erstellen.

Würde mich über eine Rückinfo freuen, ob so etwas benötigt wird und umsetzbar ist.

Danke 
Raik

**Idee**

![Anwesenheitssimulation3](https://user-images.githubusercontent.com/70769414/119249692-e407b480-bb9a-11eb-83e7-901493d4cb77.jpg)

**Comment by irudi** [comment]
Ich habe auch schon mal über soetwas nachgedacht. Schick wäre, wenn man die Aktoren definiert, die man mit einbeziehen möchte, dann das System ein paar Tage mitlaufen lässt und der Adapter die Daten zur Simulation automatisch aus der echten Nutzung ableiten würde ...

**Comment by Castlehub** [comment]
> Ich habe auch schon mal über soetwas nachgedacht. Schick wäre, wenn man die Aktoren definiert, die man mit einbeziehen möchte, dann das System ein paar Tage mitlaufen lässt und der Adapter die Daten zur Simulation automatisch aus der realen Nutzung ableiten würde ...

Das wäre ja eine super Erweiterung des ganzen. 👍

**Comment by irudi** [comment]
Habe gerade gesehen, dass in #11 etwas ähnliches gewünscht wurde.

**Comment by ldittmar81** [comment]
Ich schließe das hier und er kann im #11 weiter abgestimmt werden.
