### ISSUE TITLE
Ya, so müssen wir es auch machen. Bzgl. Phasenumschaltung werde ich ein zusätzliches Schütz vor die WB hängen und L2 und L3 schaltbar machen. z.B. über Shelly o.ä.

### ISSUE THREAD

**Issue by hannesrh** [ioBroker/AdapterRequests#633]
Ich habe heute getestet während einphasig geladen wurde, die Phasen 2,3 per LS Schalter einzuschalten. L2,L3 wurden nicht belastet. Erst das Abschalten aller Phasen und wieder Einschalten aller 3 Phasen hat 3 phasiges Laden bewirkt. Nach meiner Erfahrung bringt einfaches Zuschalten per Schütz nicht das gewünschte Ergebnis.

**Comment by DutchmanNL** [comment]
ich verstehe nicht wirklich was dieses issue mit AdapterRequest zu tun hat @hannesrh ?
