### ISSUE TITLE
DatapointAnalytics

### ISSUE THREAD

**Issue by ipod86** [ioBroker/AdapterRequests#635]
Hallo, 

ich würde mir einen Adapter ähnlich SourceAnalytics wünschen, um normale Datenpunkte auszuwerten. 

Dass zb ähnlich SA eine Jahres, Monats und Tages Ordnerstrucktur samt "last week", "last month" und "last year" angelegt wird, in der man sieht wie lange welcher Datenpunkt welchen Status hatte. 

Für Daten wie: Der Fernseher war so lange an, das Fenster so lange offen etc. 

Am besten nicht für nur  "true" oder "false" .
Manche Adapter füllen Datenpunkte ja zb mit "on", "off" und "standby". 

Es könnte ggf für jeden Zustand des Datenpunktes in der Ordnerstrucktur ein eigener Datenpunkt angelegt werden. 
Klasse wäre auch, jeden Datenpunkt sagen zu können, ob die Auswertung in Stunden, Minuten oder ms ausgegeben werden sollen. 

Den Namensvorschlag im Titel ist auf die schnelle erfunden....

**Comment by Diginix** [comment]
Schonmal den statistics Adapter angeschaut?
Der liefert min, max, avg, total usw für Tag, Woche, Monat, Quartal, Jahr.

**Comment by ldittmar81** [comment]
https://github.com/iobroker-community-adapters/ioBroker.statistics
