### ISSUE TITLE
Elsner P04/3-RS485 Wetterstation

### ISSUE THREAD

**Issue by Markus-3** [ioBroker/AdapterRequests#636]
Adapter Anfrage
für Wetterstation Elsner P04/3-RS485
https://www.elsner-elektronik.de/shop/de/p04-3-rs485.html

Technische Daten:
https://www.elsner-elektronik.de/shop/de/fileuploader/download/download/?d=1&file=custom%2Fupload%2F30152-54_P043-RS485_Datenblatt_27Mrz20_DBEEA6072.pdf

Anbindung über RS485 - USB
Adapter z.B.: https://www.amazon.de/Waveshare-Industrial-USB-RS485-Transceiving/dp/B081NBCJRS

Programmierungsbeispiel im fhem unter:
https://github.com/mhop/fhem-mirror/blob/master/fhem/FHEM/00_ElsnerWS.pm

**Comment by Markus-3** [comment]
Elsner Wetterstation P04/3-RS485
https://www.elsner-elektronik.de/shop/de/p04-3-rs485.html

Technische Daten:
https://www.elsner-elektronik.de/shop/de/fileuploader/download/download/?d=1&file=custom%2Fupload%2F30152-54_P043-RS485_Datenblatt_27Mrz20_DBEEA6072.pdf

Anbindung über RS485 - USB Adapter z.B.:
https://www.amazon.de/Waveshare-Industrial-USB-RS485-Transceiving/dp/B081NBCJRS

**Comment by Esteban70** [comment]
Hi Markus, hast du noch ein paar mehr Infos, wie Du die Wetterstation mit den Cubes integriert hast? VG Stefan

**Comment by Markus-3** [comment]
Hallo Stefan,
die Elsner P04/3 Wetterstation lies sich nicht einbinden. Ich habe die Wetterstation durch eine von Eltako (MS) ersetzt und an diese das Enocean Funkmodul angeschlossen. Nun kann ich die Wetterstation über den enocean Adapter einlesen.

**Comment by Esteban70** [comment]
Vielen Dank Markus,

 

es ist echt zum verzweifeln, ich bekomme die blöde Wiga Steuerung nicht eingebunden und Elsner bietet auch Schnittstelle wie z.B. für ein anderes Produkt.

 

Kannst du mit bitte dann noch einmal die Produktnummer von Eltako geben? War die Einbindung an die Wiga Steuerung problemlos? Ich selbst habe die WS1000 Style ...

 

VG Stefan

 
 

Gesendet: Donnerstag, 13. Januar 2022 um 12:45 Uhr
Von: "Markus-3" ***@***.***>
An: "ioBroker/AdapterRequests" ***@***.***>
Cc: "Stefan" ***@***.***>, "Comment" ***@***.***>
Betreff: Re: [ioBroker/AdapterRequests] Elsner P04/3-RS485 Wetterstation (#636)


 

Hallo Stefan,
die Elsner P04/3 Wetterstation lies sich nicht einbinden. Ich habe die Wetterstation durch eine von Eltako (MS) ersetzt und an diese das Enocean Funkmodul angeschlossen. Nun kann ich die Wetterstation über den enocean Adapter einlesen.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Markus-3** [comment]
Ich habe keine Wiga Steuerung. Bei mir war die Elsner Wetterstation an einem Windows PC angeschlossen auf dem das Programm Myhomecontrol von Bootup lief. Damit war ich aber nicht zufrieden. Wollte daher die Wetterstation an einem Rasperry anbinden auf dem der ioBroker läuft. Das war aber nicht möglich da die P04 Wetterstation andere Daten schickt zu dem es keinen Adapter gibt. Also habe ich die Wetterstation gegen einen Eltako Multisensor getauscht und daran das FWS-61 angeschlossen welches die Wetterdaten auf dem enocean Datenbus funkt. Dann habe ich einen Dosmung USB Adapter an den Raspy gehängt über welchen die Daten empfangen werden. Dann nur noch den enocean Adapter über Github auf den ioBroker geladen (ist noch im Entwicklungsstatus läuft aber sehr gut) und die Daten im ioBroker mit den anderen Komponenten wie Lüftungsanlage, Rolläden , Markiesen usw verknüpft.

**Comment by Esteban70** [comment]
Ah, ok. Verstanden. Danke!

 
 

Gesendet: Donnerstag, 13. Januar 2022 um 14:21 Uhr
Von: "Markus-3" ***@***.***>
An: "ioBroker/AdapterRequests" ***@***.***>
Cc: "Stefan" ***@***.***>, "Comment" ***@***.***>
Betreff: Re: [ioBroker/AdapterRequests] Elsner P04/3-RS485 Wetterstation (#636)


 

Ich habe keine Wiga Steuerung. Bei mir war die Elsner Wetterstation an einem Windows PC angeschlossen auf dem das Programm Myhomecontrol von Bootup lief. Damit war ich aber nicht zufrieden. Wollte daher die Wetterstation an einem Rasperry anbinden auf dem der ioBroker läuft. Das war aber nicht möglich da die P04 Wetterstation andere Daten schickt zu dem es keinen Adapter gibt. Also habe ich die Wetterstation gegen einen Eltako Multisensor getauscht und daran das FWS-61 angeschlossen welches die Wetterdaten auf dem enocean Datenbus funkt. Dann habe ich einen Dosmung USB Adapter an den Raspy gehängt über welchen die Daten empfangen werden. Dann nur noch den enocean Adapter über Github auf den ioBroker geladen (ist noch im Entwicklungsstatus läuft aber sehr gut) und die Daten im ioBroker mit den anderen Komponenten wie Lüftungsanlage, Rolläden , Markiesen usw verknüpft.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Christiank11** [comment]
Hat jemand genauere Infos für die Wetterstation von Elsner Solexa 2 ?

**Comment by mcm1957** [comment]
Dieses Topic ist bereits geschlossen.
Allgemeine Fragen bitte im Forum "https://forum.iobroker.net" stellen.

Für den Request eines neuen Adapters bitte ein neues Issue öffnen und die Frageliste ausfüllen.

Danke.
