### ISSUE TITLE
MyStrom Adapter

### ISSUE THREAD

**Issue by m3gg3** [ioBroker/AdapterRequests#641]
Adapter for managing devices from https://mystrom.ch/

**Comment by Apollon77** [comment]
Could you please add more informations as requersted in the issue template? Does there existi libraries for an integration? Other smart home systems? Is there a documented API?

**Comment by m3gg3** [comment]
Hi

The API Documentation is right here https://mystrom.ch/de/mystrom-rest-api/

Greets

**Comment by mystrom-tom** [comment]
Hi
Should be pretty simple since shelly is VERY similar.
Cheers
Tom

**Comment by UncleSamSwiss** [comment]
Would be interested in this as well.
I had a look at the API some time ago but then abandoned the project as I have too much to do with my other adapters (and general ioBroker stuff) right now.

**Comment by TA2k** [comment]
https://www.npmjs.com/package/iobroker.mystrom

**Comment by Apollon77** [comment]
@TA2k You have a time machine? That was fast *gg*

**Comment by m3gg3** [comment]
How can i configure this Adapter after Installation?

**Comment by UncleSamSwiss** [comment]
> https://www.npmjs.com/package/iobroker.mystrom
It seems like this is only for "input" devices. I have some (older) light bulbs that don't seem to be supported by the adapter.

**Comment by TA2k** [comment]
Can you see this older light bulbs automatic in the app?

**Comment by ldittmar81** [comment]
Is on latest... we can close it
