### ISSUE TITLE
Sonnen-Charger

### ISSUE THREAD

**Issue by GioElCapitano98** [ioBroker/AdapterRequests#644]
An adapter for the Sonnen battery already exists.
However, an adapter for the [Sonnen charger](https://sonnen.de/ladestation-elektroauto/) is missing.
This is an intelligent wallbox for charging electric cars.

**Comment by Apollon77** [comment]
Please provide all details as requested by teh template. API  available? Anyother links? Libraries available? Integrated also in other smart home systems?

**Comment by GioElCapitano98** [comment]
Which template?
I don't know, if API is available.
i don't know of any integration into other smart home systems . But maybe there is something i didn't find on google.
i Think you can get more informations from the sonnen support: https://sonnen.de/kontakt-allgemeine-anfrage/

**Comment by GioElCapitano98** [comment]
Es gibt auf jeden Fall eine IP-Adresse.

There is an IP-adress

**Comment by GioElCapitano98** [comment]
![grafik](https://user-images.githubusercontent.com/87119903/132195682-ce2a4b14-1294-4ec2-9720-0abe83ded062.png)

**Comment by foxriver76** [comment]
I will most likely get a Sonnen charger at the end of 2021/early 2022, and will have a look at it then, however if someone is faster - go ;-)

**Comment by ChrisWbb** [comment]
I started the development :-). 
I will try to provide a first version during January 2023.

**Comment by mcm1957** [comment]
Link to adpter: https://github.com/ChrisWbb/ioBroker.sonnen-charger

@ChrisWbb 
Thanks for your work. Please give some feedback here if a first release has been publishe to latest or if you cancel / suspend development for any reason.

**Comment by mcm1957** [comment]
Request to add to latest created:
https://github.com/ioBroker/ioBroker.repositories/pull/2197

**Comment by mcm1957** [comment]
adapter has been released
