### ISSUE TITLE
Adapter for Myenergi Zappi Wallbox

### ISSUE THREAD

**Issue by Mathias2803** [ioBroker/AdapterRequests#652]
**What kind of device or service you would like to see an adapter for?**
Myenergi Zappi Wallbox

**Is an official API including documentation is available?**
There is an API key within the application, but not offically released.
https://myenergi.info/api-f54/

**Are other libraries for an integration available?**
There is a web interface to controll / monitor your system:
https://myaccount.myenergi.com/energy-usage

**Is this device already integrated in other Smart Home systems?**
I don't think so.

**Is this device already integrated in homebridge? Might the ham adapter together with the homebridge plugin be sufficient?**
I don't think so.

**Additional context**
![image](https://user-images.githubusercontent.com/77450176/130051961-e62b3002-a78f-4abf-8f9e-2020e52bfe28.png)

![image](https://user-images.githubusercontent.com/77450176/130052048-72af3f6f-b0dd-4e12-b426-35df89efdbba.png)

After you created the issue vote for yourself in the first post of the issue using the "+1"/"Thumbs up" button

**Comment by Mathias2803** [comment]
Here is some additional information that might help:
https://github.com/twonk/MyEnergi-App-Api

**Comment by dj-mib** [comment]
Ich wäre auch interessiert, die Zappi-Community dürfte inzwischen auch recht groß sein.

**Comment by Archimedes288** [comment]
Auch ich wäre sehr interessiert.

**Comment by Apollon77** [comment]
Dann solltet Uhr alle oben im ersten Post auf Thumbs up drücken ... Posts sind unsichtbar

**Comment by MPTrixi** [comment]
ich wäre auch arg interessiert. Wäre das hier ein Anfang bzw. Teil der Lösung?
[https://github.com/bisand/myenergi-api]

**Comment by dj-mib** [comment]
@MPTrixi  @JamesDemaine-wit  did you click the "Thumbs Up" button in the first post?

@Apollon77  https://github.com/bisand/myenergi-api ist eine  NodeJS Implementierung der MyEnergi API. Ich denke die könnte wirklich als Basis für einen Adapter dienen, oder?

**Comment by MPTrixi** [comment]
@dj-mib yep - mein Daumen ist dabei

Habe mal als Beispiel in den Powerfox Adapter geschaut, was ja ähnlich sein sollte - nicht dass ich das ganze verstehen würde (meine Programmierkenntnisse sind recht angestaubt). Wenn ich es richtig verstanden habe braucht die myenergi API eine digest Authentifizierung, was wohl in axios nicht so (ohne weiteres oder überhaupt?) geht (hab zumindest nur die Aussage gefunden) und man müsste es mit fetch machen? Wie gesagt: Ahnung davon habe ich wirklich nicht. Zumindest bekomme ich die Daten im Browser mit URL (es gibt verschiedene). Ruft man die auf kommt ein Popup mit Abfrage des Users und eines Passworts. Der User ist die SN des eigenen Hubs. Als Passwort kann man mit seinem myenergi Online Konto einen API Key erzeugen. Für Tests stehe ich gerne zur Verfügung (hab aber nur gefährliches Halbwissen ;)).

**Comment by oswi82** [comment]
For testing purposes I am also available.

**Comment by dj-mib** [comment]
Moin zusammen, ich hab ein wenig gebastelt und versucht in einem Script meinen Zappi auszulesen und es klappt!

Voraussetzungen:
-  Im JS Adapter myenergi-api als zusätzliches nmp-Modul ergänzen.
-  API-Key für den Hub erzeugen. (Passwort für den Login)
Es wird nicht das Passwort zum Login an das Portal verwendet, sondern im Portal muss man für seinen Hub einen API-Key erzeugen - dann klappt auch die Anmeldung.

`var test = require('myenergi-api');

async function asyncCall() {
  const hubSerialNo = 111222333; 
  const zappiSerialNo = 222333444;
  const hubApiKey = "der im Portal für den Hub generierte API-Key";
  
  console.log('calling');
  try {
    const myenergi = new test.MyEnergi(hubSerialNo, hubApiKey);
    console.log(myenergi);
    
    var zappiAll = await myenergi.getStatusZappiAll();
    console.log("***** ZAPPI ALL *****");
    console.log(zappiAll);
    console.log("**********************");
    console.log("");
    console.log("***** MEIN ZAPPI *****");
    var statusZappi = await myenergi.getStatusZappi(zappiSerialNo);
    console.log(statusZappi);
  } catch (e) {
      log(e);
  }
}
asyncCall();`

Ergebnis jeweils ein JSON Objekt mit dem man etwas anfangen kann:
 ***** ZAPPI ALL *****
[{'sno':222333444,'dat':'27-05-2022','tim':'07:37:26','ectt1':'Internal Load','ectt2':'Internal Load','ectt3':'Internal Load','bsm':0,'bst':0,'cmt':254,'dst':1,'div':0,'frq':50.01,'fwv':'3560S3.171','grd':-5573,'pha':1,'pri':1,'sta':1,'tz':2,'vol':2382,'che':1.27,'bss':0,'lck':23,'pst':'A','tbk':99,'zmo':3,'pwm':5300,'zs':258,'rac':8,'rrac':-4,'zsh':1,'zsl':2,'ectp4':-1966,'ectp5':-1928,'ectp6':-1839,'ectt4':'Grid','ectt5':'Grid','ectt6':'Grid','mgl':100,'sbh':14,'sbk':5,'sbm':30}]



***** MEIN ZAPPI *****

{'sno':222333444,'dat':'27-05-2022','tim':'07:37:27','ectt1':'Internal Load','ectt2':'Internal Load','ectt3':'Internal Load','bsm':0,'bst':0,'cmt':254,'dst':1,'div':0,'frq':50.01,'fwv':'3560S3.171','grd':-5118,'pha':1,'pri':1,'sta':1,'tz':2,'vol':2382,'che':1.27,'bss':0,'lck':23,'pst':'A','tbk':99,'zmo':3,'pwm':5300,'zs':258,'rac':8,'rrac':-4,'zsh':1,'zsl':2,'ectp4':-1966,'ectp5':-1928,'ectp6':-1839,'ectt4':'Grid','ectt5':'Grid','ectt6':'Grid','mgl':100,'sbh':14,'sbk':5,'sbm':30}
#643 
`


Für ein paar andere Anwendungsfälle habe ich mir aber schonmal Scripte gebaut, die mir z.B, Werte meiner Heizung auslesen und in Objekten speichern...
Ich habe allerdings noch nie einen Adapter für den IO-Broker gebaut.
Mit etwas Unterstützung und einem Adapter für Dummies Guide könnte das aber der erste werden.

**Comment by MPTrixi** [comment]
@dj-mib top - läuft bei mir auch und ist doch schon mal ein Durchbruch. Im Prinzip würde das ja erstmal reichen, oder? Damit könnte man doch nun im ioBroker das als JS regelmäßig laufen lassen und die Werte die einem interessieren in vorher eigen erstellte Datenpunkte schreiben lassen. Wie wäre da das Vorgehen?
1. "npm install myernergi-api" auf dem ioBroker System
2. die Datenpunkte erstellen
3. ?wie bekommt man das nun von der Rückgabe im JSON Format in die einzelnen Datenpunkte?

Zur Adaptererstellung gibt es diverse Anleitungen (inkl. Linksammlungen) und auch Videos. So richtig trivial ist es aber zumindest für mich als DAU in der Sache nicht.

**Comment by hobili** [comment]
Super! 

Ich freue mich echt, dass sich jemand der Sache angenommen hat! 

Ein Adapter würde das Ganze natürlich für die Mehrheit (und auch mich) sehr vereinfachen... :-)

**Comment by dj-mib** [comment]
@MPTrixi   zu:

1. Ich hab tatsächlich erst tatsächlich erst auf der Konsole "npm install myernergi-api" ausgeführt. ich glaube aber es reicht das Modul in der Instanz des JS Adapters  bekannt zu machen, der installiert das dann von selbst,

2.  Kann man von Hand machen, oder ggfs auch generisch im Script

3.  https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse
So macht man aus dem JSON String ein Objekt in Javascript
und so setzt man einen Status : setState("DatenpunktName", result.wert, true); 



4.

**Comment by MPTrixi** [comment]
@dj-mib ich bin da tatsächlich zu blöd dafür. Könntest Du mal Dein Script um einen geschriebenen Datenpunkt aus dem Ergebnis von "MEIN ZAPPI" ergänzen?

**Comment by dj-mib** [comment]
@MPTrixi Wenn ich etwas halbwegs brauchbares zustandebekommen habe, werde ich das hier posten.
Ich muss mich da auch erstmal noch ein wenig einlesen, hab auch noch nicht verstanden, welcher der Werte jetzt angibt wieviel kW in Summe geladen wird...

**Comment by MPTrixi** [comment]
@dj-mib Danke, bin gespannt drauf. Hab grad meinen Post drüber mit einem Link ergänzt. Da sind Beschreibungen zu den einzelnen Werte aufgeführt. Weiter unten dann auch zur Zappi Steuerung.

**Comment by oswi82** [comment]
Bei mir funktioniert es auch. Ich konnte problemlos einmal die Datei lesen. Jetzt wäre es nötig die Daten regelmäßig zu lesen (jede 10s?) und und in einem Datenpunkt schreiben (oder besser gesagt, dass der Skript automatisch Datenpunkte anlegt und aktualisiert)

Wenn ich helfen kann, einfach sagen wie. Zum testen gerne!

**Comment by dj-mib** [comment]
Ich wollte mir eigentlich eine Entwicklungsumgebung aufbauen und versuchen einen Adapter zu bauen - Da es mir erstmal nicht gelungen ist eine lauffähige IOBroker Instanz unter Windows zu bauen und ich mir den ganzen Rest erst auch noch beibringen müsste, mache ich es jetzt erstmal Quick and Dirty als Javascript mit nem Cron, der zyklisch die Daten abruft.

Ich habe jetzt ein Script entwickelt mit dem man erstmal "was machen" kann.

Mit dem Script werden in einem definierbaren Intervall die Daten aus der Box gelesen und in Datenpunkte geschrieben.
Das Root der  Datenpunkte kann als Konstante vorgegeben werden,

Dazu kann der ChargeMode über ein Command gesetzt werden. 
Ich denke die meisten wollen irgendwann stoppen, wenn das EV einen bestimmten SoC erreicht haben, das sollte damit gehen :)


[myenergi.txt](https://github.com/ioBroker/AdapterRequests/files/8791514/myenergi.txt)

Das Script ist experimentell, wer mag kann es nach Prüfung aber gerne testen.
Vielleicht hab ich irgendwann mal Zeit mich an die Entwicklung eines Adapters zu setzten. Auf meinem produktiven Broker will ich das aber nicht machen und unter Windows hab ich's nicht hinbekommen :( Die Doku von @Apollon77  sieht aber auf den ersten Blick recht gut aus. Mir fehlt hat gerade nur die Zeit...

Feedback, Tipps und Verbesserungsvorschläge von Testopfern sind willkommen :)

**Comment by hobili** [comment]
Hi,

könntest du für einen Dummy eine kurze Anleitung schreiben wie man vorgehen muss um das zum laufen zu bekommen?

LG
Holger

**Comment by MPTrixi** [comment]
@dj-mib Das hört sich doch schon mal gut an. Ich hab zumindest mal nen iobroker auf nem alten Windows Notebook zum Laufen bekommen. Hab aber vom Rest keine Ahnung. Das ganze asynchrone Zeugs inkl. den "Versprechungen" kam lange nach meiner aktiven Programmierzeit :)

Ich hoffe ich kann morgen mal testen. Ich danke aber schon mal vorab.

**Comment by MPTrixi** [comment]
@dj-mib ich konnte heute morgen kurz testen. Habe es auf meinem Windows Test ioBroker versucht. Beim ersten Lauf schmeisst die Console ein paar Warnings. Datenpunkte werden aber angelegt. Habe auch Daten drin die sich aktualisieren. Sieht also soweit gut aus. Super Arbeit. 
Was mir erstmal aufgefallen ist und was noch angepasst werden sollte: in Zeile 18 kann man ja einen eigenen Pfad für die Datenpunkte definieren. Das geht auch, allerdings wird beim setzen des Chargemodes fest auf den ursprünglichen Wert referenziert (hier sollte auch die Variable gezogen werden (Zeile 444)).
Ich schau mal noch die Tage tiefer rein ob die Werte etc passen. Was ich schon versucht habe und 1a funktioniert, ist das Umschalten des Chargemodes (zumindest von ECO+ auf ECO und zurück).

@hobili ich versuche es mal, ist aber nicht schwer:
1. installiere auf deinem ioBroker System das entsprechende npm package auf der Konsole (ob das wirklich gebraucht wird oder automatisch gezogen wird kann ich nicht sagen, ich und auch dj-mib habens aber so gemacht. S. [hier](https://github.com/bisand/myenergi-api#installation)
2. im Script (s. Anhang myenergi.txt) von dj-mib folgende Anpassungen vornehmen:
- Zeile 24: 4711 durch die Seriennummer seines Hubs ersetzen
- Zeile 29: 0815 durch die Seriennummer seiner Zappi ersetzen
- Zeile 35: API-Key durch den erzeugten API-Key ersetzen (s. dazu [hier](https://support.myenergi.com/hc/en-gb/articles/5069627351185))
- Optional Zeile 18: Ich kann nach belieben angegeben werden wo und unter welchem "Verzeichnis" die Datenpunkte angelegt werden sollen. Wird dies geändert muss es aktuell noch in Zeile 444 nachgezogen werden.
3. Im ioBroker unter Skripte ein neues JavaScript erstellen und die angepasste myenergie.txt da reinkopieren und laufen lassen
4. fertisch

wenn man nun in den Datenpunkten einen Datenpunkt unter ...Chargemode auf TRUE setzt (wird gleich wieder FALSE) wird der Lademodus auf den entsprechenden Wert umgestellt.

**Comment by hobili** [comment]
@MPTrixi 

super! Vielen Dank für die Anleitung! 

Funktioniert auf Anhieb - die Warnings kamen auch bei mir, Datenpunkte wurden angelegt und werden regelmäßig gefüllt. 

sehr geil!

**Comment by dj-mib** [comment]
Danke für die Hinweise @MPTrixi 

UPDATE:
[myenergi.txt](https://github.com/ioBroker/AdapterRequests/files/8793427/myenergi.txt)

- Warnings sollten nicht mehr kommen - Nach dem Anlegen der Datenpunkte mit den Commands wollte ich sie mit false initialisieren, kam wohl zu schnell. 
- Trigger wird jetzt entsprechend des definierten dataRoots angezogen
- status, chargerState und chargeMode gibt es jetzt noch einmal als zusätzliche Datenpunkte mit lesbarem Text

Hab ich eigentlich erwähnt, dass ich Javascript hasse? Ich mach eigentlich eher Java und brech mir hier ständig die Finger...

**Comment by oswi82** [comment]
TOP! Super gemacht! bei mir klappt auch alles!

**Comment by MPTrixi** [comment]
Habe eine weitere Erfahrung gemacht, die ich kurz teilen möchte: Nachdem es auf dem Windows-Testsystem gut läuft, wollte ich das Script auf meinem produktiven ioBroker (Raspberry Debian 11,  ioBroker 4.0.23, npm 8.9.0, Admin 5.3.8, Skripte-Adapter 5.2.21) laufen lassen. Erstmal habe ich es ohne npm install myernergi-api versucht. Es kam dann ein Fehler. Also den Befehl auf der Konsole ausgeführt. Leider blieb der Fehler, dass myernergi-api nicht verfügbar sei. Ich musste myenergie-api in der Skripte-Instanz unter zusätzliche NPM-Module eintragen. Erst dann lief es im Produktivsystem (falls jemand auf ähnliche Probleme stößt).

**Comment by MPTrixi** [comment]
Ich hatte es leider anders herum versucht. Also nach dem Fehler erst den npm install auf der Konsole. Danach erst in der Adapterinstanz eingetragen. Komisch finde ich das unterschiedliche Verhalten der Windows- und der Rasp-Installation. Auf der Windowsseite ging es gleich nach dem npm install ohne dass was in der Instanz eingetragen ist. Auf dem Rasp nicht, hier musste es in der Instanz rein...

**Comment by hobili** [comment]
Eine Frage zu dem Lock State:

ich habe da als Wert "16" stehen - egal ob Stecker entfernt oder im Auto oder Ladend ... 

meine Zappi hat ein fest angeschlossenes Kabel, nur zur Info


In einem anderen Beitrag auf Github habe ich das gefunden:

_Lock Status

'lck' - representation of current PIN lock settings and zappi lock status Bit 0: Locked Now Bit 1: Lock when plugged in Bit 2: Lock when unplugged. Bit 3: Charge when locked. Bit 4: Charge Session Allowed (Even if locked)_


Damit kann ich aber leider nichts anfangen; hat da jemand eine Idee?

LG
Holger

**Comment by MPTrixi** [comment]
@hobili bei mir ist es auch 16 (Auto ist grad nicht da ;)).
Denke aber das hat nichts mit dem Ladestatus oder an angesteckt oder nicht zu tun. Es geht darum ob eine PIN in der Zappi vergeben ist (damit nicht fremdgeladen werden kann) und wie damit umgegangen wird. Habe im Netz bei Beispielauszügen der Abfrage bisher auch nur die 16 gefunden. An Doku sonst nicht. Denke wenn Du das brauchst müsstest man mit den Zappi Einstellungen zur PIN rumspielen und schauen wie sich der Wert verändert.

**Comment by hobili** [comment]
@MPTrixi 

ach ja, an diese Funktion hatte ich gar nicht gedacht - stimmt, dann wird es das wohl sein :-)

Brauchen tue ich die Funktion nicht, meine Zappi ist nicht per Code gesperrt.
Danke für den Hinweis!

**Comment by hobili** [comment]
Was macht Ihr bisher mit den Infos und Werten die Ihr aus den Datenpunkten lesen könnt?

ich habe bisher "nur" eine Seite meiner Vis damit ausgestattet (auf dem Screenshot bin ich noch von der Funktion des  verriegelten Steckers ausgegangen ;-) )

Noch eine Frage: Ich kann den Wert von z.B. "Minimum Green Level" in den Objekten verändern aber er ändert sich dann sofort wieder auf den in der Myenergie App eingestellten Wert. Wenn ich diesen in der App ändere wird mir die Änderung dann auch in den Objekten angezeigt... was mache ich da falsch?

![Screenshot_20220530-191138_Fully Kiosk Browser](https://user-images.githubusercontent.com/56883534/171036799-94dfa61c-c88c-48be-bfdf-0eb79bcb8cb1.jpg)
t

**Comment by dj-mib** [comment]
> Noch eine Frage: Ich kann den Wert von z.B. "Minimum Green Level" in den Objekten verändern aber er ändert sich dann sofort wieder auf den in der Myenergie App eingestellten Wert. Wenn ich diesen in der App ändere wird mir die Änderung dann auch in den Objekten angezeigt... was mache ich da falsch?

Hi @hobili , du machst da noch gar nix falsch. Das ist derzeit noch nicht implementiert.
Hab da aber gerade mal 5 Minuten drüber nachgedacht, wie ich erkennen könnte, dass die Änderung über den Broker vorgenommen wurde und nicht über die App. Ich muss ja entscheiden können ob ich den Wert jetzt an die Box schicke oder nicht :D.
Ich wollte es erst auch über ein command machen, aber der Plan ist jetzt das über das Setzen eines unbestätigten Werts zu machen.
Die Werte aus der Box sind immer bestätigte Werte.
Du setzt also z.B. 75 % als unbestätigten Wert. Ich erkenne die Änderung und sende einen Request an die API.
und irgendwann kommt ein Wert von der API zurück, der hoffentlich dem entspricht, was du gesetzt hast.

Hab aber noch nicht geschaut, ob die bisand/myenergi-api das hergibt...

**Comment by hobili** [comment]
@dj-mib 

ups - da war ich wohl ein wenig zu voreilig ;-)

sorry - wollte dich nicht unter Stress setzen! So wie es bisher funktioniert ist schon super...

LG
Holger

**Comment by dj-mib** [comment]
UPDATE: Minimum Green Level kann jetzt im Datenpunkt übergeben werden.
[myenergi.txt](https://github.com/ioBroker/AdapterRequests/files/8808916/myenergi.txt)

- Gibt man keine Zahl ein wird vom Broker der Wert auf 0 gesetzt Werte werden auf Ganzzahl gerundet und Werte < 0 und >100 abgelehnt (Fehler im Log) 
-  der Wert muss als unbestätigt übergeben werden.
- nicht wundern, dass der Wert auf den alten Wert und dann auf den neuen Wert zurückspringen kann. Der Broker spricht nicht direkt mit der Wallbox sondern mit der Myenergi Cloud und es kann einen Moment dauern bis die Kette durch ist,
Auf der Wunschliste steht ja auch, dass man direkt mit dem Hub ohne die Cloud sprechen kann.  Ich nutze zwar Cloud Dienste, bin aber kein Fan davon. (Es gibt keine Cloud - es gibt nur den Rechner eines anderen)
Wenn dieses Zurückhüpfen zum Problem wird, werde ich den Wert wieder readonly machen und das Ändern über einen eigenen Datenpunkt realisieren. Dann bleibt der Wert stabil, bis er im Zappi gesetzt, an das Myenergi Portal weitergegeben wurde und vom Broker beim nächsten Update abgeholt wurde.

**Comment by MPTrixi** [comment]
@dj-mib wollte grad mal Deine Version mit MGL versuchen. Scheint aber Du hast sie wieder rausgenommen. Hat sie nicht so funktioniert wie gewollt?

**Comment by hobili** [comment]
huch, sehe ich ja jetzt erst - hatte gestern die neue Version geholt und installiert, kam aber noch nicht zum testen...

Aber ja - wenn ich den Green Level setze ändert sich nix. Nur um sicher zu gehen: Die Buttons unter Commands funktionieren auch noch nicht, oder?!

**Comment by dj-mib** [comment]
Sorry für das Chaos, bei mir funktionierten die Commands nicht mit dem Script und ich habe gesehen, dass der Datenpunkt für den MGL noch hart verdrahtet war. Daher hab ich das kaputte Release schnell wieder entfernt - wohl nicht schnell genug ;)
Leider musste ich auch bei mir das dataRoot anpassen, da müsst ihr also hingucken und ggfs anpassen. Bei mir wurden irgendwie Werte nicht aktualisiert und auch löschen und neuanleden brachte nichts.

### Hier ein Update, dass hoffentlich besser funktioniert.
[myenergi REL-1_01.txt](https://github.com/ioBroker/AdapterRequests/files/8835323/myenergi.REL-1_01.txt)
   
 **REL-1_01 03.06.22**
- MinimumGreenLevel kann gesetzt werden (als unbestätigter Wert)
- Handling mit Commands angepasst, inkl Reset der CommandButtons auf false nach jedem Poll
- neues dataRoot (bitte ggfs anpassen)
- divisor eingeführt (Volt wird durch 10 geteilt)

**Unhabhängig von diesem Script habe ich noch folgendes für meinen Corsa gebaut:**

- Berechnen einer Energiemenge um einen definierten Soc zu erreichen
Wenn lastCharge kleiner ist als vorher (beim Start eines Ladevorgangs nach dem Einstecken des Kabels) nehme ich den aktuellen SoC des Fahrzeugs (wird normalerweise nach dem Abstellen des Fahreugs halbwegs zuverlässig aktualisiert)
Aus der Different errechne ich eine Lademenge.
Leider übermittelt das Fahrzeug nicht regelmäßig genug um zuverlässig bei z.B. 80% zu stoppen.

- Erreicht lastCharge die errechnete Lademenge stoppt die Ladung und schickt mir eine Nachricht aufs Handy (z.B Pushover, Telegram oder Whatsapp)


- Wird zwischendurch das Ladeziel von zb. 80 auf 90% erhöht wird die Differenz errechnet und die Lademenge angepasst. (der aktuelle SoC ist in KOmbination mit lastCharge nicht wirklich brauchbar)

**Comment by hobili** [comment]
Hallo Michael,

funktioniert wie von dir beschrieben - mit einer kleinen Verzögerung - aber einwandfrei.

kann es sein, dass im Script deine Serials und Api drin stehen? Nicht, dass da jemand was mit anfangen kann...

Vielen Dank für deine Arbeit!

LG
Holger

**Comment by dj-mib** [comment]
> script.js.common.Zappi: Zappi MGL: null konnte nicht gesetzt werden. {"status":"-14","statustext":""}

@hobili 
Der Fehler sieht doof aus, aber ist nicht schlimm. Ist bei mir wohl nicht aufgetreten, da der Datenpunkt schon da war. 
Bin nicht davon ausgegangen, dass der Trigger da schon ausgelöst wird. Könnte da noch auf null prüfen, damit das nicht passiert.

Serials hab ich nochmal rausgenommen, der API Key ist eh schon ein neuer. Also alles gut. Trotzdem doof von mir. 
Passiert, wenn hier dauern Kinder dazwischen funken.
Werde das mal ändern, so dass die Nummern in Datenpunkte eingetragen werden und nicht im Script stehen müssen.

Next Step wäre dann aber eigentlich ein Adapter, aber dafür muss ich die drei Kinder loswerden :)

**Comment by MPTrixi** [comment]
Nach Urlaub etc konnte ich mir es auch endlich mal anschauen. Wieder einmal danke. Habe noch zwei Fragen dazu:
@dj-mib bei den zwei Abschnitten zu dem MGL Triggern ist "0_userdata.0.zappiTest2.minimumGreenLevel" festverdrahtet. Sollte das nicht auch auf die Dataroot-Variable gehen?

UND: ich vermisse im neuen Script den Abschnitt mit 
on({id: Array.prototype.slice.apply($("state[id="+ dataRoot +".commands.chargemode.*]")), change: "gt"}, async function (obj)...
Damit lies sich doch im alten der Lademodus umschalten. Geht das dann mit dem neuen nicht mehr oder gibts einen Grund warum das raus ist?

**Comment by SpitfireXP** [comment]
Hallo zusammen,
ich habe das Script bei mir für meine beiden Zappi's eingerichtet.
Aber die APP funktioniert nicht mehr.
Wenn ich die öffne, bekomme ich den Hinweis das es einen Kommunikationsfehler gibt und ich das Passwort ändern kann.

Hat das Problem noch jemand?

**Comment by dj-mib** [comment]
Hi @SpitfireXP,
habe da leider wenig hilfreiches parat.
Werden Hub und Deine Zappis denn noch korrekt im Portal bei Myenergi angezeigt?
https://myaccount.myenergi.com/location#products

Vielleicht mal aus der App abmelden und neu anmelden.

**Comment by wzwerch** [comment]
Habe gerade das Script innerhalb von 15 Minuten installiert und funktioniert super !! Vielen Dank für die super Arbeit !!!

**Comment by dj-mib** [comment]
Ich habe für das Script mal ein Projekt in Github aufgemacht: https://github.com/dj-mib/iobroker.zappi
Wenn es Änderungen geben sollte dann dort. Damit sollte dieser Thread hier frei werden für nen richtigen Adapter.

**Comment by Apollon77** [comment]
@dj-mib Kannst bitte umbenennen und das iobroker. rausmachen, sonst verwechsekln es User mit nem Adapter und versuchen es zu installieren :-)

**Comment by dj-mib** [comment]
> @dj-mib Kannst bitte umbenennen und das iobroker. rausmachen, sonst verwechsekln es User mit nem Adapter und versuchen es zu installieren :-)
@Apollon77 ist erledigt. Habs nur nachgemacht :D https://github.com/volkerrichert/ioBroker.ecotouch
Ist auch nur ein Script, dass sich nicht als Adapter installieren ließe.

**Comment by dzirbes00** [comment]
danke auch von meiner Seite, hatte lange nach was brauchbaren für die Zappi gesucht. Funktioniert einwandfrei nach der Anleitung.

**Comment by JMHTB** [comment]
Hi Leute, genau das habe ich gesucht. Super Projekt. Vielen Dank für die Mühe!!!
Allerding benutze ich einen Hari, CT1-CT3 sind deaktiviert. CT4-CT6 sind für den Harvi.
Doch die werte schwanken im unteren 1-10watt Bereich.  Grid wird ziemlich genau angezeigt die auch mit den CT4-6  klemmen gemessen werden.  Den Havi habe ich nicht mit einer Seriennummer im Scrip hinzugefügt. Hat einer eine Idee? LG

**Comment by dj-mib** [comment]
Hallo @JMHTB, den Harvi unterstütze ich nicht wirklich. Es kann also sein, dass du mit den CT Werten dann nichts anfangen kannst. Kann auch sein, dass dann keine brauchbaren Werte von der API zurück kommen und die Warning im Log landet. Das kann ich leider nicht testen.

Den aktuellen Ladestrom solltest du aber in "diversion" sehen und die anderen Status und Commands sollten auch passen.

Ich habe leider nur ein Script gebaut, das für meinen Anwendungsfall passt. Eigentlich hätte man auf Hub Ebene schauen müssen was alles darunter hängt (Zappis, Eddis und Harvis) und danach die Struktur nach Seriennummer der gefundenen Geräte aufbauen müssen. 

Oder funkioniert was anderes nicht?

**Comment by oswi82** [comment]
Hallo zusammen, 

ich habe auch ein Eddi, welche hoffe bald in Betrieb nehmen zu dürfen. Wäre möglich den Skript um die Eddi zu erweitern?

**Comment by JMHTB** [comment]
> Hallo @JMHTB, den Harvi unterstütze ich nicht wirklich. Es kann also sein, dass du mit den CT Werten dann nichts anfangen kannst. Kann auch sein, dass dann keine brauchbaren Werte von der API zurück kommen und die Warning im Log landet. Das kann ich leider nicht testen.
> 
> Den aktuellen Ladestrom solltest du aber in "diversion" sehen und die anderen Status und Commands sollten auch passen.
> 
> Ich habe leider nur ein Script gebaut, das für meinen Anwendungsfall passt. Eigentlich hätte man auf Hub Ebene schauen müssen was alles darunter hängt (Zappis, Eddis und Harvis) und danach die Struktur nach Seriennummer der gefundenen Geräte aufbauen müssen.
> 
> Oder funkioniert was anderes nicht?

Danke für deine schnelle Antwort.
Ich habe einfach in den Objekten, den Ordner für die Zappi gelöscht, und das Script neu gestartet. Jetzt wird mir der wert an CT1 obwohl durch den Harvi deaktiviert, angezeigt. Mir ist es egal wo der wert steht, Hauptsache er wird angezeigt. Fazit: es funktioniert ! Danke danke danke!

**Comment by juggi1962** [comment]
Hallo an den Entwickler des tollen Myenergi Skript.
Ich habe ein Problem und zwar wenn der Myenergi Hub die Verbindung mal zum Myenergi Server verliert (was in letzter Zeit ein paar mal passiert ist, Serverprobleme bei Myenergi) dann versucht das Skript sich immer wieder neu einzuloggen. und nach ein paar Fehlversuchen hängt sich der Javascipt Adapter auf und nichts geht mehr. Im Host muss man dann eine Meldung bestätigen und dann kann man den Javscrip Adapter wieder neu starten. Kann man da was dagegen machen? 
Bin nur Anwender und hab davon leider keine Ahnung.
Vielleicht kann man da ja im sonst so tollen JV Skript was ändern.
Danke für eure Hilfe juggi1962

**Comment by oswi82** [comment]
Hab das selbe Problem! Bin auch interessiert!

**Comment by dj-mib** [comment]
Ich habe das selbe Problem, das liegt aber leider nicht an meinem Script sondern an der verwendeten API.
Das Problem ist auch dort schon als Problem gemeldet worden.

https://github.com/bisand/myenergi-api/issues/4

Vielleicht meldet ihr euch auch als Betroffene und der Entwickler baut einen fix. Ich habe übergangsweise einen eigenen JS Controller für das Zappi Script. Wenn der abstürzt bekomme ich eine Benachrichtigung und kann reagieren.

**Comment by MPTrixi** [comment]
Hab auch Probleme und es dort gemeldet. 

Evtl. Offtopic: Wie lässt du einen eigenen Controller dafür laufen (ist das eine weitere Instanz vom NS Adapter? Woran sehe ich warum JavaScript beendet wurde? Habt ihr zZt auch in der myenergi App (bei mir IOS) eine unvollständige Anzeige?

**Comment by juggi1962** [comment]
> Habe es [hier](https://github.com/bisand/myenergi-api/issues/4) ( [bisand/myenergi-api#4](https://github.com/bisand/myenergi-api/issues/4) ) auch schon kommentiert.
> 
> Nur zur Info: Solange das Problem nicht behoben ist, habe ich eine zweite Javascript-Instanz im ioBroker installiert. Dort läuft nur das ZAPPI Script. Sollte es wieder zum Absturz kommen, laufen die anderen Scripts weiter und meine Hausautomation funktioniert weiter.
> 
> Das nur so als Tipp.
> 
> VG, Alex

Super Tipp danke. Hab ihn gerade umgesetzt.
Hoffentlich kann man es für immer fixen.

**Comment by dj-mib** [comment]
> Wie lässt du einen eigenen Controller dafür laufen (ist das eine weitere Instanz vom NS Adapter?
Genau, eine weitere Instanz vom JS Controller installieren und dann kannst du bei den Scripten auf das Script klicken, dann auf das Symbol mit dem Bleistift. Dann ist es möglich zu entscheiden, in welcher der Instanzen das Script laufen soll.
![grafik](https://user-images.githubusercontent.com/93519503/189940579-e1c78bb7-c298-40f0-bd6e-f7b914b890b6.png)

**Comment by MPTrixi** [comment]
Super. Danke für den Tipp. Werde es versuchen.  Habt ihr auch sporadisch die unvollständige Anzeige in der myenergi App?

**Comment by juggi1962** [comment]
Kann mir bitte jemand sagen wie ich zu dem verbesserten Skript 2.0 komme, oder im ioBroker installiere?
Kenn mich hier leider überhaupt nicht aus.
Danke im Voraus

**Comment by TA2k** [comment]
Der Beitrag hat 43 votes besteht denn trotz des Skripts noch Interesse an einem Adapter?
Wenn ja bräuchte ich mal eine Seriennummer und api key

**Comment by SpitfireXP** [comment]
Ich denke das ein Adapter schon schöner/besser wäre.
Ich kann dir meine Daten geben wenn es dir hilft.

**Comment by dzirbes00** [comment]
da schließe ich mich an, habe es zwar auch über die Script Lösung am Laufen, aber eine Adapter Lösung, wäre wie Spitfire schon sagt wohl eine saubere Lösung.
Danke schon mal im Voraus für deinen Einsatz.

**Comment by TA2k** [comment]
ok dann gerne an tombox2020@gmail.com was schicken

**Comment by dzirbes00** [comment]
@TA2k : hast du schon seriennummer und api bekommen zum testen? Ansonsten schicke ich dir was zu.

**Comment by TA2k** [comment]
Hab schon eine . Ich mach das heute Abend schnell

**Comment by TA2k** [comment]
Bitte mal testen ob es so funktioniert
https://forum.iobroker.net/topic/60175/test-myenergi-adapter

**Comment by mcm1957** [comment]
Link zum Adapter:
https://github.com/iobroker-community-adapters/ioBroker.myenergi

**Comment by mcm1957** [comment]
Request to add to latest seems to be pending:
https://github.com/ioBroker/ioBroker.repositories/pull/2037

**Comment by mcm1957** [comment]
Adapter ist nu n im repository verfügbar (latest)

Bitte alle Issues und  Featurerrequestst im Adapterverzeichnis (https://github.com/iobroker-community-adapters/ioBroker.myenergi) eintragen.

@TA2k Danke für deine Arbeit
