### ISSUE TITLE
Wiegand Protokoll

### ISSUE THREAD

**Issue by Endorian88** [ioBroker/AdapterRequests#655]
Hi, 
ist es evtl. möglich einen Adapter für das Wiegand Protokoll zu schreiben? Es gibt ein paar Ansätze um einen Wiegand fähigen Reader(RFID,Pin,Fingerprint) an einem Raspberry an zu schließen und in dann per Script ab zu fragen. 

Schön wäre ein Adapter an dem die GPIOs eingestellt werden können an denen der Reader hängt (D0/D1). Zudem sollte ein Ablegen der Nutzernummer in einem Datenpunkt möglich sein. 
Hier noch der Ansatz den ich bereits gefunden habe.
https://github.com/reals79/wiegand-node

und die Arduino Library dafür.
https://github.com/monkeyboard/Wiegand-Protocol-Library-for-Arduino

MfG

**Comment by ldittmar81** [comment]
https://www.npmjs.com/package/iobroker.wiegand-tcpip
