### ISSUE TITLE
Netro Whisperer - Solar power plant sensor

### ISSUE THREAD

**Issue by JHA-2021** [ioBroker/AdapterRequests#659]
Netro Whisperer is a sensor for ground moisture, temperature and sun intensity and can be used in irrigation systems. The power is provided by solar power and connects via WLAN to the cloud. https://www.netrohome.com/en/shop/products/whisperer 

**Is an official API including documentation is available?**
Yes, complete description with examples: https://www.netrohome.com/en/shop/articles/10

**Are other libraries for an integration available?**
No Info.

**Is this device already integrated in other Smart Home systems?**
No Info.

**Is this device already integrated in homebridge? Might the ham adapter together with the homebridge plugin be sufficient?**
No Info.

**Additional context**
No Info.

**Comment by JHA-2021** [comment]
Kann Dir mal einen als Leihgabe schicken.

**Comment by Apollon77** [comment]
Nicht mir, aber ggf freut sich der Dev der Zeit findet dafür :)

**Comment by JHA-2021** [comment]
Daran sollte es nicht scheitern.

**Comment by realhawker** [comment]
Ich habe mal eine erste Version gebaut, weil ich die Sensoren selbst einsetzen will. Die Version ist weit weg von perfekt und kann bisher nur über die github URL installiert werden, aber vielleicht hilft dir das ja schon mal weiter: https://github.com/realhawker/ioBroker.netro

**Comment by JHA-2021** [comment]
Super! Vielen Dank! Da bist Du mir jetzt zuvor gekommen. Wollte mich schon selber dran machen. Schau ich mir gleich mal an.

**Comment by JHA-2021** [comment]
Funktioniert bestens! Klasse.

**Comment by Apollon77** [comment]
@realhawker Please request repo addition ... details see https://github.com/ioBroker/ioBroker.repositories

@JHA-2021 Please do not close before it is released for all :-)

**Comment by realhawker** [comment]
Ich hoffe ich habe alles richtig gemacht: https://github.com/ioBroker/ioBroker.repositories/pull/1445

**Comment by ldittmar81** [comment]
Kann eigentlich hier geschlossen werden oder? Ist ja kein Wunsch mehr :-)

**Comment by Apollon77** [comment]
But also not officially released :-)
