### ISSUE TITLE
Home Assistant Adapter

### ISSUE THREAD

**Issue by steckenpferd** [ioBroker/AdapterRequests#66]
https://www.home-assistant.io/components/#all

![grafik](https://user-images.githubusercontent.com/39061622/39716248-16e70fea-5230-11e8-9c79-d1f912fbf777.png)

**Comment by Apollon77** [comment]
@GermanBluefox already tried to start here (https://github.com/ioBroker/ioBroker.hass) but when I remember he had problems and did not found a solution for these ... But he could add more information

**Comment by GermanBluefox** [comment]
The community was so helpful.... That I could not follow the development.
Here is my question: https://community.home-assistant.io/t/websocket-or-rest-api-and-groups/46537/3

**Comment by steckenpferd** [comment]
Ja, Schade das keiner aus der Home Assistant Community bei der Frage reagiert hat.

**Comment by steckenpferd** [comment]
Die HASS Community hat reagiert:
https://community.home-assistant.io/t/websocket-or-rest-api-and-groups/46537/5

**Comment by Apollon77** [comment]
To get groups and zones, query the states via the websocket api https://developers.home-assistant.io/docs/en/external_api_websocket.html#fetching-states 23

**Comment by ldittmar81** [comment]
There are 2 adapters: https://github.com/ioBroker/ioBroker.hass and https://github.com/smarthomefans/ioBroker.hass-mqtt
