### ISSUE TITLE
Adapter zum simulieren von SMA Homemanager kompatiblen Geräten

### ISSUE THREAD

**Issue by vstefan30** [ioBroker/AdapterRequests#662]
Beim SMA Homemanager 2.0 kann man über das Sunnyportal verschiedene Geräte einrichten und steuern lassen. Dies geht aber leider nur mit Geräten die auf dieser Liste https://www.sma.de/fileadmin/content/global/Products/Documents/Monitoring_Systems/shm-2.0/SMA-Sunny-Home-Manager-2.0-Kompatibilitaetsliste-Verbraucher.pdf stehen. Dazu gehören z.B. die Fritz Funksteckdose, einige Wallboxen von Mennekes, einige Wärmepumpen  sowie  einige weiße Ware. Das schöne daran ist, dass man im Portal auch die entsprechenden Verbräuche direkt sieht, Statistiken erstellt werden, man Prioritäten setzten kann und das ganze Wettervorhersagenbasiert ist. Das kann man zwar sicherlich auch über Skripte im ioBroker lösen aber als Laie tut man sich das doch ehr schwer. 
Ein Adapter, in dem man die Objekte zum Schalten sowie ggf. Stromverbrauch auswählt und der dem Homemanager dann simuliert es wäre ein kompatibles Gerät wäre super. Ähnlich wie der SmartApplianceEnabler es macht https://github.com/camueller/SmartApplianceEnabler. 
Der einzige Nachteil am SmartApllianceEnabler ist, dass man zwei getrennte System hat.
Gruß
Stefan

**Comment by Apollon77** [comment]
AM Ende bräuchte man eine Info wie ein "kompatibles protokoll" aussieht

**Comment by vstefan30** [comment]
Hallo Apollon77,
ich denke das läuft über  die SEMP Schnittstelle. Unter https://www.sma.de/produkte/sma-developer.html
gibt es ein SEMP_Development_Kit zum Downloaden, ich hoffe da ist alles beschrieben.
Gruß
Stefan

**Comment by Apollon77** [comment]
Myaybe this could be a good startpoint https://github.com/orlopau/semp

**Comment by Apollon77** [comment]
@rg-engineering You got an invite

**Comment by rg-engineering** [comment]
Adapter is now in latest, so I close the request... 

see https://github.com/rg-engineering/ioBroker.semp
