### ISSUE TITLE
Bestway / Lay-Z-Spa (Milan) App Control Adapter

### ISSUE THREAD

**Issue by x-traxion** [ioBroker/AdapterRequests#665]
**What kind of device or service you would like to see an adapter for?**
Bestway bzw. Lay-Z-Spa Wifi App Control Modelle zB. Milan
[https://www.bestwaystore.de/lay-z-spa-whirlpools/lay-z-spa-whirlpools/airjet-plus-whirlpools/3238/lay-z-spa-milan-airjet-plus-wifi-whirlpool-196-x-71-cm-mit-app-steuerung-4-6-personen-rund-bl](url)

**Is an official API including documentation is available?**
soviel ich weiß nicht. zumindest habe ich nichts gefunden

**Are other libraries for an integration available?**
Für OpenHab gibt es Layzspa2MQTT
[https://github.com/sikksakk/LazySpa2MQTT](url)

**Is this device already integrated in other Smart Home systems?**
ja, OpenHab siehe oben

**Is this device already integrated in homebridge? Might the ham adapter together with the homebridge plugin be sufficient?**
nein

**Additional context**
Steuerbar ist der Pool entweder über die alte Lay-Z-Spa App oder die neue Bestway App.

**Comment by TA2k** [comment]
Wenn du Zugangsdaten zu der App hast kann ich schnell ein Adapter erzeugen einfach via iobroker Forum melden
https://forum.iobroker.net/user/tombox

**Comment by TA2k** [comment]
https://forum.iobroker.net/topic/48023/test-adapter-bestway-v0-0-x

**Comment by ldittmar81** [comment]
Kann geschlossen werden... ist im latest
