### ISSUE TITLE
Adapter zur Berechnung der Verbräuche wie z.B Sourceanalytix

### ISSUE THREAD

**Issue by Jeba0815** [ioBroker/AdapterRequests#666]
Einen funktionierenden Adapter zur Berechnung der Verbräuche wie z.B Sourceanalytix,würde mit Sicherheit nützlich.

**Comment by Apollon77** [comment]
Meint der Feature Request das Sourceanalytic nicht tut und man deswegen noch einen Adapter schreiben sollte anstelle den zu fixen?

**Comment by DutchmanNL** [comment]
> Einen funktionierenden Adapter zur Berechnung der Verbräuche wie z.B Sourceanalytix,würde mit Sicherheit nützlich.

Was fehlt dir den in SA?

**Comment by ldittmar81** [comment]
Ich denke man kann das schließen, denn wir haben ein Adapter um Verbrauch zu berechnen: es heißt Sourceanalytix und wenn da was fehlt, sollte dort ein Issue angelegt werden.
