### ISSUE TITLE
Untis / Webuntis Stundenplan 

### ISSUE THREAD

**Issue by Elektrickser** [ioBroker/AdapterRequests#673]
**What kind of device or service you would like to see an adapter for?**
https://www.untis.at/produkte/webuntis-das-grundpaket

**Is an official API including documentation is available?**
https://hexdocs.pm/webuntis/api-reference.html
The official documentation can get from untis.at per mail.

**Are other libraries for an integration available?**
https://python-webuntis.readthedocs.io/en/latest/index.html

**Additional context**
Hi, 

i need this content in my iobroker.

**Comment by Newan** [comment]
Soll dan nur der Stundenplan des eingeloggten Benutzer angezeigt werden oder was ist die Idee?

**Comment by Elektrickser** [comment]
Hi 

Ja das wäre der erste Schritt.

Leider schaffe ich es nicht einen Anfang zu finden. Ich arbeite gerne am Projekt mit und helfe wo ich kann. Aber von Grund auf ein Projekt zu stemmen, das liegt mir "noch" nicht. Dazu fehlt mir die Praxis im Programmieren.

Klar wäre es schön weitere Funktionen wie Mitteilungen einzupflegen, aber der aktuelle Stundenplan wäre schon erstmal was. 
ggf. dann auch für mehrere Kids. Aber das sollte ja mit mehreren Instanzen funktionieren.

**Comment by ldittmar81** [comment]
Es gibt eine JS API dafür - https://github.com/SchoolUtils/WebUntis

Außerdem hat jemand scheinbar schon damit begonnen, aber es wurde leider nicht weiter gemacht: https://github.com/NagelMichael/iobroker.webuntis

**Comment by Newan** [comment]
Meine Kids sind noch in der Kita also müsste mir mal jemand einen Account senden: info@newan.de Schaue ich mal bei

**Comment by Elektrickser** [comment]
Hier hab ich noch was gefunden:
https://github.com/SchoolUtils/WebUntis

https://openbase.com/js/untis-api/documentation
https://hexdocs.pm/webuntis/api-reference.html

**Comment by ldittmar81** [comment]
@Newan hast du Daten bekommen?

**Comment by Newan** [comment]
> @Newan hast du Daten bekommen?

Nein

**Comment by ldittmar81** [comment]
> > @Newan hast du Daten bekommen?
> 
> Nein

Done

**Comment by Newan** [comment]
Please test the first try :https://github.com/Newan/ioBroker.webuntis

**Comment by Newan** [comment]
Discussion please here: https://forum.iobroker.net/topic/51690/tester-neuer-adapter-webuntis
