### ISSUE TITLE
PID Regler

### ISSUE THREAD

**Issue by fu-zhou** [ioBroker/AdapterRequests#677]
Hallo zusammen,

ich brauche einen PID Regler zur Integration im Blockly-Skript. Ich könnte mir auch einen Adapter vorstellen, in dem man in den Instanzeinstellungen die Regler-Parameter einstellt (kp, tv, tn, ggf. Zykluszeit) und das Objekt des Istwerts und des Sollwerts angibt sowie die Grenzen und Einheit des Stellwertes (z.B. 0-100%, 0-10 kW), wobei der Stellwert ein (neues) Objekt ist. Hat das von euch schon mal jemand gelöst?
Danke vorab und Grüße!

**Comment by BenAhrdt** [comment]
Ich wäre auch interessiert an einem PID Regler

**Comment by mcm1957** [comment]
> Ich wäre auch interessiert an einem PID Regler

Statt me too postings BITTE ein Thumbs Up im ersten Beitrag

**Comment by mcm1957** [comment]
I will check the request.

**Comment by BenAhrdt** [comment]
@mcm1957 ok. A nice function (i habe Seen at a control tecnic manufacturer) Is a flag to reset the part of the „i“.
This Silvester many Problems and Is very easy to implent
(IPart = 0)

**Comment by BenAhrdt** [comment]
@mcm1957 gibt es schon ein repo, was man mal ansehen kann?

**Comment by mcm1957** [comment]
Adapter will be available as community adapter:
https://github.com/iobroker-community-adapters/ioBroker.pid

Currently only the first draft of json based config is checked in. Working oin envertech-pv took longer then expected.

**Comment by BenAhrdt** [comment]
The Adapter will ne ne in stable ohne time ?

**Comment by mcm1957** [comment]
Sorry, versteh den Satz nicht.
Sorry do not understand.

**Comment by mcm1957** [comment]
Of course this adapter will be published at latest and stable repo as soon as he is completed and tested.

"Adapter will be available as community adapter:" only indicates that it is stored at the iobroker-community organization and not at a personal repository.

Currently I cannot promise any timeframe for sure, but I thing a beta version could be available within the next two weeks

**Comment by mcm1957** [comment]
request to latest: https://github.com/ioBroker/ioBroker.repositories/pull/2274

**Comment by mcm1957** [comment]
released
