### ISSUE TITLE
Meater Cloud Adapter request

### ISSUE THREAD

**Issue by bacardy1000** [ioBroker/AdapterRequests#678]
**What kind of device or service you would like to see an adapter for?**
Add name and company of the device, including links to the device and any additional informations[...]
Meater Cloud https://store-de.meater.com/products/meater-plus

**Is an official API including documentation is available?**
If yes please add links and informations[...]

https://github.com/apption-labs/meater-cloud-public-rest-api

**Are other libraries for an integration available?**
Ideally in JavaScript/npm, but also other programming languages are interesting, add Links please

**Is this device already integrated in other Smart Home systems?**
Add Links please

https://www.youtube.com/watch?v=wNoLfMWJnSs

**Comment by bacardy1000** [comment]
@Apollon77  Soll ich dir mein Meater + für 1 Monat schicken?

**Comment by ldittmar81** [comment]
@bacardy1000 was dringender ist, sind Entwickler mit Zeit. :-)

**Comment by rohabu** [comment]
@Apollon77 ich könnte auch ein Meater + zur Verfügung stellen

**Comment by maniac-io** [comment]
Würde mich auch über einen Adapter freuen. ;)

**Comment by Apollon77** [comment]
@rohabu @maniac-io Bitte oben Daumen hoch setzen ... sonst sieht Eure Interesse niemand

**Comment by rohabu** [comment]
@Apollon77 habe ich beim Ursprungsbeitrag schon gemacht. Oder noch woanders? 🤔

**Comment by Apollon77** [comment]
Alles gut ...  hatte übersehen das du schon hattest

**Comment by Standarduser** [comment]
Ein erstes JS-Script hatte ich kürzlich im Forum vorgestellt:
https://forum.iobroker.net/topic/59632/meater-grillthermometer-script-und-vis

Aktuell versuche ich, das Script in einem Adapter zu verpacken.

**Comment by mcm1957** [comment]
@Standarduser 
Wen ich das richtig lese, dann bist du an einem Adapter dran. Ich setz den REquest mal auf work-in-progress.
Falls du die Arbeit am Adapter aus welchem Grund auch immer einstellst, trag das bitte hier ein. Ebenso wenn eine erste Version released wird.
Danke

**Comment by Standarduser** [comment]
Das erste Release habe ich als v0.1.0-alpha.0 veröffentlicht.
Auch wenn alpha eher eine halbgare Version erwarten lässt läuft es bei mir schon einwandfrei.

**Comment by mcm1957** [comment]
Wenn es einwandfrei läuft wär es sinnvoll (sofern nicht eh schon geschehen)
-) eine vx.y.z zu machen (sinnvoler Weise gleich mit dem Release script)
-) eine Aufnahme des Adapters in das repo (latest repo) zu beantragen. Siehe https://github.com/ioBroker/ioBroker.repositories#readme. (Keine Angst - mir ist nichts von abgerissenen Köpfen etc. bekannt. Anmerkungen sind immer nur sehr sachlich)

Sobald im Latest kann hier geschlossen werden und weitere Probleme / Erweiterungen über das Adapter Repo abgewickelt werden,

**Comment by rohabu** [comment]
Ich habe eben entdeckt, dass der Adapter aufgrund einer Restart Loop deaktiviert wurde.
Ich habe das erst einmal ignoriert, den Adapter auf Debug gesetzt und neu gestartet und beobachte das ganze mal.

**Comment by mcm1957** [comment]
@rohabu 
Da der Adapgter nunmehr prinzipiell existiert und es ein Adapter Repository gibt, rege ich an (potenzielle) Fehler im jeweiligen Adapter Repo zu loggen. Dort kann man diese besser tracken.

**Comment by Standarduser** [comment]
@rohabu
Auf meinem Testsystem hatte ich das auch, kann es jedoch ebenso nicht mehr nachvollziehen. Wenn es wieder auftritt eröffne gerne ein Issue direkt beim Adapter-Repository.

**Comment by mcm1957** [comment]
Adapter now available at repository (latest)

Please report all issues and feature requests at the adapter repository (https://github.com/Standarduser/ioBroker.meater).

@Standarduser Thanks for your work.
