### ISSUE TITLE
Bresser 7-in-1 Weather Station

### ISSUE THREAD

**Issue by mahoso** [ioBroker/AdapterRequests#679]
**What kind of device or service you would like to see an adapter for?**

Direct reception of data from the Bresser device into iobroker (without using adapters the retrieve the data from a cloud service).

Today, Aldi Nord (Germany), offers a Bresser Weather Center [Link](https://www.aldi-nord.de/angebote/aktion-do-28-10/wlan-clearview-wettercenter-1016215-0-0.article.html) 

On Bresser‘s website: [Link](https://www.bresser.de/Wetter-Zeit/Wettercenter/BRESSER-WLAN-ClearView-Wettercenter-mit-7-in-1-Profi-Sensor.html) 

It offers a GUI for setting up cloud hosted weather services wunderground and weathercloud AND a URL entry, namely for Awekas.

It would be very helpful to receive the data (temp, humidity, atmospheric pressure, UV, brightness, wind speed & direction) directly from the device instead of using the wunderground adapter.

The URL to be entered might be an easy way to achieve this integration into iobroker? As a noob in developing adaptors I have no idea how to program this - but I am pleased to test, if anyone gives me directions. 🙂

![CBCC4A92-78A8-4865-AFE4-0E4063EFE3C6](https://user-images.githubusercontent.com/67734159/139281264-204c32cc-9a92-4914-b5d1-4077bab00609.jpeg)
 

**Is an official API including documentation is available?**

Not from the device, but Awekas seems to be documented.

**Are other libraries for an integration available?**

Dunno

**Is this device already integrated in other Smart Home systems?**

Via wunderground adaptor into iobroker.

**Is this device already integrated in homebridge? Might the ham adapter together with the homebridge plugin be sufficient?**

Haven‘t checked this

**Additional context**
Info from the Bresser manual:
![BEAF6A7C-8897-4A07-8BA1-AAC9E1F0C1CF](https://user-images.githubusercontent.com/67734159/139284591-c2232d00-6f7f-46d6-ad74-e2f4ca5e0364.jpeg)

After you created the issue vote for yourself in the first post of the issue using the "+1"/"Thumbs up" button

**Comment by mahoso** [comment]
Solved it with node red low code. Thanks for your support.

**Comment by nsitt** [comment]
mahoso, I am trying to do the same and would appreciate if you could explain how you managed to to this with node red. thanks
