### ISSUE TITLE
SENEC V3 hybrid  Battery

### ISSUE THREAD

**Issue by marttigarden** [ioBroker/AdapterRequests#680]
It would be great to read out the data from the SENEC V3 hybrid battery as well (as other projects already seem to do). This would allow to create actions based on PV power generation or battery charge status.

https://senec.com/de/produkte/senec-home-v3-hybrid

Thank you! :)

**Comment by Apollon77** [comment]
Any more links? Libaryrioes existing? Other smart home system supporting it? (There were some more questions in teh template)

**Comment by marttigarden** [comment]
I found the following:

Library to get all data from V3:

https://gist.github.com/smashnet/82ad0b9d7f0ba2e5098e6649ba08f88a

Projects that are already using it:

https://github.com/DeBaschdi/docker.solaranzeige

**Comment by marttigarden** [comment]
Please hold off investigation for now. Seems like the very old adapter for the previous V2.1 generation might still work for the new device.  I will test that first.

**Comment by ldittmar81** [comment]
@marttigarden does it works?

**Comment by dwm66** [comment]
I'm using the Senec adapter together with a v3-hybrid ... definitely working

**Comment by mcm1957** [comment]
@dwm66
Do you refer to  https://github.com/nobl/ioBroker.Senec ? Please confirm or let us know the exact adapter reference so that we can close her. Thanks

**Comment by dwm66** [comment]
Yes, thats the adapter I have installed. Definitely can confirm it works also with v3 hybrid.

**Comment by Apollon77** [comment]
yes, I confirm it too

**Comment by mcm1957** [comment]
Is available at LATEST repo
Please report issues or feture requests at adapter repo  https://github.com/nobl/ioBroker.Senec
