### ISSUE TITLE
VeSync / Levoit air purifier / Etekcity Plugs and Lights

### ISSUE THREAD

**Issue by raphpa** [ioBroker/AdapterRequests#686]
**What kind of device or service you would like to see an adapter for?**
An adapter for the Levoit air purifier Core 300S/400S. Additionally Etekcity plugs and lights can also be controlled via the same API.

**Is an official API including documentation is available?**
There is no official API documentation, but a working python library. 

**Are other libraries for an integration available?**
Updated and working python library: [https://github.com/webdjoe/pyvesync](https://github.com/webdjoe/pyvesync)

**Is this device already integrated in other Smart Home systems?**
The devices are integrated into Home Assistant via the mentioned python library: [https://www.home-assistant.io/integrations/vesync/](https://www.home-assistant.io/integrations/vesync/)

**Is this device already integrated in homebridge? Might the ham adapter together with the homebridge plugin be sufficient?**
There seem to be homebridge implementations, but none of them works particularly well with ham adapter.
[https://github.com/RaresAil/homebridge-levoit-air-purifier](https://github.com/RaresAil/homebridge-levoit-air-purifier)
[https://github.com/mickgiles/homebridge-vesync](https://github.com/mickgiles/homebridge-vesync)

**Additional context**
It is possible to already use the smart home devices by adding them to Home Assistant and using the HASS bridge adapter. But it would be nice to see it supported natively.

**Comment by DiTechRacer** [comment]
Ich hoffe da kommt was. Habe mir auch den 300S geholt. Würde den gerne per Homematic IP Wandthermostat steuern..

**Comment by stenmic** [comment]
Würde mich auch über einen Adapter freuen. Aktuell löse ich es über ein HAM Plugin. Es funktioniert aber nur die Hälfte.

Die Hardware hätte ich…

**Comment by martin2705** [comment]
Hallo zusammen, ich würde micha uch übner einen direkten Adapter freuen, die funktionalität über das HAM Plugin ist sehr geschränkt. Ich selber habe vier 600S die ich damit gern steuern würde.

**Comment by Apollon77** [comment]
@martin2705 then a thumbs up on first post is muuuch better than me too posts :-) this is the onlxy visible

**Comment by oobyx** [comment]
Würde mich ebenfalls freuen :)

**Comment by Apollon77** [comment]
@oobyx Wenn dem so ist dann würde mich freuen wenn Du im ersten Post nen Daumen Hoch machst anstelle dem "mee too" Post ... Weil sonst sieht keiner das Du dich freuen würdest

**Comment by nifu777** [comment]
"Daumen Hoch" im 1. Post ergänzt - bin auch stark interessiert! :)

**Comment by domvo** [comment]
Ist schon jemand dran an der Entwicklung?

**Comment by TA2k** [comment]
Wenn noch niemand dran ist kann ich schnell ein Adapter erzeugen wenn mir jemand Zugangsdaten gibt

**Comment by martin2705** [comment]
Was brauchst du genau?
Ich hab 4 Geräte stehen, da könnte ich dir einen oder zwei zum Testen für dein eigenes Konto bei VSync teilen, wenn das reicht?

**Comment by TA2k** [comment]
entweder das oder temporär username Passwort schicken
tombox2020@gmail.com

**Comment by TA2k** [comment]
Adapter funktionier mit Luftbefeuchtern bräuchte noch ein Account mit Wall switch oder Lampen

**Comment by GrayTheZebra** [comment]
Ich habe einen Levoit LV600HH Luftbefeuchter und bis auf die "warmer Nebel-Funktion" funktioniert alle.

Unter dem Datenpunkt "remote" taucht der Punkt "setLevel-wind" auf, was allerdings nichts bewirkt und an sich auch keinen Sinn machen würde.

Unter "extension" findet man "warm_enabled" und "warm_level", das ändern dieser Werte bewirkt allerdings nichts.

**Comment by TA2k** [comment]
Ich habe blind mal level-warm hinzugefügt vielleicht funktioniert das ja

**Comment by GrayTheZebra** [comment]
Das funktioniert, danke.

**Comment by mcm1957** [comment]
Adapter: https://github.com/TA2k/ioBroker.vesync

Request to add to latest seems to be pending
https://github.com/ioBroker/ioBroker.repositories/pull/2039

**Comment by mcm1957** [comment]
Adapter is now available the the rpository (lastest).
https://github.com/TA2k/ioBroker.vesync

Please report any issue or feature request at the adapters repository.

@TA2k Thanks for your work.
