### ISSUE TITLE
Porsche connect / PCM integration

### ISSUE THREAD

**Issue by diehappy69** [ioBroker/AdapterRequests#687]
Hi,
I need a iob adapter for my Porsche Taycan (via Porsche Connect ( PCM service). 
Can anyone help me out?

Hi,
ich brauche Eure Hilfe. Es gibt eine Python Library für die Porsche Connect API. Kann jemand einen iob Adapter daraus bauen? Ich würde gerne die üblichen Daten( Ladezustand, Klima etc. ) in iob verwenden. Testen können wir das mit meinem Taycan. 

It seems there is a [python library for Porsche Connect API](https://github.com/CJNE/pyporscheconnectapi)

Thanx

**Comment by diehappy69** [comment]
Keiner der da unterstützen kann?

**Comment by TA2k** [comment]
https://forum.iobroker.net/topic/50883/test-adapter-myporsche-v0-0-x

**Comment by diehappy69** [comment]
Super, dank Dir. Werde ihn testen...Guten Start ins neue Jahr
