### ISSUE TITLE
Adapter für Dacia "Spring" electric" gesucht

### ISSUE THREAD

**Issue by Stephan1512** [ioBroker/AdapterRequests#688]
Leider lässt sich im Fahrzeug der Soll-Ladestand zum beenden der Ladung nicht einstellen.
So wird der Akku immer bius zu 100% aufgeladen. Das ist zwar schön für die Reichweite des Autos, aber nicht so schön für die Lebensdauer des Akkus.
Über die App "My Dacia" lässt sich der Ladestand des Akkus abfragen. Auch ein Start der Klimatisierung, und ein manueller Stop für die Ladung ist hier möglich.
Bei dieser App ist die Sicherheit nicht sehr großgeschrieben. Deshalb ist wohl eine Programmierung eines Adapters für ioBroker zumindest nicht unmöglich.
Schön wäre es, wenn man den Füllstand des Akkus abfragen könnte.
Das Starten der Klimatisierung wäre dann noch das Sahnehäubchen.
Gerne Stelle ich einem Entwickler die Zugangsdaten für die App zur Verfügung.

**Comment by Apollon77** [comment]
Mal so interessehaber: Bis wohin sollte man denn Laden?

**Comment by Stephan1512** [comment]
Die meisten Hersteller empfehlen maximal 80-90%.--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 10.12.21, 22:05 schrieb Ingo Fischer ***@***.***>:

   
  Mal so interessehaber: Bis wohin sollte man denn Laden?

**Comment by TA2k** [comment]
Ist in den renault adapter integriert

**Comment by Apollon77** [comment]
I assume https://github.com/TA2k/ioBroker.renault ?
