### ISSUE TITLE
SMA Semp Adapter

### ISSUE THREAD

**Issue by Trunks1982** [ioBroker/AdapterRequests#689]
Hallo ich möchte mal fragen wer wäre interessiert das es ein SMA Semp Adapter gibt?
Mit diesem wäre es möglich Geräte wie Schaltbare Steckdosen im Sunnyportal zu erzeugen und zusteuern.Auch wäre dann die Möglichkeit da, da die Stromverbräuche der Steckdosen bzw. Geräte zu tracken.
Es gibt zwar einen SAE Smart Appliance Enabler aber diese Software muss separat auf einem pi laufen.Über IOBroker wäre es natürlich ne Leichtigkeit Geräte ins Sunnyportal zubringen.
Ne Ladesteuerung für Wallboxen wäre natürlich auch mitdrin.

Freue mich über euer Feetback.

**Comment by kevinaus1** [comment]
Hallo @Trunks1982,

genau an so etwas hätte ich starkes Interesse. 
Gerade für "nur ein paar Steckdosen" im SMA SunnyPortal sichbar zu machen suche ich schon länger eine Lösung.

ich hoffe es wird klappen.

**Comment by Trunks1982** [comment]
Ja das wäre Mega.Tracke alle meine Sachen so im Sunnyportal.

**Comment by Newan** [comment]
Gibt es da eine api etc und wo ist diese zu finden?

**Comment by Trunks1982** [comment]
https://github.com/orlopau/semp Hier hat schonmal wer was angefangen zb.

**Comment by Trunks1982** [comment]
Und hier kann man sich die Daten für die api bestellen. https://www.sma.de/produkte/sma-developer.html

**Comment by Trunks1982** [comment]
> Gibt es da eine api etc und wo ist diese zu finden?

Hättest du interesse dran?

**Comment by Newan** [comment]
Mit einem Account könnte man das ansehen

**Comment by Trunks1982** [comment]
> Mit einem Account könnte man das ansehen

Wie meinste mit Account?
Sunnyportal?

**Comment by Petersen83** [comment]
Echt schade, dass es das noch nicht gibt. Das würde echt vieles einfacher machen.

**Comment by Trunks1982** [comment]
https://github.com/orlopau/semp
das müsste in einen Adapter😏

**Comment by Newan** [comment]
Ja das sieht machbar aus, ohne Hardware nur schwer ich bekomme Fronuis Wechselrichter.
Wenn einer die Ports 9089, 9090 nach außen hin aufmacht könnte man aber anfangen

**Comment by rg-engineering** [comment]
Wenn ich das richtig sehe, wird der Sunny Home Manager dafür benötigt. Meiner kommt aber erst im Herbst....

**Comment by Trunks1982** [comment]
Ja genau.

**Comment by Trunks1982** [comment]
Stell mich aber gerne als Tester zur Verfügung🤣

**Comment by Newan** [comment]
DU müsstest oder jemand anderes dein Gerät zur Verfügung stellen

**Comment by Trunks1982** [comment]
> DU müsstest oder jemand anderes dein Gerät zur Verfügung stellen

schwierig wie soll das gehn?
Ausbauen fällt da raus.

**Comment by Newan** [comment]
Portweiterleitung / VPN / .. gibt es ja mehr Methoden

**Comment by Trunks1982** [comment]
Könnte man ja drüber reden.Ich glaub da wäre ne portweiterleitung die bessere Wahl.Mit VPN würde ich ja mein gesamtes Netzfreigeben.Das möchte ich eigentlich nicht.

**Comment by Trunks1982** [comment]
du hast Post

**Comment by Trunks1982** [comment]
Eine Windows VM könnte ich noch anbieten was direkten Netzwerk zugriff auf den SHM hat.

**Comment by rg-engineering** [comment]
Falls es hier schon etwas zu testen gibt, kann ich ab sofort unterstützen: Mein Sunny Home Manager  ist installiert...

**Comment by Trunks1982** [comment]
Leider gibts nichts zu testen.

**Comment by rg-engineering** [comment]
arbeitet da jemand dran?
Wenn nicht, kann ich übernehmen. Ich habe schon ein Dummy-Gerät aus einem Adapter im SunnyPortal per SEMP angelegt....

**Comment by Trunks1982** [comment]
Soviel wie ich weiss noch nicht.Wäre cool wenn du das übernehmen würdest.Bin gerne zum testen bereit.

**Comment by rg-engineering** [comment]
okay, ich übernehme das....

**Comment by rg-engineering** [comment]
unter https://github.com/rg-engineering/ioBroker.semp gibt es eine erste alpha-Version.
Aktuell werden Geräte, welche im admin konfiguriert werden, im SunnyPortal angelegt und die Leistung wird regelmässig dorthin übertragen
![grafik](https://user-images.githubusercontent.com/8238668/187728447-32d9a6a9-bd47-4d8c-8330-4d7e5463a6dd.png)

![grafik](https://user-images.githubusercontent.com/8238668/187728663-d7ae31be-5673-4240-a931-7a43346a255b.png)

weitere Funktionen kommen noch...

_**Achtung**_ Die ID eines Gerätes muss eindeutig sein, darf also im SunnyPortal nicht doppelt auftreten. Ich nutze also eine DeviceBase-ID und dann eine fortlaufende Nummer. Die ID wird automatisch pro Gerät erzeugt. Aktuell werden Änderungen an dem Gerät (z.Bsp. type) nicht in's SunnyPortal übernommen. Fürs testen angelegte Geräte können also nicht nochmal geändert werden, selbst beim Löschen und neu anlegen werden die alten Daten wieder hergestellt...

Die automatisch erzeugte UUID kann geändert werden...

Bug reports bitte als Ticket im o.g. repository anlegen.

**Comment by Trunks1982** [comment]
Cool das ging aber flott🙈

**Comment by Trunks1982** [comment]
> unter https://github.com/rg-engineering/ioBroker.semp gibt es eine erste alpha-Version. Aktuell werden Geräte, welche im admin konfiguriert werden, im SunnyPortal angelegt und die Leistung wird regelmässig dorthin übertragen ![grafik](https://user-images.githubusercontent.com/8238668/187728447-32d9a6a9-bd47-4d8c-8330-4d7e5463a6dd.png)
> 
> ![grafik](https://user-images.githubusercontent.com/8238668/187728663-d7ae31be-5673-4240-a931-7a43346a255b.png)
> 
> weitere Funktionen kommen noch...
> 
> _**Achtung**_ Die ID eines Gerätes muss eindeutig sein, darf also im SunnyPortal nicht doppelt auftreten. Ich nutze also eine DeviceBase-ID und dann eine fortlaufende Nummer. Die ID wird automatisch pro Gerät erzeugt. Aktuell werden Änderungen an dem Gerät (z.Bsp. type) nicht in's SunnyPortal übernommen. Fürs testen angelegte Geräte können also nicht nochmal geändert werden, selbst beim Löschen und neu anlegen werden die alten Daten wieder hergestellt...
> 
> Die automatisch erzeugte UUID kann geändert werden...
> 
> Bug reports bitte als Ticket im o.g. repository anlegen.

die Ip die vergeben ist muss vom IoBroker sein?

**Comment by Trunks1982** [comment]
Hab jetzt mal nen shellyplug eingegeben aber es kommen keine Werte an.

**Comment by rg-engineering** [comment]
> die Ip die vergeben ist muss vom IoBroker sein?

ja, das ist die IP, wo der HomeManager die Daten anfordert...

**Comment by rg-engineering** [comment]
> Hab jetzt mal nen shellyplug eingegeben aber es kommen keine Werte an.

wird das Gerät im SunnyPortal angezeigt und hast du es dort konfiguriert?

**Comment by Trunks1982** [comment]
Ja hab ich.hab mal debug angemacht und da sieht man setlastpower und den wert.aber im sunnyportal zeigt er den wert nicht an

**Comment by rg-engineering** [comment]
lass das mal eine weile laufen...

**Comment by Trunks1982** [comment]
Ok.

**Comment by Trunks1982** [comment]
Hi bis jetzt kommt noch nichts an.Schalter an aus muss man ja nicht im adapter drin haben oder?

**Comment by rg-engineering** [comment]
vielleicht doch? wenn du das debug log anhast, müsstest du ja auch den Status des Gerätes im xml sehen. ich vermute, da steht jetzt off?

**Comment by Trunks1982** [comment]
Mhm sehe da gar nichts mit off🙈

**Comment by Trunks1982** [comment]
Ah habs gefunden ist off

**Comment by Trunks1982** [comment]
Wie bekomme ich das auf an?
Habs mal mit dem shelly schalter datenpunkt probiert aber funktioniert leider nicht.

**Comment by Tagiwara** [comment]
Interessanter Adapter. Ich habe gerade mal eine Tasmota Dose eingerichtet. IM Sunny Portal wird sie auch gefunden. Ich habe sie eingerichtet, aber schalten kann ich da noch nix. Liegt das am alpha status und kommt das noch? Weil aktuell sehe ich nur das Gerät. VErbrauchswerte werden auch keine übertragen

**Comment by rg-engineering** [comment]
> Wie bekomme ich das auf an?
Ich baue das mal um, immer wenn power > 0 stelle ich auf On, wenn power =0 dann off
> aber schalten kann ich da noch nix
ja, das ist auch noch nicht fertig. Im Moment will ich erst mal die Leistung im Portal sehen. In meinem Testaufbau (mit einem power und on/off Datenpunkt im script zum Testen) scheint es zu funktioneren, bei euch hier noch nicht...

**Comment by Trunks1982** [comment]
Beim Smart Appliance Enabler kann man da drei punkte auswählen damit der Zähler daten schickt.
Einmal immer an, einmal Zählerbasierter Zudtandsmelder und Http Schalter.Vielleicht hielft dir das.

**Comment by rg-engineering** [comment]
> hier hab ich für dich mal ein paar Bildchen für dich

danke! ich habe den hier auch installiert, muss aber noch verstehen, wie das ganze funktioniert...

**Comment by Trunks1982** [comment]
> > hier hab ich für dich mal ein paar Bildchen für dich
> 
> danke! ich habe den hier auch installiert, muss aber noch verstehen, wie das ganze funktioniert... ich baue also erst mal die Variante "zählerbasierter Zustandsmelder" ein. Wenn das geht, kann ich ja die anderen Optionen nachtragen...

👍

**Comment by TeraX** [comment]
Hallo alle zusammen,

ein kurzes Feedback, nach Anfangsschwierigkeiten, wegen einer älteren Node.js Version, habe ich nun erfolgreich meine Waschmaschine, Trockner und Geschrirrspüler eingebunden.

Diese haben eine separate Steckdose und im Verteilerkasten hängt ein Homematicaktor mit Messfunktion dazwischen, welchen ich in ioBroker auslese.

Leider habe ich noch keine PV-Anlage und nutze das daher erstmal nur zum Verbrauchstracking, sobald ich jedoch eine habe ist mein nächster Versuch, über eine Variable in ioBroker Geräte aus der BSH Gruppe, wie z.B. der Geschirrspüler, fernsteuern zu können.

Leider hat die BSH Gruppe ja aus allen neuen Modellen die EEBUS Funktionalität gestrichten und setzt nur noch auf HomeConnect.
Da es hierzu ja auch ein ioBroker Adapter gibt, der gut funktoniert, ist mein Ziel mit Hilfe von SEMP bei PV Überproduktion zu mindestens HomeConnect Geräte anzusteuern.

Vielen Dank schonmal für diesen Adapter.
Für weitere Tests stehe ich gerne zur Verfügung

**Comment by rg-engineering** [comment]
@Apollon77 Bitte weise dieses issue mir zu, Adapter ist in Arbeit.
Betrifft auch #662

**Comment by Apollon77** [comment]
@rg-engineering Done ( I think you could also do that )

**Comment by rg-engineering** [comment]
Adapter is now in latest, so I close the request... 

see https://github.com/rg-engineering/ioBroker.semp
