### ISSUE TITLE
Tinkerforge WARP 2 Wallbox 

### ISSUE THREAD

**Issue by ChrissT23** [ioBroker/AdapterRequests#690]
**What kind of device or service you would like to see an adapter for?**
Ich habe 2 Tinkerforge WARP 2 Wallboxen und würde diese gern über einen Adapter integrieren können. Leider fehlen mir die Fähigkeiten so etwas selbst zu schreiben, vielleicht besteht ja bei mehreren Interesse dazu. Sonst müsste ich mich mit der Integration über MQTT beschäftigen. 

**Is an official API including documentation is available?**
Von Tinkerforge wird eine API hier bereitgestellt https://www.warp-charger.com/api.html?v=2

Vielen Dank schon einmal im Voraus an denjenigen der sich der Sache annehmen möchte :)

**Comment by Newan** [comment]
Die wallbox bietet mqtt an. Mal mit dem mqtt Adapter probiert?

**Comment by ChrissT23** [comment]
Ja per MQTT funktioniert es, ein Adapter würde ich halt einfacher finden, da ich dann direkt die DP hätte und nichts Parsen muss, habe damit noch nicht soviel Erfahrungen und bin mich da noch am einarbeiten.

**Comment by ldittmar81** [comment]
Vielleicht ist es hier zu Überlegen, für den MQTT Adapter sowas wie Templates erstellen zu können. Einer macht sich dann die Arbeit alles schön anzulegen, exportiert dann das Template und stellt es zur Verfügung: Wäre sowas ein denkbarer Weg?

**Comment by ChrissT23** [comment]
Klar, denkbar wäre alles was hilft es etwas einfacher zu machen !

**Comment by pottio** [comment]
@ChrissT23
Ich habe einen entsprechenden Adapter entwickelt und bitte um Test mit Feedback: https://forum.iobroker.net/topic/53921/test-adapter-warp-v0-0-x-github
