### ISSUE TITLE
KNX send only adapter

### ISSUE THREAD

**Issue by pos-ei-don** [ioBroker/AdapterRequests#694]
Der KNX Adapter liest alle Werte und möchte diese abbilden.
Ich möchte jedoch lediglich einzelne Temperaturwerte aus anderen Systemen nach KNX weitergeben.
Wenn ich nichts übersehe, kann ich das mit dem aktuellen Adapter nicht machen.

**Comment by Apollon77** [comment]
Ja dann mach doch bitte feature requests bei den bestehenden adaptern ... noch nen knx Adapter nur dafür ist in meinen Augen blödsinn
