### ISSUE TITLE
Klarstein Integration

### ISSUE THREAD

**Issue by Sunnylaila** [ioBroker/AdapterRequests#703]
Hallo ich habe mir von der Firma Klarstein den
Cosmic Beam Heizstrahler gekauft, dieser ist über die Klarstein App sehr gut per WLAN bedienbar

Es wäre super wenn ich diesen in iobroker Integrieren könnte

**Comment by Apollon77** [comment]
Dann bitte alle Fragen aus dem Template nicht löschen sondern beantworten.

Gibt es andere Integrationen? Gibt es eine API? Gibt es Libraries die das unterstützen? Links? Details? Danke

**Comment by Sunnylaila** [comment]
Eine API gibt es soweit ich weiß

https://api-prod.klarstein-app.com/i18/faqs

Andere Integrationen kenne ich leider keine

**Comment by juppjuppsen** [comment]
Melde auch mal Interesse an einer Integration der Klarstein App an :-)

**Comment by Apollon77** [comment]
@juppjuppsen @Sunnylaila Interesse? Naja dann "Daumen hoch" im ersten post, sonst sieht es keiner

**Comment by juppjuppsen** [comment]
> @juppjuppsen @Sunnylaila Interesse? Naja dann "Daumen hoch" im ersten post, sonst sieht es keiner

Done 🙏

**Comment by sven-sk1337** [comment]
Bin auch schon die ganze Zeit auf der Suche nach einer ioBroker Lösung für den Klarstein Heizstrahler 😍

(Daumen hoch 👍 #done)

Vielleicht hat ja jemand eine Lösung.

Stelle mich auch gern als Beta Tester zur Verfügung ☺️👌

**Comment by fluke101** [comment]
Daumen hoch #done

**Comment by Apollon77** [comment]
Könnt Ihr bitte aufhören eure "daumen hoch geklickt" mit nem Post zu kommentieren? Danke

**Comment by THuebner29** [comment]
Hat jemand, der einen Klarstein Heitlüfter hat, diese o.g. API mit Browser schon mal ausprobiert? z.B. mit diesem Plugin für Firefox: https://addons.mozilla.org/de/firefox/addon/rest-client-apishub/

Ich habe vor, mir eventuell eine Infrarotheitzung von Klarstein zu holen. Und wenn die API funktioniert könnte man einen Adapter schreiben.

**Comment by TA2k** [comment]
Wenn mir jemand Zugangsdaten gibt kann ich mir das anschauen
tombox2020@gmail.com

**Comment by BernhardLinz** [comment]
Ich habe seit heute einen Klarstein DryFy und mich deshalb für die App registriert.
Leider hatte es natürlich nicht auf Anhieb geklappt diese Daten für eine Anmeldung an der API und dem Erhalt des notwendigen Tokens.

URL: [https://api-prod.klarstein-app.com/](https://api-prod.klarstein-app.com/)
Security => /security/jwt_login

Dann den Button "Try it out", bei "Request Body" die Anmeldedaten eintragen und auf "Execute" drücken.
Wenn es klappt sollte weiter unten dann ein Token zurück gemeldet werden (in einem JSON String), bei mir kommt im Moment noch die **401 Wrong Username or Password**

Kann mal einer verifizieren ob das bei ihm Klappt? 

Man kann ja ein paar Sachen auch ohne Anmeldung aufrufen, das scheint das gleiche zu sein wie in der App zu sehen, z.B. die FAQ

**Comment by TA2k** [comment]
Klarstein scheinen alles tuya Geräte zu sein hat jemand schon den Tuya Adapter probiert?

**Comment by TA2k** [comment]
Tuya 3.8.0 auf GitHub kann jetzt einfach neue Geräte syncen. Einfach die Klarstein Geräte in die Tuya app hinzufügen und via iobroker Tuya adapter abfragen.
