### ISSUE TITLE
Tado Adapter

### ISSUE THREAD

**Issue by steckenpferd** [ioBroker/AdapterRequests#71]
Hi,

there are many unoffical API documentenations maybe some good developer can create with that an adapter:

I can send my hardware for test purpose.

http://libtado.readthedocs.io/
http://blog.scphillips.com/posts/2017/01/the-tado-api-v2/
http://wirres.net/article/articleview/10326/1/6/

![grafik](https://user-images.githubusercontent.com/39061622/39826424-ebd3a436-53b4-11e8-802a-35190ec60291.png)

**Comment by iOt-ananas** [comment]
Kann die Hardware bzw. es reicht ein gekoppelter Account aus, zur Verfügung stellen.

**Comment by Apollon77** [comment]
Homebridge modules exist: ckuburlis/homebridge-tado, homebridge-tado-thermostat-plugin, homebridge-tado-ac as example.

Please check if the new ioBroker.ham Adapter can help here: see https://forum.iobroker.net/viewtopic.php?f=36&t=14972

**Comment by DutchmanNL** [comment]
Not really!

Home bridge can act in iObroker like an adapter, so using homebridge with the related plugin in iObroker is basically the same as an adapter.

Only functionality is limited to what homebridge cab so and that's much less iObroker could do

**Comment by CrazyApple** [comment]
Yes of course ... But I can wish me a adapter too :)

**Comment by DutchmanNL** [comment]
I checked the API and existing NPM modules it looks quite simple to implement.

It all runs by the tado Web API, will need an demo account or hardware to continue.
Needed. Logic looks equal to my as my just released discovery adapter so doesn't look very comes to build

**Comment by CrazyApple** [comment]
So I have an account. But unfortunately I can not provide my hardware ... because she has to work.

**Comment by DutchmanNL** [comment]
Would it be an option to have a teamspeak/Teamviewer Session together ?

Lets See what data The npm packages can Provide If werden manage to make an Connection we get the data needed to build the adapter.

I see on the forum that more people are interested in this one

**Comment by CrazyApple** [comment]
Yes of course, many peoples "need" this :) 

We can write in the forum about a team viewer date

**Comment by DutchmanNL** [comment]
What would be interesting to know is if an adapter would provide more capabilities than the current HAM binding, of not I would suggest to keep it by HAM binding.


Otherwise it makes sense to spend time in an adapter but from my understanding only if there is a benefit :-)

**Comment by DutchmanNL** [comment]
We are investigating the possibilities for Q1 2019

**Comment by Coffee-lover** [comment]
Looking forward to your investigations. Really appreciate to get the adapter. :)

**Comment by CrazyApple** [comment]
Yes ... But I think we have to wait :(

**Comment by DutchmanNL** [comment]
I expect being able to start within the next 2 weeks

**Comment by CrazyApple** [comment]
that's a great news ... das wäre ja wirklich wunderbar :)

**Comment by Coffee-lover** [comment]
I just wanted to inform you about my recent contact request to TaDo concerning their announced, official API.
https://support.tado.com/hc/de/articles/205505299-Welche-neuen-Funktionen-sind-geplant-Was-ist-auf-der-Roadmap-f%C3%BCr-die-Entwicklung-
I will keep you informed, if there is any feedback.

**Comment by KKief** [comment]
Much appreciated.

I did some efforts over the turn of the year with Homebridge Adapter and Tado Plugin. Anyhow, I am facing some issues resulting in overheating and some other inconsistencies. Official API and an dedicated adapter would be very needed. Otherwise in mid-term, I would even consider changing to Homematic.

Regs!

> I just wanted to inform you about my recent contact request to TaDo concerning their announced, official API.
> https://support.tado.com/hc/de/articles/205505299-Welche-neuen-Funktionen-sind-geplant-Was-ist-auf-der-Roadmap-f%C3%BCr-die-Entwicklung-
> I will keep you informed, if there is any feedback.

**Comment by KKief** [comment]
I moreover believe that Tado intentionally prevents such an official API, since they are following that approach to charge 2.99€/m or 29.90€/yr for this auto-assist service. That would provide auto switch-off if window open or if away via geo-fencing. 

Providing the API would mean then, people would bypass this and automate everything via iobroker/fhem etc.

That would be another reason to sell the Tado devices and switch to Homematic. I am kinda pissed off.

**Comment by danzbox** [comment]
@DutchmanNL Can I vote for this adapter too? Is TS/Teamviever enough or would hardware speed up things?

**Comment by danzbox** [comment]
> 
> 
> I moreover believe that Tado intentionally prevents such an official API, since they are following that approach to charge 2.99€/m or 29.90€/yr for this auto-assist service. That would provide auto switch-off if window open or if away via geo-fencing.
> 
> Providing the API would mean then, people would bypass this and automate everything via iobroker/fhem etc.
> 
> That would be another reason to sell the Tado devices and switch to Homematic. I am kinda pissed off.

True, on the other hand the window open function and the auto away feature is available (and per announcement will stay available) for all v3 users.

**Comment by CrazyApple** [comment]
Any news?

**Comment by Coffee-lover** [comment]
In the meantime I installted the HAM.adapter and integrated tado that way. Works like a charm.

**Comment by CrazyApple** [comment]
I know it works and works that way. But that is not the solution. There should be an adapter for such a big system like Tado. Everything else is just a crutch or interim solution. All others have a Tado adapter, only ioBroker not :-(

**Comment by DutchmanNL** [comment]
didn't find time yet and trying to get an device from local supplier for integration purpose

**Comment by eXTreMe-1337** [comment]
> 
> 
> I just wanted to inform you about my recent contact request to TaDo concerning their announced, official API.
> https://support.tado.com/hc/de/articles/205505299-Welche-neuen-Funktionen-sind-geplant-Was-ist-auf-der-Roadmap-f%C3%BCr-die-Entwicklung-
> I will keep you informed, if there is any feedback.

The public API is on tados developer roadmap for more than 4 years .... they announced it at CeBit 2015 .....

**Comment by Coffee-lover** [comment]
I mentioned that in my request. TaDo's answer was .... NOTHING.

**Comment by SoerenKaiser99** [comment]
Hi Dutch,

we talked also in iobroker forum. For Summertime you could have one of my thermostats and a bridge or we try it by teamviewer / VPN

**Comment by DutchmanNL** [comment]
could be a nice try, let me investigate the backend part end api availabilities and than look further

**Comment by Uwe1984** [comment]
Is anyone still working on the Tado Adapter? It would be great if there was a stand-alone adapter for Tado.

**Comment by t6a** [comment]
I know some friends (and me ofc) who would absolutely appreciate a comfortable Tado adapter for ioBroker. It would be awesome if one could just fill username and password in the adapter settings and then the adapter pulls automatically the Home ID, zone IDs, room names and all thermostats.

Link to pull home ID:
https://my.tado.com/api/v2/me?username=XXX&password=YYY

Link to pull zone ID and other:
https://my.tado.com/api/v2/homes/ZZZ/zones?password=YYY&username=XXX

**Comment by DutchmanNL** [comment]
die documentation zu dieser API is wirklich eine Katastrophe da gib es überhaupt garnix.

Da ich die Geräte nicht habe (auch nicht kaufen werde) wirds immer noch schwer und ja hab die Sommer periode bissl verpasst nur waren auch noch andere prios.

Es wierde helfen wen ich mal mit jemand seinem account einloggen und schaue dürfte und ein par queres ausprobieren die ich reverse engineering gefunden habe.

Ohne gerate/zugang und docu wirds wirklich schwer leute aber bin bereit zu helfen

**Comment by t6a** [comment]
Kann man die API documention nicht vom Macher der des Homebridge Plug-ins erfragen? haha😅 
Ich bekomme morgen ein zweites Set fuer eine andere Wohnung - muss das aber nicht sofort dort installieren und kanns erstmal an einem Heizkörper bei mir mit separatem Account laufen lassen. Dann kannst du damit erstmal bisschen spielen.

**Comment by SoerenKaiser99** [comment]
Vielleicht gibt es hier auch hilfe:

http://www.peterdebruin.net/tado.html 
Die Seite läuft super

**Comment by SoerenKaiser99** [comment]
Ansonsten ist die API hier dokumentiert:
http://blog.scphillips.com/posts/2017/01/the-tado-api-v2/

**Comment by SoerenKaiser99** [comment]
Falls das nicht hilft Dutch kannst du gern mein Account oder via VPN/Teamviewer Zugang zu meinen System haben... hatte ich ja schon mal angeboten

**Comment by SoerenKaiser99** [comment]
via node-red gehts übrigens auch super

**Comment by DutchmanNL** [comment]
na sieste kaum spuckt man bekommt man auch was mit. data cool jetzt kann weiter gehen.

brauche aber immer noch nen account bzw gerate um entwickeln zu koennen.

**Comment by SoerenKaiser99** [comment]
du hättest nur fragen müssen ;p hattest damals gesagt du musst erst noch andere Sachen machen und wolltest dich im Januar melden...

schick mir ne pm mit deiner mail dann füge ich dich zu meinem Zuhause hinzu

**Comment by DutchmanNL** [comment]
hab dir ne. mail geschikt :)

**Comment by t6a** [comment]
sehr cool!! Sobald es eine Github page für den Adapter gibt, wäre es super die hier zu verlinken

**Comment by Uwe1984** [comment]
Sehr geil, wäre echt super wenn du das machen würdest, Dutchman. Ich würde gerne unterstützen aber mein System kommt erst im November..Dann hab ich 9 Ventile

**Comment by DutchmanNL** [comment]
> sehr cool!! Sobald es eine Github page für den Adapter gibt, wäre es super die hier zu verlinken

sobald ich Zugangsdaten und die erste JSON hab kommt mal schnell ne ALPHA zum schnuppern und dan können wir den adapter zusammen fertig machen.
Glaube da hatte sich ach jemand gemeldet mit script Kenntnisse das fließt hier dan zusammen.

also wird schon :)

**Comment by DutchmanNL** [comment]
ich habe die NPM library gefunden, es kan losgehen : 

https://www.npmjs.com/package/node-tado-client

**Comment by SoerenKaiser99** [comment]
Hab dich eingeladen, die Npm läuft ebenfalls bei mir via Node-red. Hatte ich im post vorher erwähnt.. wenn das hilft kannst dort auch reinschauen.. aktuell hole ich die Werte wie Temp. Hum, online, Heating Power und Anwesenheit von dort und und schreibe sie in States für den iobroker

**Comment by DutchmanNL** [comment]
> Hab dich eingeladen, die Npm läuft ebenfalls bei mir via Node-red. Hatte ich im post vorher erwähnt.. wenn das hilft kannst dort auch reinschauen.. aktuell hole ich die Werte wie Temp. Hum, online, Heating Power und Anwesenheit von dort und und schreibe sie in States für den iobroker

danke ! Ich habe die Einladung angenommen und fange mal an :)

**Comment by DutchmanNL** [comment]
> ktuell hole ich die Werte wie Temp. Hum, online,

wen du Beispiele hasty immer  gerne

**Comment by DutchmanNL** [comment]
<img width="576" alt="Schermafbeelding 2019-10-09 om 00 39 35" src="https://user-images.githubusercontent.com/7318445/66438547-46935780-ea2d-11e9-83a2-5d31d23b05b8.png">

ich scheitere im moment hier

**Comment by SoerenKaiser99** [comment]
Moin Dutch,

hast du die HomeID & ZonenID verwendet?
Es muss mehrstufig ablaufen. 
Esrt get HomeID
dann getZoneID
und aus der Zone dann Unit
Devices (Handys etc.) bekommst du mit der HomeID

Ich schick dir meine Daten per Mail

**Comment by SoerenKaiser99** [comment]
Hier die Daten:

 

HomeID

214860

 

Bad Zone 4

 

Wohnzimmer Zone 1

 

Büro Zone 3

 

Kinderzimmer Zone 5

 

Bridge & Extension-Kit bekommst du mit der HomeID

 

 

 

 

 

 

Von: Dutchman <notifications@github.com> 
Gesendet: Dienstag, 8. Oktober 2019 20:10
An: ioBroker/AdapterRequests <AdapterRequests@noreply.github.com>
Cc: SoerenKaiser99 <vertrieb.ditosama@gmail.com>; Comment <comment@noreply.github.com>
Betreff: Re: [ioBroker/AdapterRequests] Tado Adapter (#71)

 

sehr cool!! Sobald es eine Github page für den Adapter gibt, wäre es super die hier zu verlinken

sobald ich Zugangsdaten und die erste JSON hab kommt mal schnell ne ALPHA zum schnuppern und dan können wir den adapter zusammen fertig machen.
Glaube da hatte sich ach jemand gemeldet mit script Kenntnisse das fließt hier dan zusammen.

also wird schon :)

**Comment by SoerenKaiser99** [comment]
Vielleicht hilft dir das auch? : 


// 1. Pro Thermostat muss ein Script erstellt und individuell konfiguriert werden!
// 2. Eindeutigen Raumname im Konfig-Bereich des Scripts für das Thermostat angeben. Bei mehreren Thermostaten in einem Raum bitte unterschiedliche Raumnamen verwenden.
// 3. Über folgende URL (Nutzername und Passwort in der URL angeben) per WEbbrowser die HomeID ermitteln und in dem Konfigurations-Teil des Scripts eintragen:
//    https://my.tado.com/api/v2/me?username=vertrieb.ditosama@gmail.com&password=2Gether4ever
// 4. Über folgende URL (HOME ID, Nutzername und Passwort in der URL angeben) per Webbrowser die ZoneID ermitteln und in dem Konfigurations-Teil des Scripts eintragen:
//    https://my.tado.com/api/v2/homes/214860/zones/214860/state?username=vertrieb.ditosama@gmail.com&password=2Gether4ever
//     - Die "2" im Link steht für ZoneID 2, in meinem Fall war das das Thermostat im Wohnzimmer
//     - am besten unterschiedliche Temperaturen in den Räumen per App einstellen und dann verschiedene Zahlen im Link durchprobieren


schedule("*/10 * * * *", function () { // Zeiteinstellung: Script aktualisiert alle 10 Min die Werte. Bei geringeren Abfrageintervallen kann es zu Verbindungsabbrüchen kommen und alle Geräte müssen neugestartet werden!
    
    //[b]Konfiguration:[/b]
    var Raumname = 'Wohnzimmer gross'; // Der hier angegebene Raumname dient zur Benennung des erzeugten Channel Objekts in ioBroker
    var ZoneID = "1"; // Zonennummer des Raums (muss über API URL ermittelt werden, siehe Anleitung)
    var HomeID = "214860"; // HomeID (muss über API URL ermittelt werden, siehe Anleitung)
    var Username = "vertrieb.ditosama@gmail.com"; // tado Username (E-Mail Adresse)
    var Password = "2Gether4ever"; // tado Passwort (Sonderzeichen müssen entsprechend umgewandelt werden, z.B. # = %23)
    
    // SCRIPTBEGINN - AB HIER NICHTS VERÄNDERN !

	 var url = "https://my.tado.com/api/v2/homes/"+HomeID+"/zones/"+ZoneID+"/state?username="+Username+"&password="+Password; // API URL

  	//läd die Json herunter
  	var request = require("request");
    request(url, function (error, response, body) {
  	//parst die Json
    var json = JSON.parse(body);
    
    //Datenpunkterstellung:
    createState("tado." + Raumname + ".temperature", 0, false, {type: "number", name: "temperature", desc: "Eingestellte Temperatur", role: "value.temperature", unit: "°C", read: true, write: true});
    createState("tado." + Raumname + ".power", "OFF", false, {type: "string", name: "power", desc: "Aufheizen", read: true, write: true});
    createState("tado." + Raumname + ".inside_temperature", 0, false, {type: "number", name: "inside_temperature", desc: "Gemessene (Raum-)Temperatur", role: "value.temperature", unit: "°C", read: true, write: true});
    createState("tado." + Raumname + ".humidity", 0, false, {type: "number", name: "humidity", desc: "Luftfeuchtigkeit", role: "value.humidity", unit: "%", min: 0, max: 100, read: true, write: true});
    createState("tado." + Raumname + ".heatingpower", 0, false, {type: "number", name: "heatingpower", desc: "Heizkraft", unit: "%", min: 0, max: 100, read: true, write: true});

    //Datenabfrage:
    //Temperatur:
  	setState("javascript.0.tado."+Raumname+".temperature", json.setting.temperature.celsius);
  	log('tado Temperatur '+Raumname+': ' + json.setting.temperature.celsius);
  	//Power:
  	setState("javascript.0.tado."+Raumname+".power", json.setting.power);
  	log('tado Power-Setting '+Raumname+': ' + json.setting.power);
  	//Humidity:
  	setState("javascript.0.tado."+Raumname+".humidity", json.sensorDataPoints.humidity.percentage);
  	log('tado Humidity '+Raumname+': ' + json.sensorDataPoints.humidity.percentage);
  	//Inside Temperature:
  	setState("javascript.0.tado."+Raumname+".inside_temperature", json.sensorDataPoints.insideTemperature.celsius);
  	log('tado Inside Temperature '+Raumname+': ' + json.sensorDataPoints.insideTemperature.celsius);
  	//Heating Power:
  	setState("javascript.0.tado."+Raumname+".heatingpower", json.activityDataPoints.heatingPower.percentage);
  	log('tado Heating Power '+Raumname+': ' + json.activityDataPoints.heatingPower.percentage);
  	});
});

**Comment by eXTreMe-1337** [comment]
@soerenkaiser99: ich hoffe du hast dein passwort auch bei allen anderen diensten geändert wo du diese email adresse als nutzername mit dem gleichen pw verwendest :-)
denn alle leute die hier diese github page abonniert haben, haben eine mail mit deinem ursprungsbeitrag bekommen indem auch deine zugangsdaten drin standen :-)

oh, und schön das tado script was ich vor ewigkeiten mal geschrieben habe hier wieder zu finden 😅
mittlerweile nutze ich den homebridge adapter um meine tado thermostate zu steuern, ein eigener adapter wär natürlich viel besser, da man sich das komplexe erstellen der config datei dann sparen kann.
aber ich sehe ihr seid da schon fleißig dran! weiter so und vielen dank vorab!

**Comment by SoerenKaiser99** [comment]
@eXTreMe-1337 
Moin Max,

lieben Dank für den Hinweis. War glücklicherweise ein sehr altes :) Habs aber schon gesehen und raus genommen. 
Tut mir leid das ich dich nicht als Quelle angegeben hab. Ich hab das Skript mal in nem Forum gefunden und kopiert aber schon ewig nicht mehr benutzt und wusst nicht mehr wo es herkam.

**Comment by DutchmanNL** [comment]
ich bin dran und habe schon so einiges raus hohlen koennen, heute Abend kommt was auf GitHub fuel euch

**Comment by DutchmanNL** [comment]
ok mal n kurzes update : die ersten daten kommen rein, API ist extrem verschachtelt also muss dan noch n par Sachen machen damit die states auch wirklich gut in ioBroker ankommen.

Das erste Erfolgserlebnis möchte ich aber nicht vorenthalten 💃 

<img width="1457" alt="Schermafbeelding 2019-10-09 om 16 23 54" src="https://user-images.githubusercontent.com/7318445/66490573-a7fd0a00-eab1-11e9-83c1-bcef7da540a2.png">

**Comment by Coffee-lover** [comment]
Hi Dutchman,
ich finde, das sieht schon sehr gut aus. Die Verschachtelung... ich persönlich finde es nicht einmal so schlimm, dass ich zunächst das Zimmer und dann das Thermostat auswähle. Da gibt es schlimmere Adapter. Und außerdem arbeitet man ja nicht ständig in der Struktur...
Just my 2 ct.
Cooles Teil - ich teste mal, wenn ich Zeit finde.

**Comment by t6a** [comment]
Telegram: @Asbeck

**Comment by SoerenKaiser99** [comment]
Telegram: @soerenkaiser99 
Team: SoerenKaiser99

**Comment by senger1985** [comment]
TS: Rolli

**Comment by DutchmanNL** [comment]
Alpha version released !  Who would like to help alpha testing please join our Telegram group :  

https://t.me/joinchat/GKq5HBCYWaB_H5ggZHkeIQ

https://github.com/iobroker-community-adapters/ioBroker.tado/blob/master/README.md

**Comment by t6a** [comment]
Großer Dank im Namen aller Tado+ioBroker Besitzer !

**Comment by CrazyCreator13** [comment]
Absolut einsame Spitze .... Hab jetzt nur schnell installiert um zu schauen, aber sieht schonmal verdammt gut aus. Jetzt muss ich nur noch rausfinden wie ich wo was Regel und dann das ganze in HomeKit holen ;)

**Comment by DutchmanNL** [comment]
> Jetzt muss ich nur noch rausfinden wie ich wo was Regel und dann das ganze in HomeKit holen ;)

regeln geht noch nicht, aber wird diese Wochenende rein kommen :)

**Comment by DutchmanNL** [comment]
Soo Leute, die Beta is released ich mache das issue dan auch mal zu, alles weitere bitte per forum oder GitHub issue !

Forum discussion : https://forum.iobroker.net/topic/25723/aufruf-neuer-adaper-tado
Github : https://github.com/iobroker-community-adapters/ioBroker.tado/blob/master/README.md
