### ISSUE TITLE
Update adapter for solar-wetter.com

### ISSUE THREAD

**Issue by wuggili** [ioBroker/AdapterRequests#713]
**What kind of device or service you would like to see an adapter for?**
The home page "solar-wetter.com" was updated from the owner  to get forcasts for the solar production based on solar radiation data related to the postal code. A passwort is no more necessary.

**Is an official API including documentation is available?**
unknown, details to be found on www.solar-wetter.com

**Are other libraries for an integration available?**
Older adapter for iobroker available, but not yet updates

**Is this device already integrated in other Smart Home systems?**
unknown

**Is this device already integrated in homebridge? Might the ham adapter together with the homebridge plugin be sufficient?**
Please try it and add infos

**Additional context**
Information from the owner of www.solar-wetter.com: 

Dear wuggili,
the postcode forecasts can again be found at www.selection-plz-area.solar-wetter.com
can be accessed (without a password). For use with IoBroker, the adapter would probably have to be reprogrammed due to the changed html code, which I can't do myself.

After you created the issue vote for yourself in the first post of the issue using the "+1"/"Thumbs up" button

**Comment by Apollon77** [comment]
Do you have created an issue with the "Old adapter" before requesting a new Adapter? ;-)

**Comment by klein0r** [comment]
Maybe solar-wetter should be added as an option here: https://github.com/iobroker-community-adapters/ioBroker.pvforecast

**Comment by mcm1957** [comment]
Theres a PR too which is waiting for integration.
https://github.com/iobroker-community-adapters/ioBroker.solarwetter/pull/21

So this is inprogress

**Comment by mcm1957** [comment]
solarwetter 1.1.5 (2023-08-15)
repo: https://github.com/iobroker-community-adapters/ioBroker.solarwetter

If you want to reort any issues or make some suggestion for new features please open a issue at the adapter's repositor.
