### ISSUE TITLE
Tractive GPS Device for Pets

### ISSUE THREAD

**Issue by FlexerJR** [ioBroker/AdapterRequests#714]
**What kind of device or service you would like to see an adapter for?**
Tractive ist ein weltweit genutzter GPS Tiertracer der am Halsband der Tieres befestigt wird. Es gibt verschiedene Geozonen, Bewegungsaufzeichnung, Aktivitätstracing uvm. 

Add name and company of the device, including links to the device and any additional informations[...]

https://tractive.com/de/

**Is an official API including documentation is available?**

Das einzige was ich bist jetzt gefunden habe ist eine Interation von Tractive in Homeassistant

https://github.com/Danielhiversen/home_assistant_tractive

und 

https://community.home-assistant.io/t/tractive-gps-tracker/193652

If yes please add links and informations[...]

**Are other libraries for an integration available?**
Ideally in JavaScript/npm, but also other programming languages are interesting, add Links please

**Is this device already integrated in other Smart Home systems?**
Add Links please
Schon oben verlinkt

**Is this device already integrated in homebridge? Might the ham adapter together with the homebridge plugin be sufficient?**
Please try it and add infos

**Additional context**
Add any other context or screenshots about the feature request here. If the topic was discussed in ioBroker forum please include the link too.

———

After you created the issue vote for yourself in the first post of the issue using the "+1"/"Thumbs up" button

**Comment by eugenstolz** [comment]
Das wäre super!

**Comment by Apollon77** [comment]
@eugenstolz "me too" pststs bringen keine Sichtbarkeit ... EIn Thumbs Up beim ersten Post ist "the way to go" um Dein Interesse zu bekunden

**Comment by FlexerJR** [comment]
Hey to all!

There is an early version of Tractive available. 

Check this one

https://github.com/Guinness1000/ioBroker.tractive

**Comment by FlexerJR** [comment]
Unfortunately, the Developer Guiness1000 stopped his work on the adapter linked above. No answer from him.

**Comment by TA2k** [comment]
https://github.com/xXBJXx/ioBroker.tractive-gps

**Comment by TA2k** [comment]
@xXBJXx will take over

**Comment by mcm1957** [comment]
@xXBJXx please confirm (or post something else :-) ) so that I can assign this issue to you.
Thanks

**Comment by xXBJXx** [comment]
@mcm1957  
yes I would take over

**Comment by TA2k** [comment]
Please ask the developer from the initial to get admin right to the npmjs otherwise you have to rename the adapter
https://www.npmjs.com/package/iobroker.tractive
You can find the mail of the owner

**Comment by mcm1957** [comment]
That's not always necessary. Please ask @Apollon and/or @GermanBluefox . Sometimes bluefox has admin rights already and can move the npm access. But of course the original owner should be contated first - if possible.

As TA2Ks omment seems to be truncated:

martin.michalecz@gmx.at most likely inside io-package.json (at least if he/she filled in the data correctly)

**Comment by xXBJXx** [comment]
@TA2k @mcm1957 
The developer of iobroker.tractive does not answer that was already tried several times no one except him has the npm rights. 
Since I have completely rewritten the adapter and it is therefore also called differently `tractive-gps` there will also be a new npm release for Monday.

**Comment by mcm1957** [comment]
OK, thanks for your work.

**Comment by mcm1957** [comment]
new repo: https://github.com/xXBJXx/ioBroker.tractive-gpshttps://github.com/xXBJXx/ioBroker.tractive-gps
request to add to latest: https://github.com/ioBroker/ioBroker.repositories/pull/2151

**Comment by Wildbill-Z** [comment]
@xXBJXx Are you still active with the Tractive adapter? Some time ago there seemed to be a change in the Tractive API. I wrote it in the forum and an [issue](https://github.com/xXBJXx/ioBroker.tractive-gps/issues/4), but no response. @scrounger created a [pull request](https://github.com/xXBJXx/ioBroker.tractive-gps/pull/5) to fix it, but still no response.

**Comment by mcm1957** [comment]
I've asked per mail today

**Comment by mcm1957** [comment]
new repo: https://github.com/xXBJXx/ioBroker.tractive-gpshttps://github.com/iobroker-community-adapters/ioBroker.tractive-gps
@scronger asked to migrate his fixing PRs

**Comment by aruttkamp** [comment]
> new repo: https://github.com/xXBJXx/ioBroker.tractive-gpshttps://github.com/iobroker-community-adapters/ioBroker.tractive-gps @scronger asked to migrate his fixing PRs

Der Link passt nicht ;-)

**Comment by mcm1957** [comment]
THANKS - fixed
