### ISSUE TITLE
hOn Hoover Waschingmachine

### ISSUE THREAD

**Issue by chrineuh** [ioBroker/AdapterRequests#718]
Hello, 

I have boogth an Hoover Waschingmachine, the Device uses the hOn App. 

Dose somone can make an Adapter for IoBroker for this Devices? 

Thanks

**Comment by TA2k** [comment]
Ja wenn ich Zugangsdaten bekomme
https://forum.iobroker.net/user/tombox

hON oder Hoover Wizard?


https://github.com/ioBroker/AdapterRequests/issues/321

**Comment by TA2k** [comment]
https://forum.iobroker.net/topic/55667/test-adapter-hoover-hon

**Comment by mcm1957** [comment]
Adapter: https://github.com/TA2k/ioBroker.hoover
