### ISSUE TITLE
Entwicklungsfrage / -hilfe?

### ISSUE THREAD

**Issue by ChristianHohman** [ioBroker/AdapterRequests#719]
Hallo, ich bin noch recht neu in der javascript Programmierung und iobroker☺ 

Könnte mir jemand sagen, an welcher Stelle ich noch mehr Dokumentation zum nachlesen finde außer der Doku vom iobroker?

Insbesondere bin ich an dem Punkt in der main.js -> ready, dass ich ich eine websocket Verbindung aufbauen möchte und die Ereignisse "abonnieren" möchte, um dann bei Erhalt einer msg diese zu verarbeiten.
Ich habe leider keine Vorstellung wie ich das umsetzen kann. 
Auch hier wäre ich über tipps / links zur Umsetzung dankbar!

Danke & Liebe Grüße

**Comment by TA2k** [comment]
Ist sicher besser für das Forum:

Beispiele:
https://github.com/TA2k/ioBroker.mercedesme
https://github.com/TA2k/ioBroker.hekr
https://github.com/ice987987/ioBroker.husqvarna-automower

**Comment by ldittmar81** [comment]
Außerdem haben wir eine Telegram Gruppe für Entwickler: https://t.me/ioBroker_development - hier kannst du gerne immer Fragen stellen.

**Comment by Apollon77** [comment]
bester Startpunkt (weil da sollte alles verlinkt sein) -> https://www.iobroker.dev/
Dann Discord oder Forum oder Telegram was "Austausch mit anderen Devs" angeht
