### ISSUE TITLE
snips.ai Oflline Sprachsteuerung

### ISSUE THREAD

**Issue by joeduck** [ioBroker/AdapterRequests#72]
Eine Offline Sprachsteuerung / Assistent die komplett auf einem RPI 3 läuft.
https://snips.ai/

Übersicht über Projekte mit snips:
https://github.com/snipsco/awesome-snips

Eine Anbindung / Skill für homeassistant gibt es schon:
https://www.home-assistant.io/addons/snips/

**Comment by GermanBluefox** [comment]
Have tried it in German?

чт, 10 мая 2018 г., 7:11 joeduck <notifications@github.com>:

**Comment by GermanBluefox** [comment]
I tried to find some video to understand the recognition quality in German,
but nothing found.
Do you know any videos?

сб, 12 мая 2018 г., 17:19 joeduck <notifications@github.com>:

**Comment by joeduck** [comment]
I will record a few videos who shows the functionality with german voice recognition und Matrix Voice Mic.

**Comment by GermanBluefox** [comment]
Super. I am really interested in using of the offline recognition but I am
not convinced about qualify

вс, 13 мая 2018 г., 12:49 joeduck <notifications@github.com>:

**Comment by Apollon77** [comment]
Maybe also interesting: https://medium.com/snips-ai/benchmarking-microphone-arrays-respeaker-conexant-microsemi-acuedge-matrix-creator-minidsp-950de8876fda

**Comment by joeduck** [comment]
Hi Bluefox. Dont want to upload my Videos to Youtube... tooo bade ;-) .
But you can get them from my OneDrive:

https://1drv.ms/f/s!AgAaKhZ1xP4tgXG4FyLN0P31JEdq

One video shows the console Output from snips.
The other video shows my Prototype Jarvis with LED ring on the Top (Matrix Voice).

Hope you are impressed ;-)

**Comment by Apollon77** [comment]
Is this only for raspi?

**Comment by Apollon77** [comment]
Ok found it. Most install Infos are for raspi. More is working too but a bit more work. 

So stretched based ReSpeaker v2 could work.

**Comment by GermanBluefox** [comment]
Funktioniert wirklich gut.

**Comment by Apollon77** [comment]
Was hast du für ein Mikrofon genommen?

**Comment by joeduck** [comment]
Hallo. Ich verwende einen Matrix Voice mit 8 Mics und steuerbarem LED Ring. Funktioniert prima.

**Comment by joeduck** [comment]
Das Respeaker soll auch gut funktionieren und die von snips.ai haben dafür ein Maker kit https://makers.snips.ai/kit/

**Comment by Apollon77** [comment]
Naja "wohnzimmerkompatibel ohne viel Bastelei" ist die auch nicht ;-)) Mal schauen. Kommt auf die lange Liste :-)

**Comment by joeduck** [comment]
Dann musst du dich bis Dez. 2019 gedulden.  Dann kommt snips AIR.
https://m.youtube.com/watch?v=KMzONOP_Mro#

**Comment by Apollon77** [comment]
Wenn die Satelliten noch „raum-Logik“ mitbringen wird’s echt cool ;-)

**Comment by joeduck** [comment]
Funktioniert... und Satelliten gibt's Dank romkabouter schon jetzt https://community.matrix.one/t/matrix-voice-as-a-standalone-mic-for-snips/1669

**Comment by GermanBluefox** [comment]
For  the tests only raspi s required

**Comment by GermanBluefox** [comment]
https://forum.iobroker.net/viewtopic.php?f=8&t=13955

**Comment by Jey-Cee** [comment]
Adapter is here: [https://github.com/Bettman66/ioBroker.snips](url)

**Comment by screendj** [comment]
> Hallo. Ich verwende einen Matrix Voice mit 8 Mics und steuerbarem LED Ring. Funktioniert prima.

Bei mir reagiert Matrix Voice garnicht. Hast du noch etwas umgestellt /eingestellt ?
