### ISSUE TITLE
Vis-Map with tracks

### ISSUE THREAD

**Issue by WorldNavigator** [ioBroker/AdapterRequests#721]
the adapter is already there. i would like to have a possibility to visualize Tracks (list of locations) not only single locations.
if possible in OSM.
i want to follow an object. frequently i get location data (lat/lon) and want to show that in a map. possibly with a button to delete it.

**Comment by Apollon77** [comment]
> the adapter is already there.

Why you then not add a feature request to the adapter if it is already there?

**Comment by WorldNavigator** [comment]
because i do not know how to do that. please advise.

**Comment by Apollon77** [comment]
Go to the repository of this adapter on GitHub and also create an issue there as you did here :-)
