### ISSUE TITLE
Element.IO Matrix-Adapter

### ISSUE THREAD

**Issue by Rudi1982** [ioBroker/AdapterRequests#724]
Hallo Leute,

ich würde mir einen Adapter für den Element.IO wünschen. Den Telegram-Adapter gibt es ja schon und ich denke Element.IO wäre da eine gute Alternative. Zumindest meine Meinung.
Mir persönlich würde es sehr nützen, da ich Telegram eigentlich nur noch wegen dem iobroker nutze.

Würde mich freuen, wenn ihr euch mal über den Adapter Gedanken macht...

Danke im Voraus und liebe Grüße

**Comment by joerghohn** [comment]
Das würde mich auch interessieren. Eigentlich nennt sich der Server dazu **matrix-synapse** und nicht element.io.
Die Administration API findet sich unter https://matrix-org.github.io/synapse/latest/usage/administration/admin_api/index.html
Infos zur Client-Server-API finden sich unter https://matrix.org/docs/guides/client-server-api

**Comment by oelison** [comment]
Ich habe angefangen den zu schreiben. Leider kann ich das Ticket nicht mir zuweisen (self assign geht nicht).

**Comment by oelison** [comment]
Das ging schneller als gedacht. Noch etwas wenig Übersetzung da drin, aber funktioniert bei meinem Server.

**Comment by Rudi1982** [comment]
Danke oelison, dass du dich dieser Idee widmest... Lg, Rudi

**Comment by oelison** [comment]
Revision v0.0.4 ist fertig. Mit Blockly oder js leicht zu bedienen. Es fehlen noch reviews. Ich habe diesen Adapter im Experten modus über die URL https://github.com/oelison/ioBroker.matrix-org installiert. Ich hoffe ich komme bald online.

**Comment by oelison** [comment]
Revision v0.0.5 ist fertig. Etwas sauberer implementiert. Vielleicht auch bessere Fehlermeldungen. Blockly Symbol ist jetzt besser erkennbar.

**Comment by Rudi1982** [comment]
Hi oelison,

bei mir connected der Adapter v 0.0.5 nicht und im log steht nichts...
Meine Angaben in den Adapter-Optionen:

Server: matrix.org (ja, teste auf den öffentlichen Server)
Port: 8448 (also Standart)
Raumname: #raumname:matrix.org
botName und botPasswort ist ja klar, was da drinne steht...

Sind meine Angaben falsch oder hast du sonst ne Idee?

Lg

**Comment by oelison** [comment]
Hi Rudi1982,
Am anfang sollte die Instanz (noch nichts eingestellt) 
matrix-org.0 error	No server set!
im log zeigen.
Wenn alles eingestellt ist, sollte die roomId unter objekte/matrix-org/0/matrixServerData/roomId zu finden sein.
Meist irgendwas mit "!lkdfjajdkfghfgkjh"
Ist der Raum falsch dann steht da nichts, Leider kommt auch keine Fehlermeldung. (Hier müsste ich mal nachbessern)
matrix-org.0 error	Error: Request failed with status code 403
kommt wenn das Passwort falsch ist.
Gruß
Oelison

**Comment by Rudi1982** [comment]
Okay, kurios... Ich habe den Raumnamen in allen Variationen versucht, aber es klappt einfach nicht und mittlerweile bekomme ich folgende Fehlermeldung: 
Server not reached! matrix.org:8448 with room: #xxxxxx

Lg

**Comment by oelison** [comment]
Hm, Ich werde das mal mit meinen Matrix org account ausprobieren. Aber wohl erst morgen.

**Comment by DutchmanNL** [comment]
Alles weitere bitte über issues auf der repo, danke @oelison
