### ISSUE TITLE
Solarman-Adapter

### ISSUE THREAD

**Issue by 4kiwi** [ioBroker/AdapterRequests#725]
Ein Adapter für die Solarman-Webseite wäre toll um die Daten aus einem Balkonkraftwerk mit Bosswerk-Wechselrichtern anzeigen zu können.

https://www.solarman.cn/english.html

![image](https://user-images.githubusercontent.com/105059505/167140569-ec3715d3-ebdc-4da4-9d20-e4e2f337eb61.png)

**Comment by fr00sch** [comment]
Hallo 4kiwi,

der bosswerk hat eine eigenen lokale Webseite. Einfach die IP-Adresse im Browser eingeben und die Zugangsdaten sind: admin ... admin.
Das habe ich hier erstmal so automatisiert: https://github.com/fr00sch/bosswerk_mi600_solar 
Mein nächstes Ziel ist aber das ganze in js zu bringen und dann in einen Adapter zu gießen.
Das wäre dann Cloud-unabhängig und nur den lokalen Zugriff auf die Webseite des Mikroinverters. Wäre das auch für dich interessant?

**Comment by 4kiwi** [comment]
Hallo fr00sch,

klingt interessant!



*Mit freundlichen Grüßen*
*Karsten Wiering*

*Streuweg 39*
*63755 Alzenau*

*Tel.: 06023 50 70 161*
*Mail: ***@***.*** ***@***.***>*


Am Mo., 16. Mai 2022 um 10:20 Uhr schrieb fr00sch ***@***.***

**Comment by fr00sch** [comment]
@4kiwi lösch mal besser deine Hausadresse und Telefonnummer hier!!!!

**Comment by 4kiwi** [comment]
> @4kiwi lösch mal besser deine Hausadresse und Telefonnummer hier!!!!

Done... zu flink...

**Comment by fr00sch** [comment]
@4kiwi 
Ich werde wohl doch keine Adapter dafür bauen, denn ich habe eine leichtere variante mittels http-request gefunden:
Ich habe in NodeRed dazu einen Flow gebaut, eventuell kannst du damit schon was anfangen: https://flows.nodered.org/flow/bf4e518f48eca5922ea3274680ac8692 

Auf die Idee bin ich gekommen dank dieser Verbesserung-Variante des obigen Python-Codes: https://github.com/Skarabaen/BosswerkMI600

**Comment by 4kiwi** [comment]
Danke dafür, werde mir das mal anschauen :-)

**Comment by 4kiwi** [comment]
Hallo Fr00sch,

funktioniert das Script bei Dir? Nach etwas anpassungsarbeit habe ich den Online/Offline-Status sowie Zeit und Datum, die Solarwerte kommen aber nicht an:

![image](https://user-images.githubusercontent.com/105059505/169528880-5aba76c6-688c-49ab-bdd4-9ff20c807a1f.png)

**Comment by fr00sch** [comment]
Hallo 4kiwi,

ja bei mir funktioniert der Flow seit 3 Tagen einwandfrei. Ich kann dir beim debugging helfen, müsste dazu aber von mehrer Zwischenschritt mir mal den "msg.payload" anschauen:
1.) hinter dem "http://192.168....../status.html"
2.) hinter dem "Get Script-Block with webdata_sn"
Wenn mir die Ergebnisse hier rein postest, kann ich mir das mal anschauen und versuchen den Fehler zu finden.

**Comment by 4kiwi** [comment]
1.) 
![image](https://user-images.githubusercontent.com/105059505/169532518-7f40b3d2-3586-418c-9450-b22024179c30.png)

2.)
![image](https://user-images.githubusercontent.com/105059505/169532583-4bd0f870-70fa-4fb1-9696-f2b43f590c14.png)

Was hast Du denn an dem oben geposteten Flow noch abgeändert? Ich habe die IP-Adresse und Login geändert sowie den Standort...

**Comment by fr00sch** [comment]
ich meine die Nachrichten, die hier ankommen: in einem Debug-Output: 
![Screenshot 2022-05-20 151817](https://user-images.githubusercontent.com/51095725/169536283-f5d4ffb0-eef7-48c8-b5a9-54822dc0e085.png)

Die IP-Adresse ist richtig, dass du die geändert hast. Den Login glaube ich kannst du nicht auf dem Bosswerk ändern, deswegen probiere es mal mit "admin": "admin" ... NICHT die Daten vom solarman.cn, dass ist nur für den Login in der Cloud.

**Comment by 4kiwi** [comment]
![image](https://user-images.githubusercontent.com/105059505/169539009-ca59cbae-58d7-4ba7-b595-5b849a810133.png)

![image](https://user-images.githubusercontent.com/105059505/169539288-b0c4f374-72a5-4650-b53f-0303f8184a5f.png)

**Comment by fr00sch** [comment]
Das obere Bild ist nicht ganz der richtige Punkt, bitte hier einmal an den oberen Punkt anschließen:
![Screenshot 2022-05-20 155335](https://user-images.githubusercontent.com/51095725/169542901-afb7d648-51ca-4554-b443-4a98dca9116e.png)
Zusatärlich kannst du dir imFirefox den Quelltext ausgeben lassen: view-source:http://192.168.x.x/status.html
Darin sollte es 2 HTML-Blöcke die mit folgendem beginnen geben: "<script type="text/javascript">"
Bei dem zweiten sollte etwa sowas drinnen stehen:
`<script type="text/javascript">
var webdata_sn = "12345678";
var webdata_msvn = "";
var webdata_ssvn = "";
var webdata_pv_type = "";
var webdata_rate_p = "";
**var webdata_now_p = "43";
var webdata_today_e = "2.70";
var webdata_total_e = "416.9";**
var webdata_alarm = "";
var webdata_utime = "1";
var cover_mid = "4063648958";
var cover_ver = "MW3_15_5406_1.35";
var cover_wmode = "APSTA";
var cover_ap_ssid = "AP_12345678";
var cover_ap_ip = "x.x.x.x";
var cover_ap_mac = "xx:xx:xx:xx:xx:x";
var cover_sta_ssid = "abcdefge";
var cover_sta_rssi = "60%";
var cover_sta_ip = "192.168.x.x";
var cover_sta_mac = "xx:xx:xx:xx:xx:xx";
var status_a = "1";
var status_b = "0";
var status_c = "0";

function initPageText(){....

</script>`
Ist das bei dem letzten der Fall so?

**Comment by raschy** [comment]
Ich hab mich mal drangesetzt und einen Adapter gebaut. Der läuft natürlich gegen den cn-Server. Bei den oben genannten lokalen Möglichkeiten bekommt man leider nur drei Werte. Aus der Cloud kommen doch mehr.

**Comment by fr00sch** [comment]
@raschy das klingt sehr gut. Hast du ein project, wo man das mal selbst testen kann?

**Comment by raschy** [comment]
Ich bin gerade dabei, ein Repository auf zu bauen. Ich denke mal bis zum Wochenende könnte es klappen.

**Comment by basti0681** [comment]
Ich habe https://github.com/Skarabaen/BosswerkMI600 geforkt und entsprechend angepasst, so dass die Werte an den Sonoff/Tasmota adapter geschickt werden. Man braucht jetzt nur noch einen Timer, der da Skript alle x Minuten aufruft.

https://github.com/basti0681/MI600_iobrokerTasmota

**Comment by Ilovegym66** [comment]
Hi super, Dankeschön, funktioniert auf Anhieb!!

**Comment by mcm1957** [comment]
Adapter Repository: https://github.com/raschy/ioBroker.solarmanpv

**Comment by mcm1957** [comment]
Published to latest
