### ISSUE TITLE
UWZ.de - Unwetterzentrale

### ISSUE THREAD

**Issue by Systm21** [ioBroker/AdapterRequests#73]
Would like to have it directly on iobroker, it's a feature, which i am missing from the old FHEM times.

**Comment by Apollon77** [comment]
Please check radar adapter. It should be in there when i remember correctly. Also daswetter have warnings in there. 

Is that what you mean/want?!

**Comment by Fl0ca** [comment]
https://github.com/frankjoke/ioBroker.radar
has nothing to do with Weather alarms, or am i wrong with the adapter you want me to show?

i have tested deinwetter.com, but there are no warnings in that quality, you can get from uwz.de .

i have found the perl code from Fhem on github, maybe it helps? 
https://github.com/tobias-d-oe/fhem-uwz

**Comment by Apollon77** [comment]
Read the readme from radar adapter ...

UWZ Wetterwarnungen

In there. 

Yes strange mix of functionality but ... ;-)

**Comment by GermanBluefox** [comment]
Anyway the radar is the wrong place for that and it must be extra adapter.
Imho

вс, 13 мая 2018 г., 17:24 Florian <notifications@github.com>:

**Comment by Apollon77** [comment]
Yes, Feedback already given to radar developer.

**Comment by dwm66** [comment]
ich hab da mal ein script dazu geschrieben, stell ich gerne als Basis für nen Adapter zur Verfügung

**Comment by Apollon77** [comment]
Bring es doch mal ins Forum und linke es hier. Danke

**Comment by dwm66** [comment]
Aber gern :)
https://forum.iobroker.net/viewtopic.php?f=20&t=7589&p=156760#p156760
Hab grad die letzte Version gepostet.

**Comment by mcm1957** [comment]
Is there any news to this adapter?
UnderInvestigation since 2018 :-) . 

If solved by other adapter, please let us know. If no longer processed we should dessign issue I suggest.

Issue has been referenced in forum: https://forum.iobroker.net/topic/60667/wunsch-unwetterzentrale-adapter/5

**Comment by mcm1957** [comment]
Repo: https://github.com/iobroker-community-adapters/ioBroker.radar2
Repo: https://github.com/ticaki/ioBroker.weather-warnings

UWZ Warnings are provided by at least those two adapters. So lets close here.
