### ISSUE TITLE
Ledvance Smart+ Wifi Adapter

### ISSUE THREAD

**Issue by ErdaloteX** [ioBroker/AdapterRequests#737]
Hi,
Ledvance ehemals Osram hat mittlerweile viele Wifi Lampen draußen die über die Ledvance Smart+ Wifi app angesteuert werden könnnen. Gibt es eine Möglichkeit für die Ledvance Smart+ Wifi Lampen einen Adapter zu erstellen?

Aktuell gibt es nur den alten Osram Lightify Adapter der aber so wie ich das verstehe nur für das Zigbee Gateway ist.

Ledvance hat auch eine API Seite die aber meiner Meinung nach eher dürftig ist, allerdings Kontaktmöglichkeiten für Entwickler bietet.

https://update.ledvance.com/

Die Lampen bieten die möglichkeit über Alexa und Google angesteuert zu werden aber cloud Lösungen würde ich gerne vermeiden. Ein Adpater der daher direkt über Wifi mit den Lampen sich verbinden könnte ohne z.B. Alexa zu benutzen würde daher mega sein.

Danke

**Comment by c4sti3l** [comment]
Schließe mich an, fände ich auch sehr gut!

**Comment by dhanukapulkit** [comment]
Hi @ErdaloteX , Unsere WIFI-Produkte können nur über unsere WIFI-App oder über Google/Alexa/Smart Things usw. gesteuert werden.
Für Zigbee-Produkte haben wir die hier bereits erwähnten Partner-Gateways: https://update.ledvance.com/

**Comment by TA2k** [comment]
@ErdaloteX Ich habe gelesen das es vielleicht nur Tuya Geräte sind hast du mal den Tuya Adapter gecheckt

**Comment by ErdaloteX** [comment]
> Hi @ErdaloteX , Unsere WIFI-Produkte können nur über unsere WIFI-App oder über Google/Alexa/Smart Things usw. gesteuert werden. Für Zigbee-Produkte haben wir die hier bereits erwähnten Partner-Gateways: https://update.ledvance.com/

@dhanukapulkit das ist genau das was ich nicht möchte. Ich will keine Cloudlösung verwenden. Die App ist ja ganz nett aber bringt mir nur was wenn ich ausschließlich meine Devices aus dem Ledvance Universum habe was ich nicht habe und auch nicht haben möchte, da ich mir immer die Option offen lassen möchte auch andere Geräte zu verwenden. Ich verstehe irgendwie nicht warum Ledvance nicht auch eine API für Ihre wifi Geräte bereitstellen kann. Hätte ich vorher mal vernünftig recherchiert gehabt dann hätte ich das Produkt sicherlich nicht gekauft und auf Zigbee gegriffen oder gleich ganz eine andere Marke gekauft. Also wenn ihr eure WiFi Produkte attraktiver machen wollt dann erstellt eine API dafür.

**Comment by ErdaloteX** [comment]
> @ErdaloteX Ich habe gelesen das es vielleicht nur Tuya Geräte sind hast du mal den Tuya Adapter gecheckt

@TA2k danke für den Tip habe ich tatsächlich noch nicht gemacht aber eine kleine Recherche im Internet verspricht nicht viel Hoffnung für die neuesten WiFi Modelle. Die sollen wohl den Tiya Chip noch benutzen aber den so modifiziert haben das der nur mit der ledvance app funktioniert. Werde es aber trotzdem mal ausprobieren mit dem tuya Adapter.

**Comment by neuronflow** [comment]
@ErdaloteX wie sind Deine Erfahrungen?

Die Ledvance App ist leider sehr beschraenkt und voller Bugs..Die hardware scheint gut insbesondere 1500lm Leuchten findet man kaum.

**Comment by neuronflow** [comment]
evt. hilfreich:
https://community.home-assistant.io/t/howto-ledvance-smart-plug-wifi-in-home-assistant-solution/350280/17

**Comment by KoolKeith** [comment]
Ich ärgere mich auch, eine WiFi Lampe von Ledvance gekauft zu haben. War ein Impuls-Kauf, weil es leider keine Philips Zigbee Geräte gab.... Der Versuch, den "Tuya Weg" zu gehen, scheint ein riesen Akt zu sein... App auf echtem Handy oder Emulator einrichten, Tuya Accound anlegen, Proxy einrichten .... alles mega ätzend und ekelhaft cloud-verseucht.
Cloud ist die PEST ! IoT kann nur überleben, wenn Produkte auf Wunsch cloud-frei betrieben werden können. 

@dhanukapulkit Ich würde nie wieder ein Ledvance Produkt kaufen (also ohne Zigbee) !

**Comment by Apollon77** [comment]
Für den Tuya Adapter gab es gestern einen PR der das hinzufügen sollte ... ich schaue das ich die Tage dazu komme das zu releasen

**Comment by philippeaellig** [comment]
Ich habe eine LEDVANCE SMART+ WiFi LED Deckenlampe. Die sehe ich zwar in meinem Netzwerk (Hersteller Tuya Smart Inc.), ich seh sie auch in der Smartlife-App als Gerät, aber wenn ich das Gerät zur App hinzufügen will, läuft der Pairing-Vorgang in ein Timeout. Die Ledvance SMART+ WiFi Geräte lassen sich nicht mit der Tuya-App betreiben. Was [hier](https://github.com/ioBroker/AdapterRequests/issues/737#issuecomment-1237462613) geschrieben wurde, stimmt aus meiner Sicht. Somit bringt man die Lampe nicht ins Tuya - und darum bringt der Adapter dann ja auch nichts.
In der Lampe ist ein [WB3S](https://developer.tuya.com/en/docs/iot/wb3s-module-datasheet?id=K9dx20n6hz5n4), also ein Tuya Chip.

Ich sehe nur drei Wege:

- [LED Driver ersetzen](https://hackaday.com/2021/04/17/replacing-an-esp8266-clone-with-the-real-thing/) [ersetzen](https://zorruno.com/2022/wb3s-replacement-for-home-automation-devices/)
- Firmware der Lampe flushen, [vielleicht geht das mit tasmota](https://github.com/openshwprojects/OpenBK7231T_App)
- eigener Adapter ohne Tuya bauen (wie ursprünglich in diesem issue vorgeschlagen).

Das mit dem eigenen Adapter stelle ich mir aber schwierig vor, weil es keine Doku gibt, wie die Lampen mit der Ledvance-App kommunizieren. Irgendwie müsste man heraustüfteln, wie genau das funktioniert. Wohl sehr ähnlich, wie es mit Tuya geht, weil ja ihr Chip wohl mit einer Ledvance-Firmware drin ist.

**Comment by philippeaellig** [comment]
> Für den Tuya Adapter gab es gestern einen PR der das hinzufügen sollte ... ich schaue das ich die Tage dazu komme das zu releasen

Den Tuya Adapter wird hier das Problem nicht lösen. Weil Tuya das Problem aus meiner Sicht noch verschlimmert. Es gibt [gute Gründe](https://media.ccc.de/v/35c3-9723-smart_home_-_smart_hack#t=2783), die Lampe sich nicht via China anschaltet. Ich möchte in meinem Smarthome ja unabhängig sein, auch ohne Internet. Ich selber habe Tuya zwar lokal (via einer VM, wo dann die SmartLife App läuft und dem Tuya Adapter und Proxy), aber der Aufwand ist einfach zu gross, um eine einfache Lampe zu betreiben. Das kann doch nicht der Weg sein, um einfach mal Licht anzuschalten.

**Comment by Apollon77** [comment]
Naja das ist aber ja die Frage ... der Tiuyya Adapter nutzt die Tuya-Coud im idealfall ausschliesslich zur einmaligen Synchronisation der Daten und ab dann kommuniziert er lokal mit dem Gerät. Aber natürlich muss es jeder selbst entscheiden.
Wenn aber das Protokoll hier "Tuya" ist dann wird es keinen weiteren Adapter geben - warum auch? Der Tuya Adapter kann genau das erfüllen was du beschreibst.

Wenn Du komplett nicht Cloud willst dann ist vllt Ledvance die falsche Wahl?

**Comment by philippeaellig** [comment]
> Naja das ist aber ja die Frage ... der Tiuyya Adapter nutzt die Tuya-Coud im idealfall ausschliesslich zur einmaligen Synchronisation der Daten und ab dann kommuniziert er lokal mit dem Gerät. Aber natürlich muss es jeder selbst entscheiden. Wenn aber das Protokoll hier "Tuya" ist dann wird es keinen weiteren Adapter geben - warum auch? Der Tuya Adapter kann genau das erfüllen was du beschreibst.

Also, Tuya geht nicht, weil man die Ledvance Geräte bei Tuya ja nicht anlernen kann. Auf die Tuya Idee kommt man ja nur darum, weil ein Tuya WBS3 drin ist. Aber, man kriegt die Lampe nicht in die Tuya Cloud. Auch Ledvance sagt das so. Das wird technisch wohl irgendwie verhindert, vielleicht mit einer eigenen Firmware. Und somit kommt die Ledvance Lampe nicht in die Tuya Cloud  und somit auch nicht in den Tuya Adapter. Darum hilft der Tuya Adapter nicht weiter. Oder verstehe ich das Ganze falsch? Darum wär die ursprüngliche Idee von diesem Issue wohl doch der richtige Ansatz.

> Wenn Du komplett nicht Cloud willst dann ist vllt Ledvance die falsche Wahl?

Naja, im Nachhinein ist es die falsche Wahl, ja. Aber die Lampen selber wären ja gut, nur das geschlossene Eco-System nicht. Und die Lampen sind nun mal hier bei mir und nun suche ich eine Lösung. Wenn möglich ohne Lötkolben.

**Comment by Apollon77** [comment]
> Aber, man kriegt die Lampe nicht in die Tuya Cloud

Deswegen fügt der PR im Tuya Adapter auch die Ledvence App als Login option hinzu ... Aber ja vllt versuchen wenn ich es geschafft habe es zu releasen

**Comment by walter-in-space** [comment]
Ich wollte gerade einen bestellen und bin auf den Thread hier gestoßen und werden keine bestellen. Aber was nimmt man dann? Was hat die beste offene API? JSON oder html wäre super. Wer kann was empfehlen?

**Comment by mcm1957** [comment]
> Ich wollte gerade einen bestellen und bin auf den Thread hier gestoßen und werden keine bestellen. Aber was nimmt man dann? Was hat die beste offene API? JSON oder html wäre super. Wer kann was empfehlen?

**Bitte Diskussionen zu ANDERER Hardware, Empfehlungen etc. im FORUM (forum.iobroker.net) führen.** Hierher gehören ausschließlich Informationen zum gewünschten Adapter, Informationen wie dieser umgesetzt werden kann und/oder alternative Implementierungen, Bibliotheken etc. 

OffTopic Beiträge werden ggF gelöscht.

**Comment by Shadow841222** [comment]
Ich habe Tuya Version 3.15.0 auf meinem iobroker und kann damit perfekt meine Ledvance smart+ Wifi Planon Lampen steuern! (Welche nur über wifi mit der ledvance app eingebunden sind)
Alles funktioniert,  An, Aus, Helligkeit, White, Color, Farbänderung per RGB Code.
Laut LOG local über Lan mit IP verbunden, cloud Daten (ledvance) habe ich trotzdem im Tuya  Adapter eingetragen.

**Comment by c1328** [comment]
Lies mal hier rein: https://github.com/Apollon77/ioBroker.tuya/issues/571

**Comment by gidhap** [comment]
@c1328 Danke für den Hinweis, hat mich leider nicht weitergebracht. Ich bekomme ja die Lampen weder in Tuya noch in die SmartLife App rein. Nur in die Ledvance. Und Tuya wiederum lässt mich zwar in die App einloggen, der Adapter kommt aber immer mit der Meldung incorrect ID or password. Nachdem ich jetzt schon zwei Accounts angelegt habe und bei beiden dasselbe Problem besteht. Ich begrabe jetzt das Tuya APP Geraffel und meine LEDVANCE Leuchten gleich mit. Kauf mir eben wieder IKEA und Paulmann und bleibe Lokal....und jetzt gibt's nen Kaffee.

**Comment by mcm1957** [comment]
Tuya Adapter aded ledvance login startin with Release 3.15.0

https://github.com/Apollon77/ioBroker.tuya?tab=readme-ov-file#3150-2023-11-23

So we can close here. If there are problems with the tuya Adapter please open a issue at this adapter.
A dedicated Ledvance Adapter is currently not planned.

**Comment by c1328** [comment]
Kann ich nicht nachvollziehen. Verwende den Tuya Adapter, hinterlege bei Cloud Konto dein Ledvance Konto (und im Pulldown Menü Ledvance auswählen).

Die Ledvance Geräte funktionieren einwandfrei. Ich habe vom Tuya Adapter zwei Instanzen laufen, eine für Smart-Life und eine für Ledvance.

**Comment by mcm1957** [comment]
For further discussion please use the forum http://forum.iobroker.net.

For problemreposrts please create a issue at the tuya adapter repository.
