### ISSUE TITLE
Ecoflow Powerstations

### ISSUE THREAD

**Issue by yasdfgr** [ioBroker/AdapterRequests#739]
**What kind of device or service you would like to see an adapter for?**
Ecoflow Powerstations
https://de.ecoflow.com/collections/portable-power-stations

**Is an official API including documentation is available?**
no, maybe on request from manufacturer

**Are other libraries for an integration available?**
no

**Is this device already integrated in other Smart Home systems?**
no

**Is this device already integrated in homebridge? Might the ham adapter together with the homebridge plugin be sufficient?**
no

**Additional context**
https://forum.iobroker.net/topic/54929/adapter-f%C3%BCr-ecoflow-einbindung?_=1655136811816&lang=de

**Comment by stilicrafter** [comment]
I think the EcoFlow uses Bluetooth to connect to the app, or can the ecoflow join an existing wifi Network?

**Comment by Suvero** [comment]
@stilicrafter RIVER series uses wifi connection, delta series uses bluetooth/wifi.

**Comment by AB-274** [comment]
Maybe this is helpful?
https://github.com/vwt12eh8/hassio-ecoflow

**Comment by Newan** [comment]
Adapter findet ihr unter:

https://github.com/Newan/ioBroker.ecoflow

**Comment by mcm1957** [comment]
Request for https://github.com/ioBroker/ioBroker.repositories/pull/1929

Adapetr already at lasted.
Lets close here

**Comment by foxthefox** [comment]
another adapter available, working with the mqtt cloud.
[https://github.com/foxthefox/ioBroker.ecoflow-mqtt](https://github.com/foxthefox/ioBroker.ecoflow-mqtt)

**Comment by mcm1957** [comment]
NOTE:
https://github.com/foxthefox/ioBroker.ecoflow-mqtt is not yet listed at ioBroker repositories.
Installation using github access happens AT OWN RISK.

@foxthefox 
Please consider addtion to repositories if adapter is working for users
