### ISSUE TITLE
Amazon Echo Button

### ISSUE THREAD

**Issue by mimquadrat** [ioBroker/AdapterRequests#74]
Eine Kompatibilität mit den Echo Buttons von Amazon:
https://www.amazon.de/Echo-Buttons-Alexa-Gadget-2er-Pack/dp/B072C4KCQH
Nicht zu verwechseln mit den Dash Buttons - dafür gibt es ja bereits einen Adapter. 
Die Echo Buttons sind großzügig dimensioniert und können verschiedenste Farben darstellen.
Sie werden via Bluetooth mit einem Echo verbunden.
Der Button würde sich perfekt als Schalter an der Eingangstür eignen auf den man draufhaut wenn man das Haus verlässt.

**Comment by BuZZy1337** [comment]
Wie sieht es mit der Reichweite von den Dingern aus? Hast du da Erfahrung mit?

**Comment by mimquadrat** [comment]
kann ich leider nicht sagen, aber es ist Bluetooth - sollte also schon ein paar Meter gehen.

**Comment by foxriver76** [comment]
Da die Teile ja nur mit Alexa in Verbindung arbeiten, wäre der Ansatz eher das über den Alexa Adapter auszulesen als einen extra Adapter dafür zu schreiben. Was meinst du @Apollon77 ?

**Comment by Apollon77** [comment]
Die Geräte sind als Bluetooth devices gelistet aber das wars auch schon. 

Seit neuestem kann man sie als trigger in routinen nutzen. Man kann also ein virtuelles Objekt über iot und iot skill anlegen und das per Routine schalten. Dann hat man die info wenn er gedrückt wurde. 
Farbliche Rückmeldungen sind aktuell nicht möglich. Ich wüsste jedenfalls nicht wie.

**Comment by mcm1957** [comment]
@Apollon77 
Ist da noch sinnvoll was denkbar oder geht das eh alles über den Alexa Adapter?
Du weißt das sicher auswendig :-)

**Comment by Apollon77** [comment]
Da geht nicht viel -- ausser an löst es über eine Rourtine wo ein Button ein virtuelles  iot Gerät steuert. SOnst wäre ggf low level Bluetooth

**Comment by mimquadrat** [comment]
kann man vergessen.

**Comment by mcm1957** [comment]
Danke für das Feedback
