### ISSUE TITLE
Kältebringer Klimaanlage

### ISSUE THREAD

**Issue by andre-bu** [ioBroker/AdapterRequests#744]
Ein Adpater zur Steuerung der Kältebringer Klimaanlagen wäre echt klasse. Aktuell geht das nur über den Umweg Alexa oder Smart Home App.
Vielen Dank

**Comment by Apollon77** [comment]
Ich fände es echt klasse wenn Du das Template nicht ignoriert hättest sondern alles dort gefragte ausgefüllt hättest ... 

Ein Dev der vllt was zu tun sucht müsste jetzt Google bemühen und über den Firmennamen ALLES selbstrausfinden? Also ich als dev hätte darauf schonmal direkt keinerlei Lust und würde zum nächsten Adapter Request weitergehen. Ist das Dein Ziel?

Weil ich nett bin hier nochmal Alle Fragen zum Bitte Beantworten:

**What kind of device or service you would like to see an adapter for?**
Add name and company of the device, including links to the device and any additional informations[...]

**Is an official API including documentation is available?**
If yes please add links and informations[...]

**Are other libraries for an integration available?**
Ideally in JavaScript/npm, but also other programming languages are interesting, add Links please

**Is this device already integrated in other Smart Home systems?**
Add Links please

**Is this device already integrated in homebridge? Might the ham adapter together with the homebridge plugin be sufficient?**
Please try it and add infos

**Additional context**
Add any other context or screenshots about the feature request here. If the topic was discussed in ioBroker forum please include the link too.

After you created the issue vote for yourself in the first post of the issue using the "+1"/"Thumbs up" button

**Comment by andre-bu** [comment]
@Apollon77 Moin, danke für deine Hinweise. Hab das Template natürlich nicht ignoriert. Weiß aber aktuell nicht wirklich Antworten auf die Fragen. Außer natürlich die erste. Hab daher erst einmal die Anfrage gestartet und hoffe das ein möglicher Entwickler nicht einfach weitergeht. Ich versuche mal über Mr. Google weiteres herauszufinden und ergänze dann die Anfrage

**What kind of device or service you would like to see an adapter for?**
- Split Klimanlage von Kältebringer
https://www.kaeltebringer.de/products/split-klimaanlage-12000-btu

**Comment by andre-bu** [comment]
**Is this device already integrated in other Smart Home systems?**
- works with "Alexa" und "Hey Google"

**Comment by Apollon77** [comment]
Danke. Auch die info das man die Antwort nicht weiß ich eine Antwort ;-)

**Comment by BCB0815** [comment]
Moin! 
Seit letzter Woche habe ich auch eine Klima von Kältebringer. Ein eigener Adapter wäre Klasse!
Richtig viel beitragen kann ich nicht.
Die Steuerung läuft über die folgende App:
SmartLife-SmartHome [ACSmart]
https://play.google.com/store/apps/details?id=com.tcl.smarthome&hl=de

Das finde ich etwas verwirrend, denn es gibt noch eine andere SmartLife-App mit der man wohl Tuya-Geräte steuern kann?

Über Alexa lässt sich die Klima An-/Ausschalten und die Temperatur einstellen. Leider etwas wenig...

**Comment by Apollon77** [comment]
versuch doch mal den Tuya Adapter ob der was findet ...bzw was die Tuya SmartLife App sagt

**Comment by BCB0815** [comment]
> versuch doch mal den Tuya Adapter ob der was findet ...bzw was die Tuya SmartLife App sagt

Bin jetzt mal dazu gekommen. Es funktioniert tatsächlich über den Tuya Adapter und die Klima lässt sich nun wunderbar steuern!

**Comment by Lodda0815** [comment]
> > versuch doch mal den Tuya Adapter ob der was findet ...bzw was die Tuya SmartLife App sagt
> 
> Bin jetzt mal dazu gekommen. Es funktioniert tatsächlich über den Tuya Adapter und die Klima lässt sich nun wunderbar steuern!

Hallo BCB0815, ich versuche seit 3 oder 4 Tagen eine Kältebringer Klima in den io broker zu bekommen ....keine Chance. Könntest du kurz beschreiben wie du die in den Tuya Adapter reinbekommen hast? Wäre wirklich super.

**Comment by BCB0815** [comment]
> > > versuch doch mal den Tuya Adapter ob der was findet ...bzw was die Tuya SmartLife App sagt
> > 
> > 
> > Bin jetzt mal dazu gekommen. Es funktioniert tatsächlich über den Tuya Adapter und die Klima lässt sich nun wunderbar steuern!
> 
> Hallo BCB0815, ich versuche seit 3 oder 4 Tagen eine Kältebringer Klima in den io broker zu bekommen ....keine Chance. Könntest du kurz beschreiben wie du die in den Tuya Adapter reinbekommen hast? Wäre wirklich super.

Ich habe mich an dieses YT gehalten. Allerdings ohne den Emulator aus dem Video,sondern direkt auf meinem Handy
https://youtu.be/gThBSLl1EDI

Hoffe das hilft

**Comment by Lodda0815** [comment]
Hallo BCB0815, vielen lieben Dank für Deine Antwort.
Habe es nach dem genannten Video versucht ....mit Emulation und auch mit Handy ....leider erfolglos. Was mir aufgefallen ist: Im Clip wird die smartlife App von Volcano verwendet ....bei meiner Kältebringer Anlage wird mir eine App von Guangdong angeboten. Vielleicht ist das der Grund .... Welche smartlife App hattest du im Einsatz ?

Viele Grüße vom Lodda

**Comment by BCB0815** [comment]
Deshalb wird es nicht funktionieren, Du musst die SmartLife App von Volcano nehmen. Blauer Hintergrund, weißes Haus mit 'WLAN-Schornstein' rechte Seite.

**Comment by Lodda0815** [comment]
DANKeeeeeeee hat geklappt. Heureka :-)
Habe es hinbekommen mit der Volcano App und NOX als Emulator. Mit Handy leider nicht. 
Klasse ....nochmal vielen vielen Dank

**Comment by mcm1957** [comment]
> > versuch doch mal den Tuya Adapter ob der was findet ...bzw was die Tuya SmartLife App sagt
> 
> Bin jetzt mal dazu gekommen. Es funktioniert tatsächlich über den Tuya Adapter und die Klima lässt sich nun wunderbar steuern!

Damit kann der Issue wohl geschlossen werden.
