### ISSUE TITLE
Timetree Calendar Integration

### ISSUE THREAD

**Issue by JestfulW** [ioBroker/AdapterRequests#746]
**What kind of device or service you would like to see an adapter for?**
Timetree is a Family-Calendar App. I would like to use one, but preferably all of the created calendars on my Timetree account in ioBroker.

**Is an official API including documentation is available?**
https://developers.timetreeapp.com/en/docs/api/overview

**Are other libraries for an integration available?**
npm install @timetreeapp/web-api

**Is this device already integrated in other Smart Home systems?**
Amazon Alexa... Maybe other, too

**Is this device already integrated in homebridge? **
No.

**Comment by EuloTV** [comment]
Darstellung in VIS währe ebenfalls sehr gut!

**Comment by sluggyly1991** [comment]
> As of December 22, 2023 (Friday), the Connect App (API function) is terminated. This function allowed TimeTree to connect to third-party services. Thank you for using the Connect App.

**Comment by mcm1957** [comment]
And even more explicitly:

```
Applications that no longer work with TimeTree

Google Home
Applications created by developers
```

So I will close here. Please open a new issue if some (available) Interface seems to be available.
