### ISSUE TITLE
Emporia Energy - Gen 2 Vue Energy Monitor

### ISSUE THREAD

**Issue by martux1** [ioBroker/AdapterRequests#749]
**What kind of device or service you would like to see an adapter for?**
Emporia Energy - Gen 2 Vue Energy Monitor

https://www.emporiaenergy.com/how-the-vue-energy-monitor-works

https://amzn.eu/5gFEPO1

**Is an official API including documentation is available?**

**Is this device already integrated in other Smart Home systems?**
https://community.emporiaenergy.com/topic/api-to-pull-data/

**Comment by Chris-1965** [comment]
Yes could be fine. Maybe I try to develop one
regards Chris

**Comment by fluke101** [comment]
> Yes could be fine. Maybe I try to develop one regards Chris

Hello,

is there any new information about this? it would be great to get an adapter for iobroker

greeting fluke

**Comment by Chris-1965** [comment]
Hi I am working on the adapter it is already released for testing

Discussion here:  https://forum.iobroker.net/topic/60755/emporia-energy-adapter
or 
https://github.com/Chris-1965/ioBroker.emporia/issues.
Soon I will release a stable version after a test run.
Chris

**Comment by mcm1957** [comment]
Thanks very much for your work and the feedback

**Comment by mcm1957** [comment]
https://github.com/Chris-656/ioBroker.emporia/issues/27

**Comment by mcm1957** [comment]
request for latest: https://github.com/ioBroker/ioBroker.repositories/pull/2194

**Comment by mcm1957** [comment]
adapter has been released.
