### ISSUE TITLE
Fritzbox -  WLAN-Zeitschaltung Uhrzeit ändern 

### ISSUE THREAD

**Issue by blabond** [ioBroker/AdapterRequests#751]
Hi,

Ich suche ein Möglichkeit um in der Fritzbox 6660 (Beta) die WLAN-Zeitschaltung Uhrzeiten ändern zu können.

Hierdurch lässt sich einiges an Strom sparen wenn iobroker dieses ansteuern kann. Da ich keinen Job habe wo man tgl. / Wöchentlichen zu den gleichen Uhrzeiten arbeitet bringt die hauseigene Uhrzeit Option leider wenig und möchte es intelligent über iobroker einstellen.

Danke und mit freundlichen Grüßen

**Comment by Apollon77** [comment]
Bitte schau Dir die Adapter fritzbox/tr-064 an. Die können auch WLAN kontrollieren ... damit kannst DU es mit einem Skript in iobroker steuern. Und wenn dann denke ich wäre ein Feature-Request dort sinnvoll. Das ist ja kein neuer Adapter
