### ISSUE TITLE
myJablotron JA100

### ISSUE THREAD

**Issue by Hant0r** [ioBroker/AdapterRequests#755]
Ich würde gerne meine Alarmanlage von Jablotron JA100 über den Adapter auslesen können.
Aktiv oder nicht, Status der Fenster etc.

Über die myJablotron App funktioniert das z.B.
Webseite: https://www.jablonet.net/

**Is an official API including documentation is available?**
Bin mir nicht sicher. 

Habe das mal gefunden:
https://github.com/hajekmi/myjablotron

**Is this device already integrated in homebridge? Might the ham adapter together with the homebridge plugin be sufficient?**
https://github.com/fdegier/homebridge-jablotron-alarm

Gruß

**Comment by tokenobi** [comment]
Würde mich auch sehr freuen

**Comment by mcm1957** [comment]
Please use / click thumbs-up at first posting instead of me-too commits

**Comment by DEV2DEV-DE** [comment]
@Hant0r Hast Du den PHP-Kram mal ausprobiert?
Wenn das noch funktioniert, könnte man das nach JS portieren.
Man bräuchte dann allerdings gültige Zugangsdaten. Und das Vertrauen in den Entwickler, die nicht zu missbrauchen.

**Comment by DutchmanNL** [comment]
> @Hant0r Hast Du den PHP-Kram mal ausprobiert? 

hat mal jemand es probiert mit dem homebrigde Haddon zu integrieren ?

> Wenn das noch funktioniert, könnte man das nach JS portieren. Man bräuchte dann allerdings gültige Zugangsdaten. Und das Vertrauen in den Entwickler, die nicht zu missbrauchen.

das ist bei vielen Entwicklungen so, nicht alle Entwickler habe auch die geraete und apis wir sind dan n bissl abhängig :)

**Comment by Hant0r** [comment]
Ne habe ich nicht, wüsste auch nicht wie es geht.
Aber nun hast du ja Zugangsdaten :)

**Comment by mcm1957** [comment]
offensichtlich in Arbeit
https://github.com/DEV2DEV-DE/ioBroker.jablotron

**Comment by DEV2DEV-DE** [comment]
Kann hier ein JA-100 Anwender etwas mit anfangen?
![image](https://github.com/ioBroker/AdapterRequests/assets/95883579/967869df-e0fb-4a02-9021-13698632289f)

**Comment by mcm1957** [comment]
adapter has been released to latest.
