### ISSUE TITLE
Fusion Solar - Huawai adapter

### ISSUE THREAD

**Issue by radebold** [ioBroker/AdapterRequests#757]
**What kind of device or service you would like to see an adapter for?**
Huawai

**Is an official API including documentation is available?**
[If yes please add links and informations[...]](https://eu5.fusionsolar.huawei.com/)

**Additional context**
I would like to have this integrated in my IOB, in the moment it is a portal with credentials

**Comment by RoHa78** [comment]
Bei Fusion Solar handelt es sich nahezu um eine Anlage wie bei [Adapter Huawei SUN2000-(3KTL-10KTL)-M1 LUNA2000-(5-30)-S0 DTSU666-H Photovoltaikkombination #752](https://github.com/ioBroker/AdapterRequests/issues/752), vielleicht mit anderer Leistung aber sonst identisch, nur dass hier dann die gelieferten Daten erst aus der Huawei-Cloud gezogen werden müssen...

**Comment by KornSW** [comment]
Done! Here is the Huawei FusionSolar Cloud Adapter:

https://github.com/KornSW/ioBroker.fusionsolar

https://forum.iobroker.net/topic/59422/new-adapter-huawei-fusionsolar-api

**Comment by KornSW** [comment]
![channels](https://user-images.githubusercontent.com/27276069/198554283-d9df18bc-070d-4f51-9aef-98fc6b1f52ca.png)
