### ISSUE TITLE
TPLink Tapo P100 (und andere)

### ISSUE THREAD

**Issue by DEV2DEV-DE** [ioBroker/AdapterRequests#758]
Die Tapo-Steckdosen sind beim großen A so ziemlich die günstigsten.
Ich selbst habe die P100 im Einsatz.

Für HB gibt es hier ein funktionierendes Plugin:
https://www.npmjs.com/package/homebridge-tapo

Grundsätzlich finde ich persönlich den Umweg über den HB-Adapter aber als suboptimal, zumal damit eine weitere mögliche Fehlerquelle hinzukommt.
Anwender ohne Apfelhardware sind außerdem gezwungen, einen Adapter zu installieren den sie ansonsten gar nicht benötigen sondern nur als Wrapper für die eingesetzten Geräte dient.
Von Speicherplatz und CPU-Last mal ganz zu schweigen.

Gruß
Bernd

**Comment by DEV2DEV-DE** [comment]
https://github.com/sanlike0911/node-red-contrib-tplink-tapo-connect-api

**Comment by Hant0r** [comment]
Kann einen P115 (mit Strommessung) zum Test etc. zur Verfügung stellen

**Comment by DEV2DEV-DE** [comment]
Ich könnte einen P100 bereitstellen. Von denen habe ich hier noch ein paar rumliegen.

**Comment by TA2k** [comment]
Wenn jemand ein Tape App Account hat mit Geräte kann ich mir das anschauen
tombox2020@gmail.com

**Comment by Apollon77** [comment]
@TA2k Wenn ich den COde des homebridge plugins dafür lese ist es ne lokale Schnittstelle sogar ...

**Comment by TA2k** [comment]
Ja sieht auch ziemlich trivial aus und kann man blind kopieren aber die Idee war über die Tapo App die Geräte/IPs zu bekommen und sie dann lokal anzusteuern

**Comment by Apollon77** [comment]
Ahh ... right ... wenn die kein MDNS oder UDP haben das man sie finden kann dann ist app account besser. hast recht

**Comment by TA2k** [comment]
Ja es interessiert mich einfach wie die App funktioniert

**Comment by DEV2DEV-DE** [comment]
Dann werde ich den mal etwas anonymisieren und die Dosen neu einbinden. Habe gerade gesehen, dass da alter Kram drin ist. Ich brauche die App halt nicht mehr wirklich, weil die verwendeten Dosen ihre IP behalten und ich nur noch die in die Config eintrage. 

Aber heute nicht mehr ...

**Comment by DEV2DEV-DE** [comment]
> Wenn jemand ein Tape App Account hat mit Geräte kann ich mir das anschauen
Du hast Post ;-)

**Comment by Hant0r** [comment]
Cool danke. 

Falls du noch einen Account oder einen P115 (mit Strommessung) brauchst sag bescheid

**Comment by mrmartin0815** [comment]
An einer P115 Integration hätte ich auch Interesse und könnte bei Bedarf Account samt P115 zur Verfügung stellen.

**Comment by TA2k** [comment]
Ich habe mal was angefangen, leider für lokale Fehler ungetestet einfach mal probieren ob es funktioniert
https://forum.iobroker.net/topic/57336/test-adapter-tp-link-tapo

**Comment by mrmartin0815** [comment]
Klasse, danke @TA2k !
Tapo Adapter wurde erfolgreich installiert und mit TP-Link Credentials bestückt -> Alle Status auf grün.
Allerdings werden de beiden Tapo P115 nicht angezeigt/gefunden: Ich sehe unter Objekte lediglich "tapo.0.info.connection".

**Comment by TA2k** [comment]
Ein debug log via mail wäre hilfreich tombox2020@gmail.com

**Comment by mrmartin0815** [comment]
Gerne! Gibt es eine Anleitung/Link dazu, wie man ein Debug-Log erstellt? 
Im "normalen" Protokoll gibt es nur die o.g Info-Log-Einträge vom Tapo-Adapter.
(Bin gerade erst beim ioBroker angekommen und arbeite mich jetzt ein, bevor PV aufs Dach gepackt wird)

**Comment by mcm1957** [comment]
Link to repo: https://github.com/TA2k/ioBroker.tapo

**Comment by mcm1957** [comment]
TA2k
Please let us know the current state of development.
And please finalize and add the adapter to lates repository if no known (major) issues exist.

**Comment by TA2k** [comment]
in stable
https://github.com/ioBroker/ioBroker.repositories/blob/60637e8e3943bf66070c0c475d90f08de218a68d/sources-dist-stable.json#L2278
