### ISSUE TITLE
Ecovacs Staubsauger-Roboter

### ISSUE THREAD

**Issue by el-lutschi** [ioBroker/AdapterRequests#76]
Hallo,

ich würde mich sehr über einen Adapter für die Ecovacs Staubsauber-Roboter freuen. Hauptsächlich geht es mir um den Deebot 2. Ich habe auf git schon eine Art Programm gefunden die den Robo steuern kann. Vll kann das ja jemand für den iobroker portieren?

https://github.com/wpietri/sucks

**Comment by Apollon77** [comment]
https://www.npmjs.com/package/sucks

JavaScript Port of the lib ;-)

**Comment by el-lutschi** [comment]
Hallo Apollon77,

Danke für deine Antwort. Leider verstehe ich nicht ganz wie das funktionieren soll. Kannst du mir bitte weiterhelfen?

**Comment by Apollon77** [comment]
War im ersten Schritt nur ne Info das es was für JavaScript gibt und nicht nur Python. Du könntest das direkt im JavaScript Adapter nutzen und so erstmal in eigenen Skripten steuern. 

Und es wäre eine Grundlage für einen Adapter.

**Comment by arid154** [comment]
Gibt es Neuigkeiten zu einem Adapter? Habe nun auch einen Deebot 2 Slim aber einfach keine Zeit mich großartig mit JavaScript oder Python auseinader zu setzen. -.-

**Comment by Apollon77** [comment]
Keine Neuigkeiten. Neben dem Ersteller hast nur du etwas gepostet. Keiner von euch (und sonst auch keiner) hat im ersten Post mit einem „Daumen hoch“ abgestimmt ... denke es geht nicht nur dir so mit der Zeit ...

**Comment by senger1985** [comment]
Ich wäre auch an einen funktionierend Adapter interessiert.

**Comment by Apollon77** [comment]
Dann drück mal oben auf den "daumen hoch"

**Comment by senger1985** [comment]
Habe bei dem Beitrag von el-lutschi "daumen hoch" gemacht.
Oder wo meinst du?

**Comment by Apollon77** [comment]
genau da. immer im ersten Beitrag, sonst sieht es keiner

**Comment by Julius278** [comment]
Hallo, bin auch sehr interessiert.
Ich habe selber den Slim 10 und nutze die Ecovacs Home App, da es mit der ECOVACS sich nicht verbunden hat..
Ist sucks für beide Apps konzipiert oder "nur" für eine?
Habe bisher noch keinen ioBroker Adapter entwickelt, aber würde meine Hilfe anbieten.

**Comment by PToT90** [comment]
Hallo, ich habe einen Ecovacs Deebot Slim 2 und würde mich ebenfalls über einen Adapter für ioBroker freuen.

**Comment by Volli1972** [comment]
Hallo, habe nun ebenfalls einen Ecovacs Deebot. Allerdings den OZMO 930. Ich hoffe, dass macht in der Steuerung keinen Unterschied. Würde mich riesig über einen Adapter für IOBroker freuen! Daumen hoch im ersten Post ist gesetzt. :-)

**Comment by erichegit** [comment]
Habe einen ecovacs deebot 900 - IOBroker Integration wäre mehr als nice! :+1:

**Comment by DutchmanNL** [comment]
wen ich die hardware hätte könnt ich mich da mal dran setzen, mal mit hersteller in Verbindung setzen ob die ne ioBroker integration sitzen sehen und vielleicht ne kleine spende dafür übrig haben. :)

**Comment by capitaenz** [comment]
Hallo zusammen,
wir haben einen Deebot 710.
Momentan steuere ich diesen mit einer Universalfernbedienung die ausgestattet ist mit Optokopplern an einem HM-Aktor.
Über einen IOBroker Adapter wäre es natürlich eleganter.
Könnte man das nicht über Spenden finanzieren? Wenn jeder der Interesse an dem Adapter hat, ein paar Euro Spendet, dann müsste es doch für 2 oder 3 der unterschiedlichen Deebots reichen!?

VG
Leif

**Comment by capitaenz** [comment]
@DutchmanNL
Gibt es schon Neuigkeiten?

**Comment by DutchmanNL** [comment]
> Könnte man das nicht über Spenden finanzieren? Wenn jeder der Interesse an dem Adapter hat, ein paar Euro Spendet, dann müsste es doch für 2 oder 3 der unterschiedlichen Deebots reichen!?

Ich probiere of fur solche Sachen die Hersteller zu erreichen habe noch keine zeit gefunden fuer diesen. hier aber die winter Monate kommen näher.
Spenden sind immer willkommen ich spare fuer ein neues Schlagzeug :D 

> @DutchmanNL
> Gibt es schon Neuigkeiten?

Noch keine zeit gefunden ein Bezugsquelle fuer das gerät zu finden aber die Wintermonate kommen näher.

**Comment by GermanBluefox** [comment]
> Ich wäre ebenfalls an einem Adapter interessiert! Der Ecovacs Skill mit Alexa klappt zwar, aber ich würde die Werte des Deebot gerne in IO-Broker haben, damit man diese auch für Skripte und VIS verwenden kann!
> PS: Ich denke durch Weihnachten werden sicher einige das Problem haben, da nicht jeder auf den xiaomi setzt . :)

Dann kann man aktuell ecovac über Adapter "Alexa2" anbinden.

**Comment by Julius278** [comment]
> > Ich wäre ebenfalls an einem Adapter interessiert! Der Ecovacs Skill mit Alexa klappt zwar, aber ich würde die Werte des Deebot gerne in IO-Broker haben, damit man diese auch für Skripte und VIS verwenden kann!
> > PS: Ich denke durch Weihnachten werden sicher einige das Problem haben, da nicht jeder auf den xiaomi setzt . :)
> 
> Dann kann man aktuell ecovac über Adapter "Alexa2" anbinden.

Hast du das kontrolliert? Kann ich nämlich so nicht direkt bestätigen.. letztes mal als ich geschaut habe, konnte ich auch per Alexa Sprachbefehl den kleinen Robo losschicken, im Alexa2 Adapter war er jedoch nicht zu finden.

In der Alexa App habe ich ihn auch bisher nicht als Gerät entdeckt, gerade nochmal einen Suchlauf durchgeführt. Bin allerdings auch nicht zu Hause und es kann sein, dass der Akku leer ist, weil er gestern irgendwo hängen geblieben ist und ich ihn nicht wieder an die Station gestellt habe.

**Comment by EricCLP** [comment]
Hallo, 
ich habe es geschafft, meinen Ecovacs Deebot 900 mehr oder weniger über Alexa und iobroker in Homematic zu integrieren. 

Das ganze funktioniert über die "Bespoken"-Funktion in dem Alexa2-Adapter, einer kleinen Variable aus meiner CCU (SmartHome-Zentrale) und einem kleinen javascript.
Kurz: Wenn ich den Staubsauger starten will, wird die Variable auf "True" gesetzt und die entsprechende Textpassage ("Starte die Reinigung mit Deebot") wird in bespoken.#sendtext geschrieben. Alexa bekommt diese Passage dann über den Bespoken-Dienst als Sprachmitteilung gesendet und behandelt sie, als ob ich ihr direkt den Befehl gegeben habe. Kurz: Der Staubsauger beginnt mit seiner Arbeit!

`function Deebot_Start(){
    setState("alexa2.0.Bespoken.#sendText","Starte die Reinigung mit Deebot");
}


  on({id: "hm-rega.0.5047", change: "gt"}, function() {
                Deebot_Start();
            });

`

**Comment by EricCLP** [comment]
Weil meine CCU meine Anwesenheit kontrolliert und andere Programme innerhalb der CCU die Variable triggern/ durch die Variable getriggert werden können.

**Comment by dbweb-ch** [comment]
Wie im Forum geschrieben würde ich den gerne entwickeln.
Was ich herausgefunden habe:
Es gibt mehrere Python implementierungen und Forks. Es gibt eine nodejs-portierung. Es gibt keinerlei api-doku vom Hersteller. Die api(s) sind ziemlich umständlich, und wie mir scheint für jede Modellgruppe leicht anders. Mein deebot 950 lässt sich z.B. mit einem der Python forks nur starten und stoppen, statusabfragen klappen nicht. Das Problem: Ich werde es zwar vermutlich hinkriegen, einen funktionierende nodejs-lib für meinen 950er zu schreiben und im Adapter zu verwenden, andere werden aber wohl dann nicht gehen. Was habt ihr denn so für Modelle?
Hat schon mal jemand bei Hersteller nachgefragt?

**Comment by mrbungle64** [comment]
Hallo @dbweb-ch,

ich habe zwar nicht beim Hersteller nachgefragt, aber begonnen einen Adapter zu entwickeln:
https://github.com/mrbungle64/ioBroker.ecovacs-deebot

Wenn Du möchtest kannst Du diesen gerne mal testen und Dich sehr gerne auch an der Weiterentwicklung beteiligen.
Verwendet habe ich die [node.js Variante](https://github.com/joostth/sucks.js) von [sucks](https://github.com/wpietri/sucks). Als Modell habe ich einen Slim 2.

Ich wollte eigentlich schon weiter sein und das hier posten. Nun habe ich Deinen Beitrag mal als Anlass genommen.

**Comment by dbweb-ch** [comment]
Hi mrbungle64,

Ich hatte deinen Adapter schon gesehen und auch mal installiert, ging aber nicht. Nach weiteren Nachforschungen weis ich auch wieso:
Problem ist, dass du auf der nodejs- variante basierst, die von "sucks" portiert wurde. Sucks selbst wäre ganz gut, aber es gibt dort einen Pull request der seit Februar hängig ist, und dieser ist nötig um alle D900-Serie Roboter anzusprechen (So auch meinen 950er). Deshalb gibt es einen Fork:
https://github.com/Ligio/ozmo
Ich habe vor 16 tagen beim sucks.js Entwickler angefragt, ob er nicht dem Fork folgen könnte, bisher keine Reaktion, wobei 16 Tage ja noch nicht viel ist. Jetzt müssen wir entweder warten, oder wir bauen die Änderungen von Ligio ein und stellen eine Push request.
Die schönere Alternative wäre natürlich eine Offizielle API, ich habe jetzt mal beim Hersteller nachgefragt, bevor wir uns hier die Hände wund programmieren.

Dein Adapter kann natürlich verwendet werden, jedoch sollte auch der "Unterbau" gut funktionieren. Wenn wir nicht gleich alles neu machen kannst du aber wohl dann einfach die sucks.js austauschen ;)

**Comment by msussek** [comment]
Coole Sache und vielen Dank!
Ich habe heute einen Ozmo 950 bestellt und werde ihn in den nächsten Tagen erhalten.
Dann werde ich diesen Adapter auch mal testen.

**Comment by dbweb-ch** [comment]
Bei mir geht der 950 nicht mit diesem Adapter. Gib doch bitte Rückmeldung ob er bei dir geht, würde mich wundern falls doch.

**Comment by mrbungle64** [comment]
Hallo @msussek und @dbweb-ch,

vielen Dank für Euer Interesse an dem von mir begonnenen Adapter. Ich hoffe, dass wir da (zumindest perspektivisch) auch eine Lösung für diese Modelle finden. Leider habe ich nur einen Deebot Slim 2 - von daher wäre es sinnvoll die Ergebnisse für die anderen Modelle festzuhalten und möglichst einen Issue pro Modell(-Serie) zu erstellen :)
https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues

**Comment by Atze68** [comment]
Hallo Gemeinde,

ich habe einen Deebot 900 und würde mich gerne zum Testen anbieten :-)

Gruß

**Comment by dev-xaur** [comment]
> von daher wäre es sinnvoll die Ergebnisse für die anderen Modelle festzuhalten und möglichst einen Issue pro Modell(-Serie) zu erstellen :)
> https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues

ich war mal so frei und habe den Anfang gemacht ;)

**Comment by mrbungle64** [comment]
> > von daher wäre es sinnvoll die Ergebnisse für die anderen Modelle festzuhalten und möglichst einen Issue pro Modell(-Serie) zu erstellen :)
> > https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues
> 
> ich war mal so frei und habe den Anfang gemacht ;)

Hi @dev-xaur, vielen Dank für Dein Feedback zum [Deebot 601](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/2) :)

**Comment by mrbungle64** [comment]
> Hallo Gemeinde,
> 
> ich habe einen Deebot 900 und würde mich gerne zum Testen anbieten :-)
> 
> Gruß

Hi @Atze68, vielen Dank - sehr gerne :)

Falls Du noch Unterstützung bei der Installation benötigst, sag bitte bescheid.
"Installieren aus eigener URL" => "beliebig":
https://github.com/mrbungle64/ioBroker.ecovacs-deebot.git

**Comment by Atze68** [comment]
Hab jetzt den Adapter installiert und eingerichtet und was soll ich sagen !?!?  Lämpchen ist grün.....Ich teste jetzt mal bisschen rum und berichte dann :-)

**Comment by mrbungle64** [comment]
> Hab jetzt den Adapter installiert und eingerichtet und was soll ich sagen !?!? Lämpchen ist grün.....Ich teste jetzt mal bisschen rum und berichte dann :-)

Sehr gut. Ich bin gespannt, ob der Deebot 900 funktioniert :)

**Comment by Atze68** [comment]
Sooo, jetzt hab ich mal bisschen rumgespielt. In "Control" wird gar nix angezeigt, in History : Human readable timestamp of last state change, Timestamp of last state change und in "Info" indicator.connected= true und device name.
Mit den Werten bzw. Angaben kann ich aber nix anfangen :-(

**Comment by mrbungle64** [comment]
> Sooo, jetzt hab ich mal bisschen rumgespielt. In "Control" wird gar nix angezeigt ...

Unter 'control' sollten 5 Buttons angezeigt werden, welche jeweils eine Funktion auslösen (sollten).
Falls das bei dir nicht der Fall ist scheint bei der Installation des Adapters etwas schiefgelaufen zu sein.

![ecovacs-deebot-adapter-20191212_191655](https://user-images.githubusercontent.com/37313763/70738124-68060d80-1d14-11ea-87be-af4395bf89f9.png)

**Comment by Atze68** [comment]
Moin zusammen, Adapter neu installiert und jetzt sind die Buttons vorhanden, ich melde mich dann später wieder :-)
Danke

**Comment by Atze68** [comment]
Servus,
jetzt hatte ich mal Zeit um alles zu testen, bei mir funktionieren die Buttons zwar, also ich kann sie drücken, allerdings gänzlich ohne Funktion, sprich : " es passiert absolut nix " !

**Comment by mrbungle64** [comment]
Hallo @Atze68,
das ist schade - aber danke schon mal für die Rückmeldung.

Könntest Du vielleicht einen Issue eröffnen, damit wir das jeweils pro Modell-Serie betrachten können?
https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues

Vorher aber noch 2 Fragen:
- Wenn Du den Saugroboter manuell oder per App startest, werden die Werte unter 'info', wie z.B. 'battery', 'chargestatus' oder 'cleanstatus' korrekt angezeigt - oder passiert da gar nichts?
- Erscheinen im Log Fehlermeldungen vor oder nach dem Betätigen der Buttons?

Es wäre gut, wenn Du diese Antworten bzw. Infos direkt in den Issue schreiben könntest.
Vielen Dank schon mal :)

**Comment by gruenerpanzer** [comment]
Zwar bekannt und daher nur zur Info!

Beim Ozmo 930 wird nur der Roboname und der Verbindungsstatus True angezeigt.

Von meinem iPhone gesendet

**Comment by mrbungle64** [comment]
Hallo zusammen,
ich möchte mal ein kleines Update geben:

Ich habe mir kurz vor Weihnachten zusätzlich einen Deebot Ozmo 930 zugelegt und arbeite nun an einer [angepassten Version](https://github.com/mrbungle64/ecovacs-deebot.js) von sucks.js, welche ich dann möglichst bald in meinen [ioBroker-Adapter](https://github.com/mrbungle64/ioBroker.ecovacs-deebot) einbinden möchte, um eine möglichst breite Palette an Modellen zu unterstützen.
Ich verwende dazu die Quellen vom Python Modul [ozmo](https://github.com/Ligio/ozmo).

Die aktuellen Modelle von Ecovacs verwenden weitgehend das MQTT Protokoll zur Kommunikation - sucks.js konnte aber nur XMPP (Jabber), welches die älteren Modelle (inkl. meinem älteren Deebot Slim 2) verwendet haben. Da ich mich in der Vergangheit nicht näher mit dem MQTT Protokoll beschäftigt habe, muss ich mich da erst ein bisschen einarbeiten und die Library als auch der ioBroker-Adapter sollen ja auch beides unterstützen ...

Einen Augenblick wird es also noch dauern - aber ich bin aktiv dran :)

**Comment by Dragon0501** [comment]
N79T works wirhout any issues! Thank you very much!

**Comment by mrbungle64** [comment]
> N79T works wirhout any issues! Thank you very much!

Hi @Dragon0501, I'm glad to hear that. Thanks for your feedback :)

**Comment by Dragon0501** [comment]
![Objekte](https://user-images.githubusercontent.com/59663011/72056840-a5d36300-32cd-11ea-803f-f682af251b82.jpg)
![Vis](https://user-images.githubusercontent.com/59663011/72056842-a66bf980-32cd-11ea-8bb2-687ec2a6ff2f.jpg)

Very nice. I love it!

**Comment by AudidriverA4** [comment]
Schade mit einem Depot 900 tut sich leider nichts, hab Adapter mal neu installiert gerade eben evtl hilft da ja was :-).

<img width="1099" alt="Screenshot 2020-01-09 18 04 50" src="https://user-images.githubusercontent.com/46032677/72088625-de456200-330a-11ea-8a38-d4f3a2786ee5.png">
<img width="1175" alt="Screenshot 2020-01-09 17 56 23" src="https://user-images.githubusercontent.com/46032677/72088627-de456200-330a-11ea-8037-f66f2d774bac.png">

**Comment by mrbungle64** [comment]
> Schade mit einem Depot 900 tut sich leider nichts, hab Adapter mal neu installiert gerade eben evtl hilft da ja was :-).

Hallo @AudidriverA4,

der Deebot 900 gehört wohl zu den Modellen, welche das MQTT-Protokoll benutzen.
Dafür muss - wie [hier](https://github.com/ioBroker/AdapterRequests/issues/76#issuecomment-571336093) beschrieben - die Kommunikation über dieses Protokoll implementiert werden.

Die Liste der getesteten Modelle und deren Status versuche ich in der [Readme](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/blob/master/README.md) auf dem aktuellen Stand zu halten.

Ich bin recht zuversichtlich, dass der Deebot 900 demnächst zu den funktionierenden Modellen gehören wird ;)

**Comment by msussek** [comment]
Tolle Neuigkeiten, sobald MQTT eingebunden ist, werde ich auch mit meinem Ozmo 950 testen. Vielen Dank @mrbungle64

**Comment by AudidriverA4** [comment]
Ok super danke für die Info. Teste es auch gern wenn es soweit ist 👍🏻😎

**Comment by Julius278** [comment]
Wenn ich nur ein Gerät in der App angemeldet habe bzw. in meinem Konto, muss ich dann DeviceNumber 0 wählen?

Ich bekomme meinen Ecovacs Ozmo Slim 10 mit DeviceNumber 0 zumindest als connected

![image](https://user-images.githubusercontent.com/40030409/72163478-32604d00-33c4-11ea-98e5-5a59ffd873a9.png)

**Comment by mrbungle64** [comment]
> Wenn ich nur ein Gerät in der App angemeldet habe bzw. in meinem Konto, muss ich dann DeviceNumber 0 wählen?

Hallo @Julius278,

ja genau - DeviceNumber 0 sollte bei nur einem registriertem Gerät (immer) korrekt sein. Ich werde das auch mal in die Readme aufnehmen und auch in der Adapterkonfiguration besser kenntlich machen.
 
> Ich bekomme meinen Ecovacs Ozmo Slim 10 mit DeviceNumber 0 zumindest als connected

Anhand des Screenshots würde ich sagen, dass der Slim 10 aktuell leider noch nicht zu den unterstützten Geräten gehört. Aber das sollte sich ja bald ändern ;)

**Comment by rebel1985** [comment]
hi, ozmo 900 wird erkannt aber kann nicht gesteuert werden, knöpfe ohne reaktion.

**Comment by mrbungle64** [comment]
Hallo zusammen,

es steht nun eine [neue Version des Adapters](https://github.com/mrbungle64/ioBroker.ecovacs-deebot) zur Verfügung.

Dabei verwende ich nun eine [angepasste Version](https://github.com/mrbungle64/ecovacs-deebot.js) der sucks.js library.
MQTT Geräte (wie z.B. der Ozomo 950 und 600) werden aber leider noch nicht unterstützt, da meine 2 Geräte beide über XMPP kommunizieren. Dachte zum Zeitpunkt des Kaufs eigentlich, dass der Ozmo 930 ein MQTT Gerät ist - war aber falsch gedacht :/

Wer z.B. einen Deebot Ozmo 930 besitzt, sollte nun eine funktionierende Version nutzen können. Geräte wie Deebot N79T und Slim 2 funktionieren hoffentlich weiterhin ;)

Unter 'info' gibt es mit der neuen Version einen State 'communicationProtocol'. Wenn dort 'XMPP' eingetragen wird, stehen die Chancen gut, dass das Modell funktioniert.
Bei Feedback zum Adapter bitte ich den eingetragenen Wert anzugeben (falls noch unbekannt zum jeweiligen Modell).

Sollte sich der Adapter nicht sofort verbinden (rot oder gelb als Status) ist weiterhin ein bisschen Geduld notwendig. Das liegt wahrscheinlich nicht (oder nur bedingt) am Adapter, sondern offensichtlich an irgendwas bei den Ecovacs Servern. In der Mobile App (Android) ist das auch leider sehr oft ein Geduldsspiel bis sich das mal (wieder neu) verbindet ...
In der Adapter Config kann man das aber über "Max. Versuche ..." und "Wartezeit bis ..." noch beeinflussen, falls es mit den Standardeinstellungen nicht funktionieren sollte.

Viel Erfolg beim Testen. Ich freue mich auf Euer Feedback :)

**Comment by Apollon77** [comment]
Wenn der Adapter mal im Latest Repo ist können wir hier auch zu machen :-)

**Comment by msussek** [comment]
Hier gibt's wohl ein Fork für den Ozmo 950 https://github.com/And3rsL/Deebot-for-hassio/tree/master/deebotozmo

Werde mal testen, ob ich damit meinen Bot steuern kann.

**Comment by mrbungle64** [comment]
> Wenn der Adapter mal im Latest Repo ist können wir hier auch zu machen :-)

Hallo @Apollon77,

ich habe einen Pull Request für die Latest Repo erstellt :)

**Comment by xXAeberhardXx** [comment]
Hab mir  mal ne Vis für meinen 930pro gebastelt.
[](https://prnt.sc/qt156t)

Herzlichen dank an @mrbungle64 für die mühe einen funktionierenden Adapter zu basteln

**Comment by xXAeberhardXx** [comment]
![debot widget](https://user-images.githubusercontent.com/47651772/73135201-c296c700-403f-11ea-9aff-0d8fbb8a5be5.png)
Hab mir mal ne Vis für meinen 930pro gebastelt.

Herzlichen dank an @mrbungle64  für die mühe einen funktionierenden Adapter zu basteln :)

**Comment by Dark886** [comment]
Die würde ich auch gern haben @xXAeberhardXx :)

**Comment by mrbungle64** [comment]
> ![debot widget](https://user-images.githubusercontent.com/47651772/73135201-c296c700-403f-11ea-9aff-0d8fbb8a5be5.png)
> Hab mir mal ne Vis für meinen 930pro gebastelt.
> 
> Herzlichen dank an @mrbungle64 für die mühe einen funktionierenden Adapter zu basteln :)

Hallo @xXAeberhardXx,
das freut mich, dass es bei Dir auch funktioniert.

Sieht richtig gut aus das Widget :)
Ich hoffe, dass ich auch bald an die Werte für das Verbrauchsmaterial komme ...

**Comment by AudidriverA4** [comment]
Wow coole Vis hoffentlich klappt das auch bald mit DEEBOT 900 👍🏻

**Comment by xXAeberhardXx** [comment]
@Dark886 
Ich stelle dir die hier gerne zur verfügung bzw. der allgemeinheit 
allerdings erst morgen abend da gleich der Dienst ruft.

@mrbungle64 
die werte von dem Verbrauchsmaterial kommen bei mir nicht vom deebot selbst, sondern ich hab das über Erfahrungswerte so wie Scripte & Timer   gelöst.

**Comment by Dark886** [comment]
Sehr gerne @xXAeberhardXx

**Comment by xXAeberhardXx** [comment]
@mrbungle64 

Aus irgend einem Grund kann der Adapter nicht mehr via iobroker runtergeladen werden, es hagelt lauter Fehlermeldungen 🙁🙁🙁☹

**Comment by mrbungle64** [comment]
> @mrbungle64
> 
> Aus irgend einem Grund kann der Adapter nicht mehr via iobroker runtergeladen werden, es hagelt lauter Fehlermeldungen ☹

Hallo @xXAeberhardXx,

kannst Du die Fehlermeldungen und wie Du den Adapter installierst bitte mal posten?
Bei mir funktioniert es - habe den Adapter gerade noch mal installiert.

**Comment by xXAeberhardXx** [comment]
@mrbungle64 
![FB_IMG_1580220331991](https://user-images.githubusercontent.com/47651772/73270986-14765300-41e0-11ea-834d-a0fb09ecb152.jpg)

**Comment by mrbungle64** [comment]
> @mrbungle64
> ![FB_IMG_1580220331991](https://user-images.githubusercontent.com/47651772/73270986-14765300-41e0-11ea-834d-a0fb09ecb152.jpg)

@xXAeberhardXx,

Das ist nicht der ioBroker Adapter sondern die library die Du versuchst zu installieren...

Das hier ist die korrekte URL:
https://github.com/mrbungle64/ioBroker.ecovacs-deebot.git

**Comment by mrbungle64** [comment]
@xXAeberhardXx,
ich hoffe, dass es mit dieser URL dann geklappt hat ;)

Btw., bei der gerade aktuellen Version von gestern gibt es 2 Dinge zu beachten:
- Das Passwort muss (einmalig) neu gesetzt werden, falls der Adapter vorher schon mal installiert war
- Die Einstellungen unterhalb von Email/Passwort werden zwar (korrekt) gespeichert, aber beim nächsten Aufruf der Adapter Config nicht korrekt angezeigt. Der Bug ist aber hoffentlich bald gefixt.

Ansonsten hoffe ich, dass der Adapter in den nächsten Tagen dann auch über Latest Repo installiert werden kann ;)

**Comment by GermanBluefox** [comment]
Ok. I think, that this discussion could be done in forum or in repo: https://github.com/mrbungle64/ioBroker.ecovacs-deebot and we can close this issue as done.
Ok?

**Comment by Apollon77** [comment]
Yes. SInce yesterday the adapter is also in the latest repo!

**Comment by AudidriverA4** [comment]
Hallo,

Gibt es eigentlich noch Chancen das es mit DEEBOT 900 auch noch klappt oder ehr nicht ?

Kurze Info wäre super danke 😊

**Comment by capitaenz** [comment]
@mrbungle64 
Ich bekomme den Adapter leider auch nicht installiert:
`$ ./iobroker url "https://github.com/mrbungle64/ioBroker.ecovacs-deebot.git"
install https://github.com/mrbungle64/ioBroker.ecovacs-deebot/tarball/394380fce1aff925884fe233e202ffd113bc5fa8
NPM version: 6.13.4
npm install https://github.com/mrbungle64/ioBroker.ecovacs-deebot/tarball/394380fce1aff925884fe233e202ffd113bc5fa8 --loglevel error --prefix "/opt/iobroker" (System call)
upload [5] ecovacs-deebot.admin /opt/iobroker/node_modules/iobroker.ecovacs-deebot/admin/words.js words.js application/javascript
upload [4] ecovacs-deebot.admin /opt/iobroker/node_modules/iobroker.ecovacs-deebot/admin/tsconfig.json tsconfig.json application/json
upload [3] ecovacs-deebot.admin /opt/iobroker/node_modules/iobroker.ecovacs-deebot/admin/style.css style.css text/css
upload [2] ecovacs-deebot.admin /opt/iobroker/node_modules/iobroker.ecovacs-deebot/admin/index_m.html index_m.html text/html
upload [1] ecovacs-deebot.admin /opt/iobroker/node_modules/iobroker.ecovacs-deebot/admin/ecovacs-deebot.png ecovacs-deebot.png image/png
upload [0] ecovacs-deebot.admin /opt/iobroker/node_modules/iobroker.ecovacs-deebot/admin/admin.d.ts admin.d.ts video/mp2t
process exited with code 0`
Ich meine irgendwo gelesen zu haben das noch ein weiteres Paket oder Adapter notwenig ist!?
Würde gerne testen, ob unser Deebot 710 damit läuft :-)

VG
Leif

**Comment by mrbungle64** [comment]
> @mrbungle64
> Ich bekomme den Adapter leider auch nicht installiert:
> `$ ./iobroker url "https://github.com/mrbungle64/ioBroker.ecovacs-deebot.git" install https://github.com/mrbungle64/ioBroker.ecovacs-deebot/tarball/394380fce1aff925884fe233e202ffd113bc5fa8 NPM version: 6.13.4 npm install https://github.com/mrbungle64/ioBroker.ecovacs-deebot/tarball/394380fce1aff925884fe233e202ffd113bc5fa8 --loglevel error --prefix "/opt/iobroker" (System call) upload [5] ecovacs-deebot.admin /opt/iobroker/node_modules/iobroker.ecovacs-deebot/admin/words.js words.js application/javascript upload [4] ecovacs-deebot.admin /opt/iobroker/node_modules/iobroker.ecovacs-deebot/admin/tsconfig.json tsconfig.json application/json upload [3] ecovacs-deebot.admin /opt/iobroker/node_modules/iobroker.ecovacs-deebot/admin/style.css style.css text/css upload [2] ecovacs-deebot.admin /opt/iobroker/node_modules/iobroker.ecovacs-deebot/admin/index_m.html index_m.html text/html upload [1] ecovacs-deebot.admin /opt/iobroker/node_modules/iobroker.ecovacs-deebot/admin/ecovacs-deebot.png ecovacs-deebot.png image/png upload [0] ecovacs-deebot.admin /opt/iobroker/node_modules/iobroker.ecovacs-deebot/admin/admin.d.ts admin.d.ts video/mp2t process exited with code 0`

@capitaenz 
Das sieht mir aber doch aus, als wäre das erfolgreich gewesen. Ich sehe keine Fehlermeldung ...
Der Adapter ist inzischen auch über die Latest Repo verfügbar.
Kannst Du das bitte mal darüber installieren?

> Ich meine irgendwo gelesen zu haben das noch ein weiteres Paket oder Adapter notwenig ist!?

Nein, nur die Module die autom. mit installiert werden.

> Würde gerne testen, ob unser Deebot 710 damit läuft :-)

Sehr gerne - ich bin gespannt :)

**Comment by capitaenz** [comment]
@mrbungle64 
Ha! Also hab es jetzt über "Last Repo" versucht und der Adapter ist installiert worden!
`$ ./iobroker add ecovacs-deebot  --host tinkerboard
host.tinkerboard create instance ecovacs-deebot
host.tinkerboard object system.adapter.ecovacs-deebot.0.sigKill created
host.tinkerboard object system.adapter.ecovacs-deebot.0.eventLoopLag created
host.tinkerboard object system.adapter.ecovacs-deebot.0.outputCount created
host.tinkerboard object system.adapter.ecovacs-deebot.0.inputCount created
host.tinkerboard object system.adapter.ecovacs-deebot.0.uptime created
host.tinkerboard object system.adapter.ecovacs-deebot.0.memRss created
host.tinkerboard object system.adapter.ecovacs-deebot.0.memHeapTotal created
host.tinkerboard object system.adapter.ecovacs-deebot.0.memHeapUsed created
host.tinkerboard object system.adapter.ecovacs-deebot.0.cputime created
host.tinkerboard object system.adapter.ecovacs-deebot.0.cpu created
host.tinkerboard object system.adapter.ecovacs-deebot.0.compactMode created
host.tinkerboard object system.adapter.ecovacs-deebot.0.connected created
host.tinkerboard object system.adapter.ecovacs-deebot.0.alive created
host.tinkerboard object system.adapter.ecovacs-deebot.0 created
process exited with code 0`

Feedback kommt...

VG
Leif

**Comment by mrbungle64** [comment]
> Feedback kommt...

ok gut, kannst Du dann bitte einen Issue erstellen?
https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues

Auch wenn es postives Feedback ist - halt mal kurz zusammenfassen was Du getestet hast, was funktioniert und was ggf. noch nicht funktioniert.

**Comment by capitaenz** [comment]
@mrbungle64 
Hm, also wenn unter Control keine Funktionen erscheinen, dann funktioniert dies mit dem 710 noch nicht?
![Ecovac](https://user-images.githubusercontent.com/1240236/74107518-49d05880-4b71-11ea-8fd1-5130a197d529.JPG)

**Comment by mrbungle64** [comment]
> @mrbungle64
> Hm, also wenn unter Control keine Funktionen erscheinen, dann funktioniert dies mit dem 710 noch nicht?
> ![Ecovac](https://user-images.githubusercontent.com/1240236/74107518-49d05880-4b71-11ea-8fd1-5130a197d529.JPG)

@capitaenz, einfach noch mal die Ansicht aktualisieren.

Aber bitte [hier](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues) einen Issue erstellen. Das hier ist der Adapter Request Issue und der ist inwzischen geschlossen ;)

**Comment by sourex** [comment]
> ![debot widget](https://user-images.githubusercontent.com/47651772/73135201-c296c700-403f-11ea-9aff-0d8fbb8a5be5.png)
> Hab mir mal ne Vis für meinen 930pro gebastelt.
> 
> Herzlichen dank an @mrbungle64 für die mühe einen funktionierenden Adapter zu basteln :)

Hi, könntest bitte einen Export zur Verfügung stellen ? 
Finde irgendwie die PNGS nicht :(

**Comment by jwedenig** [comment]
Hi! Ich hätte gerne das Widget, finde es aber nicht!
Bitte um Hilfe
Jürgen

**Comment by rebel1985** [comment]
> 
> 
> ![debot widget](https://user-images.githubusercontent.com/47651772/73135201-c296c700-403f-11ea-9aff-0d8fbb8a5be5.png)
> Hab mir mal ne Vis für meinen 930pro gebastelt.
> 
> Herzlichen dank an @mrbungle64 für die mühe einen funktionierenden Adapter zu basteln :)

hi könntest du mir das widget auch zur verfügung stellen?
danke

**Comment by FischerICT** [comment]
> ![debot widget](https://user-images.githubusercontent.com/47651772/73135201-c296c700-403f-11ea-9aff-0d8fbb8a5be5.png)
> Hab mir mal ne Vis für meinen 930pro gebastelt.
> 
> Herzlichen dank an @mrbungle64 für die mühe einen funktionierenden Adapter zu basteln :)

Kann mit bitte jemand das Widget vom Deebot zur Verfügung stellen? Danke

**Comment by mrbungle64** [comment]
@FischerICT
Ich würde vorschlagen, dass ihr in einem solchen Fall den Ersteller des Widgets mal direkt erwähnt (@xXAeberhardXx) und nun ggf. auch mal einen Thread im ioBroker Forum dafür erstellt.
Der Issue hier ist ja schon seit ca. 1 Jahr geschlossen 😉
