### ISSUE TITLE
Aida x32/x64 Windows Adapter?

### ISSUE THREAD

**Issue by Troox73** [ioBroker/AdapterRequests#760]
**What kind of device or service you would like to see an adapter for?**
Add name and company of the device, including links to the device and any additional informations[...]

Genial wäre es Objekte von IOBroker verfügbar zu machen in AIDA64 (https://www.aida64.com)
Ich benutze z.B. ein Mini-Display am PC um Informationen wie RAM/CPU etc. anzuzeigen. Das ganze wird realisiert über eine URL die von AIDA64 (Webserver) bereitgestellt wird. Wenn Objekte von IOBroker von AIDA64 gefunden werden könnten - wäre das der Knaller :)

**Is an official API including documentation is available?**
If yes please add links and informations[...]

Mir leider nicht bekannt

**Are other libraries for an integration available?**
Ideally in JavaScript/npm, but also other programming languages are interesting, add Links please

Mir leider nicht bekannt

**Is this device already integrated in other Smart Home systems?**
Add Links please

Mir leider nicht bekannt

**Is this device already integrated in homebridge? Might the ham adapter together with the homebridge plugin be sufficient?**
Please try it and add infos

Mir leider nicht bekannt

**Additional context**
Add any other context or screenshots about the feature request here. If the topic was discussed in ioBroker forum please include the link too.

Mir leider nicht bekannt

After you created the issue vote for yourself in the first post of the issue using the "+1"/"Thumbs up" button

**Comment by mcm1957** [comment]
Gibt es irgendeine Quelle aus der zumindest anzunehmen ist, dass AIDA die Einbindung externer System erlaubt? Ein erstes Überfliegend er Webseite hat bei mir den Eindruck hinterlassen, dass AIDA ein eher geschlossenes System ist das eine ganze Reihe von Sensoren selbst mitbringt.

Sollte eine Info bekannt sein aus der hervorgeht, dass (optimaler Weise wie) externe Sensren eingebunden werden können, dann bitte hier posten. Andernfalls wäre dieser Wunsch wohl eher ein Erweiterungswunsch für AIDA.

Und wenn ein Interface bekannt wäre, dann würde eine Implementierung wohl eine Lizenspende (vom Hersteller oder jemand anderem) erfordern. 30 Tage und lt. Beschreibung tw. eingeschränkt reicht als Lizenz zum Entwickeln sicher nicht.

**Comment by mcm1957** [comment]
Mangels weiterfüghrender Information schließe ich hier mal.

Please open a new issue if still interest and provide sufficient information.
