### ISSUE TITLE
Further development of SmartControl (existing Adapter)

### ISSUE THREAD

**Issue by Deanna4711** [ioBroker/AdapterRequests#766]
[Smart Control](https://github.com/Mic-M/ioBroker.smartcontrol)

As long as this adapter is obviously no longer under development, is there anybody too take care for this adapter please?

This adapter is very useful to do complex logical dependencies for beginners. I would very appreciate, if anybody could look after this.
Thanks a lot.

**Comment by mcm1957** [comment]
https://github.com/Mic-M/ioBroker.smartcontrol

Did you try to comtakt @Mic-m ?
Although it seems that he is no longer active at github at all. (Last commit Dez 2020)

**Comment by Deanna4711** [comment]
> https://github.com/Mic-M/ioBroker.smartcontrol
> 
> Did you try to comtakt @Mic-M ? Although it seems that he is no longer active at github at all. (Last commit Dez 2020)

In the ioBroker Forum someone posted a link to an old thread, where Mic-M wrote, that he will take a digital-detox and wanted to stop every development and participating on github, iobroker and so on. 
So, as long nobody will take over the development of his adapters, they're kind of lost.... It's really sad. I liked Smart control.

**Comment by Deanna4711** [comment]
> Hmm ... bad that noone told him to hand over the adapters to the community before he "goes away". So infact yes we could take over into community, but then still a developer is needed that takes care of it

I saw in ioBroker forum that he asked, if somemone wanted to take over the adapters, but I guess nobody replied.

**Comment by mcm1957** [comment]
@Apollon77 
@oelison

As far as I know this adapter has been oved into community area and is further developed by oelisson.

So I think, the label of this issue could / should be adapted or eventually the issue be closed all together

**Comment by mcm1957** [comment]
1.3.0 and 1.3.1 have been released lately to latest repo.
So we can close this issue here.

Please log issues at the new community repo:
https://github.com/iobroker-community-adapters/ioBroker.smartcontrol
