### ISSUE TITLE
Frigate Adapter

### ISSUE THREAD

**Issue by softwarecrash** [ioBroker/AdapterRequests#768]
frigate ist eigentlich für home assistant gebaut bzw integriert sich dort perfekt.
wäre schön wenn es etwas geben würde damit sich frigate ähnlich schön in iobroker einpflegen liese.
es ist zwar über mqtt steuerbar, aber die datenpunkte und informationen sind teilweise recht knifflig rauszupusseln, von den bildmeldungen in den datenpunkten ganz zu schweigen.

https://frigate.video/

**Comment by ChrisBGL** [comment]
Ein Adapter für frigate wäre wirklich toll!

**Comment by Bettman66** [comment]
[Adapter für Frigate](https://forum.iobroker.net/topic/64928/test-frigate-adapter-v0-0-1-alpha)

**Comment by mcm1957** [comment]
https://github.com/Bettman66/ioBroker.frigate

**Comment by mcm1957** [comment]
Repo: https://github.com/Bettman66/ioBroker.frigate
