### ISSUE TITLE
Further Development: Tibber Adapter

### ISSUE THREAD

**Issue by theGrinchUK** [ioBroker/AdapterRequests#770]
Sadly Magnus8513 (Magnus 1 on iobroker forum) has gone missing or not the time to further develop the tibber adapter:
https://github.com/Magnus8513/ioBroker.tibber
Forum: https://forum.iobroker.net/topic/46954/test-adapter-tibber-v0-1-x

Currently the Pulse is going on sale in Germany, the data received (current use, overall meter readings) are available in the API but not in the adapter.
The API seems to be well documented (https://developer.tibber.com/docs/overview) but I don't have a clue about modifying the adapter.
I could help testing and supply an API-Token.

**Comment by mcm1957** [comment]
Habe im Repo nachgefragt ob der Adapter noch weiter entwickelt wird und/oder ob eine Übernahme in iobroker-communities denkbar wäre.

https://github.com/Magnus8513/ioBroker.tibber/issues/18

**Comment by volkerrichert** [comment]
I'm thinking about using tibber for electricity. I installed the tibber adaptor, but using the test api key. I got data, so it seems to work. I don't have any meter, but maybe the test key also provides them. I'take a look

**Comment by theGrinchUK** [comment]
There is a similar adapter now which is working but does not have the calculation features of this one:
https://github.com/Codibris/ioBroker.tibberconnect

With the recent API changes by tibber, this adapter will most likely stop functioning soon if not maintained.

**Comment by volkerrichert** [comment]
the API changes will only affect websockets, AFAIK. 

Which data do you expect to be shown in ioBroker?

Hm, two adapter for the same stuff....

**Comment by theGrinchUK** [comment]
The live measurements from the Tibber Pulse stopped working with the API change. But that's not implemented into this adapter, so might be fine then.
![image](https://user-images.githubusercontent.com/77161339/203524905-1825999e-84d2-4410-b3dd-45e1067d9188.png)

**Comment by volkerrichert** [comment]
yeap, this will fail and maybe this will run into rate limits (maybe not yet).

But how needs this updates every second? Is that really needed?

**Comment by theGrinchUK** [comment]
`There is a rate limit of 100 requests in 5 minutes per IP address intended to protect the API. `
source: https://developer.tibber.com/docs/overview

So maxing it out would be a request every 3 seconds, I'd go with every 5 to be safe.

This is only usefull when using the Pulse. The info provided can be used for turning on energy consuming things like e-car wallboxes, dryer, dishwasher, ... in the event of surplus power being pushed into the grid.

I also used it fairly efficiently to teach my kids how much leaving their lights on affects energy consumption and thus money spend.

The prices only need to be polled twice per day:
`Note that prices are calculated once per day in the afternoon (for Norway and Sweden they are first preliminary and later finalized potentially with minor changes after currency rates are confirmed). You can use priceInfo.today and priceInfo.tomorrow for fetching them up front instead of only using priceInfo.current for the current hour.`
same source

**Comment by volkerrichert** [comment]
I read this, too. 

But i'm not sure If it's useful to implement / maintain tow adapters of the same kind. A tibber adapter has a very small user group, i think. like my ioBroker.oppoplayer. So maybe we should talk to [Codibris](https://github.com/Codibris) and support him integrating that prediction feature. Maybe this make more sense.

**Comment by theGrinchUK** [comment]
Thumbs up from me!

**Comment by mcm1957** [comment]
@theGrinchUK 
> Thumbs up from me!
Please avoid "Thumbs up" posts without additional information / discussion points but use the thumbs up icon (reachable by the smilie at the right upper corner of eachpost) instead.

**Comment by volkerrichert** [comment]
offtopic: how will the price of a kWh of electricity be calculated, e.g. in Germany? I habe a guess, but am i right?

(epex hourly rate) + tax (mwst 19 % in Germany) + additional taxes (Umlage, Abgaben. Nachweise, 13,06ct/kWh)

looking from the "other end". Assuming i have to pay 50ct/kWh having a fixed price provider:

50ct - 13,06ct = 36,94ct (including tax MwSt)
26,94ct / 1,19 = 31,0420ct (excl. tax) -> break even point.

Is this correct or do i miss something?

THX Volker

**Comment by theGrinchUK** [comment]
looks correct. But those are changing January 1st:


![strom](https://user-images.githubusercontent.com/77161339/205615746-e2bdc8f3-bf96-4182-a7ab-ede2daf5074d.png)

**Comment by volkerrichert** [comment]
hm, the sum (pre 31.12.2022) is larger (13,983) than 13,06ct/kWh shown on tibber.com: Confusing! And it will increase by 0,767. So, break even will be aprox. 1,5ct lower in 2023.

And what will happen if "Strompreisbremse" will kick in?

**Comment by theGrinchUK** [comment]
From their email:
"Auch die Strompreisbremse, die gesetzlich beschlossen wurde, um Verbraucher:innen angesichts der insgesamt gestiegenen Strompreise zu entlasten, wird uns beschäftigen. Wie diese Deckelung bei Tibber im Detail umgesetzt wird, werden wir zeitnah in einer separaten E-Mail erläutern. So viel können wir bereits verraten: Mit der Bremse wirst du einerseits vor längeren Hochpreisphasen geschützt sein und profitierst trotzdem weiterhin von fallenden Preisen, wie wir sie im Oktober diesen Jahres beobachten konnten."

So a cheerful: Who knows??? in in order.

**Comment by volkerrichert** [comment]
THX.

**Comment by theGrinchUK** [comment]
Closing this as an alternative adapter whixh was modified for the new api exists:
https://github.com/Codibris/ioBroker.tibberconnect

**Comment by weindler** [comment]
Nach dem Update zu nodejs 18 Version bringt der Adapter eine Fehlermeldung, deshalb würde ich jemanden suchen der sich diesem Adapter annimmt und weiterentwickelt. Denn die calculation der günstigen Preise fehlt im anderen Adapter ganz. Vielleicht könnte man ja auch die 2 Adapter zu einem verschmelzen. Ich würde hier gerne helfen aber die Adapterentwicklung ist mir ehrlich gesagt zu hoch und ich versteh hier auch nur Bahnhof

**Comment by mcm1957** [comment]
I suggest you add your requests as feature requests at the **alternative adapter https://github.com/Codibris/ioBroker.tibberconnect**
ioBroker.tibber doesnt seem to be maintained any more at all.
