### ISSUE TITLE
Govee LED Adapter

### ISSUE THREAD

**Issue by Dellishelly** [ioBroker/AdapterRequests#781]
Ich suche einen Adapter für Gote LEDs. 
Es gibt zwar einen, der funktioniert nur leider nicht mehr und wird vom ursprünglichen Entwickler auch nicht mehr supported.
Die API wird von Gote kostenlo über die App zur Verfügung gestellt.

Kann wer helfen ?

**Comment by Apollon77** [comment]
> Die API wird von Gote kostenlo über die App zur Verfügung gestellt.

Wie ist der Link zum bisherigen Adapter?

Wie ist das gemeint? Gibts eine API Dokumentation?

**Comment by DEV2DEV-DE** [comment]
Vielleicht kann man ja den alten Adapter als Basis nehmen.
Oder halt gleich neu aufsetzen. Govee bietet wohl jetzt auch den rein lokalen Zugriff ohne Cloud.
https://github.com/nbuenger/ioBroker.govee/issues/15#issue-1332997692

**Comment by mcm1957** [comment]
Developer kontaktiert ob Adapter noch weiterentwickelt wird und / oder eine Migration zu ioBroker-communita möglich wäre

https://github.com/nbuenger/ioBroker.govee/issues/16

**Comment by Apollon77** [comment]
maybe also contact him via email (maybe one from package.json)

**Comment by mcm1957** [comment]
> maybe also contact him via email (maybe one from package.json)

Anfrage per Mail gesendet

**Comment by tommyMX** [comment]
<img width="1632" alt="Bildschirm­foto 2022-11-16 um 11 31 32" src="https://user-images.githubusercontent.com/36209886/202157359-182fb5b4-c708-4e4e-8a86-181ce1fd8ee4.png">

**Comment by nbuenger** [comment]
Moin an euch alle,
es tut mir leid das ich nichts mehr von mir gehört habt.
ich hatte leider keine Zeit mich um die Adapter und seine Probleme zu kümmern.
Ich arbeite derzeit aber an einer neuen Version.
Sobald ich neue Infos habe lasse ich es euch wissen.

VG Nick

**Comment by mcm1957** [comment]
> <img alt="Bildschirm­foto 2022-11-16 um 11 31 32" width="1632" src="https://user-images.githubusercontent.com/36209886/202157359-182fb5b4-c708-4e4e-8a86-181ce1fd8ee4.png">

@tommyMX 
Bitte bei Problemen im Repository des Adapters (https://github.com/nbuenger/ioBroker.govee) ein Issue anlegen.

Der Adapter wird lt. obiger Rückmeldung des Autors weiterentwickelt. Die Kommunikation mit ihm sollte über das Adapter-Repo in GitHub laufen.

Danke

**Comment by Apollon77** [comment]
then we close here
