### ISSUE TITLE
Easy Connect für MCZ Pelletofen

### ISSUE THREAD

**Issue by Semmy100** [ioBroker/AdapterRequests#787]
Ich habe einen Pelletofen von MCZ, in diesen ist das WLAM-Modul Easy Connect eingebaut. Mit den Smartphone lässt sich der Ofen mit der Easy Connect App steuern. Ich würde den Ofen gerne mit Iobroker steuern und benötige hierfür einen Adapter. Ist das möglich?

Gruß
Semmy

**Comment by TA2k** [comment]
https://forum.iobroker.net/topic/59744/test-adapter-micronova-easy-connect-plus/
probier den mal

**Comment by Semmy100** [comment]
Den habe ich schon probiert, funktioniert leider nicht. Es gibt auch eine Easy Connect Plus App, die funktioniert auch nicht.

**Comment by TA2k** [comment]
Das heißt für dich funktioniert nur die Easy Connect App und nicht die Easy Connect Plus App.
Was kommt denn für ein Fehler

**Comment by Semmy100** [comment]
Es kommt zu keiner Verbindung zum Ofen.

**Comment by TA2k** [comment]
funktioniert die ease connect plus app?
Was sagt das iobroker Protokoll beim starten des adapters

**Comment by Semmy100** [comment]
Ich kann in der App keinen Ofen installieren.
Der Adapter zeigt alles grün an, so sieht das log aus:
`<html>
<body>


micronova.0 | 2022-11-24 20:11:08.252 | info | Found 0 devices
-- | -- | -- | --
micronova.0 | 2022-11-24 20:11:08.251 | debug | {"Success":true,"device":[]}
micronova.0 | 2022-11-24 20:11:08.121 | debug | {"Success":true,"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhGRjA3RkE4LUNEMDctNEZGRS1BMjY3LTFGNjBCMUMwNjFEQyIsImp3dGlkIjoiOGNmN2EwZWQtZDQyMS00OTM2LThkNDQtMDE5MjAyMjZjMTU3IiwiZW1haWwiOiJkbGFja2luZ2VyQGdteC5uZXQiLCJjdXN0b21lcl9jb2RlIjoiNzQ2MzE4IiwiaWRfYXBwIjoiNkRGQTQ3QTYtMUU3OC00NEQ4LUEwMzYtMTM2M0MxNzFCM0JCIiwiaWRfYnJhbmQiOiIxIiwiaWF0IjoxNjY5MzE3MDY3LCJleHAiOjE2Njk0MDM0Njd9.mBumFZUsb8DsVyMAdZECfCSq7CCv4Y90qGjnVvoAkU0","refresh_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhGRjA3RkE4LUNEMDctNEZGRS1BMjY3LTFGNjBCMUMwNjFEQyIsInR5cGUiOiJyZWZyZXNoIiwiZW1haWwiOiJkbGFja2luZ2VyQGdteC5uZXQiLCJjdXN0b21lcl9jb2RlIjoiNzQ2MzE4IiwiaWRfYXBwIjoiNkRGQTQ3QTYtMUU3OC00NEQ4LUEwMzYtMTM2M0MxNzFCM0JCIiwiaWRfYnJhbmQiOiIxIiwiaWF0IjoxNjY5MzE3MDY3LCJleHAiOjE2ODQ4NjkwNjd9.pvnWsY6PAKyue0cAn9mteVDwYl6H2oXcK9VE50qFFxY"}
micronova.0 | 2022-11-24 20:11:07.271 | info | Login to Easy connect plus
micronova.0 | 2022-11-24 20:11:07.182 | info | starting. Version 0.0.1 (non-npm: TA2k/ioBroker.micronova#d85c59fc7964f1e2b3b01e68b9757aa9263146a7) in /opt/iobroker/node_modules/iobroker.micronova, node: v16.18.1, js-controller: 4.0.23
micronova.0 | 2022-11-24 20:11:05.825 | debug | States connected to redis: 127.0.0.1:9000
micronova.0 | 2022-11-24 20:11:05.571 | debug | States create User PubSub Client
micronova.0 | 2022-11-24 20:11:05.566 | debug | States create System PubSub Client
micronova.0 | 2022-11-24 20:11:05.445 | debug | Redis States: Use Redis connection: 127.0.0.1:9000
micronova.0 | 2022-11-24 20:11:05.255 | debug | Objects connected to redis: 127.0.0.1:9001
micronova.0 | 2022-11-24 20:11:05.234 | debug | Objects client initialize lua scripts
micronova.0 | 2022-11-24 20:11:04.819 | debug | Objects create User PubSub Client
micronova.0 | 2022-11-24 20:11:04.816 | debug | Objects create System PubSub Client
micronova.0 | 2022-11-24 20:11:04.808 | debug | Objects client ready ... initialize now
micronova.0 | 2022-11-24 20:11:04.611 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001
micronova.0 | 2022-11-24 20:10:59.938 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
micronova.0 | 2022-11-24 20:10:59.937 | info | terminating
micronova.0 | 2022-11-24 20:10:59.928 | info | Got terminate signal TERMINATE_YOURSELF


</body>
</html>`

**Comment by TA2k** [comment]
Du kannst nur in der app easy connect ein Ofen installieren?

**Comment by Semmy100** [comment]
Genau, das klappt nur in der Easy Connect App--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 24.11.22, 20:24 schrieb TA2k ***@***.***>:

   
  Du kannst nur in der app easy connect ein Ofen installieren?

**Comment by TA2k** [comment]
Ich habe mal verschiedene app typen hinzugefügt unter anderem auch easy connect

**Comment by Semmy100** [comment]
Ich habe es mal neu installiert, jetzt habe ich keine Verbindung mit Gerät oder Dienst

**Comment by TA2k** [comment]
Dann benötige ich die Zugangsdaten zum testen
tombox2020@gmail.com

**Comment by Semmy100** [comment]
Jetzt habe ich Zugang zu meinen Ofen

**Comment by Semmy100** [comment]
Kann man da noch mehr Daten vom Ofen ändern wie z.B. Gebläsestufen oder Pelletsmenge?

**Comment by TA2k** [comment]
sollte alles möglich sein was in der app möglich ist

**Comment by Semmy100** [comment]
Wie erkennt man, welche Einträge das sind?

**Comment by TA2k** [comment]
Einfach durch den Abgleich in der App welcher Value zu welchem Wert passt

**Comment by mcm1957** [comment]
Da der eigentliche Adapterlink nicht im issue steht hier ein Nachtrag:

https://github.com/TA2k/ioBroker.micronova

**Comment by mcm1957** [comment]
Der Adapter ist noch nicht released und wenn ich nichts übersehen habe auch noch nicht via npm verfügbar.
-> work in progress passg da besser.
Bitte closen sobald zumindest im latest repo.

**Comment by mcm1957** [comment]
Request to add to latest repo seems to be pending:
https://github.com/ioBroker/ioBroker.repositories/pull/2035

**Comment by mcm1957** [comment]
Adapter is now availbale at repository (latest)

Please record all issues or festure requestst at the adapter repository (https://github.com/TA2k/ioBroker.micronova)

@TA2k Thanks for your work
