### ISSUE TITLE
myVaillant Gateway Connection

### ISSUE THREAD

**Issue by Vocta1310** [ioBroker/AdapterRequests#790]
**What kind of device or service would you like to see an adapter for?**
Integration for new myVaillant App and Gateway FW

**Is the device connected to the internet or only available on a local network?**
both

**Is an official App or Website available?**
https://www.vaillant.de/heizung/produkte/mobile-apps/myvaillant-app/

**Is an official API including documentation available?**
https://developer.vaillant-group.com/

**Are other libraries for an integration available?**
No

**Is this device already integrated in other Smart Home systems?**
No

**Is this device already integrated in homebridge? Might the ham adapter in combination with the homebridge plugin be sufficient?**
No

**Additional context**
After getting the upgrade notification from Vaillant - the Multimatic Adaptor have no connection anymore. In announcement they wrote, that the gateway will get an new upgrade within this process.

**Comment by Vocta1310** [comment]
> What's the different to valiant multimatic app https://forum.iobroker.net/topic/29221/test-adapter-vaillant-multimatic-senso-v0-0-x It looks like the adapter is still working

After the upgrade the adapter can not get any informations. Vaillant provide a completely new User portal - in fact you must register a complete new account. Also the senso / Multimatic App (from Vaillant itself) are dead now. 

https://www.vaillant.de/heizung/produkte/mobile-apps/myvaillant-app/

Here are additional informations. If you have further informations how to get it work with the "old" Multimatic adapter please let me know :)

Thanks!

**Comment by Apollon77** [comment]
But still: Why not adding a ssue to the existing adapter to also support new way?

**Comment by TA2k** [comment]
@Vocta1310 if you can provide an myvaillant account I can add this to the vaillant adapter
tombox2020@gmail.com

**Comment by TA2k** [comment]
Github Version von vaillant unterstützt myvaillant gerate bisher aber nur lesend aber nicht schreiben

**Comment by Vocta1310** [comment]
> 

Perfekt! Funktioniert soweit lesend :)

**Comment by mcm1957** [comment]
Ich gehe mal davon aus, dass der nachfolgende Adapter gemeint ist:
https://github.com/TA2k/ioBroker.vaillant

Da er zur Zeit offensichtlich bearbeitet wird, setz ich das Issue mal auf in-progress.

@TA2K bitte Status switchen / Bescheid geben sobald der Adapter released wurde. Lt. repo ist er ja schon älter wurde aber nie released. Warum eigentlich?
