### ISSUE TITLE
fetch solar data from the cdc Database (measurement data from dwd) as a "standard touch"

### ISSUE THREAD

**Issue by DieWaldfee** [ioBroker/AdapterRequests#795]
Hi together,

my focus ist to generate a standard solar power measurement datapoint - the max. solar energy hitting the ground.
These data are avaiable on the database of the dwd calles cdc database. The informations are represented as files with
the frequency of 5min to hours and summary data. When i am able to get these data over time in a datapoint, i am
able to calculate how many solar power should be generated in this time period and compare this with real production.
While tracking this comparison i am able to see the degeneration or errors of/in my solar modules.
(production on given module surface vs. theoretical production or available solar energy)
This will generate a "standard touch" to calibrate the comparison of own measurements like in astronomy. the nearer
you are to the measruement point the better ist the comparison.

My Issue is to get the climate data from the cdc database in datapoints with timestamp.

My wish is to enter the starting date for a requested measure (solar power, maybe others are interesting too for other models)
and start the import. The data are identified on the cdc database, downloaded, extracted, read and entered in the datapoint.
After import the requested measures the adapter calls the cdc databare frequently to import/update the last measrurements. Frequence like daily, hourly,... to take in focus how often the data are generated - the just read the missing data to timestamp
"now".

CDC-database: https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/10_minutes/solar/now

Description DE and ENG are available there als PDF. measure station IDs are listed in a txt-file
Data interval in this example 10min. Other time ranges are available too :-)
Database structure is organized in files an folders - no API available for now.

This feature request will be entered too as an feature request at the dwd adapter. 
...if the dwd adapter will be restricted only for the weather warning, a new adapter is needed.
(https://github.com/ioBroker/ioBroker.dwd/issues/157)

Here is the adapter request for grid-data: https://github.com/ioBroker/AdapterRequests/issues/796

regards
DieWaldfee

**Comment by Apollon77** [comment]
You also opened an issue in dwd adapter. There it is right. Please only create ONE issue and not 3
