### ISSUE TITLE
fetch solar power over region vom DWD

### ISSUE THREAD

**Issue by DieWaldfee** [ioBroker/AdapterRequests#796]
hi together.

my issue is on one hand an visualisation request and on the other hand an solar power over area datapoints (grid-data).

At first the visualisation:
My whish is to get a grapfical representation of the diffusion- direct- and global solar power in my defined region. The link 
below shows the data for germay in total. These data are a good overview to validate calculated solar production data.

here is the link to the dwd solar power visualisation:
https://www.dwd.de/DE/leistungen/solarenergie/strahlungskarten_sum.html;jsessionid=17860306DA2B82E2A5EA8DDB83EE31AE.live21062?nn=16102

grid-data:
My wish is to read the solar grid data for an defines area and store then in an datapoint. These data should be available 
for calculation or graphical represenation in eg. vis. With these data the same calculation is possible as descriped im my 
other request.
(https://github.com/ioBroker/ioBroker.dwd/issues/157)
(https://github.com/ioBroker/AdapterRequests/issues/795)

The solar power could be used like the "standard touch" in astronomy to compate the availabe power with my own 
production to identify modul degeneration or defekt modules.
The idea is to enter the areas in the adapter as e.g. rectangles or circles. By entering the start date for each area the 
adaper identifies and reads the grid data and stores in an datapoint. After read the initial data to now the adapter 
reads frequently (like daily or houly) the missing grid data form last connect to now. The data history could be done 
with the connetcion of the datapoint with an storage like e.g. mysql.

The Grid data are stored in the CDC-databas organised in files and folders (no api available):
https://opendata.dwd.de/climate_environment/CDC/grids_germany/

best regards 
DieWaldfee

**Comment by Apollon77** [comment]
You also opened an issue in dwd adapter. There it is right. Please only create ONE issue and not 3

**Comment by DieWaldfee** [comment]
@Apollon77: different thing here. Request of grid-data for graphical representation.
2nd ticket at dwd-adapter?

**Comment by Apollon77** [comment]
yes please ... and add details about API and all that can speed up a developers life
