### ISSUE TITLE
Homebridge-Plugin Support (Use Homebridge Plugins to get all Integrations already avbailable there)

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/AdapterRequests#80]
This idea has nothing to do with Homekit or Siri! (Yahka is already there for this!)

The idea is to offer a compatibility layer to use developed homebridge plugins directly in ioBroker to use these already existing integrations.
All data and control options would be mapped to states in iobroker so that all data fromn the Plugin/Devices are shown in ioBroker and all changes done in ioBroker are send to the plugin to control the devices.

With this we can have basic integrations for many systems (all where homebridge plugins exist) for ioBroker with only one adapter. Then specific adapters would mainly be needed for deeper and more specific integrations when needed.

**Comment by xPRozAcx** [comment]
Do you mean something like this for fibaro connection?
https://www.npmjs.com/package/homebridge-fibaro-hc2

**Comment by Apollon77** [comment]
The idea is that you coud use exactly such a module and iobroker use it and create states for it and such

**Comment by xPRozAcx** [comment]
That would be a very good way for the beginning, because dealing with Blockly and/or LUA in Fibaro is much overhead and duty cycly for both systems when syncing all items :)

**Comment by xPRozAcx** [comment]
Please tell me when I can help you. Perhaps I can give VPN access to my Fiaro API on my HC2.

**Comment by Apollon77** [comment]
For now Homebridge should be generic enough to implement it basically ... and theny we can test with several plugins :-)

**Comment by JackWolfskin42** [comment]
Will there also be an IOBroker Plugin for Homebridge?

**Comment by Apollon77** [comment]
This would be a separate topic. You can create a Request if you want :-)

**Comment by Apollon77** [comment]
Done: https://forum.iobroker.net/viewtopic.php?f=36&t=14972
