### ISSUE TITLE
Tibber Pulse Strom Messgerät 

### ISSUE THREAD

**Issue by denjo1982** [ioBroker/AdapterRequests#802]
Ich habe dieses Strom Messgerät gesehen und finde es sehr interessant

https://tibber.com/de/store/produkt/pulse-ir?utm_source=facebook&utm_medium=display&utm_campaign=PRWB_FB_DE_ConversionPurchase_Pulse2022_Ecommerce_Pulse&utm_content=23851920890950754_23852799411580754_23852799411570754&utm_id=fb_Facebook_Mobile_Feed&fbclid=IwAR33QOChxIGUR2Ayx15D16UE7ias7pJjNUnh6ZqUfX0QOFgI7_YJ6z2ryAU

Es ist fertig brauch nicht programmiert werden oder sonstiges, man brauch kein zusätzlichen raspi. 

https://developer.tibber.com/explorer

**Comment by mcm1957** [comment]
Dis you chek thi adapter:

https://github.com/Magnus8513/ioBroker.tibber

Seems to provide an ioBroker interface for tibber api. 
If this adapter does not match your demand please ask at the repo of that adapetr whether it could be enhaned.

If you really suggest a new adapter, please provide clear info what is missing and impossible with existing one.

**Comment by mcm1957** [comment]
@denjo1982 
Did you check this adapter:

https://github.com/Magnus8513/ioBroker.tibber

Seems to provide an ioBroker interface for tibber api.
If this adapter does not match your demand please ask at the repo of that adapetr whether it could be enhaned.

If you really suggest a new adapter, please provide clear info what is missing and impossible with existing one.

I will close this request the next days if there is no feedback why a new adapter would be needed.

**Comment by mcm1957** [comment]
Adapter tibberlink has been released
https://github.com/hombach/ioBroker.tibberlink
