### ISSUE TITLE
JDownloader

### ISSUE THREAD

**Issue by draq0nfly** [ioBroker/AdapterRequests#805]
I'd love to control JDownloader in ioBroker to react to finished downloads, speed, file extraction etc.
- [https://jdownloader.org/](https://jdownloader.org/)

JDownloader is used to download multiple files from the Internet.

Available for Windows, Linux, MacOS, iOS, Android etc. (see [jdownloader.org](https://jdownloader.org/download/index))

There is an [official API including Documentation](https://my.jdownloader.org/developers/).

**Comment by mcm1957** [comment]
dupliyate of #535
