### ISSUE TITLE
Scolia DART Adapter

### ISSUE THREAD

**Issue by JBSullivan** [ioBroker/AdapterRequests#807]
Vielleicht gibt es unter den ioBrokern auch noch ein Verrückte die ebenfalls Dart spielen und welche das Scolia System verwenden.

Mit einem entsprechenden Adapter der auf die Scolia API aufsetzt, könnte man die Scolia Anzeigen direkt in seine heimische VIS integrieren.

https://scoliadarts.com/api/

**Comment by JBSullivan** [comment]
Ich denke wir können diese Adapter Anfrage schließen. Warum?

Ich habe Scolia angeschrieben und auch promt eine Antwort sowie die technische Dokumentation für die API bekommen. 

Leider auch den Hinweis - Die API Freigabe wird PRO BOARD mit monatlich 49,90€ berechnet. Damit dürfte das Projekt ioBroker Integration gestorben sein. 

Der Mehrwert bei einem einzelnen Adapter von ~ 50€ im Monat ist kaum jemanden vermittelbar. Also ist die API Schnittstelle in der Tat nur etwas für Gewerbliche Software Entwickler, die die Kosten in irgend einer Form wieder einspielen können.

Ich gucke mal, ob ich es schaffe, hier auf GIT diese Adapter Anfrage zu schließen.

**Comment by JBSullivan** [comment]
Kosten Nutzen nicht Verhältnismäßig. Darum unrealistisch einen Adapter für ioB entwickeln zu lassen.

**Comment by simon1389** [comment]
50€ monatlich um vom scolia-system die erfassten daten auszulesen und für andere zwecke zu verwenden? für jedes board? wow... das ist schon hart

**Comment by OhTee70** [comment]
Moin,
Scolia hat einen Personal API Plan ins Leben gerufen. API access 1 monat trial frei und dannach entweder 6,90 (halbjährlich) oder 4,90 (jährlich). Ich bin gerade im trial monat allerdings gehen meine skills nicht über die API Abfrage per Postman hinaus. Ggf hat ja jetzt jemand hier wieder gesteigertes Interesse an der API

**Comment by simon1389** [comment]
> Moin, Scolia hat einen Personal API Plan ins Leben gerufen. API access 1 monat trial frei und dannach entweder 6,90/monat (halbjährlich zu zahlen) oder 4,90/monat (jährlich zu zahlen). Ich bin gerade im trial monat allerdings gehen meine skills nicht über die API Abfrage per Postman hinaus. Ggf hat ja jetzt jemand hier wieder gesteigertes Interesse an der API

woher hast du die information? auf der scolia seite kann ich dazu jetz nicht direkt was finden

**Comment by OhTee70** [comment]
Ich hatte denen vor einer Woche eine email geschrieben, Auszug aus der Antwort folgend.

**Pricing**
Starting from 2021, we introduced the Personal API Plan to support non-commercial API users, mainly individuals.
Pricing of the Personal API Plan is as follows:

    €6.90/month/board (billed every 6 months, paid up front) - one month free trial
    €4.90/month/board (billed every 12 months, paid up front)  - one month free trial

Please note that the Personal API Plan

    allows at most 3 boards per service account,
    is available for non-commercial customers only. Non-commercial means not primarily intended for or directed towards commercial advantage or monetary compensation.

Let me know how you would like to proceed.
