### ISSUE TITLE
iobroker CCU3 Addon

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/AdapterRequests#81]
Provide an CCU3 addon for ioBroker like e.g. https://github.com/hobbyquaker/RedMatic

**Comment by Hypnos3** [comment]
@jens-maus hat im Homematic Forum die Aussage getroffen ein derartiges AddOn zu erstellen.

**Comment by jens-maus** [comment]
Ich habe dazu nicht nur die Aussage getroffen sondern schon vor längerem angefangen ein ioBroker CCU Addon zu basteln. Bisher aber nie die Zeit gehabt dieses weiter zu bauen bzw. zu vollenden. Auch macht es IMHO ohnehin nur Sinn dieses für RaspberryMatic+Tinkerboard anzubieten das dann auch mit 2GB RAM kommt.

Das ioBroker addon ist hier zu finden:

https://github.com/jens-maus/hm-iobroker

**Comment by zautrix** [comment]
@Apollon77 
Issue can be closed:
https://github.com/zautrix/hm-iobroker

**Comment by DutchmanNL** [comment]
I think the issue should not be closed or is the adapter working ?
