### ISSUE TITLE
Deye SUN Hybrid-Wechselrichter

### ISSUE THREAD

**Issue by eller-ge** [ioBroker/AdapterRequests#811]
Ein Adapter für Deye Wechselrichter

**Comment by Apollon77** [comment]
Meinst Du es ist eine gute Idee das Template mit seinen Fragen einfach zu löschen und einen kryptischen Einzeiler ohne jegliche Details einzustellen?
Daher schliesse ich hier. Bitte neu anlegen und die gestellten Fragen beantworten. Danke
