### ISSUE TITLE
AGFEO ES Telefonanlage

### ISSUE THREAD

**Issue by hglohr** [ioBroker/AdapterRequests#819]
HAb grad gesehen, dass es schon einen Post dafür gibt 

Hallo,
Mir würde ein Adapter für die Telefonanlagen Generation ES fehlen.
Gibt es da vielleicht die Möglichkeit was bereitzustellen.

**Comment by mcm1957** [comment]
In jedem Fall bitte das TEMPLATE benutzen ...

**Comment by mcm1957** [comment]
duplicate #413
