### ISSUE TITLE
"State-Editor Lite" Adapter (Minimal Footprint for slow connections)

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/AdapterRequests#82]
For slow connections Admin3 and also cloud pro Admin has too big footprint to be able to work with.

Idea is a "State-Editor" (searching, viewing, changing states) as minimalistic web-interface

**Comment by Waly-de** [comment]
I would really like to be able to use all of the states on my cell phone. The mobile adapter just doesn't work. I only see a white, blank page. The admin page crashes because I have too many data points.

Has the project started yet? Does anyone know of any other way?

**Comment by Apollon77** [comment]
there are other visualization adapters available that work ... iqontrol, material, lovelace ...

**Comment by oweitman** [comment]
which are the requirements that such an adaptder should do?
in react?
with socketio?

there can be a dashboard area and a search area
maybe such an adapter didnt request all datapoints at once.
you can search hieraricaly from level to level an pin often used datapoints to the dashboard
only state values can be edited, no datapoint configuration?

**Comment by Apollon77** [comment]
The idea is to have a small footprint, so if react (or others) it needs to use tree-shaking for the deps and as less as possible :-)
Socket.io has the benefit that long polling is available as fallback if normal websocket do not work because of the connection
But question is if it makes sense to use an "self defined lightweight" interface that only transports data that are needed - aso question is if "real time updates" are a feature (if shpuld be disabled by default and can be enabled or such). So maybe better a "reload mechanism which then c ollects changed data on server side and only transports them if needed.

Dashboard is a good idea and yes state values are enogh in my eyes.

But in fact thats just my opinion out of "I tried once to open admin from a mega low internet in turkey vacation" :-)

**Comment by mcm1957** [comment]
If this is really still a need, I suggest to add a issue at admin to provide a slim interface. I do not see any chance that a dedicated adapter will be created for this.
