### ISSUE TITLE
Urlaubs / Absenheits / Zufalls / random Adapter

### ISSUE THREAD

**Issue by BenAhrdt** [ioBroker/AdapterRequests#824]
Hallo, wäre es möglich einen "Zufallsadapter" zu entwickeln?
Bspw. den man aktiviert, wenn man in der Urlaub fährt und welcher die gewünschten Datenpunkte dann per Zufall ein uns aus schaltet?

Idee: Man hat eine Bestimmte "Aufzählung" namens "Random" oder so....
Dort legt man alle gewünschten Datenpunkte rein, welche man von dem Adapter schalten lassen möchte.
Der Adapter schaut dann diese enum durch und schaltet die Datenpunkte per Zufall ein und aus.

Wäre dass ein gangbarer Weg, bzw. wär hätte eine bessere Idee, einen anderen Vorschlag.
Hat noch jemand Interesse an so etwas?

**Comment by Apollon77** [comment]
Duplicate zu https://github.com/ioBroker/AdapterRequests/issues/11 ?

**Comment by mcm1957** [comment]
Yes - duplicate #11 

Waiting for someone to implemnt such an adapter.

**Comment by BenAhrdt** [comment]
sorry übersehen
