### ISSUE TITLE
ESPHome Adapter weiterentwickeln und neue Funktionen von ESp Home abbilden

### ISSUE THREAD

**Issue by Matze1811** [ioBroker/AdapterRequests#825]
Hallo,
leider ist der bestehende Adapter zur Integration von ESPHome im Stand von 2021 stehengeblieben. Bugs werden nicht behoben, der Adapter steht nunmehr seit über 2 Jahren auf beta status failed.
Neue Funktionen, welche sich in ESPHome abbilden sind nicht realisiert.  Unter anderem z. Bsp. die Funktion Button.
Dies ist ein deutlicher Nachteil gegenüber HA, wo eine vollständig, gepflegter Adapter zur Verfügung steht.

Ich bin leider kein Programmierer, würde mich aber freuen, wenn dieser Adapter wieder mit Leben gefüllt wird (gern auch gegen eine Spende :-).
Ansonsten bleibt leider nur die Alternative den IOB gegen HA zu tauschen.

Grüße
Matthias

**Comment by mcm1957** [comment]
Do you refer to https://github.com/DrozmotiX/ioBroker.esphome?

**Comment by Matze1811** [comment]
Yes

**Comment by mcm1957** [comment]
As far as I know is @DutchmanNL still active. I'll assign this request to him. Please contact him directly via github repo or wait for a statement.

**Comment by Matze1811** [comment]
Hello, I contacted @DutchmanNL . He takes care of it. :-)
