### ISSUE TITLE
Senec Solar Battery - Cloud API for e.g. Wallbox Control

### ISSUE THREAD

**Issue by jhejmann** [ioBroker/AdapterRequests#827]
**What kind of device or service would you like to see an adapter for?**
To control the Senec Home Battery and attached Wallbox. Wallbox can only be persistantly be switched on/off & charge mode change using the App

**Is the device connected to the internet or only available on a local network?**
Internet API

**Is an official App or Website available?**
SENEC App for iOS and Android

**Is an official API including documentation available?**
No, but on Postman

**Are other libraries for an integration available?**
https://documenter.getpostman.com/view/10329335/UVCB9ihW#84ad7fb7-c90a-4bbb-867c-047ee9b5a589

**Is this device already integrated in other Smart Home systems?**
found only local unprotected HTTP API calls. Here the cloud overwrites settings all 5 minutes
https://github.com/nobl/ioBroker.senec

**Is this device already integrated in homebridge? Might the ham adapter in combination with the homebridge plugin be sufficient?**
None found for cloud API

**Additional context**
Based on this much better integrations can be relized. e.g. charge to a certain level and then switch to solar surplus charging.
Happy to support testing and maybe coding but not skilled enough for complete development.

**Comment by mcm1957** [comment]
As adapter ioBroker.senec already exist please open a issue at the adapterreposiory if you encounter any problems or want to suggestca feature.
