### ISSUE TITLE
BambuLab adapter

### ISSUE THREAD

**Issue by baeriwiliwonka** [ioBroker/AdapterRequests#829]
**What kind of device or service would you like to see an adapter for?**
BambuLab 3D printers
- X1C
- P1P 

**Is the device connected to the internet or only available on a local network?**
Both, there is a possibility to print via a Cloudservice, but also there is a "LAN only" feature

**Is an official App or Website available?**
Official app named Bambu Handy:
https://play.google.com/store/apps/details?id=bbl.intl.bambulab.com&hl=de&gl=US&pli=1

**Is an official API including documentation available?**
As far as I know there is no documentation available, but there is also a workaround using NodeRed:
https://forum.iobroker.net/topic/61585/bambu-lab-3d-drucker-mqtt-integration/69?lang=de

Hopefully this can be used to generate a simple adapter which can display the print status like time left, layer, temperatues, fan speeds and so on

**Are other libraries for an integration available?**
-

**Is this device already integrated in other Smart Home systems?**
Only via NodeRed as linked above

**Is this device already integrated in homebridge? Might the ham adapter in combination with the homebridge plugin be sufficient?**
-

**Additional context**
-

After you create the issue, please vote for yourself in the first post of the issue using the "+1"/"Thumbs up" button

**Comment by baeriwiliwonka** [comment]
Habe es nun als DAU tatsächlich mit der NodeRed Instanz hinbekommen.
Ein Adapter wäre natürlich schöner, vielleicht findet sich ja jemand, der Anhand dieses NodeRed Ablaufs einen Adapter bauen kann?

**Comment by XSDiVer** [comment]
Hallo hab mal ein bißchen ausprobiert.

Es geht auf jedenfall auch ohne "Node Red".

Ich habe den MQTT Adapter in ioBroker genommen.

Hab mir unter "device.Seriennummer_Deines_Babus.report" das JSON in eine Text Datei kopiert um zu sehen was 
da alles so im Angebot ist. Mir Datenpunkte angelegt - die ich gebrauchen kann, und mit "JSONata" die entsprechenden
Daten in die selbst angelegten Datenpunkte aktualisiert.

Bsp.:  `setState("0_userdata.0.X1C.Temp_Nozzle"/*Temp_Nozzle*/, parseFloat((await jsonataExpression((function () { try {return JSON.parse(getState("mqtt.0.device.00M09A340700121.report").val);} catch(e) {return {};}})(),'print.nozzle_temper'))), true);`

(hab das mit Blockly gemacht - das hier ist die aktuelle Nozzle Temperatur)

Kann man schön in ein VIS einbinden.

Schalten kann man mit dieser Methode (noch) nichts.

Und die Livebild einbindung fehlt auch noch.

Villeicht findet von Euch ja jemand die Lösung ganz nett.

**Comment by DutchmanNL** [comment]
> Habe es nun als DAU tatsächlich mit der NodeRed Instanz hinbekommen.
> Ein Adapter wäre natürlich schöner, vielleicht findet sich ja jemand, der Anhand dieses NodeRed Ablaufs einen Adapter bauen kann?

Da ich auch einen Bambulab X1 habe konnte ich das hier nicht liegen lassen, mit dank an den Informationen im forum habe ich einen adapter erstellt der alle Daten per MQTT Verbindung live bekommt.

Schalten werden ich im laufe des tages/morgen implementieren, soweit mir bekannt kann man aber nur start/stop/resume und die Lampe schalten

Wen jemand die anderen MQTT befehle zum steuern kennt gerne her damit dan ergänze ich das.

Der adapter ist in einem beta status, die erste version kann über git und NPM installiert werden.
Wen alles einigermassen läuft mache ich einen PR zur aufnähme in den admin

Hier zum adapter: [ioBroker.bambulab](https://github.com/DrozmotiX/ioBroker.bambulab)

**Comment by DutchmanNL** [comment]
PR für latest erstellt, das issue hier kan dan mal zu. Wen noch jemand mqtt Befehle findet außer Start/stop/resume/Licht an/aus bekomme ich die gerne 🤗

https://github.com/ioBroker/ioBroker.repositories/pull/2456

**Comment by mcm1957** [comment]
Adapter is not yet available at repositories

**Comment by mcm1957** [comment]
released

**Comment by Sickone4** [comment]
is there a way not to get error messages due to the fact that the printer is offline?

**Comment by mcm1957** [comment]
Adapter has been released to latest repository.
Please use forum (https://forum.iobroker.net) for general discussions and open a issue at adapter repository in case of bugs or to deposit feature requests.
