### ISSUE TITLE
Google Kontakte

### ISSUE THREAD

**Issue by bahnuhr** [ioBroker/AdapterRequests#83]
Ich würde mir einen Adapter wünschen, wo man auf die Google Kontakte zugreifen kann.

Also:
- Neuanlage oder ändern von Kontakte
- Zugriff auf die gespeicherten Kontaktbilder auf google

Und dann halt die Darstellung in vis.

mfg
Dieter

**Comment by Xyolyp** [comment]
Ich würde mir zusätzlich wünschen, dass eine Telefonbuchsuche und eine Rückwärtssuche (Name zu Nummer und Nummer zu Name) implementiert wird.

**Comment by bahnuhr** [comment]
@Xyolyp 
Das funktioniert schon mit dem TR064 Adapter von soef (also die alte Version). 
Mit der community Version funktioniert dies bisher nicht.
-> siehe github tr064 soef - Thema: phonebook

**Comment by Apollon77** [comment]
Was hat dieses generelle "Google Kontakte abfragen" Thema mit TR064 zu tun? Also ich verstehe dieses Thema ganz generell. Wenn das Thema hier für tr-0654 gedacht ist dann gehört das hier zu gemacht.

**Comment by bahnuhr** [comment]
Ja apollon mach hier zu.
Ich brauche diesen Adapter nach nun 14 Monaten nicht mehr.

**Comment by Apollon77** [comment]
@bahnuhr ne stop ... nochmal bitte: Ist der Request ein Adapter der Google Kontaktdaten in ioBroker zur Verfügung stellt? oder hat es was mit tr-064 zu tun?

**Comment by bahnuhr** [comment]
Ziel war es:
Ich pflege meine Kontakte im Handy über google.
Und diese Kontakte sind in meiner fritzbox als telefonbuch verknüpft.
Wenn es nun klingelt will ich das Bild des Anrufers anzeigen lassen.
Pfad des image wird im tr064 Adapter angezeigt; klappt aber nicht.

Und dann kam die Idee einen Adapter zu haben in dem man auf google zugreifen kann; Kontakte bearbeiten kann und auch die Bilder angezeigt bekommt wenn es klingelt.

Und danach suche ich nun seit 2 Jahren; die Anfrage hier seit 14 Monaten.

Script kann ich ein bisschen; aber dies ist zu hoch für mich.

Also Fazit:
seit 2 Jahren such ich.
Im Forum kommt keine Hilfe.
Im Internet find ich auch keine Lösung.
Google auth2 hab ich nicht hinbekommen.
Der Adapterwunsch ist 14 Monate alt; Rückäußerung bisher keine.

Also von mir aus schließen.

**Comment by Apollon77** [comment]
Auch wenn Du der Ersteller bist haben bisher 10 andere User die Idee geliked ... also scheint e ja ein paar User zugeben die das auch gut finden. Also Abwarten. Vllt kommt es noch.

Ich erkläre jetzt hier in diesem Thread nicht nochmals wie die Adapter-Requests funktionieren ... das sollte bekannt sein.

**Comment by WLAN-Kabel** [comment]
Ich habe einen erstellt. Den könnt ihr gerne einmal testen [ioBroker.contact](https://github.com/WLAN-Kabel/ioBroker.contact). Die Einrichtung ist ein bisschen kompliziert, aber wenn man es geschafft hat, ist es sehr einfach.

**Comment by Apollon77** [comment]
Cool. Stellst du ihn im Forum in nem Tester thread vor?! Dann mache ich hier mal zu. Gib Bescheid wenn du fragen hast und freue mich dann was uns Repo aufzunehmen ;-)

**Comment by WLAN-Kabel** [comment]
Werde ich machen :)
