### ISSUE TITLE
infrared4you IFW Infrared Heating Panel

### ISSUE THREAD

**Issue by PastCoder** [ioBroker/AdapterRequests#830]
**What kind of device or service would you like to see an adapter for?**
Infrared4You heating device which can be controlled with the Infrared4You app. 
The manual is available in https://www.infrared4you.eu/_files/ugd/fe1548_020c509021d540388081ebac006f4abe.pdf

**Is the device connected to the internet or only available on a local network?**
The device is connected via Wifi to my local network. Via the app it can be controlled also if my mobile is not in the local network.

**Is an official App or Website available?**
Manual: https://www.infrared4you.eu/_files/ugd/fe1548_020c509021d540388081ebac006f4abe.pdf
Android APP: It seems that it is not available in the Google Playstore anymore. Only APK in other places.

**Is an official API including documentation available?**
No (as far as I know)

**Are other libraries for an integration available?**
No (as far as I know)

**Is this device already integrated in other Smart Home systems?**
According to documentation it can be controlled via Google Assistent & Amazon Alexa

**Is this device already integrated in homebridge? Might the ham adapter in combination with the homebridge plugin be sufficient?**
No (as far as I could google it)

**Additional context**
-

After you create the issue, please vote for yourself in the first post of the issue using the "+1"/"Thumbs up" button

**Comment by PastCoder** [comment]
@mcm1957 I saw your "hardware needed" label, which makes perfectly sense for the heating device. Could I somehow support with my device (e.g. Wireshark traces)?

**Comment by PastCoder** [comment]
The vendor infrared4you changed to the SmartLife app. 
This means at the end, that it works with the tuya cloud. And by this the device can be used with the https://github.com/Apollon77/ioBroker.tuya

**Comment by mcm1957** [comment]
Thanks for the feedback
