### ISSUE TITLE
PVOutput.org - Globale Ausgabe für PVAnlagen

### ISSUE THREAD

**Issue by vatoslocos18** [ioBroker/AdapterRequests#84]
Servus,

da ich meine aktuelle Informationen immer an den PVOutput.org weiterreiche dachte ich mir vielleicht ist es möglich hier zu einen Adapter zu bauen. Somit könnte ich die Daten auch in VIS anreichern.
Ich könnte mir vorstellen das auch noch andere Personen diesen Dienst nutzen da er kostenlos ist und die Daten somit sehr gut auswertbar sind.

Eine Api dazu gibt es auch:
https://pvoutput.org/help.html#api

Leider ist das ganz für mich als Laie nicht möglich... 
Vielleicht hat ja jemand Bock das ganze um zu setzen! Ich würde mich riesig freuen!

**Comment by Seqway** [comment]
Ich werde mir das mal anschauen und eine Umgebung aufsetzen. Ich halte Euch auf dem Laufenden !

**Comment by Seqway** [comment]
Okay,
nach einigen Diskussionen im Forum wwerde ich es mal versuchen, den Adapter anzuegehen - versprechen kann ich nichts!

Idee ist, dass man in der Admin-Oberfläche die entsprechenden Daten eingibt (von zB seinem Wechselrichter, der im iobroker bereits drin ist zB über modbus) und diese Datenpunkte genommen werden und nach PVOutput.org geschrieben werden.

Dies ist die Idee, mal sehen was draus wird :-)

**Comment by ldittmar81** [comment]
https://github.com/Seqway/ioBroker.pvoutputorg

**Comment by rg-engineering** [comment]
@Seqway ist das Projekt noch aktuell? Wenn nicht, würde ich mich darum kümmern. Ich benötige im ersten step die get-Funktionen, um mehrere Systeme, die schon Daten über sbfspot an pvoutput.org senden, zu monitoren. Im nächsten step könnten auch Daten geschrieben werden...

**Comment by rg-engineering** [comment]
Falls jemand Interesse hat, hier eine erste Version zum download von Statistik, Status und System-Informationen...

https://github.com/rg-engineering/ioBroker.pvoutputorg

**Comment by rg-engineering** [comment]
@Apollon77 Du kannst dieses issue schliessen, Adapter ist in latest...
