### ISSUE TITLE
Lambda EUL Wärmepumpe

### ISSUE THREAD

**Issue by hrglzpf** [ioBroker/AdapterRequests#842]
Lambda EUL Wärmepumpe

Erreichbar über Modbus RTU und Modbus TCP
https://lambda-wp.at/wp-content/uploads/2023/04/Modbus-Protokoll-und-Beschreibung.pdf

Hauptziel wäre, die PV-Integration (Vorgabe Leistungsaufnahme Soll) zu realisieren

**Comment by Icke-de** [comment]
Hi, 
Ich habe gerade so gut wie einen Adapter fertig, der via Modbus TCP Wechselrichter z. B.  Integriert. Die Struktur habe ich so gebaut, dass unter der Instanz ein Ordner erstellt wird. 
Adapter.0.[Hersteller].[Device].Info dort werden Datenpunkte wie Zustand / Seriennummer usw. Erstellt. Unter [Device]. werden die Datenpunkte Momentane Produktion / Tagesproduktion / ges. Produktion erstellt und aktualisiert. Fällt die Produktion auf "0" wird die Abfragefrequenz vergrößert. (Einfach um den TCP Verkehr zu minimieren). Theoretisch funktioniert das bestimmt auch mit Modbus RTU das habe ich nicht getestet und auch nicht vor. Wenn Netzwerk geht, dann nehme ich das. 

Um es abzuschließen, ich glaube dein Gerät kann in den Adapter integriert werden. Habe mir die Doku allerdings noch nicht angeschaut. Würde das aber mal tun. 

Momentan ist bei mir ein SMA Sunny Tripower 8.0 integriert. Hab das alles aber erst im DEV Server und auch noch keinen Namen für den Adapter. Ursprünglich für SMA Geräte, dann kam allerdings der Gedanke, das theoretisch alle Modbusgeräte integriert werden können. 

Grüße

**Comment by Icke-de** [comment]
@hrglzpf : Da ich keine Lambda EUL WP habe, benötige ich ein paar Infos.

1. wie ist der genaue Typ der WP?
2. welche Modbusregister sind für dein Vorhaben relevant?
3. welche Register sind noch sinnvoll ?

Kennst du dich mit NodeJS aus?, Dann könnte ich dir über ein Repro mal eine Test App zur Verfügung stellen, um zu schauen, ob die richtigen Werte herauskommen.

Danke

**Comment by ArnoD15** [comment]
Ich frage mich gerade, warum man einen eigenen Adapter benötigt, wenn man mit Modbus TCP und dem Modbus Adapter eine Verbindung aufbauen kann.
Was man dann noch benötigt, ist ein einfaches Script, das die Einspeiseleistung an Register 40103 weiterreicht.
z.B so :

`
const sID_Netzleistung_W = 'e3dc-rscp.0.EMS.POWER_GRID'
const sID_WP_Aktuelle_Leistung = `modbus.2.holdingRegisters.40103_Aktuelle_Leistung`

// Netzleistung an Modbus Schnittstelle LW-Pumpe Schreiben um über PV-Leistung zu regeln.
on({id: sID_Netzleistung_W, change: "ne"}, async function (obj) {
    await setStateAsync(sID_WP_Aktuelle_Leistung,obj.state.val);
});
`

Den Rest erledigt die LW Pumpe von Lambda.

**Comment by mcm1957** [comment]
@Icke-de 

Hi,
Gibt es zu diesem Request schon einen Update / Adapter-Repo etc.
Oder wurde die Entwicklung eingestellt?

**Comment by hrglzpf** [comment]
Sorry, dass ich mich so lange nicht gemeldet habe - war lange Zeit auf overload.
Das Thema hat sich erledigt.
Mit dem Modbus-Adapter ist alles möglich.

**Comment by mcm1957** [comment]
Danke fürs Feedback

**Comment by Avarios** [comment]
Hast du heraus gefunden, wie die Lambda reagiert wenn man die Werte übergibt ?
Ich arbeite gerade an einem Tool und wollte alle 5 sek den aktuellen Wert schreiben.
Ist das zu viel ?

**Comment by ArnoD15** [comment]
Zu viel ist das nicht, ich schreibe alle 3 sek. neue Werte über die Modbus Schnittstelle.

**Comment by mcm1957** [comment]
This Issue has been closed.

For further discussions about this device and its integration please use out forum: https://forum.iobroker.net

If you feel the need for a dedictaed adapter please create a new issue and state why modbus soes not solve your problem. In addition please be informed that creating a new adapter might last some time.
