### ISSUE TITLE
WIR Elektronik Rolladensteuerung Adapter/IoBroker

### ISSUE THREAD

**Issue by Keulehd** [ioBroker/AdapterRequests#848]
**What kind of device or service would you like to see an adapter for?**

Adapter zum Steuern von Gurtwicklern der Firma WIR Elekronik. 

Hier im Einsatz:
eWickler Funk Comfort eW-940-f-m, eWickler Funk Comfort Compact eW-540-m mit Gateway v6
https://wir-elektronik.de/Aufputz-eWICKLER/1001-000039
https://wir-elektronik.de/Aufputz-eWICKLER-compact/1001-000060
https://wir-elektronik.de/WIR-CONNeCT-Gateway-V6/1100-000064
[WIR-CONNeCT_Gateway_V6_Datenblatt.pdf](https://github.com/ioBroker/AdapterRequests/files/11855965/WIR-CONNeCT_Gateway_V6_Datenblatt.pdf)
[WIR-CONNeCT_Kompatibilitätsliste.pdf](https://github.com/ioBroker/AdapterRequests/files/11855966/WIR-CONNeCT_Kompatibilitatsliste.pdf)

**Is the device connected to the internet or only available on a local network?**

Es arbeitet in einer Cloud. das Gateway ist per WLAN mit dem Internet verbunden.

**Is an official App or Website available?**

Internet: https://wir-elektronik.de/Gurtwickler/
APP: https://play.google.com/store/apps/details?id=de.wir_elektronik.wir_connect_home
APP: https://play.google.com/store/apps/details?id=de.wir_elektronik.wir_connect

**Is an official API including documentation available?**

Hallo Daniel K., 
vielen Dank für Ihr Interesse zur Teilnahme an unserem 3rd Party Developer Programm. Unsere AIO GATEWAYS API ist derzeit noch im Beta-Status und wir stellen diese ausschließlich ausgewählten Integratoren zur Verfügung, die unsere AIO GATEWAYS in eigene Anwendungen integrieren wollen. 
Unser Business Development Team wird Sie kurzfristig kontaktieren. 

Mit freundlichen Grüßen / Regards 
Ihr mediola Business Development Team 

mediola connected living AG 
Rennbahnstr. 72-74 - D-60528 Frankfurt Main 
Tel: +49 (0)69 - 96870-324 
Fax: +49 (0)69 - 21005-733 
Internet: https://www.mediola.com 

**Are other libraries for an integration available?**

[API_AIO_GATEWAYS-All.pdf](https://github.com/ioBroker/AdapterRequests/files/11855987/API_AIO_GATEWAYS-All.pdf)

**Is this device already integrated in other Smart Home systems?**

Leider keine Ahnung

**Is this device already integrated in homebridge? Might the ham adapter in combination with the homebridge plugin be sufficient?**

Weiß ich leider nicht

**Comment by mcm1957** [comment]
Daces einen mediola adapter gibt bitte mal schaun ob der passt od ggF erweitert werden kann.

**Comment by mcm1957** [comment]
https://github.com/oelison/ioBroker.mediola-gateway

**Comment by Keulehd** [comment]
Danke für die schnelle Antwort. Kann man den Mediola Adapter schon installieren zum testen oder hab ich da was falsch verstanden ? Denn bei den Adaptern kann ich den nicht finden. Dankeschön im Voraus.

**Comment by Keulehd** [comment]
Mit dem Mediola Adapter klappt es nicht. Folgendes steht im LOG obwohl ich die richtige IP und auch MAC-Adresse eingegeben habe:


mediola-gateway.0 | 2023-06-24 11:40:50.552 | error | unkown device on this port
mediola-gateway.0 | 2023-06-24 11:40:50.524 | error | no valid detection method defined
mediola-gateway.0 | 2023-06-24 11:40:50.524 | info | find by ip: false
mediola-gateway.0 | 2023-06-24 11:40:50.523 | info | find by mac: undefined
mediola-gateway.0 | 2023-06-24 11:40:50.523 | info | auto detection: false
mediola-gateway.0 | 2023-06-24 11:40:50.510 | info | starting. Version 0.1.4 (non-npm: oelison/ioBroker.mediola-gateway#fb5fd6f1616e90339decbca7407c144d340d177a) in /opt/iobroker/node_modules/iobroker.mediola-gateway, node: v19.9.0, js-controller: 4.0.24

**Comment by Keulehd** [comment]
Sämtliche Einstellungen versucht. IP findet er wohl jedoch das Device nicht

mediola-gateway.0 | 2023-06-24 11:48:32.175 | error | unkown device on this port
mediola-gateway.0 | 2023-06-24 11:48:32.103 | info | with ip: 192.168.100.153
mediola-gateway.0 | 2023-06-24 11:48:32.103 | info | find by ip: true
mediola-gateway.0 | 2023-06-24 11:48:32.102 | info | find by mac: undefined
mediola-gateway.0 | 2023-06-24 11:48:32.102 | info | auto detection: false
mediola-gateway.0 | 2023-06-24 11:48:32.089 | info | starting. Version 0.1.4 (non-npm: oelison/ioBroker.mediola-gateway#fb5fd6f1616e90339decbca7407c144d340d177a) in /opt/iobroker/node_modules/iobroker.mediola-gateway, node: v19.9.0, js-controller: 4.0.24

**Comment by mcm1957** [comment]
Danke f d Info.

**Comment by oelison** [comment]
Schade das ich kein Gateway v6 habe. Dadurch kann ich den Fehler nicht nachvollziehen. Es sollte aber mit dem Adapter durch Erweiterung gehen. Wenn nur ein Gatway im Netzwerk ist, bitte Auto verwenden, nicht die IP und auch nicht MAC-Adresse.

**Comment by Keulehd** [comment]
Ja sehr schade. Also alles rausgenommen und nur der Haken bei "Automatische Erkennung" gesetzt. Adapter bleibt gelb und folgendes steht im LOG:

**mediola-gateway.0 | 2023-06-24 14:04:01.768 | error | unkown device on this port**
mediola-gateway.0 | 2023-06-24 14:04:01.754 | info | auto detection: true
mediola-gateway.0 | 2023-06-24 14:04:01.742 | info | starting. Version 0.1.4 (non-npm: oelison/ioBroker.mediola-gateway#fb5fd6f1616e90339decbca7407c144d340d177a) in /opt/iobroker/node_modules/iobroker.mediola-gateway, node: v19.9.0, js-controller: 4.0.24
host.HomeServer | 2023-06-24 14:04:01.048 | info | instance system.adapter.mediola-gateway.0 started with pid 63426
host.HomeServer | 2023-06-24 14:04:00.954 | info | "system.adapter.mediola-gateway.0" enabled

**Comment by oelison** [comment]
Ich habe einen branch angelegt um mehr daten ins info log zu bringen. Ich werde das als debug ausgaben im hauptadapter später übernehmen. @Keulehd Bitte über diesen Link im Expertenmodus installieren
https://github.com/oelison/ioBroker.mediola-gateway/tree/more_info

**Comment by oelison** [comment]
Erwartete Ausgabe:
2023-06-24 16:57:31.119  - info: mediola-gateway.0 (19516) DHCP:FALSE
2023-06-24 16:57:31.119  - info: mediola-gateway.0 (19516) IP:123.123.123.123
2023-06-24 16:57:31.119  - info: mediola-gateway.0 (19516) SN:255.255.255.0
2023-06-24 16:57:31.119  - info: mediola-gateway.0 (19516) GW:123.123.123.123
2023-06-24 16:57:31.119  - info: mediola-gateway.0 (19516) DNS:123.123.123.123
2023-06-24 16:57:31.120  - info: mediola-gateway.0 (19516) MAC:11-11-11-11-11-11
2023-06-24 16:57:31.120  - info: mediola-gateway.0 (19516) HWV:F9
2023-06-24 16:57:31.120  - info: mediola-gateway.0 (19516) VER:3.4.7
2023-06-24 16:57:31.120  - info: mediola-gateway.0 (19516) RFV:0209
2023-06-24 16:57:31.121  - info: mediola-gateway.0 (19516) RFF:0347
2023-06-24 16:57:31.121  - info: mediola-gateway.0 (19516) RFM:0d
2023-06-24 16:57:31.121  - info: mediola-gateway.0 (19516) EID:01
2023-06-24 16:57:31.121  - info: mediola-gateway.0 (19516) FF:11
2023-06-24 16:57:31.121  - info: mediola-gateway.0 (19516) TZ:21
2023-06-24 16:57:31.122  - info: mediola-gateway.0 (19516) NAME:AIO GATEWAY
2023-06-24 16:57:31.122  - info: mediola-gateway.0 (19516) VID:FFFF
2023-06-24 16:57:31.122  - info: mediola-gateway.0 (19516)

**Comment by Keulehd** [comment]
mediola-gateway.0 | 2023-06-24 17:13:01.780 | error | unkown device on this port
mediola-gateway.0 | 2023-06-24 17:13:01.779 | info |  
mediola-gateway.0 | 2023-06-24 17:13:01.779 | info | NAME:WIR-CONNECT V6
mediola-gateway.0 | 2023-06-24 17:13:01.779 | info | MAC:40-66-7a-00-86-d4
mediola-gateway.0 | 2023-06-24 17:13:01.779 | info | DNS:192.168.100.9
mediola-gateway.0 | 2023-06-24 17:13:01.778 | info | GW:192.168.100.9
mediola-gateway.0 | 2023-06-24 17:13:01.778 | info | SN:255.255.255.0
mediola-gateway.0 | 2023-06-24 17:13:01.778 | info | IP:192.168.100.153
mediola-gateway.0 | 2023-06-24 17:13:01.777 | info | VID:000A
mediola-gateway.0 | 2023-06-24 17:13:01.777 | info | VER:1.16.0
mediola-gateway.0 | 2023-06-24 17:13:01.777 | info | HWV:C3
mediola-gateway.0 | 2023-06-24 17:13:01.776 | info | DHCP:TRUE
mediola-gateway.0 | 2023-06-24 17:13:01.666 | info | auto detection: true
mediola-gateway.0 | 2023-06-24 17:13:01.651 | info | starting. Version 0.1.4 (non-npm: oelison/ioBroker.mediola-gateway#more_info) in /opt/iobroker/node_modules/iobroker.mediola-gateway, node: v19.9.0, js-controller: 4.0.24

![Adaptereinstellungen](https://github.com/ioBroker/AdapterRequests/assets/136313097/75537689-71de-4e5b-b5d0-1d6d58e0034b)

Adapter bleibt weiterhin gelb aber mehr LOG-Einträge als vorher. Vielen Dank für die Mühen.

**Comment by oelison** [comment]
Ich habe das Grät jetzt in dem Test branch hinzugefügt. Mal sehen was passiert.

**Comment by Keulehd** [comment]
Gibt es schon neue Erkenntnisse ? Danke und schönen Sonntag

**Comment by oelison** [comment]
@Keulehd 🤔 ich dachte Du/Sie v installieren den Testbranch nochmal und dann sollte das Gerät erkannt werden. Dann auf die Variablen schreiben und es sollte gehen?!

**Comment by Keulehd** [comment]
Du ist völlig o.k. :-) Sorry das habe ich falsch verstanden. Versuche es gleich

**Comment by Keulehd** [comment]
Du ist völlig o.k. :-)
Gute Nachrichten: Adapter läuft und ist grün. Auch in den Objekten ist er drin. Aber die Rollläden fehlen. Im Log steht nach Starten des Adapters folgendes:

mediola-gateway.0
2023-07-09 19:00:47.989	error	TypeError: res.data.startsWith is not a function

mediola-gateway.0
2023-07-09 19:00:47.989	error	mediola device not reached by getting sys vars

mediola-gateway.0
2023-07-09 19:00:47.953	info	Mediola connected with ip:192.168.100.153 and mac:40-66-7a-00-86-d4

mediola-gateway.0
2023-07-09 19:00:47.953	info	

mediola-gateway.0
2023-07-09 19:00:47.952	info	NAME:WIR-CONNECT V6

mediola-gateway.0
2023-07-09 19:00:47.952	info	MAC:40-66-7a-00-86-d4

mediola-gateway.0
2023-07-09 19:00:47.952	info	DNS:192.168.100.9

mediola-gateway.0
2023-07-09 19:00:47.952	info	GW:192.168.100.9

mediola-gateway.0
2023-07-09 19:00:47.952	info	SN:255.255.255.0

mediola-gateway.0
2023-07-09 19:00:47.952	info	IP:192.168.100.153

mediola-gateway.0
2023-07-09 19:00:47.952	info	VID:000A

mediola-gateway.0
2023-07-09 19:00:47.952	info	VER:1.16.0

mediola-gateway.0
2023-07-09 19:00:47.951	info	HWV:C3

mediola-gateway.0
2023-07-09 19:00:47.951	info	DHCP:TRUE

mediola-gateway.0
2023-07-09 19:00:47.859	info	auto detection: true

mediola-gateway.0
2023-07-09 19:00:47.845	info	starting. Version 0.1.4 (non-npm: oelison/ioBroker.mediola-gateway#more_info) in /opt/iobroker/node_modules/iobroker.mediola-gateway, node: v19.9.0, js-controller: 4.0.24
host.HomeServer

Ich hoffe das hilft uns jetzt etwas weiter. Vielen Dank für die Mühe :-)

**Comment by oelison** [comment]
Schaue mir das später genauer an. Danke für den Test.

**Comment by Keulehd** [comment]
<img width="1058" alt="image" src="https://github.com/ioBroker/AdapterRequests/assets/136313097/99987949-07a8-469e-aaa6-aa5abb8c4a25">

**Comment by Keulehd** [comment]
Konntest schon mal drüberschauen ?

**Comment by oelison** [comment]
@Keulehd Ja. Leider weiß ich nicht wie die WIR geräte angesteuert werden. Wie wird das denn gemacht mit den Hauseigenen Apps von WIR? Zur not brauche ich einen WireShark mittschnitt. Geht das?
In der API von Mediola heruntergeladen (mit Anmeldung und so) steht nichts über die Rolläden von WIR drin.

**Comment by Keulehd** [comment]
Ja kein Problem (hoffe ich). Ich hab jetzt WireShark 4.0.7 installiert bin jedoch mit der Bedienung etwas überfordert. Kannst Du mit da Hilfestellung geben was ich Einstellen/Konfigurieren/Starten/usw muss ?

<img width="653" alt="image" src="https://github.com/ioBroker/AdapterRequests/assets/136313097/fb64783c-3960-4015-b2a8-ccb4601992f8">

**Comment by oelison** [comment]
Schreib mir mal eine PM and die Mail vom Adapter readme, wenn Du Lust hast.

**Comment by Keulehd** [comment]
Selbst das finde ich nicht. Hilf mir mal bitte :-(

**Comment by oelison** [comment]
@Keulehd Ganz unten auf der Seite: https://github.com/oelison/ioBroker.mediola-gateway/

**Comment by Keulehd** [comment]
Danke sollte geklappt haben. Nachricht ist raus

**Comment by mcm1957** [comment]
Wird als Erweiterung des mediola gateway behandelt.
