### ISSUE TITLE
Eigene Objekte verwalten

### ISSUE THREAD

**Issue by vr6syncro** [ioBroker/AdapterRequests#85]
Ich würde einen Adapter gut finden in dem man seine selbst erstellen Objekte besser verwalten kann.

Ich habe einige selbst erstellte Objekte habe aber irgendwann den Überblick verloren welche ich selber erstellt habe.

Ich hatte vor einigen Tagen ein Problem mit dem js Adapter und habe den neu installiert. leider waren da alle meine selbst angelegten Objekte weg. Konnte es mit einem Backup fixen war aber sehr mühsam.

Möglichkeit eins wäre alle selbst erstellten Objekte in einem JS zu speichern so das man diese so leicht wiederherstellen kann.

Möglichkeit zwei der Adapter. Man könnte ein neues Objekt über ein Button anlegen und dieses in einer Liste mit Beschreibung speichern. Sowie ein Import/Export.

**Comment by BuZZy1337** [comment]
Sehe hier keinen Bedarf für einen Adapter. Mach doch einen Unterordner "EigeneDPs" und nur in diesem Ordner legst du deine eigenen DPs an?

Organisation ist das A und O und zwar von Anfang an. :relaxed:

**Comment by Apollon77** [comment]
Und im Forum gibts auch ein Skript um States selbst zu sichern. Hilft ggf auch.
