### ISSUE TITLE
RENAC PV System hybrid inverter

### ISSUE THREAD

**Issue by Tigger86** [ioBroker/AdapterRequests#857]
Hello,
I would like to have an adapter for my PV system. 
It is from RENAC. [https://www.renacpower.com/](url)

unfortunately I do not know exactly what is needed.
Currently I have an app and in addition I can access it with a web interface.
if anything else is needed, please just write.
I have asked the company for an API. and have received documentation on how this works. 

[https://docdro.id/GuVhF4M](url)
I hope something can be done with it.

**Comment by raschy** [comment]
Stable since September 2024 in version 0.1.2.

**Comment by mcm1957** [comment]
Adapter Repo: https://github.com/raschy/ioBroker.renacidc
