### ISSUE TITLE
WEM Portal integrieren für anfänger/Integrate WEM Portal for beginners

### ISSUE THREAD

**Issue by mary-1220** [ioBroker/AdapterRequests#859]
englisch: 
Hey dear github community, I'm a complete beginner in the whole home assistant and IO broker topic.

I just installed Docker, Portainer and then Homeassistant on my Openmediavault server.
Now I'm about to integrate all my devices.
Starting with my Weißhaupt heater, can any of you give me precise installation instructions? Since I can't make sense of all of this :/
I would be super excited as I think Homeassistant could be a huge asset to my whole family.

German:
Hey liebe github community, ich bin ein kompletter einsteiger in dem Ganzen Homeassistent und IO-Broker Thema. 

Ich habe mir vorhin auf meinen Openmediavault server, Docker, Portainer und danach Homeassistant installiert. 
Nun stehe ich davor all meine Geräte einzubinden. 
Angefangen mit meiner Weißhaupt Heitzung, kann mir von euch jemand eine genaue Installationsanleitung geben? Da ich aus all dem hier absolut nicht schlau werde :/
Ich würde mich super freuen, da ich denke dass Homeassistant eine Riesen Bereicherung für meine Ganze Familie sein könnte.

**Comment by mcm1957** [comment]
Dear Mary,

First of all homeassistent and ioBroker are two different systems.
Information about homeassistent should be availbale at their homepage: https://www.home-assistant.io/
Information about ioBroker is available at https://www.iobroker.net/ and/ or at the iobroker user forum 
https://forum.iobroker.net/

This repository is dedicated to requests for new ioBroker adapters.

I will close here. Please use one of the resources mentioned above.
