### ISSUE TITLE
Heishamon verursacht den Fehler H43 in der Wärmepumpe

### ISSUE THREAD

**Issue by BennyNeumann** [ioBroker/AdapterRequests#861]
Hallo zusammen,
ich habe das Problem, das das Heishamon Modul in der t-CAP H den Fehler H43 (Fühler Heizkreis 1) auslöst und Heizkreis 2 mit 0°C angezeigt wird. Ziehe ich das Modul ab, arbeiten beide Fühler fehlerfrei.  Das Panasonic Interface CZ-TAW1 ist nicht angeschlossen, die Zusatzplatine CZ-NS4P ist verbaut. Ist dieses Problem bekannt und kann mir jemand sagen wie ich es abstellen kann?

Vielen Dank
Benny

**Comment by aruttkamp** [comment]
Das gehört eher zum Adapter als hier zu den Adapter Wünschen ;-)

**Comment by BennyNeumann** [comment]
Wie verschiebe ich das denn?

**Comment by aruttkamp** [comment]
gar nicht. gehst auf die Seite des Adapters ( ich finde nix mit Heishamon ) und dort auf Issues ... da gehört es hin. 
Ist es denn ein ioBroker Adapter ?

**Comment by mcm1957** [comment]
Geht es hier um einen ioBroker adapter? Wenn ja welchen.

Ev. gehört das ja zu dieser Software: https://github.com/Egyras/HeishaMon

Nur das scheint mal nichts mit ioBroker zu tun zu haben.
Und es ist defeinitiv kein Wunsch nach einem neuen Adapter.

Ergo - hier bist du falsch.
