### ISSUE TITLE
SolisMon3 or other Datalogger connection to Solis Inverter

### ISSUE THREAD

**Issue by schorges** [ioBroker/AdapterRequests#864]
SolisMon3

search for SolisMon3, its avail for HomeMatic
it's directly connect to Solis datalogger Sticks via MODBUS over Ethernet/WLAN

https://github.com/NosIreland/solismon3

or other :
https://github.com/fboundy/ha_solis_modbus

**Comment by mcm1957** [comment]
Please add link to device / manufactorer.

At a first look this dece serems to have a modbus interface. Did youvtry standard modbus adapter?

**Comment by schorges** [comment]
With the Standart Modbus Adapter it works.
But you cannot communicate with your SolisCloud simultaneous, [HERE](https://github.com/fboundy/ha_solis_modbus/issues/4)
only with spezial Waveshare RS485 Hardware directly to the Inverter.

Alternativ is a API to the SolisCloud to get Data and Set Data.
For HomeAssist can found [HERE](https://github.com/hultenvp/solis-sensor/tree/master)

**Comment by Trixx34** [comment]
If API access is OK check my new adapter: 

https://forum.iobroker.net/topic/69026/new-adapter-soliscloud
https://github.com/Trixx34/ioBroker.SolisCloud

**Comment by alienatedsec** [comment]
> With the Standart Modbus Adapter it works.
> 
> But you cannot communicate with your SolisCloud simultaneous 
> 
> [HERE](https://github.com/fboundy/ha_solis_modbus/issues/4)
> 
> only with spezial Waveshare RS485 Hardware directly to the Inverter.
> 
> On Read Modbus over the Datalogger Stick, in my case S2-WL-ST with TCP-Modbus
> 
> as Master, this shows Offline(LAN) and deactivate the SolisConnection.
> 
> 
> 
> Alternativ is a API to the SolisCloud to get Data and Set Data.
> 
> For HomeAssist can found [HERE](https://github.com/hultenvp/solis-sensor/tree/master)
> 
> but unfortunately not for ioBroker available 

Thanks for referencing my comment @schorges 

Shortly after that, I designed my own solution that has both SolisCloud and Home Assistant

Details here https://github.com/alienatedsec/solis-ha-modbus-cloud

**Comment by mcm1957** [comment]
adapter soliscloud released to latest

https://github.com/Trixx34/ioBroker.soliscloud
