### ISSUE TITLE
Make schedules available in Shelly adapter (Shelly Plus2PM, cover mode)

### ISSUE THREAD

**Issue by Icebear-DEU** [ioBroker/AdapterRequests#867]
**What kind of device or service would you like to see an adapter for?**
Shelly Plus2PM

**Is the device connected to the internet or only available on a local network?**
Device is connected to the Internet.

**Is an official App or Website available?**
https://www.shelly.com/de

**Is an official API including documentation available?**
https://shelly-api-docs.shelly.cloud/

**Are other libraries for an integration available?**
https://github.com/iobroker-community-adapters/ioBroker.shelly

**Same request posted here:**
https://github.com/iobroker-community-adapters/ioBroker.shelly/issues/841

**Additional context**
I like to check if the configured schedules in the Shelly are enabled or not. The current adapter does not provide any information on this topic.
Ideally, I would see:
a. how many schedules have been configured
b. which ones are enabled
c. the content/configuration of the schedule
and I would like to be able to change these values if needed. Creation of a new schedule is optional.

**Comment by mcm1957** [comment]
As this is feature request for the shelly adapter it can be processed by the existing issue https://github.com/iobroker-community-adapters/ioBroker.shelly/issues/841. Theres no need for a new adapter,
