### ISSUE TITLE
Alpha2 Möhlenhoff 

### ISSUE THREAD

**Issue by Eisbaeeer** [ioBroker/AdapterRequests#88]
Ich werde einen Neubau mit einer Alpha 2 von Möhlenhoff realisieren. Bei der API handelt es sich um eine offene XML-Api. Über CuXD und die CCU ist sie bereits ansteuerbar. Jedoch möchte ich die Einbindung direkt in iobroker realisieren. Infos: https://www.moehlenhoff.de/index.php?option=com_content&view=article&id=114&Itemid=116
Das System ist als Bussystem, sowie als Funksystem verfügbar. Eine Teststellung für die Programmierung ist bereits unterwegs.
Forum: https://forum.iobroker.net/viewtopic.php?f=24&t=2212&p=156698&hilit=alpha2#p156698

**Comment by Eisbaeeer** [comment]
Adapter ist in testing phase. 
ioBroker.alpha2

**Comment by Apollon77** [comment]
Cool, super
