### ISSUE TITLE
sma-speedwire

### ISSUE THREAD

**Issue by Trunks1982** [ioBroker/AdapterRequests#883]
Hallo hat vielleicht einer Zeit und wäre bereit diesen Adapter auf den neusten stand zubringen also auf neuste node.js usw?

https://github.com/AttackStrawbery/ioBroker.sma-speedwire

Gruß Christoph

**Comment by rg-engineering** [comment]
Habe mal ein wenig mit der alten Version des Adapters gespielt.
Unter
https://github.com/rg-engineering/ioBroker.sma-speedwire
habe ich eine aktualisierte Version, die zumindest bei mir so halbwegs läuft.
Ich denke, da müsste man noch etwas mehr Zeit investieren, damit das ganze rund wird.
Bin mir nur nicht sicher, ob das sinnvoll ist, da die meisten SMA Wechselrichter mittlerweile per Modbus o.ä. bedienbar sind...

**Comment by Trunks1982** [comment]
Ich hab richtige Probleme mit meinem SBS über Modbus.Immer wieder Error und nach ca 24std bricht die Modbusverbindung ab.Muss dann einmal die Modbus Schnittstelle Resetten. Wollte halt mal gucken ob es hier mit besser. wird und nicht mehr vorkommt.

**Comment by Trunks1982** [comment]
Verbindung klappt schonmal liest auch Daten aus.Weiß nur nicht was hier für ein update Intervall eingestellt ist.

**Comment by rg-engineering** [comment]
aktuell fix 5 Minuten, ist eines der to do's das einstellbar zu machen...

**Comment by Trunks1982** [comment]
Ah du bist nen Schatz!😘

**Comment by Trunks1982** [comment]
> aktuell fix 5 Minuten, ist eines der to do's das einstellbar zu machen...

Kann ich dir irgendwie zuarbeiten für die Werte die er abfragen soll zb beim SBS?Müsste nur wissen wie ich die mit dem Browser Entwickler Tool finde.Dann suche ich die raus.

**Comment by rg-engineering** [comment]
Welche Werte vermisst du? Bei mir aktualisiert ein SBS 2.5 die Daten...
Wir können auch in issue [hier](https://github.com/rg-engineering/ioBroker.sma-speedwire/issues) öffnen

**Comment by mcm1957** [comment]
Bitte Fragen zu einem konkreten, existierenden Adapter im Adapter repo stellen / bearbeiten - wie rg-engineering richtiger Weise schon verlinkt hat.

@rg-engineering 
Da du offensichtlich Arbeit inverstiert ahst - DANKE - ein paar Fragen:
- hast du oder sonst wer versucht den originalen Dev zu kontaktieren?
- hast du "Lust" den Adapter zu übernehmen und zu warten?
- und da der Adapter nicht in den Repos zu sein scheint, hast du Lust dies zu veranlassen und ggF die notwendigen Apassungen vorzunehmen?

**Comment by rg-engineering** [comment]
@mcm1957 Bin mir nicht sicher, ob es sinnvoll ist, den Adapter weiter zu verfolgen. Es gibt [sbfspot](https://github.com/SBFspot/SBFspot), wo SpeedWire von SMA komplett supported wird. Eine Integration von sbfspot in ioBroker ist per [sbfspot-Adapter](https://github.com/rg-engineering/ioBroker.sbfspot) oder direkt über MQTT möglich. Neue SMA-Wechselrichter sprechen von Hause aus modbus, sind also so einfach in ioBroker zu integrieren...

**Comment by Trunks1982** [comment]
Mich würde es freuen weil ich wie gesagt übelste probleme beim SBS mitModbus habe.
Klar ich könnte auch den HVS Batterie Adapter nutzen aber da stimmen die Werte zum SBS nicht weil noch keine Verluste mit drin sind.

**Comment by mcm1957** [comment]
> @mcm1957 Bin mir nicht sicher, ob es sinnvoll ist, den Adapter weiter zu verfolgen. Es gibt [sbfspot](https://github.com/SBFspot/SBFspot), wo SpeedWire von SMA komplett supported wird. Eine Integration von sbfspot in ioBroker ist per [sbfspot-Adapter](https://github.com/rg-engineering/ioBroker.sbfspot) oder direkt über MQTT möglich. Neue SMA-Wechselrichter sprechen von Hause aus modbus, sind also so einfach in ioBroker zu integrieren...

OK - danke für die Info.

Ich setz das dann mal auf revamp, wenns sich jeamdn den Adapter ansehen will, ist es mir / uns natürlich recht.
Ansionsten seh ich auch modbus als primären Weg. Wenn es mit Modbus Probleme gibt, dann kann / sollte man - sofern nicht bereits erfolgt - die Probleme im Umfeld des Modbus Adapters (Issue bzw. Forum) versuchen zu klären.

**Comment by mcm1957** [comment]
Siehe: https://github.com/ioBroker/AdapterRequests/issues/883#issuecomment-1817589205

Eine Integration von sbfspot in ioBroker ist per [sbfspot-Adapter](https://github.com/rg-engineering/ioBroker.sbfspot) oder direkt über MQTT möglich. Neue SMA-Wechselrichter sprechen von Hause aus modbus, sind also so einfach in ioBroker zu integrieren...

Eine Überarbeitung des Adapters erscheint nicht sinnvoll.

Eine GH only / Alpha Version ist hier zu finden:
https://github.com/rg-engineering/ioBroker.sma-speedwire
