### ISSUE TITLE
PiHole 6

### ISSUE THREAD

**Issue by Rudi-Ment** [ioBroker/AdapterRequests#887]
Für die neue PI-Hole 6 Version

Erreichbar über API-Schnittstelle

Aktuell im Beta-Stadium

**Comment by mcm1957** [comment]
Wie ist dieser Request zu verstehen?

Soll das eine Info über einen neuen Adapter sein? (Warum ein neuer Adapter?)
Wird ein neuer Adapter gewunschen? (Warum? Ist existierender Adapter nicht erweiterbar?)
Wird eine Adaptierung des existierenden Adapters gewunschen?

Bitte ein paar Infos mehr bzw. ein paar Klarstellungen.

**Comment by DutchmanNL** [comment]
@Rudi-Ment ?

**Comment by mcm1957** [comment]
I've created a issue at adapter pihole
https://github.com/unltdnetworx/ioBroker.pi-hole/issues/56

Depending in the target of this issue and eventually resppnsed there please open a ne issue if creation of a new adapter (or revamping the xisting) is required.
