### ISSUE TITLE
Dreame L20 Ultra Complete

### ISSUE THREAD

**Issue by Tommy1172** [ioBroker/AdapterRequests#890]
Hallo Leute,
ich möchte all den Programmierern hier mein Lob aussprechen.
Es ist wirklich erstaunlich was Ihr hier Leistet.
Ich habe mir vor ein Paar Tagen den Dream L20 Ultra Complete Gekauft ein Geiles Gerät wirklich
kann ich nur empfehlen. Leider gibt es noch nichts um diesen in Iobroker einzubinden.
Hat das jemand auf der Liste. ????
Kann hier jemand vielleicht helfen?????

Ich würde mich sehr über eine Antwort freuen.

LG Tommy

**Comment by mcm1957** [comment]
An sich scheinen die DREME Geräte mit dem ioBroker.mihome-vacuum Adapter angebunden zu werden.
https://github.com/iobroker-community-adapters/ioBroker.mihome-vacuum

Konkret havbe ich dein Modell dort nicht gesehen, Ich rate dir im Forum (forum.iobroker.net) mal nachzufragen (Da gibts sicher einen Thread zum Adapter) und / oder einen Feature Request im Adapter Repository zu stellen wenn er nicht supporte ist. 

Da mit an Sicherheit grenzender Wahrscheinlcihkeit kein neuer Adapter erforderlich ist, schließe ich hier.

**Comment by mcm1957** [comment]
> https://forum.iobroker.net/topic/59636/test-adapter-mihome-cloud

Danke TA2k 
Hatte den leider nicht im Kopf. Sorry.

**Comment by Tommy1172** [comment]
Hallo, 
erst mal vielen Dank für deine Antwort. Aber der adapter mihome cloud  bringt hier gar nichts.
In der App Xiaomi Home ist mein Gerät nicht zu finden und somit nicht ein zufügen.
Unter dem ioBroker.mihome-vacuum Adapter auch nicht.
Beide Adapter bringen nichts.  
Ich denke das der Adapter gehen würde wenn er die Neue App benutzen würde die für mein Model bereit gestellt worden ist. Dieses ist die Dream Home App unter den anderen Apps denke ich wird es keinen Nachtrag des Neuen Gerätes geben, warum eine Neue App machen und die alte auf dem Neusten Stand halten dann brauche ich auch keine Neue App.
Vielleicht wäre nur der App Wechsel Nötig, das der Adapter für mein Gerät geht. Aber Ihr seit die Profis nicht ich. 
Ich freue mich auf euere Antworten. 

LG Tommy

**Comment by mcm1957** [comment]
Ich würde dir raten, das Thema im FORUM zu thematisieren (forum.iobroker.net). Ev. kriegst du dort rascher eine Antwort ob es mit einer Erweiterung der existierenden Adapter möglich sein sollte bzw. ist.

**Comment by Tommy1172** [comment]
Ich danke dir für deine Hilfe und Ratschläge.
Werde es gleich ausprobieren vielleicht klappt´s ja. 
Vielen Dank 
LG Tommy
