### ISSUE TITLE
Aqara hub Adapter

### ISSUE THREAD

**Issue by EDWIN9000** [ioBroker/AdapterRequests#891]
**Adapter for Aqara Zigbee adapter **

https://www.aqara.com/en/product/hub/

It has the best Zigbee motion detectors (battery) on the market (2023 see reviews in internet)
**connected local and internet**

**official App or Website available , see above , apps for iPhone and Android , see "Aqara Home" at webstore and Google play**

**Is an official API including documentation available?**
?

**Are other libraries for an integration available?**
Ideally in JavaScript/npm, but also other programming languages are interesting, add links please
?

**Is this device already integrated in other Smart Home systems?**
Add links please: it is recognized in Aqara Hine and automatically in HomeKit

**Is this device already integrated in homebridge? Might the ham adapter in combination with the homebridge plugin be sufficient?**
Edit think: no

**Additional context**
Add any other context or screenshots about the feature request here. If the topic was discussed on the ioBroker forum, please include the link too.

After you create the issue, please vote for yourself in the first post of the issue using the "+1"/"Thumbs up" button

**Comment by mcm1957** [comment]
Ref: https://forum.iobroker.net/topic/40517/aqara-hub-v3-gateway/20

**Comment by DEV2DEV-DE** [comment]
Aqara hardware can be perfectly managed via ZigBee.
For this reason, I deactivated the hub and paired the components with the ZigBeee adapter.
I use the Yahka adapter to connect the devices with HomeKit.

**Comment by EDWIN9000** [comment]
The same for me: Aqara adapter not required anymore. The Zigbee adapter ( together with my cheap SONOFF Zigbee 3.0 USB Dongle Plus Gateway Universal Zigbee ) fulfills all my requirements. I tested Aqara motion sensors and plugs).

**Comment by mcm1957** [comment]
So I will close here.
Thanks for feedback.
