### ISSUE TITLE
Adapter für Weatherlink

### ISSUE THREAD

**Issue by stefan7201** [ioBroker/AdapterRequests#892]
würde einen Adapter für Weatherlink brauchen um die Daten meiner Davis Wetterstation auszulesen und in ioBroker darzustellen

**Comment by mcm1957** [comment]
Please fill the template:

**What kind of device or service would you like to see an adapter for?**
Add name and company of the device, including links to the device and any additional information[...]

**Is the device connected to the internet or only available on a local network?**

**Is an official App or Website available?**
If yes, please add links

**Is an official API including documentation available?**
If yes, please add links and information[...]

**Are other libraries for an integration available?**
Ideally in JavaScript/npm, but also other programming languages are interesting, add links please

**Is this device already integrated in other Smart Home systems?**
Add links please

**Is this device already integrated in homebridge? Might the ham adapter in combination with the homebridge plugin be sufficient?**
Please try it and add results

**Additional context**
Add any other context or screenshots about the feature request here. If the topic was discussed on the ioBroker forum, please include the link too.

After you create the issue, please vote for yourself in the first post of the issue using the "+1"/"Thumbs up" button

**Comment by mcm1957** [comment]
In addition - iof the weatherstation can use wunderground or ecowitt protocall you might check sainlogic adapter

**Comment by stefan7201** [comment]
@mcm1957  sainlogic Adapter funktioniert leider nicht trotzdem danke für den Tipp

**Comment by stefan7201** [comment]
> Please fill the template:
> 
> **What kind of device or service would you like to see an adapter for?** Add name and company of the device, including links to the device and any additional information[...]

### **https://www.davisinstruments.com/pages/vantage-pro2>** 

> **Is the device connected to the internet or only available on a local network?**

### **_beides_**
> 
> **Is an official App or Website available?** If yes, please add links

### **_https://www.davisinstruments.com/pages/download-apps_**
> 
> **Is an official API including documentation available?** If yes, please add links and information[...]
> 
> **Are other libraries for an integration available?** Ideally in JavaScript/npm, but also other programming languages are interesting, add links please
> 
> **Is this device already integrated in other Smart Home systems?** Add links please
> 
> **Is this device already integrated in homebridge? Might the ham adapter in combination with the homebridge plugin be sufficient?** Please try it and add results
> 
> **Additional context** Add any other context or screenshots about the feature request here. If the topic was discussed on the ioBroker forum, please include the link too.
> 
> After you create the issue, please vote for yourself in the first post of the issue using the "+1"/"Thumbs up" button

**Comment by stefan7201** [comment]
habe es über den weathunderground adapter geschafft

**Comment by mcm1957** [comment]
Danke für Feedback
