### ISSUE TITLE
wiregurad只发送不接收求大神解惑

### ISSUE THREAD

**Issue by 2787913266** [ioBroker/AdapterRequests#895]
求解决办法
Sun Nov 05 21:39:45 GMT+08:00 2023
reguard.androi:Not starting debugger since process cani
Sun Nov 05 21:43:09 GMT+08:00 2023
WireGuard/Tunnellmporter: ***· 未找到配

Sun Nov 05 21:39:45 GMT+08:00 2023
reguard.androi:Not starting debugger since process can
Sun Nov 05 21:43:09 GMT+08:00 2023
WireGuard/Tunnellmporter: *******大·未找到配

**Comment by DutchmanNL** [comment]
this does not look like an adapter request, if you try to raise an issue for an existing adapter please do that at the repository of that adapter

**Comment by mcm1957** [comment]
Not sure what this request trys mention.

If you want to report a problem please open a issue at the tepoditory ofcghe efected adapter.

If you want to suggest a new adapter please fill out template.
