### ISSUE TITLE
LEDVANCE Smart+ WiFi Adapter

### ISSUE THREAD

**Issue by gidhap** [ioBroker/AdapterRequests#898]
As there is no working adapter to manage LEDVANCE WiFi bulbs, I tried tuya and smartthings w/o success, I am suggesting to build a dedicated adapter. The bulbs I am using are LEDVANCE Classic G95 100 E27 Tunable white.
Unfortunately I am not able to do the coding by myself, but I would be happy to donate a bulb or two and send them to the programmer spending his time on this adapter.
And... a big thank you to all the folks spending their time to make ioBroker better every day.

**Comment by gidhap** [comment]
Seems to be a [duplicate to ](https://github.com/ioBroker/AdapterRequests/issues/737) No. clue why I didn't find it before. sorry

**Comment by mcm1957** [comment]
https://github.com/ioBroker/AdapterRequests/issues/737
