### ISSUE TITLE
[CHECK] adapter VOLUMIO broken?

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/AdapterRequests#899]
Adapter VOLUMIO seems to be broken:

https://github.com/a-i-ks/ioBroker.volumio
https://forum.iobroker.net/topic/59939/volumio-adapter/11
https://github.com/ioBroker/AdapterRequests/issues/782

Adapter is listed at repositories - should be checked.

**Comment by DutchmanNL** [comment]
I don't see any issue at the adapter repository, first action would be to do that and see if the creator/maintainer acts on the issues

If not, we can verify if other devs are able to continue this development but before creating something new or raising an request first step is to have issue at the existing repository

**Comment by mcm1957** [comment]
see https://github.com/a-i-ks/ioBroker.volumio/issues/12
