### ISSUE TITLE
Bitron Home Adapter !

### ISSUE THREAD

**Issue by Smarti15** [ioBroker/AdapterRequests#90]
Hallo Jungs, könntet ihr bitte einen Adapter für Bitron Home Geräte programmieren? Hab hier noch Außensiren und Bitron Rauchmelder mit zusätzlicher Alarm-Funktion. DANKE!

**Comment by Apollon77** [comment]
Gibt es ein paar mehr Infos?
Link zum Hersteller? Technik? Schnittstellen die Verfügbar sind?

**Comment by Smarti15** [comment]
Also hier ist ein Link vom Hersteller:
http://www.bitronvideo.eu/index.php/loesungen/smart-home/

Einsetzen tu ich die Geräte grad über die Telekom Smarthome / Qivicon
Rauchmelder: https://www.smarthome.de/geraete/bitron-video-rauchmelder-v-2-weiss
Außensirene: https://www.smarthome.de/geraete/bitron-video-aussensirene-weiss

Puh Schnittstelle? Könnte damit Zigbee gemeinte sein? Also Funkstandard ist Zigbee. Ich musste dafür acuh extra einen USB Stick für Zigbee kaufen, der in der Homebase der Telekom steckt.  Wahrscheinlich ist es dann nicht so einfach umzusetzen oder? Danke aber trotzdem für eure Mühe!

**Comment by Smarti15** [comment]
Ok dann schau ich mir das mal an. Musste ich dazu den Zigbee Stick ins Tinker Board stecken oder simuliert der Adapter dann Zigbee?

**Comment by Apollon77** [comment]
Ist Zigbee oder Deconz nun eine Option? Kann das hier ertsmal zu?

**Comment by Smarti15** [comment]
Meld mich heute Abend dazu.

**Comment by Smarti15** [comment]
Ja das wird mit beiden nicht klappen, da ich Hardware zu kaufen muss. Dann kann ich auch gleich ne neue Aussensiren holen. Hab zwar nen ZigBee USB Stick, der in der Smarthome von Telekom steckt, aber ich nehme an, der wird nicht erkannt oder unterstützt.

**Comment by Apollon77** [comment]
Das weiß ich nicht. Müsstest du bei den beiden genannten Adaptern checken.

**Comment by Smarti15** [comment]
Ok. Na dann mach den Thread hier zu. Danke

**Comment by galegro** [comment]
Die Beiträge sind zwar schon alt, aber ich habe dieselben Anliegen. Als Schnittstelle verwende ich von Texas Instruments CC26X2R1 und den ZigBee-Adapter.

Meine Wünsche ..

Ich möchte die Außensirene 902010/29 mittels des ZigBee Adapters betreiben. Leider wird dieses Gerät noch gar nicht unterstützt.

Die Sirenen der bereits unterstützten Rauchmelder 902010/20 können als Signalgeber angesteuert werden. Leider wird dies noch nicht unterstützt.
