### ISSUE TITLE
vis integration for Shelly

### ISSUE THREAD

**Issue by Kollos2k** [ioBroker/AdapterRequests#911]
I started a adapter for integration the over mqtt submitted data into vis.

I use the data from the Shelly adapter for iobroker and interpret them automatically.

Currently I'm testing and learning how to do.

Visit Kollos2k/iobroker.vis-shelly for more info.

**Comment by mcm1957** [comment]
Repo: https://github.com/Kollos2k/ioBroker.vis-shelly

**Comment by mcm1957** [comment]
Repo:  https://github.com/Kollos2k/ioBroker.vis-2-shelly
https://github.com/ioBroker/ioBroker.repositories/pull/3384

**Comment by mcm1957** [comment]
Development of adapter seems to be stalled. 
Anyway we can close here as the request is handled by a dev
