### ISSUE TITLE
adapter for using gpio on tinkerboard like rpi2

### ISSUE THREAD

**Issue by smartboart** [ioBroker/AdapterRequests#92]
Hello , i would like to use the gpio pins from my tinkerboard..
This is not possible with the rpi2 adapter.. anybody here who would like to modify the rpi2 adapter that it will work with the tinkerboard?

**Comment by smartboart** [comment]
Mybe it has something to do with the GPIO Adresslist ( gpio readall ) see attached pictures...
I think that the adapter rpi2 reads the Table BCM Adresses, which are named CPU in Tinker board table...
The CPU Adresses are totally different to the BCM Adresse...
Is it possible to change this somewhere in the rpi2 code to make it work for tinkerboard?

If i can do something for you to make it happen, just let me know...i will do my best to help in this issue...

bild_2018_03_14 001
unbenannt

**Comment by raintonr** [comment]
It has been discussed that the RPI2 adapter could be forked, removing the RPi specific stuff and creating a generic SBC GPIO adapter. I am happy to do this, but...

... what this would need is a generic NodeJS module that can identify how many GPIO pins are available, etc. on each different board and allow them to be controlled. Using `sysfs` looks promising (see https://www.kernel.org/doc/Documentation/gpio/sysfs.txt). It's hard to believe a generic SBC GPIO module doesn't already exist though... needs a little more searching before re-inventing the wheel.

FWIW, `sysfs` reports 54 GPIO pins available on RPi as that is the actual number available on the BCM SoC but of course not all of these are physically available. For this reason the settings screen for any such generic GPIO adapter would likely need a `+` button to add GPIO number with options (input, output, pull up/down, etc) for that specific number in preference to a long list of available GPIO numbers, many of which would likely not be usable.

**Comment by mcm1957** [comment]
see tinker adapter

repo: https://github.com/simatec/ioBroker.tinker

**Comment by raintonr** [comment]
I still believe it would be more efficient to have a generic SBC GPIO adapter rather than trying to maintain a plethora of adapters that all do pretty much the same thing.

**Comment by mcm1957** [comment]
As this issue requests support for tinker board, an adapter for tinkerborad exist and hhe issue is ruther pld we can close here.

Please open a new issue if you encounter a problem or like to suggest a new feature at the adapter repository. 

@taintor
If nobissue for a genericxadapter exist feel free to create one  - or write this adaPter if you have sparetume
