### ISSUE TITLE
schoolfree Adapter for more countries - Schulferien Adapter für mehr Staaten (extend existing adapter schoolfrre?)

### ISSUE THREAD

**Issue by rtwl21** [ioBroker/AdapterRequests#921]
hier kann man von vielen Staaten die Schulferien per API abrufen.

https://www.openholidaysapi.org/de/

Schulferien gibt es aktuell leider nur für Deutschland.

wäre toll, wenn jemand Zeit und Lust hat für alle nicht-deutsche User diesen Adapter zu kreieren.

die Datenpunkt Struktur könnte wie bei dem aktuellen Feiertag Adapter sein.
Wichtig ist dabei ob heute oder morgen Schulferien sind.

**Comment by mcm1957** [comment]
Richtigerweise wurde diese Anforderung bereits bzw, auch als issue beim existierenden Adapetr schoolfree als feature Request eingestellt:

https://github.com/simatec/ioBroker.schoolfree/issues/248

**Bitte vor der Entwiklcung einen neuen, zusätzlichen Adapters unbedingt mit simatec Kontakt aufnehmen um vermeidbare und unerwünschte konkurrierende Adapter zu vermeiden,**

**Comment by simatec** [comment]
Steht mit auf der Todo für den Adapter schoolfree

**Comment by mcm1957** [comment]
Da dies als Feature Request  https://github.com/simatec/ioBroker.schoolfree/issues/248 existiert kann hier geschlossen wwerden.
