### ISSUE TITLE
HMIP Not Token generated

### ISSUE THREAD

**Issue by debian333** [ioBroker/AdapterRequests#933]
**What kind of device or service would you like to see an adapter for?**
Add name and company of the device, including links to the device and any additional information[...]

**Is the device connected to the internet or only available on a local network?**

**Is an official App or Website available?**
If yes, please add links

**Is an official API including documentation available?**
If yes, please add links and information[...]

**Are other libraries for an integration available?**
Ideally in JavaScript/npm, but also other programming languages are interesting, add links please

**Is this device already integrated in other Smart Home systems?**
Add links please

**Is this device already integrated in homebridge? Might the ham adapter in combination with the homebridge plugin be sufficient?**
Please try it and add results

**Additional context**
Add any other context or screenshots about the feature request here. If the topic was discussed on the ioBroker forum, please include the link too.

After you create the issue, please vote for yourself in the first post of the issue using the "+1"/"Thumbs up" button

**Comment by debian333** [comment]
In last App Version on Hometic Ip its not System PIN.Admin PIN it on Boar.
With Admin Pin can t not generated Token for This Adapter

**Comment by mcm1957** [comment]
Adapter ioBroker.hmip already exists, 

https://github.com/iobroker-community-adapters/ioBroker.hmip

This repository is menat to request NEW Adapters or major rewrites of deprectaed Adapters.
