### ISSUE TITLE
Navimow Rasenmähroboter i105e / i108e

### ISSUE THREAD

**Issue by surfer-09** [ioBroker/AdapterRequests#946]
**What kind of device or service would you like to see an adapter for?**
Mähen Starten/Stoppen
Statusabfrage des Mähfortschrittes
Statusanzeige Mähroboter

**Is the device connected to the internet or only available on a local network?**
Internes Netzwerk per WLAN, Firmware Updates werden aus dem Internet geladen

**Is an official App or Website available?**
Navimow App

Webseite: https://de.navimow.com/products/navimow-i-series-i105e-robot-mower-500?utm_source=google&utm_medium=cpc&utm_campaign=20240501_MS_DE_CV_Search_Brand&gad_source=1&gbraid=0AAAAA9fdSXLek6nICBuauf3DqvTW2tCmm&gclid=EAIaIQobChMIzp-12PDqhgMVLTkGAB1A-g_jEAAYASAAEgLlHvD_BwE

**Is an official API including documentation available?**
https://open.segwaydiscovery.com/documents/MAXDoc/#auth

**Comment by TA2k** [comment]
Not possible at the moment
https://github.com/TA2k/ioBroker.navimow

**Comment by mcm1957** [comment]
duplicate
see https://github.com/ioBroker/AdapterRequests/issues/868

**Comment by mf2105** [comment]
Fyi there is a Skill for Alexa now available
![Screenshot_2024-09-29-12-33-49-028_com amazon dee app](https://github.com/user-attachments/assets/03fa26ec-9a50-48a3-8741-cdd237536d0e)
