### ISSUE TITLE
Extend the scope of syntax check in iobroker script tab

### ISSUE THREAD

**Issue by Marty56** [ioBroker/AdapterRequests#95]
I am not sure whether it fits in here.

I would be great if the syntax checker of iobroker would not stop checking the syntax aber about 300-400 lines of code. I would prefer more than 1000 or if possible no real hard limit.

**Comment by GermanBluefox** [comment]
Have you tried 3.7.0?

сб, 14 июл. 2018 г., 8:10 Marty56 <notifications@github.com>:

**Comment by BuZZy1337** [comment]
Please open an issue for the Javascript adapter..
https://github.com/ioBroker/ioBroker.javascript/issues

Thank you. :relaxed:

**Comment by Marty56** [comment]
Thanks for the information. I was not aware that version 3.7.0 is addressing the issue above.

**Comment by Hypnos3** [comment]
3.7.0 is using a different editor with different syntax check and other functions like intellisense, ...
