### ISSUE TITLE
Backup Adapter

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/AdapterRequests#96]
Standard backup to:
* NAS
* FTP
* Dropbox
* GoogleDrive
* Some Private Clouds
* Schedule

**Comment by Apollon77** [comment]
Could https://forum.iobroker.net/viewtopic.php?t=15256 be a Basis

**Comment by GermanBluefox** [comment]
Could be, but....
All variable names in german. Names are not formatted (not camelCase)
Backup sctipt is shell. (only linux/darwin)
Structure of main.js is questionable too....
Messages to history are in german.

**Comment by simatec** [comment]
Thanks for the feedback. 
We can rewrite the variables in English if that is a problem. 
Since iobroker is stopped in some backup variants, I think the shell makes sense. so you can cover everything with it. 

Yes, currently it is designed for Linux systems. 
The majority certainly uses this variant. 
In the forum were virtually no requests for Windows. 

It would be very nice if the adapter can be included in the repo. 
many users have been asking for a backup solution for a long time.

 Greetings simatec

**Comment by GermanBluefox** [comment]
Backup adapter is really required.
Please rename all variables in English and make them camelcase starting
with lower case.
You can give the variables the International names and description like
{"en":  "Time", "de": "Zeit"}



пн, 16 июл. 2018 г., 21:42 simatec <notifications@github.com>:

**Comment by simatec** [comment]
Hello bluefox,

the variables and languages ​​are now all in English.

camelcase will also be adapted in the next few days.

The objects, Telgram messages and the history we will adapt in the next few days in English or translate

Best regards
simatec

**Comment by GermanBluefox** [comment]
I modified a bit your project. Please merge.
Still to do: 
- texts from main.js (like this one https://github.com/simatec/ioBroker.backitup/pull/8/files#diff-7a9076d6d94e62c13d641aa71f19ae8eR54) must be added to words.js
- Comments in main.js and backitup.sh should be in english too.

**Comment by simatec** [comment]
If I understand your changes correctly, all the translations that you have tagged with (// TODO translate) must be in the flat.txt or in the words.js.

Is it correct that way?

**Comment by GermanBluefox** [comment]
In the words.js

**Comment by Apollon77** [comment]
I think as a start it is great to have it at least for Linux ... then in a second step we can add windows support ...

**Comment by simatec** [comment]
The Windows support is also on our todo. There probably have to be installed in the Windows a few packages such as tar and wget later, but in principle, the Windows support is feasible

**Comment by GermanBluefox** [comment]
I would move the whole logic into JS and not in batch file.

вт, 17 июл. 2018 г. в 14:53, simatec <notifications@github.com>:

**Comment by simatec** [comment]
I see the stop of iobroker as a problem with some backup variants.
That's why we did it in a shell

**Comment by Apollon77** [comment]
I understand it more like instead of a shell script that you exec simply exec "node jsfile.js" process with the logic ... So have the logic in Javascript because then automatically possible cross-platform

**Comment by peoples0815** [comment]
But will a node Script still be executed if the iobroker is stopped before like it is the case with the complete backup?

**Comment by Apollon77** [comment]
How you start your shellscript? If it is started as a "child of iobroker process" then it will also be killed. So when you know how to start a separate process for the shell script then executing a new "node mybackup.js" is exactly the same and it will alsorun when ibroker process is gone.

it would be "just a plain node-js file"

**Comment by Apollon77** [comment]
can we close here and have backitup as "the backup adapter"?

**Comment by GermanBluefox** [comment]
We plan to normal release in the next week. Let it open.

**Comment by simatec** [comment]
We currently have a few small bugs. But next week everything should be ready

**Comment by GermanBluefox** [comment]
This can be closed.
https://github.com/simatec/ioBroker.backitup
