### ISSUE TITLE
Does someone need the Elero Centero USB Stick? Have one to sell from Austria.

### ISSUE THREAD

**Issue by DjGreg7Home** [ioBroker/AdapterRequests#960]
Does someone need the Elero Centero USB Stick? Have one to sell from Austria.

KR
Rok

_Originally posted by @mlinko6 in https://github.com/ioBroker/AdapterRequests/issues/60#issuecomment-1833210019_
            
yes I am looking and am also Germany Please contact me.

**Comment by mcm1957** [comment]
For MARKETPLACE postings see forum https://forum.iobroker.net
