### ISSUE TITLE
BeCool Air conditioner integration

### ISSUE THREAD

**Issue by jos896** [ioBroker/AdapterRequests#974]
Hi, I'm new. this is my first request.

i try to attach a BeCool airconditioner to iobroker by a suitable adapter.
iobroker don't identify the device even it's online by wifi and identified by ping.
The model-id is BC12SK2101QW. It can be operated by mobil via wifi and "Smartlife-Smarthome"-App.
I read on the net that at least in former times BeCool devices were integrated by the Tuya adapter.
But the adapter don't match to my device.

Threrfor i'm asking for advice how to attach it to iobroker.

Thanks in advance

**Comment by mcm1957** [comment]
This repository is dedicated to request the implementaion of a new adapter. I do not know whether some solution exists for BE COOL. In addition I do not know whether this device provides a documented api, is accessible using mqtt etc.

If you did not find any hint at https://download.iobroker.net/list.html and did not find a request within this repository I suggest to ask at our forum: https://forum.iobroker.net.

**If you want to request the creation of a new adapter, please create a new issue and fill in the template provided.** 

https://github.com/ioBroker/AdapterRequests/issues/new?assignees=&labels=Requested&projects=&template=adapter_requests.md&title=
