### ISSUE TITLE
ioBroker SmartThings adapter + Oven

### ISSUE THREAD

**Issue by sonny608** [ioBroker/AdapterRequests#976]
Hello. I’ve got installed SmartThings adapter on ioBroker and it’s controlling my Oven very well but….
Can I send to him mqtt command to for example turn of oven?
In the objects I see a boolen which, when clicked, fulfills the expectation, but when I send the "true" command to its address nothing happens
<img width="1129" alt="Zrzut ekranu 2024-11-26 o 09 44 59" src="https://github.com/user-attachments/assets/4d0df2dd-c31f-4603-88f8-e5f8b5068a8c">

**Comment by mcm1957** [comment]
This repository is dedicated to requests for new adapters.

Please open a topic at our forum (https://forum.iobrpoker.net) for general discussions or open a issue at the adapter repository (https://github.com/TA2k/ioBroker.smartthings) if you want tpo report a problem / bug or request an enhancement to this adapter.
